# (PART) Introduction to R {-} 

# Installing R & RStudio {#install}

If you have a Windows, Mac, or Linux operating system, you have several  ways in which you can begin working in R. Commonly, users install R on their computer along with an integrated development environment (IDE) software application like RStudio. Recently, RStudio Cloud (https://rstudio.cloud) has emerged as an alternative to installing R and RStudio by allowing users to use R and RStudio via the cloud, which notably allows those using the Google Chrome operating system to access R and RStudio. 

#### Video Tutorial
  
Link to video tutorial: https://youtu.be/b18IHQERT4A.

## Downloading & Installing R

In the following sections, you will learn how to download and install the R program for Windows and Mac operating systems. The base R program must be installed prior to installing the RStudio program. R is open-source software and free to download.

### For Windows Operation Systems

R can currently run under operating systems as old as Windows Vista (circa 2007). To download R for your Windows operating system for the first time, click on this link: https://cran.r-project.org/bin/windows/base/. Once you are on the R download page, click on the hyperlink to download the current version of R for Windows. Once the file has downloaded, follow the installation prompts.

### For Mac Operating Systems

The current version of R works with Mac OS X (release 10.6 and higher). To download R for Mac OS X operating system for the first time, click on this link: https://cran.r-project.org/bin/macosx/. If you have Mac OS X 10.11 or higher, click on the hyperlink (with .pkg extension) under the "Latest release" section to begin your download. If you have Mac OS X 10.10 or lower, click on the appropriate hyperlink (with .pkg extension) under the "Binaries for legacy OS X systems" section. Once the file has downloaded, follow the installation prompts.  
  
I don't advise using a Mac operating system that is older than Mac OS X 10.6 (which came out in 2009), as you may run into issues when using certain R packages for data analysis and visualization.

## Downloading & Installing RStudio

RStudio is not required to use R; however, RStudio offers a number of helpful features and a user-friendly interface. More specifically, RStudio is an integrated development environment (IDE) for R. The desktop version of RStudio is free to download. To do so, click on this link: https://rstudio.com/products/rstudio/download/#download.

1. Make sure that you have already installed the R program to your computer (see above).   
2. Click on the download button below the "RStudio Desktop" followed by the version number. Again, this version is free.   
3. Under the heading "Installers for Supported Platforms", click on the link that corresponds to your operating system.  
4. Once the file has downloaded, follow the installation prompts.

## Summary

In this chapter, we learned how to install R and RStudio for our Windows or Mac operating systems. 