<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 35 Estimating Criterion-Related Validity Using Correlation | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION</title>
  <meta name="description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 35 Estimating Criterion-Related Validity Using Correlation | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://rforhr.com" />
  <meta property="og:image" content="https://rforhr.comcover.png" />
  <meta property="og:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="github-repo" content="davidcaughlin/R-for-HR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 35 Estimating Criterion-Related Validity Using Correlation | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  
  <meta name="twitter:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="twitter:image" content="https://rforhr.comcover.png" />

<meta name="author" content="David E. Caughlin" />


<meta name="date" content="2021-12-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="disparateimpact.html"/>
<link rel="next" href="predictingcriterionscores.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for HR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#hragrowth"><i class="fa fa-check"></i><b>0.1</b> Growth of HR Analytics</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#skills-gap"><i class="fa fa-check"></i><b>0.2</b> Skills Gap</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#hraplc"><i class="fa fa-check"></i><b>0.3</b> Project Life Cycle Perspective</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#overview-of-hris-hr-analytics"><i class="fa fa-check"></i><b>0.4</b> Overview of HRIS &amp; HR Analytics</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#philosophy"><i class="fa fa-check"></i><b>0.5</b> My Philosophy for This Book</a>
<ul>
<li class="chapter" data-level="0.5.1" data-path="index.html"><a href="index.html#rationalerpref"><i class="fa fa-check"></i><b>0.5.1</b> Rationale for Using R</a></li>
<li class="chapter" data-level="0.5.2" data-path="index.html"><a href="index.html#audiencepref"><i class="fa fa-check"></i><b>0.5.2</b> Audience</a></li>
<li class="chapter" data-level="0.5.3" data-path="index.html"><a href="index.html#structurepref"><i class="fa fa-check"></i><b>0.5.3</b> Structure</a></li>
</ul></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#aboutauthor"><i class="fa fa-check"></i><b>0.6</b> About the Author</a></li>
<li class="chapter" data-level="0.7" data-path="index.html"><a href="index.html#acknowpref"><i class="fa fa-check"></i><b>0.7</b> Acknowledgements</a></li>
</ul></li>
<li class="part"><span><b>I HR Analytics Project Life Cycle</b></span></li>
<li class="chapter" data-level="1" data-path="overviewhraplc.html"><a href="overviewhraplc.html"><i class="fa fa-check"></i><b>1</b> Overview of HR Analytics Project Life Cycle</a></li>
<li class="chapter" data-level="2" data-path="questionformulation.html"><a href="questionformulation.html"><i class="fa fa-check"></i><b>2</b> Question Formulation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="questionformulation.html"><a href="questionformulation.html#adoptstrategicmindset"><i class="fa fa-check"></i><b>2.1</b> Adopting a Strategic Mindset</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="questionformulation.html"><a href="questionformulation.html#strategy"><i class="fa fa-check"></i><b>2.1.1</b> Strategy</a></li>
<li class="chapter" data-level="2.1.2" data-path="questionformulation.html"><a href="questionformulation.html#strategyformulation"><i class="fa fa-check"></i><b>2.1.2</b> Strategy Formulation</a></li>
<li class="chapter" data-level="2.1.3" data-path="questionformulation.html"><a href="questionformulation.html#strategyimplementation"><i class="fa fa-check"></i><b>2.1.3</b> Strategy Implementation</a></li>
<li class="chapter" data-level="2.1.4" data-path="questionformulation.html"><a href="questionformulation.html#strategichrm"><i class="fa fa-check"></i><b>2.1.4</b> Strategic Human Resource Management</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="questionformulation.html"><a href="questionformulation.html#defining-problems-formulating-questions"><i class="fa fa-check"></i><b>2.2</b> Defining Problems &amp; Formulating Questions</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="questionformulation.html"><a href="questionformulation.html#definingaproblem"><i class="fa fa-check"></i><b>2.2.1</b> Defining a Problem</a></li>
<li class="chapter" data-level="2.2.2" data-path="questionformulation.html"><a href="questionformulation.html#formulatingaquestion"><i class="fa fa-check"></i><b>2.2.2</b> Formulating a Question</a></li>
<li class="chapter" data-level="2.2.3" data-path="questionformulation.html"><a href="questionformulation.html#divergentconvergentthinking"><i class="fa fa-check"></i><b>2.2.3</b> Thinking Divergently &amp; Convergently</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="questionformulation.html"><a href="questionformulation.html#summary"><i class="fa fa-check"></i><b>2.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dataacquisition.html"><a href="dataacquisition.html"><i class="fa fa-check"></i><b>3</b> Data Acquisition</a>
<ul>
<li class="chapter" data-level="3.1" data-path="dataacquisition.html"><a href="dataacquisition.html#employee-surveys"><i class="fa fa-check"></i><b>3.1</b> Employee Surveys</a></li>
<li class="chapter" data-level="3.2" data-path="dataacquisition.html"><a href="dataacquisition.html#rating-forms"><i class="fa fa-check"></i><b>3.2</b> Rating Forms</a></li>
<li class="chapter" data-level="3.3" data-path="dataacquisition.html"><a href="dataacquisition.html#surveillance-monitoring"><i class="fa fa-check"></i><b>3.3</b> Surveillance &amp; Monitoring</a></li>
<li class="chapter" data-level="3.4" data-path="dataacquisition.html"><a href="dataacquisition.html#database-queries"><i class="fa fa-check"></i><b>3.4</b> Database Queries</a></li>
<li class="chapter" data-level="3.5" data-path="dataacquisition.html"><a href="dataacquisition.html#scraping"><i class="fa fa-check"></i><b>3.5</b> Scraping</a></li>
<li class="chapter" data-level="3.6" data-path="dataacquisition.html"><a href="dataacquisition.html#summary-1"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="datamanagement.html"><a href="datamanagement.html"><i class="fa fa-check"></i><b>4</b> Data Management</a>
<ul>
<li class="chapter" data-level="4.1" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_clean"><i class="fa fa-check"></i><b>4.1</b> Data Cleaning</a></li>
<li class="chapter" data-level="4.2" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_manipulate"><i class="fa fa-check"></i><b>4.2</b> Data Manipulation &amp; Structuring</a></li>
<li class="chapter" data-level="4.3" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_tools"><i class="fa fa-check"></i><b>4.3</b> Common Data-Management Tools</a></li>
<li class="chapter" data-level="4.4" data-path="datamanagement.html"><a href="datamanagement.html#summary-2"><i class="fa fa-check"></i><b>4.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dataanalysis.html"><a href="dataanalysis.html"><i class="fa fa-check"></i><b>5</b> Data Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="dataanalysis.html"><a href="dataanalysis.html#dataanalysis_toolstechniques"><i class="fa fa-check"></i><b>5.1</b> Tools &amp; Techniques</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="dataanalysis.html"><a href="dataanalysis.html#mathematics"><i class="fa fa-check"></i><b>5.1.1</b> Mathematics</a></li>
<li class="chapter" data-level="5.1.2" data-path="dataanalysis.html"><a href="dataanalysis.html#statistics"><i class="fa fa-check"></i><b>5.1.2</b> Statistics</a></li>
<li class="chapter" data-level="5.1.3" data-path="dataanalysis.html"><a href="dataanalysis.html#machinelearning"><i class="fa fa-check"></i><b>5.1.3</b> Machine Learning</a></li>
<li class="chapter" data-level="5.1.4" data-path="dataanalysis.html"><a href="dataanalysis.html#computationalmodelsimulation"><i class="fa fa-check"></i><b>5.1.4</b> Computational Modeling &amp; Simulations</a></li>
<li class="chapter" data-level="5.1.5" data-path="dataanalysis.html"><a href="dataanalysis.html#textqualitativeanalyses"><i class="fa fa-check"></i><b>5.1.5</b> Text Analyses &amp; Qualitative Analyses</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="dataanalysis.html"><a href="dataanalysis.html#continuum_dataanalytics"><i class="fa fa-check"></i><b>5.2</b> Continuum of Data Analytics</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="dataanalysis.html"><a href="dataanalysis.html#descriptive_analytics"><i class="fa fa-check"></i><b>5.2.1</b> Descriptive Analytics</a></li>
<li class="chapter" data-level="5.2.2" data-path="dataanalysis.html"><a href="dataanalysis.html#predictish_analytics"><i class="fa fa-check"></i><b>5.2.2</b> Predict-ish Analytics</a></li>
<li class="chapter" data-level="5.2.3" data-path="dataanalysis.html"><a href="dataanalysis.html#predictive_analytics"><i class="fa fa-check"></i><b>5.2.3</b> Predictive Analytics</a></li>
<li class="chapter" data-level="5.2.4" data-path="dataanalysis.html"><a href="dataanalysis.html#prescriptive_analytics"><i class="fa fa-check"></i><b>5.2.4</b> Prescriptive Analytics</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="dataanalysis.html"><a href="dataanalysis.html#summary-3"><i class="fa fa-check"></i><b>5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html"><i class="fa fa-check"></i><b>6</b> Data Interpretation &amp; Storytelling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#datainterpretation"><i class="fa fa-check"></i><b>6.1</b> Data Interpretation</a></li>
<li class="chapter" data-level="6.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling"><i class="fa fa-check"></i><b>6.2</b> Storytelling</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#structure"><i class="fa fa-check"></i><b>6.2.1</b> Structure</a></li>
<li class="chapter" data-level="6.2.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#clarity-parsimony"><i class="fa fa-check"></i><b>6.2.2</b> Clarity &amp; Parsimony</a></li>
<li class="chapter" data-level="6.2.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#influence-persuasion"><i class="fa fa-check"></i><b>6.2.3</b> Influence &amp; Persuasion</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling_withdata"><i class="fa fa-check"></i><b>6.3</b> Storytelling with Data</a></li>
<li class="chapter" data-level="6.4" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#summary-4"><i class="fa fa-check"></i><b>6.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html"><i class="fa fa-check"></i><b>7</b> Deployment &amp; Implementation</a></li>
<li class="part"><span><b>II Introduction to R</b></span></li>
<li class="chapter" data-level="8" data-path="overviewR.html"><a href="overviewR.html"><i class="fa fa-check"></i><b>8</b> Overview of R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="8.1" data-path="overviewR.html"><a href="overviewR.html#R_overview"><i class="fa fa-check"></i><b>8.1</b> R Programming Language</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="overviewR.html"><a href="overviewR.html#R_what"><i class="fa fa-check"></i><b>8.1.1</b> What Is R?</a></li>
<li class="chapter" data-level="8.1.2" data-path="overviewR.html"><a href="overviewR.html#R_why"><i class="fa fa-check"></i><b>8.1.2</b> Why Use R?</a></li>
<li class="chapter" data-level="8.1.3" data-path="overviewR.html"><a href="overviewR.html#R_who"><i class="fa fa-check"></i><b>8.1.3</b> Who Uses R?</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="overviewR.html"><a href="overviewR.html#RStudio_overview"><i class="fa fa-check"></i><b>8.2</b> RStudio</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="overviewR.html"><a href="overviewR.html#RStudio_what"><i class="fa fa-check"></i><b>8.2.1</b> What is RStudio?</a></li>
<li class="chapter" data-level="8.2.2" data-path="overviewR.html"><a href="overviewR.html#RStudio_why"><i class="fa fa-check"></i><b>8.2.2</b> Why RStudio?</a></li>
<li class="chapter" data-level="8.2.3" data-path="overviewR.html"><a href="overviewR.html#RStudio_who"><i class="fa fa-check"></i><b>8.2.3</b> Who Uses RStudio?</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="overviewR.html"><a href="overviewR.html#packages_overview"><i class="fa fa-check"></i><b>8.3</b> Packages</a></li>
<li class="chapter" data-level="8.4" data-path="overviewR.html"><a href="overviewR.html#summary-5"><i class="fa fa-check"></i><b>8.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>9</b> Installing R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="9.1" data-path="install.html"><a href="install.html#installR"><i class="fa fa-check"></i><b>9.1</b> Downloading &amp; Installing R</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="install.html"><a href="install.html#for-windows-operation-systems"><i class="fa fa-check"></i><b>9.1.1</b> For Windows Operation Systems</a></li>
<li class="chapter" data-level="9.1.2" data-path="install.html"><a href="install.html#for-mac-operating-systems"><i class="fa fa-check"></i><b>9.1.2</b> For Mac Operating Systems</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="install.html"><a href="install.html#installRStudio"><i class="fa fa-check"></i><b>9.2</b> Downloading &amp; Installing RStudio</a></li>
<li class="chapter" data-level="9.3" data-path="install.html"><a href="install.html#summary-6"><i class="fa fa-check"></i><b>9.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="gettingstarted.html"><a href="gettingstarted.html"><i class="fa fa-check"></i><b>10</b> Getting Started with R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="10.1" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation-to-rstudio"><i class="fa fa-check"></i><b>10.1</b> Orientation to RStudio</a></li>
<li class="chapter" data-level="10.2" data-path="gettingstarted.html"><a href="gettingstarted.html#createRscript"><i class="fa fa-check"></i><b>10.2</b> Creating &amp; Saving an R Script</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-a-new-r-script"><i class="fa fa-check"></i><b>10.2.1</b> Creating a New R Script</a></li>
<li class="chapter" data-level="10.2.2" data-path="gettingstarted.html"><a href="gettingstarted.html#using-an-r-script"><i class="fa fa-check"></i><b>10.2.2</b> Using an R Script</a></li>
<li class="chapter" data-level="10.2.3" data-path="gettingstarted.html"><a href="gettingstarted.html#saving-an-r-script"><i class="fa fa-check"></i><b>10.2.3</b> Saving an R Script</a></li>
<li class="chapter" data-level="10.2.4" data-path="gettingstarted.html"><a href="gettingstarted.html#opening-a-saved-r-script"><i class="fa fa-check"></i><b>10.2.4</b> Opening a Saved R Script</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-an-rstudio-project"><i class="fa fa-check"></i><b>10.3</b> Creating an RStudio Project</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-a-new-rstudio-project"><i class="fa fa-check"></i><b>10.3.1</b> Creating a New RStudio Project</a></li>
<li class="chapter" data-level="10.3.2" data-path="gettingstarted.html"><a href="gettingstarted.html#opening-an-existing-rstudio-project"><i class="fa fa-check"></i><b>10.3.2</b> Opening an Existing RStudio Project</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation-to-written-tutorials"><i class="fa fa-check"></i><b>10.4</b> Orientation to Written Tutorials</a></li>
<li class="chapter" data-level="10.5" data-path="gettingstarted.html"><a href="gettingstarted.html#summary-7"><i class="fa fa-check"></i><b>10.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="gentleintro.html"><a href="gentleintro.html"><i class="fa fa-check"></i><b>11</b> Basic Features and Operations of the R Language</a>
<ul>
<li class="chapter" data-level="11.1" data-path="gentleintro.html"><a href="gentleintro.html#r_as_calculator"><i class="fa fa-check"></i><b>11.1</b> R as a Calculator</a></li>
<li class="chapter" data-level="11.2" data-path="gentleintro.html"><a href="gentleintro.html#functions"><i class="fa fa-check"></i><b>11.2</b> Functions</a></li>
<li class="chapter" data-level="11.3" data-path="gentleintro.html"><a href="gentleintro.html#packages"><i class="fa fa-check"></i><b>11.3</b> Packages</a></li>
<li class="chapter" data-level="11.4" data-path="gentleintro.html"><a href="gentleintro.html#variableassignment"><i class="fa fa-check"></i><b>11.4</b> Variable Assignment</a></li>
<li class="chapter" data-level="11.5" data-path="gentleintro.html"><a href="gentleintro.html#typesofdata"><i class="fa fa-check"></i><b>11.5</b> Types of Data</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="gentleintro.html"><a href="gentleintro.html#numeric-data"><i class="fa fa-check"></i><b>11.5.1</b> <code>numeric</code> Data</a></li>
<li class="chapter" data-level="11.5.2" data-path="gentleintro.html"><a href="gentleintro.html#character-data"><i class="fa fa-check"></i><b>11.5.2</b> <code>character</code> Data</a></li>
<li class="chapter" data-level="11.5.3" data-path="gentleintro.html"><a href="gentleintro.html#date-data"><i class="fa fa-check"></i><b>11.5.3</b> <code>Date</code> Data</a></li>
<li class="chapter" data-level="11.5.4" data-path="gentleintro.html"><a href="gentleintro.html#logical-data"><i class="fa fa-check"></i><b>11.5.4</b> <code>logical</code> Data</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="gentleintro.html"><a href="gentleintro.html#vectors"><i class="fa fa-check"></i><b>11.6</b> Vectors</a></li>
<li class="chapter" data-level="11.7" data-path="gentleintro.html"><a href="gentleintro.html#lists"><i class="fa fa-check"></i><b>11.7</b> Lists</a></li>
<li class="chapter" data-level="11.8" data-path="gentleintro.html"><a href="gentleintro.html#dataframes"><i class="fa fa-check"></i><b>11.8</b> Data Frames</a></li>
<li class="chapter" data-level="11.9" data-path="gentleintro.html"><a href="gentleintro.html#annotate"><i class="fa fa-check"></i><b>11.9</b> Annotations</a></li>
<li class="chapter" data-level="11.10" data-path="gentleintro.html"><a href="gentleintro.html#summary-8"><i class="fa fa-check"></i><b>11.10</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="setwd.html"><a href="setwd.html"><i class="fa fa-check"></i><b>12</b> Setting a Working Directory</a>
<ul>
<li class="chapter" data-level="12.0.1" data-path="setwd.html"><a href="setwd.html#identify-the-current-working-directory"><i class="fa fa-check"></i><b>12.0.1</b> Identify the Current Working Directory</a></li>
<li class="chapter" data-level="12.0.2" data-path="setwd.html"><a href="setwd.html#set-a-new-working-directory"><i class="fa fa-check"></i><b>12.0.2</b> Set a New Working Directory</a></li>
<li class="chapter" data-level="12.1" data-path="setwd.html"><a href="setwd.html#summary-9"><i class="fa fa-check"></i><b>12.1</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>III Data Acquisition &amp; Management</b></span></li>
<li class="chapter" data-level="13" data-path="read.html"><a href="read.html"><i class="fa fa-check"></i><b>13</b> Reading Data into R</a>
<ul>
<li class="chapter" data-level="13.1" data-path="read.html"><a href="read.html#conceptualoverview_read"><i class="fa fa-check"></i><b>13.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="13.2" data-path="read.html"><a href="read.html#tutorial_read"><i class="fa fa-check"></i><b>13.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="read.html"><a href="read.html#videotutorial_read"><i class="fa fa-check"></i><b>13.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="13.2.2" data-path="read.html"><a href="read.html#functions_read"><i class="fa fa-check"></i><b>13.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="13.2.3" data-path="read.html"><a href="read.html#initialsteps_read"><i class="fa fa-check"></i><b>13.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="13.2.4" data-path="read.html"><a href="read.html#readcsv"><i class="fa fa-check"></i><b>13.2.4</b> Read a .csv File</a></li>
<li class="chapter" data-level="13.2.5" data-path="read.html"><a href="read.html#readxlsx"><i class="fa fa-check"></i><b>13.2.5</b> Read a .xlsx File</a></li>
<li class="chapter" data-level="13.2.6" data-path="read.html"><a href="read.html#read_summary"><i class="fa fa-check"></i><b>13.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="read.html"><a href="read.html#read_supplement"><i class="fa fa-check"></i><b>13.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="read.html"><a href="read.html#read_supplement_functions"><i class="fa fa-check"></i><b>13.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="13.3.2" data-path="read.html"><a href="read.html#read_initsteps_supplement"><i class="fa fa-check"></i><b>13.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="13.3.3" data-path="read.html"><a href="read.html#read_additionalfunctions"><i class="fa fa-check"></i><b>13.3.3</b> Additional Functions to Read a .csv File</a></li>
<li class="chapter" data-level="13.3.4" data-path="read.html"><a href="read.html#read_skiprows"><i class="fa fa-check"></i><b>13.3.4</b> Skip Rows of Data During Read</a></li>
<li class="chapter" data-level="13.3.5" data-path="read.html"><a href="read.html#listdatafiles"><i class="fa fa-check"></i><b>13.3.5</b> List Data File Names in Working Directory</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="addnames.html"><a href="addnames.html"><i class="fa fa-check"></i><b>14</b> Removing, Adding, &amp; Changing Variable Names</a>
<ul>
<li class="chapter" data-level="14.1" data-path="addnames.html"><a href="addnames.html#conceptualoverview_addnames"><i class="fa fa-check"></i><b>14.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="14.2" data-path="addnames.html"><a href="addnames.html#tutorial_addnames"><i class="fa fa-check"></i><b>14.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="addnames.html"><a href="addnames.html#videotutorial_addnames"><i class="fa fa-check"></i><b>14.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="14.2.2" data-path="addnames.html"><a href="addnames.html#function_addnames"><i class="fa fa-check"></i><b>14.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="14.2.3" data-path="addnames.html"><a href="addnames.html#initsteps_addnames"><i class="fa fa-check"></i><b>14.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="14.2.4" data-path="addnames.html"><a href="addnames.html#remove_variablenames"><i class="fa fa-check"></i><b>14.2.4</b> Remove Variable Names from a Data Frame Object</a></li>
<li class="chapter" data-level="14.2.5" data-path="addnames.html"><a href="addnames.html#add_variablenames"><i class="fa fa-check"></i><b>14.2.5</b> Add Variable Names to a Data Frame Object</a></li>
<li class="chapter" data-level="14.2.6" data-path="addnames.html"><a href="addnames.html#change_variablenames"><i class="fa fa-check"></i><b>14.2.6</b> Change Specific Variable Names in a Data Frame Object</a></li>
<li class="chapter" data-level="14.2.7" data-path="addnames.html"><a href="addnames.html#summary_addnames"><i class="fa fa-check"></i><b>14.2.7</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="write.html"><a href="write.html"><i class="fa fa-check"></i><b>15</b> Writing Data from R</a>
<ul>
<li class="chapter" data-level="15.1" data-path="write.html"><a href="write.html#conceptualoverview_write"><i class="fa fa-check"></i><b>15.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="15.2" data-path="write.html"><a href="write.html#tutorial_write"><i class="fa fa-check"></i><b>15.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="write.html"><a href="write.html#videotutorial_write"><i class="fa fa-check"></i><b>15.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="15.2.2" data-path="write.html"><a href="write.html#functions_write"><i class="fa fa-check"></i><b>15.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="15.2.3" data-path="write.html"><a href="write.html#initialsteps_write"><i class="fa fa-check"></i><b>15.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="15.2.4" data-path="write.html"><a href="write.html#write_dataframe"><i class="fa fa-check"></i><b>15.2.4</b> Write Data Frame to Working Directory</a></li>
<li class="chapter" data-level="15.2.5" data-path="write.html"><a href="write.html#write_table"><i class="fa fa-check"></i><b>15.2.5</b> Write Table to Working Directory</a></li>
<li class="chapter" data-level="15.2.6" data-path="write.html"><a href="write.html#summary_write"><i class="fa fa-check"></i><b>15.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>16</b> Arranging (Sorting) Data</a>
<ul>
<li class="chapter" data-level="16.1" data-path="arrange.html"><a href="arrange.html#conceptualoverview_arrange"><i class="fa fa-check"></i><b>16.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="16.2" data-path="arrange.html"><a href="arrange.html#tutorial_arrange"><i class="fa fa-check"></i><b>16.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="arrange.html"><a href="arrange.html#videotutorial_arrange"><i class="fa fa-check"></i><b>16.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="16.2.2" data-path="arrange.html"><a href="arrange.html#functions_arrange"><i class="fa fa-check"></i><b>16.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="16.2.3" data-path="arrange.html"><a href="arrange.html#initsteps_arrange"><i class="fa fa-check"></i><b>16.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="16.2.4" data-path="arrange.html"><a href="arrange.html#arrangebyvalues"><i class="fa fa-check"></i><b>16.2.4</b> Arrange (Sort) Data</a></li>
<li class="chapter" data-level="16.2.5" data-path="arrange.html"><a href="arrange.html#summary_arrange"><i class="fa fa-check"></i><b>16.2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="arrange.html"><a href="arrange.html#arrange_supplement"><i class="fa fa-check"></i><b>16.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="arrange.html"><a href="arrange.html#arrange_supplement_functions"><i class="fa fa-check"></i><b>16.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="16.3.2" data-path="arrange.html"><a href="arrange.html#arrange_initsteps_supplement"><i class="fa fa-check"></i><b>16.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="16.3.3" data-path="arrange.html"><a href="arrange.html#arrange_orderfunction"><i class="fa fa-check"></i><b>16.3.3</b> <code>order</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="join.html"><a href="join.html"><i class="fa fa-check"></i><b>17</b> Joining (Merging) Data</a>
<ul>
<li class="chapter" data-level="17.1" data-path="join.html"><a href="join.html#conceptualoverview_join"><i class="fa fa-check"></i><b>17.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="join.html"><a href="join.html#review_horizontaljoin"><i class="fa fa-check"></i><b>17.1.1</b> Review of Horizontal Joins (Merges)</a></li>
<li class="chapter" data-level="17.1.2" data-path="join.html"><a href="join.html#review_verticaljoin"><i class="fa fa-check"></i><b>17.1.2</b> Review of Vertical Joins (Merges)</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="join.html"><a href="join.html#tutorial_join"><i class="fa fa-check"></i><b>17.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="join.html"><a href="join.html#videotutorial_join"><i class="fa fa-check"></i><b>17.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="17.2.2" data-path="join.html"><a href="join.html#functions-packages-introduced-2"><i class="fa fa-check"></i><b>17.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="17.2.3" data-path="join.html"><a href="join.html#initsteps_join"><i class="fa fa-check"></i><b>17.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="17.2.4" data-path="join.html"><a href="join.html#horizontaljoin"><i class="fa fa-check"></i><b>17.2.4</b> Horizontal Join (Merge)</a></li>
<li class="chapter" data-level="17.2.5" data-path="join.html"><a href="join.html#verticaljoin"><i class="fa fa-check"></i><b>17.2.5</b> Vertical Join (Merge)</a></li>
<li class="chapter" data-level="17.2.6" data-path="join.html"><a href="join.html#summary_join"><i class="fa fa-check"></i><b>17.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="join.html"><a href="join.html#join_supplement"><i class="fa fa-check"></i><b>17.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="join.html"><a href="join.html#supp_join_video"><i class="fa fa-check"></i><b>17.3.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="17.3.2" data-path="join.html"><a href="join.html#join_supplement_functions"><i class="fa fa-check"></i><b>17.3.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="17.3.3" data-path="join.html"><a href="join.html#join_initsteps_supplement"><i class="fa fa-check"></i><b>17.3.3</b> Initial Steps</a></li>
<li class="chapter" data-level="17.3.4" data-path="join.html"><a href="join.html#join_mergefunction"><i class="fa fa-check"></i><b>17.3.4</b> <code>merge</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>18</b> Filtering (Subsetting) Data</a>
<ul>
<li class="chapter" data-level="18.1" data-path="filter.html"><a href="filter.html#conceptualoverview_filter"><i class="fa fa-check"></i><b>18.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="18.1.1" data-path="filter.html"><a href="filter.html#review_logicaloperators"><i class="fa fa-check"></i><b>18.1.1</b> Review of Logical Operators</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="filter.html"><a href="filter.html#tutorial_filter"><i class="fa fa-check"></i><b>18.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="filter.html"><a href="filter.html#videotutorial_filter"><i class="fa fa-check"></i><b>18.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="18.2.2" data-path="filter.html"><a href="filter.html#function_filter"><i class="fa fa-check"></i><b>18.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="18.2.3" data-path="filter.html"><a href="filter.html#initsteps_filter"><i class="fa fa-check"></i><b>18.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="18.2.4" data-path="filter.html"><a href="filter.html#filter_cases"><i class="fa fa-check"></i><b>18.2.4</b> Filter Cases from Data Frame</a></li>
<li class="chapter" data-level="18.2.5" data-path="filter.html"><a href="filter.html#remove-single-variable-from-data-frame"><i class="fa fa-check"></i><b>18.2.5</b> Remove Single Variable from Data Frame</a></li>
<li class="chapter" data-level="18.2.6" data-path="filter.html"><a href="filter.html#select_multiplevariables"><i class="fa fa-check"></i><b>18.2.6</b> Select Multiple Variables from Data Frame</a></li>
<li class="chapter" data-level="18.2.7" data-path="filter.html"><a href="filter.html#remove_multiplevariables"><i class="fa fa-check"></i><b>18.2.7</b> Remove Multiple Variables from Data Frame</a></li>
<li class="chapter" data-level="18.2.8" data-path="filter.html"><a href="filter.html#summary_filter"><i class="fa fa-check"></i><b>18.2.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="filter.html"><a href="filter.html#filter_supplement"><i class="fa fa-check"></i><b>18.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="filter.html"><a href="filter.html#supp_filter_video"><i class="fa fa-check"></i><b>18.3.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="18.3.2" data-path="filter.html"><a href="filter.html#filter_supplement_functions"><i class="fa fa-check"></i><b>18.3.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="18.3.3" data-path="filter.html"><a href="filter.html#filter_initsteps_supplement"><i class="fa fa-check"></i><b>18.3.3</b> Initial Steps</a></li>
<li class="chapter" data-level="18.3.4" data-path="filter.html"><a href="filter.html#filter_subset_supplement"><i class="fa fa-check"></i><b>18.3.4</b> <code>subset</code> Function from Base R</a></li>
<li class="chapter" data-level="18.3.5" data-path="filter.html"><a href="filter.html#str_detect_supp"><i class="fa fa-check"></i><b>18.3.5</b> Filter by Pattern Contained within String</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="clean.html"><a href="clean.html"><i class="fa fa-check"></i><b>19</b> Cleaning Data</a>
<ul>
<li class="chapter" data-level="19.1" data-path="clean.html"><a href="clean.html#conceptualoverview_clean"><i class="fa fa-check"></i><b>19.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="19.2" data-path="clean.html"><a href="clean.html#tutorial_clean"><i class="fa fa-check"></i><b>19.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="clean.html"><a href="clean.html#videotutorial_clean"><i class="fa fa-check"></i><b>19.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="19.2.2" data-path="clean.html"><a href="clean.html#functions_clean"><i class="fa fa-check"></i><b>19.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="19.2.3" data-path="clean.html"><a href="clean.html#initsteps_clean"><i class="fa fa-check"></i><b>19.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="19.2.4" data-path="clean.html"><a href="clean.html#reviewdata_clean"><i class="fa fa-check"></i><b>19.2.4</b> Review Data</a></li>
<li class="chapter" data-level="19.2.5" data-path="clean.html"><a href="clean.html#cleandata_clean"><i class="fa fa-check"></i><b>19.2.5</b> Clean Data</a></li>
<li class="chapter" data-level="19.2.6" data-path="clean.html"><a href="clean.html#renamevariables_clean"><i class="fa fa-check"></i><b>19.2.6</b> Rename Variables</a></li>
<li class="chapter" data-level="19.2.7" data-path="clean.html"><a href="clean.html#otherapproaches_clean"><i class="fa fa-check"></i><b>19.2.7</b> Other Approaches to Cleaning Data</a></li>
<li class="chapter" data-level="19.2.8" data-path="clean.html"><a href="clean.html#summary_clean"><i class="fa fa-check"></i><b>19.2.8</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="aggregatesegment.html"><a href="aggregatesegment.html"><i class="fa fa-check"></i><b>20</b> Aggregating &amp; Segmenting Data</a>
<ul>
<li class="chapter" data-level="20.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup"><i class="fa fa-check"></i><b>20.1</b> Counts By Group</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup_pipes"><i class="fa fa-check"></i><b>20.1.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="20.1.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup_nopipes"><i class="fa fa-check"></i><b>20.1.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup"><i class="fa fa-check"></i><b>20.2</b> Measures of Central Tendency and Dispersion By Group</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup_pipes"><i class="fa fa-check"></i><b>20.2.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="20.2.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup_nopipes"><i class="fa fa-check"></i><b>20.2.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable"><i class="fa fa-check"></i><b>20.3</b> Add Variable to Data Frame Containing Aggregated Values</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable_pipes"><i class="fa fa-check"></i><b>20.3.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="20.3.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable_nopipes"><i class="fa fa-check"></i><b>20.3.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="aggregatesegment.html"><a href="aggregatesegment.html#visualize_bygroup"><i class="fa fa-check"></i><b>20.4</b> Visualize Data By Group</a></li>
<li class="chapter" data-level="20.5" data-path="aggregatesegment.html"><a href="aggregatesegment.html#summary-10"><i class="fa fa-check"></i><b>20.5</b> Summary</a></li>
<li class="chapter" data-level="20.6" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_supplement"><i class="fa fa-check"></i><b>20.6</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="20.6.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_subset_supplement"><i class="fa fa-check"></i><b>20.6.1</b> <code>describeBy</code> Function from <code>psych</code> Package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="21" data-path="manipulate.html"><a href="manipulate.html"><i class="fa fa-check"></i><b>21</b> Manipulating &amp; Restructuring Data</a>
<ul>
<li class="chapter" data-level="21.1" data-path="manipulate.html"><a href="manipulate.html#widetolong"><i class="fa fa-check"></i><b>21.1</b> Wide-to-Long Format Data Manipulation</a>
<ul>
<li class="chapter" data-level="21.1.1" data-path="manipulate.html"><a href="manipulate.html#widetolong_withpipe"><i class="fa fa-check"></i><b>21.1.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="21.1.2" data-path="manipulate.html"><a href="manipulate.html#widetolong_withoutpipe"><i class="fa fa-check"></i><b>21.1.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="manipulate.html"><a href="manipulate.html#longtowide"><i class="fa fa-check"></i><b>21.2</b> Long-to-Wide Format Data Manipulation</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="manipulate.html"><a href="manipulate.html#longtowide_withpipe"><i class="fa fa-check"></i><b>21.2.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="21.2.2" data-path="manipulate.html"><a href="manipulate.html#longtowide_withoutpipe"><i class="fa fa-check"></i><b>21.2.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="manipulate.html"><a href="manipulate.html#summary-11"><i class="fa fa-check"></i><b>21.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="center.html"><a href="center.html"><i class="fa fa-check"></i><b>22</b> Centering &amp; Standardizing Variables</a>
<ul>
<li class="chapter" data-level="22.1" data-path="center.html"><a href="center.html#grandmean_center"><i class="fa fa-check"></i><b>22.1</b> Grand-Mean Centering Variables</a>
<ul>
<li class="chapter" data-level="22.1.1" data-path="center.html"><a href="center.html#mean_function_center"><i class="fa fa-check"></i><b>22.1.1</b> Option 1: Basic Arithmetic and <code>mean</code> Function from Base R</a></li>
<li class="chapter" data-level="22.1.2" data-path="center.html"><a href="center.html#scale_function_center"><i class="fa fa-check"></i><b>22.1.2</b> Option 2: <code>scale</code> Function from Base R</a></li>
<li class="chapter" data-level="22.1.3" data-path="center.html"><a href="center.html#mutate_function_center"><i class="fa fa-check"></i><b>22.1.3</b> Option 3: <code>mutate</code> Function from <code>dplyr</code> and <code>mean</code> Function from Base R</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="center.html"><a href="center.html#standardize_center"><i class="fa fa-check"></i><b>22.2</b> Standardizing Variables</a>
<ul>
<li class="chapter" data-level="22.2.1" data-path="center.html"><a href="center.html#scale_function_standardize"><i class="fa fa-check"></i><b>22.2.1</b> Option 1: <code>scale</code> Function from Base R</a></li>
<li class="chapter" data-level="22.2.2" data-path="center.html"><a href="center.html#mutate_function_standardize"><i class="fa fa-check"></i><b>22.2.2</b> Option 2: <code>mutate</code> Function from <code>dplyr</code> and <code>scale</code> Function from Base R</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="center.html"><a href="center.html#summary_center"><i class="fa fa-check"></i><b>22.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="removeobjects.html"><a href="removeobjects.html"><i class="fa fa-check"></i><b>23</b> Removing Objects from the R Environment</a>
<ul>
<li class="chapter" data-level="23.1" data-path="removeobjects.html"><a href="removeobjects.html#conceptualoverview_removeobjects"><i class="fa fa-check"></i><b>23.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="23.2" data-path="removeobjects.html"><a href="removeobjects.html#tutorial_removeobjects"><i class="fa fa-check"></i><b>23.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="23.2.1" data-path="removeobjects.html"><a href="removeobjects.html#videotutorial_removeobjects"><i class="fa fa-check"></i><b>23.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="23.2.2" data-path="removeobjects.html"><a href="removeobjects.html#function_removeobjects"><i class="fa fa-check"></i><b>23.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="23.2.3" data-path="removeobjects.html"><a href="removeobjects.html#initsteps_removeobjects"><i class="fa fa-check"></i><b>23.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="23.2.4" data-path="removeobjects.html"><a href="removeobjects.html#listobjects_removeobjects"><i class="fa fa-check"></i><b>23.2.4</b> List Objects in R Environment</a></li>
<li class="chapter" data-level="23.2.5" data-path="removeobjects.html"><a href="removeobjects.html#removeobjects_removeobjects"><i class="fa fa-check"></i><b>23.2.5</b> Remove Objects from R Environment</a></li>
<li class="chapter" data-level="23.2.6" data-path="removeobjects.html"><a href="removeobjects.html#summary_removeobjects"><i class="fa fa-check"></i><b>23.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Employee Demographics</b></span></li>
<li class="chapter" data-level="24" data-path="employeedemographics.html"><a href="employeedemographics.html"><i class="fa fa-check"></i><b>24</b> Introduction to Employee Demographics</a></li>
<li class="chapter" data-level="25" data-path="descriptives.html"><a href="descriptives.html"><i class="fa fa-check"></i><b>25</b> Describing Employee Demographics Using Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="25.1" data-path="descriptives.html"><a href="descriptives.html#conceptualoverview_descriptives"><i class="fa fa-check"></i><b>25.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="25.1.1" data-path="descriptives.html"><a href="descriptives.html#measurementscales"><i class="fa fa-check"></i><b>25.1.1</b> Review of Measurement Scales</a></li>
<li class="chapter" data-level="25.1.2" data-path="descriptives.html"><a href="descriptives.html#constructs_measures_measurementscales"><i class="fa fa-check"></i><b>25.1.2</b> Constructs, Measures, &amp; Measurement Scales</a></li>
<li class="chapter" data-level="25.1.3" data-path="descriptives.html"><a href="descriptives.html#typesof_descriptivestatistics"><i class="fa fa-check"></i><b>25.1.3</b> Types of Descriptive Statistics</a></li>
<li class="chapter" data-level="25.1.4" data-path="descriptives.html"><a href="descriptives.html#samplewriteup_descriptives"><i class="fa fa-check"></i><b>25.1.4</b> Sample Write-Up</a></li>
</ul></li>
<li class="chapter" data-level="25.2" data-path="descriptives.html"><a href="descriptives.html#tutorial_descriptives"><i class="fa fa-check"></i><b>25.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="25.2.1" data-path="descriptives.html"><a href="descriptives.html#videotutorial_descriptives"><i class="fa fa-check"></i><b>25.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="25.2.2" data-path="descriptives.html"><a href="descriptives.html#functions_descriptives"><i class="fa fa-check"></i><b>25.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="25.2.3" data-path="descriptives.html"><a href="descriptives.html#initsteps_descriptives"><i class="fa fa-check"></i><b>25.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="25.2.4" data-path="descriptives.html"><a href="descriptives.html#determine_measurementscale"><i class="fa fa-check"></i><b>25.2.4</b> Determine the Measurement Scale</a></li>
<li class="chapter" data-level="25.2.5" data-path="descriptives.html"><a href="descriptives.html#describe_nominal_ordinal"><i class="fa fa-check"></i><b>25.2.5</b> Describe Nominal &amp; Ordinal (Categorical) Variables</a></li>
<li class="chapter" data-level="25.2.6" data-path="descriptives.html"><a href="descriptives.html#describe_interval_ratio"><i class="fa fa-check"></i><b>25.2.6</b> Describe Interval &amp; Ratio (Continuous) Variables</a></li>
<li class="chapter" data-level="25.2.7" data-path="descriptives.html"><a href="descriptives.html#summary_descriptives"><i class="fa fa-check"></i><b>25.2.7</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="crosstabs.html"><a href="crosstabs.html"><i class="fa fa-check"></i><b>26</b> Summarizing Two or More Categorical Variables Using Cross-Tabulations</a>
<ul>
<li class="chapter" data-level="26.1" data-path="crosstabs.html"><a href="crosstabs.html#conceptualoverview_crosstabs"><i class="fa fa-check"></i><b>26.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="26.1.1" data-path="crosstabs.html"><a href="crosstabs.html#review_crosstabs"><i class="fa fa-check"></i><b>26.1.1</b> Review of Cross-Tabulation</a></li>
<li class="chapter" data-level="26.1.2" data-path="crosstabs.html"><a href="crosstabs.html#samplewriteup_crosstabs"><i class="fa fa-check"></i><b>26.1.2</b> Sample Write-Up</a></li>
</ul></li>
<li class="chapter" data-level="26.2" data-path="crosstabs.html"><a href="crosstabs.html#tutorial_crosstabs"><i class="fa fa-check"></i><b>26.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="26.2.1" data-path="crosstabs.html"><a href="crosstabs.html#videotutorial_crosstabs"><i class="fa fa-check"></i><b>26.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="26.2.2" data-path="crosstabs.html"><a href="crosstabs.html#functions_crosstabs"><i class="fa fa-check"></i><b>26.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="26.2.3" data-path="crosstabs.html"><a href="crosstabs.html#initsteps_tables"><i class="fa fa-check"></i><b>26.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="26.2.4" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs"><i class="fa fa-check"></i><b>26.2.4</b> Two-Way Cross-Tabulation</a></li>
<li class="chapter" data-level="26.2.5" data-path="crosstabs.html"><a href="crosstabs.html#threeway_crosstabs"><i class="fa fa-check"></i><b>26.2.5</b> Three-Way Cross-Tabulation</a></li>
<li class="chapter" data-level="26.2.6" data-path="crosstabs.html"><a href="crosstabs.html#summary_crosstabs"><i class="fa fa-check"></i><b>26.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="27" data-path="pivottables.html"><a href="pivottables.html"><i class="fa fa-check"></i><b>27</b> Applying Pivot Tables for Data Exploration</a>
<ul>
<li class="chapter" data-level="27.1" data-path="pivottables.html"><a href="pivottables.html#conceptualoverview_pivottables"><i class="fa fa-check"></i><b>27.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="27.2" data-path="pivottables.html"><a href="pivottables.html#tutorial_pivottables"><i class="fa fa-check"></i><b>27.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="27.2.1" data-path="pivottables.html"><a href="pivottables.html#videotutorial_pivottables"><i class="fa fa-check"></i><b>27.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="27.2.2" data-path="pivottables.html"><a href="pivottables.html#functions_pivottables"><i class="fa fa-check"></i><b>27.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="27.2.3" data-path="pivottables.html"><a href="pivottables.html#initsteps_pivottables"><i class="fa fa-check"></i><b>27.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="27.2.4" data-path="pivottables.html"><a href="pivottables.html#create_pivottables"><i class="fa fa-check"></i><b>27.2.4</b> Create a Pivot Table</a></li>
<li class="chapter" data-level="27.2.5" data-path="pivottables.html"><a href="pivottables.html#summary_pivottables"><i class="fa fa-check"></i><b>27.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V Employee Surveys</b></span></li>
<li class="chapter" data-level="28" data-path="employeesurveys.html"><a href="employeesurveys.html"><i class="fa fa-check"></i><b>28</b> Introduction to Employee Surveys</a></li>
<li class="part"><span><b>VI Employee Training</b></span></li>
<li class="chapter" data-level="29" data-path="employeetraining.html"><a href="employeetraining.html"><i class="fa fa-check"></i><b>29</b> Introduction to Employee Training</a>
<ul>
<li class="chapter" data-level="29.1" data-path="employeetraining.html"><a href="employeetraining.html#trainingevaluation_employeetraining"><i class="fa fa-check"></i><b>29.1</b> Training Evaluation</a></li>
</ul></li>
<li class="chapter" data-level="30" data-path="pretestposttest.html"><a href="pretestposttest.html"><i class="fa fa-check"></i><b>30</b> Evaluating a Pre-Test/Post-Test without Control Group Design Using Paired-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="30.1" data-path="pretestposttest.html"><a href="pretestposttest.html#conceptualoverview_pretestposttest_psttest"><i class="fa fa-check"></i><b>30.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="30.1.1" data-path="pretestposttest.html"><a href="pretestposttest.html#review_pretestposttest"><i class="fa fa-check"></i><b>30.1.1</b> Review of Pre-Test/Post-Test without Control Group Design</a></li>
<li class="chapter" data-level="30.1.2" data-path="pretestposttest.html"><a href="pretestposttest.html#review_psttest"><i class="fa fa-check"></i><b>30.1.2</b> Review of Paired-Samples <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="30.2" data-path="pretestposttest.html"><a href="pretestposttest.html#tutorial_psttest"><i class="fa fa-check"></i><b>30.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="30.2.1" data-path="pretestposttest.html"><a href="pretestposttest.html#videotutorial_psttest"><i class="fa fa-check"></i><b>30.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="30.2.2" data-path="pretestposttest.html"><a href="pretestposttest.html#functions_psttest"><i class="fa fa-check"></i><b>30.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="30.2.3" data-path="pretestposttest.html"><a href="pretestposttest.html#initsteps_psttest"><i class="fa fa-check"></i><b>30.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="30.2.4" data-path="pretestposttest.html"><a href="pretestposttest.html#estimate_psttest"><i class="fa fa-check"></i><b>30.2.4</b> Estimate Paired-Samples <em>t</em>-test</a></li>
<li class="chapter" data-level="30.2.5" data-path="pretestposttest.html"><a href="pretestposttest.html#barchart_psttest"><i class="fa fa-check"></i><b>30.2.5</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="30.2.6" data-path="pretestposttest.html"><a href="pretestposttest.html#summary_psttest"><i class="fa fa-check"></i><b>30.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="30.3" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_supplement"><i class="fa fa-check"></i><b>30.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="30.3.1" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_supplement_functions"><i class="fa fa-check"></i><b>30.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="30.3.2" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_initsteps_supplement"><i class="fa fa-check"></i><b>30.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="30.3.3" data-path="pretestposttest.html"><a href="pretestposttest.html#t.test_function_psttest"><i class="fa fa-check"></i><b>30.3.3</b> <code>t.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="31" data-path="posttestonly.html"><a href="posttestonly.html"><i class="fa fa-check"></i><b>31</b> Evaluating a Post-Test-Only with Control Group Design Using Independent-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="31.1" data-path="posttestonly.html"><a href="posttestonly.html#conceptualoverview_posttestonly_isttest"><i class="fa fa-check"></i><b>31.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="31.1.1" data-path="posttestonly.html"><a href="posttestonly.html#review_posttestonly"><i class="fa fa-check"></i><b>31.1.1</b> Review of Post-Test-Only with Control Group Design</a></li>
<li class="chapter" data-level="31.1.2" data-path="posttestonly.html"><a href="posttestonly.html#review_isttest"><i class="fa fa-check"></i><b>31.1.2</b> Review of Independent-Samples <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="31.2" data-path="posttestonly.html"><a href="posttestonly.html#tutorial_isttest"><i class="fa fa-check"></i><b>31.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="31.2.1" data-path="posttestonly.html"><a href="posttestonly.html#videotutorial_isttest"><i class="fa fa-check"></i><b>31.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="31.2.2" data-path="posttestonly.html"><a href="posttestonly.html#functions_isttest"><i class="fa fa-check"></i><b>31.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="31.2.3" data-path="posttestonly.html"><a href="posttestonly.html#initsteps_isttest"><i class="fa fa-check"></i><b>31.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="31.2.4" data-path="posttestonly.html"><a href="posttestonly.html#estimate_isttest"><i class="fa fa-check"></i><b>31.2.4</b> Estimate Independent-Samples <em>t</em>-test</a></li>
<li class="chapter" data-level="31.2.5" data-path="posttestonly.html"><a href="posttestonly.html#barchart_isttest"><i class="fa fa-check"></i><b>31.2.5</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="31.2.6" data-path="posttestonly.html"><a href="posttestonly.html#summary_isttest"><i class="fa fa-check"></i><b>31.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="31.3" data-path="posttestonly.html"><a href="posttestonly.html#isttest_supplement"><i class="fa fa-check"></i><b>31.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="31.3.1" data-path="posttestonly.html"><a href="posttestonly.html#isttest_supplement_functions"><i class="fa fa-check"></i><b>31.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="31.3.2" data-path="posttestonly.html"><a href="posttestonly.html#isttest_initsteps_supplement"><i class="fa fa-check"></i><b>31.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="31.3.3" data-path="posttestonly.html"><a href="posttestonly.html#t.test_function_isttest"><i class="fa fa-check"></i><b>31.3.3</b> <code>t.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="32" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html"><i class="fa fa-check"></i><b>32</b> Evaluating a Post-Test-Only with Two Comparison Groups Design Using One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="32.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#conceptualoverview_posttestonly_threegroups_onewayanova"><i class="fa fa-check"></i><b>32.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="32.1.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#review_posttestonly_threegroups"><i class="fa fa-check"></i><b>32.1.1</b> Review of Post-Test-Only with Two Comparison Groups Design</a></li>
<li class="chapter" data-level="32.1.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#review_onewayanova"><i class="fa fa-check"></i><b>32.1.2</b> Review of One-Way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="32.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#tutorial_onewayanova"><i class="fa fa-check"></i><b>32.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="32.2.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#videotutorial_onewayanova"><i class="fa fa-check"></i><b>32.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="32.2.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#functions_onewayanova"><i class="fa fa-check"></i><b>32.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="32.2.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#initsteps_onewayanova"><i class="fa fa-check"></i><b>32.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="32.2.4" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#teststatisticalassumptions_onewayanova"><i class="fa fa-check"></i><b>32.2.4</b> Test Statistical Assumptions</a></li>
<li class="chapter" data-level="32.2.5" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#estimate_onewayanova"><i class="fa fa-check"></i><b>32.2.5</b> Estimate One-Way ANOVA</a></li>
<li class="chapter" data-level="32.2.6" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#barchart_onewayanova"><i class="fa fa-check"></i><b>32.2.6</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="32.2.7" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#summary_onewayanova"><i class="fa fa-check"></i><b>32.2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="32.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_supplement"><i class="fa fa-check"></i><b>32.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="32.3.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_supplement_functions"><i class="fa fa-check"></i><b>32.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="32.3.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_initsteps_supplement"><i class="fa fa-check"></i><b>32.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="32.3.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#aov_function_onewayanova"><i class="fa fa-check"></i><b>32.3.3</b> <code>aov</code> Function from Base R</a></li>
<li class="chapter" data-level="32.3.4" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#apatable_onewayanova"><i class="fa fa-check"></i><b>32.3.4</b> APA-Style Table of Results</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VII Employee Selection</b></span></li>
<li class="chapter" data-level="33" data-path="selection.html"><a href="selection.html"><i class="fa fa-check"></i><b>33</b> Introduction to Employee Selection</a></li>
<li class="chapter" data-level="34" data-path="disparateimpact.html"><a href="disparateimpact.html"><i class="fa fa-check"></i><b>34</b> Investigating Disparate Impact</a>
<ul>
<li class="chapter" data-level="34.1" data-path="disparateimpact.html"><a href="disparateimpact.html#conceptualoverview_disparateimpact"><i class="fa fa-check"></i><b>34.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="34.2" data-path="disparateimpact.html"><a href="disparateimpact.html#tutorial_disparateimpact"><i class="fa fa-check"></i><b>34.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="34.2.1" data-path="disparateimpact.html"><a href="disparateimpact.html#videotutorial_disparateimpact"><i class="fa fa-check"></i><b>34.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="34.2.2" data-path="disparateimpact.html"><a href="disparateimpact.html#functions_disparateimpact"><i class="fa fa-check"></i><b>34.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="34.2.3" data-path="disparateimpact.html"><a href="disparateimpact.html#initsteps_disparateimpact"><i class="fa fa-check"></i><b>34.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="34.2.4" data-path="disparateimpact.html"><a href="disparateimpact.html#fourfifthsrule"><i class="fa fa-check"></i><b>34.2.4</b> 4/5ths Rule</a></li>
<li class="chapter" data-level="34.2.5" data-path="disparateimpact.html"><a href="disparateimpact.html#chisquaretest_disparateimpact"><i class="fa fa-check"></i><b>34.2.5</b> Chi-Squared (<span class="math inline">\(\chi^2\)</span>) Test of Independence</a></li>
<li class="chapter" data-level="34.2.6" data-path="disparateimpact.html"><a href="disparateimpact.html#fisherexacttest"><i class="fa fa-check"></i><b>34.2.6</b> Fisher Exact Test</a></li>
<li class="chapter" data-level="34.2.7" data-path="disparateimpact.html"><a href="disparateimpact.html#zdifference_test_disparateimpact"><i class="fa fa-check"></i><b>34.2.7</b> <span class="math inline">\(Z_{D}\)</span> Test</a></li>
<li class="chapter" data-level="34.2.8" data-path="disparateimpact.html"><a href="disparateimpact.html#z_impactratiotest"><i class="fa fa-check"></i><b>34.2.8</b> <span class="math inline">\(Z_{IR}\)</span> Test</a></li>
<li class="chapter" data-level="34.2.9" data-path="disparateimpact.html"><a href="disparateimpact.html#summary_disparatetreatment"><i class="fa fa-check"></i><b>34.2.9</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="35" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html"><i class="fa fa-check"></i><b>35</b> Estimating Criterion-Related Validity Using Correlation</a>
<ul>
<li class="chapter" data-level="35.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#conceptualoverview_criterionrelatedvalidity"><i class="fa fa-check"></i><b>35.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="35.1.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#review_criterionrelatedvalidity"><i class="fa fa-check"></i><b>35.1.1</b> Review of Criterion-Related Validity</a></li>
<li class="chapter" data-level="35.1.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#review_correlation"><i class="fa fa-check"></i><b>35.1.2</b> Review of Correlation</a></li>
</ul></li>
<li class="chapter" data-level="35.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#tutorial_criterionrelatedvalidity"><i class="fa fa-check"></i><b>35.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="35.2.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#videotutorial_criterionrelatedvalidity"><i class="fa fa-check"></i><b>35.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="35.2.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#functions_criterionrelatedvalidity"><i class="fa fa-check"></i><b>35.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="35.2.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#initsteps_criterionrelatedvalidity"><i class="fa fa-check"></i><b>35.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="35.2.4" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#scatterplot_criterionrelatedvalidity"><i class="fa fa-check"></i><b>35.2.4</b> Visualize Association Using a Scatter Plot</a></li>
<li class="chapter" data-level="35.2.5" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#estimate_correlation"><i class="fa fa-check"></i><b>35.2.5</b> Estimate Correlation</a></li>
<li class="chapter" data-level="35.2.6" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#summary_criterionrelatedvalidity"><i class="fa fa-check"></i><b>35.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="35.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_supplement"><i class="fa fa-check"></i><b>35.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="35.3.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_supplement_functions"><i class="fa fa-check"></i><b>35.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="35.3.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_initsteps_supplement"><i class="fa fa-check"></i><b>35.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="35.3.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#cor_function"><i class="fa fa-check"></i><b>35.3.3</b> <code>cor</code> Function from Base R</a></li>
<li class="chapter" data-level="35.3.4" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#cortest_function"><i class="fa fa-check"></i><b>35.3.4</b> <code>cor.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="36" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html"><i class="fa fa-check"></i><b>36</b> Predicting Criterion Scores Using Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="36.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#conceptualoverview_predictingcriterionscores"><i class="fa fa-check"></i><b>36.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="36.1.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#review_slr"><i class="fa fa-check"></i><b>36.1.1</b> Review of Simple Linear Regression</a></li>
<li class="chapter" data-level="36.1.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#review_prediction_slr"><i class="fa fa-check"></i><b>36.1.2</b> Predicting Future Criterion Scores Using Simple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="36.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#tutorial_predictingcriterionscores"><i class="fa fa-check"></i><b>36.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="36.2.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#videotutorial_predictingcriterionscores"><i class="fa fa-check"></i><b>36.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="36.2.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#functions_predictingcriterionscores"><i class="fa fa-check"></i><b>36.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="36.2.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#initsteps_slr"><i class="fa fa-check"></i><b>36.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="36.2.4" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#estimate_slr"><i class="fa fa-check"></i><b>36.2.4</b> Estimate Simple Linear Regression Model</a></li>
<li class="chapter" data-level="36.2.5" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_slr"><i class="fa fa-check"></i><b>36.2.5</b> Predict Criterion Scores</a></li>
<li class="chapter" data-level="36.2.6" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#summary_predictingcriterionscores"><i class="fa fa-check"></i><b>36.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="36.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_supplement"><i class="fa fa-check"></i><b>36.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="36.3.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_supplement_functions"><i class="fa fa-check"></i><b>36.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="36.3.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_initsteps_supplement"><i class="fa fa-check"></i><b>36.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="36.3.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#lm_function_slr"><i class="fa fa-check"></i><b>36.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="36.3.4" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predict_function_slr"><i class="fa fa-check"></i><b>36.3.4</b> <code>predict</code> Function from Base R</a></li>
<li class="chapter" data-level="36.3.5" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#apatable_slr"><i class="fa fa-check"></i><b>36.3.5</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="37" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html"><i class="fa fa-check"></i><b>37</b> Estimating Incremental Validity Using Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="37.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#conceptualoverview_incrementalvalidity"><i class="fa fa-check"></i><b>37.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="37.1.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#review_mlr"><i class="fa fa-check"></i><b>37.1.1</b> Review of Multiple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="37.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#tutorial_incrementalvalidity"><i class="fa fa-check"></i><b>37.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="37.2.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#videotutorial_incrementalvalidity"><i class="fa fa-check"></i><b>37.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="37.2.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#function_incrementalvalidity"><i class="fa fa-check"></i><b>37.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="37.2.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#initsteps_mlr"><i class="fa fa-check"></i><b>37.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="37.2.4" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#estimate_mlr"><i class="fa fa-check"></i><b>37.2.4</b> Estimate Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="37.2.5" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#summary_incrementalvalidity"><i class="fa fa-check"></i><b>37.2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="37.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_supplement"><i class="fa fa-check"></i><b>37.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="37.3.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_supplement_functions"><i class="fa fa-check"></i><b>37.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="37.3.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_initsteps_supplement"><i class="fa fa-check"></i><b>37.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="37.3.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#lm_function_mlr"><i class="fa fa-check"></i><b>37.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="37.3.4" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#apatable_mlr"><i class="fa fa-check"></i><b>37.3.4</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="38" data-path="compensatory.html"><a href="compensatory.html"><i class="fa fa-check"></i><b>38</b> Applying a Compensatory Approach to Selection Decisions Using Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="38.1" data-path="compensatory.html"><a href="compensatory.html#conceptualoverview_compensatory"><i class="fa fa-check"></i><b>38.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="38.1.1" data-path="compensatory.html"><a href="compensatory.html#review_compensatory_mlr"><i class="fa fa-check"></i><b>38.1.1</b> Review of Multiple Linear Regression</a></li>
<li class="chapter" data-level="38.1.2" data-path="compensatory.html"><a href="compensatory.html#review_compensatory"><i class="fa fa-check"></i><b>38.1.2</b> Review of Compensatory Approach</a></li>
</ul></li>
<li class="chapter" data-level="38.2" data-path="compensatory.html"><a href="compensatory.html#tutorial_compensatory"><i class="fa fa-check"></i><b>38.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="38.2.1" data-path="compensatory.html"><a href="compensatory.html#videotutorial_compensatory"><i class="fa fa-check"></i><b>38.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="38.2.2" data-path="compensatory.html"><a href="compensatory.html#function_compensatory"><i class="fa fa-check"></i><b>38.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="38.2.3" data-path="compensatory.html"><a href="compensatory.html#initsteps_compensatory"><i class="fa fa-check"></i><b>38.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="38.2.4" data-path="compensatory.html"><a href="compensatory.html#estimate_compensatory"><i class="fa fa-check"></i><b>38.2.4</b> Estimate Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="38.2.5" data-path="compensatory.html"><a href="compensatory.html#predictcriterionscores_compensatory"><i class="fa fa-check"></i><b>38.2.5</b> Predict Criterion Scores</a></li>
<li class="chapter" data-level="38.2.6" data-path="compensatory.html"><a href="compensatory.html#summary_compensatory"><i class="fa fa-check"></i><b>38.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="38.3" data-path="compensatory.html"><a href="compensatory.html#compensatory_supplement"><i class="fa fa-check"></i><b>38.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="38.3.1" data-path="compensatory.html"><a href="compensatory.html#compensatory_supplement_functions"><i class="fa fa-check"></i><b>38.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="38.3.2" data-path="compensatory.html"><a href="compensatory.html#compensatory_initsteps_supplement"><i class="fa fa-check"></i><b>38.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="38.3.3" data-path="compensatory.html"><a href="compensatory.html#lm_predict_functions_compensatory"><i class="fa fa-check"></i><b>38.3.3</b> <code>lm</code> &amp; <code>predict</code> Functions from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="39" data-path="multiplecutoff.html"><a href="multiplecutoff.html"><i class="fa fa-check"></i><b>39</b> Applying a Noncompensatory Approach to Selection Decisions Using Angoff Method</a>
<ul>
<li class="chapter" data-level="39.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#conceptualoverview_multiplecutoff"><i class="fa fa-check"></i><b>39.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="39.1.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#review_multiplecutoff"><i class="fa fa-check"></i><b>39.1.1</b> Review of Noncompensatory Approach</a></li>
</ul></li>
<li class="chapter" data-level="39.2" data-path="multiplecutoff.html"><a href="multiplecutoff.html#tutorial_multiplecutoff"><i class="fa fa-check"></i><b>39.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="39.2.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#function_multiplecutoff"><i class="fa fa-check"></i><b>39.2.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="39.2.2" data-path="multiplecutoff.html"><a href="multiplecutoff.html#initsteps_multiplecutoff"><i class="fa fa-check"></i><b>39.2.2</b> Initial Steps</a></li>
<li class="chapter" data-level="39.2.3" data-path="multiplecutoff.html"><a href="multiplecutoff.html#createcutoffscores_multiplecutoff"><i class="fa fa-check"></i><b>39.2.3</b> Create Cutoff Scores</a></li>
<li class="chapter" data-level="39.2.4" data-path="multiplecutoff.html"><a href="multiplecutoff.html#applycutoffscores_multiplecutoff"><i class="fa fa-check"></i><b>39.2.4</b> Apply Cutoff Scores to Make Selection Decisions</a></li>
<li class="chapter" data-level="39.2.5" data-path="multiplecutoff.html"><a href="multiplecutoff.html#summary_multiplecutoff"><i class="fa fa-check"></i><b>39.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="40" data-path="differentialprediction.html"><a href="differentialprediction.html"><i class="fa fa-check"></i><b>40</b> Testing for Differential Prediction Using Moderated Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="40.1" data-path="differentialprediction.html"><a href="differentialprediction.html#conceptualoverview_differentialprediction"><i class="fa fa-check"></i><b>40.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="40.1.1" data-path="differentialprediction.html"><a href="differentialprediction.html#review_mmlr"><i class="fa fa-check"></i><b>40.1.1</b> Review of Moderated Multiple Linear Regression</a></li>
<li class="chapter" data-level="40.1.2" data-path="differentialprediction.html"><a href="differentialprediction.html#review_differentialprediction"><i class="fa fa-check"></i><b>40.1.2</b> Review of Differential Prediction</a></li>
</ul></li>
<li class="chapter" data-level="40.2" data-path="differentialprediction.html"><a href="differentialprediction.html#tutorial_differentialprediction"><i class="fa fa-check"></i><b>40.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="40.2.1" data-path="differentialprediction.html"><a href="differentialprediction.html#videotutorial_differentialprediction"><i class="fa fa-check"></i><b>40.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="40.2.2" data-path="differentialprediction.html"><a href="differentialprediction.html#function_mmlr"><i class="fa fa-check"></i><b>40.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="40.2.3" data-path="differentialprediction.html"><a href="differentialprediction.html#initsteps_mmlr"><i class="fa fa-check"></i><b>40.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="40.2.4" data-path="differentialprediction.html"><a href="differentialprediction.html#center_mmlr"><i class="fa fa-check"></i><b>40.2.4</b> Grand-Mean Center Continuous Predictor Variables</a></li>
<li class="chapter" data-level="40.2.5" data-path="differentialprediction.html"><a href="differentialprediction.html#estimate_mmlr"><i class="fa fa-check"></i><b>40.2.5</b> Estimate Moderated Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="40.2.6" data-path="differentialprediction.html"><a href="differentialprediction.html#summary_differentialprediction"><i class="fa fa-check"></i><b>40.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="40.3" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_supplement"><i class="fa fa-check"></i><b>40.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="40.3.1" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_supplement_functions"><i class="fa fa-check"></i><b>40.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="40.3.2" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_initsteps_supplement"><i class="fa fa-check"></i><b>40.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="40.3.3" data-path="differentialprediction.html"><a href="differentialprediction.html#lm_function_mmlr"><i class="fa fa-check"></i><b>40.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="40.3.4" data-path="differentialprediction.html"><a href="differentialprediction.html#apatable_mmlr"><i class="fa fa-check"></i><b>40.3.4</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VIII Odds &amp; Ends</b></span></li>
<li class="chapter" data-level="41" data-path="create-portfolio.html"><a href="create-portfolio.html"><i class="fa fa-check"></i><b>41</b> Creating a Data Analytics Portfolio</a></li>
<li class="chapter" data-level="42" data-path="literature-search-review.html"><a href="literature-search-review.html"><i class="fa fa-check"></i><b>42</b> Conducting a Literature Search &amp; Review</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for HR:<br />
<em>An Introduction to Human Resource Analytics Using R</em><br />
BOOK UNDER CONSTRUCTION</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="criterionrelatedvalidity" class="section level1" number="35">
<h1><span class="header-section-number">Chapter 35</span> Estimating Criterion-Related Validity Using Correlation</h1>
<p>In this chapter, we will learn how to estimate the criterion-related validity of an employee selection tool by using a correlation. We’ll begin with a conceptual overview of criterion-related validity and correlation, and we’ll conclude with a tutorial.</p>
<div id="conceptualoverview_criterionrelatedvalidity" class="section level2" number="35.1">
<h2><span class="header-section-number">35.1</span> Conceptual Overview</h2>
<p>In this section, we’ll begin by reviewing the concept of criterion-related validity and then conclude by reviewing the Pearson product-moment correlation. With respect to the latter, we’ll discuss the statistical assumptions that should be satisfied prior to estimating and interpreting a correlation as well as statistical significance and and practical significance in the context of correlation. The section will wrap up with a sample-write up of a correlation when used to estimate the criterion-related validity of a selection tool.</p>
<div id="review_criterionrelatedvalidity" class="section level3" number="35.1.1">
<h3><span class="header-section-number">35.1.1</span> Review of Criterion-Related Validity</h3>
<p><strong>Criterion-related validity</strong> (<strong>criterion validity</strong>) has to do with the association between a variable and some outcome variable. The term <strong>criterion</strong> can be thought of as some outcome or correlate of practical or theoretical interest. In the employee selection context, the criterion of interest is often some indicator of job performance (e.g., performance evaluations). Where possible, the U.S. court system generally favors evidence of criterion-related validity when demonstrating that a selection tool is job-relevant and job-related. The data necessary to estimate criterion-related validity can be acquired from <em>concurrent validation studies/designs</em> or <em>predictive validation studies/designs</em>, both of which can be classified beneath the umbrella term of <em>criterion-related validation studies/designs</em>. For additional information on criterion-related validity and other types of validity (e.g., content, construct, convergent, discriminant), I recommend reading the following free resources:</p>
<ul>
<li>Pages 10-15 from the <a href="https://www.apa.org/ed/accreditation/about/policies/personnel-selection-procedures.pdf">Principles for the Validiation and Use of Personnel Selection Procedures</a> <span class="citation">(<a href="references.html#ref-siop2018" role="doc-biblioref">Society for Industrial &amp; Organizational Psychology 2018</a>)</span>;</li>
<li>Chapter 4.2 from <a href="https://opentext.wsu.edu/carriecuttler/chapter/reliability-and-validity-of-measurement/">Research Methods in Psychology</a> <span class="citation">(<a href="references.html#ref-priceetal2017" role="doc-biblioref">Price et al. 2017</a>)</span>.</li>
</ul>
</div>
<div id="review_correlation" class="section level3" number="35.1.2">
<h3><span class="header-section-number">35.1.2</span> Review of Correlation</h3>
<p>A <strong>correlation</strong> represents the sign (i.e., direction) and magnitude (i.e., strength) of an association between two variables. There are different types of correlations we can estimate, and their appropriateness will depend on the measurement scales of the two variables. For instance, the <em>Pearson product-moment correlation</em> is used when both variables are continuous (i.e., have interval or ratio measurement scale), whereas the <em>biserial correlation</em> is used when one variable is continuous and the other is dichotomous (e.g., has a nominal measurement scale with just two levels or categories). In this chapter, we will focus on estimating Pearson product-moment correlations, which I will henceforth refer to as just “correlation.”</p>
<p>Correlation coefficients can range from -1.00 to +1.00, where zero (.00) represents no association, -1.00 represents a perfect negative (inverse) association, and +1.00 represents a perfect positive association. A Pearson product-moment correlation coefficient (<em>r</em>) for a sample can be computed using the following formula:</p>
<p><span class="math inline">\(r = \frac{\sum XY - \frac{(\sum X)(\sum Y)}{n}} {\sqrt{(\sum X^{2} - \frac{\sum X^{2}}{n}) (\sum Y^{2} - \frac{\sum Y^{2}}{n})}}\)</span></p>
<p>where <span class="math inline">\(X\)</span> refers to scores from one variable and <span class="math inline">\(Y\)</span> refers to scores from the other variable, <span class="math inline">\(n\)</span> refers to the sample size (i.e., the number of pairs of data corresponding to the number of cases – with complete data).</p>
<p>When estimated using data acquired from a criterion-related validation study (e.g, concurrent or predictive validation study/design), a <strong>correlation coefficient</strong> can be referred to as a <strong>validity coefficient</strong>.</p>
<div id="statisticalassumptions_correlation" class="section level4" number="35.1.2.1">
<h4><span class="header-section-number">35.1.2.1</span> Statistical Assumptions</h4>
<p>The statistical assumptions that should be met prior to running and/or interpreting a Pearson product-moment correlation include:</p>
<ul>
<li>Cases are randomly sampled from the population, such that the variable scores for one individual are independent of the variable scores of another individual;</li>
<li>Each variable shows a univariate normal distribution;</li>
<li>Each variable is free of univariate outliers, and together the variables are free of bivariate outliers;</li>
<li>Variables demonstrate a bivariate normal distribution - meaning, each variable is normally distributed at each level/value of the other variable. Often, this roughly takes the form of an ellipse shape, if you were to superimpose an oval that would fit around most cases in a bivariate scatter plot;</li>
<li>The association between the two variables is linear.</li>
</ul>
</div>
<div id="statisticalsignficance_correlation" class="section level4" number="35.1.2.2">
<h4><span class="header-section-number">35.1.2.2</span> Statistical Significance</h4>
<p>The significance level of a correlation coefficient is determined by the sample size and the magnitude of the correlation coefficient. Specifically, a <em>t</em>-statistic with <em>N</em>-2 degrees of freedom (df) is calculated and compared to a Student’s <em>t</em>-distribution with <em>N</em>-2 df and a given alpha level (usually two-tailed, alpha = .05). If the calculated <em>t</em>-statistic is greater in magnitude than the chosen <em>t</em>-distribution, we conclude that the population correlation coefficient is significantly greater than zero. We use the following formula to calculate the <em>t</em>-statistic:</p>
<p><span class="math inline">\(t = \frac{r \sqrt{N-2}}{1-r^{2}}\)</span></p>
<p>where <span class="math inline">\(r\)</span> refers to the estimated correlation coefficient and <span class="math inline">\(N\)</span> refers to the sample size. Alternatively, the exact <em>p</em>-value can be computed using a statistical software program like R if we know the df and <em>t</em>-value.</p>
<p>In practice, however, we don’t always report the associated <em>t</em>-value; instead, we almost always report the exact <em>p</em>-value associated with the <em>t</em>-value when reporting information about statistical significance. When using null hypothesis significance testing, we interpret a <em>p</em>-value that is less than our chosen alpha level (which is conventionally .05, two-tailed) to meet the standard for statistical significance. This means that we reject the null hypothesis that the correlation is equal to zero. By rejecting this null hypothesis, we conclude that the correlation is significantly different from zero. If the <em>p</em>-value is equal to or greater than our chosen alpha level (e.g., .05, two-tailed), then we fail to reject the null hypothesis that the correlation is equal to zero; meaning, we conclude that there is no evidence of linear association between the two variables.</p>
</div>
<div id="practicalsignficance_correlation" class="section level4" number="35.1.2.3">
<h4><span class="header-section-number">35.1.2.3</span> Practical Significance</h4>
<p>The size of a correlation coefficient can be described using qualitative labels, such as small, medium, and large. The quantitative values tied to such qualitative labels of magnitude should really be treated as context specific; with that said, there are some very general rules we can apply when interpreting the magnitude of correlation coefficients, which are presented in the table below <span class="citation">(<a href="references.html#ref-cohen1992power" role="doc-biblioref">Cohen 1992</a>)</span>. Please note that the <em>r</em> values in the table are absolute values, which means, for example, that correlation coefficients of .50 and -.50 would both have the same absolute value and thus would both be considered large.</p>
<table>
<thead>
<tr class="header">
<th><em>r</em></th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.10</td>
<td>Small</td>
</tr>
<tr class="even">
<td>.30</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td>.50</td>
<td>Large</td>
</tr>
</tbody>
</table>
<p>Some people like to also report the <strong>coefficient of determination</strong> as an indicator of effect size. The coefficient of determination is calculated by squaring the correlation coefficient to create <em>r</em><sup>2</sup>. When multiplied by 100, the coefficient of determination (<em>r</em><sup>2</sup>) can be interpreted as the percentage of variance/variability shared between the two variables, which is sometimes stated as follows: Variable <span class="math inline">\(X\)</span> explains <span class="math inline">\(X\)</span>% of the variance in Variable <span class="math inline">\(Y\)</span> (or vice versa). Please note that we use the lower-case <em>r</em> in <em>r</em><sup>2</sup> to indicate that we are reporting the variance overlap between only two variables.</p>
<p><em>Note: Typically, we only interpret the practical significance of an effect if the effect was found to be statistically significant. The logic is that if an effect (e.g., association, difference) is not statistically significant, then we should treat it as no different than zero, and thus it wouldn’t make sense to the interpret the size of something that statistically has no effect.</em></p>
<p>A bivariate scatter plot comes in handy when visually depicting the direction and strength of an association between two continuous (interval or ratio measurement scale) variables. Further, the scatter plot can be applied to understand whether statistical assumptions related to linearity and a bivariate normal distribution have been met. To create examples of scatter plots based on simulated data, check out <a href="https://rpsychologist.com/correlation/">this free tool</a>. The tool also does a nice job of depicting the concept of shared variance in the context of correlation (i.e., coefficient of determination) using a Venn diagram.</p>
</div>
<div id="samplewriteup_correlation" class="section level4" number="35.1.2.4">
<h4><span class="header-section-number">35.1.2.4</span> Sample Write-Up</h4>
<p>Our organization implemented a concurrent validation study to collect the data necessary to estimate the criterion-related validity of a new structured interview selection tool for customer service representatives. The concurrent validation study included a sample of 67 job incumbents (<em>N</em> = 67) and their scores on the structured interview and on the criterion of job performance. Using a Pearson product-moment correlation, we found a statistically significant, medium-sized correlation between structured interview scores and job performance scores (<em>r</em> = .29, <em>p</em> = .02), such that those who scored higher on the structured interview showed moderately higher levels of job performance. The 95% confidence interval indicated that the true correlation value for the entire population of employees likely falls somewhere between .05 and .50 (95% CI[.05, .50]). In this context, the correlation coefficient can be conceptualized as a validity coefficient and, thus, an indicator of criterion-related validity. Given that the correlation is statistically significant, we can conclude that the structured interview shows evidence of criterion-related validity for the customer service representative job, thereby demonstrating that this selection tool is job-related.</p>
<p><em>Note: If the p-value were equal to or greater than our alpha level (e.g., .05, two-tailed), then we would typically state that the association between the two variables is not statistically significant, and we would not proceed forward with interpreting the effect size (i.e., level of practical significance) because the test of statistical significance indicates that it is very unlikely based on our sample that a true association between these two variables exists in the population.</em></p>
</div>
</div>
</div>
<div id="tutorial_criterionrelatedvalidity" class="section level2" number="35.2">
<h2><span class="header-section-number">35.2</span> Tutorial</h2>
<p>This chapter’s tutorial demonstrates how to estimate criterion-related validity using a correlation, and how to present the results in writing.</p>
<div id="videotutorial_criterionrelatedvalidity" class="section level3" number="35.2.1">
<h3><span class="header-section-number">35.2.1</span> Video Tutorial</h3>
<p>As usual, you have the choice to follow along with the written tutorial in this chapter or to watch the video tutorial below.</p>
<iframe src="https://youtube.com/embed/yPAfqmISQ3U?rel=0" width="672" height="400px">
</iframe>
<p>Link to video tutorial: <a href="https://youtu.be/yPAfqmISQ3U" class="uri">https://youtu.be/yPAfqmISQ3U</a></p>
</div>
<div id="functions_criterionrelatedvalidity" class="section level3" number="35.2.2">
<h3><span class="header-section-number">35.2.2</span> Functions &amp; Packages Introduced</h3>
<table>
<thead>
<tr class="header">
<th>Function</th>
<th>Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>ScatterPlot</code></td>
<td><code>lessR</code></td>
</tr>
<tr class="even">
<td><code>Correlation</code></td>
<td><code>lessR</code></td>
</tr>
</tbody>
</table>
</div>
<div id="initsteps_criterionrelatedvalidity" class="section level3" number="35.2.3">
<h3><span class="header-section-number">35.2.3</span> Initial Steps</h3>
<p>If you haven’t already, save the file called <strong>“SelectionData.csv”</strong> into a folder that you will subsequently set as your working directory. Your working directory will likely be different than the one shown below (i.e., <code>"H:/RWorkshop"</code>). As a reminder, you can access all of the data files referenced in this book by downloading them as a compressed (zipped) folder from the my GitHub site: <a href="https://github.com/davidcaughlin/R-Tutorial-Data-Files" class="uri">https://github.com/davidcaughlin/R-Tutorial-Data-Files</a>; once you’ve followed the link to GitHub, just click “Code” (or “Download”) followed by “Download ZIP”, which will download all of the data files referenced in this book. For the sake of parsimony, I recommend downloading all of the data files into the same folder on your computer, which will allow you to set that same folder as your working directory for each of the chapters in this book.</p>
<p>Next, using the <code>setwd</code> function, set your working directory to the folder in which you saved the data file for this chapter. Alternatively, you can manually set your working directory folder in your drop-down menus by going to <em>Session &gt; Set Working Directory &gt; Choose Directory…</em>. Be sure to create a new R script file (.R) or update an existing R script file so that you can save your script and annotations. If you need refreshers on how to set your working directory and how to create and save an R script, please refer to <a href="setwd.html#setwd">Setting a Working Directory</a> and <a href="gettingstarted.html#createRscript">Creating &amp; Saving an R Script</a>.</p>
<div class="sourceCode" id="cb1081"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1081-1"><a href="criterionrelatedvalidity.html#cb1081-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your working directory</span></span>
<span id="cb1081-2"><a href="criterionrelatedvalidity.html#cb1081-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;H:/RWorkshop&quot;</span>)</span></code></pre></div>
<p>Next, read in the .csv data file called <strong>“SelectionData.csv”</strong> using your choice of read function. In this example, I use the <code>read_csv</code> function from the <code>readr</code> package <span class="citation">(<a href="references.html#ref-R-readr" role="doc-biblioref">Wickham and Hester 2020</a>)</span>. If you choose to use the <code>read_csv</code> function, be sure that you have installed and accessed the <code>readr</code> package using the <code>install.packages</code> and <code>library</code> functions. <em>Note: You don’t need to install a package every time you wish to access it; in general, I would recommend updating a package installation once ever 1-3 months.</em> For refreshers on installing packages and reading data into R, please refer to <a href="gentleintro.html#packages">Packages</a> and <a href="read.html#read">Reading Data into R</a>.</p>
<div class="sourceCode" id="cb1082"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1082-1"><a href="criterionrelatedvalidity.html#cb1082-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install readr package if you haven&#39;t already</span></span>
<span id="cb1082-2"><a href="criterionrelatedvalidity.html#cb1082-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Note: You don&#39;t need to install a package every </span></span>
<span id="cb1082-3"><a href="criterionrelatedvalidity.html#cb1082-3" aria-hidden="true" tabindex="-1"></a><span class="co"># time you wish to access it]</span></span>
<span id="cb1082-4"><a href="criterionrelatedvalidity.html#cb1082-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;readr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb1083"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1083-1"><a href="criterionrelatedvalidity.html#cb1083-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access readr package</span></span>
<span id="cb1083-2"><a href="criterionrelatedvalidity.html#cb1083-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1083-3"><a href="criterionrelatedvalidity.html#cb1083-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1083-4"><a href="criterionrelatedvalidity.html#cb1083-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data and name data frame (tibble) object</span></span>
<span id="cb1083-5"><a href="criterionrelatedvalidity.html#cb1083-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;SelectionData.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification ---------------------------------------------------------------------------------------------
## cols(
##   EmployeeID = col_double(),
##   Conscientiousness = col_double(),
##   Interview = col_double(),
##   Performance = col_double()
## )</code></pre>
<div class="sourceCode" id="cb1085"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1085-1"><a href="criterionrelatedvalidity.html#cb1085-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the names of the variables in the data frame (tibble) objects</span></span>
<span id="cb1085-2"><a href="criterionrelatedvalidity.html#cb1085-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df)</span></code></pre></div>
<pre><code>## [1] &quot;EmployeeID&quot;        &quot;Conscientiousness&quot; &quot;Interview&quot;         &quot;Performance&quot;</code></pre>
<div class="sourceCode" id="cb1087"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1087-1"><a href="criterionrelatedvalidity.html#cb1087-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View variable type for each variable in data frame</span></span>
<span id="cb1087-2"><a href="criterionrelatedvalidity.html#cb1087-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code></pre></div>
<pre><code>## spec_tbl_df[,4] [163 x 4] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ EmployeeID       : num [1:163] 1 2 3 4 5 6 7 8 9 10 ...
##  $ Conscientiousness: num [1:163] 3.33 3.83 3.33 4 3.67 ...
##  $ Interview        : num [1:163] 3.5 3.61 3.42 4.48 4.82 3.54 3.87 3.54 4.08 5 ...
##  $ Performance      : num [1:163] 2.35 1.54 3.99 3.78 3.77 3.51 3.65 1.55 2.51 3.63 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   EmployeeID = col_double(),
##   ..   Conscientiousness = col_double(),
##   ..   Interview = col_double(),
##   ..   Performance = col_double()
##   .. )</code></pre>
<div class="sourceCode" id="cb1089"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1089-1"><a href="criterionrelatedvalidity.html#cb1089-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View first 6 rows of data frame</span></span>
<span id="cb1089-2"><a href="criterionrelatedvalidity.html#cb1089-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   EmployeeID Conscientiousness Interview Performance
##        &lt;dbl&gt;             &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1          1              3.33      3.5         2.35
## 2          2              3.83      3.61        1.54
## 3          3              3.33      3.42        3.99
## 4          4              4         4.48        3.78
## 5          5              3.67      4.82        3.77
## 6          6              4         3.54        3.51</code></pre>
<p>The data frame contains 4 variables and 163 cases (i.e., employees): <code>EmployeeID</code>, <code>Conscientiousness</code>, <code>Interview</code>, and <code>Performance</code>. Let’s assume that these data were collected as part of a concurrent validation study aimed at estimating the criterion-related validity of selection tools (e.g., procedures, assessments, tests); this means that the selection tools (i.e., <code>Conscientiousness</code>, <code>Interview</code>) were administered to job incumbents and the criterion measure (<code>Performance</code>) was administered at about the same time. To begin, <code>EmployeeID</code> is the unique identifier variable. The <code>Conscientiousness</code> variable contains the scores on a personality test designed to “tap into” the psychological concept of conscientiousness; potential scores on this variable could range from 1 (<em>low conscientiousness</em>) to 5 (<em>high conscientiousness</em>). The <code>Interview</code> variable contains the scores for a structured interview designed to assess interviewees’ level customer-service knowledge and skills; potential scores on this variable could range from 1 (<em>poor customer service</em>) to 5 (<em>strong customer service</em>). Finally, the <em>criterion</em> for this concurrent validation study is the <code>Performance</code> variable, which contains the job performance evaluation ratings for the job incumbents; potential scores on this variable could range from 1 (<em>does not meet performance standards</em>) to 5 (<em>exceeds performance standards</em>).</p>
</div>
<div id="scatterplot_criterionrelatedvalidity" class="section level3" number="35.2.4">
<h3><span class="header-section-number">35.2.4</span> Visualize Association Using a Scatter Plot</h3>
<p>Two of the key statistical assumptions that should be satisfied prior to estimating a Pearson product-moment correlation are that (a) the association between the two variables is approximately linear and that (b) a bivariate normal distribution exists between the two variables. A data visualization called a <strong>scatter plot</strong> can be used to test both of these assumptions.</p>
<p>The <code>ScatterPlot</code> function from the <code>lessR</code> package does a nice job generate generating scatter plots – and it even provides an estimate of the correlation by default. If you haven’t already, install and access the <code>lessR</code> package.</p>
<div class="sourceCode" id="cb1091"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1091-1"><a href="criterionrelatedvalidity.html#cb1091-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install package</span></span>
<span id="cb1091-2"><a href="criterionrelatedvalidity.html#cb1091-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;lessR&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb1092"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1092-1"><a href="criterionrelatedvalidity.html#cb1092-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access package</span></span>
<span id="cb1092-2"><a href="criterionrelatedvalidity.html#cb1092-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lessR)</span></code></pre></div>
<p>To begin, type the name of the <code>ScatterPlot</code> function. As the first two arguments of the function, type the names of the two variables you wish to visualize; let’s start by visualizing the association between the <code>Conscientiousness</code> selection tool and the criterion (<code>Performance</code>). The variable name that we type after the <code>x=</code> argument will set the x-axis, and the variable name that we type after the <code>y=</code> argument will set the y-axis. Conventionally, we place the criterion variable on the y-axis, as it is the outcome. As the third argument, use the <code>data=</code> argument to provide the name of the data frame to which the two variables belong (<code>df</code>).</p>
<div class="sourceCode" id="cb1093"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1093-1"><a href="criterionrelatedvalidity.html#cb1093-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scatter plot using ScatterPlot function from lessR</span></span>
<span id="cb1093-2"><a href="criterionrelatedvalidity.html#cb1093-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ScatterPlot</span>(<span class="at">x=</span>Conscientiousness, <span class="at">y=</span>Performance, <span class="at">data=</span>df)</span></code></pre></div>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-652-1.png" width="672" /></p>
<pre><code>## &gt;&gt;&gt; Suggestions
## Plot(Conscientiousness, Performance, fit=&quot;lm&quot;, fit_se=c(.90,.99))  # fit line, standard errors
## Plot(Conscientiousness, Performance, out_cut=.10)  # label top 10% potential outliers
## Plot(Conscientiousness, Performance, enhance=TRUE)  # many options 
## 
## 
## &gt;&gt;&gt; Pearson&#39;s product-moment correlation 
##  
## Number of paired values with neither missing, n = 163 
## 
## 
## Sample Correlation of Conscientiousness and Performance: r = 0.469 
## 
## 
## Hypothesis Test of 0 Correlation:  t = 6.732,  df = 161,  p-value = 0.000 
## 95% Confidence Interval for Correlation:  0.339 to 0.581</code></pre>
<p>In our plot window, we can see a fairly clear positive linear trend between <code>Conscientiousness</code> and <code>Performance</code>, which provides us with some evidence that the assumption of a linear association has been satisfied. Furthermore, the distribution is ellipse-shaped, which gives us some evidence that the underlying distribution between the two variables is likely bivariate normal – thereby satisfying the second assumption mentioned above. Note that the <code>ScatterPlot</code> function automatically provides an estimate of a (Pearson product-moment) correlation in the output (<em>r</em> = .509), along with the associated p-value (<em>p</em> &lt; .001).</p>
<div id="optional-stylizing-the-scatterplot-function-from-lessr" class="section level4" number="35.2.4.1">
<h4><span class="header-section-number">35.2.4.1</span> Optional: Stylizing the <code>ScatterPlot</code> Function from <code>lessR</code></h4>
<p>If you would like to optionally stylize your scatter plot, we can use the <code>xlab=</code> and <code>ylab=</code> arguments to change the default names of the x-axis and y-axis, respectively.</p>
<div class="sourceCode" id="cb1095"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1095-1"><a href="criterionrelatedvalidity.html#cb1095-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional: Styling the scatter plot</span></span>
<span id="cb1095-2"><a href="criterionrelatedvalidity.html#cb1095-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ScatterPlot</span>(<span class="at">x=</span>Conscientiousness, <span class="at">y=</span>Performance, <span class="at">data=</span>df, </span>
<span id="cb1095-3"><a href="criterionrelatedvalidity.html#cb1095-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">xlab=</span><span class="st">&quot;Conscientiousness Test Score&quot;</span>,</span>
<span id="cb1095-4"><a href="criterionrelatedvalidity.html#cb1095-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">ylab=</span><span class="st">&quot;Job Performance Score&quot;</span>)</span></code></pre></div>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-653-1.png" width="672" /></p>
<pre><code>## &gt;&gt;&gt; Suggestions
## Plot(Conscientiousness, Performance, fit=&quot;lm&quot;, fit_se=c(.90,.99))  # fit line, standard errors
## Plot(Conscientiousness, Performance, out_cut=.10)  # label top 10% potential outliers
## Plot(Conscientiousness, Performance, enhance=TRUE)  # many options 
## 
## 
## &gt;&gt;&gt; Pearson&#39;s product-moment correlation 
##  
## Number of paired values with neither missing, n = 163 
## 
## 
## Sample Correlation of Conscientiousness and Performance: r = 0.469 
## 
## 
## Hypothesis Test of 0 Correlation:  t = 6.732,  df = 161,  p-value = 0.000 
## 95% Confidence Interval for Correlation:  0.339 to 0.581</code></pre>
<p>We can also superimpose an ellipse by adding the argument <code>ellipse=TRUE</code>, which can visually aid our judgument on whether the distribution is bivariate normal.</p>
<div class="sourceCode" id="cb1097"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1097-1"><a href="criterionrelatedvalidity.html#cb1097-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatterplot using ScatterPlot function from lessR</span></span>
<span id="cb1097-2"><a href="criterionrelatedvalidity.html#cb1097-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ScatterPlot</span>(<span class="at">x=</span>Conscientiousness, <span class="at">y=</span>Performance, <span class="at">data=</span>df, </span>
<span id="cb1097-3"><a href="criterionrelatedvalidity.html#cb1097-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">xlab=</span><span class="st">&quot;Conscientiousness Test Score&quot;</span>,</span>
<span id="cb1097-4"><a href="criterionrelatedvalidity.html#cb1097-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">ylab=</span><span class="st">&quot;Job Performance Score&quot;</span>,</span>
<span id="cb1097-5"><a href="criterionrelatedvalidity.html#cb1097-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">ellipse=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [Ellipse with Murdoch and Chow&#39;s function ellipse from their ellipse package]</code></pre>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-654-1.png" width="672" /></p>
<pre><code>## &gt;&gt;&gt; Suggestions
## Plot(Conscientiousness, Performance, fit=&quot;lm&quot;, fit_se=c(.90,.99))  # fit line, standard errors
## Plot(Conscientiousness, Performance, out_cut=.10)  # label top 10% potential outliers
## Plot(Conscientiousness, Performance, enhance=TRUE)  # many options 
## 
## 
## &gt;&gt;&gt; Pearson&#39;s product-moment correlation 
##  
## Number of paired values with neither missing, n = 163 
## 
## 
## Sample Correlation of Conscientiousness and Performance: r = 0.469 
## 
## 
## Hypothesis Test of 0 Correlation:  t = 6.732,  df = 161,  p-value = 0.000 
## 95% Confidence Interval for Correlation:  0.339 to 0.581</code></pre>
</div>
</div>
<div id="estimate_correlation" class="section level3" number="35.2.5">
<h3><span class="header-section-number">35.2.5</span> Estimate Correlation</h3>
<p><strong>Important note:</strong> For space considerations, we will assume that the variables we wish to correlate have met the necessary statistical assumptions (see <a href="criterionrelatedvalidity.html#statisticalsignficance_correlation">Statistical Assumptions</a> section). For instance, we will assume that employees in this sample were randomly drawn from the underlying population of employees, that there is evidence of univariate and bivariate normal distributions for the variables in question, that the data are free of outliers, and that the association between variables is linear. To learn how to create a histogram or VBS plot (violin-box-scatter plot) to estimate the shape of the univariate distribution for each variable and to flag any potential univariate outliers, which can be used to assess the assumptions of univariate normal distribution and absence of univariate outliers, check out the chapter called <a href="descriptives.html#descriptives">Descriptive Statistics</a>.</p>
<p>There are different functions we could use to estimate a Pearson product-moment correlation between two variables (or a biserial correlation). In this chapter, I will demonstrate how to use the <code>Correlation</code> function from the <code>lessR</code> package.</p>
<p>If you haven’t already, install and access the <code>lessR</code> package using the <code>install.packages</code> and <code>library</code> functions, respectively (see above).</p>
<p>To begin, type the name of the <code>Correlation</code> function from the <code>lessR</code> package. As the first two arguments of the function, type the names of the two variables you wish to visualize; let’s start by visualizing the association between the <code>Conscientiousness</code> selection tool and the criterion (<code>Performance</code>). Conventionally, the variable name that appears after the <code>x=</code> argument is our predictor (e.g., selection tool), and the variable name that appears after the <code>y=</code> argument is our criterion (e.g., job performance). As the third argument, use the <code>data=</code> argument to provide the name of the data frame to which the two variables belong (<code>df</code>).</p>
<div class="sourceCode" id="cb1100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1100-1"><a href="criterionrelatedvalidity.html#cb1100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate correlation using Correlation function from lessR</span></span>
<span id="cb1100-2"><a href="criterionrelatedvalidity.html#cb1100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Correlation</span>(<span class="at">x=</span>Conscientiousness, <span class="at">y=</span>Performance, <span class="at">data=</span>df)</span></code></pre></div>
<pre><code>## Correlation Analysis for Variables  and Performance 
## --------------------------------------------------- 
## &gt;&gt;&gt; Pearson&#39;s product-moment correlation 
##  
## Number of paired values with neither missing, n = 163 
## Number of cases (rows of data) deleted: 0 
## 
## 
## Sample Covariance: s = 0.324 
##  
## Sample Correlation: r = 0.469 
## 
## 
## Hypothesis Test of 0 Correlation:  t = 6.732,  df = 161,  p-value = 0.000 
## 95% Confidence Interval for Correlation:  0.339 to 0.581</code></pre>
<p>As you can see, we find the following: <em>r</em> = .469, <em>p</em> &lt; .001, 95% CI[.339, .581]. We can interpret the finding as follows: Scores on the conscientiousness test are positively associated with job performance scores to a statistically significant extent (<em>r</em> = .469, <em>p</em> &lt; .001, 95% CI[.339, .581]), such that individuals with higher conscientiousness tend to have higher job performance. How do we know the correlation coefficient is statistically significant? Well, the <em>p</em>-value is less than the conventional alpha cutoff of .05. Given the conventional rules of thumb for interpreting a correlation coefficient as an effect size (see <a href="criterionrelatedvalidity.html#practicalsignficance_correlation">Practical Significance</a> section), we can describe this correlation coefficient of .469 as approximately medium or medium-to-large in magnitude. The <em>point estimate</em> of the correlation coefficient (<em>r</em> = .469) does not directly reflect the sampling error that inevitably affects the estimated correlation coefficient derived from our sample; this is where the confidence interval can augment our interpretation by expressing a range, within which we can be reasonably confident that the true (population) correlation coefficient likely falls. With regard to the 95% confidence interval, it is likely that the range from .339 to .581 contains the true (population) correlation; that is, the true (population) correlation coefficient is likely somewhere between medium and large in magnitude.</p>
<p>In the context of selection tool validation, the correlation coefficient between a selection tool and a criterion can be used as an indicator of criterion-related validity. Because the correlation above is statistically significant, this provides initial evidence that the conscientiousness test has sufficiently high criterion-related validity, as it appears to be significantly associated with the criterion of job performance. In this context, we can refer to the correlation coefficient as a <strong>validity coefficient</strong>. Moreover, the practical significance (as indicated by the effect size) is approximately medium or medium-to-large, given the thresholds mentioned above. Thus, as a selection tool, the conscientiousness test appears to have relatively good criterion-related validity for this population.</p>
</div>
<div id="summary_criterionrelatedvalidity" class="section level3" number="35.2.6">
<h3><span class="header-section-number">35.2.6</span> Summary</h3>
<p>In this chapter, we learned how to create a scatter plot using the <code>ScatterPlot</code> function from the <code>lessR</code> package, and how to estimate a correlation using the <code>Correlation</code> function from the <code>lessR</code> package.</p>
</div>
</div>
<div id="criterionrelatedvalidity_supplement" class="section level2" number="35.3">
<h2><span class="header-section-number">35.3</span> Chapter Supplement</h2>
<p>In addition to the <code>Correlation</code> function from the <code>lessR</code> package covered <a href="criterionrelatedvalidity.html#estimate_correlation">above</a>, we can use the <code>cor</code> and <code>cor.test</code> functions from base R to estimate a correlation. Because this function comes from base R, we do not need to install and access an additional package.</p>
<div id="criterionrelatedvalidity_supplement_functions" class="section level3" number="35.3.1">
<h3><span class="header-section-number">35.3.1</span> Functions &amp; Packages Introduced</h3>
<table>
<thead>
<tr class="header">
<th>Function</th>
<th>Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>cor</code></td>
<td>base R</td>
</tr>
<tr class="even">
<td><code>cor.test</code></td>
<td>base R</td>
</tr>
</tbody>
</table>
</div>
<div id="criterionrelatedvalidity_initsteps_supplement" class="section level3" number="35.3.2">
<h3><span class="header-section-number">35.3.2</span> Initial Steps</h3>
<p>If required, please refer to the <a href="criterionrelatedvalidity.html#initsteps_criterionrelatedvalidity">Initial Steps</a> section from this chapter for more information on these initial steps.</p>
<div class="sourceCode" id="cb1102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1102-1"><a href="criterionrelatedvalidity.html#cb1102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your working directory</span></span>
<span id="cb1102-2"><a href="criterionrelatedvalidity.html#cb1102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;H:/RWorkshop&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb1103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1103-1"><a href="criterionrelatedvalidity.html#cb1103-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install readr package if you haven&#39;t already</span></span>
<span id="cb1103-2"><a href="criterionrelatedvalidity.html#cb1103-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Note: You don&#39;t need to install a package every </span></span>
<span id="cb1103-3"><a href="criterionrelatedvalidity.html#cb1103-3" aria-hidden="true" tabindex="-1"></a><span class="co"># time you wish to access it]</span></span>
<span id="cb1103-4"><a href="criterionrelatedvalidity.html#cb1103-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;readr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb1104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1104-1"><a href="criterionrelatedvalidity.html#cb1104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access readr package</span></span>
<span id="cb1104-2"><a href="criterionrelatedvalidity.html#cb1104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1104-3"><a href="criterionrelatedvalidity.html#cb1104-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1104-4"><a href="criterionrelatedvalidity.html#cb1104-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data and name data frame (tibble) object</span></span>
<span id="cb1104-5"><a href="criterionrelatedvalidity.html#cb1104-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;SelectionData.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification ---------------------------------------------------------------------------------------------
## cols(
##   EmployeeID = col_double(),
##   Conscientiousness = col_double(),
##   Interview = col_double(),
##   Performance = col_double()
## )</code></pre>
<div class="sourceCode" id="cb1106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1106-1"><a href="criterionrelatedvalidity.html#cb1106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the names of the variables in the data frame (tibble) objects</span></span>
<span id="cb1106-2"><a href="criterionrelatedvalidity.html#cb1106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df)</span></code></pre></div>
<pre><code>## [1] &quot;EmployeeID&quot;        &quot;Conscientiousness&quot; &quot;Interview&quot;         &quot;Performance&quot;</code></pre>
<div class="sourceCode" id="cb1108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1108-1"><a href="criterionrelatedvalidity.html#cb1108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View variable type for each variable in data frame</span></span>
<span id="cb1108-2"><a href="criterionrelatedvalidity.html#cb1108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code></pre></div>
<pre><code>## spec_tbl_df[,4] [163 x 4] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ EmployeeID       : num [1:163] 1 2 3 4 5 6 7 8 9 10 ...
##  $ Conscientiousness: num [1:163] 3.33 3.83 3.33 4 3.67 ...
##  $ Interview        : num [1:163] 3.5 3.61 3.42 4.48 4.82 3.54 3.87 3.54 4.08 5 ...
##  $ Performance      : num [1:163] 2.35 1.54 3.99 3.78 3.77 3.51 3.65 1.55 2.51 3.63 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   EmployeeID = col_double(),
##   ..   Conscientiousness = col_double(),
##   ..   Interview = col_double(),
##   ..   Performance = col_double()
##   .. )</code></pre>
<div class="sourceCode" id="cb1110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1110-1"><a href="criterionrelatedvalidity.html#cb1110-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View first 6 rows of data frame</span></span>
<span id="cb1110-2"><a href="criterionrelatedvalidity.html#cb1110-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   EmployeeID Conscientiousness Interview Performance
##        &lt;dbl&gt;             &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1          1              3.33      3.5         2.35
## 2          2              3.83      3.61        1.54
## 3          3              3.33      3.42        3.99
## 4          4              4         4.48        3.78
## 5          5              3.67      4.82        3.77
## 6          6              4         3.54        3.51</code></pre>
</div>
<div id="cor_function" class="section level3" number="35.3.3">
<h3><span class="header-section-number">35.3.3</span> <code>cor</code> Function from Base R</h3>
<p>The <code>cor</code> function from base R is a quick-and-easy approach to estimating a correlation coefficient if you’re only interested in the sign and magnitude (and not the significance level).</p>
<p>To begin, type the name of the <code>cor</code> function. As the first argument, type the name of your data frame (<code>df</code>) followed by the <code>$</code> symbol and the name of one of your continuous (interval/ratio) variables (<code>Conscientiousness</code>). As the second argument, type the name of your data frame (<code>df</code>) followed by the <code>$</code> symbol and the name of one of your continuous (interval/ratio) variables (<code>Performance</code>). Finally, as the third argument, specify <code>method="pearson"</code> to estimate a Pearson product-moment correlation. If you were estimating the association between two rank-order variables, you could replace “pearson” with “spearman” to estimate a Spearman correlation.</p>
<div class="sourceCode" id="cb1112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1112-1"><a href="criterionrelatedvalidity.html#cb1112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate correlation using cor function</span></span>
<span id="cb1112-2"><a href="criterionrelatedvalidity.html#cb1112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df<span class="sc">$</span>Conscientiousness, df<span class="sc">$</span>Performance, <span class="at">method=</span><span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 0.4686663</code></pre>
</div>
<div id="cortest_function" class="section level3" number="35.3.4">
<h3><span class="header-section-number">35.3.4</span> <code>cor.test</code> Function from Base R</h3>
<p>To estimate the correlation coefficient and associated <em>p</em>-value (along with the confidence interval), we can use the <code>cor.test</code> function from base R. By default, the alpha level is set to .05 (two-tailed), and thus a 95% confidence interval is used. As another default, the alternative/research hypothesis is that the true (population) correlation is not equal to zero. If wish to use these defaults, which would be most consistent with common practice. We can use the exact same three arguments as we used for the <code>cor</code> function above.</p>
<div class="sourceCode" id="cb1114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1114-1"><a href="criterionrelatedvalidity.html#cb1114-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate correlation using cor.test function</span></span>
<span id="cb1114-2"><a href="criterionrelatedvalidity.html#cb1114-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Conscientiousness, df<span class="sc">$</span>Performance, <span class="at">method=</span><span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  df$Conscientiousness and df$Performance
## t = 6.7318, df = 161, p-value = 0.0000000002801
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.3393973 0.5805611
## sample estimates:
##       cor 
## 0.4686663</code></pre>
<p>If we know that we have missing values (i.e., <em>missing data</em>) on at least one of the variables used to estimate the correlation, we can add the <code>na.action=na.omit</code> argument, which excludes cases with missing values on one or both of the variables. We don’t have any missing values in this data frame, so the estimate remains the same.</p>
<div class="sourceCode" id="cb1116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1116-1"><a href="criterionrelatedvalidity.html#cb1116-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate correlation using cor.test function</span></span>
<span id="cb1116-2"><a href="criterionrelatedvalidity.html#cb1116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Conscientiousness, df<span class="sc">$</span>Performance, <span class="at">method=</span><span class="st">&quot;pearson&quot;</span>, <span class="at">na.action=</span>na.omit)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  df$Conscientiousness and df$Performance
## t = 6.7318, df = 161, p-value = 0.0000000002801
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.3393973 0.5805611
## sample estimates:
##       cor 
## 0.4686663</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="disparateimpact.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="predictingcriterionscores.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
