<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 28 Disparate Impact | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION</title>
  <meta name="description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 28 Disparate Impact | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://rforhr.com" />
  <meta property="og:image" content="https://rforhr.comcover.png" />
  <meta property="og:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="github-repo" content="davidcaughlin/R-for-HR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 28 Disparate Impact | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  
  <meta name="twitter:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="twitter:image" content="https://rforhr.comcover.png" />

<meta name="author" content="David E. Caughlin" />


<meta name="date" content="2021-12-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="selection.html"/>
<link rel="next" href="create-portfolio.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for HR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#hragrowth"><i class="fa fa-check"></i><b>0.1</b> Growth of HR Analytics</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#skills-gap"><i class="fa fa-check"></i><b>0.2</b> Skills Gap</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#hraplc"><i class="fa fa-check"></i><b>0.3</b> Project Life Cycle Perspective</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#philosophy"><i class="fa fa-check"></i><b>0.4</b> My Philosophy for This Book</a>
<ul>
<li class="chapter" data-level="0.4.1" data-path="index.html"><a href="index.html#rationalerpref"><i class="fa fa-check"></i><b>0.4.1</b> Rationale for Using R</a></li>
<li class="chapter" data-level="0.4.2" data-path="index.html"><a href="index.html#audiencepref"><i class="fa fa-check"></i><b>0.4.2</b> Audience</a></li>
<li class="chapter" data-level="0.4.3" data-path="index.html"><a href="index.html#structurepref"><i class="fa fa-check"></i><b>0.4.3</b> Structure</a></li>
</ul></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#aboutauthor"><i class="fa fa-check"></i><b>0.5</b> About the Author</a></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#acknowpref"><i class="fa fa-check"></i><b>0.6</b> Acknowledgements</a></li>
</ul></li>
<li class="part"><span><b>I HR Analytics Project Life Cycle</b></span></li>
<li class="chapter" data-level="1" data-path="overviewhraplc.html"><a href="overviewhraplc.html"><i class="fa fa-check"></i><b>1</b> Overview of HR Analytics Project Life Cycle</a></li>
<li class="chapter" data-level="2" data-path="questionformulation.html"><a href="questionformulation.html"><i class="fa fa-check"></i><b>2</b> Question Formulation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="questionformulation.html"><a href="questionformulation.html#adoptstrategicmindset"><i class="fa fa-check"></i><b>2.1</b> Adopting a Strategic Mindset</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="questionformulation.html"><a href="questionformulation.html#strategy"><i class="fa fa-check"></i><b>2.1.1</b> Strategy</a></li>
<li class="chapter" data-level="2.1.2" data-path="questionformulation.html"><a href="questionformulation.html#strategyformulation"><i class="fa fa-check"></i><b>2.1.2</b> Strategy Formulation</a></li>
<li class="chapter" data-level="2.1.3" data-path="questionformulation.html"><a href="questionformulation.html#strategyimplementation"><i class="fa fa-check"></i><b>2.1.3</b> Strategy Implementation</a></li>
<li class="chapter" data-level="2.1.4" data-path="questionformulation.html"><a href="questionformulation.html#strategichrm"><i class="fa fa-check"></i><b>2.1.4</b> Strategic Human Resource Management</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="questionformulation.html"><a href="questionformulation.html#defining-problems-formulating-questions"><i class="fa fa-check"></i><b>2.2</b> Defining Problems &amp; Formulating Questions</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="questionformulation.html"><a href="questionformulation.html#definingaproblem"><i class="fa fa-check"></i><b>2.2.1</b> Defining a Problem</a></li>
<li class="chapter" data-level="2.2.2" data-path="questionformulation.html"><a href="questionformulation.html#formulatingaquestion"><i class="fa fa-check"></i><b>2.2.2</b> Formulating a Question</a></li>
<li class="chapter" data-level="2.2.3" data-path="questionformulation.html"><a href="questionformulation.html#divergentconvergentthinking"><i class="fa fa-check"></i><b>2.2.3</b> Thinking Divergently &amp; Convergently</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="questionformulation.html"><a href="questionformulation.html#summary"><i class="fa fa-check"></i><b>2.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dataacquisition.html"><a href="dataacquisition.html"><i class="fa fa-check"></i><b>3</b> Data Acquisition</a>
<ul>
<li class="chapter" data-level="3.1" data-path="dataacquisition.html"><a href="dataacquisition.html#employee-surveys"><i class="fa fa-check"></i><b>3.1</b> Employee Surveys</a></li>
<li class="chapter" data-level="3.2" data-path="dataacquisition.html"><a href="dataacquisition.html#rating-forms"><i class="fa fa-check"></i><b>3.2</b> Rating Forms</a></li>
<li class="chapter" data-level="3.3" data-path="dataacquisition.html"><a href="dataacquisition.html#surveillance-monitoring"><i class="fa fa-check"></i><b>3.3</b> Surveillance &amp; Monitoring</a></li>
<li class="chapter" data-level="3.4" data-path="dataacquisition.html"><a href="dataacquisition.html#database-queries"><i class="fa fa-check"></i><b>3.4</b> Database Queries</a></li>
<li class="chapter" data-level="3.5" data-path="dataacquisition.html"><a href="dataacquisition.html#scraping"><i class="fa fa-check"></i><b>3.5</b> Scraping</a></li>
<li class="chapter" data-level="3.6" data-path="dataacquisition.html"><a href="dataacquisition.html#summary-1"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="datamanagement.html"><a href="datamanagement.html"><i class="fa fa-check"></i><b>4</b> Data Management</a>
<ul>
<li class="chapter" data-level="4.1" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_clean"><i class="fa fa-check"></i><b>4.1</b> Data Cleaning</a></li>
<li class="chapter" data-level="4.2" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_manipulate"><i class="fa fa-check"></i><b>4.2</b> Data Manipulation &amp; Structuring</a></li>
<li class="chapter" data-level="4.3" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_tools"><i class="fa fa-check"></i><b>4.3</b> Common Data-Management Tools</a></li>
<li class="chapter" data-level="4.4" data-path="datamanagement.html"><a href="datamanagement.html#summary-2"><i class="fa fa-check"></i><b>4.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dataanalysis.html"><a href="dataanalysis.html"><i class="fa fa-check"></i><b>5</b> Data Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="dataanalysis.html"><a href="dataanalysis.html#dataanalysis_toolstechniques"><i class="fa fa-check"></i><b>5.1</b> Tools &amp; Techniques</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="dataanalysis.html"><a href="dataanalysis.html#mathematics"><i class="fa fa-check"></i><b>5.1.1</b> Mathematics</a></li>
<li class="chapter" data-level="5.1.2" data-path="dataanalysis.html"><a href="dataanalysis.html#statistics"><i class="fa fa-check"></i><b>5.1.2</b> Statistics</a></li>
<li class="chapter" data-level="5.1.3" data-path="dataanalysis.html"><a href="dataanalysis.html#machinelearning"><i class="fa fa-check"></i><b>5.1.3</b> Machine Learning</a></li>
<li class="chapter" data-level="5.1.4" data-path="dataanalysis.html"><a href="dataanalysis.html#computationalmodelsimulation"><i class="fa fa-check"></i><b>5.1.4</b> Computational Modeling &amp; Simulations</a></li>
<li class="chapter" data-level="5.1.5" data-path="dataanalysis.html"><a href="dataanalysis.html#textqualitativeanalyses"><i class="fa fa-check"></i><b>5.1.5</b> Text Analyses &amp; Qualitative Analyses</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="dataanalysis.html"><a href="dataanalysis.html#continuum_dataanalytics"><i class="fa fa-check"></i><b>5.2</b> Continuum of Data Analytics</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="dataanalysis.html"><a href="dataanalysis.html#descriptive_analytics"><i class="fa fa-check"></i><b>5.2.1</b> Descriptive Analytics</a></li>
<li class="chapter" data-level="5.2.2" data-path="dataanalysis.html"><a href="dataanalysis.html#predictish_analytics"><i class="fa fa-check"></i><b>5.2.2</b> Predict-ish Analytics</a></li>
<li class="chapter" data-level="5.2.3" data-path="dataanalysis.html"><a href="dataanalysis.html#predictive_analytics"><i class="fa fa-check"></i><b>5.2.3</b> Predictive Analytics</a></li>
<li class="chapter" data-level="5.2.4" data-path="dataanalysis.html"><a href="dataanalysis.html#prescriptive_analytics"><i class="fa fa-check"></i><b>5.2.4</b> Prescriptive Analytics</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="dataanalysis.html"><a href="dataanalysis.html#summary-3"><i class="fa fa-check"></i><b>5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html"><i class="fa fa-check"></i><b>6</b> Data Interpretation &amp; Storytelling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#datainterpretation"><i class="fa fa-check"></i><b>6.1</b> Data Interpretation</a></li>
<li class="chapter" data-level="6.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling"><i class="fa fa-check"></i><b>6.2</b> Storytelling</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#structure"><i class="fa fa-check"></i><b>6.2.1</b> Structure</a></li>
<li class="chapter" data-level="6.2.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#clarity-parsimony"><i class="fa fa-check"></i><b>6.2.2</b> Clarity &amp; Parsimony</a></li>
<li class="chapter" data-level="6.2.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#influence-persuasion"><i class="fa fa-check"></i><b>6.2.3</b> Influence &amp; Persuasion</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling_withdata"><i class="fa fa-check"></i><b>6.3</b> Storytelling with Data</a></li>
<li class="chapter" data-level="6.4" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#summary-4"><i class="fa fa-check"></i><b>6.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html"><i class="fa fa-check"></i><b>7</b> Deployment &amp; Implementation</a></li>
<li class="part"><span><b>II Introduction to R</b></span></li>
<li class="chapter" data-level="8" data-path="overviewR.html"><a href="overviewR.html"><i class="fa fa-check"></i><b>8</b> Overview of R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="8.1" data-path="overviewR.html"><a href="overviewR.html#R_overview"><i class="fa fa-check"></i><b>8.1</b> R Programming Language</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="overviewR.html"><a href="overviewR.html#R_what"><i class="fa fa-check"></i><b>8.1.1</b> What Is R?</a></li>
<li class="chapter" data-level="8.1.2" data-path="overviewR.html"><a href="overviewR.html#R_why"><i class="fa fa-check"></i><b>8.1.2</b> Why Use R?</a></li>
<li class="chapter" data-level="8.1.3" data-path="overviewR.html"><a href="overviewR.html#R_who"><i class="fa fa-check"></i><b>8.1.3</b> Who Uses R?</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="overviewR.html"><a href="overviewR.html#RStudio_overview"><i class="fa fa-check"></i><b>8.2</b> RStudio</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="overviewR.html"><a href="overviewR.html#RStudio_what"><i class="fa fa-check"></i><b>8.2.1</b> What is RStudio?</a></li>
<li class="chapter" data-level="8.2.2" data-path="overviewR.html"><a href="overviewR.html#RStudio_why"><i class="fa fa-check"></i><b>8.2.2</b> Why RStudio?</a></li>
<li class="chapter" data-level="8.2.3" data-path="overviewR.html"><a href="overviewR.html#RStudio_who"><i class="fa fa-check"></i><b>8.2.3</b> Who Uses RStudio?</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="overviewR.html"><a href="overviewR.html#packages_overview"><i class="fa fa-check"></i><b>8.3</b> Packages</a></li>
<li class="chapter" data-level="8.4" data-path="overviewR.html"><a href="overviewR.html#summary-5"><i class="fa fa-check"></i><b>8.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>9</b> Installing R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="9.1" data-path="install.html"><a href="install.html#installR"><i class="fa fa-check"></i><b>9.1</b> Downloading &amp; Installing R</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="install.html"><a href="install.html#for-windows-operation-systems"><i class="fa fa-check"></i><b>9.1.1</b> For Windows Operation Systems</a></li>
<li class="chapter" data-level="9.1.2" data-path="install.html"><a href="install.html#for-mac-operating-systems"><i class="fa fa-check"></i><b>9.1.2</b> For Mac Operating Systems</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="install.html"><a href="install.html#installRStudio"><i class="fa fa-check"></i><b>9.2</b> Downloading &amp; Installing RStudio</a></li>
<li class="chapter" data-level="9.3" data-path="install.html"><a href="install.html#summary-6"><i class="fa fa-check"></i><b>9.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="gettingstarted.html"><a href="gettingstarted.html"><i class="fa fa-check"></i><b>10</b> Getting Started with R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="10.1" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation-to-rstudio"><i class="fa fa-check"></i><b>10.1</b> Orientation to RStudio</a></li>
<li class="chapter" data-level="10.2" data-path="gettingstarted.html"><a href="gettingstarted.html#createRscript"><i class="fa fa-check"></i><b>10.2</b> Creating &amp; Saving an R Script</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-a-new-r-script"><i class="fa fa-check"></i><b>10.2.1</b> Creating a New R Script</a></li>
<li class="chapter" data-level="10.2.2" data-path="gettingstarted.html"><a href="gettingstarted.html#using-an-r-script"><i class="fa fa-check"></i><b>10.2.2</b> Using an R Script</a></li>
<li class="chapter" data-level="10.2.3" data-path="gettingstarted.html"><a href="gettingstarted.html#saving-an-r-script"><i class="fa fa-check"></i><b>10.2.3</b> Saving an R Script</a></li>
<li class="chapter" data-level="10.2.4" data-path="gettingstarted.html"><a href="gettingstarted.html#opening-a-saved-r-script"><i class="fa fa-check"></i><b>10.2.4</b> Opening a Saved R Script</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-an-rstudio-project"><i class="fa fa-check"></i><b>10.3</b> Creating an RStudio Project</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-a-new-rstudio-project"><i class="fa fa-check"></i><b>10.3.1</b> Creating a New RStudio Project</a></li>
<li class="chapter" data-level="10.3.2" data-path="gettingstarted.html"><a href="gettingstarted.html#opening-an-existing-rstudio-project"><i class="fa fa-check"></i><b>10.3.2</b> Opening an Existing RStudio Project</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation-to-written-tutorials"><i class="fa fa-check"></i><b>10.4</b> Orientation to Written Tutorials</a></li>
<li class="chapter" data-level="10.5" data-path="gettingstarted.html"><a href="gettingstarted.html#summary-7"><i class="fa fa-check"></i><b>10.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="gentleintro.html"><a href="gentleintro.html"><i class="fa fa-check"></i><b>11</b> Basic Features and Operations of the R Language</a>
<ul>
<li class="chapter" data-level="11.1" data-path="gentleintro.html"><a href="gentleintro.html#r_as_calculator"><i class="fa fa-check"></i><b>11.1</b> R as a Calculator</a></li>
<li class="chapter" data-level="11.2" data-path="gentleintro.html"><a href="gentleintro.html#functions"><i class="fa fa-check"></i><b>11.2</b> Functions</a></li>
<li class="chapter" data-level="11.3" data-path="gentleintro.html"><a href="gentleintro.html#packages"><i class="fa fa-check"></i><b>11.3</b> Packages</a></li>
<li class="chapter" data-level="11.4" data-path="gentleintro.html"><a href="gentleintro.html#variableassignment"><i class="fa fa-check"></i><b>11.4</b> Variable Assignment</a></li>
<li class="chapter" data-level="11.5" data-path="gentleintro.html"><a href="gentleintro.html#typesofdata"><i class="fa fa-check"></i><b>11.5</b> Types of Data</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="gentleintro.html"><a href="gentleintro.html#numeric-data"><i class="fa fa-check"></i><b>11.5.1</b> <code>numeric</code> Data</a></li>
<li class="chapter" data-level="11.5.2" data-path="gentleintro.html"><a href="gentleintro.html#character-data"><i class="fa fa-check"></i><b>11.5.2</b> <code>character</code> Data</a></li>
<li class="chapter" data-level="11.5.3" data-path="gentleintro.html"><a href="gentleintro.html#date-data"><i class="fa fa-check"></i><b>11.5.3</b> <code>Date</code> Data</a></li>
<li class="chapter" data-level="11.5.4" data-path="gentleintro.html"><a href="gentleintro.html#logical-data"><i class="fa fa-check"></i><b>11.5.4</b> <code>logical</code> Data</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="gentleintro.html"><a href="gentleintro.html#vectors"><i class="fa fa-check"></i><b>11.6</b> Vectors</a></li>
<li class="chapter" data-level="11.7" data-path="gentleintro.html"><a href="gentleintro.html#lists"><i class="fa fa-check"></i><b>11.7</b> Lists</a></li>
<li class="chapter" data-level="11.8" data-path="gentleintro.html"><a href="gentleintro.html#dataframes"><i class="fa fa-check"></i><b>11.8</b> Data Frames</a></li>
<li class="chapter" data-level="11.9" data-path="gentleintro.html"><a href="gentleintro.html#annotate"><i class="fa fa-check"></i><b>11.9</b> Annotations</a></li>
<li class="chapter" data-level="11.10" data-path="gentleintro.html"><a href="gentleintro.html#summary-8"><i class="fa fa-check"></i><b>11.10</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="setwd.html"><a href="setwd.html"><i class="fa fa-check"></i><b>12</b> Setting a Working Directory</a>
<ul>
<li class="chapter" data-level="12.0.1" data-path="setwd.html"><a href="setwd.html#identify-the-current-working-directory"><i class="fa fa-check"></i><b>12.0.1</b> Identify the Current Working Directory</a></li>
<li class="chapter" data-level="12.0.2" data-path="setwd.html"><a href="setwd.html#set-a-new-working-directory"><i class="fa fa-check"></i><b>12.0.2</b> Set a New Working Directory</a></li>
<li class="chapter" data-level="12.1" data-path="setwd.html"><a href="setwd.html#summary-9"><i class="fa fa-check"></i><b>12.1</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>III Data Acquisition &amp; Management</b></span></li>
<li class="chapter" data-level="13" data-path="read.html"><a href="read.html"><i class="fa fa-check"></i><b>13</b> Reading Data into R</a>
<ul>
<li class="chapter" data-level="13.1" data-path="read.html"><a href="read.html#readcsv"><i class="fa fa-check"></i><b>13.1</b> Read a .csv File</a></li>
<li class="chapter" data-level="13.2" data-path="read.html"><a href="read.html#readxlsx"><i class="fa fa-check"></i><b>13.2</b> Read a .xlsx File</a></li>
<li class="chapter" data-level="13.3" data-path="read.html"><a href="read.html#read_summary"><i class="fa fa-check"></i><b>13.3</b> Summary</a></li>
<li class="chapter" data-level="13.4" data-path="read.html"><a href="read.html#read_supplement"><i class="fa fa-check"></i><b>13.4</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="read.html"><a href="read.html#read_additionalfunctions"><i class="fa fa-check"></i><b>13.4.1</b> Additional Functions to Read a .csv File</a></li>
<li class="chapter" data-level="13.4.2" data-path="read.html"><a href="read.html#read_skiprows"><i class="fa fa-check"></i><b>13.4.2</b> Skip Rows of Data During Read</a></li>
<li class="chapter" data-level="13.4.3" data-path="read.html"><a href="read.html#listdatafiles"><i class="fa fa-check"></i><b>13.4.3</b> List Data File Names in Working Directory</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="addnames.html"><a href="addnames.html"><i class="fa fa-check"></i><b>14</b> Removing and Adding Variable Names</a>
<ul>
<li class="chapter" data-level="14.1" data-path="addnames.html"><a href="addnames.html#remove-variable-names-from-a-data-frame-object"><i class="fa fa-check"></i><b>14.1</b> Remove Variable Names from a Data Frame Object</a></li>
<li class="chapter" data-level="14.2" data-path="addnames.html"><a href="addnames.html#add-variable-names-to-a-data-frame-object"><i class="fa fa-check"></i><b>14.2</b> Add Variable Names to a Data Frame Object</a></li>
<li class="chapter" data-level="14.3" data-path="addnames.html"><a href="addnames.html#summary-10"><i class="fa fa-check"></i><b>14.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="write.html"><a href="write.html"><i class="fa fa-check"></i><b>15</b> Writing Data from R</a>
<ul>
<li class="chapter" data-level="15.1" data-path="write.html"><a href="write.html#write-data-frame-to-working-directory"><i class="fa fa-check"></i><b>15.1</b> Write Data Frame to Working Directory</a></li>
<li class="chapter" data-level="15.2" data-path="write.html"><a href="write.html#write-table-to-working-directory"><i class="fa fa-check"></i><b>15.2</b> Write Table to Working Directory</a></li>
<li class="chapter" data-level="15.3" data-path="write.html"><a href="write.html#summary-11"><i class="fa fa-check"></i><b>15.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>16</b> Arranging (Sorting) Data</a>
<ul>
<li class="chapter" data-level="16.1" data-path="arrange.html"><a href="arrange.html#arrangebyvalues"><i class="fa fa-check"></i><b>16.1</b> Arrange (Sort) Data</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="arrange.html"><a href="arrange.html#opt1_arrange_withpipe"><i class="fa fa-check"></i><b>16.1.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="16.1.2" data-path="arrange.html"><a href="arrange.html#opt1_arrange_withoutpipe"><i class="fa fa-check"></i><b>16.1.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="arrange.html"><a href="arrange.html#summary-12"><i class="fa fa-check"></i><b>16.2</b> Summary</a></li>
<li class="chapter" data-level="16.3" data-path="arrange.html"><a href="arrange.html#arrange_supplement"><i class="fa fa-check"></i><b>16.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="arrange.html"><a href="arrange.html#arrange_orderfunction"><i class="fa fa-check"></i><b>16.3.1</b> <code>order</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="join.html"><a href="join.html"><i class="fa fa-check"></i><b>17</b> Joining (Merging) Data</a>
<ul>
<li class="chapter" data-level="17.1" data-path="join.html"><a href="join.html#horizontaljoin"><i class="fa fa-check"></i><b>17.1</b> Horizontal Join (Merge)</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="join.html"><a href="join.html#opt2_join_withpipe"><i class="fa fa-check"></i><b>17.1.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="17.1.2" data-path="join.html"><a href="join.html#opt2_join_withoutpipe"><i class="fa fa-check"></i><b>17.1.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="join.html"><a href="join.html#verticaljoin"><i class="fa fa-check"></i><b>17.2</b> Vertical Join (Merge)</a></li>
<li class="chapter" data-level="17.3" data-path="join.html"><a href="join.html#summary-13"><i class="fa fa-check"></i><b>17.3</b> Summary</a></li>
<li class="chapter" data-level="17.4" data-path="join.html"><a href="join.html#join_supplement"><i class="fa fa-check"></i><b>17.4</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="join.html"><a href="join.html#join_mergefunction"><i class="fa fa-check"></i><b>17.4.1</b> <code>merge</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>18</b> Filtering Data</a>
<ul>
<li class="chapter" data-level="18.1" data-path="filter.html"><a href="filter.html#filter_cases"><i class="fa fa-check"></i><b>18.1</b> Filter Cases from Data Frame</a>
<ul>
<li class="chapter" data-level="18.1.1" data-path="filter.html"><a href="filter.html#with-pipes"><i class="fa fa-check"></i><b>18.1.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="18.1.2" data-path="filter.html"><a href="filter.html#without-pipes"><i class="fa fa-check"></i><b>18.1.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="filter.html"><a href="filter.html#remove-single-variable-from-data-frame"><i class="fa fa-check"></i><b>18.2</b> Remove Single Variable from Data Frame</a></li>
<li class="chapter" data-level="18.3" data-path="filter.html"><a href="filter.html#select_multiplevariables"><i class="fa fa-check"></i><b>18.3</b> Select Multiple Variables from Data Frame</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="filter.html"><a href="filter.html#with-pipe"><i class="fa fa-check"></i><b>18.3.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="18.3.2" data-path="filter.html"><a href="filter.html#without-pipe"><i class="fa fa-check"></i><b>18.3.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="filter.html"><a href="filter.html#remove_multiplevariables"><i class="fa fa-check"></i><b>18.4</b> Remove Multiple Variables from Data Frame</a>
<ul>
<li class="chapter" data-level="18.4.1" data-path="filter.html"><a href="filter.html#with-pipe-1"><i class="fa fa-check"></i><b>18.4.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="18.4.2" data-path="filter.html"><a href="filter.html#without-pipe-1"><i class="fa fa-check"></i><b>18.4.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="filter.html"><a href="filter.html#summary-14"><i class="fa fa-check"></i><b>18.5</b> Summary</a></li>
<li class="chapter" data-level="18.6" data-path="filter.html"><a href="filter.html#filter_supplement"><i class="fa fa-check"></i><b>18.6</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="18.6.1" data-path="filter.html"><a href="filter.html#filter_subset_supplement"><i class="fa fa-check"></i><b>18.6.1</b> <code>subset</code> Function from Base R</a></li>
<li class="chapter" data-level="18.6.2" data-path="filter.html"><a href="filter.html#str_detect_supp"><i class="fa fa-check"></i><b>18.6.2</b> Filter by Pattern Contained within String</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="clean.html"><a href="clean.html"><i class="fa fa-check"></i><b>19</b> Cleaning Data</a>
<ul>
<li class="chapter" data-level="19.1" data-path="clean.html"><a href="clean.html#review-data"><i class="fa fa-check"></i><b>19.1</b> Review Data</a></li>
<li class="chapter" data-level="19.2" data-path="clean.html"><a href="clean.html#clean-data"><i class="fa fa-check"></i><b>19.2</b> Clean Data</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="clean.html"><a href="clean.html#replace-a-specific-value-for-a-specific-case"><i class="fa fa-check"></i><b>19.2.1</b> Replace a Specific Value for a Specific Case</a></li>
<li class="chapter" data-level="19.2.2" data-path="clean.html"><a href="clean.html#replace-a-specific-value-for-all-cases-with-a-particular-value"><i class="fa fa-check"></i><b>19.2.2</b> Replace a Specific Value for All Cases with a Particular Value</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="clean.html"><a href="clean.html#rename-variables"><i class="fa fa-check"></i><b>19.3</b> Rename Variables</a></li>
<li class="chapter" data-level="19.4" data-path="clean.html"><a href="clean.html#other-approaches-to-cleaning-data"><i class="fa fa-check"></i><b>19.4</b> Other Approaches to Cleaning Data</a>
<ul>
<li class="chapter" data-level="19.4.1" data-path="clean.html"><a href="clean.html#changing-the-case-of-variable-names"><i class="fa fa-check"></i><b>19.4.1</b> Changing the Case of Variable Names</a></li>
<li class="chapter" data-level="19.4.2" data-path="clean.html"><a href="clean.html#changing-the-case-of-character-variable-values"><i class="fa fa-check"></i><b>19.4.2</b> Changing the Case of Character Variable Values</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="clean.html"><a href="clean.html#summary-15"><i class="fa fa-check"></i><b>19.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="aggregatesegment.html"><a href="aggregatesegment.html"><i class="fa fa-check"></i><b>20</b> Aggregating &amp; Segmenting Data</a>
<ul>
<li class="chapter" data-level="20.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup"><i class="fa fa-check"></i><b>20.1</b> Counts By Group</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup_pipes"><i class="fa fa-check"></i><b>20.1.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="20.1.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup_nopipes"><i class="fa fa-check"></i><b>20.1.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup"><i class="fa fa-check"></i><b>20.2</b> Measures of Central Tendency and Dispersion By Group</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup_pipes"><i class="fa fa-check"></i><b>20.2.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="20.2.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup_nopipes"><i class="fa fa-check"></i><b>20.2.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable"><i class="fa fa-check"></i><b>20.3</b> Add Variable to Data Frame Containing Aggregated Values</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable_pipes"><i class="fa fa-check"></i><b>20.3.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="20.3.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable_nopipes"><i class="fa fa-check"></i><b>20.3.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="aggregatesegment.html"><a href="aggregatesegment.html#visualize_bygroup"><i class="fa fa-check"></i><b>20.4</b> Visualize Data By Group</a></li>
<li class="chapter" data-level="20.5" data-path="aggregatesegment.html"><a href="aggregatesegment.html#summary-16"><i class="fa fa-check"></i><b>20.5</b> Summary</a></li>
<li class="chapter" data-level="20.6" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_supplement"><i class="fa fa-check"></i><b>20.6</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="20.6.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_subset_supplement"><i class="fa fa-check"></i><b>20.6.1</b> <code>describeBy</code> Function from <code>psych</code> Package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="21" data-path="manipulate.html"><a href="manipulate.html"><i class="fa fa-check"></i><b>21</b> Manipulating &amp; Restructuring Data</a>
<ul>
<li class="chapter" data-level="21.1" data-path="manipulate.html"><a href="manipulate.html#widetolong"><i class="fa fa-check"></i><b>21.1</b> Wide-to-Long Format Data Manipulation</a>
<ul>
<li class="chapter" data-level="21.1.1" data-path="manipulate.html"><a href="manipulate.html#widetolong_withpipe"><i class="fa fa-check"></i><b>21.1.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="21.1.2" data-path="manipulate.html"><a href="manipulate.html#widetolong_withoutpipe"><i class="fa fa-check"></i><b>21.1.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="manipulate.html"><a href="manipulate.html#longtowide"><i class="fa fa-check"></i><b>21.2</b> Long-to-Wide Format Data Manipulation</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="manipulate.html"><a href="manipulate.html#longtowide_withpipe"><i class="fa fa-check"></i><b>21.2.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="21.2.2" data-path="manipulate.html"><a href="manipulate.html#longtowide_withoutpipe"><i class="fa fa-check"></i><b>21.2.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="manipulate.html"><a href="manipulate.html#summary-17"><i class="fa fa-check"></i><b>21.3</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>IV Employee Demographics</b></span></li>
<li class="chapter" data-level="22" data-path="employeedemographics.html"><a href="employeedemographics.html"><i class="fa fa-check"></i><b>22</b> Introduction to Employee Demographics</a></li>
<li class="chapter" data-level="23" data-path="descriptives.html"><a href="descriptives.html"><i class="fa fa-check"></i><b>23</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="23.1" data-path="descriptives.html"><a href="descriptives.html#determine_measurementscale"><i class="fa fa-check"></i><b>23.1</b> Determine the Measurement Scale</a></li>
<li class="chapter" data-level="23.2" data-path="descriptives.html"><a href="descriptives.html#describe_nominal_ordinal"><i class="fa fa-check"></i><b>23.2</b> Describe Nominal &amp; Ordinal (Categorical) Variables</a>
<ul>
<li class="chapter" data-level="23.2.1" data-path="descriptives.html"><a href="descriptives.html#compute_counts"><i class="fa fa-check"></i><b>23.2.1</b> Compute Counts &amp; Frequencies</a></li>
<li class="chapter" data-level="23.2.2" data-path="descriptives.html"><a href="descriptives.html#datavisualizations_nominal_ordinal"><i class="fa fa-check"></i><b>23.2.2</b> Create Data Visualizations</a></li>
</ul></li>
<li class="chapter" data-level="23.3" data-path="descriptives.html"><a href="descriptives.html#describe_interval_ratio"><i class="fa fa-check"></i><b>23.3</b> Describe Interval &amp; Ratio (Continuous) Variables</a>
<ul>
<li class="chapter" data-level="23.3.1" data-path="descriptives.html"><a href="descriptives.html#datavisualizations_interval_ratio"><i class="fa fa-check"></i><b>23.3.1</b> Create Data Visualizations</a></li>
<li class="chapter" data-level="23.3.2" data-path="descriptives.html"><a href="descriptives.html#compute_measures_centraltendency_dispersion"><i class="fa fa-check"></i><b>23.3.2</b> Compute Measures of Central Tendency &amp; Dispersion</a></li>
</ul></li>
<li class="chapter" data-level="23.4" data-path="descriptives.html"><a href="descriptives.html#summary-18"><i class="fa fa-check"></i><b>23.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="crosstabs.html"><a href="crosstabs.html"><i class="fa fa-check"></i><b>24</b> Cross-Tabulations</a>
<ul>
<li class="chapter" data-level="24.1" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs"><i class="fa fa-check"></i><b>24.1</b> Two-Way Cross-Tabulation</a>
<ul>
<li class="chapter" data-level="24.1.1" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs_table"><i class="fa fa-check"></i><b>24.1.1</b> Option 1: Using the <code>table</code> Function</a></li>
<li class="chapter" data-level="24.1.2" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs_xtabs"><i class="fa fa-check"></i><b>24.1.2</b> Option 2: Using the <code>xtabs</code> Function</a></li>
<li class="chapter" data-level="24.1.3" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs_CrossTable"><i class="fa fa-check"></i><b>24.1.3</b> Option 3: Using the <code>CrossTable</code> Function</a></li>
</ul></li>
<li class="chapter" data-level="24.2" data-path="crosstabs.html"><a href="crosstabs.html#threeway_crosstabs"><i class="fa fa-check"></i><b>24.2</b> Three-Way Cross-Tabulation</a>
<ul>
<li class="chapter" data-level="24.2.1" data-path="crosstabs.html"><a href="crosstabs.html#threeway_crosstabs_table"><i class="fa fa-check"></i><b>24.2.1</b> Option 1: Using the <code>table</code> Function</a></li>
<li class="chapter" data-level="24.2.2" data-path="crosstabs.html"><a href="crosstabs.html#threeway_crosstabs_xtabs"><i class="fa fa-check"></i><b>24.2.2</b> Option 2: Using the <code>xtabs</code> Function</a></li>
</ul></li>
<li class="chapter" data-level="24.3" data-path="crosstabs.html"><a href="crosstabs.html#summary-19"><i class="fa fa-check"></i><b>24.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="pivottables.html"><a href="pivottables.html"><i class="fa fa-check"></i><b>25</b> Pivot Tables</a>
<ul>
<li class="chapter" data-level="25.1" data-path="pivottables.html"><a href="pivottables.html#create_pivottables"><i class="fa fa-check"></i><b>25.1</b> Create a Pivot Table</a></li>
<li class="chapter" data-level="25.2" data-path="pivottables.html"><a href="pivottables.html#summary-20"><i class="fa fa-check"></i><b>25.2</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>V Employee Surveys</b></span></li>
<li class="chapter" data-level="26" data-path="employeesurveys.html"><a href="employeesurveys.html"><i class="fa fa-check"></i><b>26</b> Introduction to Employee Surveys</a></li>
<li class="part"><span><b>VI Employee Selection</b></span></li>
<li class="chapter" data-level="27" data-path="selection.html"><a href="selection.html"><i class="fa fa-check"></i><b>27</b> Introduction to Employee Selection</a></li>
<li class="chapter" data-level="28" data-path="disparateimpact.html"><a href="disparateimpact.html"><i class="fa fa-check"></i><b>28</b> Disparate Impact</a>
<ul>
<li class="chapter" data-level="28.1" data-path="disparateimpact.html"><a href="disparateimpact.html#fourfifthsrule"><i class="fa fa-check"></i><b>28.1</b> 4/5ths Rule</a></li>
<li class="chapter" data-level="28.2" data-path="disparateimpact.html"><a href="disparateimpact.html#chisquaretest_disparateimpact"><i class="fa fa-check"></i><b>28.2</b> Chi-Squared (<span class="math inline">\(\chi^2\)</span>) Test of Independence</a></li>
<li class="chapter" data-level="28.3" data-path="disparateimpact.html"><a href="disparateimpact.html#fisherexacttest"><i class="fa fa-check"></i><b>28.3</b> Fisher Exact Test</a></li>
<li class="chapter" data-level="28.4" data-path="disparateimpact.html"><a href="disparateimpact.html#zdifference_test_disparateimpact"><i class="fa fa-check"></i><b>28.4</b> <span class="math inline">\(Z_{D}\)</span> test</a></li>
<li class="chapter" data-level="28.5" data-path="disparateimpact.html"><a href="disparateimpact.html#z_impactratiotest"><i class="fa fa-check"></i><b>28.5</b> <span class="math inline">\(Z_{IR}\)</span> Test</a></li>
<li class="chapter" data-level="28.6" data-path="disparateimpact.html"><a href="disparateimpact.html#summary_disparatetreatment"><i class="fa fa-check"></i><b>28.6</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>VII Odds &amp; Ends</b></span></li>
<li class="chapter" data-level="" data-path="create-portfolio.html"><a href="create-portfolio.html"><i class="fa fa-check"></i>Creating a Data Analytics Portfolio</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for HR:<br />
<em>An Introduction to Human Resource Analytics Using R</em><br />
BOOK UNDER CONSTRUCTION</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="disparateimpact" class="section level1" number="28">
<h1><span class="header-section-number">Chapter 28</span> Disparate Impact</h1>
<p><strong>Disparate impact</strong>, which is also referred to as <strong>adverse impact</strong>, refers to situations in which organizations “use seemingly neutral criteria that have a discriminatory effect on a protected group” (Bauer, Erdogan, Caughlin, &amp; Truxillo, 2019, p. 117). There are various tests – both statistical and nonstatistical – that may be used to evaluate whether there is evidence of disparate impact, such as the 4/5ths Rule (80% Rule), <span class="math inline">\(Z_{Difference}\)</span>-test, <span class="math inline">\(Z_{Impact Ratio}\)</span>-test, <span class="math inline">\(\chi^2\)</span> test of independence (i.e., chi-squared test of independence), and Fisher exact test. In the United States, it is legally advisable to begin with testing the 4/5ths Rule followed by a statistical test like the <span class="math inline">\(Z_{Impact Ratio}\)</span>-test, <span class="math inline">\(\chi^2\)</span> test of independence, or Fisher exact test.</p>
<p>If you would like to learn more about how to evaluate disparate impact along with empirical evidence regarding under which conditions various tests perform best, consider reading the following:</p>
<ul>
<li><p>Collins, M. W., &amp; Morris, S. B. (2008). Testing for adverse impact when sample size is small. <em>Journal of Applied Psychology, 93</em>(2), 463-471.</p></li>
<li><p>Dunleavy, E., Morris, S., &amp; Howard, E. (2015). Measuring adverse impact in employee selection decisions. In C. Hanvey &amp; K. Sady (Eds.), <em>Practitioner’s guide to legal issues in organizations</em> (pp. 1-26). Switzerland: Springer, Cham.</p></li>
<li><p>Finch, D. M., Edwards, B. D., &amp; Wallace, J. C. (2009). Multistage selection strategies: Simulating the effects on adverse impact and expected performance for various predictor combinations. <em>Journal of Applied Psychology, 94</em>(2), 318-340.</p></li>
<li><p>Morris, S. B. (2001). Sample size required for adverse impact analysis. <em>Applied HRM Research, 6</em>(1-2), 13-32.</p></li>
<li><p>Morris, S. B., &amp; Lobsenz, R. E. (2000). Significance tests and confidence intervals for the adverse impact ratio. <em>Personnel Psychology, 53</em>(1), 89-111.</p></li>
<li><p>Office of Federal Contract Compliance Programs. (1993). Federal contract compliance manual (SUDOC L 36.8: C 76/993). Washington, DC: U. S. Department of Labor, Employment Standards Administration.</p></li>
<li><p>Roth, P. L., Bobko, P., &amp; Switzer, F. S. III. (2006). Modeling the behavior of the 4/5ths rule for determining adverse impact: Reasons for caution. <em>Journal of Applied Psychology, 91</em>(3), 507-522.</p></li>
</ul>
<div id="video-tutorial-17" class="section level4" number="28.0.0.1">
<h4><span class="header-section-number">28.0.0.1</span> Video Tutorial</h4>
<p>As usual, you have the choice to follow along with the written tutorial in this chapter or to watch the video tutorials below.</p>
<iframe src="https://youtube.com/embed/1e-ZW-AC_6o?rel=0" width="672" height="400px">
</iframe>
<p>Link to Video Tutorial: <a href="https://youtu.be/1e-ZW-AC_6o" class="uri">https://youtu.be/1e-ZW-AC_6o</a></p>
<iframe src="https://youtube.com/embed/oddQdDH73oQ?rel=0" width="672" height="400px">
</iframe>
<p>Link to Video Tutorial: <a href="https://youtu.be/oddQdDH73oQ" class="uri">https://youtu.be/oddQdDH73oQ</a></p>
</div>
<div id="functions-packages-introduced-13" class="section level4" number="28.0.0.2">
<h4><span class="header-section-number">28.0.0.2</span> Functions &amp; Packages Introduced</h4>
<table>
<thead>
<tr class="header">
<th>Function</th>
<th>Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>xtabs</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="even">
<td><code>print</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="odd">
<td><code>addmargins</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="even">
<td><code>proportions</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="odd">
<td><code>chisq.test</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="even">
<td><code>phi</code></td>
<td><code>psych</code></td>
</tr>
<tr class="odd">
<td><code>fisher.test</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="even">
<td><code>sum</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="odd">
<td><code>prop.table</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="even">
<td><code>sqrt</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="odd">
<td><code>abs</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="even">
<td><code>pnorm</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="odd">
<td><code>log</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="even">
<td><code>exp</code></td>
<td>base <code>R</code></td>
</tr>
</tbody>
</table>
</div>
<div id="initsteps_disparateimpact" class="section level4" number="28.0.0.3">
<h4><span class="header-section-number">28.0.0.3</span> Initial Steps</h4>
<p>If you haven’t already, save the file called <strong>“DisparateImpact.csv”</strong> into a folder that you will subsequently set as your working directory. Your working directory will likely be different than the one shown below (i.e., <code>"H:/RWorkshop"</code>). As a reminder, you can access all of the data files referenced in this book by downloading them as a compressed (zipped) folder from the my GitHub site: <a href="https://github.com/davidcaughlin/R-Tutorial-Data-Files" class="uri">https://github.com/davidcaughlin/R-Tutorial-Data-Files</a>; once you’ve followed the link to GitHub, just click “Code” (or “Download”) followed by “Download ZIP”, which will download all of the data files referenced in this book. For the sake of parsimony, I recommend downloading all of the data files into the same folder on your computer, which will allow you to set that same folder as your working directory for each of the chapters in this book.</p>
<p>Next, using the <code>setwd</code> function, set your working directory to the folder in which you saved the data file for this chapter. Alternatively, you can manually set your working directory folder in your drop-down menus by going to <em>Session &gt; Set Working Directory &gt; Choose Directory…</em>. Be sure to create a new R script file (.R) or update an existing R script file so that you can save your script and annotations. If you need refreshers on how to set your working directory and how to create and save an R script, please refer to <a href="setwd.html#setwd">Setting a Working Directory</a> and <a href="gettingstarted.html#createRscript">Creating &amp; Saving an R Script</a>.</p>
<div class="sourceCode" id="cb798"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb798-1"><a href="disparateimpact.html#cb798-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your working directory</span></span>
<span id="cb798-2"><a href="disparateimpact.html#cb798-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;H:/RWorkshop&quot;</span>)</span></code></pre></div>
<p>Next, read in the .csv data file called <strong>“DisparateImpact.csv”</strong> using your choice of read function. In this example, I use the <code>read_csv</code> function from the <code>readr</code> package <span class="citation">(<a href="references.html#ref-R-readr" role="doc-biblioref">Wickham and Hester 2020</a>)</span>. If you choose to use the <code>read_csv</code> function, be sure that you have installed and accessed the <code>readr</code> package using the <code>install.packages</code> and <code>library</code> functions. <em>Note: You don’t need to install a package every time you wish to access it; in general, I would recommend updating a package installation once ever 1-3 months.</em> For refreshers on installing packages and reading data into R, please refer to <a href="gentleintro.html#packages">Packages</a> and <a href="read.html#read">Reading Data into R</a>.</p>
<div class="sourceCode" id="cb799"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb799-1"><a href="disparateimpact.html#cb799-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install readr package if you haven&#39;t already</span></span>
<span id="cb799-2"><a href="disparateimpact.html#cb799-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Note: You don&#39;t need to install a package every </span></span>
<span id="cb799-3"><a href="disparateimpact.html#cb799-3" aria-hidden="true" tabindex="-1"></a><span class="co"># time you wish to access it]</span></span>
<span id="cb799-4"><a href="disparateimpact.html#cb799-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;readr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb800"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb800-1"><a href="disparateimpact.html#cb800-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access readr package</span></span>
<span id="cb800-2"><a href="disparateimpact.html#cb800-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb800-3"><a href="disparateimpact.html#cb800-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb800-4"><a href="disparateimpact.html#cb800-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data and name data frame (tibble) object</span></span>
<span id="cb800-5"><a href="disparateimpact.html#cb800-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;DisparateImpact.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification -------------------------------------------------------------------------
## cols(
##   ID = col_double(),
##   Cognitive_Test = col_character(),
##   Gender = col_character()
## )</code></pre>
<div class="sourceCode" id="cb802"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb802-1"><a href="disparateimpact.html#cb802-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the names of the variables in the data frame (tibble) objects</span></span>
<span id="cb802-2"><a href="disparateimpact.html#cb802-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df)</span></code></pre></div>
<pre><code>## [1] &quot;ID&quot;             &quot;Cognitive_Test&quot; &quot;Gender&quot;</code></pre>
<div class="sourceCode" id="cb804"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb804-1"><a href="disparateimpact.html#cb804-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View variable type for each variable in data frame</span></span>
<span id="cb804-2"><a href="disparateimpact.html#cb804-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code></pre></div>
<pre><code>## spec_tbl_df[,3] [274 x 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ ID            : num [1:274] 1 2 3 4 5 6 7 8 9 10 ...
##  $ Cognitive_Test: chr [1:274] &quot;Pass&quot; &quot;Pass&quot; &quot;Pass&quot; &quot;Pass&quot; ...
##  $ Gender        : chr [1:274] &quot;Man&quot; &quot;Man&quot; &quot;Man&quot; &quot;Man&quot; ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   ID = col_double(),
##   ..   Cognitive_Test = col_character(),
##   ..   Gender = col_character()
##   .. )</code></pre>
<div class="sourceCode" id="cb806"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb806-1"><a href="disparateimpact.html#cb806-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View first 6 rows of data frame</span></span>
<span id="cb806-2"><a href="disparateimpact.html#cb806-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##      ID Cognitive_Test Gender
##   &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt; 
## 1     1 Pass           Man   
## 2     2 Pass           Man   
## 3     3 Pass           Man   
## 4     4 Pass           Man   
## 5     5 Pass           Man   
## 6     6 Pass           Man</code></pre>
<p>There are 3 variables and 274 cases (i.e., applicants) in the <code>df</code> data frame: <code>ID</code>, <code>Cognitive_Test</code>, and <code>Gender</code>. <code>ID</code> is the unique applicant identifier variable. Imagine that these data were collected as part of selection process, and this data frame contains information about the applicants. The <code>Cognitive_Test</code> variable is a categorical (nominal) variable that indicates whether an applicant passed (<code>Pass</code>) or failed (<code>Fail</code>) a cognitive ability selection test. <code>Gender</code> is also a categorical (nominal) variable that provides each applicant’s self-reported gender identify, which in this sample happens to include <code>Man</code> and <code>Woman</code>.</p>
</div>
<div id="fourfifthsrule" class="section level2" number="28.1">
<h2><span class="header-section-number">28.1</span> 4/5ths Rule</h2>
<p>Evaluating the 4/5ths Rule involves simple arithmetic. As an initial step, we will create a cross-tabulation (i.e., cross-tabs, contingency) table using the <code>xtabs</code> function from base <code>R</code>. As the first argument, in the <code>xtabs</code> function, type the tilde (<code>~</code>) operator followed by the projected class variable (<code>Gender</code>), followed by the addition (<code>+</code>) operator, followed by the selection tool variable containing the pass/fail information (<code>Cognitive_Test</code>). As the second argument, type <code>data=</code> followed by the name of the data frame object (<code>df</code>) to which the two variables mentioned in the first argument “live.” Next, to the left of the <code>xtabs</code> function, type any name you’d like for the new cross-tabs table object we’re creating using the <code>xtabs</code> function, followed by the left arrow (<code>&lt;-</code>) operator; I call this cross-tabs table object <code>observed</code> because it will contain our <em>observed</em> frequency/count data for the number of people from each gender who passed and failed this cognitive ability test.</p>
<div class="sourceCode" id="cb808"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb808-1"><a href="disparateimpact.html#cb808-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create cross-tabs table of observed data</span></span>
<span id="cb808-2"><a href="disparateimpact.html#cb808-2" aria-hidden="true" tabindex="-1"></a>observed <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="sc">~</span> Gender <span class="sc">+</span> Cognitive_Test, <span class="at">data=</span>df)</span></code></pre></div>
<p>Let’s take a look at the table object we created called <code>observed</code> by entering its name as the sole parenthetical argument in the <code>print</code> function from base <code>R</code>.</p>
<div class="sourceCode" id="cb809"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb809-1"><a href="disparateimpact.html#cb809-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print cross-tabs table of observed data</span></span>
<span id="cb809-2"><a href="disparateimpact.html#cb809-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(observed)</span></code></pre></div>
<pre><code>##        Cognitive_Test
## Gender  Fail Pass
##   Man     90   70
##   Woman   72   42</code></pre>
<p>As you can see, the <code>observed</code> object contains the raw counts/frequencies of those men and women who passed and failed the cognitive ability test.</p>
<p>Now we’re ready to compute the selection ratios (i.e., selection rates, pass rates) for the two groups we wish to compare. In this example, we will focus on the protected class variable <code>Gender</code> and the two <code>Gender</code> categories available in these data: <code>Man</code> and <code>Woman</code>. The approach we’ll use is not the most efficient or elegant way to compute selection ratios, but it is perhaps more transparent than other approaches – and thus good for learning.</p>
<p>Let’s begin by calculating the total number of men who participated in this cognitive ability test. To do so, we will use matrix/bracket notation to “pull” specific values from our <code>observed</code> table object that correspond to the number of men who passed and the number of men who failed; if we add those two values together, we will get the total sample size for men who participated in this cognitive ability test. To illustrate how matrix/bracket notation works, let’s practice by just pulling the number of men who passed. Simply, type the name of the table object (<code>observed</code>), followed by brackets <code>[ ]</code>. Within the brackets, a number that comes before the comma represents the row number in the table or matrix object, and the number that comes after the comma represents the column number. To pull the number of men who passed the test, we would reference the cell from our table that corresponds to row number 1 and column number 2 (as shown below).</p>
<div class="sourceCode" id="cb811"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb811-1"><a href="disparateimpact.html#cb811-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Practice matrix notation</span></span>
<span id="cb811-2"><a href="disparateimpact.html#cb811-2" aria-hidden="true" tabindex="-1"></a>observed[<span class="dv">1</span>,<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 70</code></pre>
<p>Now we’re ready to pull the pass and fail counts for men and assign them to object names of our choosing. For clarity, I’m labeling these objects as <code>pass_men</code> and <code>fail_men</code>, and we use the left arrow (<code>&lt;-</code>) operator to assign the values to these new objects.</p>
<div class="sourceCode" id="cb813"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb813-1"><a href="disparateimpact.html#cb813-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create pass and fail objects for men containing the raw frequencies/counts</span></span>
<span id="cb813-2"><a href="disparateimpact.html#cb813-2" aria-hidden="true" tabindex="-1"></a>pass_men <span class="ot">&lt;-</span> observed[<span class="dv">1</span>,<span class="dv">2</span>]</span>
<span id="cb813-3"><a href="disparateimpact.html#cb813-3" aria-hidden="true" tabindex="-1"></a>fail_men <span class="ot">&lt;-</span> observed[<span class="dv">1</span>,<span class="dv">1</span>]</span></code></pre></div>
<p>If you’d like you can print the <code>pass_men</code> and <code>fail_men</code> objects to verify that the correct table values were assigned to each object.</p>
<p>By adding our <code>pass_men</code> and <code>fail_men</code> values together, we can compute the total number of men who participated in this cognitive ability test. Let’s call this new object <code>N_men</code>.</p>
<div class="sourceCode" id="cb814"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb814-1"><a href="disparateimpact.html#cb814-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an object that contains the total number of men who participated in the test</span></span>
<span id="cb814-2"><a href="disparateimpact.html#cb814-2" aria-hidden="true" tabindex="-1"></a>N_men <span class="ot">&lt;-</span> pass_men <span class="sc">+</span> fail_men</span></code></pre></div>
<p>Let’s now proceed with doing the same for the number of women who passed and failed, as well as the total number of women.</p>
<div class="sourceCode" id="cb815"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb815-1"><a href="disparateimpact.html#cb815-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create object containing number of women who passed, number of women who failed,</span></span>
<span id="cb815-2"><a href="disparateimpact.html#cb815-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and the total number of women who participated in the test</span></span>
<span id="cb815-3"><a href="disparateimpact.html#cb815-3" aria-hidden="true" tabindex="-1"></a>pass_women <span class="ot">&lt;-</span> observed[<span class="dv">2</span>,<span class="dv">2</span>]</span>
<span id="cb815-4"><a href="disparateimpact.html#cb815-4" aria-hidden="true" tabindex="-1"></a>fail_women <span class="ot">&lt;-</span> observed[<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb815-5"><a href="disparateimpact.html#cb815-5" aria-hidden="true" tabindex="-1"></a>N_women <span class="ot">&lt;-</span> pass_women <span class="sc">+</span> fail_women</span></code></pre></div>
<p>We now have the ingredients necessary to compute the selection ratios for men and women. To calculate the selection ratio for men, simply divide the number of men who passed (<code>pass_men</code>) by the total number of men (<code>N_men</code>). Using the left arrow (<code>&lt;-</code>) operator, we will assign this quotient to an object that I’m arbitrarily calling <code>SR_men</code> (for “selection ratio for men”).</p>
<div class="sourceCode" id="cb816"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb816-1"><a href="disparateimpact.html#cb816-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create object containing selection ratio for men</span></span>
<span id="cb816-2"><a href="disparateimpact.html#cb816-2" aria-hidden="true" tabindex="-1"></a>SR_men <span class="ot">&lt;-</span> pass_men <span class="sc">/</span> N_men</span></code></pre></div>
<p>Let’s do create an object called <code>SR_women</code> that contains the selection ratio for women.</p>
<div class="sourceCode" id="cb817"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb817-1"><a href="disparateimpact.html#cb817-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create object containing selection ratio for women</span></span>
<span id="cb817-2"><a href="disparateimpact.html#cb817-2" aria-hidden="true" tabindex="-1"></a>SR_women <span class="ot">&lt;-</span> pass_women <span class="sc">/</span> N_women</span></code></pre></div>
<p>As the final computational step, we’ll create an object called <code>IR</code> containing the impact ratio value. Simply divide our <code>SR_women</code> object by the <code>SR_men</code> object, and assign that quotient to an object called <code>IR</code> using the left arrow (<code>&lt;-</code>) operator. In most cases, it is customary to set the group with the lower selection ratio as the numerator and the group with the higher selection ratio as the denominator. There can be exceptions, though, such as in instances in which a law is directional, such as the Age Discrimination in Employment Act of 1967, which at the federal level stipulates that workers older than 40 years of age are projected; in this particular case, we would typically always set the selection ratio for workers older 40 as the numerator and the selection ratio for workers younger than 40 as the denominator.</p>
<div class="sourceCode" id="cb818"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb818-1"><a href="disparateimpact.html#cb818-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create impact ratio object</span></span>
<span id="cb818-2"><a href="disparateimpact.html#cb818-2" aria-hidden="true" tabindex="-1"></a>IR <span class="ot">&lt;-</span> SR_women <span class="sc">/</span> SR_men</span></code></pre></div>
<p>To view the <code>IR</code> object, use the <code>print</code> function.</p>
<div class="sourceCode" id="cb819"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb819-1"><a href="disparateimpact.html#cb819-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print impact ratio object</span></span>
<span id="cb819-2"><a href="disparateimpact.html#cb819-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(IR)</span></code></pre></div>
<pre><code>## [1] 0.8421053</code></pre>
<p>Because the impact ratio (IR) value is .84 and thus greater than .80 (80%, 4/5ths), then we would concluded based on this test that there is not evidence of disparate impact on this cognitive ability test when comparing the selection ratios of men and women. If the impact ratio had been less than .80, then we would have concluded that based on the 4/5ths Rule, there was evidence of disparate impact.</p>
<p>It is sometimes recommended that we apply the “flip-flop rule”, which is essentially a sensitivity test for the 4/5ths Rule test. This is often called the <em>impact ratio adjusted</em> (<code>IR_adj</code>). To compute the impact ratio adjusted, we re-apply the impact ratio formula; however, this time we add in a hypothetical women who passed and subtract a hypothetical man who passed.</p>
<div class="sourceCode" id="cb821"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb821-1"><a href="disparateimpact.html#cb821-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply &quot;flip-flop rule&quot; (impact ratio adjusted)</span></span>
<span id="cb821-2"><a href="disparateimpact.html#cb821-2" aria-hidden="true" tabindex="-1"></a>IR_adj <span class="ot">&lt;-</span> ((pass_women <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> N_women) <span class="sc">/</span> ((pass_men <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> N_men)</span>
<span id="cb821-3"><a href="disparateimpact.html#cb821-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(IR_adj)</span></code></pre></div>
<pre><code>## [1] 0.8746504</code></pre>
<p>If the impact ratio adjusted (<code>IR_adj</code>) value is less than 1.0, then the original interpretation of the impact ratio stands; in this example, the impact ratio adjusted value is less than 1.0, and thus we continue on with our original interpretation that there is no violation of the 4/5ths Rule and thus no evidence of disparate impact.</p>
<p>Finally, it’s important to note that the impact ratio associated with the 4/5ths Rule is an effect size and, thus, can be compared across samples and tests. With that being said, on its own, the 4/5ths Rule doesn’t produce a test of statistical significance. For a test of adverse impact that yield a statistical significance estimate, we should should tern to the <span class="math inline">\(\chi^2\)</span> test of independence, Fisher Exact test, <span class="math inline">\(Z\)</span>-test, or <span class="math inline">\(Z_{ImpactRatio}\)</span>.</p>
<div id="fourfifthsrule_alternative" class="section level4" number="28.1.0.1">
<h4><span class="header-section-number">28.1.0.1</span> Optional: Alternative Approach to Computing 4/5ths Rule</h4>
<p>If you’d like to practice your <code>R</code> skills and learn some additional functions, you’re welcome to apply this mathematically and operationally equivalent approach to the 4/5ths Rule.</p>
<p>As a side note, it’s worth noting that the <code>addmargins</code> function from base <code>R</code> can be used to automatically compute the row and column marginals for a table object. This can be a handy function for simplifying some operations, and matrix/bracket notation can still be used on a new table object that is created using the <code>addmargins</code> function.</p>
<div class="sourceCode" id="cb823"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb823-1"><a href="disparateimpact.html#cb823-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View row and column marginals for table</span></span>
<span id="cb823-2"><a href="disparateimpact.html#cb823-2" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(observed)</span></code></pre></div>
<pre><code>##        Cognitive_Test
## Gender  Fail Pass Sum
##   Man     90   70 160
##   Woman   72   42 114
##   Sum    162  112 274</code></pre>
<p>Now, check out the following steps to see an alternative approach to computing an impact ratio. Note that the <code>proportions</code> function from base <code>R</code> is introduced and that we’re referencing the same table object (<code>observed</code>) as as above.</p>
<div class="sourceCode" id="cb825"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb825-1"><a href="disparateimpact.html#cb825-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert table object values to proportions by Gender (columns)</span></span>
<span id="cb825-2"><a href="disparateimpact.html#cb825-2" aria-hidden="true" tabindex="-1"></a>prop_observed <span class="ot">&lt;-</span> <span class="fu">proportions</span>(observed, <span class="st">&quot;Gender&quot;</span>)</span>
<span id="cb825-3"><a href="disparateimpact.html#cb825-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb825-4"><a href="disparateimpact.html#cb825-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute selection ratios for men</span></span>
<span id="cb825-5"><a href="disparateimpact.html#cb825-5" aria-hidden="true" tabindex="-1"></a>SR_men <span class="ot">&lt;-</span> prop_observed[<span class="dv">1</span>,<span class="dv">2</span>]</span>
<span id="cb825-6"><a href="disparateimpact.html#cb825-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb825-7"><a href="disparateimpact.html#cb825-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute selection ratios for women</span></span>
<span id="cb825-8"><a href="disparateimpact.html#cb825-8" aria-hidden="true" tabindex="-1"></a>SR_women <span class="ot">&lt;-</span> prop_observed[<span class="dv">2</span>,<span class="dv">2</span>]</span>
<span id="cb825-9"><a href="disparateimpact.html#cb825-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb825-10"><a href="disparateimpact.html#cb825-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute impact ratio (IR)</span></span>
<span id="cb825-11"><a href="disparateimpact.html#cb825-11" aria-hidden="true" tabindex="-1"></a>IR <span class="ot">&lt;-</span> SR_women <span class="sc">/</span> SR_men</span>
<span id="cb825-12"><a href="disparateimpact.html#cb825-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb825-13"><a href="disparateimpact.html#cb825-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Print impact ratio (IR)</span></span>
<span id="cb825-14"><a href="disparateimpact.html#cb825-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(IR)</span></code></pre></div>
<pre><code>## [1] 0.8421053</code></pre>
</div>
</div>
<div id="chisquaretest_disparateimpact" class="section level2" number="28.2">
<h2><span class="header-section-number">28.2</span> Chi-Squared (<span class="math inline">\(\chi^2\)</span>) Test of Independence</h2>
<p>The chi-squared (<span class="math inline">\(\chi^2\)</span>) test of independence is a statistical test than can be applied to evaluating whether this evidence of disparate impact. It’s relatively simple to compute.</p>
<p>Using the <code>chisq.test</code> function from base <code>R</code>, as the first argument, type the name of the table object containing the raw counts/frequencies (<code>observed</code>). As the second argument, enter the argument <code>correct=FALSE</code>, which stipulates that we wish for our <span class="math inline">\(\chi^2\)</span> test to be computed the traditional way without a continuity correction.</p>
<div class="sourceCode" id="cb827"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb827-1"><a href="disparateimpact.html#cb827-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute chi-squared test of independence</span></span>
<span id="cb827-2"><a href="disparateimpact.html#cb827-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(observed, <span class="at">correct=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  observed
## X-squared = 1.3144, df = 1, p-value = 0.2516</code></pre>
<p>In the output, we should focus our attention on the <em>p</em>-value and whether it is equal to or greater than the conventional two-tailed alpha level of .05. In this case, <em>p</em>-value is greater than .05, so we would conclude that appears to be no statistical association between whether someone passes or fails the cognitive ability test and whether they identify as a man or women. In other words, gender does not appear have an effect on whether someone passes or fails this particular test, and thus there is no evidence of disparate impact based on this statistical test. This corroborates what we found when test the 4/5ths Rule above. If the <em>p</em>-value had been less than .05, then we would have concluded there is statistical evidence of disparate impact.</p>
<p>For fun, we can append <code>$observed</code> and <code>$expected</code> to our function to see the observed and expected counts/frequencies that were used to compute the <span class="math inline">\(\chi^2\)</span> test of independence behind the scenes.</p>
<div class="sourceCode" id="cb829"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb829-1"><a href="disparateimpact.html#cb829-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View observed values</span></span>
<span id="cb829-2"><a href="disparateimpact.html#cb829-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(observed, <span class="at">correct=</span><span class="cn">FALSE</span>)<span class="sc">$</span>observed</span></code></pre></div>
<pre><code>##        Cognitive_Test
## Gender  Fail Pass
##   Man     90   70
##   Woman   72   42</code></pre>
<div class="sourceCode" id="cb831"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb831-1"><a href="disparateimpact.html#cb831-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View expected values</span></span>
<span id="cb831-2"><a href="disparateimpact.html#cb831-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(observed, <span class="at">correct=</span><span class="cn">FALSE</span>)<span class="sc">$</span>expected</span></code></pre></div>
<pre><code>##        Cognitive_Test
## Gender      Fail     Pass
##   Man   94.59854 65.40146
##   Woman 67.40146 46.59854</code></pre>
<p>As an aside, to apply the Yates continuity correction, we would simply flip <code>correct=FALSE</code> to <code>correct=TRUE</code>. This continuity correction is available when we are evaluating data from a 2x2 table, which is the case in this example. There is a bit of a debate regarding whether to apply this continuity correction. Briefly, this continuity correction was introduced to account for the fact that in the specific case of 2x2 contingency tables (like ours), <span class="math inline">\(\chi^2\)</span> values tend to be upwardly biased. Others, however, counter that this test is too strict. For a more conservative test, apply the continuity correction.</p>
<div class="sourceCode" id="cb833"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb833-1"><a href="disparateimpact.html#cb833-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute chi-squared test of independence (with Yates continuity correction)</span></span>
<span id="cb833-2"><a href="disparateimpact.html#cb833-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(observed, <span class="at">correct=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  observed
## X-squared = 1.0441, df = 1, p-value = 0.3069</code></pre>
<div id="chisquaretest_phi" class="section level4" number="28.2.0.1">
<h4><span class="header-section-number">28.2.0.1</span> Optional: Compute Phi (<span class="math inline">\(\phi\)</span>) Coefficient (Effect Size) for Chi-Squared Test of Independence</h4>
<p>The <em>p</em>-value we computed for the 2x2 chi-square (<span class="math inline">\(\chi^2\)</span>) test of independence is a test of statistical significance, which informs whether we should treat the association between two categorical variables is statistically significant. The <em>p</em>-value, however, does not give us any indication of practical significance or effect size, where an effect size is a standardized metric that can be compared across tests and samples. As an indicator of effect size, the phi (<span class="math inline">\(\phi\)</span>) coefficient can be computed for a 2x2 <span class="math inline">\(\chi^2\)</span> test of independence, where both variables have two levels (i.e., categories). <strong>Important note: Typically, we would only compute the phi (<span class="math inline">\(\phi\)</span>) coefficient in the event we observed a statistically significant <span class="math inline">\(\chi^2\)</span> test of independence. As shown in the previous section, we did not find evidence that the <span class="math inline">\(\chi^2\)</span> test of independence was statistically significant, so would not usually go ahead and compute an effect size. That being said, we will compute phi (<span class="math inline">\(\phi\)</span>) coefficient just for demonstration purposes.</strong></p>
<p>To compute the phi (<span class="math inline">\(\phi\)</span>) coefficient, we will use the <code>phi</code> function from the <code>psych</code> package, which means we first need to install (if not already installed) the <code>psych</code> package using the <code>install.packages</code> function from base <code>R</code> and then access the package using the <code>library</code> function from base <code>R</code>.</p>
<div class="sourceCode" id="cb835"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb835-1"><a href="disparateimpact.html#cb835-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install psych package (if not already installed)</span></span>
<span id="cb835-2"><a href="disparateimpact.html#cb835-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;psych&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb836"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb836-1"><a href="disparateimpact.html#cb836-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access the psych package</span></span>
<span id="cb836-2"><a href="disparateimpact.html#cb836-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code></pre></div>
<p>Now we’re ready to deploy the <code>phi</code> function.</p>
<div class="sourceCode" id="cb837"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb837-1"><a href="disparateimpact.html#cb837-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute phi coefficient</span></span>
<span id="cb837-2"><a href="disparateimpact.html#cb837-2" aria-hidden="true" tabindex="-1"></a><span class="fu">phi</span>(observed)</span></code></pre></div>
<pre><code>## [1] -0.07</code></pre>
<p>The phi (<span class="math inline">\(\phi\)</span>) coefficient is -.07. Because this is as an effect size, we can describe it qualitatively (e.g., small, medium, large). For a 2x2 contingency table, the phi (<span class="math inline">\(\phi\)</span>) coefficient is equivalent to a Pearson product-moment correlation (<em>r</em>). Like a correlation (<em>r</em>) coefficient, the (<span class="math inline">\(\phi\)</span>) coefficient can range from -1.00 (perfect negative association) to 1.00 (perfect positive association), with .00 indicating no association. Further, we can use the conventional correlation thresholds for describing the magnitude of the effect, which I display in the table below.</p>
<table>
<thead>
<tr class="header">
<th><span class="math inline">\(\phi\)</span></th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.10</td>
<td>Small</td>
</tr>
<tr class="even">
<td>.30</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td>.50</td>
<td>Large</td>
</tr>
</tbody>
</table>
<p>Because the absolute value of the phi (<span class="math inline">\(\phi\)</span>) coefficient is .07 and thus falls below the .10 threshold for “small,” we might describe the effect as “negligible” or “very small.” Better yet, because the <em>p</em>-value associated with the <span class="math inline">\(\chi^2\)</span> test of independence indicated that the association was nonsignificant, we should just conclude that there is no statistical association between whether someone passes or fails the cognitive ability test and whether they identify as a man or women. In other words, we treat the effect size as though it were zero.</p>
<p>Finally, one limitation of the phi (<span class="math inline">\(\phi\)</span>) coefficient is that the upper limit of the observed coefficient will be attenuated to the extent that the two categorical variables <em>don’t</em> have a 50/50 distribution <span class="citation">(<a href="references.html#ref-dunleavy2015measuring" role="doc-biblioref">Dunleavy, Morris, and Howard 2015</a>)</span>, which is often the case in the specific context of selection ratios and adverse impact. For example, if the proportion of applicants who passed the selection test is anything but .50, then the estimated <span class="math inline">\(\phi\)</span> value will <em>not</em> have the potential to reach the upper limits of -1.00 or 1.00. Similarly, if the proportion of applicants from one group relative to another group is anything but .50, then the estimated <span class="math inline">\(\phi\)</span> value will <em>not</em> have the potential to reach the upper limits of -1.00 or 1.00.</p>
</div>
</div>
<div id="fisherexacttest" class="section level2" number="28.3">
<h2><span class="header-section-number">28.3</span> Fisher Exact Test</h2>
<p>In instances in which we have a small sample size (e.g., <em>N</em> &lt; 30) and/or one of the 2x2 cells has an expected frequency that is less than 5, the Fisher exact test is a more appropriate test than other tests like the chi-square (<span class="math inline">\(\chi^2\)</span>) test of independence or the <span class="math inline">\(Z\)</span>-test <span class="citation">(<a href="references.html#ref-OFCCP1993" role="doc-biblioref">Federal Contract Compliance Programs 1993</a>)</span>. The Fisher exact test is very simple to compute when using the <code>fisher.test</code> function from base <code>R</code>. Simply, enter the name of the table object (<code>observed</code>) as the sole parenthetical argument in the function.</p>
<div class="sourceCode" id="cb839"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb839-1"><a href="disparateimpact.html#cb839-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute fisher test</span></span>
<span id="cb839-2"><a href="disparateimpact.html#cb839-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(observed)</span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  observed
## p-value = 0.2643
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.4441286 1.2622356
## sample estimates:
## odds ratio 
##  0.7507933</code></pre>
<p>In the output, we should focus our attention on the <em>p</em>-value and whether it is equal to or greater than the conventional two-tailed alpha level of .05. In this case, <em>p</em>-value is greater than .05, so we would conclude that appears to be no statistical association between whether someone passes or fails the cognitive ability test and whether they identify as a man or women. In other words, gender does not appear have an effect on whether someone passes or fails this particular test, and thus there is no evidence of disparate impact based on this statistical test. This corroborates what we found when test the 4/5ths Rule above. If the <em>p</em>-value had been less than .05, then we would have concluded there is statistical evidence of disparate impact based on this statistical test.</p>
<p>If we’d like to compute an effect size as an indicator of practical significance for a significant Fisher exact test, then we can compute the phi (<span class="math inline">\(\phi\)</span>) coefficient (see previous section) – or another effect size like an odds ratio.</p>
</div>
<div id="zdifference_test_disparateimpact" class="section level2" number="28.4">
<h2><span class="header-section-number">28.4</span> <span class="math inline">\(Z_{D}\)</span> test</h2>
<p>The <span class="math inline">\(Z_{D}\)</span> test – or just <span class="math inline">\(Z\)</span> test – offers another method for evaluating whether evidence of disparate impact exists, and more specifically, this test tests whether there is a significant <em>difference</em> between two selection ratios. The <span class="math inline">\(Z_{D}\)</span> test is also referred to as the <em>Two Standard Deviation Test</em>. Of note, the <span class="math inline">\(Z_{D}\)</span> test is statistically equivalent to a 2x2 chi-square (<span class="math inline">\(\chi^2\)</span>) test of independence, which means that they will yield the same <em>p</em>-value.</p>
<p>To compute the <span class="math inline">\(Z_{D}\)</span> test, we’ll use the contingency table (cross-tabulation) object called <code>observed</code> that we created previously. To begin, we’ll create objects called <code>N_men</code> and <code>N_woman</code> that represent the total number of men and women in our sample, respectively. First, we’ll use matrix notation to reference row 1 of our contingency table (<code>observed[1,]</code>), which contains the number of men who passed and failed the cognitive ability test. Second, we’ll “wrap” row 1 from the matrix in the <code>sum</code> function from base <code>R</code>.</p>
<div class="sourceCode" id="cb841"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb841-1"><a href="disparateimpact.html#cb841-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create object for the total number of men</span></span>
<span id="cb841-2"><a href="disparateimpact.html#cb841-2" aria-hidden="true" tabindex="-1"></a>N_men <span class="ot">&lt;-</span> <span class="fu">sum</span>(observed[<span class="dv">1</span>,])</span></code></pre></div>
<p>We’ll do the same thing to compute the total number of <em>women</em> in our sample, and their counts reside row 2 of our contingency table.</p>
<div class="sourceCode" id="cb842"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb842-1"><a href="disparateimpact.html#cb842-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create object for the total number of women</span></span>
<span id="cb842-2"><a href="disparateimpact.html#cb842-2" aria-hidden="true" tabindex="-1"></a>N_women <span class="ot">&lt;-</span> <span class="fu">sum</span>(observed[<span class="dv">2</span>,])</span></code></pre></div>
<p>Now it’s time to compute the total selection ratio for the sample, irrespective of gender identity, and we’ll assign the total selection ratio to an object that we’ll name <code>SR_total</code> by using the <code>&lt;-</code> operator. To the right of the <code>&lt;-</code>, we will specify the ratio. First, we’ll specify the numerator (i.e., total number of individuals who passed the cognitive ability test) by computing the sum of column 2 in the <code>observed</code> contingency table (<code>sum(observed[,2])</code>). Second, we’ll divide the numerator (using the <code>/</code> operator) by the denominator (i.e., total number of individuals in the sample) by computing the sum of the all counts in our contingency table (<code>sum(observed)</code>). We’ll set aside the resulting <code>SR_total</code> object until we’re ready to plug it into the <span class="math inline">\(Z_{D}\)</span> test formula.</p>
<div class="sourceCode" id="cb843"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb843-1"><a href="disparateimpact.html#cb843-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate marginal (overall, total) selection ratio/rate</span></span>
<span id="cb843-2"><a href="disparateimpact.html#cb843-2" aria-hidden="true" tabindex="-1"></a>SR_total <span class="ot">&lt;-</span> <span class="fu">sum</span>(observed[,<span class="dv">2</span>]) <span class="sc">/</span> <span class="fu">sum</span>(observed)</span></code></pre></div>
<p>Our next objective is to convert the counts in the <code>observed</code> contingency table to proportions by row. Using the <code>prop.table</code> function from base <code>R</code>, we will type the name of the contingency object as the first argument, and type 1 as the second argument, where the latter argument requests proportions by row. Using the <code>&lt;-</code> operator, we’ll assign the table with row proportions to an object that we’ll name <code>prop_observed</code>.</p>
<div class="sourceCode" id="cb844"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb844-1"><a href="disparateimpact.html#cb844-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert contingency table to proportions by row</span></span>
<span id="cb844-2"><a href="disparateimpact.html#cb844-2" aria-hidden="true" tabindex="-1"></a>prop_observed <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(observed, <span class="dv">1</span>)</span></code></pre></div>
<p>Now we’re ready to assign the selection ratios for men and women, respectively, to objects that we’ll call <code>SR_men</code> and <code>SR_women</code>, and we’ll accomplish this by using the <code>&lt;-</code> operator. Our selection ratios for each gender identity have already been computed in the row proportions contingency table object that we created above (<code>prop_observed</code>). The selection ratio for men appears in the cell corresponding to row 1 and column 2 (i.e., the proportion of men who passed the test), and the selection ratio for women appears in the cell corresponding to row 2 and column 2 (i.e., the proportion of women who passed the test). We’ll grab these values from the <code>prop_observed</code> object using matrix notation and then assign them to their respective objects.</p>
<div class="sourceCode" id="cb845"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb845-1"><a href="disparateimpact.html#cb845-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute selection ratios/rates (SR)</span></span>
<span id="cb845-2"><a href="disparateimpact.html#cb845-2" aria-hidden="true" tabindex="-1"></a>SR_men <span class="ot">&lt;-</span> prop_observed[<span class="dv">1</span>,<span class="dv">2</span>]</span>
<span id="cb845-3"><a href="disparateimpact.html#cb845-3" aria-hidden="true" tabindex="-1"></a>SR_women <span class="ot">&lt;-</span> prop_observed[<span class="dv">2</span>,<span class="dv">2</span>]</span></code></pre></div>
<p>The time has come to apply the objects we created above to the <span class="math inline">\(Z_{D}\)</span> test formula, which is shown below.</p>
<p><span class="math inline">\(Z_{D} = \frac{SR_{women} - SR_{men}} {\sqrt{SR_{total}(1-SR_{total})(\frac{1}{N_{women}} + \frac{1}{N_{men}})}}\)</span></p>
<p>Let’s apply the objects we created using the mathematical operations detailed in the formula, and let’s assign the resulting <span class="math inline">\(Z\)</span>-value to an object we’ll call <code>Z</code>.</p>
<div class="sourceCode" id="cb846"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb846-1"><a href="disparateimpact.html#cb846-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Z-value</span></span>
<span id="cb846-2"><a href="disparateimpact.html#cb846-2" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">&lt;-</span> (SR_women <span class="sc">-</span> SR_men) <span class="sc">/</span> </span>
<span id="cb846-3"><a href="disparateimpact.html#cb846-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(</span>
<span id="cb846-4"><a href="disparateimpact.html#cb846-4" aria-hidden="true" tabindex="-1"></a>    (SR_total<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> SR_total) <span class="sc">*</span> ((<span class="dv">1</span><span class="sc">/</span>N_women) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">/</span>N_men)))</span>
<span id="cb846-5"><a href="disparateimpact.html#cb846-5" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<p>Using the <code>abs</code> function from base <code>R</code>, let’s compute the absolute value of the <code>Z</code> object so that we can compare it to the critical <span class="math inline">\(Z\)</span>-values for statistical significance.</p>
<div class="sourceCode" id="cb847"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb847-1"><a href="disparateimpact.html#cb847-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute absolute value of Z-value</span></span>
<span id="cb847-2"><a href="disparateimpact.html#cb847-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abs</span>(Z)</span></code></pre></div>
<pre><code>## [1] 1.146481</code></pre>
<p>The absolute value of the <span class="math inline">\(Z\)</span>-value is 1.15, which falls below the critical value for significance of 1.96 for two-tailed test with an alpha of .05, where alpha is our <em>p</em>-value cutoff for statistical significance. Based on this critical value, we can conclude that there is not a statistical difference between the selection ratios for men and women for the cognitive ability test based on this sample.</p>
<p>With that being said, some argue that a more liberal one-tailed test with alpha equal to .05 might be more appropriate, so as to avoid false negatives (Type II Error). The critical value for a one-tailed test with an alpha of .05 is 1.645. We can see that our observed <span class="math inline">\(Z\)</span>-value of 1.15 is less than that critical value as well. Thus, at least with respect to the <span class="math inline">\(Z_{D}\)</span> test, we can conclude that the two selection ratios are not statistically different from one another. More specifically, failure to exceed the critical values indicates that the difference between the two selection ratios for men and women is less than two standard deviations, which is where the other name for this test comes from (i.e., Two Standard Deviations Test)</p>
<p>In many cases, we might also want want to report the exact <em>p</em>-value for the <span class="math inline">\(Z_{D}\)</span> test. To calculate the exact <em>p</em>-value for a one-tailed test, we will plug the absolute value of our <span class="math inline">\(Z\)</span>-value into the first argument of the <code>pnorm</code> function from base <code>R</code>; and as the second argument, we will specify <code>lower.tail=FALSE</code>, to specify that only want the upper tail of the test, thereby requesting a one-tailed test.</p>
<div class="sourceCode" id="cb849"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb849-1"><a href="disparateimpact.html#cb849-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate exact p-value (one-tailed)</span></span>
<span id="cb849-2"><a href="disparateimpact.html#cb849-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fu">abs</span>(Z), <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.1257981</code></pre>
<p>To compute a two-tailed <em>p</em>-value, we will take the <code>pnorm</code> function from above, and multiple the resulting <em>p</em>-value by 2 using the <code>*</code> (multiplication) operator.</p>
<div class="sourceCode" id="cb851"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb851-1"><a href="disparateimpact.html#cb851-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate exact p-value (two-tailed)</span></span>
<span id="cb851-2"><a href="disparateimpact.html#cb851-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pnorm</span>(<span class="fu">abs</span>(Z), <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.2515962</code></pre>
<p>Both the one- and two-tailed <em>p</em>-values fall below the conventional alpha of .05, and thus both indicate that we should fail to reject the null hypothesis that there is zero difference between the population selection ratios for these two gender identities.</p>
</div>
<div id="z_impactratiotest" class="section level2" number="28.5">
<h2><span class="header-section-number">28.5</span> <span class="math inline">\(Z_{IR}\)</span> Test</h2>
<p>The <span class="math inline">\(Z_{IR}\)</span> test is more a direct test of the 4/5ths Rule and associated impact ratio than, say, the chi-square (<span class="math inline">\(\chi^2\)</span>) test of independence or the <span class="math inline">\(Z_{D}\)</span> test, which if you recall is the selection ratio of one group divided by the selection ratio of another group. The <span class="math inline">\(Z_{IR}\)</span> also tends to be a more appropriate test when sample sizes are small, when the selection ratios for specific groups are low, and when the proportion of the focal group (e.g., women) relative to the overall sample is small <span class="citation">(<a href="references.html#ref-finch2009multistage" role="doc-biblioref">Finch, Edwards, and Wallace 2009</a>; <a href="references.html#ref-morris2001sample" role="doc-biblioref">Morris 2001</a>; <a href="references.html#ref-morris2000significance" role="doc-biblioref">Morris and Lobsenz 2000</a>)</span>.</p>
<p>The formula for the <span class="math inline">\(Z_{IR}\)</span> test is as follows.</p>
<p><span class="math inline">\(Z_{IR} = \frac{ln(\frac{SR_{women}}{SR_{men}})} {\sqrt{(\frac{ 1-SR_{total}}{SR_{total}})(\frac{1}{N_{women}} + \frac{1}{N_{men}})}}\)</span></p>
<p>Fortunately, when we prepared to compute the <span class="math inline">\(Z_{D}\)</span> test <a href="disparateimpact.html#zdifference_test_disparateimpact">above</a>, we created all of the necessary components (i.e., objects) needed to compute the <span class="math inline">\(Z_{IR}\)</span> test. So let’s plug them into our formula and assign the resulting <span class="math inline">\(Z_{IR}\)</span> to an object called <code>Z_IR</code>. Note that the <code>log</code> function from base <code>R</code> computes the natural logarithm.</p>
<div class="sourceCode" id="cb853"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb853-1"><a href="disparateimpact.html#cb853-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Z-value</span></span>
<span id="cb853-2"><a href="disparateimpact.html#cb853-2" aria-hidden="true" tabindex="-1"></a>Z_IR <span class="ot">&lt;-</span> <span class="fu">log</span>(SR_women<span class="sc">/</span>SR_men) <span class="sc">/</span> </span>
<span id="cb853-3"><a href="disparateimpact.html#cb853-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(((<span class="dv">1</span> <span class="sc">-</span> SR_total)<span class="sc">/</span>SR_total) <span class="sc">*</span> (<span class="dv">1</span><span class="sc">/</span>N_women <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>N_men))</span></code></pre></div>
<p>Using the <code>abs</code> function from base <code>R</code>, let’s compute the absolute value of the <code>Z_IR</code> object so that we can compare it to the critical <span class="math inline">\(Z\)</span>-values for statistical significance.</p>
<div class="sourceCode" id="cb854"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb854-1"><a href="disparateimpact.html#cb854-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute absolute value of Z-value</span></span>
<span id="cb854-2"><a href="disparateimpact.html#cb854-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abs</span>(Z_IR)</span></code></pre></div>
<pre><code>## [1] 1.16584</code></pre>
<p>The absolute value of the <span class="math inline">\(Z\)</span>-value is 1.17, which falls below the critical value for significance of 1.96 for two-tailed test with an alpha of .05, where alpha is our <em>p</em>-value cutoff for statistical significance. Based on this critical value, we can conclude that the ratio of the selection ratios for men and women (i.e., the impact ratio) does <em>not</em> differ significantly from an impact ratio of 1.0, where the latter would indicate that the selection ratios are equal.</p>
<p>Like we did with the <span class="math inline">\(Z_{D}\)</span> test, we can apply the more liberal one-tailed test with alpha equal to .05, where he critical value for a one-tailed test with an alpha of .05 is 1.645. We can see that our observed <span class="math inline">\(Z\)</span>-value of 1.17 is also less than that critical value. Thus, with respect to the <span class="math inline">\(Z_{IR}\)</span> test, we can conclude that the there is no relative difference between the selection ratios for men and women.</p>
<p>We might also want want to report the exact <em>p</em>-value for the <span class="math inline">\(Z_{IR}\)</span> test. To calculate the exact <em>p</em>-value for a one-tailed test, we will plug the absolute value of our <span class="math inline">\(Z\)</span>-value into the first argument of the <code>pnorm</code> function from base <code>R</code>; and as the second argument, we will specify <code>lower.tail=FALSE</code>, to specify that only want the upper tail of the test, thereby requesting a one-tailed test.</p>
<div class="sourceCode" id="cb856"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb856-1"><a href="disparateimpact.html#cb856-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate exact p-value (one-tailed)</span></span>
<span id="cb856-2"><a href="disparateimpact.html#cb856-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fu">abs</span>(Z_IR), <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.1218396</code></pre>
<p>To compute a two-tailed <em>p</em>-value, we will take the <code>pnorm</code> function from above, and multiple the resulting <em>p</em>-value by 2 using the <code>*</code> (multiplication) operator.</p>
<div class="sourceCode" id="cb858"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb858-1"><a href="disparateimpact.html#cb858-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate exact p-value (two-tailed)</span></span>
<span id="cb858-2"><a href="disparateimpact.html#cb858-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pnorm</span>(<span class="fu">abs</span>(Z_IR), <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.2436793</code></pre>
<p>Both the one- and two-tailed <em>p</em>-values are above the conventional alpha of .05, and thus both indicate that we should fail to reject the null hypothesis that there is zero relative difference between the population selection ratios for men and women with respect to the cognitive ability test.</p>
<div id="optional-compute-confidence-intervals-for-z_ir-test" class="section level4" number="28.5.0.1">
<h4><span class="header-section-number">28.5.0.1</span> Optional: Compute Confidence Intervals for <span class="math inline">\(Z_{IR}\)</span> Test</h4>
<p>Given that tests of disparate impact often involve small sample sizes and thus are susceptible to low statistical power, some have recommended that effect sizes and confidence intervals be used instead of interpreting statistical significance using a <em>p</em>-value <span class="citation">(see <a href="references.html#ref-morris2000significance" role="doc-biblioref">Morris and Lobsenz 2000</a>)</span>. Confidence intervals around an impact ratio estimate reflect sampling error and provide a range of possible values in which the population parameter (i.e., population impact ratio) may fall – or put differently, how the impact ratio will likely vary across different samples drawn from the same population.</p>
<p>To compute the confidence intervals for the <span class="math inline">\(Z_{IR}\)</span> test, we’ll first need to compute the natural log of the impact ratio using the <code>log</code> function from base <code>R</code>. We’ll assign the natural log of the impact ratio to an object that we’ll call <code>IR_log</code>.</p>
<div class="sourceCode" id="cb860"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb860-1"><a href="disparateimpact.html#cb860-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute natural log of impact ratio (IR)</span></span>
<span id="cb860-2"><a href="disparateimpact.html#cb860-2" aria-hidden="true" tabindex="-1"></a>IR_log <span class="ot">&lt;-</span> <span class="fu">log</span>(SR_women<span class="sc">/</span>SR_men)</span></code></pre></div>
<p>Next, we will compute the standard error of the impact ratio using the formula shown in the code chunk below, and we will assign it to an object that we’ll call <code>SE_IR</code>.</p>
<div class="sourceCode" id="cb861"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb861-1"><a href="disparateimpact.html#cb861-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute standard error of IR (SE_IR)</span></span>
<span id="cb861-2"><a href="disparateimpact.html#cb861-2" aria-hidden="true" tabindex="-1"></a>SE_IR <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(</span>
<span id="cb861-3"><a href="disparateimpact.html#cb861-3" aria-hidden="true" tabindex="-1"></a>  ((<span class="dv">1</span> <span class="sc">-</span> SR_women) <span class="sc">/</span> </span>
<span id="cb861-4"><a href="disparateimpact.html#cb861-4" aria-hidden="true" tabindex="-1"></a>     (N_women <span class="sc">*</span> SR_women) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> SR_men)<span class="sc">/</span>(N_men <span class="sc">*</span> SR_men))</span>
<span id="cb861-5"><a href="disparateimpact.html#cb861-5" aria-hidden="true" tabindex="-1"></a>              )</span></code></pre></div>
<p>Using the standard error of the impact ratio object (<code>SE_IR</code>) and the natural log of the impact ratio object (<code>IR_log</code>), we can compute the lower and upper limits of the a 95% confidence interval by adding and subtracting, respectively, the product of the standard error of the impact ratio and 1.96 to/from the natural log of the impact ratio.</p>
<div class="sourceCode" id="cb862"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb862-1"><a href="disparateimpact.html#cb862-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute bounds of 95% confidence interval for natural log</span></span>
<span id="cb862-2"><a href="disparateimpact.html#cb862-2" aria-hidden="true" tabindex="-1"></a><span class="co"># of impact ratio</span></span>
<span id="cb862-3"><a href="disparateimpact.html#cb862-3" aria-hidden="true" tabindex="-1"></a>LCL_log <span class="ot">&lt;-</span> IR_log <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> SE_IR <span class="co"># lower</span></span>
<span id="cb862-4"><a href="disparateimpact.html#cb862-4" aria-hidden="true" tabindex="-1"></a>UCL_log <span class="ot">&lt;-</span> IR_log <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> SE_IR <span class="co"># upper</span></span></code></pre></div>
<p>Finally, we can convert the lower and upper limits of the 95% confidence interval to the original scale of the impact ratio metric by exponentiating the lower and upper limits of the natural log of the impact ratio.</p>
<div class="sourceCode" id="cb863"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb863-1"><a href="disparateimpact.html#cb863-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to scale of original IR metric</span></span>
<span id="cb863-2"><a href="disparateimpact.html#cb863-2" aria-hidden="true" tabindex="-1"></a>LCL <span class="ot">&lt;-</span> <span class="fu">exp</span>(LCL_log) <span class="co"># lower</span></span>
<span id="cb863-3"><a href="disparateimpact.html#cb863-3" aria-hidden="true" tabindex="-1"></a>UCL <span class="ot">&lt;-</span> <span class="fu">exp</span>(UCL_log) <span class="co"># upper</span></span>
<span id="cb863-4"><a href="disparateimpact.html#cb863-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb863-5"><a href="disparateimpact.html#cb863-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the 95% confidence intervals</span></span>
<span id="cb863-6"><a href="disparateimpact.html#cb863-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(LCL)</span></code></pre></div>
<pre><code>## [1] 0.6252696</code></pre>
<div class="sourceCode" id="cb865"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb865-1"><a href="disparateimpact.html#cb865-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(UCL)</span></code></pre></div>
<pre><code>## [1] 1.134137</code></pre>
<p>Thus, we can be 95% confident that the true population impact ratio falls somewhere between .63 and 1.13 (95% CI[.63, 1.13]), and we already know that the effect size (i.e., impact ratio) for this cognitive ability test with respect to gender is .84 based on our test of the 4/5ths Rule (see above). Note that if the population parameter were to fall at the lower limit of the confidence interval (.63), then we would conclude there was disparate impact based on the 4/5ths Rule; however, if the the population parameter were to fall at the upper limit of the confidence interval (1.13), we would conclude that conclude that there wasn’t disparate impact based on the 4/5ths Rule. Thus, the confidence interval indicates that if we were to sample from the same population many more times, we would sometimes find a violation of the 4/5ths Rule – but sometimes not.</p>
<p>If we want, we can also compute the 90% confidence intervals for the impact ratio by swapping the 1.96 critical <span class="math inline">\(Z\)</span>-value for a <em>two</em>-tailed test (alpha = .05) with the 1.645 critical <span class="math inline">\(Z\)</span>-value for a <em>one</em>-tailed test (alpha = .05). Everything else will remain the same as when we computed the 95% confidence interval.</p>
<div class="sourceCode" id="cb867"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb867-1"><a href="disparateimpact.html#cb867-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute bounds of 90% confidence interval for natural log</span></span>
<span id="cb867-2"><a href="disparateimpact.html#cb867-2" aria-hidden="true" tabindex="-1"></a><span class="co"># of impact ratio</span></span>
<span id="cb867-3"><a href="disparateimpact.html#cb867-3" aria-hidden="true" tabindex="-1"></a>LCL_log <span class="ot">&lt;-</span> IR_log <span class="sc">-</span> <span class="fl">1.645</span> <span class="sc">*</span> SE_IR <span class="co"># lower</span></span>
<span id="cb867-4"><a href="disparateimpact.html#cb867-4" aria-hidden="true" tabindex="-1"></a>UCL_log <span class="ot">&lt;-</span> IR_log <span class="sc">+</span> <span class="fl">1.645</span> <span class="sc">*</span> SE_IR <span class="co"># upper</span></span>
<span id="cb867-5"><a href="disparateimpact.html#cb867-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb867-6"><a href="disparateimpact.html#cb867-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to scale of original IR metric</span></span>
<span id="cb867-7"><a href="disparateimpact.html#cb867-7" aria-hidden="true" tabindex="-1"></a>LCL <span class="ot">&lt;-</span> <span class="fu">exp</span>(LCL_log) <span class="co"># lower</span></span>
<span id="cb867-8"><a href="disparateimpact.html#cb867-8" aria-hidden="true" tabindex="-1"></a>UCL <span class="ot">&lt;-</span> <span class="fu">exp</span>(UCL_log) <span class="co"># upper</span></span>
<span id="cb867-9"><a href="disparateimpact.html#cb867-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb867-10"><a href="disparateimpact.html#cb867-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the 90% confidence intervals</span></span>
<span id="cb867-11"><a href="disparateimpact.html#cb867-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(LCL)</span></code></pre></div>
<pre><code>## [1] 0.655915</code></pre>
<div class="sourceCode" id="cb869"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb869-1"><a href="disparateimpact.html#cb869-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(UCL)</span></code></pre></div>
<pre><code>## [1] 1.081148</code></pre>
<p>Based on these calculations, we can be 90% confident that the true population impact ratio falls somewhere between .66 and 1.08 (90% CI[.66, 1.08]).</p>
</div>
</div>
<div id="summary_disparatetreatment" class="section level2" number="28.6">
<h2><span class="header-section-number">28.6</span> Summary</h2>
<p>In this chapter, we learned how to evaluate whether there is evidence of disparate impact using the 4/5ths Rule, chi-square (<span class="math inline">\(\chi^2\)</span>) test of independence, Fisher exact test, <span class="math inline">\(Z_{D}\)</span> test, and <span class="math inline">\(Z_{IR}\)</span> test.</p>

</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="selection.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="create-portfolio.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
