<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 17 Joining (Merging) Data | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION</title>
  <meta name="description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 17 Joining (Merging) Data | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://rforhr.com" />
  <meta property="og:image" content="https://rforhr.comcover.png" />
  <meta property="og:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="github-repo" content="davidcaughlin/R-for-HR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 17 Joining (Merging) Data | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  
  <meta name="twitter:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="twitter:image" content="https://rforhr.comcover.png" />

<meta name="author" content="David E. Caughlin" />


<meta name="date" content="2021-12-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="arrange.html"/>
<link rel="next" href="filter.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for HR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#hragrowth"><i class="fa fa-check"></i><b>0.1</b> Growth of HR Analytics</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#skills-gap"><i class="fa fa-check"></i><b>0.2</b> Skills Gap</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#hraplc"><i class="fa fa-check"></i><b>0.3</b> Project Life Cycle Perspective</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#overview-of-hris-hr-analytics"><i class="fa fa-check"></i><b>0.4</b> Overview of HRIS &amp; HR Analytics</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#philosophy"><i class="fa fa-check"></i><b>0.5</b> My Philosophy for This Book</a>
<ul>
<li class="chapter" data-level="0.5.1" data-path="index.html"><a href="index.html#rationalerpref"><i class="fa fa-check"></i><b>0.5.1</b> Rationale for Using R</a></li>
<li class="chapter" data-level="0.5.2" data-path="index.html"><a href="index.html#audiencepref"><i class="fa fa-check"></i><b>0.5.2</b> Audience</a></li>
<li class="chapter" data-level="0.5.3" data-path="index.html"><a href="index.html#structurepref"><i class="fa fa-check"></i><b>0.5.3</b> Structure</a></li>
</ul></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#aboutauthor"><i class="fa fa-check"></i><b>0.6</b> About the Author</a></li>
<li class="chapter" data-level="0.7" data-path="index.html"><a href="index.html#acknowpref"><i class="fa fa-check"></i><b>0.7</b> Acknowledgements</a></li>
</ul></li>
<li class="part"><span><b>I HR Analytics Project Life Cycle</b></span></li>
<li class="chapter" data-level="1" data-path="overviewhraplc.html"><a href="overviewhraplc.html"><i class="fa fa-check"></i><b>1</b> Overview of HR Analytics Project Life Cycle</a></li>
<li class="chapter" data-level="2" data-path="questionformulation.html"><a href="questionformulation.html"><i class="fa fa-check"></i><b>2</b> Question Formulation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="questionformulation.html"><a href="questionformulation.html#adoptstrategicmindset"><i class="fa fa-check"></i><b>2.1</b> Adopting a Strategic Mindset</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="questionformulation.html"><a href="questionformulation.html#strategy"><i class="fa fa-check"></i><b>2.1.1</b> Strategy</a></li>
<li class="chapter" data-level="2.1.2" data-path="questionformulation.html"><a href="questionformulation.html#strategyformulation"><i class="fa fa-check"></i><b>2.1.2</b> Strategy Formulation</a></li>
<li class="chapter" data-level="2.1.3" data-path="questionformulation.html"><a href="questionformulation.html#strategyimplementation"><i class="fa fa-check"></i><b>2.1.3</b> Strategy Implementation</a></li>
<li class="chapter" data-level="2.1.4" data-path="questionformulation.html"><a href="questionformulation.html#strategichrm"><i class="fa fa-check"></i><b>2.1.4</b> Strategic Human Resource Management</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="questionformulation.html"><a href="questionformulation.html#defining-problems-formulating-questions"><i class="fa fa-check"></i><b>2.2</b> Defining Problems &amp; Formulating Questions</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="questionformulation.html"><a href="questionformulation.html#definingaproblem"><i class="fa fa-check"></i><b>2.2.1</b> Defining a Problem</a></li>
<li class="chapter" data-level="2.2.2" data-path="questionformulation.html"><a href="questionformulation.html#formulatingaquestion"><i class="fa fa-check"></i><b>2.2.2</b> Formulating a Question</a></li>
<li class="chapter" data-level="2.2.3" data-path="questionformulation.html"><a href="questionformulation.html#divergentconvergentthinking"><i class="fa fa-check"></i><b>2.2.3</b> Thinking Divergently &amp; Convergently</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="questionformulation.html"><a href="questionformulation.html#summary"><i class="fa fa-check"></i><b>2.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dataacquisition.html"><a href="dataacquisition.html"><i class="fa fa-check"></i><b>3</b> Data Acquisition</a>
<ul>
<li class="chapter" data-level="3.1" data-path="dataacquisition.html"><a href="dataacquisition.html#employee-surveys"><i class="fa fa-check"></i><b>3.1</b> Employee Surveys</a></li>
<li class="chapter" data-level="3.2" data-path="dataacquisition.html"><a href="dataacquisition.html#rating-forms"><i class="fa fa-check"></i><b>3.2</b> Rating Forms</a></li>
<li class="chapter" data-level="3.3" data-path="dataacquisition.html"><a href="dataacquisition.html#surveillance-monitoring"><i class="fa fa-check"></i><b>3.3</b> Surveillance &amp; Monitoring</a></li>
<li class="chapter" data-level="3.4" data-path="dataacquisition.html"><a href="dataacquisition.html#database-queries"><i class="fa fa-check"></i><b>3.4</b> Database Queries</a></li>
<li class="chapter" data-level="3.5" data-path="dataacquisition.html"><a href="dataacquisition.html#scraping"><i class="fa fa-check"></i><b>3.5</b> Scraping</a></li>
<li class="chapter" data-level="3.6" data-path="dataacquisition.html"><a href="dataacquisition.html#summary-1"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="datamanagement.html"><a href="datamanagement.html"><i class="fa fa-check"></i><b>4</b> Data Management</a>
<ul>
<li class="chapter" data-level="4.1" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_clean"><i class="fa fa-check"></i><b>4.1</b> Data Cleaning</a></li>
<li class="chapter" data-level="4.2" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_manipulate"><i class="fa fa-check"></i><b>4.2</b> Data Manipulation &amp; Structuring</a></li>
<li class="chapter" data-level="4.3" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_tools"><i class="fa fa-check"></i><b>4.3</b> Common Data-Management Tools</a></li>
<li class="chapter" data-level="4.4" data-path="datamanagement.html"><a href="datamanagement.html#summary-2"><i class="fa fa-check"></i><b>4.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dataanalysis.html"><a href="dataanalysis.html"><i class="fa fa-check"></i><b>5</b> Data Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="dataanalysis.html"><a href="dataanalysis.html#dataanalysis_toolstechniques"><i class="fa fa-check"></i><b>5.1</b> Tools &amp; Techniques</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="dataanalysis.html"><a href="dataanalysis.html#mathematics"><i class="fa fa-check"></i><b>5.1.1</b> Mathematics</a></li>
<li class="chapter" data-level="5.1.2" data-path="dataanalysis.html"><a href="dataanalysis.html#statistics"><i class="fa fa-check"></i><b>5.1.2</b> Statistics</a></li>
<li class="chapter" data-level="5.1.3" data-path="dataanalysis.html"><a href="dataanalysis.html#machinelearning"><i class="fa fa-check"></i><b>5.1.3</b> Machine Learning</a></li>
<li class="chapter" data-level="5.1.4" data-path="dataanalysis.html"><a href="dataanalysis.html#computationalmodelsimulation"><i class="fa fa-check"></i><b>5.1.4</b> Computational Modeling &amp; Simulations</a></li>
<li class="chapter" data-level="5.1.5" data-path="dataanalysis.html"><a href="dataanalysis.html#textqualitativeanalyses"><i class="fa fa-check"></i><b>5.1.5</b> Text Analyses &amp; Qualitative Analyses</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="dataanalysis.html"><a href="dataanalysis.html#continuum_dataanalytics"><i class="fa fa-check"></i><b>5.2</b> Continuum of Data Analytics</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="dataanalysis.html"><a href="dataanalysis.html#descriptive_analytics"><i class="fa fa-check"></i><b>5.2.1</b> Descriptive Analytics</a></li>
<li class="chapter" data-level="5.2.2" data-path="dataanalysis.html"><a href="dataanalysis.html#predictish_analytics"><i class="fa fa-check"></i><b>5.2.2</b> Predict-ish Analytics</a></li>
<li class="chapter" data-level="5.2.3" data-path="dataanalysis.html"><a href="dataanalysis.html#predictive_analytics"><i class="fa fa-check"></i><b>5.2.3</b> Predictive Analytics</a></li>
<li class="chapter" data-level="5.2.4" data-path="dataanalysis.html"><a href="dataanalysis.html#prescriptive_analytics"><i class="fa fa-check"></i><b>5.2.4</b> Prescriptive Analytics</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="dataanalysis.html"><a href="dataanalysis.html#summary-3"><i class="fa fa-check"></i><b>5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html"><i class="fa fa-check"></i><b>6</b> Data Interpretation &amp; Storytelling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#datainterpretation"><i class="fa fa-check"></i><b>6.1</b> Data Interpretation</a></li>
<li class="chapter" data-level="6.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling"><i class="fa fa-check"></i><b>6.2</b> Storytelling</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#structure"><i class="fa fa-check"></i><b>6.2.1</b> Structure</a></li>
<li class="chapter" data-level="6.2.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#clarity-parsimony"><i class="fa fa-check"></i><b>6.2.2</b> Clarity &amp; Parsimony</a></li>
<li class="chapter" data-level="6.2.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#influence-persuasion"><i class="fa fa-check"></i><b>6.2.3</b> Influence &amp; Persuasion</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling_withdata"><i class="fa fa-check"></i><b>6.3</b> Storytelling with Data</a></li>
<li class="chapter" data-level="6.4" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#summary-4"><i class="fa fa-check"></i><b>6.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html"><i class="fa fa-check"></i><b>7</b> Deployment &amp; Implementation</a></li>
<li class="part"><span><b>II Introduction to R</b></span></li>
<li class="chapter" data-level="8" data-path="overviewR.html"><a href="overviewR.html"><i class="fa fa-check"></i><b>8</b> Overview of R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="8.1" data-path="overviewR.html"><a href="overviewR.html#R_overview"><i class="fa fa-check"></i><b>8.1</b> R Programming Language</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="overviewR.html"><a href="overviewR.html#R_what"><i class="fa fa-check"></i><b>8.1.1</b> What Is R?</a></li>
<li class="chapter" data-level="8.1.2" data-path="overviewR.html"><a href="overviewR.html#R_why"><i class="fa fa-check"></i><b>8.1.2</b> Why Use R?</a></li>
<li class="chapter" data-level="8.1.3" data-path="overviewR.html"><a href="overviewR.html#R_who"><i class="fa fa-check"></i><b>8.1.3</b> Who Uses R?</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="overviewR.html"><a href="overviewR.html#RStudio_overview"><i class="fa fa-check"></i><b>8.2</b> RStudio</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="overviewR.html"><a href="overviewR.html#RStudio_what"><i class="fa fa-check"></i><b>8.2.1</b> What is RStudio?</a></li>
<li class="chapter" data-level="8.2.2" data-path="overviewR.html"><a href="overviewR.html#RStudio_why"><i class="fa fa-check"></i><b>8.2.2</b> Why RStudio?</a></li>
<li class="chapter" data-level="8.2.3" data-path="overviewR.html"><a href="overviewR.html#RStudio_who"><i class="fa fa-check"></i><b>8.2.3</b> Who Uses RStudio?</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="overviewR.html"><a href="overviewR.html#packages_overview"><i class="fa fa-check"></i><b>8.3</b> Packages</a></li>
<li class="chapter" data-level="8.4" data-path="overviewR.html"><a href="overviewR.html#summary-5"><i class="fa fa-check"></i><b>8.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>9</b> Installing R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="9.1" data-path="install.html"><a href="install.html#videotutorial_install"><i class="fa fa-check"></i><b>9.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="9.2" data-path="install.html"><a href="install.html#installR"><i class="fa fa-check"></i><b>9.2</b> Downloading &amp; Installing R</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="install.html"><a href="install.html#installR_windows"><i class="fa fa-check"></i><b>9.2.1</b> For Windows Operation Systems</a></li>
<li class="chapter" data-level="9.2.2" data-path="install.html"><a href="install.html#installR_macos"><i class="fa fa-check"></i><b>9.2.2</b> For Mac Operating Systems</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="install.html"><a href="install.html#installRStudio"><i class="fa fa-check"></i><b>9.3</b> Downloading &amp; Installing RStudio</a></li>
<li class="chapter" data-level="9.4" data-path="install.html"><a href="install.html#summary_install"><i class="fa fa-check"></i><b>9.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="gettingstarted.html"><a href="gettingstarted.html"><i class="fa fa-check"></i><b>10</b> Getting Started with R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="10.1" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation_gettingstarted"><i class="fa fa-check"></i><b>10.1</b> Orientation to RStudio</a></li>
<li class="chapter" data-level="10.2" data-path="gettingstarted.html"><a href="gettingstarted.html#createRscript"><i class="fa fa-check"></i><b>10.2</b> Creating &amp; Saving an R Script</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="gettingstarted.html"><a href="gettingstarted.html#createnewRscript_gettingstarted"><i class="fa fa-check"></i><b>10.2.1</b> Creating a New R Script</a></li>
<li class="chapter" data-level="10.2.2" data-path="gettingstarted.html"><a href="gettingstarted.html#usenewRscript_gettingstarted"><i class="fa fa-check"></i><b>10.2.2</b> Using an R Script</a></li>
<li class="chapter" data-level="10.2.3" data-path="gettingstarted.html"><a href="gettingstarted.html#saveRscript_gettingstarted"><i class="fa fa-check"></i><b>10.2.3</b> Saving an R Script</a></li>
<li class="chapter" data-level="10.2.4" data-path="gettingstarted.html"><a href="gettingstarted.html#openRscript_gettingstarted"><i class="fa fa-check"></i><b>10.2.4</b> Opening a Saved R Script</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="gettingstarted.html"><a href="gettingstarted.html#RStudioproject_gettingstarted"><i class="fa fa-check"></i><b>10.3</b> Creating an RStudio Project</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="gettingstarted.html"><a href="gettingstarted.html#createRStudioproject_gettingstarted"><i class="fa fa-check"></i><b>10.3.1</b> Creating a New RStudio Project</a></li>
<li class="chapter" data-level="10.3.2" data-path="gettingstarted.html"><a href="gettingstarted.html#openRStudioproject_gettingstarted"><i class="fa fa-check"></i><b>10.3.2</b> Opening an Existing RStudio Project</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="gettingstarted.html"><a href="gettingstarted.html#writtentutorials_gettingstarted"><i class="fa fa-check"></i><b>10.4</b> Orientation to Written Tutorials</a></li>
<li class="chapter" data-level="10.5" data-path="gettingstarted.html"><a href="gettingstarted.html#summary_gettingstarted"><i class="fa fa-check"></i><b>10.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="gentleintro.html"><a href="gentleintro.html"><i class="fa fa-check"></i><b>11</b> Basic Features and Operations of the R Language</a>
<ul>
<li class="chapter" data-level="11.1" data-path="gentleintro.html"><a href="gentleintro.html#videotutorial_gentleintro"><i class="fa fa-check"></i><b>11.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="11.2" data-path="gentleintro.html"><a href="gentleintro.html#functions_gentleintro"><i class="fa fa-check"></i><b>11.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="11.3" data-path="gentleintro.html"><a href="gentleintro.html#r_as_calculator"><i class="fa fa-check"></i><b>11.3</b> R as a Calculator</a></li>
<li class="chapter" data-level="11.4" data-path="gentleintro.html"><a href="gentleintro.html#functions"><i class="fa fa-check"></i><b>11.4</b> Functions</a></li>
<li class="chapter" data-level="11.5" data-path="gentleintro.html"><a href="gentleintro.html#packages"><i class="fa fa-check"></i><b>11.5</b> Packages</a></li>
<li class="chapter" data-level="11.6" data-path="gentleintro.html"><a href="gentleintro.html#variableassignment"><i class="fa fa-check"></i><b>11.6</b> Variable Assignment</a></li>
<li class="chapter" data-level="11.7" data-path="gentleintro.html"><a href="gentleintro.html#typesofdata"><i class="fa fa-check"></i><b>11.7</b> Types of Data</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="gentleintro.html"><a href="gentleintro.html#numeric-data"><i class="fa fa-check"></i><b>11.7.1</b> <code>numeric</code> Data</a></li>
<li class="chapter" data-level="11.7.2" data-path="gentleintro.html"><a href="gentleintro.html#character-data"><i class="fa fa-check"></i><b>11.7.2</b> <code>character</code> Data</a></li>
<li class="chapter" data-level="11.7.3" data-path="gentleintro.html"><a href="gentleintro.html#date-data"><i class="fa fa-check"></i><b>11.7.3</b> <code>Date</code> Data</a></li>
<li class="chapter" data-level="11.7.4" data-path="gentleintro.html"><a href="gentleintro.html#logical-data"><i class="fa fa-check"></i><b>11.7.4</b> <code>logical</code> Data</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="gentleintro.html"><a href="gentleintro.html#vectors"><i class="fa fa-check"></i><b>11.8</b> Vectors</a></li>
<li class="chapter" data-level="11.9" data-path="gentleintro.html"><a href="gentleintro.html#lists"><i class="fa fa-check"></i><b>11.9</b> Lists</a></li>
<li class="chapter" data-level="11.10" data-path="gentleintro.html"><a href="gentleintro.html#dataframes"><i class="fa fa-check"></i><b>11.10</b> Data Frames</a></li>
<li class="chapter" data-level="11.11" data-path="gentleintro.html"><a href="gentleintro.html#annotate"><i class="fa fa-check"></i><b>11.11</b> Annotations</a></li>
<li class="chapter" data-level="11.12" data-path="gentleintro.html"><a href="gentleintro.html#summary_gentleintro"><i class="fa fa-check"></i><b>11.12</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="setwd.html"><a href="setwd.html"><i class="fa fa-check"></i><b>12</b> Setting a Working Directory</a>
<ul>
<li class="chapter" data-level="12.1" data-path="setwd.html"><a href="setwd.html#videotutorial_setwd"><i class="fa fa-check"></i><b>12.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="12.2" data-path="setwd.html"><a href="setwd.html#functions_setwd"><i class="fa fa-check"></i><b>12.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="12.3" data-path="setwd.html"><a href="setwd.html#getwd_setwd"><i class="fa fa-check"></i><b>12.3</b> Identify the Current Working Directory</a></li>
<li class="chapter" data-level="12.4" data-path="setwd.html"><a href="setwd.html#setwd_setwd"><i class="fa fa-check"></i><b>12.4</b> Set a New Working Directory</a></li>
<li class="chapter" data-level="12.5" data-path="setwd.html"><a href="setwd.html#summary_setwd"><i class="fa fa-check"></i><b>12.5</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>III Data Acquisition &amp; Management</b></span></li>
<li class="chapter" data-level="13" data-path="read.html"><a href="read.html"><i class="fa fa-check"></i><b>13</b> Reading Data into R</a>
<ul>
<li class="chapter" data-level="13.1" data-path="read.html"><a href="read.html#conceptualoverview_read"><i class="fa fa-check"></i><b>13.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="13.2" data-path="read.html"><a href="read.html#tutorial_read"><i class="fa fa-check"></i><b>13.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="read.html"><a href="read.html#videotutorial_read"><i class="fa fa-check"></i><b>13.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="13.2.2" data-path="read.html"><a href="read.html#functions_read"><i class="fa fa-check"></i><b>13.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="13.2.3" data-path="read.html"><a href="read.html#initialsteps_read"><i class="fa fa-check"></i><b>13.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="13.2.4" data-path="read.html"><a href="read.html#readcsv"><i class="fa fa-check"></i><b>13.2.4</b> Read a .csv File</a></li>
<li class="chapter" data-level="13.2.5" data-path="read.html"><a href="read.html#readxlsx"><i class="fa fa-check"></i><b>13.2.5</b> Read a .xlsx File</a></li>
<li class="chapter" data-level="13.2.6" data-path="read.html"><a href="read.html#read_summary"><i class="fa fa-check"></i><b>13.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="read.html"><a href="read.html#read_supplement"><i class="fa fa-check"></i><b>13.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="read.html"><a href="read.html#read_supplement_functions"><i class="fa fa-check"></i><b>13.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="13.3.2" data-path="read.html"><a href="read.html#read_initsteps_supplement"><i class="fa fa-check"></i><b>13.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="13.3.3" data-path="read.html"><a href="read.html#read_additionalfunctions"><i class="fa fa-check"></i><b>13.3.3</b> Additional Functions for Reading a .csv File</a></li>
<li class="chapter" data-level="13.3.4" data-path="read.html"><a href="read.html#read_skiprows"><i class="fa fa-check"></i><b>13.3.4</b> Skip Rows of Data During Read</a></li>
<li class="chapter" data-level="13.3.5" data-path="read.html"><a href="read.html#listdatafiles"><i class="fa fa-check"></i><b>13.3.5</b> List Data File Names in Working Directory</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="addnames.html"><a href="addnames.html"><i class="fa fa-check"></i><b>14</b> Removing, Adding, &amp; Changing Variable Names</a>
<ul>
<li class="chapter" data-level="14.1" data-path="addnames.html"><a href="addnames.html#conceptualoverview_addnames"><i class="fa fa-check"></i><b>14.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="14.2" data-path="addnames.html"><a href="addnames.html#tutorial_addnames"><i class="fa fa-check"></i><b>14.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="addnames.html"><a href="addnames.html#videotutorial_addnames"><i class="fa fa-check"></i><b>14.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="14.2.2" data-path="addnames.html"><a href="addnames.html#function_addnames"><i class="fa fa-check"></i><b>14.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="14.2.3" data-path="addnames.html"><a href="addnames.html#initsteps_addnames"><i class="fa fa-check"></i><b>14.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="14.2.4" data-path="addnames.html"><a href="addnames.html#remove_variablenames"><i class="fa fa-check"></i><b>14.2.4</b> Remove Variable Names from a Data Frame Object</a></li>
<li class="chapter" data-level="14.2.5" data-path="addnames.html"><a href="addnames.html#add_variablenames"><i class="fa fa-check"></i><b>14.2.5</b> Add Variable Names to a Data Frame Object</a></li>
<li class="chapter" data-level="14.2.6" data-path="addnames.html"><a href="addnames.html#change_variablenames"><i class="fa fa-check"></i><b>14.2.6</b> Change Specific Variable Names in a Data Frame Object</a></li>
<li class="chapter" data-level="14.2.7" data-path="addnames.html"><a href="addnames.html#summary_addnames"><i class="fa fa-check"></i><b>14.2.7</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="write.html"><a href="write.html"><i class="fa fa-check"></i><b>15</b> Writing Data from R</a>
<ul>
<li class="chapter" data-level="15.1" data-path="write.html"><a href="write.html#conceptualoverview_write"><i class="fa fa-check"></i><b>15.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="15.2" data-path="write.html"><a href="write.html#tutorial_write"><i class="fa fa-check"></i><b>15.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="write.html"><a href="write.html#videotutorial_write"><i class="fa fa-check"></i><b>15.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="15.2.2" data-path="write.html"><a href="write.html#functions_write"><i class="fa fa-check"></i><b>15.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="15.2.3" data-path="write.html"><a href="write.html#initialsteps_write"><i class="fa fa-check"></i><b>15.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="15.2.4" data-path="write.html"><a href="write.html#write_dataframe"><i class="fa fa-check"></i><b>15.2.4</b> Write Data Frame to Working Directory</a></li>
<li class="chapter" data-level="15.2.5" data-path="write.html"><a href="write.html#write_table"><i class="fa fa-check"></i><b>15.2.5</b> Write Table to Working Directory</a></li>
<li class="chapter" data-level="15.2.6" data-path="write.html"><a href="write.html#summary_write"><i class="fa fa-check"></i><b>15.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>16</b> Arranging (Sorting) Data</a>
<ul>
<li class="chapter" data-level="16.1" data-path="arrange.html"><a href="arrange.html#conceptualoverview_arrange"><i class="fa fa-check"></i><b>16.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="16.2" data-path="arrange.html"><a href="arrange.html#tutorial_arrange"><i class="fa fa-check"></i><b>16.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="arrange.html"><a href="arrange.html#videotutorial_arrange"><i class="fa fa-check"></i><b>16.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="16.2.2" data-path="arrange.html"><a href="arrange.html#functions_arrange"><i class="fa fa-check"></i><b>16.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="16.2.3" data-path="arrange.html"><a href="arrange.html#initsteps_arrange"><i class="fa fa-check"></i><b>16.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="16.2.4" data-path="arrange.html"><a href="arrange.html#arrangebyvalues"><i class="fa fa-check"></i><b>16.2.4</b> Arrange (Sort) Data</a></li>
<li class="chapter" data-level="16.2.5" data-path="arrange.html"><a href="arrange.html#summary_arrange"><i class="fa fa-check"></i><b>16.2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="arrange.html"><a href="arrange.html#arrange_supplement"><i class="fa fa-check"></i><b>16.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="arrange.html"><a href="arrange.html#arrange_supplement_functions"><i class="fa fa-check"></i><b>16.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="16.3.2" data-path="arrange.html"><a href="arrange.html#arrange_initsteps_supplement"><i class="fa fa-check"></i><b>16.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="16.3.3" data-path="arrange.html"><a href="arrange.html#arrange_orderfunction"><i class="fa fa-check"></i><b>16.3.3</b> <code>order</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="join.html"><a href="join.html"><i class="fa fa-check"></i><b>17</b> Joining (Merging) Data</a>
<ul>
<li class="chapter" data-level="17.1" data-path="join.html"><a href="join.html#conceptualoverview_join"><i class="fa fa-check"></i><b>17.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="join.html"><a href="join.html#review_horizontaljoin"><i class="fa fa-check"></i><b>17.1.1</b> Review of Horizontal Joins (Merges)</a></li>
<li class="chapter" data-level="17.1.2" data-path="join.html"><a href="join.html#review_verticaljoin"><i class="fa fa-check"></i><b>17.1.2</b> Review of Vertical Joins (Merges)</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="join.html"><a href="join.html#tutorial_join"><i class="fa fa-check"></i><b>17.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="join.html"><a href="join.html#videotutorial_join"><i class="fa fa-check"></i><b>17.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="17.2.2" data-path="join.html"><a href="join.html#functions-packages-introduced"><i class="fa fa-check"></i><b>17.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="17.2.3" data-path="join.html"><a href="join.html#initsteps_join"><i class="fa fa-check"></i><b>17.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="17.2.4" data-path="join.html"><a href="join.html#horizontaljoin"><i class="fa fa-check"></i><b>17.2.4</b> Horizontal Join (Merge)</a></li>
<li class="chapter" data-level="17.2.5" data-path="join.html"><a href="join.html#verticaljoin"><i class="fa fa-check"></i><b>17.2.5</b> Vertical Join (Merge)</a></li>
<li class="chapter" data-level="17.2.6" data-path="join.html"><a href="join.html#summary_join"><i class="fa fa-check"></i><b>17.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="join.html"><a href="join.html#join_supplement"><i class="fa fa-check"></i><b>17.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="join.html"><a href="join.html#supp_join_video"><i class="fa fa-check"></i><b>17.3.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="17.3.2" data-path="join.html"><a href="join.html#join_supplement_functions"><i class="fa fa-check"></i><b>17.3.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="17.3.3" data-path="join.html"><a href="join.html#join_initsteps_supplement"><i class="fa fa-check"></i><b>17.3.3</b> Initial Steps</a></li>
<li class="chapter" data-level="17.3.4" data-path="join.html"><a href="join.html#join_mergefunction"><i class="fa fa-check"></i><b>17.3.4</b> <code>merge</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>18</b> Filtering (Subsetting) Data</a>
<ul>
<li class="chapter" data-level="18.1" data-path="filter.html"><a href="filter.html#conceptualoverview_filter"><i class="fa fa-check"></i><b>18.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="18.1.1" data-path="filter.html"><a href="filter.html#review_logicaloperators"><i class="fa fa-check"></i><b>18.1.1</b> Review of Logical Operators</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="filter.html"><a href="filter.html#tutorial_filter"><i class="fa fa-check"></i><b>18.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="filter.html"><a href="filter.html#videotutorial_filter"><i class="fa fa-check"></i><b>18.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="18.2.2" data-path="filter.html"><a href="filter.html#function_filter"><i class="fa fa-check"></i><b>18.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="18.2.3" data-path="filter.html"><a href="filter.html#initsteps_filter"><i class="fa fa-check"></i><b>18.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="18.2.4" data-path="filter.html"><a href="filter.html#filter_cases"><i class="fa fa-check"></i><b>18.2.4</b> Filter Cases from Data Frame</a></li>
<li class="chapter" data-level="18.2.5" data-path="filter.html"><a href="filter.html#remove-single-variable-from-data-frame"><i class="fa fa-check"></i><b>18.2.5</b> Remove Single Variable from Data Frame</a></li>
<li class="chapter" data-level="18.2.6" data-path="filter.html"><a href="filter.html#select_multiplevariables"><i class="fa fa-check"></i><b>18.2.6</b> Select Multiple Variables from Data Frame</a></li>
<li class="chapter" data-level="18.2.7" data-path="filter.html"><a href="filter.html#remove_multiplevariables"><i class="fa fa-check"></i><b>18.2.7</b> Remove Multiple Variables from Data Frame</a></li>
<li class="chapter" data-level="18.2.8" data-path="filter.html"><a href="filter.html#summary_filter"><i class="fa fa-check"></i><b>18.2.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="filter.html"><a href="filter.html#filter_supplement"><i class="fa fa-check"></i><b>18.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="filter.html"><a href="filter.html#supp_filter_video"><i class="fa fa-check"></i><b>18.3.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="18.3.2" data-path="filter.html"><a href="filter.html#filter_supplement_functions"><i class="fa fa-check"></i><b>18.3.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="18.3.3" data-path="filter.html"><a href="filter.html#filter_initsteps_supplement"><i class="fa fa-check"></i><b>18.3.3</b> Initial Steps</a></li>
<li class="chapter" data-level="18.3.4" data-path="filter.html"><a href="filter.html#filter_subset_supplement"><i class="fa fa-check"></i><b>18.3.4</b> <code>subset</code> Function from Base R</a></li>
<li class="chapter" data-level="18.3.5" data-path="filter.html"><a href="filter.html#str_detect_supp"><i class="fa fa-check"></i><b>18.3.5</b> Filter by Pattern Contained within String</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="clean.html"><a href="clean.html"><i class="fa fa-check"></i><b>19</b> Cleaning Data</a>
<ul>
<li class="chapter" data-level="19.1" data-path="clean.html"><a href="clean.html#conceptualoverview_clean"><i class="fa fa-check"></i><b>19.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="19.2" data-path="clean.html"><a href="clean.html#tutorial_clean"><i class="fa fa-check"></i><b>19.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="clean.html"><a href="clean.html#videotutorial_clean"><i class="fa fa-check"></i><b>19.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="19.2.2" data-path="clean.html"><a href="clean.html#functions_clean"><i class="fa fa-check"></i><b>19.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="19.2.3" data-path="clean.html"><a href="clean.html#initsteps_clean"><i class="fa fa-check"></i><b>19.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="19.2.4" data-path="clean.html"><a href="clean.html#reviewdata_clean"><i class="fa fa-check"></i><b>19.2.4</b> Review Data</a></li>
<li class="chapter" data-level="19.2.5" data-path="clean.html"><a href="clean.html#cleandata_clean"><i class="fa fa-check"></i><b>19.2.5</b> Clean Data</a></li>
<li class="chapter" data-level="19.2.6" data-path="clean.html"><a href="clean.html#renamevariables_clean"><i class="fa fa-check"></i><b>19.2.6</b> Rename Variables</a></li>
<li class="chapter" data-level="19.2.7" data-path="clean.html"><a href="clean.html#otherapproaches_clean"><i class="fa fa-check"></i><b>19.2.7</b> Other Approaches to Cleaning Data</a></li>
<li class="chapter" data-level="19.2.8" data-path="clean.html"><a href="clean.html#summary_clean"><i class="fa fa-check"></i><b>19.2.8</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="manipulate.html"><a href="manipulate.html"><i class="fa fa-check"></i><b>20</b> Manipulating &amp; Restructuring Data</a>
<ul>
<li class="chapter" data-level="20.1" data-path="manipulate.html"><a href="manipulate.html#conceptualoverview_manipulate"><i class="fa fa-check"></i><b>20.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="20.2" data-path="manipulate.html"><a href="manipulate.html#tutorial_manipulate"><i class="fa fa-check"></i><b>20.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="manipulate.html"><a href="manipulate.html#videotutorial_manipulate"><i class="fa fa-check"></i><b>20.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="20.2.2" data-path="manipulate.html"><a href="manipulate.html#functions_manipulate"><i class="fa fa-check"></i><b>20.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="20.2.3" data-path="manipulate.html"><a href="manipulate.html#initsteps_manipulate"><i class="fa fa-check"></i><b>20.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="20.2.4" data-path="manipulate.html"><a href="manipulate.html#manipulate_widetolong"><i class="fa fa-check"></i><b>20.2.4</b> Wide-to-Long Format Data Manipulation</a></li>
<li class="chapter" data-level="20.2.5" data-path="manipulate.html"><a href="manipulate.html#manipulate_longtowide"><i class="fa fa-check"></i><b>20.2.5</b> Long-to-Wide Format Data Manipulation</a></li>
<li class="chapter" data-level="20.2.6" data-path="manipulate.html"><a href="manipulate.html#summary_manipulate"><i class="fa fa-check"></i><b>20.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="21" data-path="center.html"><a href="center.html"><i class="fa fa-check"></i><b>21</b> Centering &amp; Standardizing Variables</a>
<ul>
<li class="chapter" data-level="21.1" data-path="center.html"><a href="center.html#conceptualoverview_center"><i class="fa fa-check"></i><b>21.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="21.1.1" data-path="center.html"><a href="center.html#review_center"><i class="fa fa-check"></i><b>21.1.1</b> Review of Centering Variables</a></li>
<li class="chapter" data-level="21.1.2" data-path="center.html"><a href="center.html#review_standardize"><i class="fa fa-check"></i><b>21.1.2</b> Review of Standardizing Variables</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="center.html"><a href="center.html#tutorial_center"><i class="fa fa-check"></i><b>21.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="center.html"><a href="center.html#videotutorial_center"><i class="fa fa-check"></i><b>21.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="21.2.2" data-path="center.html"><a href="center.html#functions_center"><i class="fa fa-check"></i><b>21.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="21.2.3" data-path="center.html"><a href="center.html#initsteps_center"><i class="fa fa-check"></i><b>21.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="21.2.4" data-path="center.html"><a href="center.html#grandmean_center"><i class="fa fa-check"></i><b>21.2.4</b> Grand-Mean Center Variables</a></li>
<li class="chapter" data-level="21.2.5" data-path="center.html"><a href="center.html#groupmean_center"><i class="fa fa-check"></i><b>21.2.5</b> Group-Mean Center Variables</a></li>
<li class="chapter" data-level="21.2.6" data-path="center.html"><a href="center.html#standardize_center"><i class="fa fa-check"></i><b>21.2.6</b> Standardize Variables</a></li>
<li class="chapter" data-level="21.2.7" data-path="center.html"><a href="center.html#summary_center"><i class="fa fa-check"></i><b>21.2.7</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="removeobjects.html"><a href="removeobjects.html"><i class="fa fa-check"></i><b>22</b> Removing Objects from the R Environment</a>
<ul>
<li class="chapter" data-level="22.1" data-path="removeobjects.html"><a href="removeobjects.html#conceptualoverview_removeobjects"><i class="fa fa-check"></i><b>22.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="22.2" data-path="removeobjects.html"><a href="removeobjects.html#tutorial_removeobjects"><i class="fa fa-check"></i><b>22.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="22.2.1" data-path="removeobjects.html"><a href="removeobjects.html#videotutorial_removeobjects"><i class="fa fa-check"></i><b>22.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="22.2.2" data-path="removeobjects.html"><a href="removeobjects.html#function_removeobjects"><i class="fa fa-check"></i><b>22.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="22.2.3" data-path="removeobjects.html"><a href="removeobjects.html#initsteps_removeobjects"><i class="fa fa-check"></i><b>22.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="22.2.4" data-path="removeobjects.html"><a href="removeobjects.html#listobjects_removeobjects"><i class="fa fa-check"></i><b>22.2.4</b> List Objects in R Environment</a></li>
<li class="chapter" data-level="22.2.5" data-path="removeobjects.html"><a href="removeobjects.html#removeobjects_removeobjects"><i class="fa fa-check"></i><b>22.2.5</b> Remove Objects from R Environment</a></li>
<li class="chapter" data-level="22.2.6" data-path="removeobjects.html"><a href="removeobjects.html#summary_removeobjects"><i class="fa fa-check"></i><b>22.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Employee Demographics</b></span></li>
<li class="chapter" data-level="23" data-path="employeedemographics.html"><a href="employeedemographics.html"><i class="fa fa-check"></i><b>23</b> Introduction to Employee Demographics</a></li>
<li class="chapter" data-level="24" data-path="descriptives.html"><a href="descriptives.html"><i class="fa fa-check"></i><b>24</b> Describing Employee Demographics Using Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="24.1" data-path="descriptives.html"><a href="descriptives.html#conceptualoverview_descriptives"><i class="fa fa-check"></i><b>24.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="24.1.1" data-path="descriptives.html"><a href="descriptives.html#measurementscales"><i class="fa fa-check"></i><b>24.1.1</b> Review of Measurement Scales</a></li>
<li class="chapter" data-level="24.1.2" data-path="descriptives.html"><a href="descriptives.html#constructs_measures_measurementscales"><i class="fa fa-check"></i><b>24.1.2</b> Constructs, Measures, &amp; Measurement Scales</a></li>
<li class="chapter" data-level="24.1.3" data-path="descriptives.html"><a href="descriptives.html#typesof_descriptivestatistics"><i class="fa fa-check"></i><b>24.1.3</b> Types of Descriptive Statistics</a></li>
<li class="chapter" data-level="24.1.4" data-path="descriptives.html"><a href="descriptives.html#samplewriteup_descriptives"><i class="fa fa-check"></i><b>24.1.4</b> Sample Write-Up</a></li>
</ul></li>
<li class="chapter" data-level="24.2" data-path="descriptives.html"><a href="descriptives.html#tutorial_descriptives"><i class="fa fa-check"></i><b>24.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="24.2.1" data-path="descriptives.html"><a href="descriptives.html#videotutorial_descriptives"><i class="fa fa-check"></i><b>24.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="24.2.2" data-path="descriptives.html"><a href="descriptives.html#functions_descriptives"><i class="fa fa-check"></i><b>24.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="24.2.3" data-path="descriptives.html"><a href="descriptives.html#initsteps_descriptives"><i class="fa fa-check"></i><b>24.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="24.2.4" data-path="descriptives.html"><a href="descriptives.html#determine_measurementscale"><i class="fa fa-check"></i><b>24.2.4</b> Determine the Measurement Scale</a></li>
<li class="chapter" data-level="24.2.5" data-path="descriptives.html"><a href="descriptives.html#describe_nominal_ordinal"><i class="fa fa-check"></i><b>24.2.5</b> Describe Nominal &amp; Ordinal (Categorical) Variables</a></li>
<li class="chapter" data-level="24.2.6" data-path="descriptives.html"><a href="descriptives.html#describe_interval_ratio"><i class="fa fa-check"></i><b>24.2.6</b> Describe Interval &amp; Ratio (Continuous) Variables</a></li>
<li class="chapter" data-level="24.2.7" data-path="descriptives.html"><a href="descriptives.html#summary_descriptives"><i class="fa fa-check"></i><b>24.2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="24.3" data-path="descriptives.html"><a href="descriptives.html#descriptives_supplement"><i class="fa fa-check"></i><b>24.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="24.3.1" data-path="descriptives.html"><a href="descriptives.html#descriptives_supplement_functions"><i class="fa fa-check"></i><b>24.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="24.3.2" data-path="descriptives.html"><a href="descriptives.html#descriptives_initsteps_supplement"><i class="fa fa-check"></i><b>24.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="24.3.3" data-path="descriptives.html"><a href="descriptives.html#descriptives_coefficientofvariation_supplement"><i class="fa fa-check"></i><b>24.3.3</b> Compute Coefficient of Variation (CV)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="25" data-path="crosstabs.html"><a href="crosstabs.html"><i class="fa fa-check"></i><b>25</b> Summarizing Two or More Categorical Variables Using Cross-Tabulations</a>
<ul>
<li class="chapter" data-level="25.1" data-path="crosstabs.html"><a href="crosstabs.html#conceptualoverview_crosstabs"><i class="fa fa-check"></i><b>25.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="25.1.1" data-path="crosstabs.html"><a href="crosstabs.html#review_crosstabs"><i class="fa fa-check"></i><b>25.1.1</b> Review of Cross-Tabulation</a></li>
<li class="chapter" data-level="25.1.2" data-path="crosstabs.html"><a href="crosstabs.html#samplewriteup_crosstabs"><i class="fa fa-check"></i><b>25.1.2</b> Sample Write-Up</a></li>
</ul></li>
<li class="chapter" data-level="25.2" data-path="crosstabs.html"><a href="crosstabs.html#tutorial_crosstabs"><i class="fa fa-check"></i><b>25.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="25.2.1" data-path="crosstabs.html"><a href="crosstabs.html#videotutorial_crosstabs"><i class="fa fa-check"></i><b>25.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="25.2.2" data-path="crosstabs.html"><a href="crosstabs.html#functions_crosstabs"><i class="fa fa-check"></i><b>25.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="25.2.3" data-path="crosstabs.html"><a href="crosstabs.html#initsteps_tables"><i class="fa fa-check"></i><b>25.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="25.2.4" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs"><i class="fa fa-check"></i><b>25.2.4</b> Two-Way Cross-Tabulation</a></li>
<li class="chapter" data-level="25.2.5" data-path="crosstabs.html"><a href="crosstabs.html#threeway_crosstabs"><i class="fa fa-check"></i><b>25.2.5</b> Three-Way Cross-Tabulation</a></li>
<li class="chapter" data-level="25.2.6" data-path="crosstabs.html"><a href="crosstabs.html#summary_crosstabs"><i class="fa fa-check"></i><b>25.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="pivottables.html"><a href="pivottables.html"><i class="fa fa-check"></i><b>26</b> Applying Pivot Tables to Explore Employee Demographic Data</a>
<ul>
<li class="chapter" data-level="26.1" data-path="pivottables.html"><a href="pivottables.html#conceptualoverview_pivottables"><i class="fa fa-check"></i><b>26.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="26.2" data-path="pivottables.html"><a href="pivottables.html#tutorial_pivottables"><i class="fa fa-check"></i><b>26.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="26.2.1" data-path="pivottables.html"><a href="pivottables.html#videotutorial_pivottables"><i class="fa fa-check"></i><b>26.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="26.2.2" data-path="pivottables.html"><a href="pivottables.html#functions_pivottables"><i class="fa fa-check"></i><b>26.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="26.2.3" data-path="pivottables.html"><a href="pivottables.html#initsteps_pivottables"><i class="fa fa-check"></i><b>26.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="26.2.4" data-path="pivottables.html"><a href="pivottables.html#create_pivottables"><i class="fa fa-check"></i><b>26.2.4</b> Create a Pivot Table</a></li>
<li class="chapter" data-level="26.2.5" data-path="pivottables.html"><a href="pivottables.html#summary_pivottables"><i class="fa fa-check"></i><b>26.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V Employee Surveys</b></span></li>
<li class="chapter" data-level="27" data-path="employeesurveys.html"><a href="employeesurveys.html"><i class="fa fa-check"></i><b>27</b> Introduction to Employee Surveys</a></li>
<li class="chapter" data-level="28" data-path="aggregatesegment.html"><a href="aggregatesegment.html"><i class="fa fa-check"></i><b>28</b> Aggregating &amp; Segmenting Employee Survey Data</a>
<ul>
<li class="chapter" data-level="28.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#conceptualoverview_aggregatesegment"><i class="fa fa-check"></i><b>28.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="28.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#tutorial_aggregatesegment"><i class="fa fa-check"></i><b>28.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="28.2.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#videotutorial_aggregatesegment"><i class="fa fa-check"></i><b>28.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="28.2.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#functions_aggregatesegment"><i class="fa fa-check"></i><b>28.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="28.2.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#initsteps_aggregatesegment"><i class="fa fa-check"></i><b>28.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="28.2.4" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup"><i class="fa fa-check"></i><b>28.2.4</b> Counts By Group</a></li>
<li class="chapter" data-level="28.2.5" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup"><i class="fa fa-check"></i><b>28.2.5</b> Measures of Central Tendency and Dispersion By Group</a></li>
<li class="chapter" data-level="28.2.6" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable"><i class="fa fa-check"></i><b>28.2.6</b> Add Variable to Data Frame Containing Aggregated Values</a></li>
<li class="chapter" data-level="28.2.7" data-path="aggregatesegment.html"><a href="aggregatesegment.html#visualize_bygroup"><i class="fa fa-check"></i><b>28.2.7</b> Visualize Data By Group</a></li>
<li class="chapter" data-level="28.2.8" data-path="aggregatesegment.html"><a href="aggregatesegment.html#summary_aggregatesegment"><i class="fa fa-check"></i><b>28.2.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="28.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_supplement"><i class="fa fa-check"></i><b>28.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="28.3.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_supplement_functions"><i class="fa fa-check"></i><b>28.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="28.3.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_initsteps_supplement"><i class="fa fa-check"></i><b>28.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="28.3.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_describeby_supplement"><i class="fa fa-check"></i><b>28.3.3</b> <code>describeBy</code> Function from <code>psych</code> Package</a></li>
<li class="chapter" data-level="28.3.4" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_aggregate_supplement"><i class="fa fa-check"></i><b>28.3.4</b> <code>aggregate</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="29" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html"><i class="fa fa-check"></i><b>29</b> Estimating Internal Consistency Reliability Using Cronbach’s alpha</a>
<ul>
<li class="chapter" data-level="29.1" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#conceptualoverview_cronbachsalpha"><i class="fa fa-check"></i><b>29.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="29.2" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#tutorial_cronbachsalpha"><i class="fa fa-check"></i><b>29.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="29.2.1" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#videotutorial_cronbachsalpha"><i class="fa fa-check"></i><b>29.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="29.2.2" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#functions_cronbachsalpha"><i class="fa fa-check"></i><b>29.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="29.2.3" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#initsteps_cronbachsalpha"><i class="fa fa-check"></i><b>29.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="29.2.4" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#cronbachsalpha_alpha"><i class="fa fa-check"></i><b>29.2.4</b> Compute Cronbach’s alpha</a></li>
<li class="chapter" data-level="29.2.5" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#summary_cronbachsalpha"><i class="fa fa-check"></i><b>29.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="30" data-path="compositevariable.html"><a href="compositevariable.html"><i class="fa fa-check"></i><b>30</b> Creating a Composite Variable Based on a Multi-Item Measure</a>
<ul>
<li class="chapter" data-level="30.1" data-path="compositevariable.html"><a href="compositevariable.html#conceptualoverview_compositevariable"><i class="fa fa-check"></i><b>30.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="30.2" data-path="compositevariable.html"><a href="compositevariable.html#tutorial_compositevariable"><i class="fa fa-check"></i><b>30.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="30.2.1" data-path="compositevariable.html"><a href="compositevariable.html#videotutorial_compositevariable"><i class="fa fa-check"></i><b>30.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="30.2.2" data-path="compositevariable.html"><a href="compositevariable.html#functions_compositevariable"><i class="fa fa-check"></i><b>30.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="30.2.3" data-path="compositevariable.html"><a href="compositevariable.html#initsteps_compositevariable"><i class="fa fa-check"></i><b>30.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="30.2.4" data-path="compositevariable.html"><a href="compositevariable.html#compositevariable_cronbachsalpha"><i class="fa fa-check"></i><b>30.2.4</b> Compute Cronbach’s alpha</a></li>
<li class="chapter" data-level="30.2.5" data-path="compositevariable.html"><a href="compositevariable.html#compositevariable_composite"><i class="fa fa-check"></i><b>30.2.5</b> Create a Composite Variable</a></li>
<li class="chapter" data-level="30.2.6" data-path="compositevariable.html"><a href="compositevariable.html#summary_compositevariable"><i class="fa fa-check"></i><b>30.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VI Employee Training</b></span></li>
<li class="chapter" data-level="31" data-path="employeetraining.html"><a href="employeetraining.html"><i class="fa fa-check"></i><b>31</b> Introduction to Employee Training</a>
<ul>
<li class="chapter" data-level="31.1" data-path="employeetraining.html"><a href="employeetraining.html#trainingevaluation_employeetraining"><i class="fa fa-check"></i><b>31.1</b> Training Evaluation</a></li>
</ul></li>
<li class="chapter" data-level="32" data-path="pretestposttest.html"><a href="pretestposttest.html"><i class="fa fa-check"></i><b>32</b> Evaluating a Pre-Test/Post-Test without Control Group Design Using Paired-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="32.1" data-path="pretestposttest.html"><a href="pretestposttest.html#conceptualoverview_pretestposttest_psttest"><i class="fa fa-check"></i><b>32.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="32.1.1" data-path="pretestposttest.html"><a href="pretestposttest.html#review_pretestposttest"><i class="fa fa-check"></i><b>32.1.1</b> Review of Pre-Test/Post-Test without Control Group Design</a></li>
<li class="chapter" data-level="32.1.2" data-path="pretestposttest.html"><a href="pretestposttest.html#review_psttest"><i class="fa fa-check"></i><b>32.1.2</b> Review of Paired-Samples <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="32.2" data-path="pretestposttest.html"><a href="pretestposttest.html#tutorial_psttest"><i class="fa fa-check"></i><b>32.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="32.2.1" data-path="pretestposttest.html"><a href="pretestposttest.html#videotutorial_psttest"><i class="fa fa-check"></i><b>32.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="32.2.2" data-path="pretestposttest.html"><a href="pretestposttest.html#functions_psttest"><i class="fa fa-check"></i><b>32.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="32.2.3" data-path="pretestposttest.html"><a href="pretestposttest.html#initsteps_psttest"><i class="fa fa-check"></i><b>32.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="32.2.4" data-path="pretestposttest.html"><a href="pretestposttest.html#estimate_psttest"><i class="fa fa-check"></i><b>32.2.4</b> Estimate Paired-Samples <em>t</em>-test</a></li>
<li class="chapter" data-level="32.2.5" data-path="pretestposttest.html"><a href="pretestposttest.html#barchart_psttest"><i class="fa fa-check"></i><b>32.2.5</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="32.2.6" data-path="pretestposttest.html"><a href="pretestposttest.html#summary_psttest"><i class="fa fa-check"></i><b>32.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="32.3" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_supplement"><i class="fa fa-check"></i><b>32.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="32.3.1" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_supplement_functions"><i class="fa fa-check"></i><b>32.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="32.3.2" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_initsteps_supplement"><i class="fa fa-check"></i><b>32.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="32.3.3" data-path="pretestposttest.html"><a href="pretestposttest.html#t.test_function_psttest"><i class="fa fa-check"></i><b>32.3.3</b> <code>t.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="33" data-path="posttestonly.html"><a href="posttestonly.html"><i class="fa fa-check"></i><b>33</b> Evaluating a Post-Test-Only with Control Group Design Using Independent-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="33.1" data-path="posttestonly.html"><a href="posttestonly.html#conceptualoverview_posttestonly_isttest"><i class="fa fa-check"></i><b>33.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="33.1.1" data-path="posttestonly.html"><a href="posttestonly.html#review_posttestonly"><i class="fa fa-check"></i><b>33.1.1</b> Review of Post-Test-Only with Control Group Design</a></li>
<li class="chapter" data-level="33.1.2" data-path="posttestonly.html"><a href="posttestonly.html#review_isttest"><i class="fa fa-check"></i><b>33.1.2</b> Review of Independent-Samples <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="33.2" data-path="posttestonly.html"><a href="posttestonly.html#tutorial_isttest"><i class="fa fa-check"></i><b>33.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="33.2.1" data-path="posttestonly.html"><a href="posttestonly.html#videotutorial_isttest"><i class="fa fa-check"></i><b>33.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="33.2.2" data-path="posttestonly.html"><a href="posttestonly.html#functions_isttest"><i class="fa fa-check"></i><b>33.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="33.2.3" data-path="posttestonly.html"><a href="posttestonly.html#initsteps_isttest"><i class="fa fa-check"></i><b>33.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="33.2.4" data-path="posttestonly.html"><a href="posttestonly.html#estimate_isttest"><i class="fa fa-check"></i><b>33.2.4</b> Estimate Independent-Samples <em>t</em>-test</a></li>
<li class="chapter" data-level="33.2.5" data-path="posttestonly.html"><a href="posttestonly.html#barchart_isttest"><i class="fa fa-check"></i><b>33.2.5</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="33.2.6" data-path="posttestonly.html"><a href="posttestonly.html#summary_isttest"><i class="fa fa-check"></i><b>33.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="33.3" data-path="posttestonly.html"><a href="posttestonly.html#isttest_supplement"><i class="fa fa-check"></i><b>33.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="33.3.1" data-path="posttestonly.html"><a href="posttestonly.html#isttest_supplement_functions"><i class="fa fa-check"></i><b>33.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="33.3.2" data-path="posttestonly.html"><a href="posttestonly.html#isttest_initsteps_supplement"><i class="fa fa-check"></i><b>33.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="33.3.3" data-path="posttestonly.html"><a href="posttestonly.html#t.test_function_isttest"><i class="fa fa-check"></i><b>33.3.3</b> <code>t.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="34" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html"><i class="fa fa-check"></i><b>34</b> Evaluating a Post-Test-Only with Two Comparison Groups Design Using One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="34.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#conceptualoverview_posttestonly_threegroups_onewayanova"><i class="fa fa-check"></i><b>34.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="34.1.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#review_posttestonly_threegroups"><i class="fa fa-check"></i><b>34.1.1</b> Review of Post-Test-Only with Two Comparison Groups Design</a></li>
<li class="chapter" data-level="34.1.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#review_onewayanova"><i class="fa fa-check"></i><b>34.1.2</b> Review of One-Way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="34.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#tutorial_onewayanova"><i class="fa fa-check"></i><b>34.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="34.2.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#videotutorial_onewayanova"><i class="fa fa-check"></i><b>34.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="34.2.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#functions_onewayanova"><i class="fa fa-check"></i><b>34.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="34.2.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#initsteps_onewayanova"><i class="fa fa-check"></i><b>34.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="34.2.4" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#teststatisticalassumptions_onewayanova"><i class="fa fa-check"></i><b>34.2.4</b> Test Statistical Assumptions</a></li>
<li class="chapter" data-level="34.2.5" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#estimate_onewayanova"><i class="fa fa-check"></i><b>34.2.5</b> Estimate One-Way ANOVA</a></li>
<li class="chapter" data-level="34.2.6" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#barchart_onewayanova"><i class="fa fa-check"></i><b>34.2.6</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="34.2.7" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#summary_onewayanova"><i class="fa fa-check"></i><b>34.2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="34.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_supplement"><i class="fa fa-check"></i><b>34.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="34.3.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_supplement_functions"><i class="fa fa-check"></i><b>34.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="34.3.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_initsteps_supplement"><i class="fa fa-check"></i><b>34.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="34.3.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#aov_function_onewayanova"><i class="fa fa-check"></i><b>34.3.3</b> <code>aov</code> Function from Base R</a></li>
<li class="chapter" data-level="34.3.4" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#apatable_onewayanova"><i class="fa fa-check"></i><b>34.3.4</b> APA-Style Table of Results</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VII Employee Selection</b></span></li>
<li class="chapter" data-level="35" data-path="selection.html"><a href="selection.html"><i class="fa fa-check"></i><b>35</b> Introduction to Employee Selection</a></li>
<li class="chapter" data-level="36" data-path="disparateimpact.html"><a href="disparateimpact.html"><i class="fa fa-check"></i><b>36</b> Investigating Disparate Impact</a>
<ul>
<li class="chapter" data-level="36.1" data-path="disparateimpact.html"><a href="disparateimpact.html#conceptualoverview_disparateimpact"><i class="fa fa-check"></i><b>36.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="36.2" data-path="disparateimpact.html"><a href="disparateimpact.html#tutorial_disparateimpact"><i class="fa fa-check"></i><b>36.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="36.2.1" data-path="disparateimpact.html"><a href="disparateimpact.html#videotutorial_disparateimpact"><i class="fa fa-check"></i><b>36.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="36.2.2" data-path="disparateimpact.html"><a href="disparateimpact.html#functions_disparateimpact"><i class="fa fa-check"></i><b>36.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="36.2.3" data-path="disparateimpact.html"><a href="disparateimpact.html#initsteps_disparateimpact"><i class="fa fa-check"></i><b>36.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="36.2.4" data-path="disparateimpact.html"><a href="disparateimpact.html#fourfifthsrule"><i class="fa fa-check"></i><b>36.2.4</b> 4/5ths Rule</a></li>
<li class="chapter" data-level="36.2.5" data-path="disparateimpact.html"><a href="disparateimpact.html#chisquaretest_disparateimpact"><i class="fa fa-check"></i><b>36.2.5</b> Chi-Squared (<span class="math inline">\(\chi^2\)</span>) Test of Independence</a></li>
<li class="chapter" data-level="36.2.6" data-path="disparateimpact.html"><a href="disparateimpact.html#fisherexacttest"><i class="fa fa-check"></i><b>36.2.6</b> Fisher Exact Test</a></li>
<li class="chapter" data-level="36.2.7" data-path="disparateimpact.html"><a href="disparateimpact.html#zdifference_test_disparateimpact"><i class="fa fa-check"></i><b>36.2.7</b> <span class="math inline">\(Z_{D}\)</span> Test</a></li>
<li class="chapter" data-level="36.2.8" data-path="disparateimpact.html"><a href="disparateimpact.html#z_impactratiotest"><i class="fa fa-check"></i><b>36.2.8</b> <span class="math inline">\(Z_{IR}\)</span> Test</a></li>
<li class="chapter" data-level="36.2.9" data-path="disparateimpact.html"><a href="disparateimpact.html#summary_disparatetreatment"><i class="fa fa-check"></i><b>36.2.9</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="37" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html"><i class="fa fa-check"></i><b>37</b> Estimating Criterion-Related Validity of a Selection Tool Using Correlation</a>
<ul>
<li class="chapter" data-level="37.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#conceptualoverview_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="37.1.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#review_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.1.1</b> Review of Criterion-Related Validity</a></li>
<li class="chapter" data-level="37.1.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#review_correlation"><i class="fa fa-check"></i><b>37.1.2</b> Review of Correlation</a></li>
</ul></li>
<li class="chapter" data-level="37.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#tutorial_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="37.2.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#videotutorial_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="37.2.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#functions_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="37.2.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#initsteps_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="37.2.4" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#scatterplot_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.2.4</b> Visualize Association Using a Scatter Plot</a></li>
<li class="chapter" data-level="37.2.5" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#estimate_correlation"><i class="fa fa-check"></i><b>37.2.5</b> Estimate Correlation</a></li>
<li class="chapter" data-level="37.2.6" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#summary_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="37.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_supplement"><i class="fa fa-check"></i><b>37.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="37.3.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_supplement_functions"><i class="fa fa-check"></i><b>37.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="37.3.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_initsteps_supplement"><i class="fa fa-check"></i><b>37.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="37.3.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#cor_function"><i class="fa fa-check"></i><b>37.3.3</b> <code>cor</code> Function from Base R</a></li>
<li class="chapter" data-level="37.3.4" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#cortest_function"><i class="fa fa-check"></i><b>37.3.4</b> <code>cor.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="38" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html"><i class="fa fa-check"></i><b>38</b> Predicting Criterion Scores Based on Selection Tool Scores Using Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="38.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#conceptualoverview_predictingcriterionscores"><i class="fa fa-check"></i><b>38.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="38.1.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#review_slr"><i class="fa fa-check"></i><b>38.1.1</b> Review of Simple Linear Regression</a></li>
<li class="chapter" data-level="38.1.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#review_prediction_slr"><i class="fa fa-check"></i><b>38.1.2</b> Predicting Future Criterion Scores Using Simple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="38.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#tutorial_predictingcriterionscores"><i class="fa fa-check"></i><b>38.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="38.2.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#videotutorial_predictingcriterionscores"><i class="fa fa-check"></i><b>38.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="38.2.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#functions_predictingcriterionscores"><i class="fa fa-check"></i><b>38.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="38.2.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#initsteps_slr"><i class="fa fa-check"></i><b>38.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="38.2.4" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#estimate_slr"><i class="fa fa-check"></i><b>38.2.4</b> Estimate Simple Linear Regression Model</a></li>
<li class="chapter" data-level="38.2.5" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_slr"><i class="fa fa-check"></i><b>38.2.5</b> Predict Criterion Scores</a></li>
<li class="chapter" data-level="38.2.6" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#summary_predictingcriterionscores"><i class="fa fa-check"></i><b>38.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="38.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_supplement"><i class="fa fa-check"></i><b>38.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="38.3.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_supplement_functions"><i class="fa fa-check"></i><b>38.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="38.3.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_initsteps_supplement"><i class="fa fa-check"></i><b>38.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="38.3.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#lm_function_slr"><i class="fa fa-check"></i><b>38.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="38.3.4" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predict_function_slr"><i class="fa fa-check"></i><b>38.3.4</b> <code>predict</code> Function from Base R</a></li>
<li class="chapter" data-level="38.3.5" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#apatable_slr"><i class="fa fa-check"></i><b>38.3.5</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="39" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html"><i class="fa fa-check"></i><b>39</b> Estimating Incremental Validity of a Selection Tool Using Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="39.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#conceptualoverview_incrementalvalidity"><i class="fa fa-check"></i><b>39.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="39.1.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#review_mlr"><i class="fa fa-check"></i><b>39.1.1</b> Review of Multiple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="39.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#tutorial_incrementalvalidity"><i class="fa fa-check"></i><b>39.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="39.2.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#videotutorial_incrementalvalidity"><i class="fa fa-check"></i><b>39.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="39.2.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#function_incrementalvalidity"><i class="fa fa-check"></i><b>39.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="39.2.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#initsteps_mlr"><i class="fa fa-check"></i><b>39.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="39.2.4" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#estimate_mlr"><i class="fa fa-check"></i><b>39.2.4</b> Estimate Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="39.2.5" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#summary_incrementalvalidity"><i class="fa fa-check"></i><b>39.2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="39.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_supplement"><i class="fa fa-check"></i><b>39.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="39.3.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_supplement_functions"><i class="fa fa-check"></i><b>39.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="39.3.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_initsteps_supplement"><i class="fa fa-check"></i><b>39.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="39.3.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#lm_function_mlr"><i class="fa fa-check"></i><b>39.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="39.3.4" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#apatable_mlr"><i class="fa fa-check"></i><b>39.3.4</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="40" data-path="compensatory.html"><a href="compensatory.html"><i class="fa fa-check"></i><b>40</b> Applying a Compensatory Approach to Selection Decisions Using Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="40.1" data-path="compensatory.html"><a href="compensatory.html#conceptualoverview_compensatory"><i class="fa fa-check"></i><b>40.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="40.1.1" data-path="compensatory.html"><a href="compensatory.html#review_compensatory_mlr"><i class="fa fa-check"></i><b>40.1.1</b> Review of Multiple Linear Regression</a></li>
<li class="chapter" data-level="40.1.2" data-path="compensatory.html"><a href="compensatory.html#review_compensatory"><i class="fa fa-check"></i><b>40.1.2</b> Review of Compensatory Approach</a></li>
</ul></li>
<li class="chapter" data-level="40.2" data-path="compensatory.html"><a href="compensatory.html#tutorial_compensatory"><i class="fa fa-check"></i><b>40.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="40.2.1" data-path="compensatory.html"><a href="compensatory.html#videotutorial_compensatory"><i class="fa fa-check"></i><b>40.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="40.2.2" data-path="compensatory.html"><a href="compensatory.html#function_compensatory"><i class="fa fa-check"></i><b>40.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="40.2.3" data-path="compensatory.html"><a href="compensatory.html#initsteps_compensatory"><i class="fa fa-check"></i><b>40.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="40.2.4" data-path="compensatory.html"><a href="compensatory.html#estimate_compensatory"><i class="fa fa-check"></i><b>40.2.4</b> Estimate Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="40.2.5" data-path="compensatory.html"><a href="compensatory.html#predictcriterionscores_compensatory"><i class="fa fa-check"></i><b>40.2.5</b> Predict Criterion Scores</a></li>
<li class="chapter" data-level="40.2.6" data-path="compensatory.html"><a href="compensatory.html#summary_compensatory"><i class="fa fa-check"></i><b>40.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="40.3" data-path="compensatory.html"><a href="compensatory.html#compensatory_supplement"><i class="fa fa-check"></i><b>40.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="40.3.1" data-path="compensatory.html"><a href="compensatory.html#compensatory_supplement_functions"><i class="fa fa-check"></i><b>40.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="40.3.2" data-path="compensatory.html"><a href="compensatory.html#compensatory_initsteps_supplement"><i class="fa fa-check"></i><b>40.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="40.3.3" data-path="compensatory.html"><a href="compensatory.html#lm_predict_functions_compensatory"><i class="fa fa-check"></i><b>40.3.3</b> <code>lm</code> &amp; <code>predict</code> Functions from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="41" data-path="multiplecutoff.html"><a href="multiplecutoff.html"><i class="fa fa-check"></i><b>41</b> Applying a Noncompensatory Approach to Selection Decisions Using Angoff Method</a>
<ul>
<li class="chapter" data-level="41.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#conceptualoverview_multiplecutoff"><i class="fa fa-check"></i><b>41.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="41.1.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#review_multiplecutoff"><i class="fa fa-check"></i><b>41.1.1</b> Review of Noncompensatory Approach</a></li>
</ul></li>
<li class="chapter" data-level="41.2" data-path="multiplecutoff.html"><a href="multiplecutoff.html#tutorial_multiplecutoff"><i class="fa fa-check"></i><b>41.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="41.2.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#function_multiplecutoff"><i class="fa fa-check"></i><b>41.2.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="41.2.2" data-path="multiplecutoff.html"><a href="multiplecutoff.html#initsteps_multiplecutoff"><i class="fa fa-check"></i><b>41.2.2</b> Initial Steps</a></li>
<li class="chapter" data-level="41.2.3" data-path="multiplecutoff.html"><a href="multiplecutoff.html#createcutoffscores_multiplecutoff"><i class="fa fa-check"></i><b>41.2.3</b> Create Cutoff Scores</a></li>
<li class="chapter" data-level="41.2.4" data-path="multiplecutoff.html"><a href="multiplecutoff.html#applycutoffscores_multiplecutoff"><i class="fa fa-check"></i><b>41.2.4</b> Apply Cutoff Scores to Make Selection Decisions</a></li>
<li class="chapter" data-level="41.2.5" data-path="multiplecutoff.html"><a href="multiplecutoff.html#summary_multiplecutoff"><i class="fa fa-check"></i><b>41.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="42" data-path="differentialprediction.html"><a href="differentialprediction.html"><i class="fa fa-check"></i><b>42</b> Testing for Differential Prediction Using Moderated Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="42.1" data-path="differentialprediction.html"><a href="differentialprediction.html#conceptualoverview_differentialprediction"><i class="fa fa-check"></i><b>42.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="42.1.1" data-path="differentialprediction.html"><a href="differentialprediction.html#review_mmlr"><i class="fa fa-check"></i><b>42.1.1</b> Review of Moderated Multiple Linear Regression</a></li>
<li class="chapter" data-level="42.1.2" data-path="differentialprediction.html"><a href="differentialprediction.html#review_differentialprediction"><i class="fa fa-check"></i><b>42.1.2</b> Review of Differential Prediction</a></li>
</ul></li>
<li class="chapter" data-level="42.2" data-path="differentialprediction.html"><a href="differentialprediction.html#tutorial_differentialprediction"><i class="fa fa-check"></i><b>42.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="42.2.1" data-path="differentialprediction.html"><a href="differentialprediction.html#videotutorial_differentialprediction"><i class="fa fa-check"></i><b>42.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="42.2.2" data-path="differentialprediction.html"><a href="differentialprediction.html#function_mmlr"><i class="fa fa-check"></i><b>42.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="42.2.3" data-path="differentialprediction.html"><a href="differentialprediction.html#initsteps_mmlr"><i class="fa fa-check"></i><b>42.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="42.2.4" data-path="differentialprediction.html"><a href="differentialprediction.html#center_mmlr"><i class="fa fa-check"></i><b>42.2.4</b> Grand-Mean Center Continuous Predictor Variables</a></li>
<li class="chapter" data-level="42.2.5" data-path="differentialprediction.html"><a href="differentialprediction.html#estimate_mmlr"><i class="fa fa-check"></i><b>42.2.5</b> Estimate Moderated Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="42.2.6" data-path="differentialprediction.html"><a href="differentialprediction.html#summary_differentialprediction"><i class="fa fa-check"></i><b>42.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="42.3" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_supplement"><i class="fa fa-check"></i><b>42.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="42.3.1" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_supplement_functions"><i class="fa fa-check"></i><b>42.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="42.3.2" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_initsteps_supplement"><i class="fa fa-check"></i><b>42.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="42.3.3" data-path="differentialprediction.html"><a href="differentialprediction.html#lm_function_mmlr"><i class="fa fa-check"></i><b>42.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="42.3.4" data-path="differentialprediction.html"><a href="differentialprediction.html#apatable_mmlr"><i class="fa fa-check"></i><b>42.3.4</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VIII Odds &amp; Ends</b></span></li>
<li class="chapter" data-level="43" data-path="create-portfolio.html"><a href="create-portfolio.html"><i class="fa fa-check"></i><b>43</b> Creating a Data Analytics Portfolio</a></li>
<li class="chapter" data-level="44" data-path="literature-search-review.html"><a href="literature-search-review.html"><i class="fa fa-check"></i><b>44</b> Conducting a Literature Search &amp; Review</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for HR:<br />
<em>An Introduction to Human Resource Analytics Using R</em><br />
BOOK UNDER CONSTRUCTION</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="join" class="section level1" number="17">
<h1><span class="header-section-number">Chapter 17</span> Joining (Merging) Data</h1>
<p>In this chapter, we will learn the fundamentals of joins (merges). Specifically, we will learn how to join (merge) data horizontally and vertically.</p>
<div id="conceptualoverview_join" class="section level2" number="17.1">
<h2><span class="header-section-number">17.1</span> Conceptual Overview</h2>
<p><strong>Joining</strong> (<strong>merging</strong>) refers to the process of matching two data frames by either one or more key variables (i.e., horizontal join) or by variable names or columns (i.e., vertical join). Sometimes a <strong>join</strong> is referred to as a <strong>merge</strong> and vice versa, and thus I will use these terms interchangeably throughout the chapter. Broadly speaking, there are two types of joins (merges): horizontal and vertical.</p>
<div id="review_horizontaljoin" class="section level3" number="17.1.1">
<h3><span class="header-section-number">17.1.1</span> Review of Horizontal Joins (Merges)</h3>
<p>A <strong>horizontal join (merge)</strong> refers to the process of matching cases (i.e., rows, observations) between two data frames using a <em>key variable</em> (<em>matching variable</em>), which results in distinct sets of variables (i.e., fields, columns) being combined horizontally (laterally) across two data frames. The resulting joined data frame will be wider (in terms of the number of variables) than either of the original data frames in isolation. For example, imagine that we pull data from separate information systems, each with different variables (i.e., fields) but at least some employees (i.e., cases) in common; to combine these two data frames, we can perform a horizontal join. This is often a necessary step when creating a data frame that contains all of the variables we will need in subsequent data analyses. For instance, if we wish to estimate the criterion-related validities using the selection tool scores from one data frame with criterion (e.g., job performance) scores from another data frame, then we could perform a horizontal join, assuming we have a key variable with which to match the scores from the two data frames.</p>
<div class="figure">
<img src="horizontal_join.png" alt="" />
<p class="caption">In a <em>horizontal join</em>, cases (or observations) are matched between two data frames using one or more key variables.</p>
</div>
<p>We will focus on four different types of horizontal joins:</p>
<ol style="list-style-type: decimal">
<li><strong>Inner join</strong>: All unmatched cases (or observations) are dropped, thereby retaining only those cases that are present in both the left (x, first) and right (y, second) data frames. In other words, a case is only included in the merged data frame if it appears in both of the original data data frames.</li>
</ol>
<div class="figure">
<img src="inner_join.png" alt="" />
<p class="caption">In an <em>inner join</em>, all unmatched cases (or observations) are dropped, thereby retaining only those cases that are present in both the left (x, first) and right (y, second) data frames.</p>
</div>
<ol start="2" style="list-style-type: decimal">
<li><strong>Full join</strong>: All cases (or observations) are retained, including those cases that do not have a match in the other data data frame. In other words, a case is included in the merged data frame even if it only appears in one of the original data data frames. These type of join leads to the highest number of retained cases under conditions in which both data frames contain unique cases.</li>
</ol>
<div class="figure">
<img src="full_join.png" alt="" />
<p class="caption">In a <em>full join</em>, all cases (or observations) are retained, including those cases that do not have a match in the other data data frame.</p>
</div>
<ol start="3" style="list-style-type: decimal">
<li><strong>Left join</strong>: All cases (or observations) that appear in the left (x, first) data frame are retained, even if they lack a match in the right (y, second) data frame. Consequently, cases from the right data frame that lack a match in the left data frame are dropped in the merged data frame.</li>
</ol>
<div class="figure">
<img src="left_join.png" alt="" />
<p class="caption">In a <em>left join</em>, all cases (or observations) that appear in the left (x, first) data frame are retained, even if they lack a match in the right (y, second) data frame.</p>
</div>
<ol start="4" style="list-style-type: decimal">
<li><strong>Right join</strong>: All cases (or observations) that appear in the right (y, second) data frame are retained, even if they lack a match in the left (x, first) data frame. Consequently, cases from the left data frame that lack a match in the right data frame are dropped in the merged data frame.</li>
</ol>
<div class="figure">
<img src="right_join.png" alt="" />
<p class="caption">In a <em>left join</em>, only cases (or observations) that appear in the left (x, first) data frame are retained, even if they lack a match in the right (y, second) data frame.</p>
</div>
<p>Please note that I have illustrated different types of horizontal joins using a single key variable. It is entirely possible to perform horizontal joins using two or more key variables. For example, imagine that each morning we administered a pulse survey to employees and each afternoon we afternoon we administered a different pulse survey to the same employees, and that we repeated this process for five consecutive workdays. In this instance, we would likely need to horizontally join the data frames using both a unique employee identifier variable and a unique day-of-week variable.</p>
</div>
<div id="review_verticaljoin" class="section level3" number="17.1.2">
<h3><span class="header-section-number">17.1.2</span> Review of Vertical Joins (Merges)</h3>
<p>A <strong>vertical join (merge)</strong> refers to the process of matching identical variables from two data frames, which results in distinct sets of cases or observations being combined vertically. The resulting joined data frame will be longer (in terms of the number of cases) than either of the original data frames in isolation. For example, imagine an organization administered the same survey to two facilities (i.e., independent groups) each with unique employees; we could combine the two resulting data frames by performing a vertical join.</p>
<div class="figure">
<img src="vertical_join.png" alt="" />
<p class="caption">In a <em>vertical join</em>, identical variables are matched between two data frames, each with distinct sets of cases or observations.</p>
</div>
</div>
</div>
<div id="tutorial_join" class="section level2" number="17.2">
<h2><span class="header-section-number">17.2</span> Tutorial</h2>
<p>This chapter’s tutorial demonstrates how to join (merge) cases from two data frames.</p>
<div id="videotutorial_join" class="section level3" number="17.2.1">
<h3><span class="header-section-number">17.2.1</span> Video Tutorial</h3>
<p>As usual, you have the choice to follow along with the written tutorial in this chapter or to watch the video tutorial below. Both versions of the tutorial will show you how to join (merge) data with or without the pipe (<code>%&gt;%</code>) operator. If you’re unfamiliar with the pipe operator, no need to worry: I provide a brief explanation and demonstration regarding their purpose in both versions of the tutorial. Finally, please note that in the <a href="join.html#join_mergefunction">chapter supplement</a> you have an opportunity to learn how to join (merge) cases from data frames using a function from base R, which you may find preferable or more intuitive.</p>
<iframe src="https://youtube.com/embed/38zsLj-fWo0?rel=0" width="672" height="400px">
</iframe>
<p>Link to video tutorial: <a href="https://youtu.be/38zsLj-fWo0" class="uri">https://youtu.be/38zsLj-fWo0</a></p>
</div>
<div id="functions-packages-introduced" class="section level3" number="17.2.2">
<h3><span class="header-section-number">17.2.2</span> Functions &amp; Packages Introduced</h3>
<table>
<thead>
<tr class="header">
<th>Function</th>
<th>Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>merge</code></td>
<td>base R</td>
</tr>
<tr class="even">
<td><code>right_join</code></td>
<td><code>dplyr</code></td>
</tr>
<tr class="odd">
<td><code>left_join</code></td>
<td><code>dplyr</code></td>
</tr>
<tr class="even">
<td><code>inner_join</code></td>
<td><code>dplyr</code></td>
</tr>
<tr class="odd">
<td><code>full_join</code></td>
<td><code>dplyr</code></td>
</tr>
<tr class="even">
<td><code>data.frame</code></td>
<td>base R</td>
</tr>
<tr class="odd">
<td><code>c</code></td>
<td>base R</td>
</tr>
<tr class="even">
<td><code>rep</code></td>
<td>base R</td>
</tr>
<tr class="odd">
<td><code>rbind</code></td>
<td>base R</td>
</tr>
</tbody>
</table>
</div>
<div id="initsteps_join" class="section level3" number="17.2.3">
<h3><span class="header-section-number">17.2.3</span> Initial Steps</h3>
<p>If you haven’t already, save the files called <strong>“PersData.csv”</strong> and <strong>“PerfData.csv”</strong> into a folder that you will subsequently set as your working directory. Your working directory will likely be different than the one shown below (i.e., <code>"H:/RWorkshop"</code>). As a reminder, you can access all of the data files referenced in this book by downloading them as a compressed (zipped) folder from the my GitHub site: <a href="https://github.com/davidcaughlin/R-Tutorial-Data-Files" class="uri">https://github.com/davidcaughlin/R-Tutorial-Data-Files</a>; once you’ve followed the link to GitHub, just click “Code” (or “Download”) followed by “Download ZIP”, which will download all of the data files referenced in this book. For the sake of parsimony, I recommend downloading all of the data files into the same folder on your computer, which will allow you to set that same folder as your working directory for each of the chapters in this book.</p>
<p>Next, using the <code>setwd</code> function, set your working directory to the folder in which you saved the data files for this chapter. Alternatively, you can manually set your working directory folder in your drop-down menus by going to <em>Session &gt; Set Working Directory &gt; Choose Directory…</em>. Be sure to create a new R script file (.R) or update an existing R script file so that you can save your script and annotations. If you need refreshers on how to set your working directory and how to create and save an R script, please refer to <a href="setwd.html#setwd">Setting a Working Directory</a> and <a href="gettingstarted.html#createRscript">Creating &amp; Saving an R Script</a>.</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="join.html#cb283-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your working directory</span></span>
<span id="cb283-2"><a href="join.html#cb283-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;H:/RWorkshop&quot;</span>)</span></code></pre></div>
<p>Next, read in the .csv data files called <strong>“PersData.csv”</strong> and <strong>“PerfData.csv”</strong> using your choice of read function. In this example, I use the <code>read_csv</code> function from the <code>readr</code> package <span class="citation">(<a href="references.html#ref-R-readr" role="doc-biblioref">Wickham and Hester 2020</a>)</span>. If you choose to use the <code>read_csv</code> function, be sure that you have installed and accessed the <code>readr</code> package using the <code>install.packages</code> and <code>library</code> functions. <em>Note: You don’t need to install a package every time you wish to access it; in general, I would recommend updating a package installation once ever 1-3 months.</em> For refreshers on installing packages and reading data into R, please refer to <a href="gentleintro.html#packages">Packages</a> and <a href="read.html#read">Reading Data into R</a>.</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="join.html#cb284-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install readr package if you haven&#39;t already</span></span>
<span id="cb284-2"><a href="join.html#cb284-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Note: You don&#39;t need to install a package every </span></span>
<span id="cb284-3"><a href="join.html#cb284-3" aria-hidden="true" tabindex="-1"></a><span class="co"># time you wish to access it]</span></span>
<span id="cb284-4"><a href="join.html#cb284-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;readr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="join.html#cb285-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access readr package</span></span>
<span id="cb285-2"><a href="join.html#cb285-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb285-3"><a href="join.html#cb285-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb285-4"><a href="join.html#cb285-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data and name data frame (tibble) objects</span></span>
<span id="cb285-5"><a href="join.html#cb285-5" aria-hidden="true" tabindex="-1"></a>personaldata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;PersData.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification ---------------------------------------------------------------------------------------------------
## cols(
##   id = col_double(),
##   lastname = col_character(),
##   firstname = col_character(),
##   startdate = col_character(),
##   gender = col_character()
## )</code></pre>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="join.html#cb287-1" aria-hidden="true" tabindex="-1"></a>performancedata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;PerfData.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification ---------------------------------------------------------------------------------------------------
## cols(
##   id = col_double(),
##   perf_q1 = col_double(),
##   perf_q2 = col_double(),
##   perf_q3 = col_double(),
##   perf_q4 = col_double()
## )</code></pre>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="join.html#cb289-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the names of the variables in the data frame (tibble) objects</span></span>
<span id="cb289-2"><a href="join.html#cb289-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(personaldata)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;        &quot;lastname&quot;  &quot;firstname&quot; &quot;startdate&quot; &quot;gender&quot;</code></pre>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="join.html#cb291-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(performancedata)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;      &quot;perf_q1&quot; &quot;perf_q2&quot; &quot;perf_q3&quot; &quot;perf_q4&quot;</code></pre>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="join.html#cb293-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print data frame (tibble) objects</span></span>
<span id="cb293-2"><a href="join.html#cb293-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(personaldata)</span></code></pre></div>
<pre><code>## # A tibble: 9 x 5
##      id lastname   firstname startdate gender
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt; 
## 1   153 Sanchez    Alejandro 1/1/2016  male  
## 2   154 McDonald   Ronald    1/9/2016  male  
## 3   155 Smith      John      1/9/2016  male  
## 4   165 Doe        Jane      1/4/2016  female
## 5   125 Franklin   Benjamin  1/5/2016  male  
## 6   111 Newton     Isaac     1/9/2016  male  
## 7   198 Morales    Linda     1/7/2016  female
## 8   201 Providence Cindy     1/9/2016  female
## 9   282 Legend     John      1/9/2016  male</code></pre>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="join.html#cb295-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(performancedata)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##      id perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   153     3.9     4.8     4.9     5  
## 2   125     2.1     1.9     2.1     2.3
## 3   111     3.3     3.3     3.4     3.3
## 4   198     4.9     4.5     4.4     4.8
## 5   201     1.2     1.1     1       1  
## 6   282     2.2     2.3     2.4     2.5</code></pre>
<p>As you can see from the output generated in your Console, on the one hand, the <code>personaldata</code> data frame object contains basic employee demographic information. The variable names include: <code>id</code>, <code>lastname</code>, <code>firstname</code>, <code>startdate</code>, and <code>gender</code>. On the other hand, the <code>performancedata</code> data frame object contains the same <code>id</code> unique identifier variable as the <code>personaldata</code> data frame object, but instead of employee demographic information, this data frame object includes variables associated with quarterly employee performance: <code>perf_q1</code>, <code>perf_q2</code>, <code>perf_q3</code>, and <code>perf_q4</code>.</p>
<p>In order to better illustrate certain join functions later on in this chapter, we’ll begin by removing the case (i.e., employee) associated with the <code>id</code> variable value of 153 (i.e., Alejandro Sanchez); in terms of a rationale for doing so, let’s imagine that Alejandro no longer works for the organization, and thus we would like to remove him from the <code>personaldata</code> data frame. If you don’t completely understand the following process for removing this individual from the data frame, no need to worry, as you will learn more in the subsequent chapter on <a href="filter.html#filter">filtering data</a>.</p>
<ol style="list-style-type: decimal">
<li>Type the name of the data frame object (<code>personaldata</code>) followed by the <code>&lt;-</code> operator to overwrite the existing data frame object.</li>
<li>Type the name of the original data frame object (<code>personaldata</code>) followed by brackets (<code>[ ]</code>).</li>
<li>Within the brackets (<code>[ ]</code>), type the name of the data frame object (<code>personaldata</code>) again, followed by the <code>$</code> operator and the name of the variable we wish to use to select the case that will be removed, which in this instance is the <code>id</code> unique identifier variable. The <code>$</code> operator indicates to R that the <code>id</code> variable belongs to the <code>personaldata</code> data frame.</li>
<li>Type the “not equal to” operator, which is <code>!=</code> (the <code>!</code> means “not”), followed by the <code>id</code> variable value we wish to use to remove the case (i.e., 153).</li>
<li>Type a comma (<code>,</code>) to indicate that we are removing a row, not a column. <em>When referencing rows and columns in R, as we are doing in the brackets (<code>[ ]</code>), rows are entered first (before a comma), and columns are entered second (after a comma).</em> In doing so, we are telling R to retain all rows of data in <code>personaldata</code> except for the one corresponding to <code>id</code> equal to 153.</li>
</ol>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="join.html#cb297-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove case with id variable equal to 153</span></span>
<span id="cb297-2"><a href="join.html#cb297-2" aria-hidden="true" tabindex="-1"></a>personaldata <span class="ot">&lt;-</span> personaldata[personaldata<span class="sc">$</span>id <span class="sc">!=</span> <span class="dv">153</span>,]</span></code></pre></div>
<p>Check out the first 6 rows of the updated data frame for <code>personaldata</code>, and note that the data corresponding to the case associated with <code>id</code> equal to 153 is gone.</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="join.html#cb298-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print first 6 rows of first data frame object once more</span></span>
<span id="cb298-2"><a href="join.html#cb298-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(personaldata)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##      id lastname firstname startdate gender
##   &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt; 
## 1   154 McDonald Ronald    1/9/2016  male  
## 2   155 Smith    John      1/9/2016  male  
## 3   165 Doe      Jane      1/4/2016  female
## 4   125 Franklin Benjamin  1/5/2016  male  
## 5   111 Newton   Isaac     1/9/2016  male  
## 6   198 Morales  Linda     1/7/2016  female</code></pre>
</div>
<div id="horizontaljoin" class="section level3" number="17.2.4">
<h3><span class="header-section-number">17.2.4</span> Horizontal Join (Merge)</h3>
<p>Recall that a horizontal join (merge) means that cases are matched using one more more key variables, and as a result, variables (i.e., columns, fields) are combined across two data frames. We will review two options for performing horizontal joins.</p>
<p>To perform horizontal joins, we will learn how to use the <code>join</code> functions from the the <code>dplyr</code> package <span class="citation">(<a href="references.html#ref-R-dplyr" role="doc-biblioref">Wickham et al. 2021</a>)</span>, which include: <code>right_join</code>, <code>left_join</code>, <code>inner_join</code>, and <code>full_join</code>. Please note that there are other functions we could use to perform horizontal joins, and if you’re interested, in the <a href="join.html#join_supplement">Joining (Merging) Data: Chapter Supplement</a>, I demonstrate how to use the <code>merge</code> function from base R to carry out the same operations we will cover below.</p>
<p>Using the aforementioned <code>join</code> functions, we will match cases from the <code>personaldata</code> and <code>performancedata</code> data frames using the <code>id</code> unique identifier variable as a key variable. So how can we verify that <code>id</code> is an appropriate key variable? Well, let’s use the <code>names</code> function from base R to retrieve the list of variable names from the two data frames, which we already did above. Nevertheless, let’s call up those variable names once more. Simply enter the name of the data frame as a parenthetical argument in the <code>names</code> function.</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="join.html#cb300-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Retrieve variable names from first data frame</span></span>
<span id="cb300-2"><a href="join.html#cb300-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(personaldata)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;        &quot;lastname&quot;  &quot;firstname&quot; &quot;startdate&quot; &quot;gender&quot;</code></pre>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="join.html#cb302-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Retrieve variable names from second data frame</span></span>
<span id="cb302-2"><a href="join.html#cb302-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(performancedata)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;      &quot;perf_q1&quot; &quot;perf_q2&quot; &quot;perf_q3&quot; &quot;perf_q4&quot;</code></pre>
<p>As you can see in the variable names listed above, the <code>id</code> variable is common to both data frames, and thus it will serve as our key variable.</p>
<p>Now we are almost ready to begin joining the two data frames using the <code>id</code> unique identifier as a key variable. Before doing so, however, we should make sure that we have installed and accessed the <code>dplyr</code> package (if we haven’t already), as the <code>join</code> functions come from that package.</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="join.html#cb304-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install dplyr package if you haven&#39;t already</span></span>
<span id="cb304-2"><a href="join.html#cb304-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Note: You don&#39;t need to install a package every </span></span>
<span id="cb304-3"><a href="join.html#cb304-3" aria-hidden="true" tabindex="-1"></a><span class="co"># time you wish to access it]</span></span>
<span id="cb304-4"><a href="join.html#cb304-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;dplyr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="join.html#cb305-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access dplyr package</span></span>
<span id="cb305-2"><a href="join.html#cb305-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<p>I will demonstrate two techniques for applying the <code>join</code> function.</p>
<p>The <em>first technique</em> uses the pipe operator (<code>%&gt;%</code>). The pipe operator comes from a package called <code>magrittr</code> <span class="citation">(<a href="references.html#ref-R-magrittr" role="doc-biblioref">Bache and Wickham 2020</a>)</span>, on which the <code>dplyr</code> is partially dependent. In short, a pipe allows a person to more efficiently write code and to improve the readability of the code and overall script. Specifically, a <strong>pipe</strong> forwards the result or value of one object or expression to a subsequent function. In doing so, one can avoid writing functions in which other functions are nested parenthetically. For more information on the pipe operator, check out Wickham and Grolemund’s <span class="citation">(<a href="references.html#ref-wickham2017" role="doc-biblioref">2017</a>)</span> chapter on pipes: <a href="https://r4ds.had.co.nz/pipes.html" class="uri">https://r4ds.had.co.nz/pipes.html</a>.</p>
<p>The <em>second technique</em> for applying the <code>join</code> function takes a more traditional approach in that it involves nested functions being nested parenthetically. If you don’t want to learn how to use pipes (or would like to learn how to use them at a later date), feel free to skip to the section below called <a href="join.html#opt2_join_withoutpipe">Without Pipe</a>.</p>
<div id="opt2_join_withpipe" class="section level4" number="17.2.4.1">
<h4><span class="header-section-number">17.2.4.1</span> <em>With</em> Pipe</h4>
<p>Using the pipe (<code>%&gt;%</code>) operator technique, let’s begin with what is referred to as an <strong>inner join</strong> by doing the following:</p>
<ol style="list-style-type: decimal">
<li>Use the <code>&lt;-</code> operator to name the joined (merged) data frame that we will create using the one of the <code>dplyr</code> join functions. For this example, I name the new joined data frame <code>mergeddf</code>, which is completely arbitrary; you could name it whatever you would like. Make sure you put the name of the new data frame object to the <em>left</em> of the <code>&lt;-</code> operator.</li>
<li>To the <em>right</em> of the <code>&lt;-</code> operator, type the name of the first data frame, which we named <code>personaldata</code>, followed by the pipe (<code>%&gt;%</code>) operator. This will “pipe” our data frame into the subsequent function.</li>
<li>On the same line or on the next line, type the <code>inner_join</code> function, and within the parentheses as the first argument, type the name of the second data frame, which we called <code>performancedata</code>. As the second argument, use the <code>by=</code> argument to indicate the name of the key variable, which in this example is <code>id</code>; make sure the key variable is in quotation marks (<code>" "</code>), and remember, object and variable names in R are case and space sensitive.</li>
</ol>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="join.html#cb306-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inner join (with pipe)</span></span>
<span id="cb306-2"><a href="join.html#cb306-2" aria-hidden="true" tabindex="-1"></a>mergeddf <span class="ot">&lt;-</span> personaldata <span class="sc">%&gt;%</span> <span class="fu">inner_join</span>(performancedata, <span class="at">by=</span><span class="st">&quot;id&quot;</span>)</span>
<span id="cb306-3"><a href="join.html#cb306-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb306-4"><a href="join.html#cb306-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the joined data frame</span></span>
<span id="cb306-5"><a href="join.html#cb306-5" aria-hidden="true" tabindex="-1"></a>mergeddf</span></code></pre></div>
<pre><code>## # A tibble: 5 x 9
##      id lastname   firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   125 Franklin   Benjamin  1/5/2016  male       2.1     1.9     2.1     2.3
## 2   111 Newton     Isaac     1/9/2016  male       3.3     3.3     3.4     3.3
## 3   198 Morales    Linda     1/7/2016  female     4.9     4.5     4.4     4.8
## 4   201 Providence Cindy     1/9/2016  female     1.2     1.1     1       1  
## 5   282 Legend     John      1/9/2016  male       2.2     2.3     2.4     2.5</code></pre>
<p>Now, let’s revisit the original data frame objects that we read in initially.</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="join.html#cb308-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the first original data frame</span></span>
<span id="cb308-2"><a href="join.html#cb308-2" aria-hidden="true" tabindex="-1"></a>personaldata</span></code></pre></div>
<pre><code>## # A tibble: 8 x 5
##      id lastname   firstname startdate gender
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt; 
## 1   154 McDonald   Ronald    1/9/2016  male  
## 2   155 Smith      John      1/9/2016  male  
## 3   165 Doe        Jane      1/4/2016  female
## 4   125 Franklin   Benjamin  1/5/2016  male  
## 5   111 Newton     Isaac     1/9/2016  male  
## 6   198 Morales    Linda     1/7/2016  female
## 7   201 Providence Cindy     1/9/2016  female
## 8   282 Legend     John      1/9/2016  male</code></pre>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="join.html#cb310-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the second original data frame</span></span>
<span id="cb310-2"><a href="join.html#cb310-2" aria-hidden="true" tabindex="-1"></a>performancedata</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##      id perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   153     3.9     4.8     4.9     5  
## 2   125     2.1     1.9     2.1     2.3
## 3   111     3.3     3.3     3.4     3.3
## 4   198     4.9     4.5     4.4     4.8
## 5   201     1.2     1.1     1       1  
## 6   282     2.2     2.3     2.4     2.5</code></pre>
<p>In the output, first, note how all of the variables from the original data frames (i.e., <code>personaldata</code>, <code>performancedata</code>) are represented in the merged data frame (i.e., <code>mergeddf</code>). Second, note how the cases are matched by the <code>id</code> key variable. Third, note that the <code>personaldata</code> data frame has 8 cases, the <code>performancedata</code> data frame has 6 cases, and the <code>mergeddf</code> data frame has 6 cases. By default, the <code>merge</code> function performs an <em>inner join</em> and retains only those matched cases that have data in <em>both</em> data frames. Because cases whose <code>id</code> values were <code>154</code>, <code>155</code>, and <code>165</code> had data in <code>personaldata</code> but not <code>performancedata</code> and because the case with an <code>id</code> value equal to 153 was in <code>performancedata</code> but not <code>personaldata</code>, only the 5 cases that had available data in both data frames were retained.</p>
<p>To perform what is referred to as a <strong>full join</strong> in which we retain all cases and available data, we simply swap out the <code>inner_join</code> function from our previous code with the <code>full_join</code> function.</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="join.html#cb312-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Full join (with pipe)</span></span>
<span id="cb312-2"><a href="join.html#cb312-2" aria-hidden="true" tabindex="-1"></a>mergeddf <span class="ot">&lt;-</span> personaldata <span class="sc">%&gt;%</span> <span class="fu">full_join</span>(performancedata, <span class="at">by=</span><span class="st">&quot;id&quot;</span>)</span>
<span id="cb312-3"><a href="join.html#cb312-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb312-4"><a href="join.html#cb312-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the joined data frame</span></span>
<span id="cb312-5"><a href="join.html#cb312-5" aria-hidden="true" tabindex="-1"></a>mergeddf</span></code></pre></div>
<pre><code>## # A tibble: 9 x 9
##      id lastname   firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   154 McDonald   Ronald    1/9/2016  male      NA      NA      NA      NA  
## 2   155 Smith      John      1/9/2016  male      NA      NA      NA      NA  
## 3   165 Doe        Jane      1/4/2016  female    NA      NA      NA      NA  
## 4   125 Franklin   Benjamin  1/5/2016  male       2.1     1.9     2.1     2.3
## 5   111 Newton     Isaac     1/9/2016  male       3.3     3.3     3.4     3.3
## 6   198 Morales    Linda     1/7/2016  female     4.9     4.5     4.4     4.8
## 7   201 Providence Cindy     1/9/2016  female     1.2     1.1     1       1  
## 8   282 Legend     John      1/9/2016  male       2.2     2.3     2.4     2.5
## 9   153 &lt;NA&gt;       &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;       3.9     4.8     4.9     5</code></pre>
<p>Note how the <code>full_join</code> function retains all available cases that had available data in at least one of the data frames, which in this example is 9 cases. <em>When in doubt, I recommend using the <code>full_join</code> function to retain all available data.</em></p>
<p>To perform what is referred to as a <strong>left join</strong> in which we retain only those cases with data available in the first (left, x) data frame (<code>personaldata</code>), we use the <code>left_join</code> function instead, while keeping the rest of the previous code the same.</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="join.html#cb314-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Left join (with pipe)</span></span>
<span id="cb314-2"><a href="join.html#cb314-2" aria-hidden="true" tabindex="-1"></a>mergeddf <span class="ot">&lt;-</span> personaldata <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(performancedata, <span class="at">by=</span><span class="st">&quot;id&quot;</span>)</span>
<span id="cb314-3"><a href="join.html#cb314-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb314-4"><a href="join.html#cb314-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the joined data frame</span></span>
<span id="cb314-5"><a href="join.html#cb314-5" aria-hidden="true" tabindex="-1"></a>mergeddf</span></code></pre></div>
<pre><code>## # A tibble: 8 x 9
##      id lastname   firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   154 McDonald   Ronald    1/9/2016  male      NA      NA      NA      NA  
## 2   155 Smith      John      1/9/2016  male      NA      NA      NA      NA  
## 3   165 Doe        Jane      1/4/2016  female    NA      NA      NA      NA  
## 4   125 Franklin   Benjamin  1/5/2016  male       2.1     1.9     2.1     2.3
## 5   111 Newton     Isaac     1/9/2016  male       3.3     3.3     3.4     3.3
## 6   198 Morales    Linda     1/7/2016  female     4.9     4.5     4.4     4.8
## 7   201 Providence Cindy     1/9/2016  female     1.2     1.1     1       1  
## 8   282 Legend     John      1/9/2016  male       2.2     2.3     2.4     2.5</code></pre>
<p>Note how the <code>left_join</code> function retains only those cases for which the first (left, x) data frame (i.e., <code>personaldata</code>) has complete data, which in this case happens to be 8 cases. Notably absent is the case associated with <code>id</code> equal to 153 because the first (left, x) data frame (i.e., <code>personaldata</code>) lacked that case. An <code>NA</code> appears for each case from the second (right, y) data frame that contained missing values on variables from that data frame.</p>
<p>To perform what is referred to as a <strong>right join</strong> in which we retain only those cases with data available in the second (right, y) data frame (<code>performancedata</code>), we will use the <code>right_join</code> function instead, while keeping the rest of the previous code the same.</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="join.html#cb316-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Right join (with pipe)</span></span>
<span id="cb316-2"><a href="join.html#cb316-2" aria-hidden="true" tabindex="-1"></a>mergeddf <span class="ot">&lt;-</span> personaldata <span class="sc">%&gt;%</span> <span class="fu">right_join</span>(performancedata, <span class="at">by=</span><span class="st">&quot;id&quot;</span>)</span>
<span id="cb316-3"><a href="join.html#cb316-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb316-4"><a href="join.html#cb316-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the joined data frame</span></span>
<span id="cb316-5"><a href="join.html#cb316-5" aria-hidden="true" tabindex="-1"></a>mergeddf</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##      id lastname   firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   125 Franklin   Benjamin  1/5/2016  male       2.1     1.9     2.1     2.3
## 2   111 Newton     Isaac     1/9/2016  male       3.3     3.3     3.4     3.3
## 3   198 Morales    Linda     1/7/2016  female     4.9     4.5     4.4     4.8
## 4   201 Providence Cindy     1/9/2016  female     1.2     1.1     1       1  
## 5   282 Legend     John      1/9/2016  male       2.2     2.3     2.4     2.5
## 6   153 &lt;NA&gt;       &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;       3.9     4.8     4.9     5</code></pre>
<p>Note how the <code>right_join</code> function retains only those cases for which the joined (second, right, y) data frame (i.e., <code>performancedata</code>) has complete data. Because the first (left, x) data frame lacks data for the case in which <code>id</code> is equal to 153, an <code>NA</code> appears for each case from the first data frame that contained missing values on variables from that data frame.</p>
</div>
<div id="opt2_join_withoutpipe" class="section level4" number="17.2.4.2">
<h4><span class="header-section-number">17.2.4.2</span> <em>Without</em> Pipe</h4>
<p>In this section, I demonstrate the same <code>dplyr</code> join functions <a href="join.html#opt2_join_withpipe">as above</a>, except here I demonstrate how to specify the functions <em>without</em> the use of a pipe (<code>%&gt;%</code>) operator.</p>
<p>Let’s begin with what is referred to as an <strong>inner join</strong> by doing the following:</p>
<ol style="list-style-type: decimal">
<li>Use the <code>&lt;-</code> operator to name the joined (merged) data frame that we will create using the one of the <code>dplyr</code> join functions. For this example, I name the new joined data frame <code>mergeddf</code>, which is completely arbitrary; you could name it whatever you would like. Make sure you put the name of the new data frame object to the <em>left</em> of the <code>&lt;-</code> operator.</li>
<li>To the <em>right</em> of the <code>&lt;-</code> operator, type the name of the <code>inner_join</code> function. As the first argument within the parentheses, type the name of the first data frame, which we named <code>personaldata</code>. As the second argument, type the name of the second data frame we named <code>performancedata</code>. As the third argument, use the <code>by=</code> argument to indicate the name of the key variable, which in this example is <code>id</code>; make sure the key variable is in quotation marks (<code>" "</code>), and remember, object and variable names in R are case and space sensitive.</li>
</ol>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="join.html#cb318-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inner join (without pipe)</span></span>
<span id="cb318-2"><a href="join.html#cb318-2" aria-hidden="true" tabindex="-1"></a>mergeddf <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(personaldata, performancedata, <span class="at">by=</span><span class="st">&quot;id&quot;</span>)</span>
<span id="cb318-3"><a href="join.html#cb318-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb318-4"><a href="join.html#cb318-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the joined data frame</span></span>
<span id="cb318-5"><a href="join.html#cb318-5" aria-hidden="true" tabindex="-1"></a>mergeddf</span></code></pre></div>
<pre><code>## # A tibble: 5 x 9
##      id lastname   firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   125 Franklin   Benjamin  1/5/2016  male       2.1     1.9     2.1     2.3
## 2   111 Newton     Isaac     1/9/2016  male       3.3     3.3     3.4     3.3
## 3   198 Morales    Linda     1/7/2016  female     4.9     4.5     4.4     4.8
## 4   201 Providence Cindy     1/9/2016  female     1.2     1.1     1       1  
## 5   282 Legend     John      1/9/2016  male       2.2     2.3     2.4     2.5</code></pre>
<p>Now, let’s revisit the original data frame objects that we read in initially.</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="join.html#cb320-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the first original data frame</span></span>
<span id="cb320-2"><a href="join.html#cb320-2" aria-hidden="true" tabindex="-1"></a>personaldata</span></code></pre></div>
<pre><code>## # A tibble: 8 x 5
##      id lastname   firstname startdate gender
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt; 
## 1   154 McDonald   Ronald    1/9/2016  male  
## 2   155 Smith      John      1/9/2016  male  
## 3   165 Doe        Jane      1/4/2016  female
## 4   125 Franklin   Benjamin  1/5/2016  male  
## 5   111 Newton     Isaac     1/9/2016  male  
## 6   198 Morales    Linda     1/7/2016  female
## 7   201 Providence Cindy     1/9/2016  female
## 8   282 Legend     John      1/9/2016  male</code></pre>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="join.html#cb322-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the second original data frame</span></span>
<span id="cb322-2"><a href="join.html#cb322-2" aria-hidden="true" tabindex="-1"></a>performancedata</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##      id perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   153     3.9     4.8     4.9     5  
## 2   125     2.1     1.9     2.1     2.3
## 3   111     3.3     3.3     3.4     3.3
## 4   198     4.9     4.5     4.4     4.8
## 5   201     1.2     1.1     1       1  
## 6   282     2.2     2.3     2.4     2.5</code></pre>
<p>In the output, first, note how all of the variables from the original data frames (i.e., <code>personaldata</code>, <code>performancedata</code>) are represented in the merged data frame (i.e., <code>mergeddf</code>). Second, note how the cases are matched by the <code>id</code> key variable. Third, note that the <code>personaldata</code> data frame has 8 cases, the <code>performancedata</code> data frame has 6 cases, and the <code>mergeddf</code> data frame has 6 cases. By default, the <code>merge</code> function performs an <em>inner join</em> and retains only those matched cases that have data in <em>both</em> data frames. Because cases whose <code>id</code> values were <code>154</code>, <code>155</code>, and <code>165</code> had data in <code>personaldata</code> but not <code>performancedata</code> and because the case with an <code>id</code> value equal to 153 was in <code>performancedata</code> but not <code>personaldata</code>, only the 5 cases that had available data in both data frames were retained.</p>
<p>To perform what is referred to as a <strong>full join</strong> in which we retain all cases and available data, we simply swap out the <code>inner_join</code> function from our previous code with the <code>full_join</code> function.</p>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="join.html#cb324-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Full join (without pipe)</span></span>
<span id="cb324-2"><a href="join.html#cb324-2" aria-hidden="true" tabindex="-1"></a>mergeddf <span class="ot">&lt;-</span> <span class="fu">full_join</span>(personaldata, performancedata, <span class="at">by=</span><span class="st">&quot;id&quot;</span>)</span>
<span id="cb324-3"><a href="join.html#cb324-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb324-4"><a href="join.html#cb324-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the joined data frame</span></span>
<span id="cb324-5"><a href="join.html#cb324-5" aria-hidden="true" tabindex="-1"></a>mergeddf</span></code></pre></div>
<pre><code>## # A tibble: 9 x 9
##      id lastname   firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   154 McDonald   Ronald    1/9/2016  male      NA      NA      NA      NA  
## 2   155 Smith      John      1/9/2016  male      NA      NA      NA      NA  
## 3   165 Doe        Jane      1/4/2016  female    NA      NA      NA      NA  
## 4   125 Franklin   Benjamin  1/5/2016  male       2.1     1.9     2.1     2.3
## 5   111 Newton     Isaac     1/9/2016  male       3.3     3.3     3.4     3.3
## 6   198 Morales    Linda     1/7/2016  female     4.9     4.5     4.4     4.8
## 7   201 Providence Cindy     1/9/2016  female     1.2     1.1     1       1  
## 8   282 Legend     John      1/9/2016  male       2.2     2.3     2.4     2.5
## 9   153 &lt;NA&gt;       &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;       3.9     4.8     4.9     5</code></pre>
<p>Note how the <code>full_join</code> function retains all available cases that had available data in at least one of the data frames, which in this example is 9 cases. <em>When in doubt, I recommend using the <code>full_join</code> function to retain all available data.</em></p>
<p>To perform what is referred to as a <strong>left join</strong> in which we retain only those cases with data available in the first (left, x) data frame (<code>personaldata</code>), we use the <code>left_join</code> function instead, while keeping the rest of the previous code the same.</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="join.html#cb326-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Left join (without pipe)</span></span>
<span id="cb326-2"><a href="join.html#cb326-2" aria-hidden="true" tabindex="-1"></a>mergeddf <span class="ot">&lt;-</span> <span class="fu">left_join</span>(personaldata, performancedata, <span class="at">by=</span><span class="st">&quot;id&quot;</span>)</span>
<span id="cb326-3"><a href="join.html#cb326-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb326-4"><a href="join.html#cb326-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the joined data frame</span></span>
<span id="cb326-5"><a href="join.html#cb326-5" aria-hidden="true" tabindex="-1"></a>mergeddf</span></code></pre></div>
<pre><code>## # A tibble: 8 x 9
##      id lastname   firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   154 McDonald   Ronald    1/9/2016  male      NA      NA      NA      NA  
## 2   155 Smith      John      1/9/2016  male      NA      NA      NA      NA  
## 3   165 Doe        Jane      1/4/2016  female    NA      NA      NA      NA  
## 4   125 Franklin   Benjamin  1/5/2016  male       2.1     1.9     2.1     2.3
## 5   111 Newton     Isaac     1/9/2016  male       3.3     3.3     3.4     3.3
## 6   198 Morales    Linda     1/7/2016  female     4.9     4.5     4.4     4.8
## 7   201 Providence Cindy     1/9/2016  female     1.2     1.1     1       1  
## 8   282 Legend     John      1/9/2016  male       2.2     2.3     2.4     2.5</code></pre>
<p>Note how the <code>left_join</code> function retains only those cases for which the first (left, x) data frame (i.e., <code>personaldata</code>) has complete data, which in this case happens to be 8 cases. Notably absent is the case associated with <code>id</code> equal to 153 because the first (left, x) data frame (i.e., <code>personaldata</code>) lacked that case. An <code>NA</code> appears for each case from the second (right, y) data frame that contained missing values on variables from that data frame.</p>
<p>To perform what is referred to as a <strong>right join</strong> in which we retain only those cases with data available in the second (right, y) data frame (<code>performancedata</code>), we use the <code>right_join</code> function instead, while keeping the rest of the previous code the same.</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="join.html#cb328-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Right join (without pipe)</span></span>
<span id="cb328-2"><a href="join.html#cb328-2" aria-hidden="true" tabindex="-1"></a>mergeddf <span class="ot">&lt;-</span> <span class="fu">right_join</span>(personaldata, performancedata, <span class="at">by=</span><span class="st">&quot;id&quot;</span>)</span>
<span id="cb328-3"><a href="join.html#cb328-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb328-4"><a href="join.html#cb328-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the joined data frame</span></span>
<span id="cb328-5"><a href="join.html#cb328-5" aria-hidden="true" tabindex="-1"></a>mergeddf</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##      id lastname   firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   125 Franklin   Benjamin  1/5/2016  male       2.1     1.9     2.1     2.3
## 2   111 Newton     Isaac     1/9/2016  male       3.3     3.3     3.4     3.3
## 3   198 Morales    Linda     1/7/2016  female     4.9     4.5     4.4     4.8
## 4   201 Providence Cindy     1/9/2016  female     1.2     1.1     1       1  
## 5   282 Legend     John      1/9/2016  male       2.2     2.3     2.4     2.5
## 6   153 &lt;NA&gt;       &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;       3.9     4.8     4.9     5</code></pre>
<p>Note how the <code>right_join</code> function retains only those cases for which the joined (second, right, y) data frame (i.e., <code>performancedata</code>) has complete data. Because the first (left, x) data frame lacks data for the case in which <code>id</code> is equal to 153, an <code>NA</code> appears for each case from the first data frame that contained missing values on variables from that data frame.</p>
</div>
</div>
<div id="verticaljoin" class="section level3" number="17.2.5">
<h3><span class="header-section-number">17.2.5</span> Vertical Join (Merge)</h3>
<p>To perform a vertical join (merge), we will use the <code>rbind</code> function from base R, which stands for “row bind.” As a reminder, with a horizontal join, our focus is on joining variables (i.e., columns, fields) from two data frames containing overlapping cases (i.e., rows). In contrast, with a vertical join, our focus is on joining cases from data frames with the same variables.</p>
<p>To illustrate how to perform a vertical join, we take a slightly different approach than what we did with <a href="join.html#horizontaljoin">horizontal joins</a>. Instead of reading in data files, we will create two “toy” employee demographic data frames with the exact same variables but different cases. We will use the <code>data.frame</code> function from base R to indicate that we wish to create a data frame object; we use the <code>c</code> (combine) function from base R to combine values into a vector; and we use the <code>rep</code> (replicate) function from base R to replicate the same value a specified number of times. Also note that the <code>:</code> operator, when used between two numbers, creates a vector of consecutive values, beginning with the first value and ending with the second. Please note, that using and understanding the <code>data.frame</code>, <code>c</code>, and <code>rep</code> functions is not consequential for understanding how to do a vertical merge; rather, I merely use these functions in this tutorial to create quick toy data frames that we can use to illustrate how to do a vertical join. For more information on the <code>data.frame</code> function and the <code>c</code> function, please refer to the chapter called <a href="gentleintro.html#gentleintro">Basic Features and Operations of the R Language</a>.</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="join.html#cb330-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create data frames with same variables but arbitrary values</span></span>
<span id="cb330-2"><a href="join.html#cb330-2" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id=</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>), <span class="at">age=</span><span class="fu">c</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">26</span>), <span class="at">sex=</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;male&quot;</span>, <span class="dv">6</span>)))</span>
<span id="cb330-3"><a href="join.html#cb330-3" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id=</span><span class="fu">c</span>(<span class="dv">7</span><span class="sc">:</span><span class="dv">10</span>), <span class="at">age=</span><span class="fu">c</span>(<span class="dv">27</span><span class="sc">:</span><span class="dv">30</span>), <span class="at">sex=</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;female&quot;</span>, <span class="dv">4</span>)))</span></code></pre></div>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="join.html#cb331-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print first data frame</span></span>
<span id="cb331-2"><a href="join.html#cb331-2" aria-hidden="true" tabindex="-1"></a>df1</span></code></pre></div>
<pre><code>##   id age  sex
## 1  1  21 male
## 2  2  22 male
## 3  3  23 male
## 4  4  24 male
## 5  5  25 male
## 6  6  26 male</code></pre>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="join.html#cb333-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print second data frame</span></span>
<span id="cb333-2"><a href="join.html#cb333-2" aria-hidden="true" tabindex="-1"></a>df2</span></code></pre></div>
<pre><code>##   id age    sex
## 1  7  27 female
## 2  8  28 female
## 3  9  29 female
## 4 10  30 female</code></pre>
<p>Given that these two data frames (i.e., <code>df1</code>, <code>df2</code>) have the exact same variable names (<code>id</code>, <code>age</code>, and <code>sex</code>), we can easily perform a vertical join using the <code>rbind</code> function. To do so, enter the names of the two data frames as arguments, separated by a comma. Use the <code>&lt;-</code> operator to name the merged data frame something, which for this case, I arbitrarily named it <code>mergeddf2</code>.</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="join.html#cb335-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vertical merge</span></span>
<span id="cb335-2"><a href="join.html#cb335-2" aria-hidden="true" tabindex="-1"></a>mergeddf2 <span class="ot">&lt;-</span> <span class="fu">rbind</span>(df1, df2)</span>
<span id="cb335-3"><a href="join.html#cb335-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb335-4"><a href="join.html#cb335-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the merged data frame</span></span>
<span id="cb335-5"><a href="join.html#cb335-5" aria-hidden="true" tabindex="-1"></a>mergeddf2</span></code></pre></div>
<pre><code>##    id age    sex
## 1   1  21   male
## 2   2  22   male
## 3   3  23   male
## 4   4  24   male
## 5   5  25   male
## 6   6  26   male
## 7   7  27 female
## 8   8  28 female
## 9   9  29 female
## 10 10  30 female</code></pre>
<p>Note how the two data frames are now “stacked” on one another. This was possible because they shared the same variables names and variables types (e.g., numeric and character).</p>
</div>
<div id="summary_join" class="section level3" number="17.2.6">
<h3><span class="header-section-number">17.2.6</span> Summary</h3>
<p>Joining (merging) data frames in R is a useful practice. In this chapter, we learned how to perform a horizontal join using the <code>right_join</code>, <code>left_join</code>, <code>inner_join</code>, and <code>full_join</code> functions from the <code>dplyr</code> package. We also learned how to perform a vertical join using the <code>rbind</code> function from base R.</p>
</div>
</div>
<div id="join_supplement" class="section level2" number="17.3">
<h2><span class="header-section-number">17.3</span> Chapter Supplement</h2>
<p>In addition to the <code>join</code> functions from the <code>dplyr</code> package covered <a href="join.html#horizontaljoin">above</a>, we can use the <code>merge</code> function from base R to perform a <em>horizontal join</em>. Because this function comes from base R, we do not need to install and access an additional package like we do with the <code>join</code> functions, which some may find advantageous.</p>
<div id="supp_join_video" class="section level3" number="17.3.1">
<h3><span class="header-section-number">17.3.1</span> Video Tutorial</h3>
<p>In addition to the written chapter supplement provided below, you can follow along with the following video tutorial to learn more about how to horizontally join data two data frames using the <code>merge</code> function from base R.</p>
<iframe src="https://youtube.com/embed/MLihEVEpJBg?rel=0" width="672" height="400px">
</iframe>
<p>Link to video tutorial: <a href="https://youtu.be/MLihEVEpJBg" class="uri">https://youtu.be/MLihEVEpJBg</a></p>
</div>
<div id="join_supplement_functions" class="section level3" number="17.3.2">
<h3><span class="header-section-number">17.3.2</span> Functions &amp; Packages Introduced</h3>
<table>
<thead>
<tr class="header">
<th>Function</th>
<th>Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>names</code></td>
<td>base R</td>
</tr>
<tr class="even">
<td><code>merge</code></td>
<td>base R</td>
</tr>
</tbody>
</table>
</div>
<div id="join_initsteps_supplement" class="section level3" number="17.3.3">
<h3><span class="header-section-number">17.3.3</span> Initial Steps</h3>
<p>If required, please refer to the <a href="join.html#initsteps_join">Initial Steps</a> section from this chapter for more information on these initial steps. <strong>Please note, however, that we are using two slightly different data files in this supplement, which will simply and clarify some of the different types of merges (joins) that we’ll go over.</strong></p>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="join.html#cb337-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your working directory</span></span>
<span id="cb337-2"><a href="join.html#cb337-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;H:/RWorkshop&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="join.html#cb338-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access readr package</span></span>
<span id="cb338-2"><a href="join.html#cb338-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb338-3"><a href="join.html#cb338-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb338-4"><a href="join.html#cb338-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data and name data frame (tibble) objects</span></span>
<span id="cb338-5"><a href="join.html#cb338-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that these data files are different than the</span></span>
<span id="cb338-6"><a href="join.html#cb338-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ones we used in the main part of the chapter</span></span>
<span id="cb338-7"><a href="join.html#cb338-7" aria-hidden="true" tabindex="-1"></a>personaldata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;PersonalData.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification ---------------------------------------------------------------------------------------------------
## cols(
##   id = col_double(),
##   lastname = col_character(),
##   firstname = col_character(),
##   startdate = col_character(),
##   gender = col_character()
## )</code></pre>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="join.html#cb340-1" aria-hidden="true" tabindex="-1"></a>performancedata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;PerformanceData.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification ---------------------------------------------------------------------------------------------------
## cols(
##   id = col_double(),
##   perf_q1 = col_double(),
##   perf_q2 = col_double(),
##   perf_q3 = col_double(),
##   perf_q4 = col_double()
## )</code></pre>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="join.html#cb342-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the names of the variables in the data frame (tibble) objects</span></span>
<span id="cb342-2"><a href="join.html#cb342-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(personaldata)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;        &quot;lastname&quot;  &quot;firstname&quot; &quot;startdate&quot; &quot;gender&quot;</code></pre>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="join.html#cb344-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(performancedata)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;      &quot;perf_q1&quot; &quot;perf_q2&quot; &quot;perf_q3&quot; &quot;perf_q4&quot;</code></pre>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="join.html#cb346-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print data frame (tibble) objects</span></span>
<span id="cb346-2"><a href="join.html#cb346-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(personaldata)</span></code></pre></div>
<pre><code>## # A tibble: 8 x 5
##      id lastname   firstname startdate gender
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt; 
## 1   153 Sanchez    Alejandro 1/1/2016  man   
## 2   154 McDonald   Ronald    1/9/2016  man   
## 3   155 Smith      John      1/9/2016  man   
## 4   165 Doe        Jane      1/4/2016  woman 
## 5   111 Newton     Isaac     1/9/2016  man   
## 6   198 Morales    Linda     1/7/2016  woman 
## 7   201 Providence Cindy     1/9/2016  woman 
## 8   282 Legend     John      1/9/2016  man</code></pre>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="join.html#cb348-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(performancedata)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##      id perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   153     3.9     4.8     4.9     5  
## 2   125     2.1     1.9     2.1     2.3
## 3   111     3.3     3.3     3.4     3.3
## 4   198     4.9     4.5     4.4     4.8
## 5   201     1.2     1.1     1       1  
## 6   282     2.2     2.3     2.4     2.5</code></pre>
</div>
<div id="join_mergefunction" class="section level3" number="17.3.4">
<h3><span class="header-section-number">17.3.4</span> <code>merge</code> Function from Base R</h3>
<p>We will use the <code>merge</code> function to horizontally match cases from the <code>personaldata</code> and <code>performancedata</code> data frames using <code>id</code> as a key variable. To identify what the key variable is, let’s use the <code>names</code> function from base R to print the list of variable names from the two data frames, which we already did above. Nevertheless, let’s call up those variable names once more. Simply enter the name of the data frame as a parenthetical argument in the <code>names</code> function.</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="join.html#cb350-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print variable names from first data frame</span></span>
<span id="cb350-2"><a href="join.html#cb350-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(personaldata)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;        &quot;lastname&quot;  &quot;firstname&quot; &quot;startdate&quot; &quot;gender&quot;</code></pre>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="join.html#cb352-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print variable names from second data frame</span></span>
<span id="cb352-2"><a href="join.html#cb352-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(performancedata)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;      &quot;perf_q1&quot; &quot;perf_q2&quot; &quot;perf_q3&quot; &quot;perf_q4&quot;</code></pre>
<p>As you can see in the variable names listed above, the <code>id</code> variable is common to both data frames, and thus it will serve as our key variable.</p>
<p>Let’s begin with what is referred to as an <strong>inner join</strong>:</p>
<ol style="list-style-type: decimal">
<li>Use the <code>&lt;-</code> operator to name the joined data frame that we create using the <code>merge</code> function. For this example, I name the new joined data frame <code>mergeddf</code>, which is completely arbitrary; you could name it whatever you would like. Type the name of the new joined data frame to the <em>left</em> of the <code>&lt;-</code> operator.</li>
<li>To the <em>right</em> of the <code>&lt;-</code> operator, type the name of the <code>merge</code> function. Within the <code>merge</code> function parentheses, we will provide the arguments needed to make this join a reality. First, enter the name of one of the data frames (e.g., <code>personaldata</code>), followed by a comma. Second, enter the name of of the other data frame (e.g., <code>performancedata</code>), followed by a comma. Third, use the <code>by=</code> argument to indicate the name of the key variable (e.g., <code>id</code>); make sure the key variable is in quotation marks (<code>" "</code>), and remember, object and variable names in R are case and space sensitive.</li>
</ol>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="join.html#cb354-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inner join</span></span>
<span id="cb354-2"><a href="join.html#cb354-2" aria-hidden="true" tabindex="-1"></a>mergeddf <span class="ot">&lt;-</span> <span class="fu">merge</span>(personaldata, performancedata, <span class="at">by=</span><span class="st">&quot;id&quot;</span>)</span>
<span id="cb354-3"><a href="join.html#cb354-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb354-4"><a href="join.html#cb354-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the joined data frame</span></span>
<span id="cb354-5"><a href="join.html#cb354-5" aria-hidden="true" tabindex="-1"></a>mergeddf</span></code></pre></div>
<pre><code>##    id   lastname firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
## 1 111     Newton     Isaac  1/9/2016    man     3.3     3.3     3.4     3.3
## 2 153    Sanchez Alejandro  1/1/2016    man     3.9     4.8     4.9     5.0
## 3 198    Morales     Linda  1/7/2016  woman     4.9     4.5     4.4     4.8
## 4 201 Providence     Cindy  1/9/2016  woman     1.2     1.1     1.0     1.0
## 5 282     Legend      John  1/9/2016    man     2.2     2.3     2.4     2.5</code></pre>
<p>Now, let’s revisit the original data frame objects that we read in initially.</p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="join.html#cb356-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the first original data frame</span></span>
<span id="cb356-2"><a href="join.html#cb356-2" aria-hidden="true" tabindex="-1"></a>personaldata</span></code></pre></div>
<pre><code>## # A tibble: 8 x 5
##      id lastname   firstname startdate gender
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt; 
## 1   153 Sanchez    Alejandro 1/1/2016  man   
## 2   154 McDonald   Ronald    1/9/2016  man   
## 3   155 Smith      John      1/9/2016  man   
## 4   165 Doe        Jane      1/4/2016  woman 
## 5   111 Newton     Isaac     1/9/2016  man   
## 6   198 Morales    Linda     1/7/2016  woman 
## 7   201 Providence Cindy     1/9/2016  woman 
## 8   282 Legend     John      1/9/2016  man</code></pre>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="join.html#cb358-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the second original data frame</span></span>
<span id="cb358-2"><a href="join.html#cb358-2" aria-hidden="true" tabindex="-1"></a>performancedata</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##      id perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   153     3.9     4.8     4.9     5  
## 2   125     2.1     1.9     2.1     2.3
## 3   111     3.3     3.3     3.4     3.3
## 4   198     4.9     4.5     4.4     4.8
## 5   201     1.2     1.1     1       1  
## 6   282     2.2     2.3     2.4     2.5</code></pre>
<p>In the output, first, note how all of the variables from the original data frames (i.e., <code>personaldata</code>, <code>performancedata</code>) are represented in the merged data frame (i.e., <code>mergeddf</code>). Second, note how the cases are matched by the <code>id</code> key variable. Third, note that the <code>personaldata</code> data frame has 8 cases, the <code>performancedata</code> data frame has 6 cases, and the <code>mergeddf</code> data frame has 6 cases. By default, the <code>merge</code> function performs an <em>inner join</em> and retains only those matched cases that have data in <em>both</em> data frames. Because cases whose <code>id</code> values were <code>154</code>, <code>155</code>, and <code>165</code> had data in <code>personaldata</code> but not <code>performancedata</code> and because the case with an <code>id</code> value equal to 153 was in <code>performancedata</code> but not <code>personaldata</code>, only the 5 cases that had available data in both data frames were retained.</p>
<p>To perform what is referred to as a <strong>full join</strong> in which we retain all cases and available data, we can add the <code>all=</code> argument to our previous code and specify the logical value <code>TRUE</code>.</p>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb360-1"><a href="join.html#cb360-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Full join</span></span>
<span id="cb360-2"><a href="join.html#cb360-2" aria-hidden="true" tabindex="-1"></a>mergeddf <span class="ot">&lt;-</span> <span class="fu">merge</span>(personaldata, performancedata, <span class="at">by=</span><span class="st">&quot;id&quot;</span>, <span class="at">all=</span><span class="cn">TRUE</span>)</span>
<span id="cb360-3"><a href="join.html#cb360-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb360-4"><a href="join.html#cb360-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the joined data frame</span></span>
<span id="cb360-5"><a href="join.html#cb360-5" aria-hidden="true" tabindex="-1"></a>mergeddf</span></code></pre></div>
<pre><code>##    id   lastname firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
## 1 111     Newton     Isaac  1/9/2016    man     3.3     3.3     3.4     3.3
## 2 125       &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;   &lt;NA&gt;     2.1     1.9     2.1     2.3
## 3 153    Sanchez Alejandro  1/1/2016    man     3.9     4.8     4.9     5.0
## 4 154   McDonald    Ronald  1/9/2016    man      NA      NA      NA      NA
## 5 155      Smith      John  1/9/2016    man      NA      NA      NA      NA
## 6 165        Doe      Jane  1/4/2016  woman      NA      NA      NA      NA
## 7 198    Morales     Linda  1/7/2016  woman     4.9     4.5     4.4     4.8
## 8 201 Providence     Cindy  1/9/2016  woman     1.2     1.1     1.0     1.0
## 9 282     Legend      John  1/9/2016    man     2.2     2.3     2.4     2.5</code></pre>
<p>Note how the <code>full_join</code> function retains all available cases that had available data in at least one of the data frames, which in this example is 9 cases. <em>When in doubt, I recommend using the <code>full_join</code> function to retain all available data.</em></p>
<p>To perform what is referred to as a <strong>left join</strong> in which we retain only those cases with data available in the first (left, x) data frame (<code>personaldata</code>), we use the <code>all.x=TRUE</code> argument instead.</p>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb362-1"><a href="join.html#cb362-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Left join </span></span>
<span id="cb362-2"><a href="join.html#cb362-2" aria-hidden="true" tabindex="-1"></a>mergeddf <span class="ot">&lt;-</span> <span class="fu">merge</span>(personaldata, performancedata, <span class="at">by=</span><span class="st">&quot;id&quot;</span>, <span class="at">all.x=</span><span class="cn">TRUE</span>)</span>
<span id="cb362-3"><a href="join.html#cb362-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb362-4"><a href="join.html#cb362-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the joined data frame</span></span>
<span id="cb362-5"><a href="join.html#cb362-5" aria-hidden="true" tabindex="-1"></a>mergeddf</span></code></pre></div>
<pre><code>##    id   lastname firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
## 1 111     Newton     Isaac  1/9/2016    man     3.3     3.3     3.4     3.3
## 2 153    Sanchez Alejandro  1/1/2016    man     3.9     4.8     4.9     5.0
## 3 154   McDonald    Ronald  1/9/2016    man      NA      NA      NA      NA
## 4 155      Smith      John  1/9/2016    man      NA      NA      NA      NA
## 5 165        Doe      Jane  1/4/2016  woman      NA      NA      NA      NA
## 6 198    Morales     Linda  1/7/2016  woman     4.9     4.5     4.4     4.8
## 7 201 Providence     Cindy  1/9/2016  woman     1.2     1.1     1.0     1.0
## 8 282     Legend      John  1/9/2016    man     2.2     2.3     2.4     2.5</code></pre>
<p>Note how the <em>left join</em> retains only those cases for which the first (left, x) data frame (i.e., <code>personaldata</code>) has complete data, which in this case happens to be 8 cases. Notably absent is the case associated with <code>id</code> equal to 153 because the first (left, x) data frame (i.e., <code>personaldata</code>) lacked that case. An <code>NA</code> appears for each case from the second (right, y) data frame that contained missing values on variables from that data frame.</p>
<p>To perform what is referred to as a <strong>right join</strong> in which we retain only those cases with data available in the second (right, y) data frame (<code>performancedata</code>), we use the <code>all.y=TRUE</code> argument instead.</p>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="join.html#cb364-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Right join </span></span>
<span id="cb364-2"><a href="join.html#cb364-2" aria-hidden="true" tabindex="-1"></a>mergeddf <span class="ot">&lt;-</span> <span class="fu">merge</span>(personaldata, performancedata, <span class="at">by=</span><span class="st">&quot;id&quot;</span>, <span class="at">all.y=</span><span class="cn">TRUE</span>)</span>
<span id="cb364-3"><a href="join.html#cb364-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb364-4"><a href="join.html#cb364-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the joined data frame</span></span>
<span id="cb364-5"><a href="join.html#cb364-5" aria-hidden="true" tabindex="-1"></a>mergeddf</span></code></pre></div>
<pre><code>##    id   lastname firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
## 1 111     Newton     Isaac  1/9/2016    man     3.3     3.3     3.4     3.3
## 2 125       &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;   &lt;NA&gt;     2.1     1.9     2.1     2.3
## 3 153    Sanchez Alejandro  1/1/2016    man     3.9     4.8     4.9     5.0
## 4 198    Morales     Linda  1/7/2016  woman     4.9     4.5     4.4     4.8
## 5 201 Providence     Cindy  1/9/2016  woman     1.2     1.1     1.0     1.0
## 6 282     Legend      John  1/9/2016    man     2.2     2.3     2.4     2.5</code></pre>
<p>Note how the <em>right join</em> retains only those cases for which the joined (second, right, y) data frame (i.e., <code>performancedata</code>) has complete data. Because the first (left, x) data frame lacks data for the case in which <code>id</code> is equal to 153, an <code>NA</code> appears for each case from the first data frame that contained missing values on variables from that data frame.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="arrange.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="filter.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
