<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Joining (Merging) Data: Chapter Supplement | R for HR: An Introduction to Human Resource Analytics Using R Version: Under Construction</title>
  <meta name="description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Joining (Merging) Data: Chapter Supplement | R for HR: An Introduction to Human Resource Analytics Using R Version: Under Construction" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="cover.png" />
  <meta property="og:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="github-repo" content="davidcaughlin/R-for-HR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Joining (Merging) Data: Chapter Supplement | R for HR: An Introduction to Human Resource Analytics Using R Version: Under Construction" />
  
  <meta name="twitter:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="twitter:image" content="cover.png" />

<meta name="author" content="David E. Caughlin" />


<meta name="date" content="2021-01-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="arrange-supplement.html"/>
<link rel="next" href="filter-supplement.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for HR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#coverart"><i class="fa fa-check"></i><b>0.1</b> Cover Art</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#hragrowth"><i class="fa fa-check"></i><b>0.2</b> Growth of HR Analytics</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#skills-gap"><i class="fa fa-check"></i><b>0.3</b> Skills Gap</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#hraplc"><i class="fa fa-check"></i><b>0.4</b> HR Analytics Project Life Cycle</a><ul>
<li class="chapter" data-level="0.4.1" data-path="index.html"><a href="index.html#questform"><i class="fa fa-check"></i><b>0.4.1</b> Question Formulation</a></li>
<li class="chapter" data-level="0.4.2" data-path="index.html"><a href="index.html#dacquire"><i class="fa fa-check"></i><b>0.4.2</b> Data Acquisition</a></li>
<li class="chapter" data-level="0.4.3" data-path="index.html"><a href="index.html#dmanage"><i class="fa fa-check"></i><b>0.4.3</b> Data Management</a></li>
<li class="chapter" data-level="0.4.4" data-path="index.html"><a href="index.html#danalysis"><i class="fa fa-check"></i><b>0.4.4</b> Data Analysis</a></li>
<li class="chapter" data-level="0.4.5" data-path="index.html"><a href="index.html#dinterpret"><i class="fa fa-check"></i><b>0.4.5</b> Data Interpretion &amp; Storytelling</a></li>
<li class="chapter" data-level="0.4.6" data-path="index.html"><a href="index.html#ddeploy"><i class="fa fa-check"></i><b>0.4.6</b> Deployment &amp; Implementation</a></li>
</ul></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#philosophy"><i class="fa fa-check"></i><b>0.5</b> My Philosophy for This Book</a><ul>
<li class="chapter" data-level="0.5.1" data-path="index.html"><a href="index.html#rationalerpref"><i class="fa fa-check"></i><b>0.5.1</b> Rationale for Using R</a></li>
<li class="chapter" data-level="0.5.2" data-path="index.html"><a href="index.html#audiencepref"><i class="fa fa-check"></i><b>0.5.2</b> Audience</a></li>
<li class="chapter" data-level="0.5.3" data-path="index.html"><a href="index.html#structurepref"><i class="fa fa-check"></i><b>0.5.3</b> Structure</a></li>
</ul></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#aboutauthor"><i class="fa fa-check"></i><b>0.6</b> About the Author</a></li>
<li class="chapter" data-level="0.7" data-path="index.html"><a href="index.html#acknowpref"><i class="fa fa-check"></i><b>0.7</b> Acknowledgements</a></li>
</ul></li>
<li class="part"><span><b>I Introduction to R</b></span></li>
<li class="chapter" data-level="1" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>1</b> Installing R &amp; RStudio</a><ul>
<li class="chapter" data-level="1.1" data-path="install.html"><a href="install.html#downloading-installing-r"><i class="fa fa-check"></i><b>1.1</b> Downloading &amp; Installing R</a><ul>
<li class="chapter" data-level="1.1.1" data-path="install.html"><a href="install.html#for-windows-operation-systems"><i class="fa fa-check"></i><b>1.1.1</b> For Windows Operation Systems</a></li>
<li class="chapter" data-level="1.1.2" data-path="install.html"><a href="install.html#for-mac-operating-systems"><i class="fa fa-check"></i><b>1.1.2</b> For Mac Operating Systems</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="install.html"><a href="install.html#downloading-installing-rstudio"><i class="fa fa-check"></i><b>1.2</b> Downloading &amp; Installing RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="install.html"><a href="install.html#summary"><i class="fa fa-check"></i><b>1.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="gettingstarted.html"><a href="gettingstarted.html"><i class="fa fa-check"></i><b>2</b> Getting Started with R</a><ul>
<li class="chapter" data-level="2.1" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation-to-rstudio"><i class="fa fa-check"></i><b>2.1</b> Orientation to RStudio</a></li>
<li class="chapter" data-level="2.2" data-path="gettingstarted.html"><a href="gettingstarted.html#createRscript"><i class="fa fa-check"></i><b>2.2</b> Creating &amp; Saving an R Script</a><ul>
<li class="chapter" data-level="2.2.1" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-a-new-r-script"><i class="fa fa-check"></i><b>2.2.1</b> Creating a New R Script</a></li>
<li class="chapter" data-level="2.2.2" data-path="gettingstarted.html"><a href="gettingstarted.html#using-an-r-script"><i class="fa fa-check"></i><b>2.2.2</b> Using an R Script</a></li>
<li class="chapter" data-level="2.2.3" data-path="gettingstarted.html"><a href="gettingstarted.html#saving-an-r-script"><i class="fa fa-check"></i><b>2.2.3</b> Saving an R Script</a></li>
<li class="chapter" data-level="2.2.4" data-path="gettingstarted.html"><a href="gettingstarted.html#opening-a-saved-r-script"><i class="fa fa-check"></i><b>2.2.4</b> Opening a Saved R Script</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-an-rstudio-project"><i class="fa fa-check"></i><b>2.3</b> Creating an RStudio Project</a><ul>
<li class="chapter" data-level="2.3.1" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-a-new-rstudio-project"><i class="fa fa-check"></i><b>2.3.1</b> Creating a New RStudio Project</a></li>
<li class="chapter" data-level="2.3.2" data-path="gettingstarted.html"><a href="gettingstarted.html#opening-an-existing-rstudio-project"><i class="fa fa-check"></i><b>2.3.2</b> Opening an Existing RStudio Project</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation-to-written-tutorials"><i class="fa fa-check"></i><b>2.4</b> Orientation to Written Tutorials</a></li>
<li class="chapter" data-level="2.5" data-path="install.html"><a href="install.html#summary"><i class="fa fa-check"></i><b>2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="gentleintro.html"><a href="gentleintro.html"><i class="fa fa-check"></i><b>3</b> Basic Features and Operations of the R Language</a><ul>
<li class="chapter" data-level="3.1" data-path="gentleintro.html"><a href="gentleintro.html#r-as-a-calculator"><i class="fa fa-check"></i><b>3.1</b> R as a Calculator</a></li>
<li class="chapter" data-level="3.2" data-path="gentleintro.html"><a href="gentleintro.html#functions"><i class="fa fa-check"></i><b>3.2</b> Functions</a></li>
<li class="chapter" data-level="3.3" data-path="gentleintro.html"><a href="gentleintro.html#packages"><i class="fa fa-check"></i><b>3.3</b> Packages</a></li>
<li class="chapter" data-level="3.4" data-path="gentleintro.html"><a href="gentleintro.html#variable-assignment"><i class="fa fa-check"></i><b>3.4</b> Variable Assignment</a></li>
<li class="chapter" data-level="3.5" data-path="gentleintro.html"><a href="gentleintro.html#types-of-data"><i class="fa fa-check"></i><b>3.5</b> Types of Data</a><ul>
<li class="chapter" data-level="3.5.1" data-path="gentleintro.html"><a href="gentleintro.html#numeric-data"><i class="fa fa-check"></i><b>3.5.1</b> <code>numeric</code> Data</a></li>
<li class="chapter" data-level="3.5.2" data-path="gentleintro.html"><a href="gentleintro.html#character-data"><i class="fa fa-check"></i><b>3.5.2</b> <code>character</code> Data</a></li>
<li class="chapter" data-level="3.5.3" data-path="gentleintro.html"><a href="gentleintro.html#date-data"><i class="fa fa-check"></i><b>3.5.3</b> <code>Date</code> Data</a></li>
<li class="chapter" data-level="3.5.4" data-path="gentleintro.html"><a href="gentleintro.html#logical-data"><i class="fa fa-check"></i><b>3.5.4</b> <code>logical</code> Data</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="gentleintro.html"><a href="gentleintro.html#vectors"><i class="fa fa-check"></i><b>3.6</b> Vectors</a></li>
<li class="chapter" data-level="3.7" data-path="gentleintro.html"><a href="gentleintro.html#lists"><i class="fa fa-check"></i><b>3.7</b> Lists</a></li>
<li class="chapter" data-level="3.8" data-path="gentleintro.html"><a href="gentleintro.html#data-frames"><i class="fa fa-check"></i><b>3.8</b> Data Frames</a></li>
<li class="chapter" data-level="3.9" data-path="gentleintro.html"><a href="gentleintro.html#annotate"><i class="fa fa-check"></i><b>3.9</b> Annotations</a></li>
<li class="chapter" data-level="3.10" data-path="install.html"><a href="install.html#summary"><i class="fa fa-check"></i><b>3.10</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="setwd.html"><a href="setwd.html"><i class="fa fa-check"></i><b>4</b> Setting a Working Directory</a><ul>
<li class="chapter" data-level="4.0.1" data-path="setwd.html"><a href="setwd.html#identify-the-current-working-directory"><i class="fa fa-check"></i><b>4.0.1</b> Identify the Current Working Directory</a></li>
<li class="chapter" data-level="4.0.2" data-path="setwd.html"><a href="setwd.html#set-a-new-working-directory"><i class="fa fa-check"></i><b>4.0.2</b> Set a New Working Directory</a></li>
<li class="chapter" data-level="4.1" data-path="install.html"><a href="install.html#summary"><i class="fa fa-check"></i><b>4.1</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>II Data Acquisition</b></span></li>
<li class="chapter" data-level="5" data-path="read.html"><a href="read.html"><i class="fa fa-check"></i><b>5</b> Reading Data into R</a><ul>
<li class="chapter" data-level="5.1" data-path="read.html"><a href="read.html#read-a-.csv-file"><i class="fa fa-check"></i><b>5.1</b> Read a .csv File</a></li>
<li class="chapter" data-level="5.2" data-path="read.html"><a href="read.html#read-a-.xlsx-file"><i class="fa fa-check"></i><b>5.2</b> Read a .xlsx File</a></li>
<li class="chapter" data-level="5.3" data-path="read.html"><a href="read.html#read_specialtopics"><i class="fa fa-check"></i><b>5.3</b> Special Topics</a><ul>
<li class="chapter" data-level="5.3.1" data-path="read.html"><a href="read.html#list-data-file-names-in-working-directory"><i class="fa fa-check"></i><b>5.3.1</b> List Data File Names in Working Directory</a></li>
<li class="chapter" data-level="5.3.2" data-path="read.html"><a href="read.html#skip-rows-of-data-when-reading"><i class="fa fa-check"></i><b>5.3.2</b> Skip Rows of Data When Reading</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="install.html"><a href="install.html#summary"><i class="fa fa-check"></i><b>5.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="addnames.html"><a href="addnames.html"><i class="fa fa-check"></i><b>6</b> Removing and Adding Variable Names</a><ul>
<li class="chapter" data-level="6.1" data-path="addnames.html"><a href="addnames.html#remove-variable-names-from-a-data-frame-object"><i class="fa fa-check"></i><b>6.1</b> Remove Variable Names from a Data Frame Object</a></li>
<li class="chapter" data-level="6.2" data-path="addnames.html"><a href="addnames.html#add-variable-names-to-a-data-frame-object"><i class="fa fa-check"></i><b>6.2</b> Add Variable Names to a Data Frame Object</a></li>
<li class="chapter" data-level="6.3" data-path="install.html"><a href="install.html#summary"><i class="fa fa-check"></i><b>6.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="write.html"><a href="write.html"><i class="fa fa-check"></i><b>7</b> Writing Data from R</a><ul>
<li class="chapter" data-level="7.1" data-path="write.html"><a href="write.html#write-data-frame-to-working-directory"><i class="fa fa-check"></i><b>7.1</b> Write Data Frame to Working Directory</a></li>
<li class="chapter" data-level="7.2" data-path="write.html"><a href="write.html#write-table-to-working-directory"><i class="fa fa-check"></i><b>7.2</b> Write Table to Working Directory</a></li>
<li class="chapter" data-level="7.3" data-path="install.html"><a href="install.html#summary"><i class="fa fa-check"></i><b>7.3</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>III Data Management</b></span></li>
<li class="chapter" data-level="8" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>8</b> Arranging (Sorting) Data</a><ul>
<li class="chapter" data-level="8.1" data-path="arrange.html"><a href="arrange.html#arrangebyvalues"><i class="fa fa-check"></i><b>8.1</b> Arrange (Sort) Data</a><ul>
<li class="chapter" data-level="8.1.1" data-path="arrange.html"><a href="arrange.html#opt1_arrange_withpipe"><i class="fa fa-check"></i><b>8.1.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="8.1.2" data-path="arrange.html"><a href="arrange.html#opt1_arrange_withoutpipe"><i class="fa fa-check"></i><b>8.1.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="install.html"><a href="install.html#summary"><i class="fa fa-check"></i><b>8.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="join.html"><a href="join.html"><i class="fa fa-check"></i><b>9</b> Joining (Merging) Data</a><ul>
<li class="chapter" data-level="9.1" data-path="join.html"><a href="join.html#horizontaljoin"><i class="fa fa-check"></i><b>9.1</b> Horizontal Join (Merge)</a><ul>
<li class="chapter" data-level="9.1.1" data-path="join.html"><a href="join.html#opt2_join_withpipe"><i class="fa fa-check"></i><b>9.1.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="9.1.2" data-path="join.html"><a href="join.html#opt2_join_withoutpipe"><i class="fa fa-check"></i><b>9.1.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="join.html"><a href="join.html#verticaljoin"><i class="fa fa-check"></i><b>9.2</b> Vertical Join (Merge)</a></li>
<li class="chapter" data-level="9.3" data-path="install.html"><a href="install.html#summary"><i class="fa fa-check"></i><b>9.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>10</b> Filtering Data</a><ul>
<li class="chapter" data-level="10.1" data-path="filter.html"><a href="filter.html#filter-cases-from-data-frame"><i class="fa fa-check"></i><b>10.1</b> Filter Cases from Data Frame</a><ul>
<li class="chapter" data-level="10.1.1" data-path="filter.html"><a href="filter.html#with-pipes"><i class="fa fa-check"></i><b>10.1.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="10.1.2" data-path="filter.html"><a href="filter.html#without-pipes"><i class="fa fa-check"></i><b>10.1.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="filter.html"><a href="filter.html#remove-single-variable-from-data-frame"><i class="fa fa-check"></i><b>10.2</b> Remove Single Variable from Data Frame</a></li>
<li class="chapter" data-level="10.3" data-path="filter.html"><a href="filter.html#select-multiple-variables-from-data-frame"><i class="fa fa-check"></i><b>10.3</b> Select Multiple Variables from Data Frame</a><ul>
<li class="chapter" data-level="10.3.1" data-path="filter.html"><a href="filter.html#with-pipe"><i class="fa fa-check"></i><b>10.3.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="10.3.2" data-path="filter.html"><a href="filter.html#without-pipe"><i class="fa fa-check"></i><b>10.3.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="filter.html"><a href="filter.html#remove-multiple-variables-from-data-frame"><i class="fa fa-check"></i><b>10.4</b> Remove Multiple Variables from Data Frame</a><ul>
<li class="chapter" data-level="10.4.1" data-path="filter.html"><a href="filter.html#with-pipe-1"><i class="fa fa-check"></i><b>10.4.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="10.4.2" data-path="filter.html"><a href="filter.html#without-pipe-1"><i class="fa fa-check"></i><b>10.4.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="install.html"><a href="install.html#summary"><i class="fa fa-check"></i><b>10.5</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>Chapter Supplements</b></span></li>
<li class="chapter" data-level="" data-path="read-supplement.html"><a href="read-supplement.html"><i class="fa fa-check"></i>Read Data: Chapter Supplement</a><ul>
<li><a href="read-supplement.html#readcsv_supp"><code>read.csv</code> Function from Base R</a></li>
<li><a href="read-supplement.html#readlessr_supp"><code>Read</code> Function from <code>lessR</code> Package</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="arrange-supplement.html"><a href="arrange-supplement.html"><i class="fa fa-check"></i>Arranging (Sorting) Data: Chapter Supplement</a><ul>
<li><a href="arrange-supplement.html#arrange_supp"><code>order</code> Function from Base R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="join-supplement.html"><a href="join-supplement.html"><i class="fa fa-check"></i>Joining (Merging) Data: Chapter Supplement</a><ul>
<li><a href="join-supplement.html#join_supp"><code>merge</code> Function from Base R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="filter-supplement.html"><a href="filter-supplement.html"><i class="fa fa-check"></i>Filtering Data: Chapter Supplement</a><ul>
<li><a href="filter-supplement.html#filter_supp"><code>subset</code> Function from Base R</a><ul>
<li class="chapter" data-level="10.5.1" data-path="filter.html"><a href="filter.html#filter-cases-from-data-frame"><i class="fa fa-check"></i><b>10.5.1</b> Filter Cases from Data Frame</a></li>
<li class="chapter" data-level="10.5.2" data-path="filter-supplement.html"><a href="filter-supplement.html#select-single-variable-from-data-frame"><i class="fa fa-check"></i><b>10.5.2</b> Select Single Variable from Data Frame</a></li>
<li class="chapter" data-level="10.5.3" data-path="filter.html"><a href="filter.html#select-multiple-variables-from-data-frame"><i class="fa fa-check"></i><b>10.5.3</b> Select Multiple Variables from Data Frame</a></li>
<li class="chapter" data-level="10.5.4" data-path="filter.html"><a href="filter.html#remove-single-variable-from-data-frame"><i class="fa fa-check"></i><b>10.5.4</b> Remove Single Variable from Data Frame</a></li>
<li class="chapter" data-level="10.5.5" data-path="filter.html"><a href="filter.html#remove-multiple-variables-from-data-frame"><i class="fa fa-check"></i><b>10.5.5</b> Remove Multiple Variables from Data Frame</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for HR:<br />
<em>An Introduction to Human Resource Analytics Using R</em><br />
<em>Version: Under Construction</em></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="join_supplement" class="section level1 unnumbered">
<h1>Joining (Merging) Data: Chapter Supplement</h1>
<p>In addition to the <code>join</code> functions from the <code>dplyr</code> package covered in <a href="join.html#join">Joining (Merging) Data</a>, we can use the <code>merge</code> function from base R to perform a <em>horizontal join</em>. Because this function comes from base R, we do not need to install and access an additional package like we do with the <code>join</code> functions, which some may find advantageous.</p>
<div id="functions-packages-introduced" class="section level4 unnumbered">
<h4>Functions &amp; Packages Introduced</h4>
<table>
<thead>
<tr class="header">
<th>Function</th>
<th>Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>names</code></td>
<td>base <code>R</code></td>
</tr>
<tr class="even">
<td><code>merge</code></td>
<td>base <code>R</code></td>
</tr>
</tbody>
</table>
</div>
<div id="initsteps_join_supp" class="section level4 unnumbered">
<h4>Initial Steps</h4>
<p>If required, please refer to the <a href="join.html#initsteps_join">Initial Steps</a> section from the chapter for more information on these initial steps.</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="join-supplement.html#cb401-1"></a><span class="co"># Set your working directory</span></span>
<span id="cb401-2"><a href="join-supplement.html#cb401-2"></a><span class="kw">setwd</span>(<span class="st">&quot;H:/RWorkshop&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="join-supplement.html#cb402-1"></a><span class="co"># Install readr package if you haven&#39;t already</span></span>
<span id="cb402-2"><a href="join-supplement.html#cb402-2"></a><span class="co"># [Note: You don&#39;t need to install a package every </span></span>
<span id="cb402-3"><a href="join-supplement.html#cb402-3"></a><span class="co"># time you wish to access it]</span></span>
<span id="cb402-4"><a href="join-supplement.html#cb402-4"></a><span class="kw">install.packages</span>(<span class="st">&quot;readr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="join-supplement.html#cb403-1"></a><span class="co"># Access readr package</span></span>
<span id="cb403-2"><a href="join-supplement.html#cb403-2"></a><span class="kw">library</span>(readr)</span>
<span id="cb403-3"><a href="join-supplement.html#cb403-3"></a></span>
<span id="cb403-4"><a href="join-supplement.html#cb403-4"></a><span class="co"># Read data and name data frame (tibble) objects</span></span>
<span id="cb403-5"><a href="join-supplement.html#cb403-5"></a>personaldata &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;PersData.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification --------------------------------------------------------
## cols(
##   id = col_double(),
##   lastname = col_character(),
##   firstname = col_character(),
##   startdate = col_character(),
##   gender = col_character()
## )</code></pre>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="join-supplement.html#cb405-1"></a>performancedata &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;PerfData.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification --------------------------------------------------------
## cols(
##   id = col_double(),
##   perf_q1 = col_double(),
##   perf_q2 = col_double(),
##   perf_q3 = col_double(),
##   perf_q4 = col_double()
## )</code></pre>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="join-supplement.html#cb407-1"></a><span class="co"># View the names of the variables in the data frame (tibble) objects</span></span>
<span id="cb407-2"><a href="join-supplement.html#cb407-2"></a><span class="kw">names</span>(personaldata)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;        &quot;lastname&quot;  &quot;firstname&quot; &quot;startdate&quot; &quot;gender&quot;</code></pre>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="join-supplement.html#cb409-1"></a><span class="kw">names</span>(performancedata)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;      &quot;perf_q1&quot; &quot;perf_q2&quot; &quot;perf_q3&quot; &quot;perf_q4&quot;</code></pre>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="join-supplement.html#cb411-1"></a><span class="co"># View data frame (tibble) objects</span></span>
<span id="cb411-2"><a href="join-supplement.html#cb411-2"></a>personaldata</span></code></pre></div>
<pre><code>## # A tibble: 9 x 5
##      id lastname   firstname startdate gender
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt; 
## 1   153 Sanchez    Alejandro 1/1/2016  male  
## 2   154 McDonald   Ronald    1/9/2016  male  
## 3   155 Smith      John      1/9/2016  male  
## 4   165 Doe        Jane      1/4/2016  female
## 5   125 Franklin   Benjamin  1/5/2016  male  
## 6   111 Newton     Isaac     1/9/2016  male  
## 7   198 Morales    Linda     1/7/2016  female
## 8   201 Providence Cindy     1/9/2016  female
## 9   282 Legend     John      1/9/2016  male</code></pre>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="join-supplement.html#cb413-1"></a>performancedata</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##      id perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   153     3.9     4.8     4.9     5  
## 2   125     2.1     1.9     2.1     2.3
## 3   111     3.3     3.3     3.4     3.3
## 4   198     4.9     4.5     4.4     4.8
## 5   201     1.2     1.1     1       1  
## 6   282     2.2     2.3     2.4     2.5</code></pre>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb415-1"><a href="join-supplement.html#cb415-1"></a><span class="co"># Remove case with id variable equal to 153</span></span>
<span id="cb415-2"><a href="join-supplement.html#cb415-2"></a>personaldata &lt;-<span class="st"> </span>personaldata[personaldata<span class="op">$</span>id <span class="op">!=</span><span class="st"> </span><span class="dv">153</span>,]</span></code></pre></div>
</div>
<div id="join_supp" class="section level2 unnumbered">
<h2><code>merge</code> Function from Base R</h2>
<p>We will use the <code>merge</code> function to horizontally match cases from the <code>personaldata</code> and <code>performancedata</code> data frames using <code>id</code> as a key variable. To identify what the key variable is, let’s use the <code>names</code> function from base R to retrieve the list of variable names from the two data frames, which we already did above. Nevertheless, let’s call up those variable names once more. Simply enter the name of the data frame as a parenthetical argument in the <code>names</code> function.</p>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="join-supplement.html#cb416-1"></a><span class="co"># Retrieve variable names from first data frame</span></span>
<span id="cb416-2"><a href="join-supplement.html#cb416-2"></a><span class="kw">names</span>(personaldata)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;        &quot;lastname&quot;  &quot;firstname&quot; &quot;startdate&quot; &quot;gender&quot;</code></pre>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="join-supplement.html#cb418-1"></a><span class="co"># Retrieve variable names from second data frame</span></span>
<span id="cb418-2"><a href="join-supplement.html#cb418-2"></a><span class="kw">names</span>(performancedata)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;      &quot;perf_q1&quot; &quot;perf_q2&quot; &quot;perf_q3&quot; &quot;perf_q4&quot;</code></pre>
<p>As you can see in the variable names listed above, the <code>id</code> variable is common to both data frames, and thus it will serve as our key variable.</p>
<p>Let’s begin with what is referred to as an <strong>inner join</strong>:</p>
<ol style="list-style-type: decimal">
<li>Use the <code>&lt;-</code> operator to name the joined data frame that we create using the <code>merge</code> function. For this example, I name the new joined data frame <code>mergeddf</code>, which is completely arbitrary; you could name it whatever you would like. Type the name of the new joined data frame to the <em>left</em> of the <code>&lt;-</code> operator.</li>
<li>To the <em>right</em> of the <code>&lt;-</code> operator, type the name of the <code>merge</code> function. Within the <code>merge</code> function parentheses, we will provide the arguments needed to make this join a reality. First, enter the name of one of the data frames (e.g., <code>personaldata</code>), followed by a comma. Second, enter the name of of the other data frame (e.g., <code>performancedata</code>), followed by a comma. Third, use the <code>by=</code> argument to indicate the name of the key variable (e.g., <code>id</code>); make sure the key variable is in quotation marks (<code>" "</code>), and remember, object and variable names in R are case and space sensitive.</li>
</ol>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="join-supplement.html#cb420-1"></a><span class="co"># Inner join</span></span>
<span id="cb420-2"><a href="join-supplement.html#cb420-2"></a>mergeddf &lt;-<span class="st"> </span><span class="kw">merge</span>(personaldata, performancedata, <span class="dt">by=</span><span class="st">&quot;id&quot;</span>)</span>
<span id="cb420-3"><a href="join-supplement.html#cb420-3"></a></span>
<span id="cb420-4"><a href="join-supplement.html#cb420-4"></a><span class="co"># View the joined data frame</span></span>
<span id="cb420-5"><a href="join-supplement.html#cb420-5"></a>mergeddf</span></code></pre></div>
<pre><code>##    id   lastname firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
## 1 111     Newton     Isaac  1/9/2016   male     3.3     3.3     3.4     3.3
## 2 125   Franklin  Benjamin  1/5/2016   male     2.1     1.9     2.1     2.3
## 3 198    Morales     Linda  1/7/2016 female     4.9     4.5     4.4     4.8
## 4 201 Providence     Cindy  1/9/2016 female     1.2     1.1     1.0     1.0
## 5 282     Legend      John  1/9/2016   male     2.2     2.3     2.4     2.5</code></pre>
<p>Now, let’s revisit the original data frame objects that we read in initially.</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="join-supplement.html#cb422-1"></a><span class="co"># View the first original data frame</span></span>
<span id="cb422-2"><a href="join-supplement.html#cb422-2"></a>personaldata</span></code></pre></div>
<pre><code>## # A tibble: 8 x 5
##      id lastname   firstname startdate gender
##   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt; 
## 1   154 McDonald   Ronald    1/9/2016  male  
## 2   155 Smith      John      1/9/2016  male  
## 3   165 Doe        Jane      1/4/2016  female
## 4   125 Franklin   Benjamin  1/5/2016  male  
## 5   111 Newton     Isaac     1/9/2016  male  
## 6   198 Morales    Linda     1/7/2016  female
## 7   201 Providence Cindy     1/9/2016  female
## 8   282 Legend     John      1/9/2016  male</code></pre>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="join-supplement.html#cb424-1"></a><span class="co"># View the second original data frame</span></span>
<span id="cb424-2"><a href="join-supplement.html#cb424-2"></a>performancedata</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##      id perf_q1 perf_q2 perf_q3 perf_q4
##   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1   153     3.9     4.8     4.9     5  
## 2   125     2.1     1.9     2.1     2.3
## 3   111     3.3     3.3     3.4     3.3
## 4   198     4.9     4.5     4.4     4.8
## 5   201     1.2     1.1     1       1  
## 6   282     2.2     2.3     2.4     2.5</code></pre>
<p>In the output, first, note how all of the variables from the original data frames (i.e., <code>personaldata</code>, <code>performancedata</code>) are represented in the merged data frame (i.e., <code>mergeddf</code>). Second, note how the cases are matched by the <code>id</code> key variable. Third, note that the <code>personaldata</code> data frame has 8 cases, the <code>performancedata</code> data frame has 6 cases, and the <code>mergeddf</code> data frame has 6 cases. By default, the <code>merge</code> function performs an <em>inner join</em> and retains only those matched cases that have data in <em>both</em> data frames. Because cases whose <code>id</code> values were <code>154</code>, <code>155</code>, and <code>165</code> had data in <code>personaldata</code> but not <code>performancedata</code> and because the case with an <code>id</code> value equal to 153 was in <code>performancedata</code> but not <code>personaldata</code>, only the 5 cases that had available data in both data frames were retained.</p>
<p>To perform what is referred to as a <strong>full join</strong> in which we retain all cases and available data, we can add the <code>all=</code> argument to our previous code and specify the logical value <code>TRUE</code>.</p>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="join-supplement.html#cb426-1"></a><span class="co"># Full join</span></span>
<span id="cb426-2"><a href="join-supplement.html#cb426-2"></a>mergeddf &lt;-<span class="st"> </span><span class="kw">merge</span>(personaldata, performancedata, <span class="dt">by=</span><span class="st">&quot;id&quot;</span>, <span class="dt">all=</span><span class="ot">TRUE</span>)</span>
<span id="cb426-3"><a href="join-supplement.html#cb426-3"></a></span>
<span id="cb426-4"><a href="join-supplement.html#cb426-4"></a><span class="co"># View the joined data frame</span></span>
<span id="cb426-5"><a href="join-supplement.html#cb426-5"></a>mergeddf</span></code></pre></div>
<pre><code>##    id   lastname firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
## 1 111     Newton     Isaac  1/9/2016   male     3.3     3.3     3.4     3.3
## 2 125   Franklin  Benjamin  1/5/2016   male     2.1     1.9     2.1     2.3
## 3 153       &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;   &lt;NA&gt;     3.9     4.8     4.9     5.0
## 4 154   McDonald    Ronald  1/9/2016   male      NA      NA      NA      NA
## 5 155      Smith      John  1/9/2016   male      NA      NA      NA      NA
## 6 165        Doe      Jane  1/4/2016 female      NA      NA      NA      NA
## 7 198    Morales     Linda  1/7/2016 female     4.9     4.5     4.4     4.8
## 8 201 Providence     Cindy  1/9/2016 female     1.2     1.1     1.0     1.0
## 9 282     Legend      John  1/9/2016   male     2.2     2.3     2.4     2.5</code></pre>
<p>Note how the <code>full_join</code> function retains all available cases that had available data in at least one of the data frames, which in this example is 9 cases. <em>When in doubt, I recommend using the <code>full_join</code> function to retain all available data.</em></p>
<p>To perform what is referred to as a <strong>left join</strong> in which we retain only those cases with data available in the first (left, x) data frame (<code>personaldata</code>), we use the <code>all.x=TRUE</code> argument instead.</p>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="join-supplement.html#cb428-1"></a><span class="co"># Left join </span></span>
<span id="cb428-2"><a href="join-supplement.html#cb428-2"></a>mergeddf &lt;-<span class="st"> </span><span class="kw">merge</span>(personaldata, performancedata, <span class="dt">by=</span><span class="st">&quot;id&quot;</span>, <span class="dt">all.x=</span><span class="ot">TRUE</span>)</span>
<span id="cb428-3"><a href="join-supplement.html#cb428-3"></a></span>
<span id="cb428-4"><a href="join-supplement.html#cb428-4"></a><span class="co"># View the joined data frame</span></span>
<span id="cb428-5"><a href="join-supplement.html#cb428-5"></a>mergeddf</span></code></pre></div>
<pre><code>##    id   lastname firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
## 1 111     Newton     Isaac  1/9/2016   male     3.3     3.3     3.4     3.3
## 2 125   Franklin  Benjamin  1/5/2016   male     2.1     1.9     2.1     2.3
## 3 154   McDonald    Ronald  1/9/2016   male      NA      NA      NA      NA
## 4 155      Smith      John  1/9/2016   male      NA      NA      NA      NA
## 5 165        Doe      Jane  1/4/2016 female      NA      NA      NA      NA
## 6 198    Morales     Linda  1/7/2016 female     4.9     4.5     4.4     4.8
## 7 201 Providence     Cindy  1/9/2016 female     1.2     1.1     1.0     1.0
## 8 282     Legend      John  1/9/2016   male     2.2     2.3     2.4     2.5</code></pre>
<p>Note how the <em>left join</em> retains only those cases for which the first (left, x) data frame (i.e., <code>personaldata</code>) has complete data, which in this case happens to be 8 cases. Notably absent is the case associated with <code>id</code> equal to 153 because the first (left, x) data frame (i.e., <code>personaldata</code>) lacked that case. An <code>NA</code> appears for each case from the second (right, y) data frame that contained missing values on variables from that data frame.</p>
<p>To perform what is referred to as a <strong>right join</strong> in which we retain only those cases with data available in the second (right, y) data frame (<code>performancedata</code>), we use the <code>all.y=TRUE</code> argument instead.</p>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="join-supplement.html#cb430-1"></a><span class="co"># Right join </span></span>
<span id="cb430-2"><a href="join-supplement.html#cb430-2"></a>mergeddf &lt;-<span class="st"> </span><span class="kw">merge</span>(personaldata, performancedata, <span class="dt">by=</span><span class="st">&quot;id&quot;</span>, <span class="dt">all.y=</span><span class="ot">TRUE</span>)</span>
<span id="cb430-3"><a href="join-supplement.html#cb430-3"></a></span>
<span id="cb430-4"><a href="join-supplement.html#cb430-4"></a><span class="co"># View the joined data frame</span></span>
<span id="cb430-5"><a href="join-supplement.html#cb430-5"></a>mergeddf</span></code></pre></div>
<pre><code>##    id   lastname firstname startdate gender perf_q1 perf_q2 perf_q3 perf_q4
## 1 111     Newton     Isaac  1/9/2016   male     3.3     3.3     3.4     3.3
## 2 125   Franklin  Benjamin  1/5/2016   male     2.1     1.9     2.1     2.3
## 3 153       &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;   &lt;NA&gt;     3.9     4.8     4.9     5.0
## 4 198    Morales     Linda  1/7/2016 female     4.9     4.5     4.4     4.8
## 5 201 Providence     Cindy  1/9/2016 female     1.2     1.1     1.0     1.0
## 6 282     Legend      John  1/9/2016   male     2.2     2.3     2.4     2.5</code></pre>
<p>Note how the <em>right join</em> retains only those cases for which the joined (second, right, y) data frame (i.e., <code>performancedata</code>) has complete data. Because the first (left, x) data frame lacks data for the case in which <code>id</code> is equal to 153, an <code>NA</code> appears for each case from the first data frame that contained missing values on variables from that data frame.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="arrange-supplement.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="filter-supplement.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["R for HR.pdf", "R for HR.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
