<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 52 Investigating Nonlinear Associations Using Polynomial Regression | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION</title>
  <meta name="description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 52 Investigating Nonlinear Associations Using Polynomial Regression | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://rforhr.com" />
  <meta property="og:image" content="https://rforhr.com/cover.png" />
  <meta property="og:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="github-repo" content="davidcaughlin/R-for-HR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 52 Investigating Nonlinear Associations Using Polynomial Regression | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  
  <meta name="twitter:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="twitter:image" content="https://rforhr.com/cover.png" />

<meta name="author" content="David E. Caughlin" />


<meta name="date" content="2022-01-22" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="convergentdiscriminantvalidity.html"/>
<link rel="next" href="lassoregression.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for HR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#hragrowth"><i class="fa fa-check"></i><b>0.1</b> Growth of HR Analytics</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#hranalytics_skillsgap"><i class="fa fa-check"></i><b>0.2</b> Skills Gap</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#hraplc"><i class="fa fa-check"></i><b>0.3</b> Project Life Cycle Perspective</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#hranalytics_hris_overview"><i class="fa fa-check"></i><b>0.4</b> Overview of HRIS &amp; HR Analytics</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#philosophy"><i class="fa fa-check"></i><b>0.5</b> My Philosophy for This Book</a>
<ul>
<li class="chapter" data-level="0.5.1" data-path="index.html"><a href="index.html#rationalerpref"><i class="fa fa-check"></i><b>0.5.1</b> Rationale for Using R</a></li>
<li class="chapter" data-level="0.5.2" data-path="index.html"><a href="index.html#audiencepref"><i class="fa fa-check"></i><b>0.5.2</b> Audience</a></li>
</ul></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#structurepref"><i class="fa fa-check"></i><b>0.6</b> Structure</a></li>
<li class="chapter" data-level="0.7" data-path="index.html"><a href="index.html#aboutauthor"><i class="fa fa-check"></i><b>0.7</b> About the Author</a></li>
<li class="chapter" data-level="0.8" data-path="index.html"><a href="index.html#contactauthor"><i class="fa fa-check"></i><b>0.8</b> Contacting the Author</a></li>
<li class="chapter" data-level="0.9" data-path="index.html"><a href="index.html#acknowpref"><i class="fa fa-check"></i><b>0.9</b> Acknowledgements</a></li>
</ul></li>
<li class="part"><span><b>I HR Analytics Project Life Cycle</b></span></li>
<li class="chapter" data-level="1" data-path="overviewhraplc.html"><a href="overviewhraplc.html"><i class="fa fa-check"></i><b>1</b> Overview of HR Analytics Project Life Cycle</a></li>
<li class="chapter" data-level="2" data-path="questionformulation.html"><a href="questionformulation.html"><i class="fa fa-check"></i><b>2</b> Question Formulation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="questionformulation.html"><a href="questionformulation.html#adoptstrategicmindset"><i class="fa fa-check"></i><b>2.1</b> Adopting a Strategic Mindset</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="questionformulation.html"><a href="questionformulation.html#strategy"><i class="fa fa-check"></i><b>2.1.1</b> Strategy</a></li>
<li class="chapter" data-level="2.1.2" data-path="questionformulation.html"><a href="questionformulation.html#strategyformulation"><i class="fa fa-check"></i><b>2.1.2</b> Strategy Formulation</a></li>
<li class="chapter" data-level="2.1.3" data-path="questionformulation.html"><a href="questionformulation.html#strategyimplementation"><i class="fa fa-check"></i><b>2.1.3</b> Strategy Implementation</a></li>
<li class="chapter" data-level="2.1.4" data-path="questionformulation.html"><a href="questionformulation.html#strategichrm"><i class="fa fa-check"></i><b>2.1.4</b> Strategic Human Resource Management</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="questionformulation.html"><a href="questionformulation.html#defining-problems-formulating-questions"><i class="fa fa-check"></i><b>2.2</b> Defining Problems &amp; Formulating Questions</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="questionformulation.html"><a href="questionformulation.html#definingaproblem"><i class="fa fa-check"></i><b>2.2.1</b> Defining a Problem</a></li>
<li class="chapter" data-level="2.2.2" data-path="questionformulation.html"><a href="questionformulation.html#formulatingaquestion"><i class="fa fa-check"></i><b>2.2.2</b> Formulating a Question</a></li>
<li class="chapter" data-level="2.2.3" data-path="questionformulation.html"><a href="questionformulation.html#divergentconvergentthinking"><i class="fa fa-check"></i><b>2.2.3</b> Thinking Divergently &amp; Convergently</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="questionformulation.html"><a href="questionformulation.html#summary"><i class="fa fa-check"></i><b>2.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dataacquisition.html"><a href="dataacquisition.html"><i class="fa fa-check"></i><b>3</b> Data Acquisition</a>
<ul>
<li class="chapter" data-level="3.1" data-path="dataacquisition.html"><a href="dataacquisition.html#employee-surveys"><i class="fa fa-check"></i><b>3.1</b> Employee Surveys</a></li>
<li class="chapter" data-level="3.2" data-path="dataacquisition.html"><a href="dataacquisition.html#rating-forms"><i class="fa fa-check"></i><b>3.2</b> Rating Forms</a></li>
<li class="chapter" data-level="3.3" data-path="dataacquisition.html"><a href="dataacquisition.html#surveillance-monitoring"><i class="fa fa-check"></i><b>3.3</b> Surveillance &amp; Monitoring</a></li>
<li class="chapter" data-level="3.4" data-path="dataacquisition.html"><a href="dataacquisition.html#database-queries"><i class="fa fa-check"></i><b>3.4</b> Database Queries</a></li>
<li class="chapter" data-level="3.5" data-path="dataacquisition.html"><a href="dataacquisition.html#scraping"><i class="fa fa-check"></i><b>3.5</b> Scraping</a></li>
<li class="chapter" data-level="3.6" data-path="dataacquisition.html"><a href="dataacquisition.html#summary-1"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="datamanagement.html"><a href="datamanagement.html"><i class="fa fa-check"></i><b>4</b> Data Management</a>
<ul>
<li class="chapter" data-level="4.1" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_clean"><i class="fa fa-check"></i><b>4.1</b> Data Cleaning</a></li>
<li class="chapter" data-level="4.2" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_manipulate"><i class="fa fa-check"></i><b>4.2</b> Data Manipulation &amp; Structuring</a></li>
<li class="chapter" data-level="4.3" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_tools"><i class="fa fa-check"></i><b>4.3</b> Common Data-Management Tools</a></li>
<li class="chapter" data-level="4.4" data-path="datamanagement.html"><a href="datamanagement.html#summary-2"><i class="fa fa-check"></i><b>4.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dataanalysis.html"><a href="dataanalysis.html"><i class="fa fa-check"></i><b>5</b> Data Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="dataanalysis.html"><a href="dataanalysis.html#dataanalysis_toolstechniques"><i class="fa fa-check"></i><b>5.1</b> Tools &amp; Techniques</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="dataanalysis.html"><a href="dataanalysis.html#mathematics"><i class="fa fa-check"></i><b>5.1.1</b> Mathematics</a></li>
<li class="chapter" data-level="5.1.2" data-path="dataanalysis.html"><a href="dataanalysis.html#statistics"><i class="fa fa-check"></i><b>5.1.2</b> Statistics</a></li>
<li class="chapter" data-level="5.1.3" data-path="dataanalysis.html"><a href="dataanalysis.html#machinelearning"><i class="fa fa-check"></i><b>5.1.3</b> Machine Learning</a></li>
<li class="chapter" data-level="5.1.4" data-path="dataanalysis.html"><a href="dataanalysis.html#computationalmodelsimulation"><i class="fa fa-check"></i><b>5.1.4</b> Computational Modeling &amp; Simulations</a></li>
<li class="chapter" data-level="5.1.5" data-path="dataanalysis.html"><a href="dataanalysis.html#textqualitativeanalyses"><i class="fa fa-check"></i><b>5.1.5</b> Text Analyses &amp; Qualitative Analyses</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="dataanalysis.html"><a href="dataanalysis.html#continuum_dataanalytics"><i class="fa fa-check"></i><b>5.2</b> Continuum of Data Analytics</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="dataanalysis.html"><a href="dataanalysis.html#descriptive_analytics"><i class="fa fa-check"></i><b>5.2.1</b> Descriptive Analytics</a></li>
<li class="chapter" data-level="5.2.2" data-path="dataanalysis.html"><a href="dataanalysis.html#predictish_analytics"><i class="fa fa-check"></i><b>5.2.2</b> Predict-ish Analytics</a></li>
<li class="chapter" data-level="5.2.3" data-path="dataanalysis.html"><a href="dataanalysis.html#predictive_analytics"><i class="fa fa-check"></i><b>5.2.3</b> Predictive Analytics</a></li>
<li class="chapter" data-level="5.2.4" data-path="dataanalysis.html"><a href="dataanalysis.html#prescriptive_analytics"><i class="fa fa-check"></i><b>5.2.4</b> Prescriptive Analytics</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="dataanalysis.html"><a href="dataanalysis.html#summary-3"><i class="fa fa-check"></i><b>5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html"><i class="fa fa-check"></i><b>6</b> Data Interpretation &amp; Storytelling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#datainterpretation"><i class="fa fa-check"></i><b>6.1</b> Data Interpretation</a></li>
<li class="chapter" data-level="6.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling"><i class="fa fa-check"></i><b>6.2</b> Storytelling</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#structure"><i class="fa fa-check"></i><b>6.2.1</b> Structure</a></li>
<li class="chapter" data-level="6.2.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#clarity-parsimony"><i class="fa fa-check"></i><b>6.2.2</b> Clarity &amp; Parsimony</a></li>
<li class="chapter" data-level="6.2.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#influence-persuasion"><i class="fa fa-check"></i><b>6.2.3</b> Influence &amp; Persuasion</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling_withdata"><i class="fa fa-check"></i><b>6.3</b> Storytelling with Data</a></li>
<li class="chapter" data-level="6.4" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#summary-4"><i class="fa fa-check"></i><b>6.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html"><i class="fa fa-check"></i><b>7</b> Deployment &amp; Implementation</a></li>
<li class="part"><span><b>II Introduction to R</b></span></li>
<li class="chapter" data-level="8" data-path="overviewR.html"><a href="overviewR.html"><i class="fa fa-check"></i><b>8</b> Overview of R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="8.1" data-path="overviewR.html"><a href="overviewR.html#R_overview"><i class="fa fa-check"></i><b>8.1</b> R Programming Language</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="overviewR.html"><a href="overviewR.html#R_what"><i class="fa fa-check"></i><b>8.1.1</b> What Is R?</a></li>
<li class="chapter" data-level="8.1.2" data-path="overviewR.html"><a href="overviewR.html#R_why"><i class="fa fa-check"></i><b>8.1.2</b> Why Use R?</a></li>
<li class="chapter" data-level="8.1.3" data-path="overviewR.html"><a href="overviewR.html#R_who"><i class="fa fa-check"></i><b>8.1.3</b> Who Uses R?</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="overviewR.html"><a href="overviewR.html#RStudio_overview"><i class="fa fa-check"></i><b>8.2</b> RStudio</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="overviewR.html"><a href="overviewR.html#RStudio_what"><i class="fa fa-check"></i><b>8.2.1</b> What is RStudio?</a></li>
<li class="chapter" data-level="8.2.2" data-path="overviewR.html"><a href="overviewR.html#RStudio_why"><i class="fa fa-check"></i><b>8.2.2</b> Why RStudio?</a></li>
<li class="chapter" data-level="8.2.3" data-path="overviewR.html"><a href="overviewR.html#RStudio_who"><i class="fa fa-check"></i><b>8.2.3</b> Who Uses RStudio?</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="overviewR.html"><a href="overviewR.html#packages_overview"><i class="fa fa-check"></i><b>8.3</b> Packages</a></li>
<li class="chapter" data-level="8.4" data-path="overviewR.html"><a href="overviewR.html#summary-5"><i class="fa fa-check"></i><b>8.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>9</b> Installing R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="9.1" data-path="install.html"><a href="install.html#videotutorial_install"><i class="fa fa-check"></i><b>9.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="9.2" data-path="install.html"><a href="install.html#installR"><i class="fa fa-check"></i><b>9.2</b> Downloading &amp; Installing R</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="install.html"><a href="install.html#installR_windows"><i class="fa fa-check"></i><b>9.2.1</b> For Windows Operation Systems</a></li>
<li class="chapter" data-level="9.2.2" data-path="install.html"><a href="install.html#installR_macos"><i class="fa fa-check"></i><b>9.2.2</b> For Mac Operating Systems</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="install.html"><a href="install.html#installRStudio"><i class="fa fa-check"></i><b>9.3</b> Downloading &amp; Installing RStudio</a></li>
<li class="chapter" data-level="9.4" data-path="install.html"><a href="install.html#summary_install"><i class="fa fa-check"></i><b>9.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="gettingstarted.html"><a href="gettingstarted.html"><i class="fa fa-check"></i><b>10</b> Getting Started with R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="10.1" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation_gettingstarted"><i class="fa fa-check"></i><b>10.1</b> Orientation to RStudio</a></li>
<li class="chapter" data-level="10.2" data-path="gettingstarted.html"><a href="gettingstarted.html#createRscript"><i class="fa fa-check"></i><b>10.2</b> Creating &amp; Saving an R Script</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="gettingstarted.html"><a href="gettingstarted.html#createnewRscript_gettingstarted"><i class="fa fa-check"></i><b>10.2.1</b> Creating a New R Script</a></li>
<li class="chapter" data-level="10.2.2" data-path="gettingstarted.html"><a href="gettingstarted.html#usenewRscript_gettingstarted"><i class="fa fa-check"></i><b>10.2.2</b> Using an R Script</a></li>
<li class="chapter" data-level="10.2.3" data-path="gettingstarted.html"><a href="gettingstarted.html#saveRscript_gettingstarted"><i class="fa fa-check"></i><b>10.2.3</b> Saving an R Script</a></li>
<li class="chapter" data-level="10.2.4" data-path="gettingstarted.html"><a href="gettingstarted.html#openRscript_gettingstarted"><i class="fa fa-check"></i><b>10.2.4</b> Opening a Saved R Script</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="gettingstarted.html"><a href="gettingstarted.html#RStudioproject_gettingstarted"><i class="fa fa-check"></i><b>10.3</b> Creating an RStudio Project</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="gettingstarted.html"><a href="gettingstarted.html#createRStudioproject_gettingstarted"><i class="fa fa-check"></i><b>10.3.1</b> Creating a New RStudio Project</a></li>
<li class="chapter" data-level="10.3.2" data-path="gettingstarted.html"><a href="gettingstarted.html#openRStudioproject_gettingstarted"><i class="fa fa-check"></i><b>10.3.2</b> Opening an Existing RStudio Project</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="gettingstarted.html"><a href="gettingstarted.html#writtentutorials_gettingstarted"><i class="fa fa-check"></i><b>10.4</b> Orientation to Written Tutorials</a></li>
<li class="chapter" data-level="10.5" data-path="gettingstarted.html"><a href="gettingstarted.html#summary_gettingstarted"><i class="fa fa-check"></i><b>10.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="gentleintro.html"><a href="gentleintro.html"><i class="fa fa-check"></i><b>11</b> Basic Features and Operations of the R Language</a>
<ul>
<li class="chapter" data-level="11.1" data-path="gentleintro.html"><a href="gentleintro.html#videotutorial_gentleintro"><i class="fa fa-check"></i><b>11.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="11.2" data-path="gentleintro.html"><a href="gentleintro.html#functions_gentleintro"><i class="fa fa-check"></i><b>11.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="11.3" data-path="gentleintro.html"><a href="gentleintro.html#r_as_calculator"><i class="fa fa-check"></i><b>11.3</b> R as a Calculator</a></li>
<li class="chapter" data-level="11.4" data-path="gentleintro.html"><a href="gentleintro.html#functions"><i class="fa fa-check"></i><b>11.4</b> Functions</a></li>
<li class="chapter" data-level="11.5" data-path="gentleintro.html"><a href="gentleintro.html#packages"><i class="fa fa-check"></i><b>11.5</b> Packages</a></li>
<li class="chapter" data-level="11.6" data-path="gentleintro.html"><a href="gentleintro.html#variableassignment"><i class="fa fa-check"></i><b>11.6</b> Variable Assignment</a></li>
<li class="chapter" data-level="11.7" data-path="gentleintro.html"><a href="gentleintro.html#typesofdata"><i class="fa fa-check"></i><b>11.7</b> Types of Data</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="gentleintro.html"><a href="gentleintro.html#numeric-data"><i class="fa fa-check"></i><b>11.7.1</b> <code>numeric</code> Data</a></li>
<li class="chapter" data-level="11.7.2" data-path="gentleintro.html"><a href="gentleintro.html#character-data"><i class="fa fa-check"></i><b>11.7.2</b> <code>character</code> Data</a></li>
<li class="chapter" data-level="11.7.3" data-path="gentleintro.html"><a href="gentleintro.html#date-data"><i class="fa fa-check"></i><b>11.7.3</b> <code>Date</code> Data</a></li>
<li class="chapter" data-level="11.7.4" data-path="gentleintro.html"><a href="gentleintro.html#logical-data"><i class="fa fa-check"></i><b>11.7.4</b> <code>logical</code> Data</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="gentleintro.html"><a href="gentleintro.html#vectors"><i class="fa fa-check"></i><b>11.8</b> Vectors</a></li>
<li class="chapter" data-level="11.9" data-path="gentleintro.html"><a href="gentleintro.html#lists"><i class="fa fa-check"></i><b>11.9</b> Lists</a></li>
<li class="chapter" data-level="11.10" data-path="gentleintro.html"><a href="gentleintro.html#dataframes"><i class="fa fa-check"></i><b>11.10</b> Data Frames</a></li>
<li class="chapter" data-level="11.11" data-path="gentleintro.html"><a href="gentleintro.html#annotate"><i class="fa fa-check"></i><b>11.11</b> Annotations</a></li>
<li class="chapter" data-level="11.12" data-path="gentleintro.html"><a href="gentleintro.html#summary_gentleintro"><i class="fa fa-check"></i><b>11.12</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="setwd.html"><a href="setwd.html"><i class="fa fa-check"></i><b>12</b> Setting a Working Directory</a>
<ul>
<li class="chapter" data-level="12.1" data-path="setwd.html"><a href="setwd.html#videotutorial_setwd"><i class="fa fa-check"></i><b>12.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="12.2" data-path="setwd.html"><a href="setwd.html#functions_setwd"><i class="fa fa-check"></i><b>12.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="12.3" data-path="setwd.html"><a href="setwd.html#getwd_setwd"><i class="fa fa-check"></i><b>12.3</b> Identify the Current Working Directory</a></li>
<li class="chapter" data-level="12.4" data-path="setwd.html"><a href="setwd.html#setwd_setwd"><i class="fa fa-check"></i><b>12.4</b> Set a New Working Directory</a></li>
<li class="chapter" data-level="12.5" data-path="setwd.html"><a href="setwd.html#summary_setwd"><i class="fa fa-check"></i><b>12.5</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>III Data Acquisition &amp; Management</b></span></li>
<li class="chapter" data-level="13" data-path="read.html"><a href="read.html"><i class="fa fa-check"></i><b>13</b> Reading Data into R</a>
<ul>
<li class="chapter" data-level="13.1" data-path="read.html"><a href="read.html#conceptualoverview_read"><i class="fa fa-check"></i><b>13.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="13.2" data-path="read.html"><a href="read.html#tutorial_read"><i class="fa fa-check"></i><b>13.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="read.html"><a href="read.html#videotutorial_read"><i class="fa fa-check"></i><b>13.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="13.2.2" data-path="read.html"><a href="read.html#functions_read"><i class="fa fa-check"></i><b>13.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="13.2.3" data-path="read.html"><a href="read.html#initialsteps_read"><i class="fa fa-check"></i><b>13.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="13.2.4" data-path="read.html"><a href="read.html#readcsv"><i class="fa fa-check"></i><b>13.2.4</b> Read a .csv File</a></li>
<li class="chapter" data-level="13.2.5" data-path="read.html"><a href="read.html#readxlsx"><i class="fa fa-check"></i><b>13.2.5</b> Read a .xlsx File</a></li>
<li class="chapter" data-level="13.2.6" data-path="read.html"><a href="read.html#read_summary"><i class="fa fa-check"></i><b>13.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="read.html"><a href="read.html#read_supplement"><i class="fa fa-check"></i><b>13.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="read.html"><a href="read.html#read_supplement_functions"><i class="fa fa-check"></i><b>13.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="13.3.2" data-path="read.html"><a href="read.html#read_initsteps_supplement"><i class="fa fa-check"></i><b>13.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="13.3.3" data-path="read.html"><a href="read.html#read_additionalfunctions"><i class="fa fa-check"></i><b>13.3.3</b> Additional Functions for Reading a .csv File</a></li>
<li class="chapter" data-level="13.3.4" data-path="read.html"><a href="read.html#read_skiprows"><i class="fa fa-check"></i><b>13.3.4</b> Skip Rows of Data During Read</a></li>
<li class="chapter" data-level="13.3.5" data-path="read.html"><a href="read.html#listdatafiles"><i class="fa fa-check"></i><b>13.3.5</b> List Data File Names in Working Directory</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="addnames.html"><a href="addnames.html"><i class="fa fa-check"></i><b>14</b> Removing, Adding, &amp; Changing Variable Names</a>
<ul>
<li class="chapter" data-level="14.1" data-path="addnames.html"><a href="addnames.html#conceptualoverview_addnames"><i class="fa fa-check"></i><b>14.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="14.2" data-path="addnames.html"><a href="addnames.html#tutorial_addnames"><i class="fa fa-check"></i><b>14.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="addnames.html"><a href="addnames.html#videotutorial_addnames"><i class="fa fa-check"></i><b>14.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="14.2.2" data-path="addnames.html"><a href="addnames.html#function_addnames"><i class="fa fa-check"></i><b>14.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="14.2.3" data-path="addnames.html"><a href="addnames.html#initsteps_addnames"><i class="fa fa-check"></i><b>14.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="14.2.4" data-path="addnames.html"><a href="addnames.html#remove_variablenames"><i class="fa fa-check"></i><b>14.2.4</b> Remove Variable Names from a Data Frame Object</a></li>
<li class="chapter" data-level="14.2.5" data-path="addnames.html"><a href="addnames.html#add_variablenames"><i class="fa fa-check"></i><b>14.2.5</b> Add Variable Names to a Data Frame Object</a></li>
<li class="chapter" data-level="14.2.6" data-path="addnames.html"><a href="addnames.html#change_variablenames"><i class="fa fa-check"></i><b>14.2.6</b> Change Specific Variable Names in a Data Frame Object</a></li>
<li class="chapter" data-level="14.2.7" data-path="addnames.html"><a href="addnames.html#summary_addnames"><i class="fa fa-check"></i><b>14.2.7</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="write.html"><a href="write.html"><i class="fa fa-check"></i><b>15</b> Writing Data from R</a>
<ul>
<li class="chapter" data-level="15.1" data-path="write.html"><a href="write.html#conceptualoverview_write"><i class="fa fa-check"></i><b>15.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="15.2" data-path="write.html"><a href="write.html#tutorial_write"><i class="fa fa-check"></i><b>15.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="write.html"><a href="write.html#videotutorial_write"><i class="fa fa-check"></i><b>15.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="15.2.2" data-path="write.html"><a href="write.html#functions_write"><i class="fa fa-check"></i><b>15.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="15.2.3" data-path="write.html"><a href="write.html#initialsteps_write"><i class="fa fa-check"></i><b>15.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="15.2.4" data-path="write.html"><a href="write.html#write_dataframe"><i class="fa fa-check"></i><b>15.2.4</b> Write Data Frame to Working Directory</a></li>
<li class="chapter" data-level="15.2.5" data-path="write.html"><a href="write.html#write_table"><i class="fa fa-check"></i><b>15.2.5</b> Write Table to Working Directory</a></li>
<li class="chapter" data-level="15.2.6" data-path="write.html"><a href="write.html#summary_write"><i class="fa fa-check"></i><b>15.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>16</b> Arranging (Sorting) Data</a>
<ul>
<li class="chapter" data-level="16.1" data-path="arrange.html"><a href="arrange.html#conceptualoverview_arrange"><i class="fa fa-check"></i><b>16.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="16.2" data-path="arrange.html"><a href="arrange.html#tutorial_arrange"><i class="fa fa-check"></i><b>16.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="arrange.html"><a href="arrange.html#videotutorial_arrange"><i class="fa fa-check"></i><b>16.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="16.2.2" data-path="arrange.html"><a href="arrange.html#functions_arrange"><i class="fa fa-check"></i><b>16.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="16.2.3" data-path="arrange.html"><a href="arrange.html#initsteps_arrange"><i class="fa fa-check"></i><b>16.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="16.2.4" data-path="arrange.html"><a href="arrange.html#arrangebyvalues"><i class="fa fa-check"></i><b>16.2.4</b> Arrange (Sort) Data</a></li>
<li class="chapter" data-level="16.2.5" data-path="arrange.html"><a href="arrange.html#summary_arrange"><i class="fa fa-check"></i><b>16.2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="arrange.html"><a href="arrange.html#arrange_supplement"><i class="fa fa-check"></i><b>16.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="arrange.html"><a href="arrange.html#arrange_supplement_functions"><i class="fa fa-check"></i><b>16.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="16.3.2" data-path="arrange.html"><a href="arrange.html#arrange_initsteps_supplement"><i class="fa fa-check"></i><b>16.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="16.3.3" data-path="arrange.html"><a href="arrange.html#arrange_orderfunction"><i class="fa fa-check"></i><b>16.3.3</b> <code>order</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="join.html"><a href="join.html"><i class="fa fa-check"></i><b>17</b> Joining (Merging) Data</a>
<ul>
<li class="chapter" data-level="17.1" data-path="join.html"><a href="join.html#conceptualoverview_join"><i class="fa fa-check"></i><b>17.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="join.html"><a href="join.html#review_horizontaljoin"><i class="fa fa-check"></i><b>17.1.1</b> Review of Horizontal Joins (Merges)</a></li>
<li class="chapter" data-level="17.1.2" data-path="join.html"><a href="join.html#review_verticaljoin"><i class="fa fa-check"></i><b>17.1.2</b> Review of Vertical Joins (Merges)</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="join.html"><a href="join.html#tutorial_join"><i class="fa fa-check"></i><b>17.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="join.html"><a href="join.html#videotutorial_join"><i class="fa fa-check"></i><b>17.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="17.2.2" data-path="join.html"><a href="join.html#functions-packages-introduced"><i class="fa fa-check"></i><b>17.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="17.2.3" data-path="join.html"><a href="join.html#initsteps_join"><i class="fa fa-check"></i><b>17.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="17.2.4" data-path="join.html"><a href="join.html#horizontaljoin"><i class="fa fa-check"></i><b>17.2.4</b> Horizontal Join (Merge)</a></li>
<li class="chapter" data-level="17.2.5" data-path="join.html"><a href="join.html#verticaljoin"><i class="fa fa-check"></i><b>17.2.5</b> Vertical Join (Merge)</a></li>
<li class="chapter" data-level="17.2.6" data-path="join.html"><a href="join.html#summary_join"><i class="fa fa-check"></i><b>17.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="join.html"><a href="join.html#join_supplement"><i class="fa fa-check"></i><b>17.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="join.html"><a href="join.html#supp_join_video"><i class="fa fa-check"></i><b>17.3.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="17.3.2" data-path="join.html"><a href="join.html#join_supplement_functions"><i class="fa fa-check"></i><b>17.3.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="17.3.3" data-path="join.html"><a href="join.html#join_initsteps_supplement"><i class="fa fa-check"></i><b>17.3.3</b> Initial Steps</a></li>
<li class="chapter" data-level="17.3.4" data-path="join.html"><a href="join.html#join_mergefunction"><i class="fa fa-check"></i><b>17.3.4</b> <code>merge</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>18</b> Filtering (Subsetting) Data</a>
<ul>
<li class="chapter" data-level="18.1" data-path="filter.html"><a href="filter.html#conceptualoverview_filter"><i class="fa fa-check"></i><b>18.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="18.1.1" data-path="filter.html"><a href="filter.html#review_logicaloperators"><i class="fa fa-check"></i><b>18.1.1</b> Review of Logical Operators</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="filter.html"><a href="filter.html#tutorial_filter"><i class="fa fa-check"></i><b>18.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="filter.html"><a href="filter.html#videotutorial_filter"><i class="fa fa-check"></i><b>18.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="18.2.2" data-path="filter.html"><a href="filter.html#function_filter"><i class="fa fa-check"></i><b>18.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="18.2.3" data-path="filter.html"><a href="filter.html#initsteps_filter"><i class="fa fa-check"></i><b>18.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="18.2.4" data-path="filter.html"><a href="filter.html#filter_cases"><i class="fa fa-check"></i><b>18.2.4</b> Filter Cases from Data Frame</a></li>
<li class="chapter" data-level="18.2.5" data-path="filter.html"><a href="filter.html#remove-single-variable-from-data-frame"><i class="fa fa-check"></i><b>18.2.5</b> Remove Single Variable from Data Frame</a></li>
<li class="chapter" data-level="18.2.6" data-path="filter.html"><a href="filter.html#select_multiplevariables"><i class="fa fa-check"></i><b>18.2.6</b> Select Multiple Variables from Data Frame</a></li>
<li class="chapter" data-level="18.2.7" data-path="filter.html"><a href="filter.html#remove_multiplevariables"><i class="fa fa-check"></i><b>18.2.7</b> Remove Multiple Variables from Data Frame</a></li>
<li class="chapter" data-level="18.2.8" data-path="filter.html"><a href="filter.html#summary_filter"><i class="fa fa-check"></i><b>18.2.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="filter.html"><a href="filter.html#filter_supplement"><i class="fa fa-check"></i><b>18.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="filter.html"><a href="filter.html#supp_filter_video"><i class="fa fa-check"></i><b>18.3.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="18.3.2" data-path="filter.html"><a href="filter.html#filter_supplement_functions"><i class="fa fa-check"></i><b>18.3.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="18.3.3" data-path="filter.html"><a href="filter.html#filter_initsteps_supplement"><i class="fa fa-check"></i><b>18.3.3</b> Initial Steps</a></li>
<li class="chapter" data-level="18.3.4" data-path="filter.html"><a href="filter.html#filter_subset_supplement"><i class="fa fa-check"></i><b>18.3.4</b> <code>subset</code> Function from Base R</a></li>
<li class="chapter" data-level="18.3.5" data-path="filter.html"><a href="filter.html#str_detect_supp"><i class="fa fa-check"></i><b>18.3.5</b> Filter by Pattern Contained within String</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="clean.html"><a href="clean.html"><i class="fa fa-check"></i><b>19</b> Cleaning Data</a>
<ul>
<li class="chapter" data-level="19.1" data-path="clean.html"><a href="clean.html#conceptualoverview_clean"><i class="fa fa-check"></i><b>19.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="19.2" data-path="clean.html"><a href="clean.html#tutorial_clean"><i class="fa fa-check"></i><b>19.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="clean.html"><a href="clean.html#videotutorial_clean"><i class="fa fa-check"></i><b>19.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="19.2.2" data-path="clean.html"><a href="clean.html#functions_clean"><i class="fa fa-check"></i><b>19.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="19.2.3" data-path="clean.html"><a href="clean.html#initsteps_clean"><i class="fa fa-check"></i><b>19.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="19.2.4" data-path="clean.html"><a href="clean.html#reviewdata_clean"><i class="fa fa-check"></i><b>19.2.4</b> Review Data</a></li>
<li class="chapter" data-level="19.2.5" data-path="clean.html"><a href="clean.html#cleandata_clean"><i class="fa fa-check"></i><b>19.2.5</b> Clean Data</a></li>
<li class="chapter" data-level="19.2.6" data-path="clean.html"><a href="clean.html#renamevariables_clean"><i class="fa fa-check"></i><b>19.2.6</b> Rename Variables</a></li>
<li class="chapter" data-level="19.2.7" data-path="clean.html"><a href="clean.html#otherapproaches_clean"><i class="fa fa-check"></i><b>19.2.7</b> Other Approaches to Cleaning Data</a></li>
<li class="chapter" data-level="19.2.8" data-path="clean.html"><a href="clean.html#summary_clean"><i class="fa fa-check"></i><b>19.2.8</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="manipulate.html"><a href="manipulate.html"><i class="fa fa-check"></i><b>20</b> Manipulating &amp; Restructuring Data</a>
<ul>
<li class="chapter" data-level="20.1" data-path="manipulate.html"><a href="manipulate.html#conceptualoverview_manipulate"><i class="fa fa-check"></i><b>20.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="20.2" data-path="manipulate.html"><a href="manipulate.html#tutorial_manipulate"><i class="fa fa-check"></i><b>20.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="manipulate.html"><a href="manipulate.html#videotutorial_manipulate"><i class="fa fa-check"></i><b>20.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="20.2.2" data-path="manipulate.html"><a href="manipulate.html#functions_manipulate"><i class="fa fa-check"></i><b>20.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="20.2.3" data-path="manipulate.html"><a href="manipulate.html#initsteps_manipulate"><i class="fa fa-check"></i><b>20.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="20.2.4" data-path="manipulate.html"><a href="manipulate.html#manipulate_widetolong"><i class="fa fa-check"></i><b>20.2.4</b> Wide-to-Long Format Data Manipulation</a></li>
<li class="chapter" data-level="20.2.5" data-path="manipulate.html"><a href="manipulate.html#manipulate_longtowide"><i class="fa fa-check"></i><b>20.2.5</b> Long-to-Wide Format Data Manipulation</a></li>
<li class="chapter" data-level="20.2.6" data-path="manipulate.html"><a href="manipulate.html#summary_manipulate"><i class="fa fa-check"></i><b>20.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="21" data-path="center.html"><a href="center.html"><i class="fa fa-check"></i><b>21</b> Centering &amp; Standardizing Variables</a>
<ul>
<li class="chapter" data-level="21.1" data-path="center.html"><a href="center.html#conceptualoverview_center"><i class="fa fa-check"></i><b>21.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="21.1.1" data-path="center.html"><a href="center.html#review_center"><i class="fa fa-check"></i><b>21.1.1</b> Review of Centering Variables</a></li>
<li class="chapter" data-level="21.1.2" data-path="center.html"><a href="center.html#review_standardize"><i class="fa fa-check"></i><b>21.1.2</b> Review of Standardizing Variables</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="center.html"><a href="center.html#tutorial_center"><i class="fa fa-check"></i><b>21.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="center.html"><a href="center.html#videotutorial_center"><i class="fa fa-check"></i><b>21.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="21.2.2" data-path="center.html"><a href="center.html#functions_center"><i class="fa fa-check"></i><b>21.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="21.2.3" data-path="center.html"><a href="center.html#initsteps_center"><i class="fa fa-check"></i><b>21.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="21.2.4" data-path="center.html"><a href="center.html#grandmean_center"><i class="fa fa-check"></i><b>21.2.4</b> Grand-Mean Center Variables</a></li>
<li class="chapter" data-level="21.2.5" data-path="center.html"><a href="center.html#groupmean_center"><i class="fa fa-check"></i><b>21.2.5</b> Group-Mean Center Variables</a></li>
<li class="chapter" data-level="21.2.6" data-path="center.html"><a href="center.html#standardize_center"><i class="fa fa-check"></i><b>21.2.6</b> Standardize Variables</a></li>
<li class="chapter" data-level="21.2.7" data-path="center.html"><a href="center.html#summary_center"><i class="fa fa-check"></i><b>21.2.7</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="removeobjects.html"><a href="removeobjects.html"><i class="fa fa-check"></i><b>22</b> Removing Objects from the R Environment</a>
<ul>
<li class="chapter" data-level="22.1" data-path="removeobjects.html"><a href="removeobjects.html#conceptualoverview_removeobjects"><i class="fa fa-check"></i><b>22.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="22.2" data-path="removeobjects.html"><a href="removeobjects.html#tutorial_removeobjects"><i class="fa fa-check"></i><b>22.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="22.2.1" data-path="removeobjects.html"><a href="removeobjects.html#videotutorial_removeobjects"><i class="fa fa-check"></i><b>22.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="22.2.2" data-path="removeobjects.html"><a href="removeobjects.html#function_removeobjects"><i class="fa fa-check"></i><b>22.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="22.2.3" data-path="removeobjects.html"><a href="removeobjects.html#initsteps_removeobjects"><i class="fa fa-check"></i><b>22.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="22.2.4" data-path="removeobjects.html"><a href="removeobjects.html#listobjects_removeobjects"><i class="fa fa-check"></i><b>22.2.4</b> List Objects in R Environment</a></li>
<li class="chapter" data-level="22.2.5" data-path="removeobjects.html"><a href="removeobjects.html#removeobjects_removeobjects"><i class="fa fa-check"></i><b>22.2.5</b> Remove Objects from R Environment</a></li>
<li class="chapter" data-level="22.2.6" data-path="removeobjects.html"><a href="removeobjects.html#summary_removeobjects"><i class="fa fa-check"></i><b>22.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Employee Demographics</b></span></li>
<li class="chapter" data-level="23" data-path="employeedemographics.html"><a href="employeedemographics.html"><i class="fa fa-check"></i><b>23</b> Introduction to Employee Demographics</a></li>
<li class="chapter" data-level="24" data-path="descriptives.html"><a href="descriptives.html"><i class="fa fa-check"></i><b>24</b> Describing Employee Demographics Using Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="24.1" data-path="descriptives.html"><a href="descriptives.html#conceptualoverview_descriptives"><i class="fa fa-check"></i><b>24.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="24.1.1" data-path="descriptives.html"><a href="descriptives.html#measurementscales"><i class="fa fa-check"></i><b>24.1.1</b> Review of Measurement Scales</a></li>
<li class="chapter" data-level="24.1.2" data-path="descriptives.html"><a href="descriptives.html#constructs_measures_measurementscales"><i class="fa fa-check"></i><b>24.1.2</b> Constructs, Measures, &amp; Measurement Scales</a></li>
<li class="chapter" data-level="24.1.3" data-path="descriptives.html"><a href="descriptives.html#typesof_descriptivestatistics"><i class="fa fa-check"></i><b>24.1.3</b> Types of Descriptive Statistics</a></li>
<li class="chapter" data-level="24.1.4" data-path="descriptives.html"><a href="descriptives.html#samplewriteup_descriptives"><i class="fa fa-check"></i><b>24.1.4</b> Sample Write-Up</a></li>
</ul></li>
<li class="chapter" data-level="24.2" data-path="descriptives.html"><a href="descriptives.html#tutorial_descriptives"><i class="fa fa-check"></i><b>24.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="24.2.1" data-path="descriptives.html"><a href="descriptives.html#videotutorial_descriptives"><i class="fa fa-check"></i><b>24.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="24.2.2" data-path="descriptives.html"><a href="descriptives.html#functions_descriptives"><i class="fa fa-check"></i><b>24.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="24.2.3" data-path="descriptives.html"><a href="descriptives.html#initsteps_descriptives"><i class="fa fa-check"></i><b>24.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="24.2.4" data-path="descriptives.html"><a href="descriptives.html#determine_measurementscale"><i class="fa fa-check"></i><b>24.2.4</b> Determine the Measurement Scale</a></li>
<li class="chapter" data-level="24.2.5" data-path="descriptives.html"><a href="descriptives.html#describe_nominal_ordinal"><i class="fa fa-check"></i><b>24.2.5</b> Describe Nominal &amp; Ordinal (Categorical) Variables</a></li>
<li class="chapter" data-level="24.2.6" data-path="descriptives.html"><a href="descriptives.html#describe_interval_ratio"><i class="fa fa-check"></i><b>24.2.6</b> Describe Interval &amp; Ratio (Continuous) Variables</a></li>
<li class="chapter" data-level="24.2.7" data-path="descriptives.html"><a href="descriptives.html#summary_descriptives"><i class="fa fa-check"></i><b>24.2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="24.3" data-path="descriptives.html"><a href="descriptives.html#descriptives_supplement"><i class="fa fa-check"></i><b>24.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="24.3.1" data-path="descriptives.html"><a href="descriptives.html#descriptives_supplement_functions"><i class="fa fa-check"></i><b>24.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="24.3.2" data-path="descriptives.html"><a href="descriptives.html#descriptives_initsteps_supplement"><i class="fa fa-check"></i><b>24.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="24.3.3" data-path="descriptives.html"><a href="descriptives.html#descriptives_coefficientofvariation_supplement"><i class="fa fa-check"></i><b>24.3.3</b> Compute Coefficient of Variation (CV)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="25" data-path="crosstabs.html"><a href="crosstabs.html"><i class="fa fa-check"></i><b>25</b> Summarizing Two or More Categorical Variables Using Cross-Tabulations</a>
<ul>
<li class="chapter" data-level="25.1" data-path="crosstabs.html"><a href="crosstabs.html#conceptualoverview_crosstabs"><i class="fa fa-check"></i><b>25.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="25.1.1" data-path="crosstabs.html"><a href="crosstabs.html#review_crosstabs"><i class="fa fa-check"></i><b>25.1.1</b> Review of Cross-Tabulation</a></li>
<li class="chapter" data-level="25.1.2" data-path="crosstabs.html"><a href="crosstabs.html#samplewriteup_crosstabs"><i class="fa fa-check"></i><b>25.1.2</b> Sample Write-Up</a></li>
</ul></li>
<li class="chapter" data-level="25.2" data-path="crosstabs.html"><a href="crosstabs.html#tutorial_crosstabs"><i class="fa fa-check"></i><b>25.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="25.2.1" data-path="crosstabs.html"><a href="crosstabs.html#videotutorial_crosstabs"><i class="fa fa-check"></i><b>25.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="25.2.2" data-path="crosstabs.html"><a href="crosstabs.html#functions_crosstabs"><i class="fa fa-check"></i><b>25.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="25.2.3" data-path="crosstabs.html"><a href="crosstabs.html#initsteps_tables"><i class="fa fa-check"></i><b>25.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="25.2.4" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs"><i class="fa fa-check"></i><b>25.2.4</b> Two-Way Cross-Tabulation</a></li>
<li class="chapter" data-level="25.2.5" data-path="crosstabs.html"><a href="crosstabs.html#threeway_crosstabs"><i class="fa fa-check"></i><b>25.2.5</b> Three-Way Cross-Tabulation</a></li>
<li class="chapter" data-level="25.2.6" data-path="crosstabs.html"><a href="crosstabs.html#summary_crosstabs"><i class="fa fa-check"></i><b>25.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="pivottables.html"><a href="pivottables.html"><i class="fa fa-check"></i><b>26</b> Applying Pivot Tables to Explore Employee Demographic Data</a>
<ul>
<li class="chapter" data-level="26.1" data-path="pivottables.html"><a href="pivottables.html#conceptualoverview_pivottables"><i class="fa fa-check"></i><b>26.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="26.2" data-path="pivottables.html"><a href="pivottables.html#tutorial_pivottables"><i class="fa fa-check"></i><b>26.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="26.2.1" data-path="pivottables.html"><a href="pivottables.html#videotutorial_pivottables"><i class="fa fa-check"></i><b>26.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="26.2.2" data-path="pivottables.html"><a href="pivottables.html#functions_pivottables"><i class="fa fa-check"></i><b>26.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="26.2.3" data-path="pivottables.html"><a href="pivottables.html#initsteps_pivottables"><i class="fa fa-check"></i><b>26.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="26.2.4" data-path="pivottables.html"><a href="pivottables.html#create_pivottables"><i class="fa fa-check"></i><b>26.2.4</b> Create a Pivot Table</a></li>
<li class="chapter" data-level="26.2.5" data-path="pivottables.html"><a href="pivottables.html#summary_pivottables"><i class="fa fa-check"></i><b>26.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V Employee Surveys</b></span></li>
<li class="chapter" data-level="27" data-path="employeesurveys.html"><a href="employeesurveys.html"><i class="fa fa-check"></i><b>27</b> Introduction to Employee Surveys</a></li>
<li class="chapter" data-level="28" data-path="aggregatesegment.html"><a href="aggregatesegment.html"><i class="fa fa-check"></i><b>28</b> Aggregating &amp; Segmenting Employee Survey Data</a>
<ul>
<li class="chapter" data-level="28.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#conceptualoverview_aggregatesegment"><i class="fa fa-check"></i><b>28.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="28.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#tutorial_aggregatesegment"><i class="fa fa-check"></i><b>28.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="28.2.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#videotutorial_aggregatesegment"><i class="fa fa-check"></i><b>28.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="28.2.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#functions_aggregatesegment"><i class="fa fa-check"></i><b>28.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="28.2.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#initsteps_aggregatesegment"><i class="fa fa-check"></i><b>28.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="28.2.4" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup"><i class="fa fa-check"></i><b>28.2.4</b> Counts By Group</a></li>
<li class="chapter" data-level="28.2.5" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup"><i class="fa fa-check"></i><b>28.2.5</b> Measures of Central Tendency and Dispersion By Group</a></li>
<li class="chapter" data-level="28.2.6" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable"><i class="fa fa-check"></i><b>28.2.6</b> Add Variable to Data Frame Containing Aggregated Values</a></li>
<li class="chapter" data-level="28.2.7" data-path="aggregatesegment.html"><a href="aggregatesegment.html#visualize_bygroup"><i class="fa fa-check"></i><b>28.2.7</b> Visualize Data By Group</a></li>
<li class="chapter" data-level="28.2.8" data-path="aggregatesegment.html"><a href="aggregatesegment.html#summary_aggregatesegment"><i class="fa fa-check"></i><b>28.2.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="28.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_supplement"><i class="fa fa-check"></i><b>28.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="28.3.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_supplement_functions"><i class="fa fa-check"></i><b>28.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="28.3.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_initsteps_supplement"><i class="fa fa-check"></i><b>28.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="28.3.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_describeby_supplement"><i class="fa fa-check"></i><b>28.3.3</b> <code>describeBy</code> Function from <code>psych</code> Package</a></li>
<li class="chapter" data-level="28.3.4" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_aggregate_supplement"><i class="fa fa-check"></i><b>28.3.4</b> <code>aggregate</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="29" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html"><i class="fa fa-check"></i><b>29</b> Estimating Internal Consistency Reliability Using Cronbach’s alpha</a>
<ul>
<li class="chapter" data-level="29.1" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#conceptualoverview_cronbachsalpha"><i class="fa fa-check"></i><b>29.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="29.2" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#tutorial_cronbachsalpha"><i class="fa fa-check"></i><b>29.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="29.2.1" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#videotutorial_cronbachsalpha"><i class="fa fa-check"></i><b>29.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="29.2.2" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#functions_cronbachsalpha"><i class="fa fa-check"></i><b>29.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="29.2.3" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#initsteps_cronbachsalpha"><i class="fa fa-check"></i><b>29.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="29.2.4" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#cronbachsalpha_alpha"><i class="fa fa-check"></i><b>29.2.4</b> Compute Cronbach’s alpha</a></li>
<li class="chapter" data-level="29.2.5" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#summary_cronbachsalpha"><i class="fa fa-check"></i><b>29.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="30" data-path="compositevariable.html"><a href="compositevariable.html"><i class="fa fa-check"></i><b>30</b> Creating a Composite Variable Based on a Multi-Item Measure</a>
<ul>
<li class="chapter" data-level="30.1" data-path="compositevariable.html"><a href="compositevariable.html#conceptualoverview_compositevariable"><i class="fa fa-check"></i><b>30.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="30.2" data-path="compositevariable.html"><a href="compositevariable.html#tutorial_compositevariable"><i class="fa fa-check"></i><b>30.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="30.2.1" data-path="compositevariable.html"><a href="compositevariable.html#videotutorial_compositevariable"><i class="fa fa-check"></i><b>30.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="30.2.2" data-path="compositevariable.html"><a href="compositevariable.html#functions_compositevariable"><i class="fa fa-check"></i><b>30.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="30.2.3" data-path="compositevariable.html"><a href="compositevariable.html#initsteps_compositevariable"><i class="fa fa-check"></i><b>30.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="30.2.4" data-path="compositevariable.html"><a href="compositevariable.html#compositevariable_cronbachsalpha"><i class="fa fa-check"></i><b>30.2.4</b> Compute Cronbach’s alpha</a></li>
<li class="chapter" data-level="30.2.5" data-path="compositevariable.html"><a href="compositevariable.html#compositevariable_composite"><i class="fa fa-check"></i><b>30.2.5</b> Create a Composite Variable</a></li>
<li class="chapter" data-level="30.2.6" data-path="compositevariable.html"><a href="compositevariable.html#summary_compositevariable"><i class="fa fa-check"></i><b>30.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VI Employee Training</b></span></li>
<li class="chapter" data-level="31" data-path="employeetraining.html"><a href="employeetraining.html"><i class="fa fa-check"></i><b>31</b> Introduction to Employee Training</a>
<ul>
<li class="chapter" data-level="31.1" data-path="employeetraining.html"><a href="employeetraining.html#trainingevaluation_employeetraining"><i class="fa fa-check"></i><b>31.1</b> Training Evaluation</a></li>
</ul></li>
<li class="chapter" data-level="32" data-path="pretestposttest.html"><a href="pretestposttest.html"><i class="fa fa-check"></i><b>32</b> Evaluating a Pre-Test/Post-Test without Control Group Design Using Paired-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="32.1" data-path="pretestposttest.html"><a href="pretestposttest.html#conceptualoverview_pretestposttest_psttest"><i class="fa fa-check"></i><b>32.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="32.1.1" data-path="pretestposttest.html"><a href="pretestposttest.html#review_pretestposttest"><i class="fa fa-check"></i><b>32.1.1</b> Review of Pre-Test/Post-Test without Control Group Design</a></li>
<li class="chapter" data-level="32.1.2" data-path="pretestposttest.html"><a href="pretestposttest.html#review_psttest"><i class="fa fa-check"></i><b>32.1.2</b> Review of Paired-Samples <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="32.2" data-path="pretestposttest.html"><a href="pretestposttest.html#tutorial_psttest"><i class="fa fa-check"></i><b>32.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="32.2.1" data-path="pretestposttest.html"><a href="pretestposttest.html#videotutorial_psttest"><i class="fa fa-check"></i><b>32.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="32.2.2" data-path="pretestposttest.html"><a href="pretestposttest.html#functions_psttest"><i class="fa fa-check"></i><b>32.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="32.2.3" data-path="pretestposttest.html"><a href="pretestposttest.html#initsteps_psttest"><i class="fa fa-check"></i><b>32.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="32.2.4" data-path="pretestposttest.html"><a href="pretestposttest.html#estimate_psttest"><i class="fa fa-check"></i><b>32.2.4</b> Estimate Paired-Samples <em>t</em>-test</a></li>
<li class="chapter" data-level="32.2.5" data-path="pretestposttest.html"><a href="pretestposttest.html#barchart_psttest"><i class="fa fa-check"></i><b>32.2.5</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="32.2.6" data-path="pretestposttest.html"><a href="pretestposttest.html#summary_psttest"><i class="fa fa-check"></i><b>32.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="32.3" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_supplement"><i class="fa fa-check"></i><b>32.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="32.3.1" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_supplement_functions"><i class="fa fa-check"></i><b>32.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="32.3.2" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_initsteps_supplement"><i class="fa fa-check"></i><b>32.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="32.3.3" data-path="pretestposttest.html"><a href="pretestposttest.html#t.test_function_psttest"><i class="fa fa-check"></i><b>32.3.3</b> <code>t.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="33" data-path="posttestonly.html"><a href="posttestonly.html"><i class="fa fa-check"></i><b>33</b> Evaluating a Post-Test-Only with Control Group Design Using Independent-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="33.1" data-path="posttestonly.html"><a href="posttestonly.html#conceptualoverview_posttestonly_isttest"><i class="fa fa-check"></i><b>33.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="33.1.1" data-path="posttestonly.html"><a href="posttestonly.html#review_posttestonly"><i class="fa fa-check"></i><b>33.1.1</b> Review of Post-Test-Only with Control Group Design</a></li>
<li class="chapter" data-level="33.1.2" data-path="posttestonly.html"><a href="posttestonly.html#review_isttest"><i class="fa fa-check"></i><b>33.1.2</b> Review of Independent-Samples <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="33.2" data-path="posttestonly.html"><a href="posttestonly.html#tutorial_isttest"><i class="fa fa-check"></i><b>33.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="33.2.1" data-path="posttestonly.html"><a href="posttestonly.html#videotutorial_isttest"><i class="fa fa-check"></i><b>33.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="33.2.2" data-path="posttestonly.html"><a href="posttestonly.html#functions_isttest"><i class="fa fa-check"></i><b>33.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="33.2.3" data-path="posttestonly.html"><a href="posttestonly.html#initsteps_isttest"><i class="fa fa-check"></i><b>33.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="33.2.4" data-path="posttestonly.html"><a href="posttestonly.html#estimate_isttest"><i class="fa fa-check"></i><b>33.2.4</b> Estimate Independent-Samples <em>t</em>-test</a></li>
<li class="chapter" data-level="33.2.5" data-path="posttestonly.html"><a href="posttestonly.html#barchart_isttest"><i class="fa fa-check"></i><b>33.2.5</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="33.2.6" data-path="posttestonly.html"><a href="posttestonly.html#summary_isttest"><i class="fa fa-check"></i><b>33.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="33.3" data-path="posttestonly.html"><a href="posttestonly.html#isttest_supplement"><i class="fa fa-check"></i><b>33.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="33.3.1" data-path="posttestonly.html"><a href="posttestonly.html#isttest_supplement_functions"><i class="fa fa-check"></i><b>33.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="33.3.2" data-path="posttestonly.html"><a href="posttestonly.html#isttest_initsteps_supplement"><i class="fa fa-check"></i><b>33.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="33.3.3" data-path="posttestonly.html"><a href="posttestonly.html#t.test_function_isttest"><i class="fa fa-check"></i><b>33.3.3</b> <code>t.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="34" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html"><i class="fa fa-check"></i><b>34</b> Evaluating a Post-Test-Only with Two Comparison Groups Design Using One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="34.1" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#conceptualoverview_posttestonly_threegroups_onewayanova"><i class="fa fa-check"></i><b>34.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="34.1.1" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#review_posttestonly_threegroups"><i class="fa fa-check"></i><b>34.1.1</b> Review of Post-Test-Only with Two Comparison Groups Design</a></li>
<li class="chapter" data-level="34.1.2" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#review_onewayanova"><i class="fa fa-check"></i><b>34.1.2</b> Review of One-Way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="34.2" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#tutorial_onewayanova"><i class="fa fa-check"></i><b>34.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="34.2.1" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#videotutorial_onewayanova"><i class="fa fa-check"></i><b>34.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="34.2.2" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#functions_onewayanova"><i class="fa fa-check"></i><b>34.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="34.2.3" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#initsteps_onewayanova"><i class="fa fa-check"></i><b>34.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="34.2.4" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#teststatisticalassumptions_onewayanova"><i class="fa fa-check"></i><b>34.2.4</b> Test Statistical Assumptions</a></li>
<li class="chapter" data-level="34.2.5" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#estimate_onewayanova"><i class="fa fa-check"></i><b>34.2.5</b> Estimate One-Way ANOVA</a></li>
<li class="chapter" data-level="34.2.6" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#barchart_onewayanova"><i class="fa fa-check"></i><b>34.2.6</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="34.2.7" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#summary_onewayanova"><i class="fa fa-check"></i><b>34.2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="34.3" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#onewayanova_supplement"><i class="fa fa-check"></i><b>34.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="34.3.1" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#onewayanova_supplement_functions"><i class="fa fa-check"></i><b>34.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="34.3.2" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#onewayanova_initsteps_supplement"><i class="fa fa-check"></i><b>34.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="34.3.3" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#aov_function_onewayanova"><i class="fa fa-check"></i><b>34.3.3</b> <code>aov</code> Function from Base R</a></li>
<li class="chapter" data-level="34.3.4" data-path="posttestonly_threegroups.html"><a href="posttestonly_threegroups.html#apatable_onewayanova"><i class="fa fa-check"></i><b>34.3.4</b> APA-Style Table of Results</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VII Employee Selection</b></span></li>
<li class="chapter" data-level="35" data-path="selection.html"><a href="selection.html"><i class="fa fa-check"></i><b>35</b> Introduction to Employee Selection</a></li>
<li class="chapter" data-level="36" data-path="disparateimpact.html"><a href="disparateimpact.html"><i class="fa fa-check"></i><b>36</b> Investigating Disparate Impact</a>
<ul>
<li class="chapter" data-level="36.1" data-path="disparateimpact.html"><a href="disparateimpact.html#conceptualoverview_disparateimpact"><i class="fa fa-check"></i><b>36.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="36.2" data-path="disparateimpact.html"><a href="disparateimpact.html#tutorial_disparateimpact"><i class="fa fa-check"></i><b>36.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="36.2.1" data-path="disparateimpact.html"><a href="disparateimpact.html#videotutorial_disparateimpact"><i class="fa fa-check"></i><b>36.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="36.2.2" data-path="disparateimpact.html"><a href="disparateimpact.html#functions_disparateimpact"><i class="fa fa-check"></i><b>36.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="36.2.3" data-path="disparateimpact.html"><a href="disparateimpact.html#initsteps_disparateimpact"><i class="fa fa-check"></i><b>36.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="36.2.4" data-path="disparateimpact.html"><a href="disparateimpact.html#fourfifthsrule"><i class="fa fa-check"></i><b>36.2.4</b> 4/5ths Rule</a></li>
<li class="chapter" data-level="36.2.5" data-path="disparateimpact.html"><a href="disparateimpact.html#chisquaretest_disparateimpact"><i class="fa fa-check"></i><b>36.2.5</b> chi-square (<span class="math inline">\(\chi^2\)</span>) Test of Independence</a></li>
<li class="chapter" data-level="36.2.6" data-path="disparateimpact.html"><a href="disparateimpact.html#fisherexacttest"><i class="fa fa-check"></i><b>36.2.6</b> Fisher Exact Test</a></li>
<li class="chapter" data-level="36.2.7" data-path="disparateimpact.html"><a href="disparateimpact.html#zdifference_test_disparateimpact"><i class="fa fa-check"></i><b>36.2.7</b> <span class="math inline">\(Z_{D}\)</span> Test</a></li>
<li class="chapter" data-level="36.2.8" data-path="disparateimpact.html"><a href="disparateimpact.html#z_impactratiotest"><i class="fa fa-check"></i><b>36.2.8</b> <span class="math inline">\(Z_{IR}\)</span> Test</a></li>
<li class="chapter" data-level="36.2.9" data-path="disparateimpact.html"><a href="disparateimpact.html#summary_disparatetreatment"><i class="fa fa-check"></i><b>36.2.9</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="37" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html"><i class="fa fa-check"></i><b>37</b> Estimating Criterion-Related Validity of a Selection Tool Using Correlation</a>
<ul>
<li class="chapter" data-level="37.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#conceptualoverview_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="37.1.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#review_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.1.1</b> Review of Criterion-Related Validity</a></li>
<li class="chapter" data-level="37.1.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#review_correlation"><i class="fa fa-check"></i><b>37.1.2</b> Review of Correlation</a></li>
</ul></li>
<li class="chapter" data-level="37.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#tutorial_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="37.2.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#videotutorial_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="37.2.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#functions_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="37.2.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#initsteps_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="37.2.4" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#scatterplot_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.2.4</b> Visualize Association Using a Scatter Plot</a></li>
<li class="chapter" data-level="37.2.5" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#estimate_correlation"><i class="fa fa-check"></i><b>37.2.5</b> Estimate Correlation</a></li>
<li class="chapter" data-level="37.2.6" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#summary_criterionrelatedvalidity"><i class="fa fa-check"></i><b>37.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="37.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_supplement"><i class="fa fa-check"></i><b>37.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="37.3.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_supplement_functions"><i class="fa fa-check"></i><b>37.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="37.3.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_initsteps_supplement"><i class="fa fa-check"></i><b>37.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="37.3.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#cor_function"><i class="fa fa-check"></i><b>37.3.3</b> <code>cor</code> Function from Base R</a></li>
<li class="chapter" data-level="37.3.4" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#cortest_function"><i class="fa fa-check"></i><b>37.3.4</b> <code>cor.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="38" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html"><i class="fa fa-check"></i><b>38</b> Predicting Criterion Scores Based on Selection Tool Scores Using Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="38.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#conceptualoverview_predictingcriterionscores"><i class="fa fa-check"></i><b>38.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="38.1.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#review_slr"><i class="fa fa-check"></i><b>38.1.1</b> Review of Simple Linear Regression</a></li>
<li class="chapter" data-level="38.1.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#review_prediction_slr"><i class="fa fa-check"></i><b>38.1.2</b> Predicting Future Criterion Scores Using Simple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="38.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#tutorial_predictingcriterionscores"><i class="fa fa-check"></i><b>38.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="38.2.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#videotutorial_predictingcriterionscores"><i class="fa fa-check"></i><b>38.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="38.2.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#functions_predictingcriterionscores"><i class="fa fa-check"></i><b>38.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="38.2.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#initsteps_slr"><i class="fa fa-check"></i><b>38.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="38.2.4" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#estimate_slr"><i class="fa fa-check"></i><b>38.2.4</b> Estimate Simple Linear Regression Model</a></li>
<li class="chapter" data-level="38.2.5" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_slr"><i class="fa fa-check"></i><b>38.2.5</b> Predict Criterion Scores</a></li>
<li class="chapter" data-level="38.2.6" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#summary_predictingcriterionscores"><i class="fa fa-check"></i><b>38.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="38.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_supplement"><i class="fa fa-check"></i><b>38.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="38.3.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_supplement_functions"><i class="fa fa-check"></i><b>38.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="38.3.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_initsteps_supplement"><i class="fa fa-check"></i><b>38.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="38.3.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#lm_function_slr"><i class="fa fa-check"></i><b>38.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="38.3.4" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predict_function_slr"><i class="fa fa-check"></i><b>38.3.4</b> <code>predict</code> Function from Base R</a></li>
<li class="chapter" data-level="38.3.5" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#apatable_slr"><i class="fa fa-check"></i><b>38.3.5</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="39" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html"><i class="fa fa-check"></i><b>39</b> Estimating Incremental Validity of a Selection Tool Using Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="39.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#conceptualoverview_incrementalvalidity"><i class="fa fa-check"></i><b>39.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="39.1.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#review_mlr"><i class="fa fa-check"></i><b>39.1.1</b> Review of Multiple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="39.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#tutorial_incrementalvalidity"><i class="fa fa-check"></i><b>39.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="39.2.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#videotutorial_incrementalvalidity"><i class="fa fa-check"></i><b>39.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="39.2.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#function_incrementalvalidity"><i class="fa fa-check"></i><b>39.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="39.2.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#initsteps_mlr"><i class="fa fa-check"></i><b>39.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="39.2.4" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#estimate_mlr"><i class="fa fa-check"></i><b>39.2.4</b> Estimate Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="39.2.5" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#summary_incrementalvalidity"><i class="fa fa-check"></i><b>39.2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="39.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_supplement"><i class="fa fa-check"></i><b>39.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="39.3.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_supplement_functions"><i class="fa fa-check"></i><b>39.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="39.3.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_initsteps_supplement"><i class="fa fa-check"></i><b>39.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="39.3.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#lm_function_mlr"><i class="fa fa-check"></i><b>39.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="39.3.4" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#apatable_mlr"><i class="fa fa-check"></i><b>39.3.4</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="40" data-path="compensatory.html"><a href="compensatory.html"><i class="fa fa-check"></i><b>40</b> Applying a Compensatory Approach to Selection Decisions Using Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="40.1" data-path="compensatory.html"><a href="compensatory.html#conceptualoverview_compensatory"><i class="fa fa-check"></i><b>40.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="40.1.1" data-path="compensatory.html"><a href="compensatory.html#review_compensatory_mlr"><i class="fa fa-check"></i><b>40.1.1</b> Review of Multiple Linear Regression</a></li>
<li class="chapter" data-level="40.1.2" data-path="compensatory.html"><a href="compensatory.html#review_compensatory"><i class="fa fa-check"></i><b>40.1.2</b> Review of Compensatory Approach</a></li>
</ul></li>
<li class="chapter" data-level="40.2" data-path="compensatory.html"><a href="compensatory.html#tutorial_compensatory"><i class="fa fa-check"></i><b>40.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="40.2.1" data-path="compensatory.html"><a href="compensatory.html#videotutorial_compensatory"><i class="fa fa-check"></i><b>40.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="40.2.2" data-path="compensatory.html"><a href="compensatory.html#function_compensatory"><i class="fa fa-check"></i><b>40.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="40.2.3" data-path="compensatory.html"><a href="compensatory.html#initsteps_compensatory"><i class="fa fa-check"></i><b>40.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="40.2.4" data-path="compensatory.html"><a href="compensatory.html#estimate_compensatory"><i class="fa fa-check"></i><b>40.2.4</b> Estimate Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="40.2.5" data-path="compensatory.html"><a href="compensatory.html#predictcriterionscores_compensatory"><i class="fa fa-check"></i><b>40.2.5</b> Predict Criterion Scores</a></li>
<li class="chapter" data-level="40.2.6" data-path="compensatory.html"><a href="compensatory.html#summary_compensatory"><i class="fa fa-check"></i><b>40.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="40.3" data-path="compensatory.html"><a href="compensatory.html#compensatory_supplement"><i class="fa fa-check"></i><b>40.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="40.3.1" data-path="compensatory.html"><a href="compensatory.html#compensatory_supplement_functions"><i class="fa fa-check"></i><b>40.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="40.3.2" data-path="compensatory.html"><a href="compensatory.html#compensatory_initsteps_supplement"><i class="fa fa-check"></i><b>40.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="40.3.3" data-path="compensatory.html"><a href="compensatory.html#lm_predict_functions_compensatory"><i class="fa fa-check"></i><b>40.3.3</b> <code>lm</code> &amp; <code>predict</code> Functions from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="41" data-path="multiplecutoff.html"><a href="multiplecutoff.html"><i class="fa fa-check"></i><b>41</b> Applying a Noncompensatory Approach to Selection Decisions Using Angoff Method</a>
<ul>
<li class="chapter" data-level="41.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#conceptualoverview_multiplecutoff"><i class="fa fa-check"></i><b>41.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="41.1.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#review_multiplecutoff"><i class="fa fa-check"></i><b>41.1.1</b> Review of Noncompensatory Approach</a></li>
</ul></li>
<li class="chapter" data-level="41.2" data-path="multiplecutoff.html"><a href="multiplecutoff.html#tutorial_multiplecutoff"><i class="fa fa-check"></i><b>41.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="41.2.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#function_multiplecutoff"><i class="fa fa-check"></i><b>41.2.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="41.2.2" data-path="multiplecutoff.html"><a href="multiplecutoff.html#initsteps_multiplecutoff"><i class="fa fa-check"></i><b>41.2.2</b> Initial Steps</a></li>
<li class="chapter" data-level="41.2.3" data-path="multiplecutoff.html"><a href="multiplecutoff.html#createcutoffscores_multiplecutoff"><i class="fa fa-check"></i><b>41.2.3</b> Create Cutoff Scores</a></li>
<li class="chapter" data-level="41.2.4" data-path="multiplecutoff.html"><a href="multiplecutoff.html#applycutoffscores_multiplecutoff"><i class="fa fa-check"></i><b>41.2.4</b> Apply Cutoff Scores to Make Selection Decisions</a></li>
<li class="chapter" data-level="41.2.5" data-path="multiplecutoff.html"><a href="multiplecutoff.html#summary_multiplecutoff"><i class="fa fa-check"></i><b>41.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="42" data-path="differentialprediction.html"><a href="differentialprediction.html"><i class="fa fa-check"></i><b>42</b> Testing for Differential Prediction Using Moderated Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="42.1" data-path="differentialprediction.html"><a href="differentialprediction.html#conceptualoverview_differentialprediction"><i class="fa fa-check"></i><b>42.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="42.1.1" data-path="differentialprediction.html"><a href="differentialprediction.html#review_mmlr"><i class="fa fa-check"></i><b>42.1.1</b> Review of Moderated Multiple Linear Regression</a></li>
<li class="chapter" data-level="42.1.2" data-path="differentialprediction.html"><a href="differentialprediction.html#review_differentialprediction"><i class="fa fa-check"></i><b>42.1.2</b> Review of Differential Prediction</a></li>
</ul></li>
<li class="chapter" data-level="42.2" data-path="differentialprediction.html"><a href="differentialprediction.html#tutorial_differentialprediction"><i class="fa fa-check"></i><b>42.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="42.2.1" data-path="differentialprediction.html"><a href="differentialprediction.html#videotutorial_differentialprediction"><i class="fa fa-check"></i><b>42.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="42.2.2" data-path="differentialprediction.html"><a href="differentialprediction.html#function_mmlr"><i class="fa fa-check"></i><b>42.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="42.2.3" data-path="differentialprediction.html"><a href="differentialprediction.html#initsteps_mmlr"><i class="fa fa-check"></i><b>42.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="42.2.4" data-path="differentialprediction.html"><a href="differentialprediction.html#center_mmlr"><i class="fa fa-check"></i><b>42.2.4</b> Grand-Mean Center Continuous Predictor Variables</a></li>
<li class="chapter" data-level="42.2.5" data-path="differentialprediction.html"><a href="differentialprediction.html#estimate_mmlr"><i class="fa fa-check"></i><b>42.2.5</b> Estimate Moderated Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="42.2.6" data-path="differentialprediction.html"><a href="differentialprediction.html#summary_differentialprediction"><i class="fa fa-check"></i><b>42.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="42.3" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_supplement"><i class="fa fa-check"></i><b>42.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="42.3.1" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_supplement_functions"><i class="fa fa-check"></i><b>42.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="42.3.2" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_initsteps_supplement"><i class="fa fa-check"></i><b>42.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="42.3.3" data-path="differentialprediction.html"><a href="differentialprediction.html#lm_function_mmlr"><i class="fa fa-check"></i><b>42.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="42.3.4" data-path="differentialprediction.html"><a href="differentialprediction.html#apatable_mmlr"><i class="fa fa-check"></i><b>42.3.4</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="43" data-path="crossvalidation.html"><a href="crossvalidation.html"><i class="fa fa-check"></i><b>43</b> Statistically &amp; Empirically Cross-Validating a Selection Tool</a>
<ul>
<li class="chapter" data-level="43.1" data-path="crossvalidation.html"><a href="crossvalidation.html#conceptualoverview_crossvalidation"><i class="fa fa-check"></i><b>43.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="43.1.1" data-path="crossvalidation.html"><a href="crossvalidation.html#review_statistical_crossvalidation"><i class="fa fa-check"></i><b>43.1.1</b> Review of Statistical Cross-Validation</a></li>
<li class="chapter" data-level="43.1.2" data-path="crossvalidation.html"><a href="crossvalidation.html#review_empirical_crossvalidation"><i class="fa fa-check"></i><b>43.1.2</b> Review of Empirical Cross-Validation</a></li>
</ul></li>
<li class="chapter" data-level="43.2" data-path="crossvalidation.html"><a href="crossvalidation.html#tutorial_crossvalidation"><i class="fa fa-check"></i><b>43.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="43.2.1" data-path="crossvalidation.html"><a href="crossvalidation.html#function_crossvalidation"><i class="fa fa-check"></i><b>43.2.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="43.2.2" data-path="crossvalidation.html"><a href="crossvalidation.html#initsteps_crossvalidation"><i class="fa fa-check"></i><b>43.2.2</b> Initial Steps</a></li>
<li class="chapter" data-level="43.2.3" data-path="crossvalidation.html"><a href="crossvalidation.html#crossvalidation_statistical"><i class="fa fa-check"></i><b>43.2.3</b> Perform Statistical Cross-Validation</a></li>
<li class="chapter" data-level="43.2.4" data-path="crossvalidation.html"><a href="crossvalidation.html#crossvalidation_empirical"><i class="fa fa-check"></i><b>43.2.4</b> Perform Empirical Cross-Validation</a></li>
<li class="chapter" data-level="43.2.5" data-path="crossvalidation.html"><a href="crossvalidation.html#summary_crossvalidation"><i class="fa fa-check"></i><b>43.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VIII Employee Separation &amp; Retention</b></span></li>
<li class="chapter" data-level="44" data-path="turnover.html"><a href="turnover.html"><i class="fa fa-check"></i><b>44</b> Introduction to Employee Separation &amp; Retention</a></li>
<li class="chapter" data-level="45" data-path="turnoverrate.html"><a href="turnoverrate.html"><i class="fa fa-check"></i><b>45</b> Computing Monthly &amp; Annual Turnover Rates</a>
<ul>
<li class="chapter" data-level="45.1" data-path="turnoverrate.html"><a href="turnoverrate.html#conceptualoverview_turnoverrate"><i class="fa fa-check"></i><b>45.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="45.2" data-path="turnoverrate.html"><a href="turnoverrate.html#tutorial_turnoverrate"><i class="fa fa-check"></i><b>45.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="45.2.1" data-path="turnoverrate.html"><a href="turnoverrate.html#videotutorial_turnoverrate"><i class="fa fa-check"></i><b>45.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="45.2.2" data-path="turnoverrate.html"><a href="turnoverrate.html#functions_turnoverrate"><i class="fa fa-check"></i><b>45.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="45.2.3" data-path="turnoverrate.html"><a href="turnoverrate.html#initsteps_turnoverrate"><i class="fa fa-check"></i><b>45.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="45.2.4" data-path="turnoverrate.html"><a href="turnoverrate.html#turnoverrate_monthlyturnoverrate"><i class="fa fa-check"></i><b>45.2.4</b> Compute Monthly Turnover Rates</a></li>
<li class="chapter" data-level="45.2.5" data-path="turnoverrate.html"><a href="turnoverrate.html#turnoverrate_annualturnoverrate"><i class="fa fa-check"></i><b>45.2.5</b> Compute Annual Turnover Rate</a></li>
<li class="chapter" data-level="45.2.6" data-path="turnoverrate.html"><a href="turnoverrate.html#summary_turnoverrate"><i class="fa fa-check"></i><b>45.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="46" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html"><i class="fa fa-check"></i><b>46</b> Estimating the Association Between Two Categorical Variables Using Chi-Square (<span class="math inline">\(\chi^2\)</span>) Test of Independence</a>
<ul>
<li class="chapter" data-level="46.1" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#conceptualoverview_turnoverchisquare"><i class="fa fa-check"></i><b>46.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="46.2" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#tutorial_turnoverchisquare"><i class="fa fa-check"></i><b>46.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="46.2.1" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#videotutorial_turnoverchisquare"><i class="fa fa-check"></i><b>46.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="46.2.2" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#functions_turnoverchisquare"><i class="fa fa-check"></i><b>46.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="46.2.3" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#initsteps_turnoverchisquare"><i class="fa fa-check"></i><b>46.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="46.2.4" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#turnoverchisquare_contingencytable"><i class="fa fa-check"></i><b>46.2.4</b> Create a Contingency Table for Observed Data</a></li>
<li class="chapter" data-level="46.2.5" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#turnoverchisquare_chisquare"><i class="fa fa-check"></i><b>46.2.5</b> Estimate Chi-Square (<span class="math inline">\(\chi^2\)</span>) Test of Independence</a></li>
<li class="chapter" data-level="46.2.6" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#summary_turnoverchisquare"><i class="fa fa-check"></i><b>46.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="46.3" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#turnoverchisquare_supplement"><i class="fa fa-check"></i><b>46.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="46.3.1" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#turnoverchisquare_supplement_functions"><i class="fa fa-check"></i><b>46.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="46.3.2" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#turnoverchisquare_initsteps_supplement"><i class="fa fa-check"></i><b>46.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="46.3.3" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#supplement_turnoverchisquare_oddsratio"><i class="fa fa-check"></i><b>46.3.3</b> Compute Odds Ratio for 2x2 Contingency Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="47" data-path="logistic.html"><a href="logistic.html"><i class="fa fa-check"></i><b>47</b> Identifying Predictors of Turnover Using Logistic Regression</a>
<ul>
<li class="chapter" data-level="47.1" data-path="logistic.html"><a href="logistic.html#conceptualoverview_logistic"><i class="fa fa-check"></i><b>47.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="47.1.1" data-path="logistic.html"><a href="logistic.html#review_logistic"><i class="fa fa-check"></i><b>47.1.1</b> Review of Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="47.2" data-path="logistic.html"><a href="logistic.html#tutorial_logistic"><i class="fa fa-check"></i><b>47.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="47.2.1" data-path="logistic.html"><a href="logistic.html#videotutorial_logistic"><i class="fa fa-check"></i><b>47.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="47.2.2" data-path="logistic.html"><a href="logistic.html#functions_logistic"><i class="fa fa-check"></i><b>47.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="47.2.3" data-path="logistic.html"><a href="logistic.html#initsteps_logistic"><i class="fa fa-check"></i><b>47.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="47.2.4" data-path="logistic.html"><a href="logistic.html#estimate_simple_logistic"><i class="fa fa-check"></i><b>47.2.4</b> Estimate Simple Logistic Regression Model</a></li>
<li class="chapter" data-level="47.2.5" data-path="logistic.html"><a href="logistic.html#estimate_multiple_logistic"><i class="fa fa-check"></i><b>47.2.5</b> Estimate Multiple Logistic Regression Model</a></li>
<li class="chapter" data-level="47.2.6" data-path="logistic.html"><a href="logistic.html#summary_logistic"><i class="fa fa-check"></i><b>47.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="47.3" data-path="logistic.html"><a href="logistic.html#logistic_supplement"><i class="fa fa-check"></i><b>47.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="47.3.1" data-path="logistic.html"><a href="logistic.html#logistic_supplement_functions"><i class="fa fa-check"></i><b>47.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="47.3.2" data-path="logistic.html"><a href="logistic.html#logistic_initsteps_supplement"><i class="fa fa-check"></i><b>47.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="47.3.3" data-path="logistic.html"><a href="logistic.html#glm_function_simple_logistic"><i class="fa fa-check"></i><b>47.3.3</b> Simple Logistic Regression Model Using <code>glm</code> Function from Base R</a></li>
<li class="chapter" data-level="47.3.4" data-path="logistic.html"><a href="logistic.html#glm_function_multiple_logistic"><i class="fa fa-check"></i><b>47.3.4</b> Multiple Logistic Regression Using <code>glm</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="48" data-path="kfold.html"><a href="kfold.html"><i class="fa fa-check"></i><b>48</b> Applying <em>k</em>-Fold Cross-Validation to Logistic Regression</a>
<ul>
<li class="chapter" data-level="48.1" data-path="kfold.html"><a href="kfold.html#conceptualoverview_kfold"><i class="fa fa-check"></i><b>48.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="48.1.1" data-path="kfold.html"><a href="kfold.html#review_predictiveanalytics"><i class="fa fa-check"></i><b>48.1.1</b> Review of Predictive Analytics</a></li>
<li class="chapter" data-level="48.1.2" data-path="kfold.html"><a href="kfold.html#review_kfold"><i class="fa fa-check"></i><b>48.1.2</b> Review of <em>k</em>-Fold Cross-Validation</a></li>
<li class="chapter" data-level="48.1.3" data-path="kfold.html"><a href="kfold.html#conceptualvideo_kfold"><i class="fa fa-check"></i><b>48.1.3</b> Conceptual Video</a></li>
</ul></li>
<li class="chapter" data-level="48.2" data-path="kfold.html"><a href="kfold.html#tutorial_kfold"><i class="fa fa-check"></i><b>48.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="48.2.1" data-path="kfold.html"><a href="kfold.html#videotutorial_kfold"><i class="fa fa-check"></i><b>48.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="48.2.2" data-path="kfold.html"><a href="kfold.html#functions_kfold"><i class="fa fa-check"></i><b>48.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="48.2.3" data-path="kfold.html"><a href="kfold.html#initsteps_kfold"><i class="fa fa-check"></i><b>48.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="48.2.4" data-path="kfold.html"><a href="kfold.html#estimate_kfold_logistic"><i class="fa fa-check"></i><b>48.2.4</b> Apply <em>k</em>-Fold Cross-Validation Using Logistic Regression</a></li>
<li class="chapter" data-level="48.2.5" data-path="kfold.html"><a href="kfold.html#summary_kfold"><i class="fa fa-check"></i><b>48.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="49" data-path="survival.html"><a href="survival.html"><i class="fa fa-check"></i><b>49</b> Understanding Length of Service Using Survival Analysis</a>
<ul>
<li class="chapter" data-level="49.1" data-path="survival.html"><a href="survival.html#conceptualoverview_survival"><i class="fa fa-check"></i><b>49.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="49.1.1" data-path="survival.html"><a href="survival.html#review_censoring_survival"><i class="fa fa-check"></i><b>49.1.1</b> Censoring</a></li>
<li class="chapter" data-level="49.1.2" data-path="survival.html"><a href="survival.html#review_types_survival"><i class="fa fa-check"></i><b>49.1.2</b> Types of Survival Analysis</a></li>
<li class="chapter" data-level="49.1.3" data-path="survival.html"><a href="survival.html#conceptualvideo_survival"><i class="fa fa-check"></i><b>49.1.3</b> Conceptual Video</a></li>
</ul></li>
<li class="chapter" data-level="49.2" data-path="survival.html"><a href="survival.html#tutorial_survival"><i class="fa fa-check"></i><b>49.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="49.2.1" data-path="survival.html"><a href="survival.html#videotutorial_survival"><i class="fa fa-check"></i><b>49.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="49.2.2" data-path="survival.html"><a href="survival.html#functions_survival"><i class="fa fa-check"></i><b>49.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="49.2.3" data-path="survival.html"><a href="survival.html#initsteps_survival"><i class="fa fa-check"></i><b>49.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="49.2.4" data-path="survival.html"><a href="survival.html#createcensoring_survival"><i class="fa fa-check"></i><b>49.2.4</b> Create a Censoring Variable</a></li>
<li class="chapter" data-level="49.2.5" data-path="survival.html"><a href="survival.html#inspectlosdistribution_survival"><i class="fa fa-check"></i><b>49.2.5</b> Inspect Distribution of Length of Service</a></li>
<li class="chapter" data-level="49.2.6" data-path="survival.html"><a href="survival.html#conductkmanalysis_lifetable_survival"><i class="fa fa-check"></i><b>49.2.6</b> Conduct Kaplan-Meier Analysis &amp; Create Life Table</a></li>
<li class="chapter" data-level="49.2.7" data-path="survival.html"><a href="survival.html#estimatecox_survival"><i class="fa fa-check"></i><b>49.2.7</b> Estimate Cox Proportional Hazards Model</a></li>
<li class="chapter" data-level="49.2.8" data-path="survival.html"><a href="survival.html#summary_survival"><i class="fa fa-check"></i><b>49.2.8</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IX Employee Performance Management</b></span></li>
<li class="chapter" data-level="50" data-path="performancemanagement.html"><a href="performancemanagement.html"><i class="fa fa-check"></i><b>50</b> Introduction to Employee Performance Management</a></li>
<li class="chapter" data-level="51" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html"><i class="fa fa-check"></i><b>51</b> Evaluating Convergent &amp; Discriminant Validity Using Scatter Plots &amp; Correlations</a>
<ul>
<li class="chapter" data-level="51.1" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#conceptualoverview_convergentdiscriminantvalidity"><i class="fa fa-check"></i><b>51.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="51.1.1" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#review_convergentdiscriminantvalidity"><i class="fa fa-check"></i><b>51.1.1</b> Review of Concurrent &amp; Discriminant Validity</a></li>
<li class="chapter" data-level="51.1.2" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#review_pearson_pointbiserial_correlation"><i class="fa fa-check"></i><b>51.1.2</b> Review of Pearson Product-Moment &amp; Point-Biserial Correlation</a></li>
<li class="chapter" data-level="51.1.3" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#review_bivariatescatterplot"><i class="fa fa-check"></i><b>51.1.3</b> Review of Bivariate Scatter Plot</a></li>
</ul></li>
<li class="chapter" data-level="51.2" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#tutorial_convergentdiscriminantvalidity"><i class="fa fa-check"></i><b>51.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="51.2.1" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#videotutorial_convergentdiscriminantvalidity"><i class="fa fa-check"></i><b>51.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="51.2.2" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#functions_convergentdiscriminantvalidity"><i class="fa fa-check"></i><b>51.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="51.2.3" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#initsteps_convergentdiscriminantvalidity"><i class="fa fa-check"></i><b>51.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="51.2.4" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#bivariatescatterplot_convergentdiscriminantvalidity"><i class="fa fa-check"></i><b>51.2.4</b> Visualize Association Using a Bivariate Scatter Plot</a></li>
<li class="chapter" data-level="51.2.5" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#estimate_correlation_convergentdiscriminantvalidity"><i class="fa fa-check"></i><b>51.2.5</b> Estimate Correlations</a></li>
<li class="chapter" data-level="51.2.6" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#correlationmatrix_convergentdiscriminantvalidity"><i class="fa fa-check"></i><b>51.2.6</b> Create Correlation Matrix</a></li>
<li class="chapter" data-level="51.2.7" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#summary_convergentdiscriminantvalidity"><i class="fa fa-check"></i><b>51.2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="51.3" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#convergentdiscriminantvalidity_supplement"><i class="fa fa-check"></i><b>51.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="51.3.1" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#convergentdiscriminantvalidity_supplement_functions"><i class="fa fa-check"></i><b>51.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="51.3.2" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#convergentdiscriminantvalidity_initsteps_supplement"><i class="fa fa-check"></i><b>51.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="51.3.3" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#shapiro.test_function"><i class="fa fa-check"></i><b>51.3.3</b> <code>shapiro.test</code> Function from Base R</a></li>
<li class="chapter" data-level="51.3.4" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#apatable_correlationmatrix"><i class="fa fa-check"></i><b>51.3.4</b> APA-Style Results Table</a></li>
<li class="chapter" data-level="51.3.5" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#cor.plot_psych_function"><i class="fa fa-check"></i><b>51.3.5</b> <code>cor.plot</code> Function from <code>psych</code> package</a></li>
<li class="chapter" data-level="51.3.6" data-path="convergentdiscriminantvalidity.html"><a href="convergentdiscriminantvalidity.html#corrgram_corrgram_function"><i class="fa fa-check"></i><b>51.3.6</b> <code>corrgram</code> Function from <code>corrgram</code> package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="52" data-path="polynomialregression.html"><a href="polynomialregression.html"><i class="fa fa-check"></i><b>52</b> Investigating Nonlinear Associations Using Polynomial Regression</a>
<ul>
<li class="chapter" data-level="52.1" data-path="polynomialregression.html"><a href="polynomialregression.html#conceptualoverview_polynomialregression"><i class="fa fa-check"></i><b>52.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="52.1.1" data-path="polynomialregression.html"><a href="polynomialregression.html#statisticalassumptions_polynomialregression"><i class="fa fa-check"></i><b>52.1.1</b> Statistical Assumptions</a></li>
<li class="chapter" data-level="52.1.2" data-path="polynomialregression.html"><a href="polynomialregression.html#statisticalsignficance_polynomialregression"><i class="fa fa-check"></i><b>52.1.2</b> Statistical Significance</a></li>
</ul></li>
<li class="chapter" data-level="52.2" data-path="polynomialregression.html"><a href="polynomialregression.html#tutorial_polynomialregression"><i class="fa fa-check"></i><b>52.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="52.2.1" data-path="polynomialregression.html"><a href="polynomialregression.html#functions_polynomialregression"><i class="fa fa-check"></i><b>52.2.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="52.2.2" data-path="polynomialregression.html"><a href="polynomialregression.html#initsteps_polynomialregression"><i class="fa fa-check"></i><b>52.2.2</b> Initial Steps</a></li>
<li class="chapter" data-level="52.2.3" data-path="polynomialregression.html"><a href="polynomialregression.html#bivariatescatterplot_polynomialregression"><i class="fa fa-check"></i><b>52.2.3</b> Visualize Association Using a Bivariate Scatter Plot</a></li>
<li class="chapter" data-level="52.2.4" data-path="polynomialregression.html"><a href="polynomialregression.html#estimate_polynomialregression"><i class="fa fa-check"></i><b>52.2.4</b> Estimate Polynomial Regression Model</a></li>
<li class="chapter" data-level="52.2.5" data-path="polynomialregression.html"><a href="polynomialregression.html#summary_polynomialregression"><i class="fa fa-check"></i><b>52.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="53" data-path="lassoregression.html"><a href="lassoregression.html"><i class="fa fa-check"></i><b>53</b> Supervised Statistical Learning Using Lasso Regression</a>
<ul>
<li class="chapter" data-level="53.1" data-path="lassoregression.html"><a href="lassoregression.html#conceptualoverview_lassoregression"><i class="fa fa-check"></i><b>53.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="53.1.1" data-path="lassoregression.html"><a href="lassoregression.html#shrinkage_lassoregression"><i class="fa fa-check"></i><b>53.1.1</b> Shrinkage</a></li>
<li class="chapter" data-level="53.1.2" data-path="lassoregression.html"><a href="lassoregression.html#regularization_lassoregression"><i class="fa fa-check"></i><b>53.1.2</b> Regularization</a></li>
<li class="chapter" data-level="53.1.3" data-path="lassoregression.html"><a href="lassoregression.html#tuning_lassoregression"><i class="fa fa-check"></i><b>53.1.3</b> Tuning</a></li>
<li class="chapter" data-level="53.1.4" data-path="lassoregression.html"><a href="lassoregression.html#modeltype_selection_lassoregression"><i class="fa fa-check"></i><b>53.1.4</b> Model Type Selection</a></li>
<li class="chapter" data-level="53.1.5" data-path="lassoregression.html"><a href="lassoregression.html#crossvalidation_lassoregression"><i class="fa fa-check"></i><b>53.1.5</b> Cross-Validation</a></li>
<li class="chapter" data-level="53.1.6" data-path="lassoregression.html"><a href="lassoregression.html#predictiveanalytics_lassoregression"><i class="fa fa-check"></i><b>53.1.6</b> Predictive Analytics</a></li>
<li class="chapter" data-level="53.1.7" data-path="lassoregression.html"><a href="lassoregression.html#conceptualvideo_lassoregression"><i class="fa fa-check"></i><b>53.1.7</b> Conceptual Video</a></li>
</ul></li>
<li class="chapter" data-level="53.2" data-path="lassoregression.html"><a href="lassoregression.html#tutorial_lassoregression"><i class="fa fa-check"></i><b>53.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="53.2.1" data-path="lassoregression.html"><a href="lassoregression.html#videotutorial_lassoregression"><i class="fa fa-check"></i><b>53.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="53.2.2" data-path="lassoregression.html"><a href="lassoregression.html#functions_lassoregression"><i class="fa fa-check"></i><b>53.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="53.2.3" data-path="lassoregression.html"><a href="lassoregression.html#initsteps_lassoregression"><i class="fa fa-check"></i><b>53.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="53.2.4" data-path="lassoregression.html"><a href="lassoregression.html#processoverview_lasso"><i class="fa fa-check"></i><b>53.2.4</b> Process Overview</a></li>
<li class="chapter" data-level="53.2.5" data-path="lassoregression.html"><a href="lassoregression.html#partitiondata_lasso"><i class="fa fa-check"></i><b>53.2.5</b> Partition the Data</a></li>
<li class="chapter" data-level="53.2.6" data-path="lassoregression.html"><a href="lassoregression.html#specify-k-fold-cross-validation"><i class="fa fa-check"></i><b>53.2.6</b> Specify <em>k</em>-Fold Cross-Validation</a></li>
<li class="chapter" data-level="53.2.7" data-path="lassoregression.html"><a href="lassoregression.html#trainlasso_lasso"><i class="fa fa-check"></i><b>53.2.7</b> Specify and Train Lasso Regression Model</a></li>
<li class="chapter" data-level="53.2.8" data-path="lassoregression.html"><a href="lassoregression.html#compare_ols_lasso"><i class="fa fa-check"></i><b>53.2.8</b> Optional: Compare to Lasso Model to OLS Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="53.2.9" data-path="lassoregression.html"><a href="lassoregression.html#summary_lasso"><i class="fa fa-check"></i><b>53.2.9</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="54" data-path="pathanalysis.html"><a href="pathanalysis.html"><i class="fa fa-check"></i><b>54</b> Investigating Processes Using Path Analysis</a>
<ul>
<li class="chapter" data-level="54.1" data-path="pathanalysis.html"><a href="pathanalysis.html#conceptualoverview_pathanalysis"><i class="fa fa-check"></i><b>54.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="54.1.1" data-path="pathanalysis.html"><a href="pathanalysis.html#pathdiagram_pathanalysis"><i class="fa fa-check"></i><b>54.1.1</b> Path Diagram</a></li>
<li class="chapter" data-level="54.1.2" data-path="pathanalysis.html"><a href="pathanalysis.html#modelidentification_pathanalysis"><i class="fa fa-check"></i><b>54.1.2</b> Model Identification</a></li>
<li class="chapter" data-level="54.1.3" data-path="pathanalysis.html"><a href="pathanalysis.html#modelfit_pathanalysis"><i class="fa fa-check"></i><b>54.1.3</b> Model Fit</a></li>
<li class="chapter" data-level="54.1.4" data-path="pathanalysis.html"><a href="pathanalysis.html#parameterestimatese_pathanalysis"><i class="fa fa-check"></i><b>54.1.4</b> Parameter Estimates</a></li>
<li class="chapter" data-level="54.1.5" data-path="pathanalysis.html"><a href="pathanalysis.html#statisticalassumptions_pathanalysis"><i class="fa fa-check"></i><b>54.1.5</b> Statistical Assumptions</a></li>
<li class="chapter" data-level="54.1.6" data-path="pathanalysis.html"><a href="pathanalysis.html#conceptualvideo_pathanalysis"><i class="fa fa-check"></i><b>54.1.6</b> Conceptual Video</a></li>
</ul></li>
<li class="chapter" data-level="54.2" data-path="pathanalysis.html"><a href="pathanalysis.html#tutorial_pathanalysis"><i class="fa fa-check"></i><b>54.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="54.2.1" data-path="pathanalysis.html"><a href="pathanalysis.html#videotutorial_pathanalysis"><i class="fa fa-check"></i><b>54.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="54.2.2" data-path="pathanalysis.html"><a href="pathanalysis.html#functions_pathanalysis"><i class="fa fa-check"></i><b>54.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="54.2.3" data-path="pathanalysis.html"><a href="pathanalysis.html#initsteps_pathanalysis"><i class="fa fa-check"></i><b>54.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="54.2.4" data-path="pathanalysis.html"><a href="pathanalysis.html#specifymodel_pathanalysis"><i class="fa fa-check"></i><b>54.2.4</b> Specify &amp; Estimate Path Analysis Models</a></li>
<li class="chapter" data-level="54.2.5" data-path="pathanalysis.html"><a href="pathanalysis.html#additionalinfo_pathanalysis"><i class="fa fa-check"></i><b>54.2.5</b> Additional Information on Model Specification Notation</a></li>
<li class="chapter" data-level="54.2.6" data-path="pathanalysis.html"><a href="pathanalysis.html#summary_pathanalysis"><i class="fa fa-check"></i><b>54.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="55" data-path="mediationanalysis.html"><a href="mediationanalysis.html"><i class="fa fa-check"></i><b>55</b> Estimating a Mediation Model Using Path Analysis</a>
<ul>
<li class="chapter" data-level="55.1" data-path="mediationanalysis.html"><a href="mediationanalysis.html#conceptualoverview_mediationanalysis"><i class="fa fa-check"></i><b>55.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="55.1.1" data-path="mediationanalysis.html"><a href="mediationanalysis.html#indirecteffect_mediationanalysis"><i class="fa fa-check"></i><b>55.1.1</b> Estimation of Indirect Effect</a></li>
<li class="chapter" data-level="55.1.2" data-path="mediationanalysis.html"><a href="mediationanalysis.html#modelidentification_mediationanalysis"><i class="fa fa-check"></i><b>55.1.2</b> Model Identification</a></li>
<li class="chapter" data-level="55.1.3" data-path="mediationanalysis.html"><a href="mediationanalysis.html#modelfit_mediationanalysis"><i class="fa fa-check"></i><b>55.1.3</b> Model Fit</a></li>
<li class="chapter" data-level="55.1.4" data-path="mediationanalysis.html"><a href="mediationanalysis.html#parameterestimatese_mediationanalysis"><i class="fa fa-check"></i><b>55.1.4</b> Parameter Estimates</a></li>
<li class="chapter" data-level="55.1.5" data-path="mediationanalysis.html"><a href="mediationanalysis.html#statisticalassumptions_mediationanalysis"><i class="fa fa-check"></i><b>55.1.5</b> Statistical Assumptions</a></li>
<li class="chapter" data-level="55.1.6" data-path="mediationanalysis.html"><a href="mediationanalysis.html#conceptualvideo_mediationanalysis"><i class="fa fa-check"></i><b>55.1.6</b> Conceptual Video</a></li>
</ul></li>
<li class="chapter" data-level="55.2" data-path="mediationanalysis.html"><a href="mediationanalysis.html#tutorial_mediationanalysis"><i class="fa fa-check"></i><b>55.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="55.2.1" data-path="mediationanalysis.html"><a href="mediationanalysis.html#videotutorial_mediationanalysis"><i class="fa fa-check"></i><b>55.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="55.2.2" data-path="mediationanalysis.html"><a href="mediationanalysis.html#functions_mediationanalysis"><i class="fa fa-check"></i><b>55.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="55.2.3" data-path="mediationanalysis.html"><a href="mediationanalysis.html#initsteps_mediationanalysis"><i class="fa fa-check"></i><b>55.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="55.2.4" data-path="mediationanalysis.html"><a href="mediationanalysis.html#specifymodel_mediationanalysis"><i class="fa fa-check"></i><b>55.2.4</b> Specify &amp; Estimate a Mediation Analysis Model</a></li>
<li class="chapter" data-level="55.2.5" data-path="mediationanalysis.html"><a href="mediationanalysis.html#summary_mediationanalysis"><i class="fa fa-check"></i><b>55.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>X Employee Compensation &amp; Reward Systems</b></span></li>
<li class="chapter" data-level="56" data-path="compensation.html"><a href="compensation.html"><i class="fa fa-check"></i><b>56</b> Introduction to Employee Compensation &amp; Reward Systems</a></li>
<li class="chapter" data-level="57" data-path="marketsurvey.html"><a href="marketsurvey.html"><i class="fa fa-check"></i><b>57</b> Preparing Market Survey Data</a>
<ul>
<li class="chapter" data-level="57.1" data-path="marketsurvey.html"><a href="marketsurvey.html#conceptualoverview_marketsurvey"><i class="fa fa-check"></i><b>57.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="57.1.1" data-path="marketsurvey.html"><a href="marketsurvey.html#agingdata_marketsurvey"><i class="fa fa-check"></i><b>57.1.1</b> Aging Market Survey Data</a></li>
<li class="chapter" data-level="57.1.2" data-path="marketsurvey.html"><a href="marketsurvey.html#applyingweights_marketsurvey"><i class="fa fa-check"></i><b>57.1.2</b> Applying Market Survey Weights</a></li>
<li class="chapter" data-level="57.1.3" data-path="marketsurvey.html"><a href="marketsurvey.html#conceptualvideo_marketsurvey"><i class="fa fa-check"></i><b>57.1.3</b> Conceptual Video</a></li>
</ul></li>
<li class="chapter" data-level="57.2" data-path="marketsurvey.html"><a href="marketsurvey.html#tutorial_marketsurvey"><i class="fa fa-check"></i><b>57.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="57.2.1" data-path="marketsurvey.html"><a href="marketsurvey.html#videotutorial_marketsurvey"><i class="fa fa-check"></i><b>57.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="57.2.2" data-path="marketsurvey.html"><a href="marketsurvey.html#functions_marketsurvey"><i class="fa fa-check"></i><b>57.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="57.2.3" data-path="marketsurvey.html"><a href="marketsurvey.html#initsteps_marketsurvey"><i class="fa fa-check"></i><b>57.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="57.2.4" data-path="marketsurvey.html"><a href="marketsurvey.html#agedata_marketsurvey"><i class="fa fa-check"></i><b>57.2.4</b> Age the Data</a></li>
<li class="chapter" data-level="57.2.5" data-path="marketsurvey.html"><a href="marketsurvey.html#weightdata_marketsurvey"><i class="fa fa-check"></i><b>57.2.5</b> Compute the Sample-Weighted Means</a></li>
<li class="chapter" data-level="57.2.6" data-path="marketsurvey.html"><a href="marketsurvey.html#summary_marketsurvey"><i class="fa fa-check"></i><b>57.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="58" data-path="marketpayline.html"><a href="marketpayline.html"><i class="fa fa-check"></i><b>58</b> Estimating a Market Pay Line</a>
<ul>
<li class="chapter" data-level="58.1" data-path="marketpayline.html"><a href="marketpayline.html#conceptualoverview_marketpayline"><i class="fa fa-check"></i><b>58.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="58.1.1" data-path="marketpayline.html"><a href="marketpayline.html#statisticalassumptions_marketpayline"><i class="fa fa-check"></i><b>58.1.1</b> Statistical Assumptions</a></li>
<li class="chapter" data-level="58.1.2" data-path="marketpayline.html"><a href="marketpayline.html#statisticalsignificance_marketpayline"><i class="fa fa-check"></i><b>58.1.2</b> Statistical Significance</a></li>
<li class="chapter" data-level="58.1.3" data-path="marketpayline.html"><a href="marketpayline.html#practicalsignificance_marketpayline"><i class="fa fa-check"></i><b>58.1.3</b> Practical Significance</a></li>
<li class="chapter" data-level="58.1.4" data-path="marketpayline.html"><a href="marketpayline.html#conceptualvideo_marketpayline"><i class="fa fa-check"></i><b>58.1.4</b> Conceptual Video</a></li>
</ul></li>
<li class="chapter" data-level="58.2" data-path="marketpayline.html"><a href="marketpayline.html#tutorial_marketpayline"><i class="fa fa-check"></i><b>58.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="58.2.1" data-path="marketpayline.html"><a href="marketpayline.html#videotutorial_marketpayline"><i class="fa fa-check"></i><b>58.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="58.2.2" data-path="marketpayline.html"><a href="marketpayline.html#functions_marketpayline"><i class="fa fa-check"></i><b>58.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="58.2.3" data-path="marketpayline.html"><a href="marketpayline.html#initsteps_marketpayline"><i class="fa fa-check"></i><b>58.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="58.2.4" data-path="marketpayline.html"><a href="marketpayline.html#estimate_slr_marketpayline"><i class="fa fa-check"></i><b>58.2.4</b> Estimate a Market Pay Line</a></li>
<li class="chapter" data-level="58.2.5" data-path="marketpayline.html"><a href="marketpayline.html#summary_marketpayline"><i class="fa fa-check"></i><b>58.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>XI Odds &amp; Ends</b></span></li>
<li class="chapter" data-level="59" data-path="create_portfolio.html"><a href="create_portfolio.html"><i class="fa fa-check"></i><b>59</b> Creating a Data Analytics Portfolio</a></li>
<li class="chapter" data-level="60" data-path="literature_search_review.html"><a href="literature_search_review.html"><i class="fa fa-check"></i><b>60</b> Conducting a Literature Search &amp; Review</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for HR:<br />
<em>An Introduction to Human Resource Analytics Using R</em><br />
BOOK UNDER CONSTRUCTION</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="polynomialregression" class="section level1" number="52">
<h1><span class="header-section-number">Chapter 52</span> Investigating Nonlinear Associations Using Polynomial Regression</h1>
<p>In this chapter, we will learn how to investigate nonlinear associations between two continuous (interval, ratio) variables using polynomial regression. There are other ways in which we can estimate nonlinear associations, but in this chapter, we’ll focus just on polynomial regression.</p>
<div id="conceptualoverview_polynomialregression" class="section level2" number="52.1">
<h2><span class="header-section-number">52.1</span> Conceptual Overview</h2>
<p>A common way to explore a nonlinear association between two variables is to estimate a <strong>polynomial regression</strong> model. If you think way back to algebra class, a <em>polynomial</em> is a mathematical expression with multiple terms, which might include constants, variables, or exponents. With polynomial regression, we are able to estimate curvature in the relation between two variables, such as quadratic or cubic functional forms. For example, let’s imagine that we have variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, and we suspect that the association between the two variables is nonlinear. Specifically, let’s assume that the true association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> can be expressed as the following quadratic equation:</p>
<p><span class="math inline">\(\hat{Y} = 8 - 9X + X^2\)</span></p>
<p>where <span class="math inline">\(\hat{Y}\)</span> is the predicted (fitted) value of the outcome variable <span class="math inline">\(Y\)</span>.</p>
<p>If we plot this equation, we get the following parabolic shape.</p>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-1222-1.png" width="672" /></p>
<p>If we only estimated a linear association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, we might miss the fact that these two variables are indeed associated with one another – or we might miss the true functional form of their association.</p>
<p>In addition to quadratic terms, we can also include cubic terms, which can manifest as an association with two bends or curves:</p>
<p><span class="math inline">\(\hat{Y} = 1 - .25x + .75X^2 + .35X^3\)</span></p>
<p>If we plot this equation, we get the following functional form.</p>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-1223-1.png" width="672" /></p>
<p>As the name implies, polynomial regression is a type of regression. If you haven’t already, prior to following along with this tutorial, I recommend checking out the chapters that introduce <a href="predictingcriterionscores.html#predictingcriterionscores">simple linear regression</a>, <a href="incrementalvalidity.html#incrementalvalidity">multiple linear regression</a>, and <a href="differentialprediction.html#differentialprediction">moderated multiple linear regression</a>.</p>
<div id="statisticalassumptions_polynomialregression" class="section level3" number="52.1.1">
<h3><span class="header-section-number">52.1.1</span> Statistical Assumptions</h3>
<p>The statistical assumptions that should be met prior to running and/or interpreting estimates from a polynomial regression model include:</p>
<ul>
<li>Cases are randomly sampled from the population, such that the variable scores for one individual are independent of the variable scores of another individual;</li>
<li>The association between the predictor and outcome variables is nonlinear;</li>
<li>Average residual error value is zero;</li>
<li>Residual errors are normally distributed.</li>
</ul>
<p><em>Note:</em> Regarding the first statistical assumption (i.e., cases randomly sampled from population), we will assume in this chapter’s data that this is not an issue. If we were to suspect, however, that there were some clustering or nesting of cases in units/groups (e.g., by supervisors, units, or facilities) with respect to our outcome variable, then we would need to run some type of multilevel model (e.g., hierarchical linear model, multilevel structural equation model), which is beyond the scope of this tutorial. An <em>intraclass correlation (ICC)</em> can be used to diagnose such nesting or cluster. Failing to account for clustering or nesting in the data can bias estimates of standard errors, which ultimately influences the <em>p</em>-values and inferences of statistical significance.</p>
</div>
<div id="statisticalsignficance_polynomialregression" class="section level3" number="52.1.2">
<h3><span class="header-section-number">52.1.2</span> Statistical Significance</h3>
<p>In polynomial regression, we are often interested in the significance of the highest order term in the model (e.g., <span class="math inline">\(X^3\)</span>) when controlling for the lower order terms (e.g., <span class="math inline">\(X\)</span>, <span class="math inline">\(X^2\)</span>). Using null hypothesis significance testing (NHST), we interpret a <em>p</em>-value that is <em>less than .05</em> (or whatever two- or one-tailed alpha level we set) to meet the standard for statistical significance, meaning that we reject the null hypothesis that the regression coefficient is equal to zero. In other words, if a regression coefficient’s <em>p</em>-value is less than .05, we conclude that the regression coefficient differs from zero to a statistically significant extent. In contrast, if the regression coefficient’s <em>p</em>-value is <em>equal to or greater than .05</em>, then we fail to reject the null hypothesis that the regression coefficient is equal to zero. Put differently, if a regression coefficient’s <em>p</em>-value is equal to or greater than .05, we conclude that the regression coefficient does <em>not</em> differ from zero to a statistically significant extent, leading us to conclude that there is no association between the predictor variable and the outcome variable in the population.</p>
<p>When setting an alpha threshold, such as the conventional two-tailed .05 level, sometimes the question comes up regarding whether borderline <em>p</em>-values signify significance or nonsignificance. For our purposes, let’s be very strict in our application of the chosen alpha level. For example, if we set our alpha level at .05, <em>p</em> = .049 would be considered statistically significant, and <em>p</em> = .050 would be considered statistically nonsignificant.</p>
<p>Because our regression model estimates are based on data from a sample that is drawn from an underlying population, sampling error will affect the extent to which our sample is representative of the population from which its drawn. That is, a regression coefficient estimate (<em>b</em>) is a <em>point estimate</em> of the population parameter that is subject to sampling error. Fortunately, confidence intervals can give us a better idea of what the true population parameter value might be. If we apply an alpha level of .05 (two-tailed), then the equivalent confidence interval (CI) is a 95% CI. In terms of whether a regression coefficient is statistically significant, if the lower and upper limits of 95% CI do <em>not</em> include zero, then this tells us the same thing as a <em>p</em>-value that is less than .05. Strictly speaking, a 95% CI indicates that if we were to hypothetically draw many more samples from the underlying population and construct CIs for each of those samples, then the true parameter (i.e., true value of the regression coefficient in the population) would likely fall within the lower and upper bounds of 95% of the estimated CIs. In other words, the 95% CI gives us an indication of plausible values for the population parameter while taking into consideration sampling error. A wide CI (i.e., large difference between the lower and upper limits) signifies more sampling error, and a narrow CI signifies less sampling error.</p>
<div id="practicalsignficance_polynomialregression" class="section level4" number="52.1.2.1">
<h4><span class="header-section-number">52.1.2.1</span> Practical Significance</h4>
<p>As a reminder, an effect size is a standardized metric that can be compared across samples. In a polynomial regression model, an <em>unstandardized</em> regression coefficient (<span class="math inline">\(b\)</span>) is <em>not</em> an effect size. The reason being, an unstandardized regression coefficient estimate is based on the original scaling of the predictor and outcome variables, and thus the same effect will take on different regression coefficients to the extent that the predictor and outcome variables have different scalings across samples.</p>
<p>In contrast, a <em>standardized</em> regression coefficient (<span class="math inline">\(\beta\)</span>) is estimated by standardizing the scores of the both the predictor and outcome variables. Given this, a standardized regression coefficient can be compared to other standardized regression coefficients; however, we should take caution when making such comparisons in a polynomial regression model, as we are effectively controlling for lower-order terms in the model.</p>
<p>In a polynomial regression model, we can also describe the magnitude of the effect in terms of the proportion of variance explained in the outcome variable by the predictor variable (i.e., <em>R</em><sup>2</sup>). Conceptually, we can think of the overlap between the variability in the predictor and outcome variables as the variance explained (<em>R</em><sup>2</sup>). I’ve found that the <em>R</em><sup>2</sup> is often more readily interpretable by non-analytics audiences. For example, an <em>R</em><sup>2</sup> of .10 in a polynomial regression model can be interpreted as: 10% of the variability in scores on the outcome variable can be explained by scores on the predictor variable. That is, to convert an <em>R</em><sup>2</sup> from a proportion to a percent, we just multiply by 100.</p>
<table>
<thead>
<tr class="header">
<th align="center"><em>R</em><sup>2</sup></th>
<th align="center">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">.01</td>
<td align="center">Small</td>
</tr>
<tr class="even">
<td align="center">.09</td>
<td align="center">Medium</td>
</tr>
<tr class="odd">
<td align="center">.25</td>
<td align="center">Large</td>
</tr>
</tbody>
</table>
<p><em>Note: Typically, we only interpret the practical significance of an effect if the effect was found to be statistically significant. The logic is that if an effect (e.g., association, difference) is not statistically significant, then we should treat it as no different than zero, and thus it wouldn’t make sense to the interpret the size of something that statistically has no effect.</em></p>
</div>
<div id="samplewriteup_polynomialregression" class="section level4" number="52.1.2.2">
<h4><span class="header-section-number">52.1.2.2</span> Sample Write-Up</h4>
<p>Based on a sample of 107 employees (<em>N</em> = 107), We found that the association between emotional stability scores and supervisor ratings of job performance was nonlinear. Using polynomial regression, we found that the quadratic term for emotional stability was statistically significant (<em>b</em> = -.475, <em>p</em> &lt; .001), which implies that there is a statistically significant nonlinear association with a quadratic functional form. Moreover, with the quadratic term included, the model explained 22.7% of the variability in supervisor ratings of job performance, which was an 18.9% improvement over a simple linear regression model that lacked the quadratic term. The functional form of the association can be described as an inverted “U,” such that supervisor ratings of performance are highest for those employees with more moderate levels of emotional stability.</p>
</div>
</div>
</div>
<div id="tutorial_polynomialregression" class="section level2" number="52.2">
<h2><span class="header-section-number">52.2</span> Tutorial</h2>
<p>This chapter’s tutorial demonstrates how to estimate a polynomial regression model in R.</p>
<div id="functions_polynomialregression" class="section level3" number="52.2.1">
<h3><span class="header-section-number">52.2.1</span> Functions &amp; Packages Introduced</h3>
<table>
<thead>
<tr class="header">
<th align="center">Function</th>
<th align="center">Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><code>plot</code></td>
<td align="center">base R</td>
</tr>
<tr class="even">
<td align="center"><code>lm</code></td>
<td align="center">base R</td>
</tr>
<tr class="odd">
<td align="center"><code>summary</code></td>
<td align="center">base R</td>
</tr>
<tr class="even">
<td align="center"><code>mean</code></td>
<td align="center">base R</td>
</tr>
<tr class="odd">
<td align="center"><code>I</code></td>
<td align="center">base R</td>
</tr>
<tr class="even">
<td align="center"><code>hist</code></td>
<td align="center">base R</td>
</tr>
<tr class="odd">
<td align="center"><code>seq</code></td>
<td align="center">base R</td>
</tr>
<tr class="even">
<td align="center"><code>min</code></td>
<td align="center">base R</td>
</tr>
<tr class="odd">
<td align="center"><code>max</code></td>
<td align="center">base R</td>
</tr>
<tr class="even">
<td align="center"><code>lines</code></td>
<td align="center">base R</td>
</tr>
<tr class="odd">
<td align="center"><code>poly</code></td>
<td align="center">base R</td>
</tr>
<tr class="even">
<td align="center"><code>predict</code></td>
<td align="center">base R</td>
</tr>
</tbody>
</table>
</div>
<div id="initsteps_polynomialregression" class="section level3" number="52.2.2">
<h3><span class="header-section-number">52.2.2</span> Initial Steps</h3>
<p>If you haven’t already, save the file called <strong>“Nonlinear.csv”</strong> into a folder that you will subsequently set as your working directory. Your working directory will likely be different than the one shown below (i.e., <code>"H:/RWorkshop"</code>). As a reminder, you can access all of the data files referenced in this book by downloading them as a compressed (zipped) folder from the my GitHub site: <a href="https://github.com/davidcaughlin/R-Tutorial-Data-Files" class="uri">https://github.com/davidcaughlin/R-Tutorial-Data-Files</a>; once you’ve followed the link to GitHub, just click “Code” (or “Download”) followed by “Download ZIP,” which will download all of the data files referenced in this book. For the sake of parsimony, I recommend downloading all of the data files into the same folder on your computer, which will allow you to set that same folder as your working directory for each of the chapters in this book.</p>
<p>Next, using the <code>setwd</code> function, set your working directory to the folder in which you saved the data file for this chapter. Alternatively, you can manually set your working directory folder in your drop-down menus by going to <em>Session &gt; Set Working Directory &gt; Choose Directory…</em>. Be sure to create a new R script file (.R) or update an existing R script file so that you can save your script and annotations. If you need refreshers on how to set your working directory and how to create and save an R script, please refer to <a href="setwd.html#setwd">Setting a Working Directory</a> and <a href="gettingstarted.html#createRscript">Creating &amp; Saving an R Script</a>.</p>
<div class="sourceCode" id="cb2143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2143-1"><a href="polynomialregression.html#cb2143-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your working directory</span></span>
<span id="cb2143-2"><a href="polynomialregression.html#cb2143-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;H:/RWorkshop&quot;</span>)</span></code></pre></div>
<p>Next, read in the .csv data file called <strong>“Nonlinear.csv”</strong> using your choice of read function. In this example, I use the <code>read_csv</code> function from the <code>readr</code> package <span class="citation">(<a href="#ref-R-readr" role="doc-biblioref">Wickham, Hester, and Bryan 2021</a>)</span>. If you choose to use the <code>read_csv</code> function, be sure that you have installed and accessed the <code>readr</code> package using the <code>install.packages</code> and <code>library</code> functions. <em>Note: You don’t need to install a package every time you wish to access it; in general, I would recommend updating a package installation once ever 1-3 months.</em> For refreshers on installing packages and reading data into R, please refer to <a href="gentleintro.html#packages">Packages</a> and <a href="read.html#read">Reading Data into R</a>.</p>
<div class="sourceCode" id="cb2144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2144-1"><a href="polynomialregression.html#cb2144-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install readr package if you haven&#39;t already</span></span>
<span id="cb2144-2"><a href="polynomialregression.html#cb2144-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Note: You don&#39;t need to install a package every </span></span>
<span id="cb2144-3"><a href="polynomialregression.html#cb2144-3" aria-hidden="true" tabindex="-1"></a><span class="co"># time you wish to access it]</span></span>
<span id="cb2144-4"><a href="polynomialregression.html#cb2144-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;readr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb2145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2145-1"><a href="polynomialregression.html#cb2145-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access readr package</span></span>
<span id="cb2145-2"><a href="polynomialregression.html#cb2145-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb2145-3"><a href="polynomialregression.html#cb2145-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2145-4"><a href="polynomialregression.html#cb2145-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data and name data frame (tibble) object</span></span>
<span id="cb2145-5"><a href="polynomialregression.html#cb2145-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;Nonlinear.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 107 Columns: 2</code></pre>
<pre><code>## -- Column specification ------------------------------------------------------------------------------------------------------------------------
## Delimiter: &quot;,&quot;
## dbl (2): ES, Perf</code></pre>
<pre><code>## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb2149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2149-1"><a href="polynomialregression.html#cb2149-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the names of the variables in the data frame (tibble) object</span></span>
<span id="cb2149-2"><a href="polynomialregression.html#cb2149-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df)</span></code></pre></div>
<pre><code>## [1] &quot;ES&quot;   &quot;Perf&quot;</code></pre>
<div class="sourceCode" id="cb2151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2151-1"><a href="polynomialregression.html#cb2151-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print variable type for each variable in data frame (tibble) object</span></span>
<span id="cb2151-2"><a href="polynomialregression.html#cb2151-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code></pre></div>
<pre><code>## spec_tbl_df [107 x 2] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ ES  : num [1:107] 0.2 0.9 2.1 1.9 1.6 1.8 1.4 2.3 1.7 0.2 ...
##  $ Perf: num [1:107] 1.6 10.1 6.7 4.9 3.4 15.1 11.7 6.8 26.5 8.3 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   ES = col_double(),
##   ..   Perf = col_double()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
<div class="sourceCode" id="cb2153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2153-1"><a href="polynomialregression.html#cb2153-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print first 6 rows of data frame (tibble) object</span></span>
<span id="cb2153-2"><a href="polynomialregression.html#cb2153-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##      ES  Perf
##   &lt;dbl&gt; &lt;dbl&gt;
## 1   0.2   1.6
## 2   0.9  10.1
## 3   2.1   6.7
## 4   1.9   4.9
## 5   1.6   3.4
## 6   1.8  15.1</code></pre>
<div class="sourceCode" id="cb2155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2155-1"><a href="polynomialregression.html#cb2155-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print number of rows in data frame (tibble) object</span></span>
<span id="cb2155-2"><a href="polynomialregression.html#cb2155-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df)</span></code></pre></div>
<pre><code>## [1] 107</code></pre>
<p>There are 2 variables and 107 cases (i.e., employees) in the <code>df</code> data frame: <code>ES</code> and <code>Perf</code>. Per the output of the <code>str</code> (structure) function above, both variables are of type <em>numeric</em> (continuous: interval, ratio). The <code>ES</code> variable is a measure of emotional stability, with scores ranging from 1 (low emotional stability) to 10 (high emotional stability). The <code>Perf</code> variable includes performance evaluation data that can range from 0 (low performance) to 30 (high performance).</p>
</div>
<div id="bivariatescatterplot_polynomialregression" class="section level3" number="52.2.3">
<h3><span class="header-section-number">52.2.3</span> Visualize Association Using a Bivariate Scatter Plot</h3>
<p>A <strong>bivariate scatter plot</strong> can be used to visualize the association between two continuous (interval, ratio) variables. This type of plot can help us identify whether an association between variables might be nonlinear.</p>
<p>Let’s create a bivariate scatter plot to visualize the association between the <code>ES</code> (emotional stability) and the <code>Perf</code> (supervisor-ratings of job performance) variables, both of which are continuous.</p>
<p>The <code>plot</code> function from base R will help us generate a very simple scatter plot, which will be fine for our purposes. To begin, type the name of the <code>plot</code> function. As the first argument, we’ll type the name of the data frame object (<code>df</code>), followed by the <code>$</code> operator and the name of the predictor variable (<code>ES</code>). As the second argument, we’ll type the name of the data frame object (<code>df</code>), followed by the <code>$</code> operator and the name of the outcome variable (<code>Perf</code>).</p>
<div class="sourceCode" id="cb2157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2157-1"><a href="polynomialregression.html#cb2157-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scatter plot using plot function from base R</span></span>
<span id="cb2157-2"><a href="polynomialregression.html#cb2157-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>ES, df<span class="sc">$</span>Perf)</span></code></pre></div>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-1230-1.png" width="672" /></p>
<p>In our plot window, we can see evidence of a nonlinear association between scores on <code>ES</code> and scores on <code>Perf</code>. In fact, the association seems to take the functional form of a quadratic inverted “U” shape. This suggests that a simple linear regression model would not be appropriate for exploration the nature of the association between these two variables. Instead, we should try estimating a polynomial regression model.</p>
</div>
<div id="estimate_polynomialregression" class="section level3" number="52.2.4">
<h3><span class="header-section-number">52.2.4</span> Estimate Polynomial Regression Model</h3>
<p>It’s customary to build a polynomial regression model in an iterative manner. That is, we’ll start with a simple linear regression model, with <code>ES</code> as the predictor variable and <code>Perf</code> as the outcome variable, and then work our way up to a polynomial regression model by adding additional terms.</p>
<div id="estimate_stepone_slr" class="section level4" number="52.2.4.1">
<h4><span class="header-section-number">52.2.4.1</span> Step One: Simple Linear Regression Model</h4>
<p>Let’s name our simple linear regression model object <code>mod1</code>. For a review, check out the <a href="predictingcriterionscores.html#predictingcriterionscores">chapter that covers simple linear regression</a>.</p>
<div class="sourceCode" id="cb2158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2158-1"><a href="polynomialregression.html#cb2158-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate simple linear regression model</span></span>
<span id="cb2158-2"><a href="polynomialregression.html#cb2158-2" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Perf <span class="sc">~</span> ES, <span class="at">data=</span>df)</span>
<span id="cb2158-3"><a href="polynomialregression.html#cb2158-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2158-4"><a href="polynomialregression.html#cb2158-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary of results</span></span>
<span id="cb2158-5"><a href="polynomialregression.html#cb2158-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Perf ~ ES, data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -16.2413  -4.0120   0.3052   5.4448  10.6708 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept)  16.6540     1.3533  12.306 &lt;0.0000000000000002 ***
## ES            0.4931     0.2419   2.038               0.044 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.95 on 105 degrees of freedom
## Multiple R-squared:  0.03807,    Adjusted R-squared:  0.02891 
## F-statistic: 4.155 on 1 and 105 DF,  p-value: 0.04402</code></pre>
<p>The regression coefficient associated with <code>ES</code> is .493 (<em>p</em> = .044), which is statistically significant, so that seems promising; however, let’s plot the predicted/fitted values based on our model with the residuals (errors). To do so, we will use the <code>plot</code> function from base R, and enter the name of our regression model object (<code>mod1</code>) as the first argument. As the second argument, enter the numeral <em>1</em> to request the residuals vs. fitted values plot.</p>
<div class="sourceCode" id="cb2160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2160-1"><a href="polynomialregression.html#cb2160-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagnostic plot: Residuals vs. Fitted Values</span></span>
<span id="cb2160-2"><a href="polynomialregression.html#cb2160-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod1, <span class="dv">1</span>)</span></code></pre></div>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-1232-1.png" width="672" /></p>
<p>The plot shows evidence of what looks like a nonlinear association. Given that, we have found additional evidence that the association between the <code>ES</code> and <code>Perf</code> variables violates key statistical assumptions that should be satisfied to interpret a simple linear regression. Thus, we should proceed forward by constructing a polynomial regression model.</p>
</div>
<div id="estimate_steptwo_polynomialregression" class="section level4" number="52.2.4.2">
<h4><span class="header-section-number">52.2.4.2</span> Step Two: Polynomial Regression Model</h4>
<p>We’ll build upon our previous model by adding a quadratic term to our model. Prior to doing so, however, let’s grand-mean center our predictor variable (<code>ES</code>) to reduce the collinearity between <code>ES</code> and its quadratic (product) term. We’ll call the grand-mean centered variable <code>c_ES</code>. For more information on centering variables, check out the <a href="center.html#center">chapter on centering and standardizing variables</a>.</p>
<p><em>Note:</em> While grand-mean centering may improve estimates of standard errors, it does not generally affect the overall model fit to the data; thus, when plotting model, you may choose to use the uncentered predictor variables.</p>
<div class="sourceCode" id="cb2161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2161-1"><a href="polynomialregression.html#cb2161-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grand-mean center predictor variable and create new variable</span></span>
<span id="cb2161-2"><a href="polynomialregression.html#cb2161-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>c_ES <span class="ot">&lt;-</span> df<span class="sc">$</span>ES <span class="sc">-</span> <span class="fu">mean</span>(df<span class="sc">$</span>ES, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p>There are different ways we can add the quadratic term to the model. Let’s start with what I believe is the most intuitive approach.</p>
<ol style="list-style-type: decimal">
<li>Let’s name this polynomial regression model object (<code>mod2</code>) using the <code>&lt;-</code> assignment operator.</li>
<li>To the right of the <code>&lt;-</code> assignment operator, start with the simple linear regression model we specified in the previous step.</li>
<li>In the regression model formula, type the name of your grand-mean centered predictor variable (<code>c_ES</code>), followed by the <code>+</code> operator.</li>
<li>After the <code>+</code> operator, insert the <code>I</code> function from base R, and within its parentheses, type the name of the grand-mean centered predictor variable (<code>c_ES</code>) followed by <code>^2</code> to signal that you want to include a quadratic term.</li>
</ol>
<div class="sourceCode" id="cb2162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2162-1"><a href="polynomialregression.html#cb2162-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate polynomial regression model: Option 1</span></span>
<span id="cb2162-2"><a href="polynomialregression.html#cb2162-2" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Perf <span class="sc">~</span> c_ES <span class="sc">+</span> <span class="fu">I</span>(c_ES<span class="sc">^</span><span class="dv">2</span>), <span class="at">data=</span>df)</span>
<span id="cb2162-3"><a href="polynomialregression.html#cb2162-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2162-4"><a href="polynomialregression.html#cb2162-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary of results</span></span>
<span id="cb2162-5"><a href="polynomialregression.html#cb2162-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Perf ~ c_ES + I(c_ES^2), data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -16.2757  -4.1173   0.9039   4.9100  10.9401 
## 
## Coefficients:
##             Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept) 22.70895    0.94469  24.038 &lt; 0.0000000000000002 ***
## c_ES         0.57739    0.21850   2.642               0.0095 ** 
## I(c_ES^2)   -0.47454    0.09405  -5.045           0.00000193 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.259 on 104 degrees of freedom
## Multiple R-squared:  0.2272, Adjusted R-squared:  0.2124 
## F-statistic: 15.29 on 2 and 104 DF,  p-value: 0.00000151</code></pre>
<p>Looking at the output, note that the product (quadratic, second-order) term is statistically significant (<em>b</em> = -.475, <em>p</em> &lt; .001), which implies that there is a statistically significant nonlinear association between <code>ES</code> and <code>Perf</code> that specifically takes a quadratic functional form. Note that the unadjusted <em>R</em><sup>2</sup> value increased from .038 (3.8%) in the simple linear regression model to .227 (22.7%) in this polynomial regression model; that is a huge amount of incremental variance explained in <code>Perf</code> after adding the quadratic term of <code>ES</code> to the model.</p>
<p>Let’s plot the fitted/predicted values in relation to the residuals, as we did with the simple linear regression model above.</p>
<div class="sourceCode" id="cb2164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2164-1"><a href="polynomialregression.html#cb2164-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagnostic plot: Residuals vs. Fitted Values</span></span>
<span id="cb2164-2"><a href="polynomialregression.html#cb2164-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod2, <span class="dv">1</span>)</span></code></pre></div>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-1235-1.png" width="672" /></p>
<p>That looks much better with regard to meeting the statistical assumption that the average residual error value is zero.</p>
<p>Next, let’s check to see if we can feel reasonably confident that the data meet the statistical assumption that the residual errors are normally distributed for each level of the predictor variable. To do so, we will use the histogram (<code>hist</code>) function from base R. As the sole argument, enter the <code>summary</code> function with the regression model (<code>mod2</code>) in the parentheses, followed by the <code>$</code> operator and <code>residuals</code> (which extracts the vector of residuals from your model summary).</p>
<div class="sourceCode" id="cb2165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2165-1"><a href="polynomialregression.html#cb2165-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagnostic plot: Distribution of residuals</span></span>
<span id="cb2165-2"><a href="polynomialregression.html#cb2165-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">summary</span>(mod2)<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-1236-1.png" width="672" /></p>
<p>The distribution of the residuals seems to be approximately normal and centered around zero, so we can conclude that we have pretty good evidence that we have met that statistical assumption. Given that we have good reason to believe we have met the aforementioned statistical assumptions, we can proceed forward with interpreting and exploring our polynomial regression model.</p>
<p>If we create a sequence of predictor (x) variable values (that I call <code>xvalues</code>) using the <code>seq</code> function from base R and plug those values along with the regression equation values from the output above into the <code>plot</code> function from base R, we view the predicted form of the nonlinear association.</p>
<div class="sourceCode" id="cb2166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2166-1"><a href="polynomialregression.html#cb2166-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create object xvalues w/ continuous sequence of 1000 values </span></span>
<span id="cb2166-2"><a href="polynomialregression.html#cb2166-2" aria-hidden="true" tabindex="-1"></a><span class="co"># to include observed range of centered predictor values</span></span>
<span id="cb2166-3"><a href="polynomialregression.html#cb2166-3" aria-hidden="true" tabindex="-1"></a>xvalues <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(df<span class="sc">$</span>c_ES), <span class="co"># Mininum of observed range</span></span>
<span id="cb2166-4"><a href="polynomialregression.html#cb2166-4" aria-hidden="true" tabindex="-1"></a>               <span class="fu">max</span>(df<span class="sc">$</span>c_ES), <span class="co"># Maximum of observed range</span></span>
<span id="cb2166-5"><a href="polynomialregression.html#cb2166-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">length=</span><span class="dv">1000</span>) <span class="co"># Number of sequence values within range</span></span>
<span id="cb2166-6"><a href="polynomialregression.html#cb2166-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2166-7"><a href="polynomialregression.html#cb2166-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scatterplot for predictor and outcome variables</span></span>
<span id="cb2166-8"><a href="polynomialregression.html#cb2166-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>c_ES, <span class="co"># Insert predictor variable</span></span>
<span id="cb2166-9"><a href="polynomialregression.html#cb2166-9" aria-hidden="true" tabindex="-1"></a>     df<span class="sc">$</span>Perf, <span class="co"># Insert outcome variable</span></span>
<span id="cb2166-10"><a href="polynomialregression.html#cb2166-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Emotional Stability&quot;</span>, <span class="co"># Set x-axis label</span></span>
<span id="cb2166-11"><a href="polynomialregression.html#cb2166-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Supervisor-Rated Performance&quot;</span>) <span class="co"># Set y-axis label</span></span>
<span id="cb2166-12"><a href="polynomialregression.html#cb2166-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2166-13"><a href="polynomialregression.html#cb2166-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Add estimated regression equation line to scatterplot</span></span>
<span id="cb2166-14"><a href="polynomialregression.html#cb2166-14" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(xvalues, <span class="co"># Insert continuous sequence of values object</span></span>
<span id="cb2166-15"><a href="polynomialregression.html#cb2166-15" aria-hidden="true" tabindex="-1"></a>      <span class="fl">22.70895</span> <span class="sc">+</span> <span class="fl">0.57739</span><span class="sc">*</span>(xvalues<span class="sc">^</span><span class="dv">1</span>) <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.47454</span><span class="sc">*</span>(xvalues<span class="sc">^</span><span class="dv">2</span>), <span class="co"># Insert regression equation</span></span>
<span id="cb2166-16"><a href="polynomialregression.html#cb2166-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">col=</span><span class="st">&quot;red&quot;</span>) <span class="co"># Set line color to red</span></span></code></pre></div>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-1237-1.png" width="672" /></p>
<p>As you can see, supervisor-ratings of performance are highest when emotional stability is somewhere around its mean. Thus, it seems that there is a sweet-spot for the Big Five personality dimension of emotional stability when it comes to performance. People who are really high in emotional stability might have a tendency to be too relaxed and may not be motivated to perform, whereas those who are really low in emotional stability might be too prone to experiencing emotional fluctuations and volatility to perform well.</p>
<p>We can also estimate the polynomial regression model <em>without</em> having to create a new grand-mean-centered predictor variable. The <code>poly</code> function from base R allows us to create orthogonal (uncorrelated) polynomial (e.g., product, quadratic) terms. We’ll name this model <code>mod3</code>.</p>
<div class="sourceCode" id="cb2167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2167-1"><a href="polynomialregression.html#cb2167-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate polynomial regression model: Option 2</span></span>
<span id="cb2167-2"><a href="polynomialregression.html#cb2167-2" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Perf <span class="sc">~</span> <span class="fu">poly</span>(ES, <span class="dv">2</span>), <span class="co"># Insert 2 for quadratic</span></span>
<span id="cb2167-3"><a href="polynomialregression.html#cb2167-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data=</span>df) <span class="co"># Specify data frame</span></span>
<span id="cb2167-4"><a href="polynomialregression.html#cb2167-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2167-5"><a href="polynomialregression.html#cb2167-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary of results</span></span>
<span id="cb2167-6"><a href="polynomialregression.html#cb2167-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Perf ~ poly(ES, 2), data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -16.2757  -4.1173   0.9039   4.9100  10.9401 
## 
## Coefficients:
##              Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)   19.0486     0.6051  31.481 &lt; 0.0000000000000002 ***
## poly(ES, 2)1  14.1666     6.2589   2.263               0.0257 *  
## poly(ES, 2)2 -31.5788     6.2589  -5.045           0.00000193 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.259 on 104 degrees of freedom
## Multiple R-squared:  0.2272, Adjusted R-squared:  0.2124 
## F-statistic: 15.29 on 2 and 104 DF,  p-value: 0.00000151</code></pre>
<p>Note that the unadjusted <em>R</em><sup>2</sup> value of .227 is the same for both approaches, but due to differences in how the polynomial is created/estimated, we see differences in the coefficients between the two approaches. Nonetheless, if we plot the second approach, we see the same functional form. Here, we use the <code>predict</code> function from base R to create predicted values. A benefit to using this approach is that the predictor (x) variable remains in its original scale (i.e., 1-5) in the model and plot. In the script below, I also show a different way of specifying the <code>plot</code> function arguments.</p>
<div class="sourceCode" id="cb2169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2169-1"><a href="polynomialregression.html#cb2169-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create object xvalues w/ continuous sequence of 1,000 values </span></span>
<span id="cb2169-2"><a href="polynomialregression.html#cb2169-2" aria-hidden="true" tabindex="-1"></a><span class="co"># to include observed range of uncentered predictor values</span></span>
<span id="cb2169-3"><a href="polynomialregression.html#cb2169-3" aria-hidden="true" tabindex="-1"></a>xvalues <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(df<span class="sc">$</span>ES), <span class="co"># Mininum of observed range</span></span>
<span id="cb2169-4"><a href="polynomialregression.html#cb2169-4" aria-hidden="true" tabindex="-1"></a>               <span class="fu">max</span>(df<span class="sc">$</span>ES), <span class="co"># Maximum of observed range</span></span>
<span id="cb2169-5"><a href="polynomialregression.html#cb2169-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">length=</span><span class="dv">1000</span>) <span class="co"># Number of sequence values within range</span></span>
<span id="cb2169-6"><a href="polynomialregression.html#cb2169-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2169-7"><a href="polynomialregression.html#cb2169-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate predicted values</span></span>
<span id="cb2169-8"><a href="polynomialregression.html#cb2169-8" aria-hidden="true" tabindex="-1"></a>predicted_values <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod3, <span class="co"># Regression model/equation </span></span>
<span id="cb2169-9"><a href="polynomialregression.html#cb2169-9" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">data.frame</span>(<span class="at">ES=</span>xvalues)) <span class="co"># Values to fit</span></span>
<span id="cb2169-10"><a href="polynomialregression.html#cb2169-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2169-11"><a href="polynomialregression.html#cb2169-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scatterplot for predictor and outcome variables</span></span>
<span id="cb2169-12"><a href="polynomialregression.html#cb2169-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Perf <span class="sc">~</span> ES, <span class="co"># Specify outcome and predictor</span></span>
<span id="cb2169-13"><a href="polynomialregression.html#cb2169-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">data=</span>df, <span class="co"># Specify data frame</span></span>
<span id="cb2169-14"><a href="polynomialregression.html#cb2169-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Emotional Stability&quot;</span>, <span class="co"># Set x-axis label</span></span>
<span id="cb2169-15"><a href="polynomialregression.html#cb2169-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Supervisor-Rated Performance&quot;</span>) <span class="co"># Set y-axis label</span></span>
<span id="cb2169-16"><a href="polynomialregression.html#cb2169-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2169-17"><a href="polynomialregression.html#cb2169-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Add estimated regression equation line to scatterplot</span></span>
<span id="cb2169-18"><a href="polynomialregression.html#cb2169-18" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(xvalues, <span class="co"># sequence of predictor values</span></span>
<span id="cb2169-19"><a href="polynomialregression.html#cb2169-19" aria-hidden="true" tabindex="-1"></a>      predicted_values, <span class="co"># Insert fitted/predicted values based on model</span></span>
<span id="cb2169-20"><a href="polynomialregression.html#cb2169-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">col=</span><span class="st">&quot;red&quot;</span>) <span class="co"># Set line color to red</span></span></code></pre></div>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-1239-1.png" width="672" /></p>
<p>As you can see, those two options for estimating a polynomial regression model reach the same end.</p>
<p>If you’d like to add a cubic term to the model, please do the following.</p>
<div class="sourceCode" id="cb2170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2170-1"><a href="polynomialregression.html#cb2170-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate polynomial regression model: Option 1</span></span>
<span id="cb2170-2"><a href="polynomialregression.html#cb2170-2" aria-hidden="true" tabindex="-1"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Perf <span class="sc">~</span> c_ES <span class="sc">+</span> <span class="fu">I</span>(c_ES<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(c_ES<span class="sc">^</span><span class="dv">3</span>), <span class="at">data=</span>df)</span>
<span id="cb2170-3"><a href="polynomialregression.html#cb2170-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2170-4"><a href="polynomialregression.html#cb2170-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary of results</span></span>
<span id="cb2170-5"><a href="polynomialregression.html#cb2170-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Perf ~ c_ES + I(c_ES^2) + I(c_ES^3), data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -16.4004  -4.2345   0.9338   4.9217  10.9981 
## 
## Coefficients:
##              Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept) 22.720359   0.951473  23.879 &lt; 0.0000000000000002 ***
## c_ES         0.664814   0.556168   1.195                0.235    
## I(c_ES^2)   -0.474834   0.094512  -5.024           0.00000214 ***
## I(c_ES^3)   -0.006664   0.038953  -0.171                0.864    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.288 on 103 degrees of freedom
## Multiple R-squared:  0.2274, Adjusted R-squared:  0.2049 
## F-statistic: 10.11 on 3 and 103 DF,  p-value: 0.000006791</code></pre>
<p>Or, an equivalent approach is the following.</p>
<div class="sourceCode" id="cb2172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2172-1"><a href="polynomialregression.html#cb2172-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate polynomial regression model: Option 2</span></span>
<span id="cb2172-2"><a href="polynomialregression.html#cb2172-2" aria-hidden="true" tabindex="-1"></a>mod5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Perf <span class="sc">~</span> <span class="fu">poly</span>(ES, <span class="dv">3</span>), <span class="co"># Insert 3 for cubic</span></span>
<span id="cb2172-3"><a href="polynomialregression.html#cb2172-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data=</span>df) </span>
<span id="cb2172-4"><a href="polynomialregression.html#cb2172-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2172-5"><a href="polynomialregression.html#cb2172-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary of results</span></span>
<span id="cb2172-6"><a href="polynomialregression.html#cb2172-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod5)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Perf ~ poly(ES, 3), data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -16.4004  -4.2345   0.9338   4.9217  10.9981 
## 
## Coefficients:
##              Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)   19.0486     0.6079  31.334 &lt; 0.0000000000000002 ***
## poly(ES, 3)1  14.1666     6.2884   2.253               0.0264 *  
## poly(ES, 3)2 -31.5788     6.2884  -5.022           0.00000216 ***
## poly(ES, 3)3  -1.0758     6.2884  -0.171               0.8645    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.288 on 103 degrees of freedom
## Multiple R-squared:  0.2274, Adjusted R-squared:  0.2049 
## F-statistic: 10.11 on 3 and 103 DF,  p-value: 0.000006791</code></pre>
<p>As you can see, adding the cubic term did not explain additional variability in the outcome. Thus, we would conclude in this situation that the association between <code>ES</code> and <code>Perf</code> has a quadratic functional form.</p>
<p><strong>Sample Technical Write-Up:</strong> Based on a sample of 107 employees (<em>N</em> = 107), We found that the association between emotional stability scores and supervisor ratings of job performance was nonlinear. Using polynomial regression, we found that the quadratic term for emotional stability was statistically significant (<em>b</em> = -.475, <em>p</em> &lt; .001), which implies that there is a statistically significant nonlinear association between <code>ES</code> and <code>Perf</code> that specifically takes a quadratic functional form. Moreover, with the quadratic term included, the model explained 22.7% of the variability in supervisor ratings of job performance, which was an 18.9% improvement over a simple linear regression model that lacked the quadratic term. The functional form of the association can be described as an inverted “U,” such that supervisor ratings of performance are highest for those employees with more moderate levels of emotional stability.</p>
</div>
</div>
<div id="summary_polynomialregression" class="section level3" number="52.2.5">
<h3><span class="header-section-number">52.2.5</span> Summary</h3>
<p>In this chapter, we learned how to explore a nonlinear association by estimating a polynomial regression model.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-R-readr" class="csl-entry">
Wickham, Hadley, Jim Hester, and Jennifer Bryan. 2021. <em>Readr: Read Rectangular Text Data</em>. <a href="https://CRAN.R-project.org/package=readr">https://CRAN.R-project.org/package=readr</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="convergentdiscriminantvalidity.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="lassoregression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
