<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 30 Evaluating a Post-Test-Only with Control Group Design Using Independent-Samples t-test | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION</title>
  <meta name="description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 30 Evaluating a Post-Test-Only with Control Group Design Using Independent-Samples t-test | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://rforhr.com" />
  <meta property="og:image" content="https://rforhr.comcover.png" />
  <meta property="og:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="github-repo" content="davidcaughlin/R-for-HR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 30 Evaluating a Post-Test-Only with Control Group Design Using Independent-Samples t-test | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  
  <meta name="twitter:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="twitter:image" content="https://rforhr.comcover.png" />

<meta name="author" content="David E. Caughlin" />


<meta name="date" content="2021-12-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="pretestposttest.html"/>
<link rel="next" href="posttestonly-threegroups.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for HR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#hragrowth"><i class="fa fa-check"></i><b>0.1</b> Growth of HR Analytics</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#skills-gap"><i class="fa fa-check"></i><b>0.2</b> Skills Gap</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#hraplc"><i class="fa fa-check"></i><b>0.3</b> Project Life Cycle Perspective</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#overview-of-hris-hr-analytics"><i class="fa fa-check"></i><b>0.4</b> Overview of HRIS &amp; HR Analytics</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#philosophy"><i class="fa fa-check"></i><b>0.5</b> My Philosophy for This Book</a>
<ul>
<li class="chapter" data-level="0.5.1" data-path="index.html"><a href="index.html#rationalerpref"><i class="fa fa-check"></i><b>0.5.1</b> Rationale for Using R</a></li>
<li class="chapter" data-level="0.5.2" data-path="index.html"><a href="index.html#audiencepref"><i class="fa fa-check"></i><b>0.5.2</b> Audience</a></li>
<li class="chapter" data-level="0.5.3" data-path="index.html"><a href="index.html#structurepref"><i class="fa fa-check"></i><b>0.5.3</b> Structure</a></li>
</ul></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#aboutauthor"><i class="fa fa-check"></i><b>0.6</b> About the Author</a></li>
<li class="chapter" data-level="0.7" data-path="index.html"><a href="index.html#acknowpref"><i class="fa fa-check"></i><b>0.7</b> Acknowledgements</a></li>
</ul></li>
<li class="part"><span><b>I HR Analytics Project Life Cycle</b></span></li>
<li class="chapter" data-level="1" data-path="overviewhraplc.html"><a href="overviewhraplc.html"><i class="fa fa-check"></i><b>1</b> Overview of HR Analytics Project Life Cycle</a></li>
<li class="chapter" data-level="2" data-path="questionformulation.html"><a href="questionformulation.html"><i class="fa fa-check"></i><b>2</b> Question Formulation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="questionformulation.html"><a href="questionformulation.html#adoptstrategicmindset"><i class="fa fa-check"></i><b>2.1</b> Adopting a Strategic Mindset</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="questionformulation.html"><a href="questionformulation.html#strategy"><i class="fa fa-check"></i><b>2.1.1</b> Strategy</a></li>
<li class="chapter" data-level="2.1.2" data-path="questionformulation.html"><a href="questionformulation.html#strategyformulation"><i class="fa fa-check"></i><b>2.1.2</b> Strategy Formulation</a></li>
<li class="chapter" data-level="2.1.3" data-path="questionformulation.html"><a href="questionformulation.html#strategyimplementation"><i class="fa fa-check"></i><b>2.1.3</b> Strategy Implementation</a></li>
<li class="chapter" data-level="2.1.4" data-path="questionformulation.html"><a href="questionformulation.html#strategichrm"><i class="fa fa-check"></i><b>2.1.4</b> Strategic Human Resource Management</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="questionformulation.html"><a href="questionformulation.html#defining-problems-formulating-questions"><i class="fa fa-check"></i><b>2.2</b> Defining Problems &amp; Formulating Questions</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="questionformulation.html"><a href="questionformulation.html#definingaproblem"><i class="fa fa-check"></i><b>2.2.1</b> Defining a Problem</a></li>
<li class="chapter" data-level="2.2.2" data-path="questionformulation.html"><a href="questionformulation.html#formulatingaquestion"><i class="fa fa-check"></i><b>2.2.2</b> Formulating a Question</a></li>
<li class="chapter" data-level="2.2.3" data-path="questionformulation.html"><a href="questionformulation.html#divergentconvergentthinking"><i class="fa fa-check"></i><b>2.2.3</b> Thinking Divergently &amp; Convergently</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="questionformulation.html"><a href="questionformulation.html#summary"><i class="fa fa-check"></i><b>2.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dataacquisition.html"><a href="dataacquisition.html"><i class="fa fa-check"></i><b>3</b> Data Acquisition</a>
<ul>
<li class="chapter" data-level="3.1" data-path="dataacquisition.html"><a href="dataacquisition.html#employee-surveys"><i class="fa fa-check"></i><b>3.1</b> Employee Surveys</a></li>
<li class="chapter" data-level="3.2" data-path="dataacquisition.html"><a href="dataacquisition.html#rating-forms"><i class="fa fa-check"></i><b>3.2</b> Rating Forms</a></li>
<li class="chapter" data-level="3.3" data-path="dataacquisition.html"><a href="dataacquisition.html#surveillance-monitoring"><i class="fa fa-check"></i><b>3.3</b> Surveillance &amp; Monitoring</a></li>
<li class="chapter" data-level="3.4" data-path="dataacquisition.html"><a href="dataacquisition.html#database-queries"><i class="fa fa-check"></i><b>3.4</b> Database Queries</a></li>
<li class="chapter" data-level="3.5" data-path="dataacquisition.html"><a href="dataacquisition.html#scraping"><i class="fa fa-check"></i><b>3.5</b> Scraping</a></li>
<li class="chapter" data-level="3.6" data-path="dataacquisition.html"><a href="dataacquisition.html#summary-1"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="datamanagement.html"><a href="datamanagement.html"><i class="fa fa-check"></i><b>4</b> Data Management</a>
<ul>
<li class="chapter" data-level="4.1" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_clean"><i class="fa fa-check"></i><b>4.1</b> Data Cleaning</a></li>
<li class="chapter" data-level="4.2" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_manipulate"><i class="fa fa-check"></i><b>4.2</b> Data Manipulation &amp; Structuring</a></li>
<li class="chapter" data-level="4.3" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_tools"><i class="fa fa-check"></i><b>4.3</b> Common Data-Management Tools</a></li>
<li class="chapter" data-level="4.4" data-path="datamanagement.html"><a href="datamanagement.html#summary-2"><i class="fa fa-check"></i><b>4.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dataanalysis.html"><a href="dataanalysis.html"><i class="fa fa-check"></i><b>5</b> Data Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="dataanalysis.html"><a href="dataanalysis.html#dataanalysis_toolstechniques"><i class="fa fa-check"></i><b>5.1</b> Tools &amp; Techniques</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="dataanalysis.html"><a href="dataanalysis.html#mathematics"><i class="fa fa-check"></i><b>5.1.1</b> Mathematics</a></li>
<li class="chapter" data-level="5.1.2" data-path="dataanalysis.html"><a href="dataanalysis.html#statistics"><i class="fa fa-check"></i><b>5.1.2</b> Statistics</a></li>
<li class="chapter" data-level="5.1.3" data-path="dataanalysis.html"><a href="dataanalysis.html#machinelearning"><i class="fa fa-check"></i><b>5.1.3</b> Machine Learning</a></li>
<li class="chapter" data-level="5.1.4" data-path="dataanalysis.html"><a href="dataanalysis.html#computationalmodelsimulation"><i class="fa fa-check"></i><b>5.1.4</b> Computational Modeling &amp; Simulations</a></li>
<li class="chapter" data-level="5.1.5" data-path="dataanalysis.html"><a href="dataanalysis.html#textqualitativeanalyses"><i class="fa fa-check"></i><b>5.1.5</b> Text Analyses &amp; Qualitative Analyses</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="dataanalysis.html"><a href="dataanalysis.html#continuum_dataanalytics"><i class="fa fa-check"></i><b>5.2</b> Continuum of Data Analytics</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="dataanalysis.html"><a href="dataanalysis.html#descriptive_analytics"><i class="fa fa-check"></i><b>5.2.1</b> Descriptive Analytics</a></li>
<li class="chapter" data-level="5.2.2" data-path="dataanalysis.html"><a href="dataanalysis.html#predictish_analytics"><i class="fa fa-check"></i><b>5.2.2</b> Predict-ish Analytics</a></li>
<li class="chapter" data-level="5.2.3" data-path="dataanalysis.html"><a href="dataanalysis.html#predictive_analytics"><i class="fa fa-check"></i><b>5.2.3</b> Predictive Analytics</a></li>
<li class="chapter" data-level="5.2.4" data-path="dataanalysis.html"><a href="dataanalysis.html#prescriptive_analytics"><i class="fa fa-check"></i><b>5.2.4</b> Prescriptive Analytics</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="dataanalysis.html"><a href="dataanalysis.html#summary-3"><i class="fa fa-check"></i><b>5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html"><i class="fa fa-check"></i><b>6</b> Data Interpretation &amp; Storytelling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#datainterpretation"><i class="fa fa-check"></i><b>6.1</b> Data Interpretation</a></li>
<li class="chapter" data-level="6.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling"><i class="fa fa-check"></i><b>6.2</b> Storytelling</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#structure"><i class="fa fa-check"></i><b>6.2.1</b> Structure</a></li>
<li class="chapter" data-level="6.2.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#clarity-parsimony"><i class="fa fa-check"></i><b>6.2.2</b> Clarity &amp; Parsimony</a></li>
<li class="chapter" data-level="6.2.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#influence-persuasion"><i class="fa fa-check"></i><b>6.2.3</b> Influence &amp; Persuasion</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling_withdata"><i class="fa fa-check"></i><b>6.3</b> Storytelling with Data</a></li>
<li class="chapter" data-level="6.4" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#summary-4"><i class="fa fa-check"></i><b>6.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html"><i class="fa fa-check"></i><b>7</b> Deployment &amp; Implementation</a></li>
<li class="part"><span><b>II Introduction to R</b></span></li>
<li class="chapter" data-level="8" data-path="overviewR.html"><a href="overviewR.html"><i class="fa fa-check"></i><b>8</b> Overview of R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="8.1" data-path="overviewR.html"><a href="overviewR.html#R_overview"><i class="fa fa-check"></i><b>8.1</b> R Programming Language</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="overviewR.html"><a href="overviewR.html#R_what"><i class="fa fa-check"></i><b>8.1.1</b> What Is R?</a></li>
<li class="chapter" data-level="8.1.2" data-path="overviewR.html"><a href="overviewR.html#R_why"><i class="fa fa-check"></i><b>8.1.2</b> Why Use R?</a></li>
<li class="chapter" data-level="8.1.3" data-path="overviewR.html"><a href="overviewR.html#R_who"><i class="fa fa-check"></i><b>8.1.3</b> Who Uses R?</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="overviewR.html"><a href="overviewR.html#RStudio_overview"><i class="fa fa-check"></i><b>8.2</b> RStudio</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="overviewR.html"><a href="overviewR.html#RStudio_what"><i class="fa fa-check"></i><b>8.2.1</b> What is RStudio?</a></li>
<li class="chapter" data-level="8.2.2" data-path="overviewR.html"><a href="overviewR.html#RStudio_why"><i class="fa fa-check"></i><b>8.2.2</b> Why RStudio?</a></li>
<li class="chapter" data-level="8.2.3" data-path="overviewR.html"><a href="overviewR.html#RStudio_who"><i class="fa fa-check"></i><b>8.2.3</b> Who Uses RStudio?</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="overviewR.html"><a href="overviewR.html#packages_overview"><i class="fa fa-check"></i><b>8.3</b> Packages</a></li>
<li class="chapter" data-level="8.4" data-path="overviewR.html"><a href="overviewR.html#summary-5"><i class="fa fa-check"></i><b>8.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>9</b> Installing R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="9.1" data-path="install.html"><a href="install.html#installR"><i class="fa fa-check"></i><b>9.1</b> Downloading &amp; Installing R</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="install.html"><a href="install.html#for-windows-operation-systems"><i class="fa fa-check"></i><b>9.1.1</b> For Windows Operation Systems</a></li>
<li class="chapter" data-level="9.1.2" data-path="install.html"><a href="install.html#for-mac-operating-systems"><i class="fa fa-check"></i><b>9.1.2</b> For Mac Operating Systems</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="install.html"><a href="install.html#installRStudio"><i class="fa fa-check"></i><b>9.2</b> Downloading &amp; Installing RStudio</a></li>
<li class="chapter" data-level="9.3" data-path="install.html"><a href="install.html#summary-6"><i class="fa fa-check"></i><b>9.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="gettingstarted.html"><a href="gettingstarted.html"><i class="fa fa-check"></i><b>10</b> Getting Started with R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="10.1" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation-to-rstudio"><i class="fa fa-check"></i><b>10.1</b> Orientation to RStudio</a></li>
<li class="chapter" data-level="10.2" data-path="gettingstarted.html"><a href="gettingstarted.html#createRscript"><i class="fa fa-check"></i><b>10.2</b> Creating &amp; Saving an R Script</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-a-new-r-script"><i class="fa fa-check"></i><b>10.2.1</b> Creating a New R Script</a></li>
<li class="chapter" data-level="10.2.2" data-path="gettingstarted.html"><a href="gettingstarted.html#using-an-r-script"><i class="fa fa-check"></i><b>10.2.2</b> Using an R Script</a></li>
<li class="chapter" data-level="10.2.3" data-path="gettingstarted.html"><a href="gettingstarted.html#saving-an-r-script"><i class="fa fa-check"></i><b>10.2.3</b> Saving an R Script</a></li>
<li class="chapter" data-level="10.2.4" data-path="gettingstarted.html"><a href="gettingstarted.html#opening-a-saved-r-script"><i class="fa fa-check"></i><b>10.2.4</b> Opening a Saved R Script</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-an-rstudio-project"><i class="fa fa-check"></i><b>10.3</b> Creating an RStudio Project</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-a-new-rstudio-project"><i class="fa fa-check"></i><b>10.3.1</b> Creating a New RStudio Project</a></li>
<li class="chapter" data-level="10.3.2" data-path="gettingstarted.html"><a href="gettingstarted.html#opening-an-existing-rstudio-project"><i class="fa fa-check"></i><b>10.3.2</b> Opening an Existing RStudio Project</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation-to-written-tutorials"><i class="fa fa-check"></i><b>10.4</b> Orientation to Written Tutorials</a></li>
<li class="chapter" data-level="10.5" data-path="gettingstarted.html"><a href="gettingstarted.html#summary-7"><i class="fa fa-check"></i><b>10.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="gentleintro.html"><a href="gentleintro.html"><i class="fa fa-check"></i><b>11</b> Basic Features and Operations of the R Language</a>
<ul>
<li class="chapter" data-level="11.1" data-path="gentleintro.html"><a href="gentleintro.html#r_as_calculator"><i class="fa fa-check"></i><b>11.1</b> R as a Calculator</a></li>
<li class="chapter" data-level="11.2" data-path="gentleintro.html"><a href="gentleintro.html#functions"><i class="fa fa-check"></i><b>11.2</b> Functions</a></li>
<li class="chapter" data-level="11.3" data-path="gentleintro.html"><a href="gentleintro.html#packages"><i class="fa fa-check"></i><b>11.3</b> Packages</a></li>
<li class="chapter" data-level="11.4" data-path="gentleintro.html"><a href="gentleintro.html#variableassignment"><i class="fa fa-check"></i><b>11.4</b> Variable Assignment</a></li>
<li class="chapter" data-level="11.5" data-path="gentleintro.html"><a href="gentleintro.html#typesofdata"><i class="fa fa-check"></i><b>11.5</b> Types of Data</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="gentleintro.html"><a href="gentleintro.html#numeric-data"><i class="fa fa-check"></i><b>11.5.1</b> <code>numeric</code> Data</a></li>
<li class="chapter" data-level="11.5.2" data-path="gentleintro.html"><a href="gentleintro.html#character-data"><i class="fa fa-check"></i><b>11.5.2</b> <code>character</code> Data</a></li>
<li class="chapter" data-level="11.5.3" data-path="gentleintro.html"><a href="gentleintro.html#date-data"><i class="fa fa-check"></i><b>11.5.3</b> <code>Date</code> Data</a></li>
<li class="chapter" data-level="11.5.4" data-path="gentleintro.html"><a href="gentleintro.html#logical-data"><i class="fa fa-check"></i><b>11.5.4</b> <code>logical</code> Data</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="gentleintro.html"><a href="gentleintro.html#vectors"><i class="fa fa-check"></i><b>11.6</b> Vectors</a></li>
<li class="chapter" data-level="11.7" data-path="gentleintro.html"><a href="gentleintro.html#lists"><i class="fa fa-check"></i><b>11.7</b> Lists</a></li>
<li class="chapter" data-level="11.8" data-path="gentleintro.html"><a href="gentleintro.html#dataframes"><i class="fa fa-check"></i><b>11.8</b> Data Frames</a></li>
<li class="chapter" data-level="11.9" data-path="gentleintro.html"><a href="gentleintro.html#annotate"><i class="fa fa-check"></i><b>11.9</b> Annotations</a></li>
<li class="chapter" data-level="11.10" data-path="gentleintro.html"><a href="gentleintro.html#summary-8"><i class="fa fa-check"></i><b>11.10</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="setwd.html"><a href="setwd.html"><i class="fa fa-check"></i><b>12</b> Setting a Working Directory</a>
<ul>
<li class="chapter" data-level="12.0.1" data-path="setwd.html"><a href="setwd.html#identify-the-current-working-directory"><i class="fa fa-check"></i><b>12.0.1</b> Identify the Current Working Directory</a></li>
<li class="chapter" data-level="12.0.2" data-path="setwd.html"><a href="setwd.html#set-a-new-working-directory"><i class="fa fa-check"></i><b>12.0.2</b> Set a New Working Directory</a></li>
<li class="chapter" data-level="12.1" data-path="setwd.html"><a href="setwd.html#summary-9"><i class="fa fa-check"></i><b>12.1</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>III Data Acquisition &amp; Management</b></span></li>
<li class="chapter" data-level="13" data-path="read.html"><a href="read.html"><i class="fa fa-check"></i><b>13</b> Reading Data into R</a>
<ul>
<li class="chapter" data-level="13.1" data-path="read.html"><a href="read.html#readcsv"><i class="fa fa-check"></i><b>13.1</b> Read a .csv File</a></li>
<li class="chapter" data-level="13.2" data-path="read.html"><a href="read.html#readxlsx"><i class="fa fa-check"></i><b>13.2</b> Read a .xlsx File</a></li>
<li class="chapter" data-level="13.3" data-path="read.html"><a href="read.html#read_summary"><i class="fa fa-check"></i><b>13.3</b> Summary</a></li>
<li class="chapter" data-level="13.4" data-path="read.html"><a href="read.html#read_supplement"><i class="fa fa-check"></i><b>13.4</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="read.html"><a href="read.html#read_additionalfunctions"><i class="fa fa-check"></i><b>13.4.1</b> Additional Functions to Read a .csv File</a></li>
<li class="chapter" data-level="13.4.2" data-path="read.html"><a href="read.html#read_skiprows"><i class="fa fa-check"></i><b>13.4.2</b> Skip Rows of Data During Read</a></li>
<li class="chapter" data-level="13.4.3" data-path="read.html"><a href="read.html#listdatafiles"><i class="fa fa-check"></i><b>13.4.3</b> List Data File Names in Working Directory</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="addnames.html"><a href="addnames.html"><i class="fa fa-check"></i><b>14</b> Removing, Adding, &amp; Changing Variable Names</a>
<ul>
<li class="chapter" data-level="14.1" data-path="addnames.html"><a href="addnames.html#remove_variablenames"><i class="fa fa-check"></i><b>14.1</b> Remove Variable Names from a Data Frame Object</a></li>
<li class="chapter" data-level="14.2" data-path="addnames.html"><a href="addnames.html#add_variablenames"><i class="fa fa-check"></i><b>14.2</b> Add Variable Names to a Data Frame Object</a></li>
<li class="chapter" data-level="14.3" data-path="addnames.html"><a href="addnames.html#change_variablenames"><i class="fa fa-check"></i><b>14.3</b> Change Specific Variable Names in a Data Frame Object</a></li>
<li class="chapter" data-level="14.4" data-path="addnames.html"><a href="addnames.html#summary-10"><i class="fa fa-check"></i><b>14.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="write.html"><a href="write.html"><i class="fa fa-check"></i><b>15</b> Writing Data from R</a>
<ul>
<li class="chapter" data-level="15.1" data-path="write.html"><a href="write.html#write-data-frame-to-working-directory"><i class="fa fa-check"></i><b>15.1</b> Write Data Frame to Working Directory</a></li>
<li class="chapter" data-level="15.2" data-path="write.html"><a href="write.html#write-table-to-working-directory"><i class="fa fa-check"></i><b>15.2</b> Write Table to Working Directory</a></li>
<li class="chapter" data-level="15.3" data-path="write.html"><a href="write.html#summary-11"><i class="fa fa-check"></i><b>15.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>16</b> Arranging (Sorting) Data</a>
<ul>
<li class="chapter" data-level="16.1" data-path="arrange.html"><a href="arrange.html#arrangebyvalues"><i class="fa fa-check"></i><b>16.1</b> Arrange (Sort) Data</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="arrange.html"><a href="arrange.html#opt1_arrange_withpipe"><i class="fa fa-check"></i><b>16.1.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="16.1.2" data-path="arrange.html"><a href="arrange.html#opt1_arrange_withoutpipe"><i class="fa fa-check"></i><b>16.1.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="arrange.html"><a href="arrange.html#summary-12"><i class="fa fa-check"></i><b>16.2</b> Summary</a></li>
<li class="chapter" data-level="16.3" data-path="arrange.html"><a href="arrange.html#arrange_supplement"><i class="fa fa-check"></i><b>16.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="arrange.html"><a href="arrange.html#arrange_orderfunction"><i class="fa fa-check"></i><b>16.3.1</b> <code>order</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="join.html"><a href="join.html"><i class="fa fa-check"></i><b>17</b> Joining (Merging) Data</a>
<ul>
<li class="chapter" data-level="17.1" data-path="join.html"><a href="join.html#horizontaljoin"><i class="fa fa-check"></i><b>17.1</b> Horizontal Join (Merge)</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="join.html"><a href="join.html#opt2_join_withpipe"><i class="fa fa-check"></i><b>17.1.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="17.1.2" data-path="join.html"><a href="join.html#opt2_join_withoutpipe"><i class="fa fa-check"></i><b>17.1.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="join.html"><a href="join.html#verticaljoin"><i class="fa fa-check"></i><b>17.2</b> Vertical Join (Merge)</a></li>
<li class="chapter" data-level="17.3" data-path="join.html"><a href="join.html#summary-13"><i class="fa fa-check"></i><b>17.3</b> Summary</a></li>
<li class="chapter" data-level="17.4" data-path="join.html"><a href="join.html#join_supplement"><i class="fa fa-check"></i><b>17.4</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="join.html"><a href="join.html#join_mergefunction"><i class="fa fa-check"></i><b>17.4.1</b> <code>merge</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>18</b> Filtering Data</a>
<ul>
<li class="chapter" data-level="18.1" data-path="filter.html"><a href="filter.html#filter_cases"><i class="fa fa-check"></i><b>18.1</b> Filter Cases from Data Frame</a>
<ul>
<li class="chapter" data-level="18.1.1" data-path="filter.html"><a href="filter.html#with-pipes"><i class="fa fa-check"></i><b>18.1.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="18.1.2" data-path="filter.html"><a href="filter.html#without-pipes"><i class="fa fa-check"></i><b>18.1.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="filter.html"><a href="filter.html#remove-single-variable-from-data-frame"><i class="fa fa-check"></i><b>18.2</b> Remove Single Variable from Data Frame</a></li>
<li class="chapter" data-level="18.3" data-path="filter.html"><a href="filter.html#select_multiplevariables"><i class="fa fa-check"></i><b>18.3</b> Select Multiple Variables from Data Frame</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="filter.html"><a href="filter.html#with-pipe"><i class="fa fa-check"></i><b>18.3.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="18.3.2" data-path="filter.html"><a href="filter.html#without-pipe"><i class="fa fa-check"></i><b>18.3.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="filter.html"><a href="filter.html#remove_multiplevariables"><i class="fa fa-check"></i><b>18.4</b> Remove Multiple Variables from Data Frame</a>
<ul>
<li class="chapter" data-level="18.4.1" data-path="filter.html"><a href="filter.html#with-pipe-1"><i class="fa fa-check"></i><b>18.4.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="18.4.2" data-path="filter.html"><a href="filter.html#without-pipe-1"><i class="fa fa-check"></i><b>18.4.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="filter.html"><a href="filter.html#summary-14"><i class="fa fa-check"></i><b>18.5</b> Summary</a></li>
<li class="chapter" data-level="18.6" data-path="filter.html"><a href="filter.html#filter_supplement"><i class="fa fa-check"></i><b>18.6</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="18.6.1" data-path="filter.html"><a href="filter.html#filter_subset_supplement"><i class="fa fa-check"></i><b>18.6.1</b> <code>subset</code> Function from Base R</a></li>
<li class="chapter" data-level="18.6.2" data-path="filter.html"><a href="filter.html#str_detect_supp"><i class="fa fa-check"></i><b>18.6.2</b> Filter by Pattern Contained within String</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="clean.html"><a href="clean.html"><i class="fa fa-check"></i><b>19</b> Cleaning Data</a>
<ul>
<li class="chapter" data-level="19.1" data-path="clean.html"><a href="clean.html#review-data"><i class="fa fa-check"></i><b>19.1</b> Review Data</a></li>
<li class="chapter" data-level="19.2" data-path="clean.html"><a href="clean.html#clean-data"><i class="fa fa-check"></i><b>19.2</b> Clean Data</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="clean.html"><a href="clean.html#replace-a-specific-value-for-a-specific-case"><i class="fa fa-check"></i><b>19.2.1</b> Replace a Specific Value for a Specific Case</a></li>
<li class="chapter" data-level="19.2.2" data-path="clean.html"><a href="clean.html#replace-a-specific-value-for-all-cases-with-a-particular-value"><i class="fa fa-check"></i><b>19.2.2</b> Replace a Specific Value for All Cases with a Particular Value</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="clean.html"><a href="clean.html#rename-variables"><i class="fa fa-check"></i><b>19.3</b> Rename Variables</a></li>
<li class="chapter" data-level="19.4" data-path="clean.html"><a href="clean.html#other-approaches-to-cleaning-data"><i class="fa fa-check"></i><b>19.4</b> Other Approaches to Cleaning Data</a>
<ul>
<li class="chapter" data-level="19.4.1" data-path="clean.html"><a href="clean.html#changing-the-case-of-variable-names"><i class="fa fa-check"></i><b>19.4.1</b> Changing the Case of Variable Names</a></li>
<li class="chapter" data-level="19.4.2" data-path="clean.html"><a href="clean.html#changing-the-case-of-character-variable-values"><i class="fa fa-check"></i><b>19.4.2</b> Changing the Case of Character Variable Values</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="clean.html"><a href="clean.html#summary-15"><i class="fa fa-check"></i><b>19.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="aggregatesegment.html"><a href="aggregatesegment.html"><i class="fa fa-check"></i><b>20</b> Aggregating &amp; Segmenting Data</a>
<ul>
<li class="chapter" data-level="20.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup"><i class="fa fa-check"></i><b>20.1</b> Counts By Group</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup_pipes"><i class="fa fa-check"></i><b>20.1.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="20.1.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup_nopipes"><i class="fa fa-check"></i><b>20.1.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup"><i class="fa fa-check"></i><b>20.2</b> Measures of Central Tendency and Dispersion By Group</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup_pipes"><i class="fa fa-check"></i><b>20.2.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="20.2.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup_nopipes"><i class="fa fa-check"></i><b>20.2.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable"><i class="fa fa-check"></i><b>20.3</b> Add Variable to Data Frame Containing Aggregated Values</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable_pipes"><i class="fa fa-check"></i><b>20.3.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="20.3.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable_nopipes"><i class="fa fa-check"></i><b>20.3.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="aggregatesegment.html"><a href="aggregatesegment.html#visualize_bygroup"><i class="fa fa-check"></i><b>20.4</b> Visualize Data By Group</a></li>
<li class="chapter" data-level="20.5" data-path="aggregatesegment.html"><a href="aggregatesegment.html#summary-16"><i class="fa fa-check"></i><b>20.5</b> Summary</a></li>
<li class="chapter" data-level="20.6" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_supplement"><i class="fa fa-check"></i><b>20.6</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="20.6.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_subset_supplement"><i class="fa fa-check"></i><b>20.6.1</b> <code>describeBy</code> Function from <code>psych</code> Package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="21" data-path="manipulate.html"><a href="manipulate.html"><i class="fa fa-check"></i><b>21</b> Manipulating &amp; Restructuring Data</a>
<ul>
<li class="chapter" data-level="21.1" data-path="manipulate.html"><a href="manipulate.html#widetolong"><i class="fa fa-check"></i><b>21.1</b> Wide-to-Long Format Data Manipulation</a>
<ul>
<li class="chapter" data-level="21.1.1" data-path="manipulate.html"><a href="manipulate.html#widetolong_withpipe"><i class="fa fa-check"></i><b>21.1.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="21.1.2" data-path="manipulate.html"><a href="manipulate.html#widetolong_withoutpipe"><i class="fa fa-check"></i><b>21.1.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="manipulate.html"><a href="manipulate.html#longtowide"><i class="fa fa-check"></i><b>21.2</b> Long-to-Wide Format Data Manipulation</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="manipulate.html"><a href="manipulate.html#longtowide_withpipe"><i class="fa fa-check"></i><b>21.2.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="21.2.2" data-path="manipulate.html"><a href="manipulate.html#longtowide_withoutpipe"><i class="fa fa-check"></i><b>21.2.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="manipulate.html"><a href="manipulate.html#summary-17"><i class="fa fa-check"></i><b>21.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="center.html"><a href="center.html"><i class="fa fa-check"></i><b>22</b> Centering &amp; Standardizing Variables</a>
<ul>
<li class="chapter" data-level="22.1" data-path="center.html"><a href="center.html#grandmean_center"><i class="fa fa-check"></i><b>22.1</b> Grand-Mean Centering Variables</a>
<ul>
<li class="chapter" data-level="22.1.1" data-path="center.html"><a href="center.html#mean_function_center"><i class="fa fa-check"></i><b>22.1.1</b> Option 1: Basic Arithmetic and <code>mean</code> Function from Base R</a></li>
<li class="chapter" data-level="22.1.2" data-path="center.html"><a href="center.html#scale_function_center"><i class="fa fa-check"></i><b>22.1.2</b> Option 2: <code>scale</code> Function from Base R</a></li>
<li class="chapter" data-level="22.1.3" data-path="center.html"><a href="center.html#mutate_function_center"><i class="fa fa-check"></i><b>22.1.3</b> Option 3: <code>mutate</code> Function from <code>dplyr</code> and <code>mean</code> Function from Base R</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="center.html"><a href="center.html#standardize_center"><i class="fa fa-check"></i><b>22.2</b> Standardizing Variables</a>
<ul>
<li class="chapter" data-level="22.2.1" data-path="center.html"><a href="center.html#scale_function_standardize"><i class="fa fa-check"></i><b>22.2.1</b> Option 1: <code>scale</code> Function from Base R</a></li>
<li class="chapter" data-level="22.2.2" data-path="center.html"><a href="center.html#mutate_function_standardize"><i class="fa fa-check"></i><b>22.2.2</b> Option 2: <code>mutate</code> Function from <code>dplyr</code> and <code>scale</code> Function from Base R</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="center.html"><a href="center.html#summary_center"><i class="fa fa-check"></i><b>22.3</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>IV Employee Demographics</b></span></li>
<li class="chapter" data-level="23" data-path="employeedemographics.html"><a href="employeedemographics.html"><i class="fa fa-check"></i><b>23</b> Introduction to Employee Demographics</a></li>
<li class="chapter" data-level="24" data-path="descriptives.html"><a href="descriptives.html"><i class="fa fa-check"></i><b>24</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="24.1" data-path="descriptives.html"><a href="descriptives.html#measurementscales"><i class="fa fa-check"></i><b>24.1</b> Measurement Scales</a>
<ul>
<li class="chapter" data-level="24.1.1" data-path="descriptives.html"><a href="descriptives.html#measurementscales_nominal"><i class="fa fa-check"></i><b>24.1.1</b> Nominal</a></li>
<li class="chapter" data-level="24.1.2" data-path="descriptives.html"><a href="descriptives.html#measurementscales_ordinal"><i class="fa fa-check"></i><b>24.1.2</b> Ordinal</a></li>
<li class="chapter" data-level="24.1.3" data-path="descriptives.html"><a href="descriptives.html#measurementscales_interval"><i class="fa fa-check"></i><b>24.1.3</b> Interval</a></li>
<li class="chapter" data-level="24.1.4" data-path="descriptives.html"><a href="descriptives.html#measurementscales_ratio"><i class="fa fa-check"></i><b>24.1.4</b> Ratio</a></li>
</ul></li>
<li class="chapter" data-level="24.2" data-path="descriptives.html"><a href="descriptives.html#constructs_measures_measurementscales"><i class="fa fa-check"></i><b>24.2</b> Constructs, Measures, &amp; Measurement Scales</a></li>
<li class="chapter" data-level="24.3" data-path="descriptives.html"><a href="descriptives.html#typesof_descriptivestatistics"><i class="fa fa-check"></i><b>24.3</b> Types of Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="24.3.1" data-path="descriptives.html"><a href="descriptives.html#descriptivestatistics_counts"><i class="fa fa-check"></i><b>24.3.1</b> Counts</a></li>
<li class="chapter" data-level="24.3.2" data-path="descriptives.html"><a href="descriptives.html#descriptivestatistics_centraltendency"><i class="fa fa-check"></i><b>24.3.2</b> Measures of Central Tendency &amp; Dispersion</a></li>
<li class="chapter" data-level="24.3.3" data-path="descriptives.html"><a href="descriptives.html#video-tutorials"><i class="fa fa-check"></i><b>24.3.3</b> Video Tutorials</a></li>
</ul></li>
<li class="chapter" data-level="24.4" data-path="descriptives.html"><a href="descriptives.html#determine_measurementscale"><i class="fa fa-check"></i><b>24.4</b> Determine the Measurement Scale</a></li>
<li class="chapter" data-level="24.5" data-path="descriptives.html"><a href="descriptives.html#describe_nominal_ordinal"><i class="fa fa-check"></i><b>24.5</b> Describe Nominal &amp; Ordinal (Categorical) Variables</a>
<ul>
<li class="chapter" data-level="24.5.1" data-path="descriptives.html"><a href="descriptives.html#compute_counts"><i class="fa fa-check"></i><b>24.5.1</b> Compute Counts &amp; Frequencies</a></li>
<li class="chapter" data-level="24.5.2" data-path="descriptives.html"><a href="descriptives.html#datavisualizations_nominal_ordinal"><i class="fa fa-check"></i><b>24.5.2</b> Create Data Visualizations</a></li>
</ul></li>
<li class="chapter" data-level="24.6" data-path="descriptives.html"><a href="descriptives.html#describe_interval_ratio"><i class="fa fa-check"></i><b>24.6</b> Describe Interval &amp; Ratio (Continuous) Variables</a>
<ul>
<li class="chapter" data-level="24.6.1" data-path="descriptives.html"><a href="descriptives.html#datavisualizations_interval_ratio"><i class="fa fa-check"></i><b>24.6.1</b> Create Data Visualizations</a></li>
<li class="chapter" data-level="24.6.2" data-path="descriptives.html"><a href="descriptives.html#compute_measures_centraltendency_dispersion"><i class="fa fa-check"></i><b>24.6.2</b> Compute Measures of Central Tendency &amp; Dispersion</a></li>
</ul></li>
<li class="chapter" data-level="24.7" data-path="descriptives.html"><a href="descriptives.html#summary_descriptives"><i class="fa fa-check"></i><b>24.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="crosstabs.html"><a href="crosstabs.html"><i class="fa fa-check"></i><b>25</b> Cross-Tabulations</a>
<ul>
<li class="chapter" data-level="25.0.1" data-path="crosstabs.html"><a href="crosstabs.html#video-tutorial-16"><i class="fa fa-check"></i><b>25.0.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="25.1" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs"><i class="fa fa-check"></i><b>25.1</b> Two-Way Cross-Tabulation</a>
<ul>
<li class="chapter" data-level="25.1.1" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs_table"><i class="fa fa-check"></i><b>25.1.1</b> Option 1: Using the <code>table</code> Function</a></li>
<li class="chapter" data-level="25.1.2" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs_xtabs"><i class="fa fa-check"></i><b>25.1.2</b> Option 2: Using the <code>xtabs</code> Function</a></li>
<li class="chapter" data-level="25.1.3" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs_CrossTable"><i class="fa fa-check"></i><b>25.1.3</b> Option 3: Using the <code>CrossTable</code> Function</a></li>
</ul></li>
<li class="chapter" data-level="25.2" data-path="crosstabs.html"><a href="crosstabs.html#threeway_crosstabs"><i class="fa fa-check"></i><b>25.2</b> Three-Way Cross-Tabulation</a>
<ul>
<li class="chapter" data-level="25.2.1" data-path="crosstabs.html"><a href="crosstabs.html#threeway_crosstabs_table"><i class="fa fa-check"></i><b>25.2.1</b> Option 1: Using the <code>table</code> Function</a></li>
<li class="chapter" data-level="25.2.2" data-path="crosstabs.html"><a href="crosstabs.html#threeway_crosstabs_xtabs"><i class="fa fa-check"></i><b>25.2.2</b> Option 2: Using the <code>xtabs</code> Function</a></li>
</ul></li>
<li class="chapter" data-level="25.3" data-path="crosstabs.html"><a href="crosstabs.html#summary-18"><i class="fa fa-check"></i><b>25.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="pivottables.html"><a href="pivottables.html"><i class="fa fa-check"></i><b>26</b> Pivot Tables</a>
<ul>
<li class="chapter" data-level="26.0.1" data-path="pivottables.html"><a href="pivottables.html#video-tutorial-17"><i class="fa fa-check"></i><b>26.0.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="26.1" data-path="pivottables.html"><a href="pivottables.html#create_pivottables"><i class="fa fa-check"></i><b>26.1</b> Create a Pivot Table</a></li>
<li class="chapter" data-level="26.2" data-path="pivottables.html"><a href="pivottables.html#summary-19"><i class="fa fa-check"></i><b>26.2</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>V Employee Surveys</b></span></li>
<li class="chapter" data-level="27" data-path="employeesurveys.html"><a href="employeesurveys.html"><i class="fa fa-check"></i><b>27</b> Introduction to Employee Surveys</a></li>
<li class="part"><span><b>VI Employee Training</b></span></li>
<li class="chapter" data-level="28" data-path="employeetraining.html"><a href="employeetraining.html"><i class="fa fa-check"></i><b>28</b> Introduction to Employee Training</a>
<ul>
<li class="chapter" data-level="28.1" data-path="employeetraining.html"><a href="employeetraining.html#trainingevaluation_employeetraining"><i class="fa fa-check"></i><b>28.1</b> Training Evaluation</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="pretestposttest.html"><a href="pretestposttest.html"><i class="fa fa-check"></i><b>29</b> Evaluating a Pre-Test/Post-Test without Control Group Design Using Paired-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="29.1" data-path="pretestposttest.html"><a href="pretestposttest.html#review_psttest"><i class="fa fa-check"></i><b>29.1</b> Review of Paired-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="29.1.1" data-path="pretestposttest.html"><a href="pretestposttest.html#statisticalassumptions_psttest"><i class="fa fa-check"></i><b>29.1.1</b> Statistical Assumptions</a></li>
<li class="chapter" data-level="29.1.2" data-path="pretestposttest.html"><a href="pretestposttest.html#statisticalsignficance_psttest"><i class="fa fa-check"></i><b>29.1.2</b> Statistical Significance</a></li>
<li class="chapter" data-level="29.1.3" data-path="pretestposttest.html"><a href="pretestposttest.html#practicalsignficance_psttest"><i class="fa fa-check"></i><b>29.1.3</b> Practical Significance</a></li>
<li class="chapter" data-level="29.1.4" data-path="pretestposttest.html"><a href="pretestposttest.html#samplewriteup_psttest"><i class="fa fa-check"></i><b>29.1.4</b> Sample Write-Up</a></li>
<li class="chapter" data-level="29.1.5" data-path="pretestposttest.html"><a href="pretestposttest.html#video-tutorial-18"><i class="fa fa-check"></i><b>29.1.5</b> Video Tutorial</a></li>
</ul></li>
<li class="chapter" data-level="29.2" data-path="pretestposttest.html"><a href="pretestposttest.html#estimate_psttest"><i class="fa fa-check"></i><b>29.2</b> Estimate Paired-Samples <em>t</em>-test</a></li>
<li class="chapter" data-level="29.3" data-path="pretestposttest.html"><a href="pretestposttest.html#barchart_psttest"><i class="fa fa-check"></i><b>29.3</b> Visualize Results Using Bar Chart</a>
<ul>
<li class="chapter" data-level="29.3.1" data-path="pretestposttest.html"><a href="pretestposttest.html#barchart_psttest_firstapproach"><i class="fa fa-check"></i><b>29.3.1</b> First Approach</a></li>
<li class="chapter" data-level="29.3.2" data-path="pretestposttest.html"><a href="pretestposttest.html#barchart_psttest_secondapproach"><i class="fa fa-check"></i><b>29.3.2</b> Second Approach</a></li>
</ul></li>
<li class="chapter" data-level="29.4" data-path="pretestposttest.html"><a href="pretestposttest.html#summary_psttest"><i class="fa fa-check"></i><b>29.4</b> Summary</a></li>
<li class="chapter" data-level="29.5" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_supplement"><i class="fa fa-check"></i><b>29.5</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="29.5.1" data-path="pretestposttest.html"><a href="pretestposttest.html#t.test_function_psttest"><i class="fa fa-check"></i><b>29.5.1</b> <code>t.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="30" data-path="posttestonly.html"><a href="posttestonly.html"><i class="fa fa-check"></i><b>30</b> Evaluating a Post-Test-Only with Control Group Design Using Independent-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="30.1" data-path="posttestonly.html"><a href="posttestonly.html#review_isttest"><i class="fa fa-check"></i><b>30.1</b> Review of Independent-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="30.1.1" data-path="posttestonly.html"><a href="posttestonly.html#statisticalassumptions_isttest"><i class="fa fa-check"></i><b>30.1.1</b> Statistical Assumptions</a></li>
<li class="chapter" data-level="30.1.2" data-path="posttestonly.html"><a href="posttestonly.html#statisticalsignficance_isttest"><i class="fa fa-check"></i><b>30.1.2</b> Statistical Significance</a></li>
<li class="chapter" data-level="30.1.3" data-path="posttestonly.html"><a href="posttestonly.html#practicalsignficance_isttest"><i class="fa fa-check"></i><b>30.1.3</b> Practical Significance</a></li>
<li class="chapter" data-level="30.1.4" data-path="posttestonly.html"><a href="posttestonly.html#samplewriteup_isttest"><i class="fa fa-check"></i><b>30.1.4</b> Sample Write-Up</a></li>
<li class="chapter" data-level="30.1.5" data-path="posttestonly.html"><a href="posttestonly.html#video-tutorial-19"><i class="fa fa-check"></i><b>30.1.5</b> Video Tutorial</a></li>
</ul></li>
<li class="chapter" data-level="30.2" data-path="posttestonly.html"><a href="posttestonly.html#estimate_isttest"><i class="fa fa-check"></i><b>30.2</b> Estimate Independent-Samples <em>t</em>-test</a></li>
<li class="chapter" data-level="30.3" data-path="posttestonly.html"><a href="posttestonly.html#barchart_isttest"><i class="fa fa-check"></i><b>30.3</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="30.4" data-path="posttestonly.html"><a href="posttestonly.html#summary_isttest"><i class="fa fa-check"></i><b>30.4</b> Summary</a></li>
<li class="chapter" data-level="30.5" data-path="posttestonly.html"><a href="posttestonly.html#isttest_supplement"><i class="fa fa-check"></i><b>30.5</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="30.5.1" data-path="posttestonly.html"><a href="posttestonly.html#t.test_function_isttest"><i class="fa fa-check"></i><b>30.5.1</b> <code>t.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="31" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html"><i class="fa fa-check"></i><b>31</b> Evaluating a Post-Test-Only with Two Comparison Groups Design Using One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="31.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#review_onewayanova"><i class="fa fa-check"></i><b>31.1</b> Review of One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="31.1.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#post-hoc-pairwise-mean-comparison-tests-posthoc_onewayanova"><i class="fa fa-check"></i><b>31.1.1</b> Post-Hoc Pairwise Mean Comparison Tests {posthoc_onewayanova}</a></li>
<li class="chapter" data-level="31.1.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#statisticalassumptions_onewayanova"><i class="fa fa-check"></i><b>31.1.2</b> Statistical Assumptions</a></li>
<li class="chapter" data-level="31.1.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#statisticalsignficance_onewayanova"><i class="fa fa-check"></i><b>31.1.3</b> Statistical Significance</a></li>
<li class="chapter" data-level="31.1.4" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#practicalsignficance_onewayanova"><i class="fa fa-check"></i><b>31.1.4</b> Practical Significance</a></li>
<li class="chapter" data-level="31.1.5" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#samplewriteup_onewayanova"><i class="fa fa-check"></i><b>31.1.5</b> Sample Write-Up</a></li>
<li class="chapter" data-level="31.1.6" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#video-tutorial-20"><i class="fa fa-check"></i><b>31.1.6</b> Video Tutorial</a></li>
</ul></li>
<li class="chapter" data-level="31.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#teststatisticalassumptions_onewayanova"><i class="fa fa-check"></i><b>31.2</b> Test Statistical Assumptions</a></li>
<li class="chapter" data-level="31.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#estimate_onewayanova"><i class="fa fa-check"></i><b>31.3</b> Estimate One-Way ANOVA</a></li>
<li class="chapter" data-level="31.4" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#visualize-results-using-bar-chart"><i class="fa fa-check"></i><b>31.4</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="31.5" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#summary_onewayanova"><i class="fa fa-check"></i><b>31.5</b> Summary</a></li>
<li class="chapter" data-level="31.6" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_supplement"><i class="fa fa-check"></i><b>31.6</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="31.6.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#aov_function_onewayanova"><i class="fa fa-check"></i><b>31.6.1</b> <code>aov</code> Function from Base R</a></li>
</ul></li>
<li class="chapter" data-level="31.7" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#apatable_onewayanova"><i class="fa fa-check"></i><b>31.7</b> APA-Style Table of Results</a></li>
</ul></li>
<li class="part"><span><b>VII Employee Selection</b></span></li>
<li class="chapter" data-level="32" data-path="selection.html"><a href="selection.html"><i class="fa fa-check"></i><b>32</b> Introduction to Employee Selection</a></li>
<li class="chapter" data-level="33" data-path="disparateimpact.html"><a href="disparateimpact.html"><i class="fa fa-check"></i><b>33</b> Investigating Disparate Impact</a>
<ul>
<li class="chapter" data-level="33.0.1" data-path="disparateimpact.html"><a href="disparateimpact.html#video-tutorial-21"><i class="fa fa-check"></i><b>33.0.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="33.1" data-path="disparateimpact.html"><a href="disparateimpact.html#fourfifthsrule"><i class="fa fa-check"></i><b>33.1</b> 4/5ths Rule</a></li>
<li class="chapter" data-level="33.2" data-path="disparateimpact.html"><a href="disparateimpact.html#chisquaretest_disparateimpact"><i class="fa fa-check"></i><b>33.2</b> Chi-Squared (<span class="math inline">\(\chi^2\)</span>) Test of Independence</a></li>
<li class="chapter" data-level="33.3" data-path="disparateimpact.html"><a href="disparateimpact.html#fisherexacttest"><i class="fa fa-check"></i><b>33.3</b> Fisher Exact Test</a></li>
<li class="chapter" data-level="33.4" data-path="disparateimpact.html"><a href="disparateimpact.html#zdifference_test_disparateimpact"><i class="fa fa-check"></i><b>33.4</b> <span class="math inline">\(Z_{D}\)</span> test</a></li>
<li class="chapter" data-level="33.5" data-path="disparateimpact.html"><a href="disparateimpact.html#z_impactratiotest"><i class="fa fa-check"></i><b>33.5</b> <span class="math inline">\(Z_{IR}\)</span> Test</a></li>
<li class="chapter" data-level="33.6" data-path="disparateimpact.html"><a href="disparateimpact.html#summary_disparatetreatment"><i class="fa fa-check"></i><b>33.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="34" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html"><i class="fa fa-check"></i><b>34</b> Estimating Criterion-Related Validity Using Correlation</a>
<ul>
<li class="chapter" data-level="34.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#review_correlation"><i class="fa fa-check"></i><b>34.1</b> Review of Correlation</a>
<ul>
<li class="chapter" data-level="34.1.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#statisticalassumptions_correlation"><i class="fa fa-check"></i><b>34.1.1</b> Statistical Assumptions</a></li>
<li class="chapter" data-level="34.1.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#statisticalsignficance_correlation"><i class="fa fa-check"></i><b>34.1.2</b> Statistical Significance</a></li>
<li class="chapter" data-level="34.1.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#practicalsignficance_correlation"><i class="fa fa-check"></i><b>34.1.3</b> Practical Significance</a></li>
<li class="chapter" data-level="34.1.4" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#samplewriteup_correlation"><i class="fa fa-check"></i><b>34.1.4</b> Sample Write-Up</a></li>
<li class="chapter" data-level="34.1.5" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#video-tutorial-22"><i class="fa fa-check"></i><b>34.1.5</b> Video Tutorial</a></li>
</ul></li>
<li class="chapter" data-level="34.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#visualize-association-using-a-scatter-plot"><i class="fa fa-check"></i><b>34.2</b> Visualize Association Using a Scatter Plot</a></li>
<li class="chapter" data-level="34.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#estimate_correlation"><i class="fa fa-check"></i><b>34.3</b> Estimate Correlation</a></li>
<li class="chapter" data-level="34.4" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#summary_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.4</b> Summary</a></li>
<li class="chapter" data-level="34.5" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_supplement"><i class="fa fa-check"></i><b>34.5</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="34.5.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#cor_function"><i class="fa fa-check"></i><b>34.5.1</b> <code>cor</code> Function from Base R</a></li>
<li class="chapter" data-level="34.5.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#cortest_function"><i class="fa fa-check"></i><b>34.5.2</b> <code>cor.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="35" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html"><i class="fa fa-check"></i><b>35</b> Predicting Criterion Scores Using Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="35.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#review_slr"><i class="fa fa-check"></i><b>35.1</b> Review of Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="35.1.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#statisticalassumptions_slr"><i class="fa fa-check"></i><b>35.1.1</b> Statistical Assumptions</a></li>
<li class="chapter" data-level="35.1.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#statisticalsignficance_slr"><i class="fa fa-check"></i><b>35.1.2</b> Statistical Signficance</a></li>
<li class="chapter" data-level="35.1.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#practicalsignficance_slr"><i class="fa fa-check"></i><b>35.1.3</b> Practical Significance</a></li>
<li class="chapter" data-level="35.1.4" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#samplewriteup_slr"><i class="fa fa-check"></i><b>35.1.4</b> Sample Write-Up</a></li>
<li class="chapter" data-level="35.1.5" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#review_prediction_slr"><i class="fa fa-check"></i><b>35.1.5</b> Predicting Future Criterion Scores Using Simple Linear Regression</a></li>
<li class="chapter" data-level="35.1.6" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#video-tutorial-23"><i class="fa fa-check"></i><b>35.1.6</b> Video Tutorial</a></li>
<li class="chapter" data-level="35.1.7" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#functions-packages-introduced-19"><i class="fa fa-check"></i><b>35.1.7</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="35.1.8" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#initsteps_slr"><i class="fa fa-check"></i><b>35.1.8</b> Initial Steps</a></li>
</ul></li>
<li class="chapter" data-level="35.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#estimate_slr"><i class="fa fa-check"></i><b>35.2</b> Estimate Simple Linear Regression Model</a>
<ul>
<li class="chapter" data-level="35.2.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#teststatisticalassumptions_slr"><i class="fa fa-check"></i><b>35.2.1</b> Test Statistical Assumptions</a></li>
<li class="chapter" data-level="35.2.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#interpret_slr"><i class="fa fa-check"></i><b>35.2.2</b> Interpret Simple Linear Regression Model Results</a></li>
<li class="chapter" data-level="35.2.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#standardized_slr"><i class="fa fa-check"></i><b>35.2.3</b> Optional: Obtaining Standardized Coefficients</a></li>
</ul></li>
<li class="chapter" data-level="35.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_slr"><i class="fa fa-check"></i><b>35.3</b> Predict Criterion Scores</a></li>
<li class="chapter" data-level="35.4" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#summary_predictingcriterionscores"><i class="fa fa-check"></i><b>35.4</b> Summary</a></li>
<li class="chapter" data-level="35.5" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_supplement"><i class="fa fa-check"></i><b>35.5</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="35.5.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#lm_function_slr"><i class="fa fa-check"></i><b>35.5.1</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="35.5.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predict_function_slr"><i class="fa fa-check"></i><b>35.5.2</b> <code>predict</code> Function from Base R</a></li>
<li class="chapter" data-level="35.5.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#apatable_slr"><i class="fa fa-check"></i><b>35.5.3</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="36" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html"><i class="fa fa-check"></i><b>36</b> Estimating Incremental Validity Using Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="36.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#review_mlr"><i class="fa fa-check"></i><b>36.1</b> Review of Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="36.1.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#statisticalassumptions_mlr"><i class="fa fa-check"></i><b>36.1.1</b> Statistical Assumptions</a></li>
<li class="chapter" data-level="36.1.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#statisticalsignficance_mlr"><i class="fa fa-check"></i><b>36.1.2</b> Statistical Signficance</a></li>
<li class="chapter" data-level="36.1.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#practicalsignficance_mlr"><i class="fa fa-check"></i><b>36.1.3</b> Practical Significance</a></li>
<li class="chapter" data-level="36.1.4" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#samplewriteup_mlr"><i class="fa fa-check"></i><b>36.1.4</b> Sample Write-Up</a></li>
<li class="chapter" data-level="36.1.5" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#video-tutorial-24"><i class="fa fa-check"></i><b>36.1.5</b> Video Tutorial</a></li>
</ul></li>
<li class="chapter" data-level="36.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#estimate_mlr"><i class="fa fa-check"></i><b>36.2</b> Estimate Multiple Linear Regression Model</a>
<ul>
<li class="chapter" data-level="36.2.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#teststatisticalassumptions_mlr"><i class="fa fa-check"></i><b>36.2.1</b> Test Statistical Assumptions</a></li>
<li class="chapter" data-level="36.2.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#interpret_mlr"><i class="fa fa-check"></i><b>36.2.2</b> Interpret Multiple Linear Regression Model Results</a></li>
<li class="chapter" data-level="36.2.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#standardized_mlr"><i class="fa fa-check"></i><b>36.2.3</b> Optional: Obtaining Standardized Coefficients</a></li>
</ul></li>
<li class="chapter" data-level="36.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#summary_incrementalvalidity"><i class="fa fa-check"></i><b>36.3</b> Summary</a></li>
<li class="chapter" data-level="36.4" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_supplement"><i class="fa fa-check"></i><b>36.4</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="36.4.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#lm_function_mlr"><i class="fa fa-check"></i><b>36.4.1</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="36.4.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#apatable_mlr"><i class="fa fa-check"></i><b>36.4.2</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="37" data-path="compensatory.html"><a href="compensatory.html"><i class="fa fa-check"></i><b>37</b> Compensatory Approach to Selection Decisions</a>
<ul>
<li class="chapter" data-level="37.1" data-path="compensatory.html"><a href="compensatory.html#review_compensatory"><i class="fa fa-check"></i><b>37.1</b> Review of Compensatory Approach</a>
<ul>
<li class="chapter" data-level="37.1.1" data-path="compensatory.html"><a href="compensatory.html#video-tutorial-25"><i class="fa fa-check"></i><b>37.1.1</b> Video Tutorial</a></li>
</ul></li>
<li class="chapter" data-level="37.2" data-path="compensatory.html"><a href="compensatory.html#estimate_compensatory"><i class="fa fa-check"></i><b>37.2</b> Estimate Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="37.3" data-path="compensatory.html"><a href="compensatory.html#predictcriterionscores_compensatory"><i class="fa fa-check"></i><b>37.3</b> Predict Criterion Scores</a></li>
<li class="chapter" data-level="37.4" data-path="compensatory.html"><a href="compensatory.html#summary_compensatory"><i class="fa fa-check"></i><b>37.4</b> Summary</a></li>
<li class="chapter" data-level="37.5" data-path="compensatory.html"><a href="compensatory.html#compensatory_supplement"><i class="fa fa-check"></i><b>37.5</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="37.5.1" data-path="compensatory.html"><a href="compensatory.html#lm_predict_functions_compensatory"><i class="fa fa-check"></i><b>37.5.1</b> <code>lm</code> &amp; <code>predict</code> Functions from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="38" data-path="multiplecutoff.html"><a href="multiplecutoff.html"><i class="fa fa-check"></i><b>38</b> Noncompensatory Approach to Selection Decisions</a>
<ul>
<li class="chapter" data-level="38.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#review_multiplecutoff"><i class="fa fa-check"></i><b>38.1</b> Review of Noncompensatory Approach</a></li>
<li class="chapter" data-level="38.2" data-path="multiplecutoff.html"><a href="multiplecutoff.html#createcutoffscores_multiplecutoff"><i class="fa fa-check"></i><b>38.2</b> Create Cutoff Scores</a></li>
<li class="chapter" data-level="38.3" data-path="multiplecutoff.html"><a href="multiplecutoff.html#applycutoffscores_multiplecutoff"><i class="fa fa-check"></i><b>38.3</b> Apply Cutoff Scores to Make Selection Decisions</a></li>
<li class="chapter" data-level="38.4" data-path="multiplecutoff.html"><a href="multiplecutoff.html#summary_multiplecutoff"><i class="fa fa-check"></i><b>38.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="39" data-path="differentialprediction.html"><a href="differentialprediction.html"><i class="fa fa-check"></i><b>39</b> Testing for Differential Prediction Using Moderated Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="39.1" data-path="differentialprediction.html"><a href="differentialprediction.html#review_mmlr"><i class="fa fa-check"></i><b>39.1</b> Review of Moderated Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="39.1.1" data-path="differentialprediction.html"><a href="differentialprediction.html#moderation_mmlr"><i class="fa fa-check"></i><b>39.1.1</b> Moderation</a></li>
<li class="chapter" data-level="39.1.2" data-path="differentialprediction.html"><a href="differentialprediction.html#centering_mmlr"><i class="fa fa-check"></i><b>39.1.2</b> Centering Predictor &amp; Moderator Variables</a></li>
<li class="chapter" data-level="39.1.3" data-path="differentialprediction.html"><a href="differentialprediction.html#mmlr_mmlr"><i class="fa fa-check"></i><b>39.1.3</b> Moderated Multiple Linear Regression</a></li>
<li class="chapter" data-level="39.1.4" data-path="differentialprediction.html"><a href="differentialprediction.html#statisticalassumptions_mmlr"><i class="fa fa-check"></i><b>39.1.4</b> Statistical Assumptions</a></li>
<li class="chapter" data-level="39.1.5" data-path="differentialprediction.html"><a href="differentialprediction.html#statisticalsignficance_mmlr"><i class="fa fa-check"></i><b>39.1.5</b> Statistical Signficance</a></li>
<li class="chapter" data-level="39.1.6" data-path="differentialprediction.html"><a href="differentialprediction.html#practicalsignficance_mmlr"><i class="fa fa-check"></i><b>39.1.6</b> Practical Significance</a></li>
</ul></li>
<li class="chapter" data-level="39.2" data-path="differentialprediction.html"><a href="differentialprediction.html#review_differentialprediction"><i class="fa fa-check"></i><b>39.2</b> Review of Differential Prediction</a>
<ul>
<li class="chapter" data-level="39.2.1" data-path="differentialprediction.html"><a href="differentialprediction.html#samplewriteup_mmlr"><i class="fa fa-check"></i><b>39.2.1</b> Sample Write-Up</a></li>
<li class="chapter" data-level="39.2.2" data-path="differentialprediction.html"><a href="differentialprediction.html#video-tutorial-26"><i class="fa fa-check"></i><b>39.2.2</b> Video Tutorial</a></li>
</ul></li>
<li class="chapter" data-level="39.3" data-path="differentialprediction.html"><a href="differentialprediction.html#center_mmlr"><i class="fa fa-check"></i><b>39.3</b> Grand-Mean Center Continuous Predictor Variables</a></li>
<li class="chapter" data-level="39.4" data-path="differentialprediction.html"><a href="differentialprediction.html#estimate_mmlr"><i class="fa fa-check"></i><b>39.4</b> Estimate Moderated Multiple Linear Regression Model</a>
<ul>
<li class="chapter" data-level="39.4.1" data-path="differentialprediction.html"><a href="differentialprediction.html#gender_differentialprediction"><i class="fa fa-check"></i><b>39.4.1</b> Test Differential Prediction Based on <code>gender</code></a></li>
<li class="chapter" data-level="39.4.2" data-path="differentialprediction.html"><a href="differentialprediction.html#age_differentialprediction"><i class="fa fa-check"></i><b>39.4.2</b> Test Differential Prediction Based on <code>c_age</code></a></li>
<li class="chapter" data-level="39.4.3" data-path="differentialprediction.html"><a href="differentialprediction.html#race_differentialprediction"><i class="fa fa-check"></i><b>39.4.3</b> Test Differential Prediction Based on <code>race</code></a></li>
</ul></li>
<li class="chapter" data-level="39.5" data-path="differentialprediction.html"><a href="differentialprediction.html#summary_differentialprediction"><i class="fa fa-check"></i><b>39.5</b> Summary</a></li>
<li class="chapter" data-level="39.6" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_supplement"><i class="fa fa-check"></i><b>39.6</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="39.6.1" data-path="differentialprediction.html"><a href="differentialprediction.html#lm_function_mmlr"><i class="fa fa-check"></i><b>39.6.1</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="39.6.2" data-path="differentialprediction.html"><a href="differentialprediction.html#apatable_mmlr"><i class="fa fa-check"></i><b>39.6.2</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VIII Odds &amp; Ends</b></span></li>
<li class="chapter" data-level="40" data-path="create-portfolio.html"><a href="create-portfolio.html"><i class="fa fa-check"></i><b>40</b> Creating a Data Analytics Portfolio</a></li>
<li class="chapter" data-level="41" data-path="literature-search-review.html"><a href="literature-search-review.html"><i class="fa fa-check"></i><b>41</b> Conducting a Literature Search &amp; Review</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for HR:<br />
<em>An Introduction to Human Resource Analytics Using R</em><br />
BOOK UNDER CONSTRUCTION</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="posttestonly" class="section level1" number="30">
<h1><span class="header-section-number">Chapter 30</span> Evaluating a Post-Test-Only with Control Group Design Using Independent-Samples <em>t</em>-test</h1>
<p>In a <strong>post-test-only with control group</strong> training evaluation design (i.e., research design), employees are assigned (randomly or non-randomly) to either a treatment group (e.g., new training program) or a control group (e.g., comparison group, old training program), and every participating employee is assessed on selected training outcomes (i.e., measures) after the training has concluded. If <em>random assignment</em> to groups is used, then a post-test-only with control group design is considered <em>experimental</em>. Conversely, if <em>non-random assignment</em> to groups is used, then the design is considered <em>quasi-experimental</em>. Regardless of whether random or non-random assignment is used, an independent-samples <em>t</em>-test can be used to analyze the data from a post-test-only with control group design, provided key statistical assumptions are satisfied.</p>
<p>Like any evaluation design, there are limitations to the inferences and conclusions we can draw from a post-test-only with control group design. As a major strength, this design includes a control group, and if coupled with random assignment to groups, then the design qualifies as a true experimental design. With that being said, if we use <em>non</em>-random assignment to the treatment and control groups, then we are less likely to have equivalent groups of individuals who enter each group, which may bias how they engage in the demands of their respective group and how they complete the outcome measures. Further, because this design lacks a pre-test (i.e., assessment of initial performance on the outcome measures), we cannot be confident that employees in the treatment and control groups “started in the same place” with respect to the outcome(s) we might measure at post-test. Consequently, any differences we observe between the two groups on a post-test outcome measure may reflect pre-existing differences – meaning, the training may not have “caused” the differences that are apparent at post-test.</p>
<div id="review_isttest" class="section level2" number="30.1">
<h2><span class="header-section-number">30.1</span> Review of Independent-Samples <em>t</em>-test</h2>
<p>The <strong>independent-samples <em>t</em>-test</strong> is an inferential statistical analysis that can be used to compare the to compare the means of two independent groups, such as a treatment and control group. That is, this analysis compares differences in means when we have two separate groups of cases drawn from two populations; critically, each case must appear in only one of the two samples, hence the name <em>independent-samples</em> <em>t</em>-test. In the context of a post-test-only training evaluation design, we can conceptualize group membership (e.g., treatment vs. control) as a categorical (nominal, ordinal) predictor variable with just two categories (i.e., levels), and the post-test outcome measure as a continuous (interval, ratio) outcome variable. Importantly, the outcome variable must be continuous for an independent-samples <em>t</em>-test to be an appropriate analysis. The independent-samples <em>t</em>-test is sometimes called a between-subjects <em>t</em>-test or a two-groups <em>t</em>-test.</p>
<p>The formula for an independent-samples <em>t</em>-test can be written as follows:</p>
<p><span class="math inline">\(t = \frac{\overline{X}_1 - \overline{X}_2}{s_{{X}_{1}{X}_2} \sqrt{\frac{2}{n}}}\)</span></p>
<p>where <span class="math inline">\(X_{1}\)</span> is the mean of the first group and <span class="math inline">\(X_{2}\)</span> is the mean of the second group, <span class="math inline">\(s_{{X}_{1}{X}_2}\)</span> is the pooled standard deviation of <span class="math inline">\(X_{1}\)</span> and <span class="math inline">\(X_{2}\)</span>, and <span class="math inline">\(n\)</span> refers to the number of cases (i.e., sample size).</p>
<div id="statisticalassumptions_isttest" class="section level3" number="30.1.1">
<h3><span class="header-section-number">30.1.1</span> Statistical Assumptions</h3>
<p>The statistical assumptions that should be met prior to running and/or interpreting estimates from an independent-samples <em>t</em>-test include:</p>
<ul>
<li>The outcome (dependent, response) variable has a univariate normal distribution in each of the two underlying populations (e.g., samples, groups, conditions), which correspond to the two categories (levels) of the predictor (independent, explanatory) variable;</li>
<li>The variances of the outcome (dependent, response) variable are equal across the two populations (e.g., samples, groups, conditions), which is often called the equality of variances or homogeneity of variances assumption.</li>
</ul>
</div>
<div id="statisticalsignficance_isttest" class="section level3" number="30.1.2">
<h3><span class="header-section-number">30.1.2</span> Statistical Significance</h3>
<p>If we wish to know whether the two means we are comparing differ to a statistically significant extent, we can compare our <em>t</em>-value value to a table of critical values of a <em>t</em>-distribution. If our calculated value is larger than the critical value given the number of degrees of freedom (<em>df</em> = <em>n</em> - 2) and the desired alpha level (i.e., significance level, <em>p</em>-value threshold), we would conclude that there is evidence of a significant <em>difference</em> in means between the two independent samples. Alternatively, we can calculate the exact <em>p</em>-value if we know the <em>t</em>-value and the degrees of freedom. Fortunately, modern statistical software calculates the <em>t</em>-value, degrees of freedom, and <em>p</em>-value for us.</p>
<p>Using null hypothesis significance testing (NHST), we interpret a <em>p</em>-value that is <em>less than .05</em> (or whatever two- or one-tailed alpha level we set) to meet the standard for statistical significance, meaning that we reject the null hypothesis that the difference between the two means is equal to zero. In other words, if the <em>p</em>-value is less than .05, we conclude that the two means differ from each other to a statistically significant extent. In contrast, if the <em>p</em>-value is <em>equal to or greater than .05</em>, then we fail to reject the null hypothesis that the difference between the two means is equal to zero. Put differently, if the <em>p</em>-value is equal to or greater than .05, we conclude that the two means do <em>not</em> differ from zero to a statistically significant extent, leading us to conclude that there is no difference between the two means in the population.</p>
<p>When setting an alpha threshold, such as the conventional two-tailed .05 level, sometimes the question comes up regarding whether borderline <em>p</em>-values signify significance or nonsignificance. For our purposes, let’s be very strict in our application of the chosen alpha level. For example, if we set our alpha level at .05, <em>p</em> = .049 would be considered statistically significant, and <em>p</em> = .050 would be considered statistically nonsignificant.</p>
<p>Because our independent-samples <em>t</em>-test is estimated using data from a sample drawn from an underlying population, sampling error will affect the extent to which our sample is representative of the population from which its drawn. That is, the observed difference between the two means is a <em>point estimate</em> of the population parameter and is subject to sampling error. Fortunately, confidence intervals can give us a better idea of what the true population parameter value might be. If we apply an alpha level of .05 (two-tailed), then the equivalent confidence interval (CI) is a 95% CI. In terms of whether the difference between two means is is statistically significant, if the lower and upper limits of 95% CI do <em>not</em> include zero, then this tells us the same thing as a <em>p</em>-value that is less than .05. Strictly speaking, a 95% CI indicates that if we were to hypothetically draw many more samples from the underlying populations and construct CIs for each of those samples, then the true parameter (i.e., true value of the difference in means in the population) would likely fall within the lower and upper bounds of 95% of the estimated CIs. In other words, the 95% CI gives us an indication of plausible values for the population parameter while taking into consideration sampling error. A wide CI (i.e., large difference between the lower and upper limits) signifies more sampling error, and a narrow CI signifies less sampling error.</p>
</div>
<div id="practicalsignficance_isttest" class="section level3" number="30.1.3">
<h3><span class="header-section-number">30.1.3</span> Practical Significance</h3>
<p>A significant independent-samples <em>t</em>-test and associated <em>p</em>-value only tells us that the two means are statistically different from one another. It does not, however, tell us about the magnitude of the difference between means – or in other words, the practical significance. The standardized mean difference score (Cohen’s <em>d</em>) is an effect size, which means that it is a standardized metric that can be used to compare <em>d</em>-values compare samples. In essence, the Cohen’s <em>d</em> indicates the magnitude of the difference between means in standard deviation units. A <em>d</em>-value of .00 indicates that there is no difference between the two means, while the following are some generally accepted qualitative-magnitude labels we can attach to the absolute value of <em>d</em>.</p>
<table>
<thead>
<tr class="header">
<th>Cohen’s <em>d</em></th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.20</td>
<td>Small</td>
</tr>
<tr class="even">
<td>.50</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td>.80</td>
<td>Large</td>
</tr>
</tbody>
</table>
<p>Here is the formula for computing <em>d</em>:</p>
<p><span class="math inline">\(d = t \sqrt{\frac{n_1 + n_2} {n_1n_2}}\)</span></p>
<p>where <span class="math inline">\(t\)</span> refers to the calculated <span class="math inline">\(t\)</span>-value, <span class="math inline">\(n_1\)</span> refers to the sample size of the first independent sample, and <span class="math inline">\(n_2\)</span> refers to the sample size of the second independent sample.</p>
</div>
<div id="samplewriteup_isttest" class="section level3" number="30.1.4">
<h3><span class="header-section-number">30.1.4</span> Sample Write-Up</h3>
<p>One group of 25 participants completes a new safety training program (treatment group), and a separate group of 25 participants completes the old safety training program (control group). Both groups of participants complete a safety knowledge test one week after completing their respective training programs. In other words, these participants were part of a post-test-only with control group training evaluation design. An independent-samples <em>t</em>-test was used to determine whether the average safety knowledge test score for the group that completed the new training program was significantly different than the average safety knowledge test score for the group that completed the old training program. We found a statistically significant difference between the means on the safety knowledge test for the treatment group that participated in the new training program (<em>M</em> = 72.36, <em>SD</em> = 6.98, <em>n</em> = 25) and the control group that participated in the old training program (<em>M</em> = 61.32, <em>SD</em> = 9.15, <em>n</em> = 25), such that those who participated in the new training program performed better on the safety knowledge test (<em>t</em> = 4.80, <em>p</em> &lt; .01, 95% CI[6.41, 15.67]). Further, because we found a statistically significant difference in means, we then interpreted the practical significance of this effect, which was large (<em>d</em> = 1.36).</p>
</div>
<div id="video-tutorial-19" class="section level3" number="30.1.5">
<h3><span class="header-section-number">30.1.5</span> Video Tutorial</h3>
<p>As usual, you have the choice to follow along with the written tutorial in this chapter or to watch the video tutorial below.</p>
<iframe src="https://youtube.com/embed/oATcHuMZtuo?rel=0" width="672" height="400px">
</iframe>
<p>Link to Video Tutorial: <a href="https://youtu.be/oATcHuMZtuo" class="uri">https://youtu.be/oATcHuMZtuo</a></p>
<div id="functions-packages-introduced-15" class="section level4" number="30.1.5.1">
<h4><span class="header-section-number">30.1.5.1</span> Functions &amp; Packages Introduced</h4>
<table>
<thead>
<tr class="header">
<th>Function</th>
<th>Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>ttest</code></td>
<td><code>lessR</code></td>
</tr>
<tr class="even">
<td><code>BarChart</code></td>
<td><code>lessR</code></td>
</tr>
</tbody>
</table>
</div>
<div id="initsteps_isttest" class="section level4" number="30.1.5.2">
<h4><span class="header-section-number">30.1.5.2</span> Initial Steps</h4>
<p>If you haven’t already, save the file called <strong>“TrainingEvaluation_PostControl.csv”</strong> into a folder that you will subsequently set as your working directory. Your working directory will likely be different than the one shown below (i.e., <code>"H:/RWorkshop"</code>). As a reminder, you can access all of the data files referenced in this book by downloading them as a compressed (zipped) folder from the my GitHub site: <a href="https://github.com/davidcaughlin/R-Tutorial-Data-Files" class="uri">https://github.com/davidcaughlin/R-Tutorial-Data-Files</a>; once you’ve followed the link to GitHub, just click “Code” (or “Download”) followed by “Download ZIP”, which will download all of the data files referenced in this book. For the sake of parsimony, I recommend downloading all of the data files into the same folder on your computer, which will allow you to set that same folder as your working directory for each of the chapters in this book.</p>
<p>Next, using the <code>setwd</code> function, set your working directory to the folder in which you saved the data file for this chapter. Alternatively, you can manually set your working directory folder in your drop-down menus by going to <em>Session &gt; Set Working Directory &gt; Choose Directory…</em>. Be sure to create a new R script file (.R) or update an existing R script file so that you can save your script and annotations. If you need refreshers on how to set your working directory and how to create and save an R script, please refer to <a href="setwd.html#setwd">Setting a Working Directory</a> and <a href="gettingstarted.html#createRscript">Creating &amp; Saving an R Script</a>.</p>
<div class="sourceCode" id="cb875"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb875-1"><a href="posttestonly.html#cb875-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your working directory</span></span>
<span id="cb875-2"><a href="posttestonly.html#cb875-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;H:/RWorkshop&quot;</span>)</span></code></pre></div>
<p>Next, read in the .csv data file called <strong>“TrainingEvaluation_PostControl.csv”</strong> using your choice of read function. In this example, I use the <code>read_csv</code> function from the <code>readr</code> package <span class="citation">(<a href="references.html#ref-R-readr" role="doc-biblioref">Wickham and Hester 2020</a>)</span>. If you choose to use the <code>read_csv</code> function, be sure that you have installed and accessed the <code>readr</code> package using the <code>install.packages</code> and <code>library</code> functions. <em>Note: You don’t need to install a package every time you wish to access it; in general, I would recommend updating a package installation once ever 1-3 months.</em> For refreshers on installing packages and reading data into R, please refer to <a href="gentleintro.html#packages">Packages</a> and <a href="read.html#read">Reading Data into R</a>.</p>
<div class="sourceCode" id="cb876"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb876-1"><a href="posttestonly.html#cb876-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install readr package if you haven&#39;t already</span></span>
<span id="cb876-2"><a href="posttestonly.html#cb876-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Note: You don&#39;t need to install a package every </span></span>
<span id="cb876-3"><a href="posttestonly.html#cb876-3" aria-hidden="true" tabindex="-1"></a><span class="co"># time you wish to access it]</span></span>
<span id="cb876-4"><a href="posttestonly.html#cb876-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;readr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb877"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb877-1"><a href="posttestonly.html#cb877-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access readr package</span></span>
<span id="cb877-2"><a href="posttestonly.html#cb877-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb877-3"><a href="posttestonly.html#cb877-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb877-4"><a href="posttestonly.html#cb877-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data and name data frame (tibble) object</span></span>
<span id="cb877-5"><a href="posttestonly.html#cb877-5" aria-hidden="true" tabindex="-1"></a>td <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;TrainingEvaluation_PostControl.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification --------------------------------------------------------------------------
## cols(
##   EmpID = col_double(),
##   Condition = col_character(),
##   PostTest = col_double()
## )</code></pre>
<div class="sourceCode" id="cb879"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb879-1"><a href="posttestonly.html#cb879-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the names of the variables in the data frame (tibble) objects</span></span>
<span id="cb879-2"><a href="posttestonly.html#cb879-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(td)</span></code></pre></div>
<pre><code>## [1] &quot;EmpID&quot;     &quot;Condition&quot; &quot;PostTest&quot;</code></pre>
<div class="sourceCode" id="cb881"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb881-1"><a href="posttestonly.html#cb881-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View variable type for each variable in data frame</span></span>
<span id="cb881-2"><a href="posttestonly.html#cb881-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(td)</span></code></pre></div>
<pre><code>## spec_tbl_df[,3] [50 x 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ EmpID    : num [1:50] 26 27 28 29 30 31 32 33 34 35 ...
##  $ Condition: chr [1:50] &quot;New&quot; &quot;New&quot; &quot;New&quot; &quot;New&quot; ...
##  $ PostTest : num [1:50] 66 74 62 84 78 73 60 61 71 83 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   EmpID = col_double(),
##   ..   Condition = col_character(),
##   ..   PostTest = col_double()
##   .. )</code></pre>
<div class="sourceCode" id="cb883"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb883-1"><a href="posttestonly.html#cb883-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View first 6 rows of data frame</span></span>
<span id="cb883-2"><a href="posttestonly.html#cb883-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(td)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   EmpID Condition PostTest
##   &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;
## 1    26 New             66
## 2    27 New             74
## 3    28 New             62
## 4    29 New             84
## 5    30 New             78
## 6    31 New             73</code></pre>
<p>There are 50 cases (i.e., employees) and 3 variables in the <code>td</code> data frame: <code>EmpID</code> (unique identifier for employees), <code>Condition</code> (training condition: <em>New</em> = new training program, <em>Old</em> = old training program), and <code>PostTest</code> (post-training scores on training assessment, ranging from 1-100, where 100 indicates better performance). Regarding participation in the training conditions, 25 employees participated in the old training program, and 25 employees participated in the new training program.</p>
</div>
</div>
</div>
<div id="estimate_isttest" class="section level2" number="30.2">
<h2><span class="header-section-number">30.2</span> Estimate Independent-Samples <em>t</em>-test</h2>
<p>Different functions are available that will allow us to estimate an independent-samples <em>t</em>-test in <code>R</code>. In this chapter, we will review how to run an independent-samples <em>t</em>-test using the <code>ttest</code> function from the <code>lessR</code> package, as it produces a generous amount of output automatically. Using this function, we will evaluate whether the means on the post-test variable (<code>PostTest</code>) differ based on the two levels of the training <code>Condition</code> variable (<em>New</em>, <em>Old</em>) differ from one another to a statistically significant extent; in other words, let’s find out if we should treat the means as being different from one another.</p>
<p>To access and use the <code>ttest</code> function, we need to install and/or access the <code>lessR</code> package. If you haven’t already, be sure to install the <code>lessR</code> package; if you’ve recently installed the package, then you likely don’t need to install it in this session, and you can skip that step to save time. You <em>will</em> need to run the <code>library</code> function to access the package (assuming it’s been installed), so don’t forget that important step.</p>
<div class="sourceCode" id="cb885"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb885-1"><a href="posttestonly.html#cb885-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install lessR package</span></span>
<span id="cb885-2"><a href="posttestonly.html#cb885-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;lessR&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb886"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb886-1"><a href="posttestonly.html#cb886-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access lessR package and its functions</span></span>
<span id="cb886-2"><a href="posttestonly.html#cb886-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lessR)</span></code></pre></div>
<p>Please note that when you use the <code>library</code> function to access the <code>lessR</code> package in a new <code>R</code> or <code>RStudio</code> session, you will likely receive a message in red font in your Console. Typically, red font in your Console is not a good sign; however, accessing the <code>lessR</code> package is one of the unique situations in which a red-font message is not a warning or error message. You may also receive a warning message that indicates that certain “objects are masked.” For our purposes, we can ignore that message.</p>
<p>Now we’re ready to run an independent-samples <em>t</em>-test. To begin, type the name of the <code>ttest</code> function. As the first argument in the parentheses, specify the statistical model that we wish to estimate. To do so, type the name of the continuous outcome (dependent) variable (<code>PostTest</code>) to the left of the <code>~</code> operator and the name of the categorical predictor (independent) variable (<code>Condition</code>) to the right of the <code>~</code> operator. For the second argument, use <code>data=</code> to specify the name of the data frame where the outcome and predictor variables are located (<code>td</code>). For the third argument, enter <code>paired=FALSE</code> to inform <code>R</code> that the data are <em>not</em> paired (i.e., you are <em>not</em> requesting a paired-samples <em>t</em>-test).</p>
<div class="sourceCode" id="cb887"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb887-1"><a href="posttestonly.html#cb887-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate independent-samples t-test</span></span>
<span id="cb887-2"><a href="posttestonly.html#cb887-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ttest</span>(PostTest <span class="sc">~</span> Condition, <span class="at">data=</span>td, <span class="at">paired=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
## Compare PostTest across Condition levels New and Old 
## 
## ------ Describe ------
## 
## PostTest for Condition New:  n.miss = 0,  n = 25,  mean = 72.360,  sd = 6.975
## PostTest for Condition Old:  n.miss = 0,  n = 25,  mean = 61.320,  sd = 9.150
## 
## Mean Difference of PostTest:  11.040
## 
## Weighted Average Standard Deviation:   8.136 
## 
## 
## ------ Assumptions ------
## 
## Note: These hypothesis tests can perform poorly, and the 
##       t-test is typically robust to violations of assumptions. 
##       Use as heuristic guides instead of interpreting literally. 
## 
## Null hypothesis, for each group, is a normal distribution of PostTest.
## Group New  Shapiro-Wilk normality test:  W = 0.950,  p-value = 0.253
## Group Old  Shapiro-Wilk normality test:  W = 0.969,  p-value = 0.621
## 
## Null hypothesis is equal variances of PostTest, i.e., homogeneous.
## Variance Ratio test:  F = 83.727/48.657 = 1.721,  df = 24;24,  p-value = 0.191
## Levene&#39;s test, Brown-Forsythe:  t = -0.955,  df = 48,  p-value = 0.344
## 
## 
## ------ Infer ------
## 
## --- Assume equal population variances of PostTest for each Condition 
## 
## t-cutoff for 95% range of variation: tcut =  2.011 
## Standard Error of Mean Difference: SE =  2.301 
## 
## Hypothesis Test of 0 Mean Diff:  t = 4.798,  df = 48,  p-value = 0.000
## 
## Margin of Error for 95% Confidence Level:  4.627
## 95% Confidence Interval for Mean Difference:  6.413 to 15.667
## 
## 
## --- Do not assume equal population variances of PostTest for each Condition 
## 
## t-cutoff: tcut =  2.014 
## Standard Error of Mean Difference: SE =  2.301 
## 
## Hypothesis Test of 0 Mean Diff:  t = 4.798,  df = 44.852, p-value = 0.000
## 
## Margin of Error for 95% Confidence Level:  4.635
## 95% Confidence Interval for Mean Difference:  6.405 to 15.675
## 
## 
## ------ Effect Size ------
## 
## --- Assume equal population variances of PostTest for each Condition 
## 
## Standardized Mean Difference of PostTest, Cohen&#39;s d:  1.357
## 
## 
## ------ Practical Importance ------
## 
## Minimum Mean Difference of practical importance: mmd
## Minimum Standardized Mean Difference of practical importance: msmd
## Neither value specified, so no analysis
## 
## 
## ------ Graphics Smoothing Parameter ------
## 
## Density bandwidth for Condition New: 4.175
## Density bandwidth for Condition Old: 5.464</code></pre>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-519-1.png" width="672" /></p>
<p>As you can see in the output, the <code>ttest</code> function provides descriptive statistics, assumption tests regarding the distributions and the variances, a statistical significance test of the mean comparison, and an indicator of practical significance in the form of the standardized mean difference (Cohen’s <em>d</em>). In addition, the default data visualization depicting the two density distributions is helpful for understanding the difference between the two means. Let’s now review each section of the output.</p>
<p><strong>Description</strong>: The <em>Description</em> section includes basic descriptive statistics about the sample. In the output, we can see that that there are 25 employees in each condition (<em>n</em> = 25), and descriptively, the mean <code>PostTest</code> score for the <em>New</em> condition is 72.36 (<em>SD</em> = 6.98), and the mean <code>PostTest</code> score for the <em>Old</em> condition is 61.32 (<em>SD</em> = 9.15). The difference between the two means is 11.04.</p>
<p><strong>Assumptions:</strong> As noted in the output: “These hypothesis tests can perform poorly, and the <em>t</em>-test is typically robust to violations of assumptions. Use as heuristic guides instead of interpreting literally.” Given that, we shouldn’t put too much of an emphasis on these statistical assumption tests, but nevertheless than can provide some guidance when it comes to detecting potential statistical-assumption violations that might preclude us from choosing to interpret the results of the independent-samples <em>t</em>-test itself.</p>
<p>Let’s dive into interpreting these assumption tests. The <strong>Shapiro-Wilk normality test</strong> is used to test the null hypothesis that a distribution is normal; as such, if the <em>p</em>-value associated with the test statistic (<em>W</em>) is <em>less than</em> the conventional alpha level of .05, then we <em>reject</em> the null hypothesis and assume that the distribution is <em>not</em> normal. If, however, <em>p</em>-value associated with the test statistic (<em>W</em>) is <em>greater than</em> .05, then we <em>fail to reject</em> the null hypothesis, which means that we do not have statistical evidence that the distribution is anything other than normal; in other words, if the <em>p</em>-value is equal to or greater than our alpha level (.05), then we can assume the variable is normally distributed, and can feel satisfied that we have met the statistical assumption of normality for that particular distribution. In the output, we can see that the <code>PostTest</code> variable for those in the <em>New</em> training condition is normally distributed (<em>W</em> = .950, <em>p</em> = .253), and for those in the <em>Old</em> training condition, the <code>PostTest</code> variable is also normally distributed (<em>W</em> = .969, <em>p</em> = .621).</p>
<p>As for the equal variances assumption, <strong>Levene’s test</strong> (i.e., homogeneity of variances test) is commonly used. The null hypothesis of this test is that the variances are equal. Thus, if the <em>p</em>-value is <em>less</em> than the conventional alpha level of .05, then we reject the null hypothesis and assume the variances are different. If, however, the <em>p</em>-value is <em>equal to or greater than</em> .05, then we fail to reject the null hypothesis and assume that the variances are equal (i.e., variances are homogeneous). In the output, we see that the test is nonsignificant (<em>t</em> = -.955, <em>p</em> = .344), which suggests that, based on this test, we have no reason to believe that the two variances are anything but equal. All in all, we found evidence to support that we met the two statistical assumptions necessary to proceed forward with making inferences.</p>
<p><strong>Inference:</strong> The <em>Inference</em> section of the output is where you will find the independent-samples <em>t</em>-test itself. This section is called <em>Inference</em> because this is where we’re making statistical inferences about the underlying population of employees. Specifically, the <em>t</em>-test and its associated <em>p</em>-value represent the statistical test of the null hypothesis (i.e., the two means are equal). If we have evidence that the variances are equal (which we do based on Levene’s test), then we should interpret the sub-section titled <em>Assume equal population variances of PostTest for each Condition</em>. If we had instead found evidence that the variances were <em>not</em> equal, then we would want to interpret the sub-section titled <em>Do not assume equal population variances of PostTest for each Condition</em>.</p>
<p>First, take a look at the line prefaced with <em>Hypothesis Test of 0 Mean Diff</em>; this line contains the results of the independent-samples <em>t</em>-test (<em>t</em> = 4.798, <em>p</em> &lt; .001). Because the <em>p</em>-value is less than our conventional two-tailed alpha cutoff of .05, we reject the null hypothesis and conclude that the two means are different from one another. How do we know which mean is greater (or less than) the other? Well, we need to look back to the <em>Description</em> section; in that section, we see that the mean <code>PostTest</code> score for the <em>New</em> training condition is greater than the mean for the <em>Old</em> training condition; as such, we can conclude the following: The average post-training assessment score for employees who participated in the new training program (<em>M</em> = 72.36, <em>SD</em> = 6.98) was significantly higher than the average score for those who participated in the old training program (<em>M</em> = 61.32, <em>SD</em> = 9.15) (<em>t</em> = 4.798, <em>p</em> &lt; .001). Regarding the 95% confidence interval, we can conclude that the true mean difference in the population is likely between 6.41 and 15.67 (on a 1-100 point assessment).</p>
<p><strong>Effect Size:</strong> In the <em>Effect Size</em> section, the standardized mean difference (Cohen’s <em>d</em>) is provided as an indicator of practical significance. In the output, <em>d</em> is equal to 1.36, which is considered to be a (very) large effect, according to conventional rules-of-thumb (see table below). <em>Please note that typically we only interpret practical significance when a difference has been found to be statistically significant (see Inference section).</em></p>
<table>
<thead>
<tr class="header">
<th>Cohen’s <em>d</em></th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.20</td>
<td>Small</td>
</tr>
<tr class="even">
<td>.50</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td>.80</td>
<td>Large</td>
</tr>
</tbody>
</table>
<p><strong>Sample Write-Up:</strong> In total, 25 employees participated in the new training program and 25 employees participated in the old training program. After completely their respective training programs, employees completed an assessment of their knowledge, where scores could range from 1-100. The average post-training assessment score for employees who participated in the new training program (<em>M</em> = 72.36, <em>SD</em> = 6.98) was significantly higher than the average score for those who participated in the old training program (<em>M</em> = 61.32, <em>SD</em> = 9.15) (<em>t</em> = 4.798, <em>p</em> &lt; .001, 95% CI[6.41, 15.67]). This difference can be considered to be very large (<em>d</em> = 1.36).</p>
</div>
<div id="barchart_isttest" class="section level2" number="30.3">
<h2><span class="header-section-number">30.3</span> Visualize Results Using Bar Chart</h2>
<p>When we find a statistically significant difference between two means based on an independent-samples <em>t</em>-test, you may decide to present the two means in a bar chart. We will use the <code>BarChart</code> function from <code>lessR</code> to do so.</p>
<p>Type the name of the <code>BarChart</code> function. As the first argument, type <code>x=</code> followed by the name of the categorical predictor variable (<code>Condition</code>). As the second argument, type <code>y=</code> followed by the name of the continuous outcome variable (<code>PostTest</code>). As the third argument, specify <code>stat="mean"</code> to request the application of the mean function to the <code>PostTest</code> variable based on the levels of the <code>Condition</code> variable. As the fourth argument, type <code>data=</code> followed by the name of the data frame object to which our predictor and outcome variables belong (<code>td</code>). As the fifth argument, use <code>xlab=</code> to provide the x-axis label (<code>"Training Condition"</code>). As the sixth argument, use <code>ylab=</code> to provide the y-axis label (<code>"Post-Test Score"</code>).</p>
<div class="sourceCode" id="cb889"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb889-1"><a href="posttestonly.html#cb889-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create bar chart</span></span>
<span id="cb889-2"><a href="posttestonly.html#cb889-2" aria-hidden="true" tabindex="-1"></a><span class="fu">BarChart</span>(<span class="at">x=</span>Condition, <span class="at">y=</span>PostTest,</span>
<span id="cb889-3"><a href="posttestonly.html#cb889-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">stat=</span><span class="st">&quot;mean&quot;</span>,</span>
<span id="cb889-4"><a href="posttestonly.html#cb889-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">data=</span>td,</span>
<span id="cb889-5"><a href="posttestonly.html#cb889-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab=</span><span class="st">&quot;Training Condition&quot;</span>, </span>
<span id="cb889-6"><a href="posttestonly.html#cb889-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab=</span><span class="st">&quot;Post-Test Score&quot;</span>)</span></code></pre></div>
<pre><code>## PostTest 
##   - by levels of - 
## Condition 
##  
##        n   miss     mean       sd      min      mdn      max 
## New   25      0    72.36     6.98    60.00    73.00    84.00 
## Old   25      0    61.32     9.15    42.00    61.00    79.00</code></pre>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-520-1.png" width="672" /></p>
<pre><code>## &gt;&gt;&gt; Suggestions
## Plot(PostTest, Condition) # lollipop plot 
## 
## 
##  Data for:  PostTest 
##  ------------------- 
##     New    Old 
##   72.36  61.32</code></pre>
</div>
<div id="summary_isttest" class="section level2" number="30.4">
<h2><span class="header-section-number">30.4</span> Summary</h2>
<p>In this chapter, we learned to use the independent-samples <em>t</em>-test to compare two means from independent groups of cases, which is the case when we evaluating a training program using a post-test-only <em>with</em> control group design. The <code>ttest</code> function from <code>lessR</code> can be used to run an independent-samples <em>t</em>-test, and the <code>BarChart</code> function from <code>lessR</code> can be used to present the results of a significant difference visually.</p>
</div>
<div id="isttest_supplement" class="section level2" number="30.5">
<h2><span class="header-section-number">30.5</span> Chapter Supplement</h2>
<p>In addition to the <code>ttest</code> function from the <code>lessR</code> package covered <a href="posttestonly.html#estimate_isttest">above</a>, we can use the <code>t.test</code> function from base R to estimate an independent-samples <em>t</em>-test. Because this function comes from base R, we do not need to install and access an additional package.</p>
<div id="isttest_supplement_functions" class="section level4" number="30.5.0.1">
<h4><span class="header-section-number">30.5.0.1</span> Functions &amp; Packages Introduced</h4>
<table>
<thead>
<tr class="header">
<th>Function</th>
<th>Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>tapply</code></td>
<td>base R</td>
</tr>
<tr class="even">
<td><code>shapiro.test</code></td>
<td>base R</td>
</tr>
<tr class="odd">
<td><code>leveneTest</code></td>
<td><code>car</code></td>
</tr>
<tr class="even">
<td><code>t.test</code></td>
<td>base R</td>
</tr>
<tr class="odd">
<td><code>cohen.d</code></td>
<td><code>effsize</code></td>
</tr>
<tr class="even">
<td><code>mean</code></td>
<td>base R</td>
</tr>
</tbody>
</table>
</div>
<div id="isttest_initsteps_supplement" class="section level4" number="30.5.0.2">
<h4><span class="header-section-number">30.5.0.2</span> Initial Steps</h4>
<p>If required, please refer to the <a href="posttestonly.html#initsteps_isttest">Initial Steps</a> section from this chapter for more information on these initial steps.</p>
<div class="sourceCode" id="cb892"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb892-1"><a href="posttestonly.html#cb892-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your working directory</span></span>
<span id="cb892-2"><a href="posttestonly.html#cb892-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;H:/RWorkshop&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb893"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb893-1"><a href="posttestonly.html#cb893-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install readr package if you haven&#39;t already</span></span>
<span id="cb893-2"><a href="posttestonly.html#cb893-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Note: You don&#39;t need to install a package every </span></span>
<span id="cb893-3"><a href="posttestonly.html#cb893-3" aria-hidden="true" tabindex="-1"></a><span class="co"># time you wish to access it]</span></span>
<span id="cb893-4"><a href="posttestonly.html#cb893-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;readr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb894"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb894-1"><a href="posttestonly.html#cb894-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access readr package</span></span>
<span id="cb894-2"><a href="posttestonly.html#cb894-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb894-3"><a href="posttestonly.html#cb894-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb894-4"><a href="posttestonly.html#cb894-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data and name data frame (tibble) object</span></span>
<span id="cb894-5"><a href="posttestonly.html#cb894-5" aria-hidden="true" tabindex="-1"></a>td <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;TrainingEvaluation_PostControl.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification --------------------------------------------------------------------------
## cols(
##   EmpID = col_double(),
##   Condition = col_character(),
##   PostTest = col_double()
## )</code></pre>
<div class="sourceCode" id="cb896"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb896-1"><a href="posttestonly.html#cb896-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the names of the variables in the data frame (tibble) objects</span></span>
<span id="cb896-2"><a href="posttestonly.html#cb896-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(td)</span></code></pre></div>
<pre><code>## [1] &quot;EmpID&quot;     &quot;Condition&quot; &quot;PostTest&quot;</code></pre>
<div class="sourceCode" id="cb898"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb898-1"><a href="posttestonly.html#cb898-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View variable type for each variable in data frame</span></span>
<span id="cb898-2"><a href="posttestonly.html#cb898-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(td)</span></code></pre></div>
<pre><code>## spec_tbl_df[,3] [50 x 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ EmpID    : num [1:50] 26 27 28 29 30 31 32 33 34 35 ...
##  $ Condition: chr [1:50] &quot;New&quot; &quot;New&quot; &quot;New&quot; &quot;New&quot; ...
##  $ PostTest : num [1:50] 66 74 62 84 78 73 60 61 71 83 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   EmpID = col_double(),
##   ..   Condition = col_character(),
##   ..   PostTest = col_double()
##   .. )</code></pre>
<div class="sourceCode" id="cb900"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb900-1"><a href="posttestonly.html#cb900-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View first 6 rows of data frame</span></span>
<span id="cb900-2"><a href="posttestonly.html#cb900-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(td)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   EmpID Condition PostTest
##   &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;
## 1    26 New             66
## 2    27 New             74
## 3    28 New             62
## 4    29 New             84
## 5    30 New             78
## 6    31 New             73</code></pre>
</div>
<div id="t.test_function_isttest" class="section level3" number="30.5.1">
<h3><span class="header-section-number">30.5.1</span> <code>t.test</code> Function from Base R</h3>
<p>By itself, the <code>t.test</code> function from base R does not generate statistical assumption tests and and estimates of effect size (practical significance) like the <code>ttest</code> function from <code>lessR</code> does. Thus, we will need to apply additional functions to achieve all of the necessary output.</p>
<p>Before running our independent-samples <em>t</em>-test using the <code>t.test</code> function from base R, we should test two assumptions (see <a href="posttestonly.html#statisticalassumptions_isttest">Statistical Assumptions</a> section). We will begin by estimating the <em>Shapiro-Wilk normality test</em> and <em>Levene’s test</em> of equal variances (i.e., homogeneity of variances), which are two statistical tests of the two statistical assumptions. Both of these tests were covered in detail above when we applied the <code>ttest</code> function from <code>lessR</code>, so we will breeze through the interpretation in this section.</p>
<p>To compute the Shapiro-Wilk normality test to test the assumption of normal distributions, we will use the <code>shapiro.test</code> function from base <code>R</code>. Because we need to test the assumption of normality of the outcome variable (<code>PostTest</code>) for both levels of the predictor variable (<code>Condition</code>), we also need to use the <code>tapply</code> function from base <code>R</code>. The <code>tapply</code> function can be quite useful, as it allows us to apply a function to a variable for each level of another categorical (nominal, ordinal) variable. To begin, type the name of the <code>tapply</code> function. As the first argument, type the name of the data frame (<code>td</code>), followed by the <code>$</code> symbol and the name of the outcome variable (<code>PostTest</code>). As the second argument, type the name of the data frame (<code>td</code>), followed by the <code>$</code> symbol and the name of the categorical predictor variable (<code>Condition</code>). Finally, as the third argument, type the name of the <code>shapiro.test</code> function.</p>
<div class="sourceCode" id="cb902"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb902-1"><a href="posttestonly.html#cb902-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Shapiro-Wilk normality test for normal distributions</span></span>
<span id="cb902-2"><a href="posttestonly.html#cb902-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(td<span class="sc">$</span>PostTest, td<span class="sc">$</span>Condition, shapiro.test)</span></code></pre></div>
<pre><code>## $New
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.95019, p-value = 0.2533
## 
## 
## $Old
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.96904, p-value = 0.6208</code></pre>
<p>The output indicates that the <em>p</em>-values associated with both tests are equal to or greater than the conventional alpha of .05; therefore, we <em>fail to reject</em> the null hypothesis that the values are normally distributed. In other words, we have evidence that the outcome variable is normally distributed for both conditions, which suggests that we have met the first statistical assumption.</p>
<p>To test the equality (homogeneity) of variances assumption, we will use the <code>leveneTest</code> function from the <code>car</code> package. More than likely the <code>car</code> package is already installed, as many other packages are dependent on it. That being said, you may still need to install the package prior to accessing it using the <code>library</code> function.</p>
<div class="sourceCode" id="cb904"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb904-1"><a href="posttestonly.html#cb904-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install package</span></span>
<span id="cb904-2"><a href="posttestonly.html#cb904-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;car&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb905"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb905-1"><a href="posttestonly.html#cb905-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access package</span></span>
<span id="cb905-2"><a href="posttestonly.html#cb905-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<p>Type the name of the <code>leveneTest</code> function. As the first argument, specify the statistical model. To do so, type the name of the outcome variable (<code>PostTest</code>) to the left of the <code>~</code> symbol and the name of the predictor variable (<code>Condition</code>) to the right of the <code>~</code> symbol. For the second argument, use <code>data=</code> to specify the name of the data frame (<code>td</code>).</p>
<div class="sourceCode" id="cb906"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb906-1"><a href="posttestonly.html#cb906-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Levene&#39;s test for equal variances</span></span>
<span id="cb906-2"><a href="posttestonly.html#cb906-2" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(PostTest <span class="sc">~</span> Condition, <span class="at">data=</span>td)</span></code></pre></div>
<pre><code>## Warning in leveneTest.default(y = y, group = group, ...): group coerced to factor.</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  0.9121 0.3443
##       48</code></pre>
<p>The output indicates that the <em>p</em>-value (i.e., <code>Pr(&gt;F)</code> = .3443) associated with Levene’s test is equal to or greater than an alpha of .05; thus, we <em>fail to reject</em> the null hypothesis that the variances are equal and thus conclude that the variances are equal. We have satisfied the second statistical assumption.</p>
<p>Now that we seem to have satisfied the two statistical assumptions, we are ready to apply the <code>t.test</code> function from base R. To begin, type the name of the <code>t.test</code> function. As the first argument, type the name of the outcome (dependent) variable (<code>PostTest</code>) to the left of the <code>~</code> symbol and the name of the predictor (independent) variable (<code>Condition</code>) to the right of the <code>~</code> symbol. For the second argument, use <code>data=</code> to specify the name of the data frame (<code>td</code>). As the third argument, type <code>paired=FALSE</code> to indicate that the data are <em>not</em> paired, which means to that are <em>not</em> requesting a paired-samples <em>t</em>-test. As the final argument, type <code>var.equal=TRUE</code> to indicate that we found evidence that the variances were equal; if you had found evidence that the variances were <em>not</em> equal, then you would use the argument <code>var.equal=FALSE</code>.</p>
<div class="sourceCode" id="cb909"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb909-1"><a href="posttestonly.html#cb909-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Independent-samples t-test using t.test function from base R</span></span>
<span id="cb909-2"><a href="posttestonly.html#cb909-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(PostTest <span class="sc">~</span> Condition, <span class="at">data=</span>td, <span class="at">paired=</span><span class="cn">FALSE</span>, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  PostTest by Condition
## t = 4.7976, df = 48, p-value = 0.000016
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   6.413209 15.666791
## sample estimates:
## mean in group New mean in group Old 
##             72.36             61.32</code></pre>
<p>Note that the output provides you with the results of the independent-samples <em>t</em>-test in terms of a formal statistical test (<em>t</em> = 4.798, <em>p</em> &lt; .001), the 95% confidence interval (95% CI[6.413, 15.667]), and the mean of the outcome variable for each level of the categorical predictor variable (<em>New</em> condition: <em>M</em> = 72.36; <em>Old</em> condition: <em>M</em> = 61.32). Thus, we found evidence that the mean <code>PostTest</code> score for the <em>New</em> training condition was statistically significantly higher than the mean of the <em>Old</em> training condition. The output, however, does <em>not</em> include an estimate of practical significance (i.e., effect size).</p>
<p>To compute Cohen’s <em>d</em> as an indicator of practical significance, we will use the <code>cohen.d</code> function from the <code>effsize</code> package. If you haven’t already, install the <code>effsize</code> package. Make sure to access the package using the <code>library</code> function.</p>
<div class="sourceCode" id="cb911"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb911-1"><a href="posttestonly.html#cb911-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install package</span></span>
<span id="cb911-2"><a href="posttestonly.html#cb911-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;effsize&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb912"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb912-1"><a href="posttestonly.html#cb912-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access package</span></span>
<span id="cb912-2"><a href="posttestonly.html#cb912-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effsize)</span></code></pre></div>
<p>As the first argument in the <code>cohen.d</code> function parentheses, type the name of the outcome variable (<code>PostTest</code>) to the left of the <code>~</code> symbol and the name of the predictor variable (<code>Condition</code>) to the right of the <code>~</code> symbol. For the second argument, use <code>data=</code> to specify the name of the data frame (<code>td</code>). As the third argument, type <code>paired=FALSE</code> to indicate that the data are <em>not</em> paired (i.e., dependent).</p>
<div class="sourceCode" id="cb913"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb913-1"><a href="posttestonly.html#cb913-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Cohen&#39;s d</span></span>
<span id="cb913-2"><a href="posttestonly.html#cb913-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohen.d</span>(PostTest <span class="sc">~</span> Condition, <span class="at">data=</span>td, <span class="at">paired=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: 1.356961 (large)
## 95 percent confidence interval:
##     lower     upper 
## 0.7262066 1.9877157</code></pre>
<p>The output indicates that Cohen’s <em>d</em> is 1.357, which would be considered large by conventional cutoff standards.</p>
<table>
<thead>
<tr class="header">
<th>Cohen’s <em>d</em></th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.20</td>
<td>Small</td>
</tr>
<tr class="even">
<td>.50</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td>.80</td>
<td>Large</td>
</tr>
</tbody>
</table>
<p><strong>Sample Write-Up:</strong> In total, 25 employees participated in the new training program and 25 employees participated in the old training program. After completely their respective training programs, employees completed an assessment of their knowledge, where scores could range from 1-100. The average post-training assessment score for employees who participated in the new training program (<em>M</em> = 72.36, <em>SD</em> = 6.98) was significantly higher than the average score for those who participated in the old training program (<em>M</em> = 61.32, <em>SD</em> = 9.15) (<em>t</em> = 4.798, <em>p</em> &lt; .001, 95% CI[6.41, 15.67]). This difference can be considered to be very large (<em>d</em> = 1.36).</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="pretestposttest.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="posttestonly-threegroups.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
