<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 29 Evaluating a Pre-Test/Post-Test without Control Group Design Using Paired-Samples t-test | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION</title>
  <meta name="description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 29 Evaluating a Pre-Test/Post-Test without Control Group Design Using Paired-Samples t-test | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://rforhr.com" />
  <meta property="og:image" content="https://rforhr.comcover.png" />
  <meta property="og:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="github-repo" content="davidcaughlin/R-for-HR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 29 Evaluating a Pre-Test/Post-Test without Control Group Design Using Paired-Samples t-test | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  
  <meta name="twitter:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="twitter:image" content="https://rforhr.comcover.png" />

<meta name="author" content="David E. Caughlin" />


<meta name="date" content="2021-12-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="employeetraining.html"/>
<link rel="next" href="posttestonly.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for HR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#hragrowth"><i class="fa fa-check"></i><b>0.1</b> Growth of HR Analytics</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#skills-gap"><i class="fa fa-check"></i><b>0.2</b> Skills Gap</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#hraplc"><i class="fa fa-check"></i><b>0.3</b> Project Life Cycle Perspective</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#overview-of-hris-hr-analytics"><i class="fa fa-check"></i><b>0.4</b> Overview of HRIS &amp; HR Analytics</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#philosophy"><i class="fa fa-check"></i><b>0.5</b> My Philosophy for This Book</a>
<ul>
<li class="chapter" data-level="0.5.1" data-path="index.html"><a href="index.html#rationalerpref"><i class="fa fa-check"></i><b>0.5.1</b> Rationale for Using R</a></li>
<li class="chapter" data-level="0.5.2" data-path="index.html"><a href="index.html#audiencepref"><i class="fa fa-check"></i><b>0.5.2</b> Audience</a></li>
<li class="chapter" data-level="0.5.3" data-path="index.html"><a href="index.html#structurepref"><i class="fa fa-check"></i><b>0.5.3</b> Structure</a></li>
</ul></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#aboutauthor"><i class="fa fa-check"></i><b>0.6</b> About the Author</a></li>
<li class="chapter" data-level="0.7" data-path="index.html"><a href="index.html#acknowpref"><i class="fa fa-check"></i><b>0.7</b> Acknowledgements</a></li>
</ul></li>
<li class="part"><span><b>I HR Analytics Project Life Cycle</b></span></li>
<li class="chapter" data-level="1" data-path="overviewhraplc.html"><a href="overviewhraplc.html"><i class="fa fa-check"></i><b>1</b> Overview of HR Analytics Project Life Cycle</a></li>
<li class="chapter" data-level="2" data-path="questionformulation.html"><a href="questionformulation.html"><i class="fa fa-check"></i><b>2</b> Question Formulation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="questionformulation.html"><a href="questionformulation.html#adoptstrategicmindset"><i class="fa fa-check"></i><b>2.1</b> Adopting a Strategic Mindset</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="questionformulation.html"><a href="questionformulation.html#strategy"><i class="fa fa-check"></i><b>2.1.1</b> Strategy</a></li>
<li class="chapter" data-level="2.1.2" data-path="questionformulation.html"><a href="questionformulation.html#strategyformulation"><i class="fa fa-check"></i><b>2.1.2</b> Strategy Formulation</a></li>
<li class="chapter" data-level="2.1.3" data-path="questionformulation.html"><a href="questionformulation.html#strategyimplementation"><i class="fa fa-check"></i><b>2.1.3</b> Strategy Implementation</a></li>
<li class="chapter" data-level="2.1.4" data-path="questionformulation.html"><a href="questionformulation.html#strategichrm"><i class="fa fa-check"></i><b>2.1.4</b> Strategic Human Resource Management</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="questionformulation.html"><a href="questionformulation.html#defining-problems-formulating-questions"><i class="fa fa-check"></i><b>2.2</b> Defining Problems &amp; Formulating Questions</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="questionformulation.html"><a href="questionformulation.html#definingaproblem"><i class="fa fa-check"></i><b>2.2.1</b> Defining a Problem</a></li>
<li class="chapter" data-level="2.2.2" data-path="questionformulation.html"><a href="questionformulation.html#formulatingaquestion"><i class="fa fa-check"></i><b>2.2.2</b> Formulating a Question</a></li>
<li class="chapter" data-level="2.2.3" data-path="questionformulation.html"><a href="questionformulation.html#divergentconvergentthinking"><i class="fa fa-check"></i><b>2.2.3</b> Thinking Divergently &amp; Convergently</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="questionformulation.html"><a href="questionformulation.html#summary"><i class="fa fa-check"></i><b>2.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dataacquisition.html"><a href="dataacquisition.html"><i class="fa fa-check"></i><b>3</b> Data Acquisition</a>
<ul>
<li class="chapter" data-level="3.1" data-path="dataacquisition.html"><a href="dataacquisition.html#employee-surveys"><i class="fa fa-check"></i><b>3.1</b> Employee Surveys</a></li>
<li class="chapter" data-level="3.2" data-path="dataacquisition.html"><a href="dataacquisition.html#rating-forms"><i class="fa fa-check"></i><b>3.2</b> Rating Forms</a></li>
<li class="chapter" data-level="3.3" data-path="dataacquisition.html"><a href="dataacquisition.html#surveillance-monitoring"><i class="fa fa-check"></i><b>3.3</b> Surveillance &amp; Monitoring</a></li>
<li class="chapter" data-level="3.4" data-path="dataacquisition.html"><a href="dataacquisition.html#database-queries"><i class="fa fa-check"></i><b>3.4</b> Database Queries</a></li>
<li class="chapter" data-level="3.5" data-path="dataacquisition.html"><a href="dataacquisition.html#scraping"><i class="fa fa-check"></i><b>3.5</b> Scraping</a></li>
<li class="chapter" data-level="3.6" data-path="dataacquisition.html"><a href="dataacquisition.html#summary-1"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="datamanagement.html"><a href="datamanagement.html"><i class="fa fa-check"></i><b>4</b> Data Management</a>
<ul>
<li class="chapter" data-level="4.1" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_clean"><i class="fa fa-check"></i><b>4.1</b> Data Cleaning</a></li>
<li class="chapter" data-level="4.2" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_manipulate"><i class="fa fa-check"></i><b>4.2</b> Data Manipulation &amp; Structuring</a></li>
<li class="chapter" data-level="4.3" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_tools"><i class="fa fa-check"></i><b>4.3</b> Common Data-Management Tools</a></li>
<li class="chapter" data-level="4.4" data-path="datamanagement.html"><a href="datamanagement.html#summary-2"><i class="fa fa-check"></i><b>4.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dataanalysis.html"><a href="dataanalysis.html"><i class="fa fa-check"></i><b>5</b> Data Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="dataanalysis.html"><a href="dataanalysis.html#dataanalysis_toolstechniques"><i class="fa fa-check"></i><b>5.1</b> Tools &amp; Techniques</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="dataanalysis.html"><a href="dataanalysis.html#mathematics"><i class="fa fa-check"></i><b>5.1.1</b> Mathematics</a></li>
<li class="chapter" data-level="5.1.2" data-path="dataanalysis.html"><a href="dataanalysis.html#statistics"><i class="fa fa-check"></i><b>5.1.2</b> Statistics</a></li>
<li class="chapter" data-level="5.1.3" data-path="dataanalysis.html"><a href="dataanalysis.html#machinelearning"><i class="fa fa-check"></i><b>5.1.3</b> Machine Learning</a></li>
<li class="chapter" data-level="5.1.4" data-path="dataanalysis.html"><a href="dataanalysis.html#computationalmodelsimulation"><i class="fa fa-check"></i><b>5.1.4</b> Computational Modeling &amp; Simulations</a></li>
<li class="chapter" data-level="5.1.5" data-path="dataanalysis.html"><a href="dataanalysis.html#textqualitativeanalyses"><i class="fa fa-check"></i><b>5.1.5</b> Text Analyses &amp; Qualitative Analyses</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="dataanalysis.html"><a href="dataanalysis.html#continuum_dataanalytics"><i class="fa fa-check"></i><b>5.2</b> Continuum of Data Analytics</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="dataanalysis.html"><a href="dataanalysis.html#descriptive_analytics"><i class="fa fa-check"></i><b>5.2.1</b> Descriptive Analytics</a></li>
<li class="chapter" data-level="5.2.2" data-path="dataanalysis.html"><a href="dataanalysis.html#predictish_analytics"><i class="fa fa-check"></i><b>5.2.2</b> Predict-ish Analytics</a></li>
<li class="chapter" data-level="5.2.3" data-path="dataanalysis.html"><a href="dataanalysis.html#predictive_analytics"><i class="fa fa-check"></i><b>5.2.3</b> Predictive Analytics</a></li>
<li class="chapter" data-level="5.2.4" data-path="dataanalysis.html"><a href="dataanalysis.html#prescriptive_analytics"><i class="fa fa-check"></i><b>5.2.4</b> Prescriptive Analytics</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="dataanalysis.html"><a href="dataanalysis.html#summary-3"><i class="fa fa-check"></i><b>5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html"><i class="fa fa-check"></i><b>6</b> Data Interpretation &amp; Storytelling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#datainterpretation"><i class="fa fa-check"></i><b>6.1</b> Data Interpretation</a></li>
<li class="chapter" data-level="6.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling"><i class="fa fa-check"></i><b>6.2</b> Storytelling</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#structure"><i class="fa fa-check"></i><b>6.2.1</b> Structure</a></li>
<li class="chapter" data-level="6.2.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#clarity-parsimony"><i class="fa fa-check"></i><b>6.2.2</b> Clarity &amp; Parsimony</a></li>
<li class="chapter" data-level="6.2.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#influence-persuasion"><i class="fa fa-check"></i><b>6.2.3</b> Influence &amp; Persuasion</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling_withdata"><i class="fa fa-check"></i><b>6.3</b> Storytelling with Data</a></li>
<li class="chapter" data-level="6.4" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#summary-4"><i class="fa fa-check"></i><b>6.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html"><i class="fa fa-check"></i><b>7</b> Deployment &amp; Implementation</a></li>
<li class="part"><span><b>II Introduction to R</b></span></li>
<li class="chapter" data-level="8" data-path="overviewR.html"><a href="overviewR.html"><i class="fa fa-check"></i><b>8</b> Overview of R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="8.1" data-path="overviewR.html"><a href="overviewR.html#R_overview"><i class="fa fa-check"></i><b>8.1</b> R Programming Language</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="overviewR.html"><a href="overviewR.html#R_what"><i class="fa fa-check"></i><b>8.1.1</b> What Is R?</a></li>
<li class="chapter" data-level="8.1.2" data-path="overviewR.html"><a href="overviewR.html#R_why"><i class="fa fa-check"></i><b>8.1.2</b> Why Use R?</a></li>
<li class="chapter" data-level="8.1.3" data-path="overviewR.html"><a href="overviewR.html#R_who"><i class="fa fa-check"></i><b>8.1.3</b> Who Uses R?</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="overviewR.html"><a href="overviewR.html#RStudio_overview"><i class="fa fa-check"></i><b>8.2</b> RStudio</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="overviewR.html"><a href="overviewR.html#RStudio_what"><i class="fa fa-check"></i><b>8.2.1</b> What is RStudio?</a></li>
<li class="chapter" data-level="8.2.2" data-path="overviewR.html"><a href="overviewR.html#RStudio_why"><i class="fa fa-check"></i><b>8.2.2</b> Why RStudio?</a></li>
<li class="chapter" data-level="8.2.3" data-path="overviewR.html"><a href="overviewR.html#RStudio_who"><i class="fa fa-check"></i><b>8.2.3</b> Who Uses RStudio?</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="overviewR.html"><a href="overviewR.html#packages_overview"><i class="fa fa-check"></i><b>8.3</b> Packages</a></li>
<li class="chapter" data-level="8.4" data-path="overviewR.html"><a href="overviewR.html#summary-5"><i class="fa fa-check"></i><b>8.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>9</b> Installing R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="9.1" data-path="install.html"><a href="install.html#installR"><i class="fa fa-check"></i><b>9.1</b> Downloading &amp; Installing R</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="install.html"><a href="install.html#for-windows-operation-systems"><i class="fa fa-check"></i><b>9.1.1</b> For Windows Operation Systems</a></li>
<li class="chapter" data-level="9.1.2" data-path="install.html"><a href="install.html#for-mac-operating-systems"><i class="fa fa-check"></i><b>9.1.2</b> For Mac Operating Systems</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="install.html"><a href="install.html#installRStudio"><i class="fa fa-check"></i><b>9.2</b> Downloading &amp; Installing RStudio</a></li>
<li class="chapter" data-level="9.3" data-path="install.html"><a href="install.html#summary-6"><i class="fa fa-check"></i><b>9.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="gettingstarted.html"><a href="gettingstarted.html"><i class="fa fa-check"></i><b>10</b> Getting Started with R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="10.1" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation-to-rstudio"><i class="fa fa-check"></i><b>10.1</b> Orientation to RStudio</a></li>
<li class="chapter" data-level="10.2" data-path="gettingstarted.html"><a href="gettingstarted.html#createRscript"><i class="fa fa-check"></i><b>10.2</b> Creating &amp; Saving an R Script</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-a-new-r-script"><i class="fa fa-check"></i><b>10.2.1</b> Creating a New R Script</a></li>
<li class="chapter" data-level="10.2.2" data-path="gettingstarted.html"><a href="gettingstarted.html#using-an-r-script"><i class="fa fa-check"></i><b>10.2.2</b> Using an R Script</a></li>
<li class="chapter" data-level="10.2.3" data-path="gettingstarted.html"><a href="gettingstarted.html#saving-an-r-script"><i class="fa fa-check"></i><b>10.2.3</b> Saving an R Script</a></li>
<li class="chapter" data-level="10.2.4" data-path="gettingstarted.html"><a href="gettingstarted.html#opening-a-saved-r-script"><i class="fa fa-check"></i><b>10.2.4</b> Opening a Saved R Script</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-an-rstudio-project"><i class="fa fa-check"></i><b>10.3</b> Creating an RStudio Project</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="gettingstarted.html"><a href="gettingstarted.html#creating-a-new-rstudio-project"><i class="fa fa-check"></i><b>10.3.1</b> Creating a New RStudio Project</a></li>
<li class="chapter" data-level="10.3.2" data-path="gettingstarted.html"><a href="gettingstarted.html#opening-an-existing-rstudio-project"><i class="fa fa-check"></i><b>10.3.2</b> Opening an Existing RStudio Project</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation-to-written-tutorials"><i class="fa fa-check"></i><b>10.4</b> Orientation to Written Tutorials</a></li>
<li class="chapter" data-level="10.5" data-path="gettingstarted.html"><a href="gettingstarted.html#summary-7"><i class="fa fa-check"></i><b>10.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="gentleintro.html"><a href="gentleintro.html"><i class="fa fa-check"></i><b>11</b> Basic Features and Operations of the R Language</a>
<ul>
<li class="chapter" data-level="11.1" data-path="gentleintro.html"><a href="gentleintro.html#r_as_calculator"><i class="fa fa-check"></i><b>11.1</b> R as a Calculator</a></li>
<li class="chapter" data-level="11.2" data-path="gentleintro.html"><a href="gentleintro.html#functions"><i class="fa fa-check"></i><b>11.2</b> Functions</a></li>
<li class="chapter" data-level="11.3" data-path="gentleintro.html"><a href="gentleintro.html#packages"><i class="fa fa-check"></i><b>11.3</b> Packages</a></li>
<li class="chapter" data-level="11.4" data-path="gentleintro.html"><a href="gentleintro.html#variableassignment"><i class="fa fa-check"></i><b>11.4</b> Variable Assignment</a></li>
<li class="chapter" data-level="11.5" data-path="gentleintro.html"><a href="gentleintro.html#typesofdata"><i class="fa fa-check"></i><b>11.5</b> Types of Data</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="gentleintro.html"><a href="gentleintro.html#numeric-data"><i class="fa fa-check"></i><b>11.5.1</b> <code>numeric</code> Data</a></li>
<li class="chapter" data-level="11.5.2" data-path="gentleintro.html"><a href="gentleintro.html#character-data"><i class="fa fa-check"></i><b>11.5.2</b> <code>character</code> Data</a></li>
<li class="chapter" data-level="11.5.3" data-path="gentleintro.html"><a href="gentleintro.html#date-data"><i class="fa fa-check"></i><b>11.5.3</b> <code>Date</code> Data</a></li>
<li class="chapter" data-level="11.5.4" data-path="gentleintro.html"><a href="gentleintro.html#logical-data"><i class="fa fa-check"></i><b>11.5.4</b> <code>logical</code> Data</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="gentleintro.html"><a href="gentleintro.html#vectors"><i class="fa fa-check"></i><b>11.6</b> Vectors</a></li>
<li class="chapter" data-level="11.7" data-path="gentleintro.html"><a href="gentleintro.html#lists"><i class="fa fa-check"></i><b>11.7</b> Lists</a></li>
<li class="chapter" data-level="11.8" data-path="gentleintro.html"><a href="gentleintro.html#dataframes"><i class="fa fa-check"></i><b>11.8</b> Data Frames</a></li>
<li class="chapter" data-level="11.9" data-path="gentleintro.html"><a href="gentleintro.html#annotate"><i class="fa fa-check"></i><b>11.9</b> Annotations</a></li>
<li class="chapter" data-level="11.10" data-path="gentleintro.html"><a href="gentleintro.html#summary-8"><i class="fa fa-check"></i><b>11.10</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="setwd.html"><a href="setwd.html"><i class="fa fa-check"></i><b>12</b> Setting a Working Directory</a>
<ul>
<li class="chapter" data-level="12.0.1" data-path="setwd.html"><a href="setwd.html#identify-the-current-working-directory"><i class="fa fa-check"></i><b>12.0.1</b> Identify the Current Working Directory</a></li>
<li class="chapter" data-level="12.0.2" data-path="setwd.html"><a href="setwd.html#set-a-new-working-directory"><i class="fa fa-check"></i><b>12.0.2</b> Set a New Working Directory</a></li>
<li class="chapter" data-level="12.1" data-path="setwd.html"><a href="setwd.html#summary-9"><i class="fa fa-check"></i><b>12.1</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>III Data Acquisition &amp; Management</b></span></li>
<li class="chapter" data-level="13" data-path="read.html"><a href="read.html"><i class="fa fa-check"></i><b>13</b> Reading Data into R</a>
<ul>
<li class="chapter" data-level="13.1" data-path="read.html"><a href="read.html#readcsv"><i class="fa fa-check"></i><b>13.1</b> Read a .csv File</a></li>
<li class="chapter" data-level="13.2" data-path="read.html"><a href="read.html#readxlsx"><i class="fa fa-check"></i><b>13.2</b> Read a .xlsx File</a></li>
<li class="chapter" data-level="13.3" data-path="read.html"><a href="read.html#read_summary"><i class="fa fa-check"></i><b>13.3</b> Summary</a></li>
<li class="chapter" data-level="13.4" data-path="read.html"><a href="read.html#read_supplement"><i class="fa fa-check"></i><b>13.4</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="read.html"><a href="read.html#read_additionalfunctions"><i class="fa fa-check"></i><b>13.4.1</b> Additional Functions to Read a .csv File</a></li>
<li class="chapter" data-level="13.4.2" data-path="read.html"><a href="read.html#read_skiprows"><i class="fa fa-check"></i><b>13.4.2</b> Skip Rows of Data During Read</a></li>
<li class="chapter" data-level="13.4.3" data-path="read.html"><a href="read.html#listdatafiles"><i class="fa fa-check"></i><b>13.4.3</b> List Data File Names in Working Directory</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="addnames.html"><a href="addnames.html"><i class="fa fa-check"></i><b>14</b> Removing, Adding, &amp; Changing Variable Names</a>
<ul>
<li class="chapter" data-level="14.1" data-path="addnames.html"><a href="addnames.html#remove_variablenames"><i class="fa fa-check"></i><b>14.1</b> Remove Variable Names from a Data Frame Object</a></li>
<li class="chapter" data-level="14.2" data-path="addnames.html"><a href="addnames.html#add_variablenames"><i class="fa fa-check"></i><b>14.2</b> Add Variable Names to a Data Frame Object</a></li>
<li class="chapter" data-level="14.3" data-path="addnames.html"><a href="addnames.html#change_variablenames"><i class="fa fa-check"></i><b>14.3</b> Change Specific Variable Names in a Data Frame Object</a></li>
<li class="chapter" data-level="14.4" data-path="addnames.html"><a href="addnames.html#summary-10"><i class="fa fa-check"></i><b>14.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="write.html"><a href="write.html"><i class="fa fa-check"></i><b>15</b> Writing Data from R</a>
<ul>
<li class="chapter" data-level="15.1" data-path="write.html"><a href="write.html#write-data-frame-to-working-directory"><i class="fa fa-check"></i><b>15.1</b> Write Data Frame to Working Directory</a></li>
<li class="chapter" data-level="15.2" data-path="write.html"><a href="write.html#write-table-to-working-directory"><i class="fa fa-check"></i><b>15.2</b> Write Table to Working Directory</a></li>
<li class="chapter" data-level="15.3" data-path="write.html"><a href="write.html#summary-11"><i class="fa fa-check"></i><b>15.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>16</b> Arranging (Sorting) Data</a>
<ul>
<li class="chapter" data-level="16.1" data-path="arrange.html"><a href="arrange.html#arrangebyvalues"><i class="fa fa-check"></i><b>16.1</b> Arrange (Sort) Data</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="arrange.html"><a href="arrange.html#opt1_arrange_withpipe"><i class="fa fa-check"></i><b>16.1.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="16.1.2" data-path="arrange.html"><a href="arrange.html#opt1_arrange_withoutpipe"><i class="fa fa-check"></i><b>16.1.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="arrange.html"><a href="arrange.html#summary-12"><i class="fa fa-check"></i><b>16.2</b> Summary</a></li>
<li class="chapter" data-level="16.3" data-path="arrange.html"><a href="arrange.html#arrange_supplement"><i class="fa fa-check"></i><b>16.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="arrange.html"><a href="arrange.html#arrange_orderfunction"><i class="fa fa-check"></i><b>16.3.1</b> <code>order</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="join.html"><a href="join.html"><i class="fa fa-check"></i><b>17</b> Joining (Merging) Data</a>
<ul>
<li class="chapter" data-level="17.1" data-path="join.html"><a href="join.html#horizontaljoin"><i class="fa fa-check"></i><b>17.1</b> Horizontal Join (Merge)</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="join.html"><a href="join.html#opt2_join_withpipe"><i class="fa fa-check"></i><b>17.1.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="17.1.2" data-path="join.html"><a href="join.html#opt2_join_withoutpipe"><i class="fa fa-check"></i><b>17.1.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="join.html"><a href="join.html#verticaljoin"><i class="fa fa-check"></i><b>17.2</b> Vertical Join (Merge)</a></li>
<li class="chapter" data-level="17.3" data-path="join.html"><a href="join.html#summary-13"><i class="fa fa-check"></i><b>17.3</b> Summary</a></li>
<li class="chapter" data-level="17.4" data-path="join.html"><a href="join.html#join_supplement"><i class="fa fa-check"></i><b>17.4</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="join.html"><a href="join.html#join_mergefunction"><i class="fa fa-check"></i><b>17.4.1</b> <code>merge</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>18</b> Filtering Data</a>
<ul>
<li class="chapter" data-level="18.1" data-path="filter.html"><a href="filter.html#filter_cases"><i class="fa fa-check"></i><b>18.1</b> Filter Cases from Data Frame</a>
<ul>
<li class="chapter" data-level="18.1.1" data-path="filter.html"><a href="filter.html#with-pipes"><i class="fa fa-check"></i><b>18.1.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="18.1.2" data-path="filter.html"><a href="filter.html#without-pipes"><i class="fa fa-check"></i><b>18.1.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="filter.html"><a href="filter.html#remove-single-variable-from-data-frame"><i class="fa fa-check"></i><b>18.2</b> Remove Single Variable from Data Frame</a></li>
<li class="chapter" data-level="18.3" data-path="filter.html"><a href="filter.html#select_multiplevariables"><i class="fa fa-check"></i><b>18.3</b> Select Multiple Variables from Data Frame</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="filter.html"><a href="filter.html#with-pipe"><i class="fa fa-check"></i><b>18.3.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="18.3.2" data-path="filter.html"><a href="filter.html#without-pipe"><i class="fa fa-check"></i><b>18.3.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="filter.html"><a href="filter.html#remove_multiplevariables"><i class="fa fa-check"></i><b>18.4</b> Remove Multiple Variables from Data Frame</a>
<ul>
<li class="chapter" data-level="18.4.1" data-path="filter.html"><a href="filter.html#with-pipe-1"><i class="fa fa-check"></i><b>18.4.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="18.4.2" data-path="filter.html"><a href="filter.html#without-pipe-1"><i class="fa fa-check"></i><b>18.4.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="filter.html"><a href="filter.html#summary-14"><i class="fa fa-check"></i><b>18.5</b> Summary</a></li>
<li class="chapter" data-level="18.6" data-path="filter.html"><a href="filter.html#filter_supplement"><i class="fa fa-check"></i><b>18.6</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="18.6.1" data-path="filter.html"><a href="filter.html#filter_subset_supplement"><i class="fa fa-check"></i><b>18.6.1</b> <code>subset</code> Function from Base R</a></li>
<li class="chapter" data-level="18.6.2" data-path="filter.html"><a href="filter.html#str_detect_supp"><i class="fa fa-check"></i><b>18.6.2</b> Filter by Pattern Contained within String</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="clean.html"><a href="clean.html"><i class="fa fa-check"></i><b>19</b> Cleaning Data</a>
<ul>
<li class="chapter" data-level="19.1" data-path="clean.html"><a href="clean.html#review-data"><i class="fa fa-check"></i><b>19.1</b> Review Data</a></li>
<li class="chapter" data-level="19.2" data-path="clean.html"><a href="clean.html#clean-data"><i class="fa fa-check"></i><b>19.2</b> Clean Data</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="clean.html"><a href="clean.html#replace-a-specific-value-for-a-specific-case"><i class="fa fa-check"></i><b>19.2.1</b> Replace a Specific Value for a Specific Case</a></li>
<li class="chapter" data-level="19.2.2" data-path="clean.html"><a href="clean.html#replace-a-specific-value-for-all-cases-with-a-particular-value"><i class="fa fa-check"></i><b>19.2.2</b> Replace a Specific Value for All Cases with a Particular Value</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="clean.html"><a href="clean.html#rename-variables"><i class="fa fa-check"></i><b>19.3</b> Rename Variables</a></li>
<li class="chapter" data-level="19.4" data-path="clean.html"><a href="clean.html#other-approaches-to-cleaning-data"><i class="fa fa-check"></i><b>19.4</b> Other Approaches to Cleaning Data</a>
<ul>
<li class="chapter" data-level="19.4.1" data-path="clean.html"><a href="clean.html#changing-the-case-of-variable-names"><i class="fa fa-check"></i><b>19.4.1</b> Changing the Case of Variable Names</a></li>
<li class="chapter" data-level="19.4.2" data-path="clean.html"><a href="clean.html#changing-the-case-of-character-variable-values"><i class="fa fa-check"></i><b>19.4.2</b> Changing the Case of Character Variable Values</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="clean.html"><a href="clean.html#summary-15"><i class="fa fa-check"></i><b>19.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="aggregatesegment.html"><a href="aggregatesegment.html"><i class="fa fa-check"></i><b>20</b> Aggregating &amp; Segmenting Data</a>
<ul>
<li class="chapter" data-level="20.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup"><i class="fa fa-check"></i><b>20.1</b> Counts By Group</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup_pipes"><i class="fa fa-check"></i><b>20.1.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="20.1.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup_nopipes"><i class="fa fa-check"></i><b>20.1.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup"><i class="fa fa-check"></i><b>20.2</b> Measures of Central Tendency and Dispersion By Group</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup_pipes"><i class="fa fa-check"></i><b>20.2.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="20.2.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup_nopipes"><i class="fa fa-check"></i><b>20.2.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable"><i class="fa fa-check"></i><b>20.3</b> Add Variable to Data Frame Containing Aggregated Values</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable_pipes"><i class="fa fa-check"></i><b>20.3.1</b> <em>With</em> Pipes</a></li>
<li class="chapter" data-level="20.3.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable_nopipes"><i class="fa fa-check"></i><b>20.3.2</b> <em>Without</em> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="aggregatesegment.html"><a href="aggregatesegment.html#visualize_bygroup"><i class="fa fa-check"></i><b>20.4</b> Visualize Data By Group</a></li>
<li class="chapter" data-level="20.5" data-path="aggregatesegment.html"><a href="aggregatesegment.html#summary-16"><i class="fa fa-check"></i><b>20.5</b> Summary</a></li>
<li class="chapter" data-level="20.6" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_supplement"><i class="fa fa-check"></i><b>20.6</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="20.6.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_subset_supplement"><i class="fa fa-check"></i><b>20.6.1</b> <code>describeBy</code> Function from <code>psych</code> Package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="21" data-path="manipulate.html"><a href="manipulate.html"><i class="fa fa-check"></i><b>21</b> Manipulating &amp; Restructuring Data</a>
<ul>
<li class="chapter" data-level="21.1" data-path="manipulate.html"><a href="manipulate.html#widetolong"><i class="fa fa-check"></i><b>21.1</b> Wide-to-Long Format Data Manipulation</a>
<ul>
<li class="chapter" data-level="21.1.1" data-path="manipulate.html"><a href="manipulate.html#widetolong_withpipe"><i class="fa fa-check"></i><b>21.1.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="21.1.2" data-path="manipulate.html"><a href="manipulate.html#widetolong_withoutpipe"><i class="fa fa-check"></i><b>21.1.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="manipulate.html"><a href="manipulate.html#longtowide"><i class="fa fa-check"></i><b>21.2</b> Long-to-Wide Format Data Manipulation</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="manipulate.html"><a href="manipulate.html#longtowide_withpipe"><i class="fa fa-check"></i><b>21.2.1</b> <em>With</em> Pipe</a></li>
<li class="chapter" data-level="21.2.2" data-path="manipulate.html"><a href="manipulate.html#longtowide_withoutpipe"><i class="fa fa-check"></i><b>21.2.2</b> <em>Without</em> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="manipulate.html"><a href="manipulate.html#summary-17"><i class="fa fa-check"></i><b>21.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="center.html"><a href="center.html"><i class="fa fa-check"></i><b>22</b> Centering &amp; Standardizing Variables</a>
<ul>
<li class="chapter" data-level="22.1" data-path="center.html"><a href="center.html#grandmean_center"><i class="fa fa-check"></i><b>22.1</b> Grand-Mean Centering Variables</a>
<ul>
<li class="chapter" data-level="22.1.1" data-path="center.html"><a href="center.html#mean_function_center"><i class="fa fa-check"></i><b>22.1.1</b> Option 1: Basic Arithmetic and <code>mean</code> Function from Base R</a></li>
<li class="chapter" data-level="22.1.2" data-path="center.html"><a href="center.html#scale_function_center"><i class="fa fa-check"></i><b>22.1.2</b> Option 2: <code>scale</code> Function from Base R</a></li>
<li class="chapter" data-level="22.1.3" data-path="center.html"><a href="center.html#mutate_function_center"><i class="fa fa-check"></i><b>22.1.3</b> Option 3: <code>mutate</code> Function from <code>dplyr</code> and <code>mean</code> Function from Base R</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="center.html"><a href="center.html#standardize_center"><i class="fa fa-check"></i><b>22.2</b> Standardizing Variables</a>
<ul>
<li class="chapter" data-level="22.2.1" data-path="center.html"><a href="center.html#scale_function_standardize"><i class="fa fa-check"></i><b>22.2.1</b> Option 1: <code>scale</code> Function from Base R</a></li>
<li class="chapter" data-level="22.2.2" data-path="center.html"><a href="center.html#mutate_function_standardize"><i class="fa fa-check"></i><b>22.2.2</b> Option 2: <code>mutate</code> Function from <code>dplyr</code> and <code>scale</code> Function from Base R</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="center.html"><a href="center.html#summary_center"><i class="fa fa-check"></i><b>22.3</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>IV Employee Demographics</b></span></li>
<li class="chapter" data-level="23" data-path="employeedemographics.html"><a href="employeedemographics.html"><i class="fa fa-check"></i><b>23</b> Introduction to Employee Demographics</a></li>
<li class="chapter" data-level="24" data-path="descriptives.html"><a href="descriptives.html"><i class="fa fa-check"></i><b>24</b> Describing Employee Demographics Using Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="24.1" data-path="descriptives.html"><a href="descriptives.html#conceptualoverview_descriptives"><i class="fa fa-check"></i><b>24.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="24.1.1" data-path="descriptives.html"><a href="descriptives.html#measurementscales"><i class="fa fa-check"></i><b>24.1.1</b> Review of Measurement Scales</a></li>
<li class="chapter" data-level="24.1.2" data-path="descriptives.html"><a href="descriptives.html#constructs_measures_measurementscales"><i class="fa fa-check"></i><b>24.1.2</b> Constructs, Measures, &amp; Measurement Scales</a></li>
<li class="chapter" data-level="24.1.3" data-path="descriptives.html"><a href="descriptives.html#typesof_descriptivestatistics"><i class="fa fa-check"></i><b>24.1.3</b> Types of Descriptive Statistics</a></li>
<li class="chapter" data-level="24.1.4" data-path="descriptives.html"><a href="descriptives.html#samplewriteup_descriptives"><i class="fa fa-check"></i><b>24.1.4</b> Sample Write-Up</a></li>
</ul></li>
<li class="chapter" data-level="24.2" data-path="descriptives.html"><a href="descriptives.html#tutorial_descriptives"><i class="fa fa-check"></i><b>24.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="24.2.1" data-path="descriptives.html"><a href="descriptives.html#videotutorial_descriptives"><i class="fa fa-check"></i><b>24.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="24.2.2" data-path="descriptives.html"><a href="descriptives.html#functions_descriptives"><i class="fa fa-check"></i><b>24.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="24.2.3" data-path="descriptives.html"><a href="descriptives.html#initsteps_descriptives"><i class="fa fa-check"></i><b>24.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="24.2.4" data-path="descriptives.html"><a href="descriptives.html#determine_measurementscale"><i class="fa fa-check"></i><b>24.2.4</b> Determine the Measurement Scale</a></li>
<li class="chapter" data-level="24.2.5" data-path="descriptives.html"><a href="descriptives.html#describe_nominal_ordinal"><i class="fa fa-check"></i><b>24.2.5</b> Describe Nominal &amp; Ordinal (Categorical) Variables</a></li>
<li class="chapter" data-level="24.2.6" data-path="descriptives.html"><a href="descriptives.html#describe_interval_ratio"><i class="fa fa-check"></i><b>24.2.6</b> Describe Interval &amp; Ratio (Continuous) Variables</a></li>
<li class="chapter" data-level="24.2.7" data-path="descriptives.html"><a href="descriptives.html#summary_descriptives"><i class="fa fa-check"></i><b>24.2.7</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="25" data-path="crosstabs.html"><a href="crosstabs.html"><i class="fa fa-check"></i><b>25</b> Summarizing Two or More Categorical Variables Using Cross-Tabulations</a>
<ul>
<li class="chapter" data-level="25.1" data-path="crosstabs.html"><a href="crosstabs.html#conceptualoverview_crosstabs"><i class="fa fa-check"></i><b>25.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="25.1.1" data-path="crosstabs.html"><a href="crosstabs.html#review_crosstabs"><i class="fa fa-check"></i><b>25.1.1</b> Review of Cross-Tabulation</a></li>
<li class="chapter" data-level="25.1.2" data-path="crosstabs.html"><a href="crosstabs.html#samplewriteup_crosstabs"><i class="fa fa-check"></i><b>25.1.2</b> Sample Write-Up</a></li>
</ul></li>
<li class="chapter" data-level="25.2" data-path="crosstabs.html"><a href="crosstabs.html#tutorial_crosstabs"><i class="fa fa-check"></i><b>25.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="25.2.1" data-path="crosstabs.html"><a href="crosstabs.html#videotutorial_crosstabs"><i class="fa fa-check"></i><b>25.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="25.2.2" data-path="crosstabs.html"><a href="crosstabs.html#functions_crosstabs"><i class="fa fa-check"></i><b>25.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="25.2.3" data-path="crosstabs.html"><a href="crosstabs.html#initsteps_tables"><i class="fa fa-check"></i><b>25.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="25.2.4" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs"><i class="fa fa-check"></i><b>25.2.4</b> Two-Way Cross-Tabulation</a></li>
<li class="chapter" data-level="25.2.5" data-path="crosstabs.html"><a href="crosstabs.html#threeway_crosstabs"><i class="fa fa-check"></i><b>25.2.5</b> Three-Way Cross-Tabulation</a></li>
<li class="chapter" data-level="25.2.6" data-path="crosstabs.html"><a href="crosstabs.html#summary-summar_crosstabs"><i class="fa fa-check"></i><b>25.2.6</b> Summary {summar_crosstabs}</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="pivottables.html"><a href="pivottables.html"><i class="fa fa-check"></i><b>26</b> Applying Pivot Tables for Data Exploration</a>
<ul>
<li class="chapter" data-level="26.1" data-path="pivottables.html"><a href="pivottables.html#conceptualoverview_pivottables"><i class="fa fa-check"></i><b>26.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="26.2" data-path="pivottables.html"><a href="pivottables.html#tutorial_pivottables"><i class="fa fa-check"></i><b>26.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="26.2.1" data-path="pivottables.html"><a href="pivottables.html#videotutorial_pivottables"><i class="fa fa-check"></i><b>26.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="26.2.2" data-path="pivottables.html"><a href="pivottables.html#functions_pivottables"><i class="fa fa-check"></i><b>26.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="26.2.3" data-path="pivottables.html"><a href="pivottables.html#initsteps_pivottables"><i class="fa fa-check"></i><b>26.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="26.2.4" data-path="pivottables.html"><a href="pivottables.html#create_pivottables"><i class="fa fa-check"></i><b>26.2.4</b> Create a Pivot Table</a></li>
<li class="chapter" data-level="26.2.5" data-path="pivottables.html"><a href="pivottables.html#summary_pivottables"><i class="fa fa-check"></i><b>26.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V Employee Surveys</b></span></li>
<li class="chapter" data-level="27" data-path="employeesurveys.html"><a href="employeesurveys.html"><i class="fa fa-check"></i><b>27</b> Introduction to Employee Surveys</a></li>
<li class="part"><span><b>VI Employee Training</b></span></li>
<li class="chapter" data-level="28" data-path="employeetraining.html"><a href="employeetraining.html"><i class="fa fa-check"></i><b>28</b> Introduction to Employee Training</a>
<ul>
<li class="chapter" data-level="28.1" data-path="employeetraining.html"><a href="employeetraining.html#trainingevaluation_employeetraining"><i class="fa fa-check"></i><b>28.1</b> Training Evaluation</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="pretestposttest.html"><a href="pretestposttest.html"><i class="fa fa-check"></i><b>29</b> Evaluating a Pre-Test/Post-Test without Control Group Design Using Paired-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="29.1" data-path="pretestposttest.html"><a href="pretestposttest.html#conceptualoverview_pretestposttest_psttest"><i class="fa fa-check"></i><b>29.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="29.1.1" data-path="pretestposttest.html"><a href="pretestposttest.html#review_pretestposttest"><i class="fa fa-check"></i><b>29.1.1</b> Review of Pre-Test/Post-Test without Control Group Design</a></li>
<li class="chapter" data-level="29.1.2" data-path="pretestposttest.html"><a href="pretestposttest.html#review_psttest"><i class="fa fa-check"></i><b>29.1.2</b> Review of Paired-Samples <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="29.2" data-path="pretestposttest.html"><a href="pretestposttest.html#tutorial_psttest"><i class="fa fa-check"></i><b>29.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="29.2.1" data-path="pretestposttest.html"><a href="pretestposttest.html#videotutorial_psttest"><i class="fa fa-check"></i><b>29.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="29.2.2" data-path="pretestposttest.html"><a href="pretestposttest.html#functions_psttest"><i class="fa fa-check"></i><b>29.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="29.2.3" data-path="pretestposttest.html"><a href="pretestposttest.html#initsteps_psttest"><i class="fa fa-check"></i><b>29.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="29.2.4" data-path="pretestposttest.html"><a href="pretestposttest.html#estimate_psttest"><i class="fa fa-check"></i><b>29.2.4</b> Estimate Paired-Samples <em>t</em>-test</a></li>
<li class="chapter" data-level="29.2.5" data-path="pretestposttest.html"><a href="pretestposttest.html#barchart_psttest"><i class="fa fa-check"></i><b>29.2.5</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="29.2.6" data-path="pretestposttest.html"><a href="pretestposttest.html#summary_psttest"><i class="fa fa-check"></i><b>29.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="29.3" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_supplement"><i class="fa fa-check"></i><b>29.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="29.3.1" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_supplement_functions"><i class="fa fa-check"></i><b>29.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="29.3.2" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_initsteps_supplement"><i class="fa fa-check"></i><b>29.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="29.3.3" data-path="pretestposttest.html"><a href="pretestposttest.html#t.test_function_psttest"><i class="fa fa-check"></i><b>29.3.3</b> <code>t.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="30" data-path="posttestonly.html"><a href="posttestonly.html"><i class="fa fa-check"></i><b>30</b> Evaluating a Post-Test-Only with Control Group Design Using Independent-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="30.1" data-path="posttestonly.html"><a href="posttestonly.html#conceptualoverview_posttestonly_isttest"><i class="fa fa-check"></i><b>30.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="30.1.1" data-path="posttestonly.html"><a href="posttestonly.html#review_posttestonly"><i class="fa fa-check"></i><b>30.1.1</b> Review of Post-Test-Only with Control Group Design</a></li>
<li class="chapter" data-level="30.1.2" data-path="posttestonly.html"><a href="posttestonly.html#review_isttest"><i class="fa fa-check"></i><b>30.1.2</b> Review of Independent-Samples <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="30.2" data-path="posttestonly.html"><a href="posttestonly.html#tutorial_isttest"><i class="fa fa-check"></i><b>30.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="30.2.1" data-path="posttestonly.html"><a href="posttestonly.html#videotutorial_isttest"><i class="fa fa-check"></i><b>30.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="30.2.2" data-path="posttestonly.html"><a href="posttestonly.html#functions_isttest"><i class="fa fa-check"></i><b>30.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="30.2.3" data-path="posttestonly.html"><a href="posttestonly.html#initsteps_isttest"><i class="fa fa-check"></i><b>30.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="30.2.4" data-path="posttestonly.html"><a href="posttestonly.html#estimate_isttest"><i class="fa fa-check"></i><b>30.2.4</b> Estimate Independent-Samples <em>t</em>-test</a></li>
<li class="chapter" data-level="30.2.5" data-path="posttestonly.html"><a href="posttestonly.html#barchart_isttest"><i class="fa fa-check"></i><b>30.2.5</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="30.2.6" data-path="posttestonly.html"><a href="posttestonly.html#summary_isttest"><i class="fa fa-check"></i><b>30.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="30.3" data-path="posttestonly.html"><a href="posttestonly.html#isttest_supplement"><i class="fa fa-check"></i><b>30.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="30.3.1" data-path="posttestonly.html"><a href="posttestonly.html#isttest_supplement_functions"><i class="fa fa-check"></i><b>30.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="30.3.2" data-path="posttestonly.html"><a href="posttestonly.html#isttest_initsteps_supplement"><i class="fa fa-check"></i><b>30.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="30.3.3" data-path="posttestonly.html"><a href="posttestonly.html#t.test_function_isttest"><i class="fa fa-check"></i><b>30.3.3</b> <code>t.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="31" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html"><i class="fa fa-check"></i><b>31</b> Evaluating a Post-Test-Only with Two Comparison Groups Design Using One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="31.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#conceptualoverview_posttestonly_threegroups_onewayanova"><i class="fa fa-check"></i><b>31.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="31.1.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#review_posttestonly_threegroups"><i class="fa fa-check"></i><b>31.1.1</b> Review of Post-Test-Only with Two Comparison Groups Design</a></li>
<li class="chapter" data-level="31.1.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#review_onewayanova"><i class="fa fa-check"></i><b>31.1.2</b> Review of One-Way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="31.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#tutorial_onewayanova"><i class="fa fa-check"></i><b>31.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="31.2.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#videotutorial_onewayanova"><i class="fa fa-check"></i><b>31.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="31.2.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#functions_onewayanova"><i class="fa fa-check"></i><b>31.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="31.2.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#initsteps_onewayanova"><i class="fa fa-check"></i><b>31.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="31.2.4" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#teststatisticalassumptions_onewayanova"><i class="fa fa-check"></i><b>31.2.4</b> Test Statistical Assumptions</a></li>
<li class="chapter" data-level="31.2.5" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#estimate_onewayanova"><i class="fa fa-check"></i><b>31.2.5</b> Estimate One-Way ANOVA</a></li>
<li class="chapter" data-level="31.2.6" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#barchart_onewayanova"><i class="fa fa-check"></i><b>31.2.6</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="31.2.7" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#summary_onewayanova"><i class="fa fa-check"></i><b>31.2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="31.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_supplement"><i class="fa fa-check"></i><b>31.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="31.3.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_supplement_functions"><i class="fa fa-check"></i><b>31.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="31.3.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_initsteps_supplement"><i class="fa fa-check"></i><b>31.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="31.3.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#aov_function_onewayanova"><i class="fa fa-check"></i><b>31.3.3</b> <code>aov</code> Function from Base R</a></li>
<li class="chapter" data-level="31.3.4" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#apatable_onewayanova"><i class="fa fa-check"></i><b>31.3.4</b> APA-Style Table of Results</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VII Employee Selection</b></span></li>
<li class="chapter" data-level="32" data-path="selection.html"><a href="selection.html"><i class="fa fa-check"></i><b>32</b> Introduction to Employee Selection</a></li>
<li class="chapter" data-level="33" data-path="disparateimpact.html"><a href="disparateimpact.html"><i class="fa fa-check"></i><b>33</b> Investigating Disparate Impact</a>
<ul>
<li class="chapter" data-level="33.1" data-path="disparateimpact.html"><a href="disparateimpact.html#conceptualoverview_disparateimpact"><i class="fa fa-check"></i><b>33.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="33.2" data-path="disparateimpact.html"><a href="disparateimpact.html#tutorial_disparateimpact"><i class="fa fa-check"></i><b>33.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="33.2.1" data-path="disparateimpact.html"><a href="disparateimpact.html#videotutorial_disparateimpact"><i class="fa fa-check"></i><b>33.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="33.2.2" data-path="disparateimpact.html"><a href="disparateimpact.html#functions_disparateimpact"><i class="fa fa-check"></i><b>33.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="33.2.3" data-path="disparateimpact.html"><a href="disparateimpact.html#initsteps_disparateimpact"><i class="fa fa-check"></i><b>33.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="33.2.4" data-path="disparateimpact.html"><a href="disparateimpact.html#fourfifthsrule"><i class="fa fa-check"></i><b>33.2.4</b> 4/5ths Rule</a></li>
<li class="chapter" data-level="33.2.5" data-path="disparateimpact.html"><a href="disparateimpact.html#chisquaretest_disparateimpact"><i class="fa fa-check"></i><b>33.2.5</b> Chi-Squared (<span class="math inline">\(\chi^2\)</span>) Test of Independence</a></li>
<li class="chapter" data-level="33.2.6" data-path="disparateimpact.html"><a href="disparateimpact.html#fisherexacttest"><i class="fa fa-check"></i><b>33.2.6</b> Fisher Exact Test</a></li>
<li class="chapter" data-level="33.2.7" data-path="disparateimpact.html"><a href="disparateimpact.html#zdifference_test_disparateimpact"><i class="fa fa-check"></i><b>33.2.7</b> <span class="math inline">\(Z_{D}\)</span> Test</a></li>
<li class="chapter" data-level="33.2.8" data-path="disparateimpact.html"><a href="disparateimpact.html#z_impactratiotest"><i class="fa fa-check"></i><b>33.2.8</b> <span class="math inline">\(Z_{IR}\)</span> Test</a></li>
<li class="chapter" data-level="33.2.9" data-path="disparateimpact.html"><a href="disparateimpact.html#summary_disparatetreatment"><i class="fa fa-check"></i><b>33.2.9</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="34" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html"><i class="fa fa-check"></i><b>34</b> Estimating Criterion-Related Validity Using Correlation</a>
<ul>
<li class="chapter" data-level="34.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#conceptualoverview_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="34.1.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#review_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.1.1</b> Review of Criterion-Related Validity</a></li>
<li class="chapter" data-level="34.1.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#review_correlation"><i class="fa fa-check"></i><b>34.1.2</b> Review of Correlation</a></li>
</ul></li>
<li class="chapter" data-level="34.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#tutorial_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="34.2.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#videotutorial_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="34.2.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#functions_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="34.2.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#initsteps_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="34.2.4" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#scatterplot_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.2.4</b> Visualize Association Using a Scatter Plot</a></li>
<li class="chapter" data-level="34.2.5" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#estimate_correlation"><i class="fa fa-check"></i><b>34.2.5</b> Estimate Correlation</a></li>
<li class="chapter" data-level="34.2.6" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#summary_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="34.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_supplement"><i class="fa fa-check"></i><b>34.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="34.3.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_supplement_functions"><i class="fa fa-check"></i><b>34.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="34.3.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_initsteps_supplement"><i class="fa fa-check"></i><b>34.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="34.3.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#cor_function"><i class="fa fa-check"></i><b>34.3.3</b> <code>cor</code> Function from Base R</a></li>
<li class="chapter" data-level="34.3.4" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#cortest_function"><i class="fa fa-check"></i><b>34.3.4</b> <code>cor.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="35" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html"><i class="fa fa-check"></i><b>35</b> Predicting Criterion Scores Using Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="35.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#conceptualoverview_predictingcriterionscores"><i class="fa fa-check"></i><b>35.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="35.1.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#review_slr"><i class="fa fa-check"></i><b>35.1.1</b> Review of Simple Linear Regression</a></li>
<li class="chapter" data-level="35.1.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#review_prediction_slr"><i class="fa fa-check"></i><b>35.1.2</b> Predicting Future Criterion Scores Using Simple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="35.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#tutorial_predictingcriterionscores"><i class="fa fa-check"></i><b>35.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="35.2.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#videotutorial_predictingcriterionscores"><i class="fa fa-check"></i><b>35.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="35.2.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#functions_predictingcriterionscores"><i class="fa fa-check"></i><b>35.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="35.2.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#initsteps_slr"><i class="fa fa-check"></i><b>35.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="35.2.4" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#estimate_slr"><i class="fa fa-check"></i><b>35.2.4</b> Estimate Simple Linear Regression Model</a></li>
<li class="chapter" data-level="35.2.5" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_slr"><i class="fa fa-check"></i><b>35.2.5</b> Predict Criterion Scores</a></li>
<li class="chapter" data-level="35.2.6" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#summary_predictingcriterionscores"><i class="fa fa-check"></i><b>35.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="35.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_supplement"><i class="fa fa-check"></i><b>35.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="35.3.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_supplement_functions"><i class="fa fa-check"></i><b>35.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="35.3.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_initsteps_supplement"><i class="fa fa-check"></i><b>35.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="35.3.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#lm_function_slr"><i class="fa fa-check"></i><b>35.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="35.3.4" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predict_function_slr"><i class="fa fa-check"></i><b>35.3.4</b> <code>predict</code> Function from Base R</a></li>
<li class="chapter" data-level="35.3.5" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#apatable_slr"><i class="fa fa-check"></i><b>35.3.5</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="36" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html"><i class="fa fa-check"></i><b>36</b> Estimating Incremental Validity Using Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="36.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#conceptualoverview_incrementalvalidity"><i class="fa fa-check"></i><b>36.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="36.1.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#review_mlr"><i class="fa fa-check"></i><b>36.1.1</b> Review of Multiple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="36.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#tutorial_incrementalvalidity"><i class="fa fa-check"></i><b>36.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="36.2.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#videotutorial_incrementalvalidity"><i class="fa fa-check"></i><b>36.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="36.2.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#function_incrementalvalidity"><i class="fa fa-check"></i><b>36.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="36.2.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#initsteps_mlr"><i class="fa fa-check"></i><b>36.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="36.2.4" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#estimate_mlr"><i class="fa fa-check"></i><b>36.2.4</b> Estimate Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="36.2.5" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#summary_incrementalvalidity"><i class="fa fa-check"></i><b>36.2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="36.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_supplement"><i class="fa fa-check"></i><b>36.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="36.3.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_supplement_functions"><i class="fa fa-check"></i><b>36.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="36.3.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_initsteps_supplement"><i class="fa fa-check"></i><b>36.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="36.3.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#lm_function_mlr"><i class="fa fa-check"></i><b>36.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="36.3.4" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#apatable_mlr"><i class="fa fa-check"></i><b>36.3.4</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="37" data-path="compensatory.html"><a href="compensatory.html"><i class="fa fa-check"></i><b>37</b> Applying a Compensatory Approach to Selection Decisions Using Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="37.1" data-path="compensatory.html"><a href="compensatory.html#conceptualoverview_compensatory"><i class="fa fa-check"></i><b>37.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="37.1.1" data-path="compensatory.html"><a href="compensatory.html#review_compensatory_mlr"><i class="fa fa-check"></i><b>37.1.1</b> Review of Multiple Linear Regression</a></li>
<li class="chapter" data-level="37.1.2" data-path="compensatory.html"><a href="compensatory.html#review_compensatory"><i class="fa fa-check"></i><b>37.1.2</b> Review of Compensatory Approach</a></li>
</ul></li>
<li class="chapter" data-level="37.2" data-path="compensatory.html"><a href="compensatory.html#tutorial_compensatory"><i class="fa fa-check"></i><b>37.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="37.2.1" data-path="compensatory.html"><a href="compensatory.html#videotutorial_compensatory"><i class="fa fa-check"></i><b>37.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="37.2.2" data-path="compensatory.html"><a href="compensatory.html#function_compensatory"><i class="fa fa-check"></i><b>37.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="37.2.3" data-path="compensatory.html"><a href="compensatory.html#initsteps_compensatory"><i class="fa fa-check"></i><b>37.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="37.2.4" data-path="compensatory.html"><a href="compensatory.html#estimate_compensatory"><i class="fa fa-check"></i><b>37.2.4</b> Estimate Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="37.2.5" data-path="compensatory.html"><a href="compensatory.html#predictcriterionscores_compensatory"><i class="fa fa-check"></i><b>37.2.5</b> Predict Criterion Scores</a></li>
<li class="chapter" data-level="37.2.6" data-path="compensatory.html"><a href="compensatory.html#summary_compensatory"><i class="fa fa-check"></i><b>37.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="37.3" data-path="compensatory.html"><a href="compensatory.html#compensatory_supplement"><i class="fa fa-check"></i><b>37.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="37.3.1" data-path="compensatory.html"><a href="compensatory.html#compensatory_supplement_functions"><i class="fa fa-check"></i><b>37.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="37.3.2" data-path="compensatory.html"><a href="compensatory.html#compensatory_initsteps_supplement"><i class="fa fa-check"></i><b>37.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="37.3.3" data-path="compensatory.html"><a href="compensatory.html#lm_predict_functions_compensatory"><i class="fa fa-check"></i><b>37.3.3</b> <code>lm</code> &amp; <code>predict</code> Functions from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="38" data-path="multiplecutoff.html"><a href="multiplecutoff.html"><i class="fa fa-check"></i><b>38</b> Applying a Noncompensatory Approach to Selection Decisions Using Angoff Method</a>
<ul>
<li class="chapter" data-level="38.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#conceptualoverview_multiplecutoff"><i class="fa fa-check"></i><b>38.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="38.1.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#review_multiplecutoff"><i class="fa fa-check"></i><b>38.1.1</b> Review of Noncompensatory Approach</a></li>
</ul></li>
<li class="chapter" data-level="38.2" data-path="multiplecutoff.html"><a href="multiplecutoff.html#tutorial_multiplecutoff"><i class="fa fa-check"></i><b>38.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="38.2.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#function_multiplecutoff"><i class="fa fa-check"></i><b>38.2.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="38.2.2" data-path="multiplecutoff.html"><a href="multiplecutoff.html#initsteps_multiplecutoff"><i class="fa fa-check"></i><b>38.2.2</b> Initial Steps</a></li>
<li class="chapter" data-level="38.2.3" data-path="multiplecutoff.html"><a href="multiplecutoff.html#createcutoffscores_multiplecutoff"><i class="fa fa-check"></i><b>38.2.3</b> Create Cutoff Scores</a></li>
<li class="chapter" data-level="38.2.4" data-path="multiplecutoff.html"><a href="multiplecutoff.html#applycutoffscores_multiplecutoff"><i class="fa fa-check"></i><b>38.2.4</b> Apply Cutoff Scores to Make Selection Decisions</a></li>
<li class="chapter" data-level="38.2.5" data-path="multiplecutoff.html"><a href="multiplecutoff.html#summary_multiplecutoff"><i class="fa fa-check"></i><b>38.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="39" data-path="differentialprediction.html"><a href="differentialprediction.html"><i class="fa fa-check"></i><b>39</b> Testing for Differential Prediction Using Moderated Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="39.1" data-path="differentialprediction.html"><a href="differentialprediction.html#conceptualoverview_differentialprediction"><i class="fa fa-check"></i><b>39.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="39.1.1" data-path="differentialprediction.html"><a href="differentialprediction.html#review_mmlr"><i class="fa fa-check"></i><b>39.1.1</b> Review of Moderated Multiple Linear Regression</a></li>
<li class="chapter" data-level="39.1.2" data-path="differentialprediction.html"><a href="differentialprediction.html#review_differentialprediction"><i class="fa fa-check"></i><b>39.1.2</b> Review of Differential Prediction</a></li>
</ul></li>
<li class="chapter" data-level="39.2" data-path="differentialprediction.html"><a href="differentialprediction.html#tutorial_differentialprediction"><i class="fa fa-check"></i><b>39.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="39.2.1" data-path="differentialprediction.html"><a href="differentialprediction.html#videotutorial_differentialprediction"><i class="fa fa-check"></i><b>39.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="39.2.2" data-path="differentialprediction.html"><a href="differentialprediction.html#function_mmlr"><i class="fa fa-check"></i><b>39.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="39.2.3" data-path="differentialprediction.html"><a href="differentialprediction.html#initsteps_mmlr"><i class="fa fa-check"></i><b>39.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="39.2.4" data-path="differentialprediction.html"><a href="differentialprediction.html#center_mmlr"><i class="fa fa-check"></i><b>39.2.4</b> Grand-Mean Center Continuous Predictor Variables</a></li>
<li class="chapter" data-level="39.2.5" data-path="differentialprediction.html"><a href="differentialprediction.html#estimate_mmlr"><i class="fa fa-check"></i><b>39.2.5</b> Estimate Moderated Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="39.2.6" data-path="differentialprediction.html"><a href="differentialprediction.html#summary_differentialprediction"><i class="fa fa-check"></i><b>39.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="39.3" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_supplement"><i class="fa fa-check"></i><b>39.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="39.3.1" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_supplement_functions"><i class="fa fa-check"></i><b>39.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="39.3.2" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_initsteps_supplement"><i class="fa fa-check"></i><b>39.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="39.3.3" data-path="differentialprediction.html"><a href="differentialprediction.html#lm_function_mmlr"><i class="fa fa-check"></i><b>39.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="39.3.4" data-path="differentialprediction.html"><a href="differentialprediction.html#apatable_mmlr"><i class="fa fa-check"></i><b>39.3.4</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VIII Odds &amp; Ends</b></span></li>
<li class="chapter" data-level="40" data-path="create-portfolio.html"><a href="create-portfolio.html"><i class="fa fa-check"></i><b>40</b> Creating a Data Analytics Portfolio</a></li>
<li class="chapter" data-level="41" data-path="literature-search-review.html"><a href="literature-search-review.html"><i class="fa fa-check"></i><b>41</b> Conducting a Literature Search &amp; Review</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for HR:<br />
<em>An Introduction to Human Resource Analytics Using R</em><br />
BOOK UNDER CONSTRUCTION</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="pretestposttest" class="section level1" number="29">
<h1><span class="header-section-number">Chapter 29</span> Evaluating a Pre-Test/Post-Test without Control Group Design Using Paired-Samples <em>t</em>-test</h1>
<p>In this chapter, we learn about the post-test/pre-test without control group training evaluation design and how a paired-samples <em>t</em>-test can be used to analyze the data acquired from this design. We’ll begin with conceptual overviews of this training evaluation design and of the paired-samples <em>t</em>-test, and then we’ll conclude with a tutorial.</p>
<div id="conceptualoverview_pretestposttest_psttest" class="section level2" number="29.1">
<h2><span class="header-section-number">29.1</span> Conceptual Overview</h2>
<p>In this section, we’ll begin by describing the post-test/pre-test without control group training evaluation design, and we’ll conclude by reviewing the paired-samples <em>t</em>-test, with discussions of statistical assumptions, statistical significance, and practical significance; the section wraps up with a sample-write up of a paired-samples <em>t</em>-test used to evaluate data from a post-test/pre-test without control group training evaluation design.</p>
<div id="review_pretestposttest" class="section level3" number="29.1.1">
<h3><span class="header-section-number">29.1.1</span> Review of Pre-Test/Post-Test without Control Group Design</h3>
<p>In a <strong>pre-test/post-test without control group</strong> training evaluation design (i.e., research design), all employees participate in the same training program, and there is no random assignment and no control group. This design can best be described as <em>pre-experimental</em>. A paired-samples <em>t</em>-test can be used to analyze the data from a pre-test/post-test without control group design, provided the statistical assumptions are satisfied.</p>
<p>Like any evaluation design, there are limitations to the inferences and conclusions we can draw from a pre-test/post-test without control group design. As a strength, this design includes a pre-test, which assesses initial performance on the focal outcome measure. The pre-test serves as a baseline and gives us information about where the employees started with respect to outcome measure prior to completing the training. Further, the addition of a pre-test allows us to assess whether employees’ scores on the outcome measure have <em>changed</em> from before to after training. As a major weakness, this design lacks a control group and, moreover, random assignment to treatment and control groups; for these reasons, this design is not considered (quasi-)experimental. The lack of a control group (i.e., comparison group), means that we are unable to compare if the direction and amount of any observed change from pre-test to post-test differs from a group that did not receive the program training program. Consequently, this design doesn’t give us much confidence that any change we observe was due to the training itself – as opposed to natural maturation and developmental processes or other confounding factors. In other words, this design doesn’t given us much confidence that the training “caused” any change we observe from pre-test to post-test.</p>
</div>
<div id="review_psttest" class="section level3" number="29.1.2">
<h3><span class="header-section-number">29.1.2</span> Review of Paired-Samples <em>t</em>-test</h3>
<p>The <strong>paired-samples <em>t</em>-test</strong> is an inferential statistical analysis that can be used to compare the to compare the mean of the differences between two sets of dependent scores to some population mean; in the context of training evaluation, the population mean is typically set to zero. That is, this analysis helps us understand whether one sample of cases shows evidence of change or difference between two dependent sets of scores. Often dependence refers to the fact that the two sets of scores (through which a difference score is calculated) come from the same group of individuals who were measured (assessed) twice over time (e.g., time 1 assessment and time 2 assessment for same employees), twice using the same scale associated with different foci (e.g., ratings of supervisor satisfaction and coworker satisfaction from same employees), or twice using the same scale evaluating a common target but associated with two different raters/sources (e.g., employee self-ratings of performance and supervisor-ratings of employee performance). The paired-samples <em>t</em>-test is sometimes called a dependent-samples <em>t</em>-test, a repeated-measures <em>t</em>-test, or a Student’s <em>t</em>-test.</p>
<p>The formula for a paired-samples <em>t</em>-test can be written as follows:</p>
<p><span class="math inline">\(t = \frac{\overline{X}_D - \mu_0}{\frac{s_D}{\sqrt{n}}}\)</span></p>
<p>where <span class="math inline">\(\overline{X}_D\)</span> is the mean of the differences between the two sets of dependent scores, <span class="math inline">\(\mu_0\)</span> is the zero or non-zero population mean to which <span class="math inline">\(\overline{X}_D\)</span> is compared, <span class="math inline">\(s_D\)</span> is the standard deviation of the differences between the dependent scores, and <span class="math inline">\(n\)</span> refers to the number of cases (i.e., sample size).</p>
<div id="statisticalassumptions_psttest" class="section level4" number="29.1.2.1">
<h4><span class="header-section-number">29.1.2.1</span> Statistical Assumptions</h4>
<p>The statistical assumptions that should be met prior to running and/or interpreting estimates from a paired-samples <em>t</em>-test include:</p>
<ul>
<li>The difference scores based on the two outcome measures (e.g., pre-test, post-test) are independent of each other, suggesting that cases (employees) are randomly sampled from the underlying population;</li>
<li>The difference scores have a univariate normal distribution in the underlying population.</li>
</ul>
</div>
<div id="statisticalsignficance_psttest" class="section level4" number="29.1.2.2">
<h4><span class="header-section-number">29.1.2.2</span> Statistical Significance</h4>
<p>If we wish to know whether the mean of the differences differs from the population mean to a statistically significant extent, we can compare our <em>t</em>-value value to a table of critical values of a <em>t</em>-distribution. If our calculated value is larger than the critical value given the number of degrees of freedom (<em>df</em> = <em>n</em> - 2) and the desired alpha level (i.e., significance level, <em>p</em>-value threshold), we would conclude that there is evidence that the mean of the differences differs to a statistically significant extent from the population mean (e.g., zero). Alternatively, we can calculate the exact <em>p</em>-value if we know the <em>t</em>-value and the degrees of freedom. Fortunately, modern statistical software calculates the <em>t</em>-value, degrees of freedom, and <em>p</em>-value for us.</p>
<p>Using null hypothesis significance testing (NHST), we interpret a <em>p</em>-value that is <em>less than .05</em> (or whatever two- or one-tailed alpha level we set) to meet the standard for statistical significance, meaning that we reject the null hypothesis that the mean of the differences between the two sets of dependent scores is equal to the population mean; as noted above, in the training evaluation context, the population mean is often set to zero. In other words, if the <em>p</em>-value is less than .05, we conclude that the mean of the differences differs from zero to a statistically significant extent. In contrast, if the <em>p</em>-value is <em>equal to or greater than .05</em>, then we fail to reject the null hypothesis that the mean of the differences is equal to zero. Put differently, if the <em>p</em>-value is equal to or greater than .05, we conclude that the mean of the differences does <em>not</em> differ from zero to a statistically significant extent, leading us to conclude that there is no change/difference between the two sets of dependent scores in the population.</p>
<p>When setting an alpha threshold, such as the conventional two-tailed .05 level, sometimes the question comes up regarding whether borderline <em>p</em>-values signify significance or nonsignificance. For our purposes, let’s be very strict in our application of the chosen alpha level. For example, if we set our alpha level at .05, <em>p</em> = .049 would be considered statistically significant, and <em>p</em> = .050 would be considered statistically nonsignificant.</p>
<p>Because our paired-samples <em>t</em>-test is estimated using data from a sample drawn from an underlying population, sampling error will affect the extent to which our sample is representative of the population from which its drawn. That is, the observed mean of the differences is a <em>point estimate</em> of the population parameter and is subject to sampling error. Fortunately, confidence intervals can give us a better idea of what the true population parameter value might be. If we apply an alpha level of .05 (two-tailed), then the equivalent confidence interval (CI) is a 95% CI. In terms of whether the difference between two means is is statistically significant, if the lower and upper limits of 95% CI do <em>not</em> include zero, then this tells us the same thing as a <em>p</em>-value that is less than .05. Strictly speaking, a 95% CI indicates that if we were to hypothetically draw many more samples from the underlying populations and construct CIs for each of those samples, then the true parameter (i.e., true value of the mean of the differences in the population) would likely fall within the lower and upper bounds of 95% of the estimated CIs. In other words, the 95% CI gives us an indication of plausible values for the population parameter while taking into consideration sampling error. A wide CI (i.e., large difference between the lower and upper limits) signifies more sampling error, and a narrow CI signifies less sampling error.</p>
</div>
<div id="practicalsignficance_psttest" class="section level4" number="29.1.2.3">
<h4><span class="header-section-number">29.1.2.3</span> Practical Significance</h4>
<p>A significant paired-samples <em>t</em>-test and associated <em>p</em>-value only tells us that the mean of the differences is statistically different from zero. It does not, however, tell us about the magnitude of the mean of the differences – or in other words, the practical significance. The standardized mean difference score (Cohen’s <em>d</em>) is an effect size, which means that it is a standardized metric that can be used to compare <em>d</em>-values compare samples. In essence, the Cohen’s <em>d</em> indicates the magnitude of the mean of the differences in standard deviation units. A <em>d</em>-value of .00 would indicate that the mean of the differences is equal to zero, while the following are some generally accepted qualitative-magnitude labels we can attach to the absolute value of <em>d</em>.</p>
<table>
<thead>
<tr class="header">
<th>Cohen’s <em>d</em></th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.20</td>
<td>Small</td>
</tr>
<tr class="even">
<td>.50</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td>.80</td>
<td>Large</td>
</tr>
</tbody>
</table>
<p>Here is the formula for computing <em>d</em>:</p>
<p><span class="math inline">\(d = \frac{\overline{X}_D} {s_D}\)</span></p>
<p>where <span class="math inline">\(\overline{X}_D\)</span> is the mean of the differences between the two sets of dependent scores, and <span class="math inline">\(s_D\)</span> is the standard deviation of the differences between the dependent scores.</p>
</div>
<div id="samplewriteup_psttest" class="section level4" number="29.1.2.4">
<h4><span class="header-section-number">29.1.2.4</span> Sample Write-Up</h4>
<p><strong>Example 1:</strong> The same employees are assessed on the exact same test before and after completing the same training program; in other words, the employees took part of a pre-test/post-test without control group training evaluation design. Because each participant has two scores on the same test (corresponding to the pre-test and post-test), a paired-samples <em>t</em>-test is an appropriate inferential statistical analysis for determining whether the mean of the differences between the sets of pre-test and post-test scores differs from zero, assuming the aforementioned statistical assumptions have been satisfied. More specifically, a paired-samples <em>t</em>-test was used to determine whether there were significant changes within participants in terms of their average test scores from before participating in the training program to after participating. The mean of the differences (i.e., before-training scores subtracted from after-training scores) for 25 participants was 19.64 (<em>SD</em> = 11.60), and possible test scores could range from 1 to 100 points. Further, the paired-samples <em>t</em>-test indicated that this mean of the differences is significantly greater than zero (<em>t</em> = 8.47, <em>p</em> &lt; .01, 95% CI[14.85, 24.43]) and is large in magnitude (<em>d</em> = 1.69).</p>
<p><strong>Example 2:</strong> A single sample of 30 employees was asked to rate their pay satisfaction and their supervisor satisfaction. Here, the same employees rated their satisfaction with two different targets: pay and supervisor. Because the same employees rated two different ratings targets, we can classify it as a repeated-measures design, which is amenable to a paired-samples <em>t</em>-test. A paired-samples <em>t</em>-test is used to determine whether there the mean of the differences between employees pay satisfaction and supervisor satisfaction differed from zero. We found that the mean of the differences (<em>M</em> = 2.70, <em>SD</em> = 13.20) did not differ significantly from zero (<em>t</em> = 1.12, <em>p</em> = .27, 95% CI[-2.23, 7.62]) based on this sample of 30 employees. Because we did not find evidence of statistical significance, we assume that, statistically, the mean of the differences does not differ from zero, and thus we will not interpret the level of practical significance (i.e., effect size).</p>
</div>
</div>
</div>
<div id="tutorial_psttest" class="section level2" number="29.2">
<h2><span class="header-section-number">29.2</span> Tutorial</h2>
<p>This chapter’s tutorial demonstrates how to estimate a paired-samples <em>t</em>-test, test the associated statistical assumptions, and present the findings in writing and visually.</p>
<div id="videotutorial_psttest" class="section level3" number="29.2.1">
<h3><span class="header-section-number">29.2.1</span> Video Tutorial</h3>
<p>As usual, you have the choice to follow along with the written tutorial in this chapter or to watch the video tutorial below.</p>
<iframe src="https://youtube.com/embed/ZMc9IBFdGsw?rel=0" width="672" height="400px">
</iframe>
<p>Link to video tutorial: <a href="https://youtu.be/ZMc9IBFdGsw" class="uri">https://youtu.be/ZMc9IBFdGsw</a></p>
</div>
<div id="functions_psttest" class="section level3" number="29.2.2">
<h3><span class="header-section-number">29.2.2</span> Functions &amp; Packages Introduced</h3>
<table>
<thead>
<tr class="header">
<th>Function</th>
<th>Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>ttest</code></td>
<td><code>lessR</code></td>
</tr>
<tr class="even">
<td><code>c</code></td>
<td>base R</td>
</tr>
<tr class="odd">
<td><code>mean</code></td>
<td>base R</td>
</tr>
<tr class="even">
<td><code>data.frame</code></td>
<td>base R</td>
</tr>
<tr class="odd">
<td><code>remove</code></td>
<td>base R</td>
</tr>
<tr class="even">
<td><code>BarChart</code></td>
<td><code>lessR</code></td>
</tr>
<tr class="odd">
<td><code>pivot_longer</code></td>
<td><code>tidyr</code></td>
</tr>
<tr class="even">
<td><code>factor</code></td>
<td>base R</td>
</tr>
</tbody>
</table>
</div>
<div id="initsteps_psttest" class="section level3" number="29.2.3">
<h3><span class="header-section-number">29.2.3</span> Initial Steps</h3>
<p>If you haven’t already, save the file called <strong>“TrainingEvaluation_PrePostOnly.csv”</strong> into a folder that you will subsequently set as your working directory. Your working directory will likely be different than the one shown below (i.e., <code>"H:/RWorkshop"</code>). As a reminder, you can access all of the data files referenced in this book by downloading them as a compressed (zipped) folder from the my GitHub site: <a href="https://github.com/davidcaughlin/R-Tutorial-Data-Files" class="uri">https://github.com/davidcaughlin/R-Tutorial-Data-Files</a>; once you’ve followed the link to GitHub, just click “Code” (or “Download”) followed by “Download ZIP”, which will download all of the data files referenced in this book. For the sake of parsimony, I recommend downloading all of the data files into the same folder on your computer, which will allow you to set that same folder as your working directory for each of the chapters in this book.</p>
<p>Next, using the <code>setwd</code> function, set your working directory to the folder in which you saved the data file for this chapter. Alternatively, you can manually set your working directory folder in your drop-down menus by going to <em>Session &gt; Set Working Directory &gt; Choose Directory…</em>. Be sure to create a new R script file (.R) or update an existing R script file so that you can save your script and annotations. If you need refreshers on how to set your working directory and how to create and save an R script, please refer to <a href="setwd.html#setwd">Setting a Working Directory</a> and <a href="gettingstarted.html#createRscript">Creating &amp; Saving an R Script</a>.</p>
<div class="sourceCode" id="cb825"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb825-1"><a href="pretestposttest.html#cb825-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your working directory</span></span>
<span id="cb825-2"><a href="pretestposttest.html#cb825-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;H:/RWorkshop&quot;</span>)</span></code></pre></div>
<p>Next, read in the .csv data file called <strong>“TrainingEvaluation_PrePostOnly.csv”</strong> using your choice of read function. In this example, I use the <code>read_csv</code> function from the <code>readr</code> package <span class="citation">(<a href="references.html#ref-R-readr" role="doc-biblioref">Wickham and Hester 2020</a>)</span>. If you choose to use the <code>read_csv</code> function, be sure that you have installed and accessed the <code>readr</code> package using the <code>install.packages</code> and <code>library</code> functions. <em>Note: You don’t need to install a package every time you wish to access it; in general, I would recommend updating a package installation once ever 1-3 months.</em> For refreshers on installing packages and reading data into R, please refer to <a href="gentleintro.html#packages">Packages</a> and <a href="read.html#read">Reading Data into R</a>.</p>
<div class="sourceCode" id="cb826"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb826-1"><a href="pretestposttest.html#cb826-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install readr package if you haven&#39;t already</span></span>
<span id="cb826-2"><a href="pretestposttest.html#cb826-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Note: You don&#39;t need to install a package every </span></span>
<span id="cb826-3"><a href="pretestposttest.html#cb826-3" aria-hidden="true" tabindex="-1"></a><span class="co"># time you wish to access it]</span></span>
<span id="cb826-4"><a href="pretestposttest.html#cb826-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;readr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb827"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb827-1"><a href="pretestposttest.html#cb827-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access readr package</span></span>
<span id="cb827-2"><a href="pretestposttest.html#cb827-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb827-3"><a href="pretestposttest.html#cb827-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb827-4"><a href="pretestposttest.html#cb827-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data and name data frame (tibble) object</span></span>
<span id="cb827-5"><a href="pretestposttest.html#cb827-5" aria-hidden="true" tabindex="-1"></a>td <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;TrainingEvaluation_PrePostOnly.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification ----------------------------------------------------------------------------------------------------
## cols(
##   EmpID = col_double(),
##   PreTest = col_double(),
##   PostTest = col_double()
## )</code></pre>
<div class="sourceCode" id="cb829"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb829-1"><a href="pretestposttest.html#cb829-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the names of the variables in the data frame (tibble) objects</span></span>
<span id="cb829-2"><a href="pretestposttest.html#cb829-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(td)</span></code></pre></div>
<pre><code>## [1] &quot;EmpID&quot;    &quot;PreTest&quot;  &quot;PostTest&quot;</code></pre>
<div class="sourceCode" id="cb831"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb831-1"><a href="pretestposttest.html#cb831-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View variable type for each variable in data frame</span></span>
<span id="cb831-2"><a href="pretestposttest.html#cb831-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(td)</span></code></pre></div>
<pre><code>## spec_tbl_df[,3] [25 x 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ EmpID   : num [1:25] 26 27 28 29 30 31 32 33 34 35 ...
##  $ PreTest : num [1:25] 43 58 52 47 43 50 66 48 49 49 ...
##  $ PostTest: num [1:25] 66 74 62 84 78 73 60 61 71 83 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   EmpID = col_double(),
##   ..   PreTest = col_double(),
##   ..   PostTest = col_double()
##   .. )</code></pre>
<div class="sourceCode" id="cb833"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb833-1"><a href="pretestposttest.html#cb833-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View first 6 rows of data frame</span></span>
<span id="cb833-2"><a href="pretestposttest.html#cb833-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(td)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   EmpID PreTest PostTest
##   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
## 1    26      43       66
## 2    27      58       74
## 3    28      52       62
## 4    29      47       84
## 5    30      43       78
## 6    31      50       73</code></pre>
<p>There are 25 cases (i.e., employees) and 3 variables in the <code>td</code> data frame: <code>EmpID</code> (unique identifier for employees), <code>PreTest</code> (pre-training scores on training assessment, ranging from 1-100, where higher scores indicate higher performance), and <code>PostTest</code> (post-training scores on training assessment, ranging from 1-100, where higher scores indicate higher performance).</p>
</div>
<div id="estimate_psttest" class="section level3" number="29.2.4">
<h3><span class="header-section-number">29.2.4</span> Estimate Paired-Samples <em>t</em>-test</h3>
<p>In this chapter, we will review how to estimate a paired-samples <em>t</em>-test using the <code>ttest</code> function from the <code>lessR</code> package. Using this function, we will evaluate whether the mean of the differences between the pre-test (<code>PreTest</code>) and post-test (<code>PostTest</code>) outcome variables differs significantly from zero. In other words, let’s find out if assessment scores increased, stayed the same, or decreased from before to after the employees participated in training.</p>
<p>Prior to running the paired-samples <em>t</em>-test, we’ll have to assume (because we don’t have access to information that would indicate otherwise) that the data meet the statistical assumption that the difference scores based on the two outcome measures (e.g., pre-test, post-test) are independent of each other (i.e., randomly sampled from the underlying population).</p>
<p>To access and use the <code>ttest</code> function, we need to install and/or access the <code>lessR</code> package. If you haven’t already, be sure to install the <code>lessR</code> package; if you’ve recently installed the package, then you likely don’t need to install it in this session, and you can skip that step to save time. You <em>will</em> need to run the <code>library</code> function to access the package (assuming it’s been installed), so don’t forget that important step.</p>
<div class="sourceCode" id="cb835"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb835-1"><a href="pretestposttest.html#cb835-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install lessR package</span></span>
<span id="cb835-2"><a href="pretestposttest.html#cb835-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;lessR&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb836"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb836-1"><a href="pretestposttest.html#cb836-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access lessR package and its functions</span></span>
<span id="cb836-2"><a href="pretestposttest.html#cb836-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lessR)</span></code></pre></div>
<p>Please note that when you use the <code>library</code> function to access the <code>lessR</code> package in a new <code>R</code> or <code>RStudio</code> session, you will likely receive a message in red font in your Console. Typically, red font in your Console is not a good sign; however, accessing the <code>lessR</code> package is one of the unique situations in which a red-font message is not a warning or error message. You may also receive a warning message that indicates that certain “objects are masked.” For our purposes, we can ignore that message.</p>
<p>The <code>ttest</code> function from the <code>lessR</code> package makes running a paired-samples <em>t</em>-test relatively straightforward, as wrapped up in the function are tests of the second statistical assumption (see <a href="pretestposttest.html#statisticalassumptions_psttest">Statistical Assumptions section</a>).</p>
<p>Now we’re ready to run a paired-samples <em>t</em>-test. To begin, type the name of the <code>ttest</code> function. As the first argument in the parentheses, specify the name of the first outcome variable (<code>PreTest</code>). As the second argument, specify the name of the second outcome variable (<code>PostTest</code>). Difference scores will be calculated as part of the function by subtracting the variable in the first argument from the variable in the second argument. For the third argument, use <code>data=</code> to specify the name of the data frame (<code>td</code>) where the outcome and predictor variables are located. For the fourth argument, enter <code>paired=TRUE</code> to inform <code>R</code> that the data are paired and, thus, you are requesting a paired-samples <em>t</em>-test.</p>
<div class="sourceCode" id="cb837"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb837-1"><a href="pretestposttest.html#cb837-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paired-samples t-test using ttest function from lessR</span></span>
<span id="cb837-2"><a href="pretestposttest.html#cb837-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ttest</span>(PreTest, PostTest, <span class="at">data=</span>td, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## 
## ------ Description ------
## 
## Difference:  n.miss = 0,  n = 25,   mean = 19.640,  sd = 11.597
## 
## 
## ------ Normality Assumption ------
## 
## Null hypothesis is a normal distribution of Difference.
## Shapiro-Wilk normality test:  W = 0.9687,  p-value = 0.6134
## 
## 
## ------ Inference ------
## 
## t-cutoff for 95% range of variation: tcut =  2.064 
## Standard Error of Mean: SE =  2.319 
## 
## Hypothesized Value H0: mu = 0 
## Hypothesis Test of Mean:  t-value = 8.468,  df = 24,  p-value = 0.000
## 
## Margin of Error for 95% Confidence Level:  4.787
## 95% Confidence Interval for Mean:  14.853 to 24.427
## 
## 
## ------ Effect Size ------
## 
## Distance of sample mean from hypothesized:  19.640
## Standardized Distance, Cohen&#39;s d:  1.694
## 
## 
## ------ Graphics Smoothing Parameter ------
## 
## Density bandwidth for 6.941
## --------------------------------------------------</code></pre>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-488-1.png" width="672" /><img src="R-for-HR_files/figure-html/unnamed-chunk-488-2.png" width="672" /></p>
<p>As you can see in the output, the <code>ttest</code> function provides descriptive statistics, assumption tests regarding the distribution of the difference scores, a statistical significance test of the mean comparison, and an indicator of practical significance in the form of the standardized mean difference (Cohen’s <em>d</em>). In addition, the default lollipop data visualization depicts the distance from the <code>PreTest</code> score to the <code>PostTest</code> score for each case, and the default density distribution depicts the shape of the difference-score distribution, and the extent to which the mean of this distribution appears (visually) to differ from zero.</p>
<p><strong>Description</strong>: The <em>Description</em> section includes basic descriptive statistics about the sample. In the output, we can see that that there are 25 employees (<em>n</em> = 25), and descriptively, the mean of the differences (<code>PostTest</code> minus <code>PreTest</code>) is 19.64 (<em>SD</em> = 11.60), which indicates that, on average, scores increased from before to after training (although we will not know if this difference is statistically significant until we get to the <em>Inference</em> section of the output).</p>
<p><strong>Normality Assumption:</strong> If the sample size is small enough, the <strong>Shapiro-Wilk normality test</strong> is used to test the null hypothesis that the distribution of the difference scores is normal; as such, if the <code>p</code>-values associated with the test statistic (<em>W</em>) is less than the conventional alpha level of .05, then we would <em>reject</em> the null hypothesis and assume that the distribution is <em>not</em> normal. If, however, we <em>fail to reject</em> the null hypothesis, then we don’t have statistical evidence that the distribution is anything other than normal; in other words, if the <em>p</em>-value is equal to or greater than our alpha level (.05), then we can assume the variable is likely normally distributed. In the output, we can see that the difference is normally distributed (<em>W</em> = .969, <em>p</em> = .613).</p>
<p><strong>Inference:</strong> In the <em>Inference</em> section of the output, you will find the statistical test of the null hypothesis (e.g., mean of the differences is equal to zero). First, take a look at the line prefaced with <em>Hypothesis Test of Mean</em>, as this line contains the results of the paired-samples <em>t</em>-test (<em>t</em> = 8.468, <em>p</em> &lt; .001). Because the <em>p</em>-value is less than our conventional two-tailed alpha cutoff of .05, we reject the null hypothesis and conclude that the mean of the differences differs from zero to a statistically significant extent. But in what direction? To answer this question, we need to look back to the <em>Description</em> section; in that section, the mean of the differences (<code>PostTest</code> minus <code>PreTest</code>) is 19.64; as such, we can conclude the following: On average, employees’ performed’ performance on the assessment increased after completing training (<em>M</em> = 19.64, <em>SD</em> = 11.60, <em>t</em> = 8.468, <em>p</em> &lt; .001). Regarding the 95% confidence interval, we can conclude that the true mean of the differences in the population is likely between 14.85 and 24.43 (on a 1-100 point assessment).</p>
<p><strong>Effect Size:</strong> In the <em>Effect Size</em> section, the standardized mean difference (Cohen’s <em>d</em>) is provided as an indicator of practical significance. In the output, <em>d</em> is equal to 1.69, which is considered to be a (very) large effect, according to conventional rules-of-thumb (see table below). <em>Please note that typically we only interpret practical significance when the mean of the differences has been found to be statistically significant.</em></p>
<table>
<thead>
<tr class="header">
<th>Cohen’s <em>d</em></th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.20</td>
<td>Small</td>
</tr>
<tr class="even">
<td>.50</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td>.80</td>
<td>Large</td>
</tr>
</tbody>
</table>
<p><strong>Sample Write-Up:</strong> In total, 25 employees participated in the new training program, which was evaluated using a pre-test/post-test without control group training evaluation design. Employees completed an assessment of their knowledge before training and after training, where assessment scores could range from 1-100. On average, employees’ performance on the assessment increased to a statistically significant extent from before to after completing the training (<em>M</em> = 19.64, <em>SD</em> = 11.60, <em>t</em> = 8.468, <em>p</em> &lt; .001, 95% CI[14.85, 24.43]). This improvement can be considered very large (<em>d</em> = 1.69).</p>
</div>
<div id="barchart_psttest" class="section level3" number="29.2.5">
<h3><span class="header-section-number">29.2.5</span> Visualize Results Using Bar Chart</h3>
<p>When we find a statistically significant difference between the mean of the differences, we may decide to create a bar chart in which the mean of the first outcome variable (<code>PreTest</code>) and the mean of the second outcome variable (<code>PostTest</code>) are displayed as separate bars. We will use the <code>BarChart</code> function from <code>lessR</code> to do so. Before doing so, however, we must prep (i.e., restructure, manipulate) the data to meet the needs of the <code>BarChart</code> function. I will show you two approaches for prepping the data. The first approach requires the installation of the <code>tidyr</code> package (from the <code>tidyverse</code> universe of packages), and the second uses only functions from base <code>R</code>. In my opinion, the logic needed to apply the first approach is more straightforward; however, if you don’t find that to be the case, then by all means try out the second approach.</p>
<div id="barchart_psttest_firstapproach" class="section level4" number="29.2.5.1">
<h4><span class="header-section-number">29.2.5.1</span> First Approach</h4>
<p>For the first approach to prepping the data and generating a bar chart, we will use the <code>pivot_longer</code> function from the <code>tidyr</code> package, which means that we need to install and/or access the <code>tidyr</code> package. If you’d like additional information on the restructuring data frames using the <code>pivot_longer</code> function, please check out the <a href="manipulate.html#manipulate">chapter on manipulating and restructuring data</a>.</p>
<p>If you haven’t already, be sure to install the <code>lessR</code> package; if you’ve recently installed the package, then you likely don’t need to install it in this session, and you can skip that step to save time. You <em>will</em> need to run the <code>library</code> function to access the package (assuming it’s been installed), so don’t forget that important step. <em>[Note: If you run into any installation errors, try installing and access the <code>tidyverse</code> “grand” package, which subsumes the <code>tidyr</code> package, along with many others.]</em></p>
<div class="sourceCode" id="cb839"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb839-1"><a href="pretestposttest.html#cb839-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install tidyr package</span></span>
<span id="cb839-2"><a href="pretestposttest.html#cb839-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;tidyr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb840"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb840-1"><a href="pretestposttest.html#cb840-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access tidyr package and its functions</span></span>
<span id="cb840-2"><a href="pretestposttest.html#cb840-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span></code></pre></div>
<p>Next, let’s use the <code>pivot_longer</code> function from the <code>tidyr</code> package to “pivot” (i.e., manipulate, restructure) our data into “long format”, where “long format” is sometimes referred to as “stacked format”.</p>
<ol style="list-style-type: decimal">
<li>As the first step, create a unique name for an object that we can subsequently assign the manipulated data frame object to. Here, I call the new data frame object <code>td_long</code> to indicate that the new data frame object is in long format.</li>
<li>Insert the <code>&lt;-</code>operator to the right of the new data frame object name. This operator will assign the manipulated data frame object to the new object we’ve named.</li>
<li>Type the name of the <code>pivot_longer</code> function.
<ul>
<li>As the first argument, type <code>data=</code> followed by the exact name of the original data frame object we were working with (<code>td</code>). This will tell the function which data frame object we wish to manipulate.</li>
<li>As the second argument, type the <code>cols=</code> argument to specify a vector of two or more variables we wish to pivot from wide format (i.e., separate columns) to long format (i.e., a single column). Our goal here is to “stack” the <code>PreTest</code> and <code>PostTest</code> variable names as categories (i.e., levels) within a new variable that we will subsequently create. Thus, we will type the name of the <code>c</code> (combine) function from base <code>R</code>, and as the two arguments, we will list the names of the <code>PreTest</code> and <code>PostTest</code> variables.</li>
<li>As the third argument, type the <code>names_to=</code> argument followed by the name of the new “stacked” variable with categorical labels that we’d like to create; make sure the name of the new variable is within quotation marks (<code>" "</code>). This is the variable that will contain the categories (i.e., levels) that were the <code>PreTest</code> and <code>PostTest</code> variable names from the original <code>td</code> data frame object. Here, I name this new variable <code>"Test"</code>.</li>
<li>As the fourth argument, type the <code>values_to=</code> argument followed by the name of a new variable containing the test scores that were originally nested within the <code>PreTest</code> and <code>PostTest</code> variable names from the original <code>td</code> data frame object; make sure the name of the new variable is within quotation marks (<code>" "</code>). Here, I name this new variable <code>"Score"</code>.</li>
</ul></li>
</ol>
<div class="sourceCode" id="cb841"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb841-1"><a href="pretestposttest.html#cb841-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Manipulate data from wide to long format (i.e., stack)</span></span>
<span id="cb841-2"><a href="pretestposttest.html#cb841-2" aria-hidden="true" tabindex="-1"></a>td_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(<span class="at">data=</span>td,</span>
<span id="cb841-3"><a href="pretestposttest.html#cb841-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">cols=</span><span class="fu">c</span>(PreTest,PostTest), </span>
<span id="cb841-4"><a href="pretestposttest.html#cb841-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">names_to=</span><span class="st">&quot;Test&quot;</span>, </span>
<span id="cb841-5"><a href="pretestposttest.html#cb841-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">values_to=</span><span class="st">&quot;Score&quot;</span>)</span></code></pre></div>
<p>Let’s take a peek at our new <code>td_long</code> data frame object by using the <code>Print</code> function.</p>
<div class="sourceCode" id="cb842"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb842-1"><a href="pretestposttest.html#cb842-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print new data frame object to Console</span></span>
<span id="cb842-2"><a href="pretestposttest.html#cb842-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(td_long)</span></code></pre></div>
<pre><code>## # A tibble: 50 x 3
##    EmpID Test     Score
##    &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;
##  1    26 PreTest     43
##  2    26 PostTest    66
##  3    27 PreTest     58
##  4    27 PostTest    74
##  5    28 PreTest     52
##  6    28 PostTest    62
##  7    29 PreTest     47
##  8    29 PostTest    84
##  9    30 PreTest     43
## 10    30 PostTest    78
## # ... with 40 more rows</code></pre>
<p>As you can see, each observation (i.e., employee) now has two rows of data (as opposed to one), such that they have a row for <code>PreTest</code> scores and <code>PostTest</code> scores. These data are now in long (i.e., stacked) format.</p>
<p>By default, the <code>PreTest</code> and <code>PostTest</code> levels of the <code>Test</code> variable we created will be in alphabetical order, such that <code>PostTest</code> will come before <code>PreTest</code> if we created any data visualizations or go to analyze the data from this variable. Intuitively, this is not the order we want, as temporally <code>PreTest</code> should precede (i.e., come before) <code>PostTest</code>. Fortunately, we can use the <code>factor</code> function from base <code>R</code> to convert the <code>Test</code> variable to an ordered factor.</p>
<ol style="list-style-type: decimal">
<li>Let’s overwrite the existing <code>Test</code> variable from the <code>td_long</code> data frame object by typing the name of the data frame object (<code>td_long</code>) followed by the <code>$</code> operator and the name of the variable (<code>Test</code>).</li>
<li>To the right of <code>td_long$Test</code>, type the <code>&lt;-</code> operator so that we can assign the new ordered factored variable to the existing variable called <code>Test</code> from the <code>td_long</code> data frame object.</li>
<li>To the right of the <code>&lt;-</code> operator, type the name of the <code>factor</code> function.
<ul>
<li>As the first argument, type the name of the data frame object (<code>td_long</code>) followed by the <code>$</code> operator and the name of the variable (<code>Test</code>).</li>
<li>As the second argument, type <code>ordered=TRUE</code> to signify that this variable will have ordered levels.</li>
<li>As the third argument, type <code>levels=</code> followed by a vector of the variable levels (i.e., categories) in ascending order. Note that we use the <code>c</code> (combine) function from base <code>R</code> to construct the vector, and we need to put each level within quotation marks (<code>" "</code>). Here, we wish to order the levels such that <code>PreTest</code> comes before <code>PostTest</code>, so we insert the following: <code>c("PreTest","PostTest")</code>.</li>
</ul></li>
</ol>
<div class="sourceCode" id="cb844"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb844-1"><a href="pretestposttest.html#cb844-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-order the Test variable so that PreTest comes first</span></span>
<span id="cb844-2"><a href="pretestposttest.html#cb844-2" aria-hidden="true" tabindex="-1"></a>td_long<span class="sc">$</span>Test <span class="ot">&lt;-</span> <span class="fu">factor</span>(td_long<span class="sc">$</span>Test,</span>
<span id="cb844-3"><a href="pretestposttest.html#cb844-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">ordered=</span><span class="cn">TRUE</span>,</span>
<span id="cb844-4"><a href="pretestposttest.html#cb844-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;PreTest&quot;</span>,<span class="st">&quot;PostTest&quot;</span>))</span></code></pre></div>
<p>We are now ready to create our bar chart of the average scores on the pre-test and the post-test from our pre-test/post-test without control group evaluation design.</p>
<ol style="list-style-type: decimal">
<li>Begin by typing the name of the <code>BarChart</code> function from the <code>lessR</code> package; if you haven’t already, be sure that you have recently installed the <code>lessR</code> package and that you have accessed the package in your current R session. See above for more details on how to install and access the <code>lessR</code> package.</li>
<li>As the first argument, type <code>x=</code> followed by the name of the categorical (i.e., nominal, ordinal) variable that contains the names of the different test times. In this example, the name of the variable is <code>Test</code>, and it contains the levels (i.e., categories) <code>PreTest</code> and <code>PostTest</code>.</li>
<li>As the second argument, type <code>y=</code> followed by the name of the variable that contains the scores for the different test administration times. In this example, the name of the variable is <code>Score</code>, and it contains the numeric scores on the <code>PreTest</code> and <code>PostTest</code> for each employee (i.e., observation).</li>
<li>As the third argument, type <code>data=</code> followed by the exact name of the data frame object to which the variables specified in the two previous arguments belong. In this example, the name of the data frame object is <code>td_long</code>.</li>
<li>As the fourth argument, type <code>stat="mean"</code> to indicate that we wish for the <code>BarChart</code> function to compute the average (i.e., mean) score from the <code>Score</code> variable for each level of the <code>Test</code> variable.</li>
</ol>
<div class="sourceCode" id="cb845"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb845-1"><a href="pretestposttest.html#cb845-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create bar chart</span></span>
<span id="cb845-2"><a href="pretestposttest.html#cb845-2" aria-hidden="true" tabindex="-1"></a><span class="fu">BarChart</span>(<span class="at">x=</span>Test, <span class="at">y=</span>Score, <span class="at">data=</span>td_long, <span class="at">stat=</span><span class="st">&quot;mean&quot;</span>)</span></code></pre></div>
<pre><code>## Score 
##   - by levels of - 
## Test 
##  
##             n   miss     mean       sd      min      mdn      max 
## PreTest    25      0    52.72     7.05    43.00    51.00    66.00 
## PostTest   25      0    72.36     6.98    60.00    73.00    84.00</code></pre>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-494-1.png" width="672" /></p>
<pre><code>## &gt;&gt;&gt; Suggestions
## Plot(Score, Test) # lollipop plot 
## 
## 
##  Data for:  Score 
##  ---------------- 
##   PreTest  PostTest 
##     52.72     72.36</code></pre>
<p>If you wish, you can then add additional arguments like <code>xlab=</code> and <code>ylab=</code> to re-label the x- and y-axes, respectively.</p>
<div class="sourceCode" id="cb848"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb848-1"><a href="pretestposttest.html#cb848-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create bar chart</span></span>
<span id="cb848-2"><a href="pretestposttest.html#cb848-2" aria-hidden="true" tabindex="-1"></a><span class="fu">BarChart</span>(<span class="at">x=</span>Test, <span class="at">y=</span>Score, <span class="at">data=</span>td_long, <span class="at">stat=</span><span class="st">&quot;mean&quot;</span>,</span>
<span id="cb848-3"><a href="pretestposttest.html#cb848-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab=</span><span class="st">&quot;Average Score&quot;</span>,</span>
<span id="cb848-4"><a href="pretestposttest.html#cb848-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab=</span><span class="st">&quot;Time&quot;</span>)</span></code></pre></div>
<pre><code>## Score 
##   - by levels of - 
## Test 
##  
##             n   miss     mean       sd      min      mdn      max 
## PreTest    25      0    52.72     7.05    43.00    51.00    66.00 
## PostTest   25      0    72.36     6.98    60.00    73.00    84.00</code></pre>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-495-1.png" width="672" /></p>
<pre><code>## &gt;&gt;&gt; Suggestions
## Plot(Score, Test) # lollipop plot 
## 
## 
##  Data for:  Score 
##  ---------------- 
##   PreTest  PostTest 
##     52.72     72.36</code></pre>
</div>
<div id="barchart_psttest_secondapproach" class="section level4" number="29.2.5.2">
<h4><span class="header-section-number">29.2.5.2</span> Second Approach</h4>
<p>For the second approach, we will create a data frame of the means and their names so that we can use the data frame as input into the <code>BarChart</code> function.</p>
<ol style="list-style-type: decimal">
<li>Come up with a unique name for a vector of means that we will create; here, I name the vector <code>prepost_means</code>.</li>
<li>Type the <code>&lt;-</code> operator to the right of the vector name (<code>prepost_means</code>) so that we can assign the vector we create to the right of the <code>&lt;-</code> operator to the new object.</li>
<li>Second, type the name of the <code>c</code> function from base R.
<ul>
<li>As the first argument within the <code>c</code> function, type the name of the <code>mean</code> function from base R, and within that function’s parentheses, type the name of the data frame (<code>td</code>), followed by the <code>$</code> symbol and the name of the first outcome variable (<code>PreTest</code>). As the second argument within the <code>mean</code> function, type <code>na.rm=TRUE</code> in case there are missing data.</li>
<li>As the second argument within the <code>c</code> function, type the name of the <code>mean</code> function from base R, and within that function’s parentheses, type the name of the data frame (<code>td</code>), followed by the <code>$</code> symbol and the name of the second outcome variable (<code>PostTest</code>); as the second argument within the <code>mean</code> function, type <code>na.rm=TRUE</code> in case there are missing data.</li>
</ul></li>
</ol>
<div class="sourceCode" id="cb851"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb851-1"><a href="pretestposttest.html#cb851-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create vector of means for first and second outcome variables</span></span>
<span id="cb851-2"><a href="pretestposttest.html#cb851-2" aria-hidden="true" tabindex="-1"></a>prepost_means <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(td<span class="sc">$</span>PreTest, <span class="at">na.rm=</span><span class="cn">TRUE</span>), <span class="fu">mean</span>(td<span class="sc">$</span>PostTest, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code></pre></div>
<p>Now it’s time to create a vector of the names (i.e., variable names) that correspond with the means contained within the vector we just created. First, come up with a name for the vector object that will contain the names; here, I name the vector <code>meannames</code> using the <code>&lt;-</code> operator. Second, type the name of the <code>c</code> function from base R. As the first argument within the function, type what you wish to name the first mean (i.e., variable name for the first value), and put it in quotation marks (<code>"Pre-Test"</code>). As the second argument within the function, type what you wish to name the second mean (i.e., variable name for the second value), and put it in quotation marks (<code>"Post-Test"</code>).</p>
<div class="sourceCode" id="cb852"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb852-1"><a href="pretestposttest.html#cb852-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create vector of names corresponding to the first and second means above</span></span>
<span id="cb852-2"><a href="pretestposttest.html#cb852-2" aria-hidden="true" tabindex="-1"></a>meannames <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Pre-Test&quot;</span>,<span class="st">&quot;Post-Test&quot;</span>)</span></code></pre></div>
<p>To combine these two vectors into a data frame, we will use the <code>data.frame</code> function from base R. First, come up with a name for the data frame object; here, I name the data frame <code>meansdf</code> using the <code>&lt;-</code> naming symbol. Second, type the name of the <code>data.frame</code> function. As the first argument, type the name of <code>meannames</code> vector we created. As the second argument, type the name of the <code>prepost_means</code> vector we created.</p>
<div class="sourceCode" id="cb853"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb853-1"><a href="pretestposttest.html#cb853-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create data frame from the two vectors created above</span></span>
<span id="cb853-2"><a href="pretestposttest.html#cb853-2" aria-hidden="true" tabindex="-1"></a>meansdf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(meannames, prepost_means)</span></code></pre></div>
<p>Remove the vectors called <code>meannames</code> and <code>prepost_means</code> from your <code>R</code> Global environment to avoid any confusion when specifying the <code>BarChart</code> function. Use the <code>remove</code> function from base R to accomplish this.</p>
<div class="sourceCode" id="cb854"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb854-1"><a href="pretestposttest.html#cb854-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the two vectors created above from R Global Environment</span></span>
<span id="cb854-2"><a href="pretestposttest.html#cb854-2" aria-hidden="true" tabindex="-1"></a><span class="fu">remove</span>(prepost_means)</span>
<span id="cb854-3"><a href="pretestposttest.html#cb854-3" aria-hidden="true" tabindex="-1"></a><span class="fu">remove</span>(meannames)</span></code></pre></div>
<p>Now have data in a format that can be used as input in the <code>BarChart</code> function from the <code>lessR</code> package. Begin by typing the name of the <code>BarChart</code> function. As the first argument, type the name of the variable that contains the names of the means (<code>meannames</code>). As the second argument, type the name of the variable that contains the actual means (<code>prepost_means</code>). As the third argument, type <code>data=</code> followed by the name of the data frame to which the aforementioned variables belong (<code>meansdf</code>). As the fourth argument, use <code>xlab=</code> to provide the x-axis label (<code>"Time"</code>). As the fifth argument, use <code>ylab=</code> to provide the y-axis label (<code>"Average Score"</code>).</p>
<div class="sourceCode" id="cb855"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb855-1"><a href="pretestposttest.html#cb855-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create bar chart</span></span>
<span id="cb855-2"><a href="pretestposttest.html#cb855-2" aria-hidden="true" tabindex="-1"></a><span class="fu">BarChart</span>(meannames, prepost_means, <span class="at">data=</span>meansdf, </span>
<span id="cb855-3"><a href="pretestposttest.html#cb855-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab=</span><span class="st">&quot;Time&quot;</span>, </span>
<span id="cb855-4"><a href="pretestposttest.html#cb855-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab=</span><span class="st">&quot;Average Score&quot;</span>)</span></code></pre></div>
<p><img src="R-for-HR_files/figure-html/unnamed-chunk-500-1.png" width="672" /></p>
<pre><code>## &gt;&gt;&gt; Suggestions
## Plot(prepost_means, meannames) # lollipop plot 
## 
## 
##  Data for:  prepost_means 
##  ------------------------ 
##   Pre-Test  Post-Test 
##      52.72      72.36</code></pre>
</div>
</div>
<div id="summary_psttest" class="section level3" number="29.2.6">
<h3><span class="header-section-number">29.2.6</span> Summary</h3>
<p>In this chapter, we learned how to estimate a paired-samples <em>t</em>-test to determine whether the mean of the differences between scores on two dependent variables is significantly different from zero. This analysis is useful when evaluating a pre-test/post-test <em>without</em> control group training design. The <code>ttest</code> function from <code>lessR</code>can be used to run paired-samples <em>t</em>-tests. We also learned how to visualize the results using the <code>BarChart</code> function from <code>lessR</code>.</p>
</div>
</div>
<div id="psttest_supplement" class="section level2" number="29.3">
<h2><span class="header-section-number">29.3</span> Chapter Supplement</h2>
<p>In addition to the <code>ttest</code> function from the <code>lessR</code> package covered <a href="posttestonly.html#estimate_isttest">above</a>, we can use the <code>t.test</code> function from base R to estimate a paired-samples <em>t</em>-test. Because this function comes from base R, we do not need to install and access an additional package.</p>
<div id="psttest_supplement_functions" class="section level3" number="29.3.1">
<h3><span class="header-section-number">29.3.1</span> Functions &amp; Packages Introduced</h3>
<table>
<thead>
<tr class="header">
<th>Function</th>
<th>Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>shapiro.test</code></td>
<td>base R</td>
</tr>
<tr class="even">
<td><code>t.test</code></td>
<td>base R</td>
</tr>
<tr class="odd">
<td><code>cohen.d</code></td>
<td><code>effsize</code></td>
</tr>
<tr class="even">
<td><code>c</code></td>
<td>base R</td>
</tr>
<tr class="odd">
<td><code>mean</code></td>
<td>base R</td>
</tr>
</tbody>
</table>
</div>
<div id="psttest_initsteps_supplement" class="section level3" number="29.3.2">
<h3><span class="header-section-number">29.3.2</span> Initial Steps</h3>
<p>If required, please refer to the <a href="pretestposttest.html#initsteps_psttest">Initial Steps</a> section from this chapter for more information on these initial steps.</p>
<div class="sourceCode" id="cb857"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb857-1"><a href="pretestposttest.html#cb857-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your working directory</span></span>
<span id="cb857-2"><a href="pretestposttest.html#cb857-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;H:/RWorkshop&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb858"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb858-1"><a href="pretestposttest.html#cb858-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install readr package if you haven&#39;t already</span></span>
<span id="cb858-2"><a href="pretestposttest.html#cb858-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Note: You don&#39;t need to install a package every </span></span>
<span id="cb858-3"><a href="pretestposttest.html#cb858-3" aria-hidden="true" tabindex="-1"></a><span class="co"># time you wish to access it]</span></span>
<span id="cb858-4"><a href="pretestposttest.html#cb858-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;readr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb859"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb859-1"><a href="pretestposttest.html#cb859-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access readr package</span></span>
<span id="cb859-2"><a href="pretestposttest.html#cb859-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb859-3"><a href="pretestposttest.html#cb859-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb859-4"><a href="pretestposttest.html#cb859-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data and name data frame (tibble) object</span></span>
<span id="cb859-5"><a href="pretestposttest.html#cb859-5" aria-hidden="true" tabindex="-1"></a>td <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;TrainingEvaluation_PrePostOnly.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification ----------------------------------------------------------------------------------------------------
## cols(
##   EmpID = col_double(),
##   PreTest = col_double(),
##   PostTest = col_double()
## )</code></pre>
<div class="sourceCode" id="cb861"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb861-1"><a href="pretestposttest.html#cb861-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the names of the variables in the data frame (tibble) objects</span></span>
<span id="cb861-2"><a href="pretestposttest.html#cb861-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(td)</span></code></pre></div>
<pre><code>## [1] &quot;EmpID&quot;    &quot;PreTest&quot;  &quot;PostTest&quot;</code></pre>
<div class="sourceCode" id="cb863"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb863-1"><a href="pretestposttest.html#cb863-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View variable type for each variable in data frame</span></span>
<span id="cb863-2"><a href="pretestposttest.html#cb863-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(td)</span></code></pre></div>
<pre><code>## spec_tbl_df[,3] [25 x 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ EmpID   : num [1:25] 26 27 28 29 30 31 32 33 34 35 ...
##  $ PreTest : num [1:25] 43 58 52 47 43 50 66 48 49 49 ...
##  $ PostTest: num [1:25] 66 74 62 84 78 73 60 61 71 83 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   EmpID = col_double(),
##   ..   PreTest = col_double(),
##   ..   PostTest = col_double()
##   .. )</code></pre>
<div class="sourceCode" id="cb865"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb865-1"><a href="pretestposttest.html#cb865-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View first 6 rows of data frame</span></span>
<span id="cb865-2"><a href="pretestposttest.html#cb865-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(td)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   EmpID PreTest PostTest
##   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
## 1    26      43       66
## 2    27      58       74
## 3    28      52       62
## 4    29      47       84
## 5    30      43       78
## 6    31      50       73</code></pre>
</div>
<div id="t.test_function_psttest" class="section level3" number="29.3.3">
<h3><span class="header-section-number">29.3.3</span> <code>t.test</code> Function from Base R</h3>
<p>By itself, the <code>t.test</code> function from base R does not generate statistical assumption tests and and estimates of effect size (practical significance) like the <code>ttest</code> function from <code>lessR</code> does. Thus, we will need to apply additional functions to achieve all of the necessary output.</p>
<p>Before running our paired-samples <em>t</em>-test using the <code>t.test</code> function from base R, we should test the second assumption (see <a href="pretestposttest.html#statisticalassumptions_psttest">Statistical Assumptions</a> section). To do so, we will estimate the <em>Shapiro-Wilk normality test</em>. This test was covered in detail above when we applied the <code>ttest</code> function from <code>lessR</code>, so we will breeze through the interpretation in this section.</p>
<p>To compute the Shapiro-Wilk normality test to test the assumption that the difference scores are normally distributed, we will use the <code>shapiro.test</code> function from base <code>R</code>. First, type the name of the <code>shapiro.test</code> function. As the sole argument, type the name of the data frame (<code>td</code>), followed by the <code>$</code> symbol and the difference between the <code>PostTest</code> scores and <code>PreTest</code> scores: <code>td$PostTest - td$PreTest</code>.</p>
<div class="sourceCode" id="cb867"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb867-1"><a href="pretestposttest.html#cb867-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Shapiro-Wilk normality test for normal distribution</span></span>
<span id="cb867-2"><a href="pretestposttest.html#cb867-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(td<span class="sc">$</span>PostTest <span class="sc">-</span> td<span class="sc">$</span>PreTest)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  td$PostTest - td$PreTest
## W = 0.96874, p-value = 0.6134</code></pre>
<p>The output of the script/code above indicates that the <em>p</em>-value associated with the test is equal to or greater than the conventional alpha of .05; therefore, we <em>fail to reject</em> the null hypothesis that the difference scores are normally distributed. In other words, we have no evidence to suggest that the difference score variable scores are anything other than normally distributed.</p>
<p>With confidence that we met the statistical assumptions for a paired-samples <em>t</em>-test, we are ready to apply the <code>t.test</code> function from base <code>R</code>. To begin, type the name of the <code>t.test</code> function. As the first argument, specify the name of the data frame (<code>td</code>), followed by the <code>$</code> symbol and the name of the <em>second</em> outcome variable (<code>PostTest</code>). As the second argument, specify the name of the data frame (<code>td</code>), followed by the <code>$</code> symbol and the name of the <em>first</em> outcome variable (<code>PreTest</code>). Note that the ordering of the variables is opposite of the <code>ttest</code> function from <code>lessR</code>. Difference scores will be calculated as part of the function by subtracting the variable in the second argument from the variable in the first variable argument. For the third argument, enter <code>paired=TRUE</code> to inform <code>R</code> that the data are paired, which means you are requesting a paired-samples <em>t</em>-test.</p>
<div class="sourceCode" id="cb869"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb869-1"><a href="pretestposttest.html#cb869-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paired-samples t-test using t.test function from base R</span></span>
<span id="cb869-2"><a href="pretestposttest.html#cb869-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(td<span class="sc">$</span>PostTest, td<span class="sc">$</span>PreTest, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  td$PostTest and td$PreTest
## t = 8.4677, df = 24, p-value = 0.00000001138
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  14.853 24.427
## sample estimates:
## mean of the differences 
##                   19.64</code></pre>
<p>Note that the <code>t.test</code> output provides you with the results of the paired-samples <em>t</em>-test in terms of the formal statistical test (<em>t</em> = 8.4677, <em>p</em> &lt; .001), the 95% confidence interval (95% CI[14.853, 24.427]), and the mean of the differences (<em>M</em> = 19.64). The output, however, does <em>not</em> include an estimate of practical significance.</p>
<p>To compute Cohen’s <em>d</em> as an estimate of practical significance we will use the <code>cohen.d</code> function from the <code>effsize</code> package. If you haven’t already, install the <code>effsize</code> package. Make sure to access the package using the <code>library</code> function.</p>
<div class="sourceCode" id="cb871"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb871-1"><a href="pretestposttest.html#cb871-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install package</span></span>
<span id="cb871-2"><a href="pretestposttest.html#cb871-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;effsize&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb872"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb872-1"><a href="pretestposttest.html#cb872-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access package</span></span>
<span id="cb872-2"><a href="pretestposttest.html#cb872-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effsize)</span></code></pre></div>
<p>As the first argument in the <code>cohen.d</code> function, specify the name of the data frame (<code>td</code>), followed by the <code>$</code> symbol and the name of the <em>second</em> outcome variable (<code>PostTest</code>). As the second argument, specify the name of the data frame (<code>td</code>), followed by the <code>$</code> symbol and the name of the <em>first</em> outcome variable (<code>PreTest</code>). As the third argument, type <code>paired=TRUE</code> to indicate that the data are indeed paired (i.e., dependent).</p>
<div class="sourceCode" id="cb873"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb873-1"><a href="pretestposttest.html#cb873-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Cohen&#39;s d</span></span>
<span id="cb873-2"><a href="pretestposttest.html#cb873-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohen.d</span>(td<span class="sc">$</span>PostTest, td<span class="sc">$</span>PreTest, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: 2.800502 (large)
## 95 percent confidence interval:
##    lower    upper 
## 1.325315 4.275689</code></pre>
<p>The output indicates that Cohen’s <em>d</em> is 1.694, which would be considered large by conventional cutoff standards (see table earlier in this tutorial).</p>
<p><strong>Sample Write-Up:</strong> In total, 25 employees participated in the new training program, which was evaluated using a pre-test/post-test without control group training evaluation design. Employees completed an assessment of their knowledge before training and after training, where assessment scores could range from 1-100. On average, employees’ performance on the assessment increased to a statistically significant extent from before to after completing the training (<em>M</em> = 19.64, <em>SD</em> = 11.60, <em>t</em> = 8.468, <em>p</em> &lt; .001, 95% CI[14.85, 24.43]). This improvement can be considered very large (<em>d</em> = 1.69).</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="employeetraining.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="posttestonly.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
