<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 42 Estimating Association Between Two Categorical Variables Using Chi-Square (\(\chi^2\)) Test of Independence | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION</title>
  <meta name="description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 42 Estimating Association Between Two Categorical Variables Using Chi-Square (\(\chi^2\)) Test of Independence | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://rforhr.com" />
  <meta property="og:image" content="https://rforhr.comcover.png" />
  <meta property="og:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="github-repo" content="davidcaughlin/R-for-HR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 42 Estimating Association Between Two Categorical Variables Using Chi-Square (\(\chi^2\)) Test of Independence | R for HR: An Introduction to Human Resource Analytics Using R BOOK UNDER CONSTRUCTION" />
  
  <meta name="twitter:description" content="Human resource (HR) analytics is a growing area of HR manage, and the purpose of this book is to show how the R programming language can be used as tool to manage, analyze, and visualize HR data in order to derive insights and to inform decision making. [NOTE: This book is currently under construction.]" />
  <meta name="twitter:image" content="https://rforhr.comcover.png" />

<meta name="author" content="David E. Caughlin" />


<meta name="date" content="2021-12-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="turnoverrate.html"/>
<link rel="next" href="literature-search-review.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for HR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#hragrowth"><i class="fa fa-check"></i><b>0.1</b> Growth of HR Analytics</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#hranalytics_skillsgap"><i class="fa fa-check"></i><b>0.2</b> Skills Gap</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#hraplc"><i class="fa fa-check"></i><b>0.3</b> Project Life Cycle Perspective</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#hranalytics_hris_overview"><i class="fa fa-check"></i><b>0.4</b> Overview of HRIS &amp; HR Analytics</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#philosophy"><i class="fa fa-check"></i><b>0.5</b> My Philosophy for This Book</a>
<ul>
<li class="chapter" data-level="0.5.1" data-path="index.html"><a href="index.html#rationalerpref"><i class="fa fa-check"></i><b>0.5.1</b> Rationale for Using R</a></li>
<li class="chapter" data-level="0.5.2" data-path="index.html"><a href="index.html#audiencepref"><i class="fa fa-check"></i><b>0.5.2</b> Audience</a></li>
</ul></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#structurepref"><i class="fa fa-check"></i><b>0.6</b> Structure</a></li>
<li class="chapter" data-level="0.7" data-path="index.html"><a href="index.html#aboutauthor"><i class="fa fa-check"></i><b>0.7</b> About the Author</a></li>
<li class="chapter" data-level="0.8" data-path="index.html"><a href="index.html#acknowpref"><i class="fa fa-check"></i><b>0.8</b> Acknowledgements</a></li>
</ul></li>
<li class="part"><span><b>I HR Analytics Project Life Cycle</b></span></li>
<li class="chapter" data-level="1" data-path="overviewhraplc.html"><a href="overviewhraplc.html"><i class="fa fa-check"></i><b>1</b> Overview of HR Analytics Project Life Cycle</a></li>
<li class="chapter" data-level="2" data-path="questionformulation.html"><a href="questionformulation.html"><i class="fa fa-check"></i><b>2</b> Question Formulation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="questionformulation.html"><a href="questionformulation.html#adoptstrategicmindset"><i class="fa fa-check"></i><b>2.1</b> Adopting a Strategic Mindset</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="questionformulation.html"><a href="questionformulation.html#strategy"><i class="fa fa-check"></i><b>2.1.1</b> Strategy</a></li>
<li class="chapter" data-level="2.1.2" data-path="questionformulation.html"><a href="questionformulation.html#strategyformulation"><i class="fa fa-check"></i><b>2.1.2</b> Strategy Formulation</a></li>
<li class="chapter" data-level="2.1.3" data-path="questionformulation.html"><a href="questionformulation.html#strategyimplementation"><i class="fa fa-check"></i><b>2.1.3</b> Strategy Implementation</a></li>
<li class="chapter" data-level="2.1.4" data-path="questionformulation.html"><a href="questionformulation.html#strategichrm"><i class="fa fa-check"></i><b>2.1.4</b> Strategic Human Resource Management</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="questionformulation.html"><a href="questionformulation.html#defining-problems-formulating-questions"><i class="fa fa-check"></i><b>2.2</b> Defining Problems &amp; Formulating Questions</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="questionformulation.html"><a href="questionformulation.html#definingaproblem"><i class="fa fa-check"></i><b>2.2.1</b> Defining a Problem</a></li>
<li class="chapter" data-level="2.2.2" data-path="questionformulation.html"><a href="questionformulation.html#formulatingaquestion"><i class="fa fa-check"></i><b>2.2.2</b> Formulating a Question</a></li>
<li class="chapter" data-level="2.2.3" data-path="questionformulation.html"><a href="questionformulation.html#divergentconvergentthinking"><i class="fa fa-check"></i><b>2.2.3</b> Thinking Divergently &amp; Convergently</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="questionformulation.html"><a href="questionformulation.html#summary"><i class="fa fa-check"></i><b>2.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dataacquisition.html"><a href="dataacquisition.html"><i class="fa fa-check"></i><b>3</b> Data Acquisition</a>
<ul>
<li class="chapter" data-level="3.1" data-path="dataacquisition.html"><a href="dataacquisition.html#employee-surveys"><i class="fa fa-check"></i><b>3.1</b> Employee Surveys</a></li>
<li class="chapter" data-level="3.2" data-path="dataacquisition.html"><a href="dataacquisition.html#rating-forms"><i class="fa fa-check"></i><b>3.2</b> Rating Forms</a></li>
<li class="chapter" data-level="3.3" data-path="dataacquisition.html"><a href="dataacquisition.html#surveillance-monitoring"><i class="fa fa-check"></i><b>3.3</b> Surveillance &amp; Monitoring</a></li>
<li class="chapter" data-level="3.4" data-path="dataacquisition.html"><a href="dataacquisition.html#database-queries"><i class="fa fa-check"></i><b>3.4</b> Database Queries</a></li>
<li class="chapter" data-level="3.5" data-path="dataacquisition.html"><a href="dataacquisition.html#scraping"><i class="fa fa-check"></i><b>3.5</b> Scraping</a></li>
<li class="chapter" data-level="3.6" data-path="dataacquisition.html"><a href="dataacquisition.html#summary-1"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="datamanagement.html"><a href="datamanagement.html"><i class="fa fa-check"></i><b>4</b> Data Management</a>
<ul>
<li class="chapter" data-level="4.1" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_clean"><i class="fa fa-check"></i><b>4.1</b> Data Cleaning</a></li>
<li class="chapter" data-level="4.2" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_manipulate"><i class="fa fa-check"></i><b>4.2</b> Data Manipulation &amp; Structuring</a></li>
<li class="chapter" data-level="4.3" data-path="datamanagement.html"><a href="datamanagement.html#datamanage_tools"><i class="fa fa-check"></i><b>4.3</b> Common Data-Management Tools</a></li>
<li class="chapter" data-level="4.4" data-path="datamanagement.html"><a href="datamanagement.html#summary-2"><i class="fa fa-check"></i><b>4.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dataanalysis.html"><a href="dataanalysis.html"><i class="fa fa-check"></i><b>5</b> Data Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="dataanalysis.html"><a href="dataanalysis.html#dataanalysis_toolstechniques"><i class="fa fa-check"></i><b>5.1</b> Tools &amp; Techniques</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="dataanalysis.html"><a href="dataanalysis.html#mathematics"><i class="fa fa-check"></i><b>5.1.1</b> Mathematics</a></li>
<li class="chapter" data-level="5.1.2" data-path="dataanalysis.html"><a href="dataanalysis.html#statistics"><i class="fa fa-check"></i><b>5.1.2</b> Statistics</a></li>
<li class="chapter" data-level="5.1.3" data-path="dataanalysis.html"><a href="dataanalysis.html#machinelearning"><i class="fa fa-check"></i><b>5.1.3</b> Machine Learning</a></li>
<li class="chapter" data-level="5.1.4" data-path="dataanalysis.html"><a href="dataanalysis.html#computationalmodelsimulation"><i class="fa fa-check"></i><b>5.1.4</b> Computational Modeling &amp; Simulations</a></li>
<li class="chapter" data-level="5.1.5" data-path="dataanalysis.html"><a href="dataanalysis.html#textqualitativeanalyses"><i class="fa fa-check"></i><b>5.1.5</b> Text Analyses &amp; Qualitative Analyses</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="dataanalysis.html"><a href="dataanalysis.html#continuum_dataanalytics"><i class="fa fa-check"></i><b>5.2</b> Continuum of Data Analytics</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="dataanalysis.html"><a href="dataanalysis.html#descriptive_analytics"><i class="fa fa-check"></i><b>5.2.1</b> Descriptive Analytics</a></li>
<li class="chapter" data-level="5.2.2" data-path="dataanalysis.html"><a href="dataanalysis.html#predictish_analytics"><i class="fa fa-check"></i><b>5.2.2</b> Predict-ish Analytics</a></li>
<li class="chapter" data-level="5.2.3" data-path="dataanalysis.html"><a href="dataanalysis.html#predictive_analytics"><i class="fa fa-check"></i><b>5.2.3</b> Predictive Analytics</a></li>
<li class="chapter" data-level="5.2.4" data-path="dataanalysis.html"><a href="dataanalysis.html#prescriptive_analytics"><i class="fa fa-check"></i><b>5.2.4</b> Prescriptive Analytics</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="dataanalysis.html"><a href="dataanalysis.html#summary-3"><i class="fa fa-check"></i><b>5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html"><i class="fa fa-check"></i><b>6</b> Data Interpretation &amp; Storytelling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#datainterpretation"><i class="fa fa-check"></i><b>6.1</b> Data Interpretation</a></li>
<li class="chapter" data-level="6.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling"><i class="fa fa-check"></i><b>6.2</b> Storytelling</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#structure"><i class="fa fa-check"></i><b>6.2.1</b> Structure</a></li>
<li class="chapter" data-level="6.2.2" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#clarity-parsimony"><i class="fa fa-check"></i><b>6.2.2</b> Clarity &amp; Parsimony</a></li>
<li class="chapter" data-level="6.2.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#influence-persuasion"><i class="fa fa-check"></i><b>6.2.3</b> Influence &amp; Persuasion</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#storytelling_withdata"><i class="fa fa-check"></i><b>6.3</b> Storytelling with Data</a></li>
<li class="chapter" data-level="6.4" data-path="datainterpretationstorytelling.html"><a href="datainterpretationstorytelling.html#summary-4"><i class="fa fa-check"></i><b>6.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html"><i class="fa fa-check"></i><b>7</b> Deployment &amp; Implementation</a></li>
<li class="chapter" data-level="" data-path=""><a href="#part-introduction-to-r"><i class="fa fa-check"></i>(PART) Introduction to R</a>
<ul>
<li class="chapter" data-level="7.1" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html#R_overview"><i class="fa fa-check"></i><b>7.1</b> R Programming Language</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html#R_what"><i class="fa fa-check"></i><b>7.1.1</b> What Is R?</a></li>
<li class="chapter" data-level="7.1.2" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html#R_why"><i class="fa fa-check"></i><b>7.1.2</b> Why Use R?</a></li>
<li class="chapter" data-level="7.1.3" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html#R_who"><i class="fa fa-check"></i><b>7.1.3</b> Who Uses R?</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html#RStudio_overview"><i class="fa fa-check"></i><b>7.2</b> RStudio</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html#RStudio_what"><i class="fa fa-check"></i><b>7.2.1</b> What is RStudio?</a></li>
<li class="chapter" data-level="7.2.2" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html#RStudio_why"><i class="fa fa-check"></i><b>7.2.2</b> Why RStudio?</a></li>
<li class="chapter" data-level="7.2.3" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html#RStudio_who"><i class="fa fa-check"></i><b>7.2.3</b> Who Uses RStudio?</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html#packages_overview"><i class="fa fa-check"></i><b>7.3</b> Packages</a></li>
<li class="chapter" data-level="7.4" data-path="deploymentimplementation.html"><a href="deploymentimplementation.html#summary-5"><i class="fa fa-check"></i><b>7.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>8</b> Installing R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="8.1" data-path="install.html"><a href="install.html#videotutorial_install"><i class="fa fa-check"></i><b>8.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="8.2" data-path="install.html"><a href="install.html#installR"><i class="fa fa-check"></i><b>8.2</b> Downloading &amp; Installing R</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="install.html"><a href="install.html#installR_windows"><i class="fa fa-check"></i><b>8.2.1</b> For Windows Operation Systems</a></li>
<li class="chapter" data-level="8.2.2" data-path="install.html"><a href="install.html#installR_macos"><i class="fa fa-check"></i><b>8.2.2</b> For Mac Operating Systems</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="install.html"><a href="install.html#installRStudio"><i class="fa fa-check"></i><b>8.3</b> Downloading &amp; Installing RStudio</a></li>
<li class="chapter" data-level="8.4" data-path="install.html"><a href="install.html#summary_install"><i class="fa fa-check"></i><b>8.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="gettingstarted.html"><a href="gettingstarted.html"><i class="fa fa-check"></i><b>9</b> Getting Started with R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="9.1" data-path="gettingstarted.html"><a href="gettingstarted.html#orientation_gettingstarted"><i class="fa fa-check"></i><b>9.1</b> Orientation to RStudio</a></li>
<li class="chapter" data-level="9.2" data-path="gettingstarted.html"><a href="gettingstarted.html#createRscript"><i class="fa fa-check"></i><b>9.2</b> Creating &amp; Saving an R Script</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="gettingstarted.html"><a href="gettingstarted.html#createnewRscript_gettingstarted"><i class="fa fa-check"></i><b>9.2.1</b> Creating a New R Script</a></li>
<li class="chapter" data-level="9.2.2" data-path="gettingstarted.html"><a href="gettingstarted.html#usenewRscript_gettingstarted"><i class="fa fa-check"></i><b>9.2.2</b> Using an R Script</a></li>
<li class="chapter" data-level="9.2.3" data-path="gettingstarted.html"><a href="gettingstarted.html#saveRscript_gettingstarted"><i class="fa fa-check"></i><b>9.2.3</b> Saving an R Script</a></li>
<li class="chapter" data-level="9.2.4" data-path="gettingstarted.html"><a href="gettingstarted.html#openRscript_gettingstarted"><i class="fa fa-check"></i><b>9.2.4</b> Opening a Saved R Script</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="gettingstarted.html"><a href="gettingstarted.html#RStudioproject_gettingstarted"><i class="fa fa-check"></i><b>9.3</b> Creating an RStudio Project</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="gettingstarted.html"><a href="gettingstarted.html#createRStudioproject_gettingstarted"><i class="fa fa-check"></i><b>9.3.1</b> Creating a New RStudio Project</a></li>
<li class="chapter" data-level="9.3.2" data-path="gettingstarted.html"><a href="gettingstarted.html#openRStudioproject_gettingstarted"><i class="fa fa-check"></i><b>9.3.2</b> Opening an Existing RStudio Project</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="gettingstarted.html"><a href="gettingstarted.html#writtentutorials_gettingstarted"><i class="fa fa-check"></i><b>9.4</b> Orientation to Written Tutorials</a></li>
<li class="chapter" data-level="9.5" data-path="gettingstarted.html"><a href="gettingstarted.html#summary_gettingstarted"><i class="fa fa-check"></i><b>9.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="gentleintro.html"><a href="gentleintro.html"><i class="fa fa-check"></i><b>10</b> Basic Features and Operations of the R Language</a>
<ul>
<li class="chapter" data-level="10.1" data-path="gentleintro.html"><a href="gentleintro.html#videotutorial_gentleintro"><i class="fa fa-check"></i><b>10.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="10.2" data-path="gentleintro.html"><a href="gentleintro.html#functions_gentleintro"><i class="fa fa-check"></i><b>10.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="10.3" data-path="gentleintro.html"><a href="gentleintro.html#r_as_calculator"><i class="fa fa-check"></i><b>10.3</b> R as a Calculator</a></li>
<li class="chapter" data-level="10.4" data-path="gentleintro.html"><a href="gentleintro.html#functions"><i class="fa fa-check"></i><b>10.4</b> Functions</a></li>
<li class="chapter" data-level="10.5" data-path="gentleintro.html"><a href="gentleintro.html#packages"><i class="fa fa-check"></i><b>10.5</b> Packages</a></li>
<li class="chapter" data-level="10.6" data-path="gentleintro.html"><a href="gentleintro.html#variableassignment"><i class="fa fa-check"></i><b>10.6</b> Variable Assignment</a></li>
<li class="chapter" data-level="10.7" data-path="gentleintro.html"><a href="gentleintro.html#typesofdata"><i class="fa fa-check"></i><b>10.7</b> Types of Data</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="gentleintro.html"><a href="gentleintro.html#numeric-data"><i class="fa fa-check"></i><b>10.7.1</b> <code>numeric</code> Data</a></li>
<li class="chapter" data-level="10.7.2" data-path="gentleintro.html"><a href="gentleintro.html#character-data"><i class="fa fa-check"></i><b>10.7.2</b> <code>character</code> Data</a></li>
<li class="chapter" data-level="10.7.3" data-path="gentleintro.html"><a href="gentleintro.html#date-data"><i class="fa fa-check"></i><b>10.7.3</b> <code>Date</code> Data</a></li>
<li class="chapter" data-level="10.7.4" data-path="gentleintro.html"><a href="gentleintro.html#logical-data"><i class="fa fa-check"></i><b>10.7.4</b> <code>logical</code> Data</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="gentleintro.html"><a href="gentleintro.html#vectors"><i class="fa fa-check"></i><b>10.8</b> Vectors</a></li>
<li class="chapter" data-level="10.9" data-path="gentleintro.html"><a href="gentleintro.html#lists"><i class="fa fa-check"></i><b>10.9</b> Lists</a></li>
<li class="chapter" data-level="10.10" data-path="gentleintro.html"><a href="gentleintro.html#dataframes"><i class="fa fa-check"></i><b>10.10</b> Data Frames</a></li>
<li class="chapter" data-level="10.11" data-path="gentleintro.html"><a href="gentleintro.html#annotate"><i class="fa fa-check"></i><b>10.11</b> Annotations</a></li>
<li class="chapter" data-level="10.12" data-path="gentleintro.html"><a href="gentleintro.html#summary_gentleintro"><i class="fa fa-check"></i><b>10.12</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="setwd.html"><a href="setwd.html"><i class="fa fa-check"></i><b>11</b> Setting a Working Directory</a>
<ul>
<li class="chapter" data-level="11.1" data-path="setwd.html"><a href="setwd.html#videotutorial_setwd"><i class="fa fa-check"></i><b>11.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="11.2" data-path="setwd.html"><a href="setwd.html#functions_setwd"><i class="fa fa-check"></i><b>11.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="11.3" data-path="setwd.html"><a href="setwd.html#getwd_setwd"><i class="fa fa-check"></i><b>11.3</b> Identify the Current Working Directory</a></li>
<li class="chapter" data-level="11.4" data-path="setwd.html"><a href="setwd.html#setwd_setwd"><i class="fa fa-check"></i><b>11.4</b> Set a New Working Directory</a></li>
<li class="chapter" data-level="11.5" data-path="setwd.html"><a href="setwd.html#summary_setwd"><i class="fa fa-check"></i><b>11.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#part-data-acquisition-management"><i class="fa fa-check"></i>(PART) Data Acquisition &amp; Management</a>
<ul>
<li class="chapter" data-level="11.6" data-path="setwd.html"><a href="setwd.html#conceptualoverview_read"><i class="fa fa-check"></i><b>11.6</b> Conceptual Overview</a></li>
<li class="chapter" data-level="11.7" data-path="setwd.html"><a href="setwd.html#tutorial_read"><i class="fa fa-check"></i><b>11.7</b> Tutorial</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="setwd.html"><a href="setwd.html#videotutorial_read"><i class="fa fa-check"></i><b>11.7.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="11.7.2" data-path="setwd.html"><a href="setwd.html#functions_read"><i class="fa fa-check"></i><b>11.7.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="11.7.3" data-path="setwd.html"><a href="setwd.html#initialsteps_read"><i class="fa fa-check"></i><b>11.7.3</b> Initial Steps</a></li>
<li class="chapter" data-level="11.7.4" data-path="setwd.html"><a href="setwd.html#readcsv"><i class="fa fa-check"></i><b>11.7.4</b> Read a .csv File</a></li>
<li class="chapter" data-level="11.7.5" data-path="setwd.html"><a href="setwd.html#readxlsx"><i class="fa fa-check"></i><b>11.7.5</b> Read a .xlsx File</a></li>
<li class="chapter" data-level="11.7.6" data-path="setwd.html"><a href="setwd.html#read_summary"><i class="fa fa-check"></i><b>11.7.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="setwd.html"><a href="setwd.html#read_supplement"><i class="fa fa-check"></i><b>11.8</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="setwd.html"><a href="setwd.html#read_supplement_functions"><i class="fa fa-check"></i><b>11.8.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="11.8.2" data-path="setwd.html"><a href="setwd.html#read_initsteps_supplement"><i class="fa fa-check"></i><b>11.8.2</b> Initial Steps</a></li>
<li class="chapter" data-level="11.8.3" data-path="setwd.html"><a href="setwd.html#read_additionalfunctions"><i class="fa fa-check"></i><b>11.8.3</b> Additional Functions for Reading a .csv File</a></li>
<li class="chapter" data-level="11.8.4" data-path="setwd.html"><a href="setwd.html#read_skiprows"><i class="fa fa-check"></i><b>11.8.4</b> Skip Rows of Data During Read</a></li>
<li class="chapter" data-level="11.8.5" data-path="setwd.html"><a href="setwd.html#listdatafiles"><i class="fa fa-check"></i><b>11.8.5</b> List Data File Names in Working Directory</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="addnames.html"><a href="addnames.html"><i class="fa fa-check"></i><b>12</b> Removing, Adding, &amp; Changing Variable Names</a>
<ul>
<li class="chapter" data-level="12.1" data-path="addnames.html"><a href="addnames.html#conceptualoverview_addnames"><i class="fa fa-check"></i><b>12.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="12.2" data-path="addnames.html"><a href="addnames.html#tutorial_addnames"><i class="fa fa-check"></i><b>12.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="addnames.html"><a href="addnames.html#videotutorial_addnames"><i class="fa fa-check"></i><b>12.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="12.2.2" data-path="addnames.html"><a href="addnames.html#function_addnames"><i class="fa fa-check"></i><b>12.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="12.2.3" data-path="addnames.html"><a href="addnames.html#initsteps_addnames"><i class="fa fa-check"></i><b>12.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="12.2.4" data-path="addnames.html"><a href="addnames.html#remove_variablenames"><i class="fa fa-check"></i><b>12.2.4</b> Remove Variable Names from a Data Frame Object</a></li>
<li class="chapter" data-level="12.2.5" data-path="addnames.html"><a href="addnames.html#add_variablenames"><i class="fa fa-check"></i><b>12.2.5</b> Add Variable Names to a Data Frame Object</a></li>
<li class="chapter" data-level="12.2.6" data-path="addnames.html"><a href="addnames.html#change_variablenames"><i class="fa fa-check"></i><b>12.2.6</b> Change Specific Variable Names in a Data Frame Object</a></li>
<li class="chapter" data-level="12.2.7" data-path="addnames.html"><a href="addnames.html#summary_addnames"><i class="fa fa-check"></i><b>12.2.7</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="write.html"><a href="write.html"><i class="fa fa-check"></i><b>13</b> Writing Data from R</a>
<ul>
<li class="chapter" data-level="13.1" data-path="write.html"><a href="write.html#conceptualoverview_write"><i class="fa fa-check"></i><b>13.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="13.2" data-path="write.html"><a href="write.html#tutorial_write"><i class="fa fa-check"></i><b>13.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="write.html"><a href="write.html#videotutorial_write"><i class="fa fa-check"></i><b>13.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="13.2.2" data-path="write.html"><a href="write.html#functions_write"><i class="fa fa-check"></i><b>13.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="13.2.3" data-path="write.html"><a href="write.html#initialsteps_write"><i class="fa fa-check"></i><b>13.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="13.2.4" data-path="write.html"><a href="write.html#write_dataframe"><i class="fa fa-check"></i><b>13.2.4</b> Write Data Frame to Working Directory</a></li>
<li class="chapter" data-level="13.2.5" data-path="write.html"><a href="write.html#write_table"><i class="fa fa-check"></i><b>13.2.5</b> Write Table to Working Directory</a></li>
<li class="chapter" data-level="13.2.6" data-path="write.html"><a href="write.html#summary_write"><i class="fa fa-check"></i><b>13.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>14</b> Arranging (Sorting) Data</a>
<ul>
<li class="chapter" data-level="14.1" data-path="arrange.html"><a href="arrange.html#conceptualoverview_arrange"><i class="fa fa-check"></i><b>14.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="14.2" data-path="arrange.html"><a href="arrange.html#tutorial_arrange"><i class="fa fa-check"></i><b>14.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="arrange.html"><a href="arrange.html#videotutorial_arrange"><i class="fa fa-check"></i><b>14.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="14.2.2" data-path="arrange.html"><a href="arrange.html#functions_arrange"><i class="fa fa-check"></i><b>14.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="14.2.3" data-path="arrange.html"><a href="arrange.html#initsteps_arrange"><i class="fa fa-check"></i><b>14.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="14.2.4" data-path="arrange.html"><a href="arrange.html#arrangebyvalues"><i class="fa fa-check"></i><b>14.2.4</b> Arrange (Sort) Data</a></li>
<li class="chapter" data-level="14.2.5" data-path="arrange.html"><a href="arrange.html#summary_arrange"><i class="fa fa-check"></i><b>14.2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="arrange.html"><a href="arrange.html#arrange_supplement"><i class="fa fa-check"></i><b>14.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="arrange.html"><a href="arrange.html#arrange_supplement_functions"><i class="fa fa-check"></i><b>14.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="14.3.2" data-path="arrange.html"><a href="arrange.html#arrange_initsteps_supplement"><i class="fa fa-check"></i><b>14.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="14.3.3" data-path="arrange.html"><a href="arrange.html#arrange_orderfunction"><i class="fa fa-check"></i><b>14.3.3</b> <code>order</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="join.html"><a href="join.html"><i class="fa fa-check"></i><b>15</b> Joining (Merging) Data</a>
<ul>
<li class="chapter" data-level="15.1" data-path="join.html"><a href="join.html#conceptualoverview_join"><i class="fa fa-check"></i><b>15.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="join.html"><a href="join.html#review_horizontaljoin"><i class="fa fa-check"></i><b>15.1.1</b> Review of Horizontal Joins (Merges)</a></li>
<li class="chapter" data-level="15.1.2" data-path="join.html"><a href="join.html#review_verticaljoin"><i class="fa fa-check"></i><b>15.1.2</b> Review of Vertical Joins (Merges)</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="join.html"><a href="join.html#tutorial_join"><i class="fa fa-check"></i><b>15.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="join.html"><a href="join.html#videotutorial_join"><i class="fa fa-check"></i><b>15.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="15.2.2" data-path="join.html"><a href="join.html#functions-packages-introduced"><i class="fa fa-check"></i><b>15.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="15.2.3" data-path="join.html"><a href="join.html#initsteps_join"><i class="fa fa-check"></i><b>15.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="15.2.4" data-path="join.html"><a href="join.html#horizontaljoin"><i class="fa fa-check"></i><b>15.2.4</b> Horizontal Join (Merge)</a></li>
<li class="chapter" data-level="15.2.5" data-path="join.html"><a href="join.html#verticaljoin"><i class="fa fa-check"></i><b>15.2.5</b> Vertical Join (Merge)</a></li>
<li class="chapter" data-level="15.2.6" data-path="join.html"><a href="join.html#summary_join"><i class="fa fa-check"></i><b>15.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="join.html"><a href="join.html#join_supplement"><i class="fa fa-check"></i><b>15.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="join.html"><a href="join.html#supp_join_video"><i class="fa fa-check"></i><b>15.3.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="15.3.2" data-path="join.html"><a href="join.html#join_supplement_functions"><i class="fa fa-check"></i><b>15.3.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="15.3.3" data-path="join.html"><a href="join.html#join_initsteps_supplement"><i class="fa fa-check"></i><b>15.3.3</b> Initial Steps</a></li>
<li class="chapter" data-level="15.3.4" data-path="join.html"><a href="join.html#join_mergefunction"><i class="fa fa-check"></i><b>15.3.4</b> <code>merge</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>16</b> Filtering (Subsetting) Data</a>
<ul>
<li class="chapter" data-level="16.1" data-path="filter.html"><a href="filter.html#conceptualoverview_filter"><i class="fa fa-check"></i><b>16.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="filter.html"><a href="filter.html#review_logicaloperators"><i class="fa fa-check"></i><b>16.1.1</b> Review of Logical Operators</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="filter.html"><a href="filter.html#tutorial_filter"><i class="fa fa-check"></i><b>16.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="filter.html"><a href="filter.html#videotutorial_filter"><i class="fa fa-check"></i><b>16.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="16.2.2" data-path="filter.html"><a href="filter.html#function_filter"><i class="fa fa-check"></i><b>16.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="16.2.3" data-path="filter.html"><a href="filter.html#initsteps_filter"><i class="fa fa-check"></i><b>16.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="16.2.4" data-path="filter.html"><a href="filter.html#filter_cases"><i class="fa fa-check"></i><b>16.2.4</b> Filter Cases from Data Frame</a></li>
<li class="chapter" data-level="16.2.5" data-path="filter.html"><a href="filter.html#remove-single-variable-from-data-frame"><i class="fa fa-check"></i><b>16.2.5</b> Remove Single Variable from Data Frame</a></li>
<li class="chapter" data-level="16.2.6" data-path="filter.html"><a href="filter.html#select_multiplevariables"><i class="fa fa-check"></i><b>16.2.6</b> Select Multiple Variables from Data Frame</a></li>
<li class="chapter" data-level="16.2.7" data-path="filter.html"><a href="filter.html#remove_multiplevariables"><i class="fa fa-check"></i><b>16.2.7</b> Remove Multiple Variables from Data Frame</a></li>
<li class="chapter" data-level="16.2.8" data-path="filter.html"><a href="filter.html#summary_filter"><i class="fa fa-check"></i><b>16.2.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="filter.html"><a href="filter.html#filter_supplement"><i class="fa fa-check"></i><b>16.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="filter.html"><a href="filter.html#supp_filter_video"><i class="fa fa-check"></i><b>16.3.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="16.3.2" data-path="filter.html"><a href="filter.html#filter_supplement_functions"><i class="fa fa-check"></i><b>16.3.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="16.3.3" data-path="filter.html"><a href="filter.html#filter_initsteps_supplement"><i class="fa fa-check"></i><b>16.3.3</b> Initial Steps</a></li>
<li class="chapter" data-level="16.3.4" data-path="filter.html"><a href="filter.html#filter_subset_supplement"><i class="fa fa-check"></i><b>16.3.4</b> <code>subset</code> Function from Base R</a></li>
<li class="chapter" data-level="16.3.5" data-path="filter.html"><a href="filter.html#str_detect_supp"><i class="fa fa-check"></i><b>16.3.5</b> Filter by Pattern Contained within String</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="clean.html"><a href="clean.html"><i class="fa fa-check"></i><b>17</b> Cleaning Data</a>
<ul>
<li class="chapter" data-level="17.1" data-path="clean.html"><a href="clean.html#conceptualoverview_clean"><i class="fa fa-check"></i><b>17.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="17.2" data-path="clean.html"><a href="clean.html#tutorial_clean"><i class="fa fa-check"></i><b>17.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="clean.html"><a href="clean.html#videotutorial_clean"><i class="fa fa-check"></i><b>17.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="17.2.2" data-path="clean.html"><a href="clean.html#functions_clean"><i class="fa fa-check"></i><b>17.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="17.2.3" data-path="clean.html"><a href="clean.html#initsteps_clean"><i class="fa fa-check"></i><b>17.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="17.2.4" data-path="clean.html"><a href="clean.html#reviewdata_clean"><i class="fa fa-check"></i><b>17.2.4</b> Review Data</a></li>
<li class="chapter" data-level="17.2.5" data-path="clean.html"><a href="clean.html#cleandata_clean"><i class="fa fa-check"></i><b>17.2.5</b> Clean Data</a></li>
<li class="chapter" data-level="17.2.6" data-path="clean.html"><a href="clean.html#renamevariables_clean"><i class="fa fa-check"></i><b>17.2.6</b> Rename Variables</a></li>
<li class="chapter" data-level="17.2.7" data-path="clean.html"><a href="clean.html#otherapproaches_clean"><i class="fa fa-check"></i><b>17.2.7</b> Other Approaches to Cleaning Data</a></li>
<li class="chapter" data-level="17.2.8" data-path="clean.html"><a href="clean.html#summary_clean"><i class="fa fa-check"></i><b>17.2.8</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="manipulate.html"><a href="manipulate.html"><i class="fa fa-check"></i><b>18</b> Manipulating &amp; Restructuring Data</a>
<ul>
<li class="chapter" data-level="18.1" data-path="manipulate.html"><a href="manipulate.html#conceptualoverview_manipulate"><i class="fa fa-check"></i><b>18.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="18.2" data-path="manipulate.html"><a href="manipulate.html#tutorial_manipulate"><i class="fa fa-check"></i><b>18.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="manipulate.html"><a href="manipulate.html#videotutorial_manipulate"><i class="fa fa-check"></i><b>18.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="18.2.2" data-path="manipulate.html"><a href="manipulate.html#functions_manipulate"><i class="fa fa-check"></i><b>18.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="18.2.3" data-path="manipulate.html"><a href="manipulate.html#initsteps_manipulate"><i class="fa fa-check"></i><b>18.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="18.2.4" data-path="manipulate.html"><a href="manipulate.html#manipulate_widetolong"><i class="fa fa-check"></i><b>18.2.4</b> Wide-to-Long Format Data Manipulation</a></li>
<li class="chapter" data-level="18.2.5" data-path="manipulate.html"><a href="manipulate.html#manipulate_longtowide"><i class="fa fa-check"></i><b>18.2.5</b> Long-to-Wide Format Data Manipulation</a></li>
<li class="chapter" data-level="18.2.6" data-path="manipulate.html"><a href="manipulate.html#summary_manipulate"><i class="fa fa-check"></i><b>18.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="center.html"><a href="center.html"><i class="fa fa-check"></i><b>19</b> Centering &amp; Standardizing Variables</a>
<ul>
<li class="chapter" data-level="19.1" data-path="center.html"><a href="center.html#conceptualoverview_center"><i class="fa fa-check"></i><b>19.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="center.html"><a href="center.html#review_center"><i class="fa fa-check"></i><b>19.1.1</b> Review of Centering Variables</a></li>
<li class="chapter" data-level="19.1.2" data-path="center.html"><a href="center.html#review_standardize"><i class="fa fa-check"></i><b>19.1.2</b> Review of Standardizing Variables</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="center.html"><a href="center.html#tutorial_center"><i class="fa fa-check"></i><b>19.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="center.html"><a href="center.html#videotutorial_center"><i class="fa fa-check"></i><b>19.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="19.2.2" data-path="center.html"><a href="center.html#functions_center"><i class="fa fa-check"></i><b>19.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="19.2.3" data-path="center.html"><a href="center.html#initsteps_center"><i class="fa fa-check"></i><b>19.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="19.2.4" data-path="center.html"><a href="center.html#grandmean_center"><i class="fa fa-check"></i><b>19.2.4</b> Grand-Mean Center Variables</a></li>
<li class="chapter" data-level="19.2.5" data-path="center.html"><a href="center.html#groupmean_center"><i class="fa fa-check"></i><b>19.2.5</b> Group-Mean Center Variables</a></li>
<li class="chapter" data-level="19.2.6" data-path="center.html"><a href="center.html#standardize_center"><i class="fa fa-check"></i><b>19.2.6</b> Standardize Variables</a></li>
<li class="chapter" data-level="19.2.7" data-path="center.html"><a href="center.html#summary_center"><i class="fa fa-check"></i><b>19.2.7</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="removeobjects.html"><a href="removeobjects.html"><i class="fa fa-check"></i><b>20</b> Removing Objects from the R Environment</a>
<ul>
<li class="chapter" data-level="20.1" data-path="removeobjects.html"><a href="removeobjects.html#conceptualoverview_removeobjects"><i class="fa fa-check"></i><b>20.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="20.2" data-path="removeobjects.html"><a href="removeobjects.html#tutorial_removeobjects"><i class="fa fa-check"></i><b>20.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="removeobjects.html"><a href="removeobjects.html#videotutorial_removeobjects"><i class="fa fa-check"></i><b>20.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="20.2.2" data-path="removeobjects.html"><a href="removeobjects.html#function_removeobjects"><i class="fa fa-check"></i><b>20.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="20.2.3" data-path="removeobjects.html"><a href="removeobjects.html#initsteps_removeobjects"><i class="fa fa-check"></i><b>20.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="20.2.4" data-path="removeobjects.html"><a href="removeobjects.html#listobjects_removeobjects"><i class="fa fa-check"></i><b>20.2.4</b> List Objects in R Environment</a></li>
<li class="chapter" data-level="20.2.5" data-path="removeobjects.html"><a href="removeobjects.html#removeobjects_removeobjects"><i class="fa fa-check"></i><b>20.2.5</b> Remove Objects from R Environment</a></li>
<li class="chapter" data-level="20.2.6" data-path="removeobjects.html"><a href="removeobjects.html#summary_removeobjects"><i class="fa fa-check"></i><b>20.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Employee Demographics</b></span></li>
<li class="chapter" data-level="21" data-path="employeedemographics.html"><a href="employeedemographics.html"><i class="fa fa-check"></i><b>21</b> Introduction to Employee Demographics</a></li>
<li class="chapter" data-level="22" data-path="descriptives.html"><a href="descriptives.html"><i class="fa fa-check"></i><b>22</b> Describing Employee Demographics Using Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="22.1" data-path="descriptives.html"><a href="descriptives.html#conceptualoverview_descriptives"><i class="fa fa-check"></i><b>22.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="22.1.1" data-path="descriptives.html"><a href="descriptives.html#measurementscales"><i class="fa fa-check"></i><b>22.1.1</b> Review of Measurement Scales</a></li>
<li class="chapter" data-level="22.1.2" data-path="descriptives.html"><a href="descriptives.html#constructs_measures_measurementscales"><i class="fa fa-check"></i><b>22.1.2</b> Constructs, Measures, &amp; Measurement Scales</a></li>
<li class="chapter" data-level="22.1.3" data-path="descriptives.html"><a href="descriptives.html#typesof_descriptivestatistics"><i class="fa fa-check"></i><b>22.1.3</b> Types of Descriptive Statistics</a></li>
<li class="chapter" data-level="22.1.4" data-path="descriptives.html"><a href="descriptives.html#samplewriteup_descriptives"><i class="fa fa-check"></i><b>22.1.4</b> Sample Write-Up</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="descriptives.html"><a href="descriptives.html#tutorial_descriptives"><i class="fa fa-check"></i><b>22.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="22.2.1" data-path="descriptives.html"><a href="descriptives.html#videotutorial_descriptives"><i class="fa fa-check"></i><b>22.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="22.2.2" data-path="descriptives.html"><a href="descriptives.html#functions_descriptives"><i class="fa fa-check"></i><b>22.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="22.2.3" data-path="descriptives.html"><a href="descriptives.html#initsteps_descriptives"><i class="fa fa-check"></i><b>22.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="22.2.4" data-path="descriptives.html"><a href="descriptives.html#determine_measurementscale"><i class="fa fa-check"></i><b>22.2.4</b> Determine the Measurement Scale</a></li>
<li class="chapter" data-level="22.2.5" data-path="descriptives.html"><a href="descriptives.html#describe_nominal_ordinal"><i class="fa fa-check"></i><b>22.2.5</b> Describe Nominal &amp; Ordinal (Categorical) Variables</a></li>
<li class="chapter" data-level="22.2.6" data-path="descriptives.html"><a href="descriptives.html#describe_interval_ratio"><i class="fa fa-check"></i><b>22.2.6</b> Describe Interval &amp; Ratio (Continuous) Variables</a></li>
<li class="chapter" data-level="22.2.7" data-path="descriptives.html"><a href="descriptives.html#summary_descriptives"><i class="fa fa-check"></i><b>22.2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="descriptives.html"><a href="descriptives.html#descriptives_supplement"><i class="fa fa-check"></i><b>22.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="22.3.1" data-path="descriptives.html"><a href="descriptives.html#descriptives_supplement_functions"><i class="fa fa-check"></i><b>22.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="22.3.2" data-path="descriptives.html"><a href="descriptives.html#descriptives_initsteps_supplement"><i class="fa fa-check"></i><b>22.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="22.3.3" data-path="descriptives.html"><a href="descriptives.html#descriptives_coefficientofvariation_supplement"><i class="fa fa-check"></i><b>22.3.3</b> Compute Coefficient of Variation (CV)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="23" data-path="crosstabs.html"><a href="crosstabs.html"><i class="fa fa-check"></i><b>23</b> Summarizing Two or More Categorical Variables Using Cross-Tabulations</a>
<ul>
<li class="chapter" data-level="23.1" data-path="crosstabs.html"><a href="crosstabs.html#conceptualoverview_crosstabs"><i class="fa fa-check"></i><b>23.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="23.1.1" data-path="crosstabs.html"><a href="crosstabs.html#review_crosstabs"><i class="fa fa-check"></i><b>23.1.1</b> Review of Cross-Tabulation</a></li>
<li class="chapter" data-level="23.1.2" data-path="crosstabs.html"><a href="crosstabs.html#samplewriteup_crosstabs"><i class="fa fa-check"></i><b>23.1.2</b> Sample Write-Up</a></li>
</ul></li>
<li class="chapter" data-level="23.2" data-path="crosstabs.html"><a href="crosstabs.html#tutorial_crosstabs"><i class="fa fa-check"></i><b>23.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="23.2.1" data-path="crosstabs.html"><a href="crosstabs.html#videotutorial_crosstabs"><i class="fa fa-check"></i><b>23.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="23.2.2" data-path="crosstabs.html"><a href="crosstabs.html#functions_crosstabs"><i class="fa fa-check"></i><b>23.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="23.2.3" data-path="crosstabs.html"><a href="crosstabs.html#initsteps_tables"><i class="fa fa-check"></i><b>23.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="23.2.4" data-path="crosstabs.html"><a href="crosstabs.html#twoway_crosstabs"><i class="fa fa-check"></i><b>23.2.4</b> Two-Way Cross-Tabulation</a></li>
<li class="chapter" data-level="23.2.5" data-path="crosstabs.html"><a href="crosstabs.html#threeway_crosstabs"><i class="fa fa-check"></i><b>23.2.5</b> Three-Way Cross-Tabulation</a></li>
<li class="chapter" data-level="23.2.6" data-path="crosstabs.html"><a href="crosstabs.html#summary_crosstabs"><i class="fa fa-check"></i><b>23.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="24" data-path="pivottables.html"><a href="pivottables.html"><i class="fa fa-check"></i><b>24</b> Applying Pivot Tables to Explore Employee Demographic Data</a>
<ul>
<li class="chapter" data-level="24.1" data-path="pivottables.html"><a href="pivottables.html#conceptualoverview_pivottables"><i class="fa fa-check"></i><b>24.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="24.2" data-path="pivottables.html"><a href="pivottables.html#tutorial_pivottables"><i class="fa fa-check"></i><b>24.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="24.2.1" data-path="pivottables.html"><a href="pivottables.html#videotutorial_pivottables"><i class="fa fa-check"></i><b>24.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="24.2.2" data-path="pivottables.html"><a href="pivottables.html#functions_pivottables"><i class="fa fa-check"></i><b>24.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="24.2.3" data-path="pivottables.html"><a href="pivottables.html#initsteps_pivottables"><i class="fa fa-check"></i><b>24.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="24.2.4" data-path="pivottables.html"><a href="pivottables.html#create_pivottables"><i class="fa fa-check"></i><b>24.2.4</b> Create a Pivot Table</a></li>
<li class="chapter" data-level="24.2.5" data-path="pivottables.html"><a href="pivottables.html#summary_pivottables"><i class="fa fa-check"></i><b>24.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Employee Surveys</b></span></li>
<li class="chapter" data-level="25" data-path="employeesurveys.html"><a href="employeesurveys.html"><i class="fa fa-check"></i><b>25</b> Introduction to Employee Surveys</a></li>
<li class="chapter" data-level="26" data-path="aggregatesegment.html"><a href="aggregatesegment.html"><i class="fa fa-check"></i><b>26</b> Aggregating &amp; Segmenting Employee Survey Data</a>
<ul>
<li class="chapter" data-level="26.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#conceptualoverview_aggregatesegment"><i class="fa fa-check"></i><b>26.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="26.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#tutorial_aggregatesegment"><i class="fa fa-check"></i><b>26.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="26.2.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#videotutorial_aggregatesegment"><i class="fa fa-check"></i><b>26.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="26.2.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#functions_aggregatesegment"><i class="fa fa-check"></i><b>26.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="26.2.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#initsteps_aggregatesegment"><i class="fa fa-check"></i><b>26.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="26.2.4" data-path="aggregatesegment.html"><a href="aggregatesegment.html#counts_bygroup"><i class="fa fa-check"></i><b>26.2.4</b> Counts By Group</a></li>
<li class="chapter" data-level="26.2.5" data-path="aggregatesegment.html"><a href="aggregatesegment.html#centraldispersion_bygroup"><i class="fa fa-check"></i><b>26.2.5</b> Measures of Central Tendency and Dispersion By Group</a></li>
<li class="chapter" data-level="26.2.6" data-path="aggregatesegment.html"><a href="aggregatesegment.html#addaggregatedvariable"><i class="fa fa-check"></i><b>26.2.6</b> Add Variable to Data Frame Containing Aggregated Values</a></li>
<li class="chapter" data-level="26.2.7" data-path="aggregatesegment.html"><a href="aggregatesegment.html#visualize_bygroup"><i class="fa fa-check"></i><b>26.2.7</b> Visualize Data By Group</a></li>
<li class="chapter" data-level="26.2.8" data-path="aggregatesegment.html"><a href="aggregatesegment.html#summary_aggregatesegment"><i class="fa fa-check"></i><b>26.2.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="26.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_supplement"><i class="fa fa-check"></i><b>26.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="26.3.1" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_supplement_functions"><i class="fa fa-check"></i><b>26.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="26.3.2" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_initsteps_supplement"><i class="fa fa-check"></i><b>26.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="26.3.3" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_describeby_supplement"><i class="fa fa-check"></i><b>26.3.3</b> <code>describeBy</code> Function from <code>psych</code> Package</a></li>
<li class="chapter" data-level="26.3.4" data-path="aggregatesegment.html"><a href="aggregatesegment.html#aggregatesegment_aggregate_supplement"><i class="fa fa-check"></i><b>26.3.4</b> <code>aggregate</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="27" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html"><i class="fa fa-check"></i><b>27</b> Estimating Internal Consistency Reliability Using Cronbach’s alpha</a>
<ul>
<li class="chapter" data-level="27.1" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#conceptualoverview_cronbachsalpha"><i class="fa fa-check"></i><b>27.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="27.2" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#tutorial_cronbachsalpha"><i class="fa fa-check"></i><b>27.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="27.2.1" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#videotutorial_cronbachsalpha"><i class="fa fa-check"></i><b>27.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="27.2.2" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#functions_cronbachsalpha"><i class="fa fa-check"></i><b>27.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="27.2.3" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#initsteps_cronbachsalpha"><i class="fa fa-check"></i><b>27.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="27.2.4" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#cronbachsalpha_alpha"><i class="fa fa-check"></i><b>27.2.4</b> Compute Cronbach’s alpha</a></li>
<li class="chapter" data-level="27.2.5" data-path="cronbachsalpha.html"><a href="cronbachsalpha.html#summary_cronbachsalpha"><i class="fa fa-check"></i><b>27.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="28" data-path="compositevariable.html"><a href="compositevariable.html"><i class="fa fa-check"></i><b>28</b> Creating a Composite Variable Based on a Multi-Item Measure</a>
<ul>
<li class="chapter" data-level="28.1" data-path="compositevariable.html"><a href="compositevariable.html#conceptualoverview_compositevariable"><i class="fa fa-check"></i><b>28.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="28.2" data-path="compositevariable.html"><a href="compositevariable.html#tutorial_compositevariable"><i class="fa fa-check"></i><b>28.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="28.2.1" data-path="compositevariable.html"><a href="compositevariable.html#videotutorial_compositevariable"><i class="fa fa-check"></i><b>28.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="28.2.2" data-path="compositevariable.html"><a href="compositevariable.html#functions_compositevariable"><i class="fa fa-check"></i><b>28.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="28.2.3" data-path="compositevariable.html"><a href="compositevariable.html#initsteps_compositevariable"><i class="fa fa-check"></i><b>28.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="28.2.4" data-path="compositevariable.html"><a href="compositevariable.html#compositevariable_cronbachsalpha"><i class="fa fa-check"></i><b>28.2.4</b> Compute Cronbach’s alpha</a></li>
<li class="chapter" data-level="28.2.5" data-path="compositevariable.html"><a href="compositevariable.html#compositevariable_composite"><i class="fa fa-check"></i><b>28.2.5</b> Create a Composite Variable</a></li>
<li class="chapter" data-level="28.2.6" data-path="compositevariable.html"><a href="compositevariable.html#summary_compositevariable"><i class="fa fa-check"></i><b>28.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#part-employee-training"><i class="fa fa-check"></i>(PART) Employee Training</a>
<ul>
<li class="chapter" data-level="28.3" data-path="compositevariable.html"><a href="compositevariable.html#trainingevaluation_employeetraining"><i class="fa fa-check"></i><b>28.3</b> Training Evaluation</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="pretestposttest.html"><a href="pretestposttest.html"><i class="fa fa-check"></i><b>29</b> Evaluating a Pre-Test/Post-Test without Control Group Design Using Paired-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="29.1" data-path="pretestposttest.html"><a href="pretestposttest.html#conceptualoverview_pretestposttest_psttest"><i class="fa fa-check"></i><b>29.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="29.1.1" data-path="pretestposttest.html"><a href="pretestposttest.html#review_pretestposttest"><i class="fa fa-check"></i><b>29.1.1</b> Review of Pre-Test/Post-Test without Control Group Design</a></li>
<li class="chapter" data-level="29.1.2" data-path="pretestposttest.html"><a href="pretestposttest.html#review_psttest"><i class="fa fa-check"></i><b>29.1.2</b> Review of Paired-Samples <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="29.2" data-path="pretestposttest.html"><a href="pretestposttest.html#tutorial_psttest"><i class="fa fa-check"></i><b>29.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="29.2.1" data-path="pretestposttest.html"><a href="pretestposttest.html#videotutorial_psttest"><i class="fa fa-check"></i><b>29.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="29.2.2" data-path="pretestposttest.html"><a href="pretestposttest.html#functions_psttest"><i class="fa fa-check"></i><b>29.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="29.2.3" data-path="pretestposttest.html"><a href="pretestposttest.html#initsteps_psttest"><i class="fa fa-check"></i><b>29.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="29.2.4" data-path="pretestposttest.html"><a href="pretestposttest.html#estimate_psttest"><i class="fa fa-check"></i><b>29.2.4</b> Estimate Paired-Samples <em>t</em>-test</a></li>
<li class="chapter" data-level="29.2.5" data-path="pretestposttest.html"><a href="pretestposttest.html#barchart_psttest"><i class="fa fa-check"></i><b>29.2.5</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="29.2.6" data-path="pretestposttest.html"><a href="pretestposttest.html#summary_psttest"><i class="fa fa-check"></i><b>29.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="29.3" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_supplement"><i class="fa fa-check"></i><b>29.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="29.3.1" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_supplement_functions"><i class="fa fa-check"></i><b>29.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="29.3.2" data-path="pretestposttest.html"><a href="pretestposttest.html#psttest_initsteps_supplement"><i class="fa fa-check"></i><b>29.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="29.3.3" data-path="pretestposttest.html"><a href="pretestposttest.html#t.test_function_psttest"><i class="fa fa-check"></i><b>29.3.3</b> <code>t.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="30" data-path="posttestonly.html"><a href="posttestonly.html"><i class="fa fa-check"></i><b>30</b> Evaluating a Post-Test-Only with Control Group Design Using Independent-Samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="30.1" data-path="posttestonly.html"><a href="posttestonly.html#conceptualoverview_posttestonly_isttest"><i class="fa fa-check"></i><b>30.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="30.1.1" data-path="posttestonly.html"><a href="posttestonly.html#review_posttestonly"><i class="fa fa-check"></i><b>30.1.1</b> Review of Post-Test-Only with Control Group Design</a></li>
<li class="chapter" data-level="30.1.2" data-path="posttestonly.html"><a href="posttestonly.html#review_isttest"><i class="fa fa-check"></i><b>30.1.2</b> Review of Independent-Samples <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="30.2" data-path="posttestonly.html"><a href="posttestonly.html#tutorial_isttest"><i class="fa fa-check"></i><b>30.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="30.2.1" data-path="posttestonly.html"><a href="posttestonly.html#videotutorial_isttest"><i class="fa fa-check"></i><b>30.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="30.2.2" data-path="posttestonly.html"><a href="posttestonly.html#functions_isttest"><i class="fa fa-check"></i><b>30.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="30.2.3" data-path="posttestonly.html"><a href="posttestonly.html#initsteps_isttest"><i class="fa fa-check"></i><b>30.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="30.2.4" data-path="posttestonly.html"><a href="posttestonly.html#estimate_isttest"><i class="fa fa-check"></i><b>30.2.4</b> Estimate Independent-Samples <em>t</em>-test</a></li>
<li class="chapter" data-level="30.2.5" data-path="posttestonly.html"><a href="posttestonly.html#barchart_isttest"><i class="fa fa-check"></i><b>30.2.5</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="30.2.6" data-path="posttestonly.html"><a href="posttestonly.html#summary_isttest"><i class="fa fa-check"></i><b>30.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="30.3" data-path="posttestonly.html"><a href="posttestonly.html#isttest_supplement"><i class="fa fa-check"></i><b>30.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="30.3.1" data-path="posttestonly.html"><a href="posttestonly.html#isttest_supplement_functions"><i class="fa fa-check"></i><b>30.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="30.3.2" data-path="posttestonly.html"><a href="posttestonly.html#isttest_initsteps_supplement"><i class="fa fa-check"></i><b>30.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="30.3.3" data-path="posttestonly.html"><a href="posttestonly.html#t.test_function_isttest"><i class="fa fa-check"></i><b>30.3.3</b> <code>t.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="31" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html"><i class="fa fa-check"></i><b>31</b> Evaluating a Post-Test-Only with Two Comparison Groups Design Using One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="31.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#conceptualoverview_posttestonly_threegroups_onewayanova"><i class="fa fa-check"></i><b>31.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="31.1.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#review_posttestonly_threegroups"><i class="fa fa-check"></i><b>31.1.1</b> Review of Post-Test-Only with Two Comparison Groups Design</a></li>
<li class="chapter" data-level="31.1.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#review_onewayanova"><i class="fa fa-check"></i><b>31.1.2</b> Review of One-Way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="31.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#tutorial_onewayanova"><i class="fa fa-check"></i><b>31.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="31.2.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#videotutorial_onewayanova"><i class="fa fa-check"></i><b>31.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="31.2.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#functions_onewayanova"><i class="fa fa-check"></i><b>31.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="31.2.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#initsteps_onewayanova"><i class="fa fa-check"></i><b>31.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="31.2.4" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#teststatisticalassumptions_onewayanova"><i class="fa fa-check"></i><b>31.2.4</b> Test Statistical Assumptions</a></li>
<li class="chapter" data-level="31.2.5" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#estimate_onewayanova"><i class="fa fa-check"></i><b>31.2.5</b> Estimate One-Way ANOVA</a></li>
<li class="chapter" data-level="31.2.6" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#barchart_onewayanova"><i class="fa fa-check"></i><b>31.2.6</b> Visualize Results Using Bar Chart</a></li>
<li class="chapter" data-level="31.2.7" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#summary_onewayanova"><i class="fa fa-check"></i><b>31.2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="31.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_supplement"><i class="fa fa-check"></i><b>31.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="31.3.1" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_supplement_functions"><i class="fa fa-check"></i><b>31.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="31.3.2" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#onewayanova_initsteps_supplement"><i class="fa fa-check"></i><b>31.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="31.3.3" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#aov_function_onewayanova"><i class="fa fa-check"></i><b>31.3.3</b> <code>aov</code> Function from Base R</a></li>
<li class="chapter" data-level="31.3.4" data-path="posttestonly-threegroups.html"><a href="posttestonly-threegroups.html#apatable_onewayanova"><i class="fa fa-check"></i><b>31.3.4</b> APA-Style Table of Results</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Employee Selection</b></span></li>
<li class="chapter" data-level="32" data-path="selection.html"><a href="selection.html"><i class="fa fa-check"></i><b>32</b> Introduction to Employee Selection</a></li>
<li class="chapter" data-level="33" data-path="disparateimpact.html"><a href="disparateimpact.html"><i class="fa fa-check"></i><b>33</b> Investigating Disparate Impact</a>
<ul>
<li class="chapter" data-level="33.1" data-path="disparateimpact.html"><a href="disparateimpact.html#conceptualoverview_disparateimpact"><i class="fa fa-check"></i><b>33.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="33.2" data-path="disparateimpact.html"><a href="disparateimpact.html#tutorial_disparateimpact"><i class="fa fa-check"></i><b>33.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="33.2.1" data-path="disparateimpact.html"><a href="disparateimpact.html#videotutorial_disparateimpact"><i class="fa fa-check"></i><b>33.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="33.2.2" data-path="disparateimpact.html"><a href="disparateimpact.html#functions_disparateimpact"><i class="fa fa-check"></i><b>33.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="33.2.3" data-path="disparateimpact.html"><a href="disparateimpact.html#initsteps_disparateimpact"><i class="fa fa-check"></i><b>33.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="33.2.4" data-path="disparateimpact.html"><a href="disparateimpact.html#fourfifthsrule"><i class="fa fa-check"></i><b>33.2.4</b> 4/5ths Rule</a></li>
<li class="chapter" data-level="33.2.5" data-path="disparateimpact.html"><a href="disparateimpact.html#chisquaretest_disparateimpact"><i class="fa fa-check"></i><b>33.2.5</b> chi-square (<span class="math inline">\(\chi^2\)</span>) Test of Independence</a></li>
<li class="chapter" data-level="33.2.6" data-path="disparateimpact.html"><a href="disparateimpact.html#fisherexacttest"><i class="fa fa-check"></i><b>33.2.6</b> Fisher Exact Test</a></li>
<li class="chapter" data-level="33.2.7" data-path="disparateimpact.html"><a href="disparateimpact.html#zdifference_test_disparateimpact"><i class="fa fa-check"></i><b>33.2.7</b> <span class="math inline">\(Z_{D}\)</span> Test</a></li>
<li class="chapter" data-level="33.2.8" data-path="disparateimpact.html"><a href="disparateimpact.html#z_impactratiotest"><i class="fa fa-check"></i><b>33.2.8</b> <span class="math inline">\(Z_{IR}\)</span> Test</a></li>
<li class="chapter" data-level="33.2.9" data-path="disparateimpact.html"><a href="disparateimpact.html#summary_disparatetreatment"><i class="fa fa-check"></i><b>33.2.9</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="34" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html"><i class="fa fa-check"></i><b>34</b> Estimating Criterion-Related Validity of a Selection Tool Using Correlation</a>
<ul>
<li class="chapter" data-level="34.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#conceptualoverview_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="34.1.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#review_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.1.1</b> Review of Criterion-Related Validity</a></li>
<li class="chapter" data-level="34.1.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#review_correlation"><i class="fa fa-check"></i><b>34.1.2</b> Review of Correlation</a></li>
</ul></li>
<li class="chapter" data-level="34.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#tutorial_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="34.2.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#videotutorial_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="34.2.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#functions_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="34.2.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#initsteps_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="34.2.4" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#scatterplot_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.2.4</b> Visualize Association Using a Scatter Plot</a></li>
<li class="chapter" data-level="34.2.5" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#estimate_correlation"><i class="fa fa-check"></i><b>34.2.5</b> Estimate Correlation</a></li>
<li class="chapter" data-level="34.2.6" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#summary_criterionrelatedvalidity"><i class="fa fa-check"></i><b>34.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="34.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_supplement"><i class="fa fa-check"></i><b>34.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="34.3.1" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_supplement_functions"><i class="fa fa-check"></i><b>34.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="34.3.2" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#criterionrelatedvalidity_initsteps_supplement"><i class="fa fa-check"></i><b>34.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="34.3.3" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#cor_function"><i class="fa fa-check"></i><b>34.3.3</b> <code>cor</code> Function from Base R</a></li>
<li class="chapter" data-level="34.3.4" data-path="criterionrelatedvalidity.html"><a href="criterionrelatedvalidity.html#cortest_function"><i class="fa fa-check"></i><b>34.3.4</b> <code>cor.test</code> Function from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="35" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html"><i class="fa fa-check"></i><b>35</b> Predicting Criterion Scores Based on Selection Tool Scores Using Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="35.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#conceptualoverview_predictingcriterionscores"><i class="fa fa-check"></i><b>35.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="35.1.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#review_slr"><i class="fa fa-check"></i><b>35.1.1</b> Review of Simple Linear Regression</a></li>
<li class="chapter" data-level="35.1.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#review_prediction_slr"><i class="fa fa-check"></i><b>35.1.2</b> Predicting Future Criterion Scores Using Simple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="35.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#tutorial_predictingcriterionscores"><i class="fa fa-check"></i><b>35.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="35.2.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#videotutorial_predictingcriterionscores"><i class="fa fa-check"></i><b>35.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="35.2.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#functions_predictingcriterionscores"><i class="fa fa-check"></i><b>35.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="35.2.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#initsteps_slr"><i class="fa fa-check"></i><b>35.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="35.2.4" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#estimate_slr"><i class="fa fa-check"></i><b>35.2.4</b> Estimate Simple Linear Regression Model</a></li>
<li class="chapter" data-level="35.2.5" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_slr"><i class="fa fa-check"></i><b>35.2.5</b> Predict Criterion Scores</a></li>
<li class="chapter" data-level="35.2.6" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#summary_predictingcriterionscores"><i class="fa fa-check"></i><b>35.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="35.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_supplement"><i class="fa fa-check"></i><b>35.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="35.3.1" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_supplement_functions"><i class="fa fa-check"></i><b>35.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="35.3.2" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predictingcriterionscores_initsteps_supplement"><i class="fa fa-check"></i><b>35.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="35.3.3" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#lm_function_slr"><i class="fa fa-check"></i><b>35.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="35.3.4" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#predict_function_slr"><i class="fa fa-check"></i><b>35.3.4</b> <code>predict</code> Function from Base R</a></li>
<li class="chapter" data-level="35.3.5" data-path="predictingcriterionscores.html"><a href="predictingcriterionscores.html#apatable_slr"><i class="fa fa-check"></i><b>35.3.5</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="36" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html"><i class="fa fa-check"></i><b>36</b> Estimating Incremental Validity of a Selection Tool Using Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="36.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#conceptualoverview_incrementalvalidity"><i class="fa fa-check"></i><b>36.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="36.1.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#review_mlr"><i class="fa fa-check"></i><b>36.1.1</b> Review of Multiple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="36.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#tutorial_incrementalvalidity"><i class="fa fa-check"></i><b>36.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="36.2.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#videotutorial_incrementalvalidity"><i class="fa fa-check"></i><b>36.2.1</b> Video Tutorials</a></li>
<li class="chapter" data-level="36.2.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#function_incrementalvalidity"><i class="fa fa-check"></i><b>36.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="36.2.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#initsteps_mlr"><i class="fa fa-check"></i><b>36.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="36.2.4" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#estimate_mlr"><i class="fa fa-check"></i><b>36.2.4</b> Estimate Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="36.2.5" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#summary_incrementalvalidity"><i class="fa fa-check"></i><b>36.2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="36.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_supplement"><i class="fa fa-check"></i><b>36.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="36.3.1" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_supplement_functions"><i class="fa fa-check"></i><b>36.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="36.3.2" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#incrementalvalidity_initsteps_supplement"><i class="fa fa-check"></i><b>36.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="36.3.3" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#lm_function_mlr"><i class="fa fa-check"></i><b>36.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="36.3.4" data-path="incrementalvalidity.html"><a href="incrementalvalidity.html#apatable_mlr"><i class="fa fa-check"></i><b>36.3.4</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="37" data-path="compensatory.html"><a href="compensatory.html"><i class="fa fa-check"></i><b>37</b> Applying a Compensatory Approach to Selection Decisions Using Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="37.1" data-path="compensatory.html"><a href="compensatory.html#conceptualoverview_compensatory"><i class="fa fa-check"></i><b>37.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="37.1.1" data-path="compensatory.html"><a href="compensatory.html#review_compensatory_mlr"><i class="fa fa-check"></i><b>37.1.1</b> Review of Multiple Linear Regression</a></li>
<li class="chapter" data-level="37.1.2" data-path="compensatory.html"><a href="compensatory.html#review_compensatory"><i class="fa fa-check"></i><b>37.1.2</b> Review of Compensatory Approach</a></li>
</ul></li>
<li class="chapter" data-level="37.2" data-path="compensatory.html"><a href="compensatory.html#tutorial_compensatory"><i class="fa fa-check"></i><b>37.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="37.2.1" data-path="compensatory.html"><a href="compensatory.html#videotutorial_compensatory"><i class="fa fa-check"></i><b>37.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="37.2.2" data-path="compensatory.html"><a href="compensatory.html#function_compensatory"><i class="fa fa-check"></i><b>37.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="37.2.3" data-path="compensatory.html"><a href="compensatory.html#initsteps_compensatory"><i class="fa fa-check"></i><b>37.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="37.2.4" data-path="compensatory.html"><a href="compensatory.html#estimate_compensatory"><i class="fa fa-check"></i><b>37.2.4</b> Estimate Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="37.2.5" data-path="compensatory.html"><a href="compensatory.html#predictcriterionscores_compensatory"><i class="fa fa-check"></i><b>37.2.5</b> Predict Criterion Scores</a></li>
<li class="chapter" data-level="37.2.6" data-path="compensatory.html"><a href="compensatory.html#summary_compensatory"><i class="fa fa-check"></i><b>37.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="37.3" data-path="compensatory.html"><a href="compensatory.html#compensatory_supplement"><i class="fa fa-check"></i><b>37.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="37.3.1" data-path="compensatory.html"><a href="compensatory.html#compensatory_supplement_functions"><i class="fa fa-check"></i><b>37.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="37.3.2" data-path="compensatory.html"><a href="compensatory.html#compensatory_initsteps_supplement"><i class="fa fa-check"></i><b>37.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="37.3.3" data-path="compensatory.html"><a href="compensatory.html#lm_predict_functions_compensatory"><i class="fa fa-check"></i><b>37.3.3</b> <code>lm</code> &amp; <code>predict</code> Functions from Base R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="38" data-path="multiplecutoff.html"><a href="multiplecutoff.html"><i class="fa fa-check"></i><b>38</b> Applying a Noncompensatory Approach to Selection Decisions Using Angoff Method</a>
<ul>
<li class="chapter" data-level="38.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#conceptualoverview_multiplecutoff"><i class="fa fa-check"></i><b>38.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="38.1.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#review_multiplecutoff"><i class="fa fa-check"></i><b>38.1.1</b> Review of Noncompensatory Approach</a></li>
</ul></li>
<li class="chapter" data-level="38.2" data-path="multiplecutoff.html"><a href="multiplecutoff.html#tutorial_multiplecutoff"><i class="fa fa-check"></i><b>38.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="38.2.1" data-path="multiplecutoff.html"><a href="multiplecutoff.html#function_multiplecutoff"><i class="fa fa-check"></i><b>38.2.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="38.2.2" data-path="multiplecutoff.html"><a href="multiplecutoff.html#initsteps_multiplecutoff"><i class="fa fa-check"></i><b>38.2.2</b> Initial Steps</a></li>
<li class="chapter" data-level="38.2.3" data-path="multiplecutoff.html"><a href="multiplecutoff.html#createcutoffscores_multiplecutoff"><i class="fa fa-check"></i><b>38.2.3</b> Create Cutoff Scores</a></li>
<li class="chapter" data-level="38.2.4" data-path="multiplecutoff.html"><a href="multiplecutoff.html#applycutoffscores_multiplecutoff"><i class="fa fa-check"></i><b>38.2.4</b> Apply Cutoff Scores to Make Selection Decisions</a></li>
<li class="chapter" data-level="38.2.5" data-path="multiplecutoff.html"><a href="multiplecutoff.html#summary_multiplecutoff"><i class="fa fa-check"></i><b>38.2.5</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="39" data-path="differentialprediction.html"><a href="differentialprediction.html"><i class="fa fa-check"></i><b>39</b> Testing for Differential Prediction Using Moderated Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="39.1" data-path="differentialprediction.html"><a href="differentialprediction.html#conceptualoverview_differentialprediction"><i class="fa fa-check"></i><b>39.1</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="39.1.1" data-path="differentialprediction.html"><a href="differentialprediction.html#review_mmlr"><i class="fa fa-check"></i><b>39.1.1</b> Review of Moderated Multiple Linear Regression</a></li>
<li class="chapter" data-level="39.1.2" data-path="differentialprediction.html"><a href="differentialprediction.html#review_differentialprediction"><i class="fa fa-check"></i><b>39.1.2</b> Review of Differential Prediction</a></li>
</ul></li>
<li class="chapter" data-level="39.2" data-path="differentialprediction.html"><a href="differentialprediction.html#tutorial_differentialprediction"><i class="fa fa-check"></i><b>39.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="39.2.1" data-path="differentialprediction.html"><a href="differentialprediction.html#videotutorial_differentialprediction"><i class="fa fa-check"></i><b>39.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="39.2.2" data-path="differentialprediction.html"><a href="differentialprediction.html#function_mmlr"><i class="fa fa-check"></i><b>39.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="39.2.3" data-path="differentialprediction.html"><a href="differentialprediction.html#initsteps_mmlr"><i class="fa fa-check"></i><b>39.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="39.2.4" data-path="differentialprediction.html"><a href="differentialprediction.html#center_mmlr"><i class="fa fa-check"></i><b>39.2.4</b> Grand-Mean Center Continuous Predictor Variables</a></li>
<li class="chapter" data-level="39.2.5" data-path="differentialprediction.html"><a href="differentialprediction.html#estimate_mmlr"><i class="fa fa-check"></i><b>39.2.5</b> Estimate Moderated Multiple Linear Regression Model</a></li>
<li class="chapter" data-level="39.2.6" data-path="differentialprediction.html"><a href="differentialprediction.html#summary_differentialprediction"><i class="fa fa-check"></i><b>39.2.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="39.3" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_supplement"><i class="fa fa-check"></i><b>39.3</b> Chapter Supplement</a>
<ul>
<li class="chapter" data-level="39.3.1" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_supplement_functions"><i class="fa fa-check"></i><b>39.3.1</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="39.3.2" data-path="differentialprediction.html"><a href="differentialprediction.html#differentialprediction_initsteps_supplement"><i class="fa fa-check"></i><b>39.3.2</b> Initial Steps</a></li>
<li class="chapter" data-level="39.3.3" data-path="differentialprediction.html"><a href="differentialprediction.html#lm_function_mmlr"><i class="fa fa-check"></i><b>39.3.3</b> <code>lm</code> Function from Base R</a></li>
<li class="chapter" data-level="39.3.4" data-path="differentialprediction.html"><a href="differentialprediction.html#apatable_mmlr"><i class="fa fa-check"></i><b>39.3.4</b> APA-Style Results Table</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V Employee Separation &amp; Retention</b></span></li>
<li class="chapter" data-level="40" data-path="turnover.html"><a href="turnover.html"><i class="fa fa-check"></i><b>40</b> Introduction to Employee Separation &amp; Retention</a></li>
<li class="chapter" data-level="41" data-path="turnoverrate.html"><a href="turnoverrate.html"><i class="fa fa-check"></i><b>41</b> Computing Monthly &amp; Annual Turnover Rates</a>
<ul>
<li class="chapter" data-level="41.1" data-path="turnoverrate.html"><a href="turnoverrate.html#conceptualoverview_turnoverrate"><i class="fa fa-check"></i><b>41.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="41.2" data-path="turnoverrate.html"><a href="turnoverrate.html#tutorial_turnoverrate"><i class="fa fa-check"></i><b>41.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="41.2.1" data-path="turnoverrate.html"><a href="turnoverrate.html#videotutorial_turnoverrate"><i class="fa fa-check"></i><b>41.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="41.2.2" data-path="turnoverrate.html"><a href="turnoverrate.html#functions_turnoverrate"><i class="fa fa-check"></i><b>41.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="41.2.3" data-path="turnoverrate.html"><a href="turnoverrate.html#initsteps_turnoverrate"><i class="fa fa-check"></i><b>41.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="41.2.4" data-path="turnoverrate.html"><a href="turnoverrate.html#turnoverrate_monthlyturnoverrate"><i class="fa fa-check"></i><b>41.2.4</b> Compute Monthly Turnover Rates</a></li>
<li class="chapter" data-level="41.2.5" data-path="turnoverrate.html"><a href="turnoverrate.html#turnoverrate_annualturnoverrate"><i class="fa fa-check"></i><b>41.2.5</b> Compute Annual Turnover Rate</a></li>
<li class="chapter" data-level="41.2.6" data-path="turnoverrate.html"><a href="turnoverrate.html#summary_turnoverrate"><i class="fa fa-check"></i><b>41.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="42" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html"><i class="fa fa-check"></i><b>42</b> Estimating Association Between Two Categorical Variables Using Chi-Square (<span class="math inline">\(\chi^2\)</span>) Test of Independence</a>
<ul>
<li class="chapter" data-level="42.1" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#conceptualoverview_turnoverchisquare"><i class="fa fa-check"></i><b>42.1</b> Conceptual Overview</a></li>
<li class="chapter" data-level="42.2" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#tutorial_turnoverchisquare"><i class="fa fa-check"></i><b>42.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="42.2.1" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#videotutorial_turnoverchisquare"><i class="fa fa-check"></i><b>42.2.1</b> Video Tutorial</a></li>
<li class="chapter" data-level="42.2.2" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#functions_turnoverchisquare"><i class="fa fa-check"></i><b>42.2.2</b> Functions &amp; Packages Introduced</a></li>
<li class="chapter" data-level="42.2.3" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#initsteps_turnoverchisquare"><i class="fa fa-check"></i><b>42.2.3</b> Initial Steps</a></li>
<li class="chapter" data-level="42.2.4" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#turnoverchisquare_contingencytable"><i class="fa fa-check"></i><b>42.2.4</b> Create a Contingency Table for Observed Data</a></li>
<li class="chapter" data-level="42.2.5" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#turnoverchisquare_chisquare"><i class="fa fa-check"></i><b>42.2.5</b> Estimate Chi-Square (<span class="math inline">\(\chi^2\)</span>) Test of Independence</a></li>
<li class="chapter" data-level="42.2.6" data-path="turnoverchisquare.html"><a href="turnoverchisquare.html#summary_turnoverchisquare"><i class="fa fa-check"></i><b>42.2.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VI Odds &amp; Ends</b></span></li>
<li class="chapter" data-level="43" data-path="literature-search-review.html"><a href="literature-search-review.html"><i class="fa fa-check"></i><b>43</b> Conducting a Literature Search &amp; Review</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for HR:<br />
<em>An Introduction to Human Resource Analytics Using R</em><br />
BOOK UNDER CONSTRUCTION</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="turnoverchisquare" class="section level1" number="42">
<h1><span class="header-section-number">Chapter 42</span> Estimating Association Between Two Categorical Variables Using Chi-Square (<span class="math inline">\(\chi^2\)</span>) Test of Independence</h1>
<p>In this chapter, we will learn how to estimate whether theoretically or practically relevant categorical (nominal, ordinal) variables are associated with employees’ decisions to voluntarily turn over. In doing so, we will learn how to estimate the chi-square (<span class="math inline">\(\chi^2\)</span>) test of independence. In a <a href="disparateimpact.html#disparateimpact">previous chapter</a>, we learned how to apply the <span class="math inline">\(\chi^2\)</span> test of independence to determine whether there was evidence of disparate impact.</p>
<div id="conceptualoverview_turnoverchisquare" class="section level2" number="42.1">
<h2><span class="header-section-number">42.1</span> Conceptual Overview</h2>
<p>A <strong>chi-square (<span class="math inline">\(\chi^2\)</span>) test of independence</strong> is a type of categorical nonparametric statistical analysis that can be used to estimate the association between two categorical (nominal, ordinal) variables. As a reminder, categorical variables do not have inherent numeric values, and thus we often just describe how many cases belong to each category (i.e., counts, frequencies). It is very common to represent the association between two categorical variables as a contingency table, which is often referred to as a cross-tabulation. A <span class="math inline">\(\chi^2\)</span> test of independence is calculated by comparing the <strong>observed data</strong> in the contingency table (i.e., what we actually found in the sample) to a model in which the variables and data in another table are distributed to be independent of one another (i.e., <strong>expected data</strong>); there are other types of expected models, but we will focus on just an independent model in this review.</p>
<div class="figure">
<img src="chisquare_observed.png" alt="" />
<p class="caption">The <strong>observed data</strong> includes the raw counts (i.e., frequencies) from the sample. The row and column marginals represent the sums of each row and column, respectively.</p>
</div>
<div class="figure">
<img src="chisquare_expected.png" alt="" />
<p class="caption">The <strong>expected data</strong> includes the counts (i.e., frequencies) that would be expected if the two categorical variables were independent of one another (i.e., not associated). The expected values for each cell are calculated by multiplying the corresponding row and column marginals and dividing that product by the total sample size.</p>
</div>
<p>In essence, a <span class="math inline">\(\chi^2\)</span> test of independence is used to test the null hypothesis that the two categorical variables are independent of one another (i.e., no association between them). If we reject the null hypothesis because the <span class="math inline">\(\chi^2\)</span> value relative to the degrees of freedom of the model is large enough, we conclude that the categorical variables are not in fact independent of one another but instead are contingent upon one another. In this chapter, we will focus specifically on a 2x2 <span class="math inline">\(\chi^2\)</span> test, which refers to the fact there are two categorical variables with two levels each (e.g., age: old vs. young; height: tall vs. short). As an added bonus, a 2x2 <span class="math inline">\(\chi^2\)</span> value can be converted to a phi (<span class="math inline">\(\phi\)</span>) coefficient, which can be interpreted as a Pearson product-moment correlation and thus as an effect size or indicator of practical significance.</p>
<p>The formula for calculating <span class="math inline">\(\chi^2\)</span> is as follows:</p>
<p><span class="math inline">\(\chi^2 = \sum_{i = 1}^{n} \frac{(O_i - E_i)^2}{E_i}\)</span></p>
<p>where <span class="math inline">\(O_i\)</span> refers to the observed values and <span class="math inline">\(E_i\)</span> refers to expected values.</p>
<p>The degrees of freedom (<span class="math inline">\(df\)</span>) of a <span class="math inline">\(\chi^2\)</span> test is equal to the product of the number of levels of the first variable minus one and the number of levels of the second variable minus one. For example, a 2x2 <span class="math inline">\(\chi^2\)</span> test has 1 <span class="math inline">\(df\)</span>: <span class="math inline">\((2-1)(2-1) = 1\)</span></p>
<div id="statisticalassumptions_turnoverchisquare" class="section level4" number="42.1.0.1">
<h4><span class="header-section-number">42.1.0.1</span> Statistical Assumptions</h4>
<p>The statistical assumptions that should be met prior to running and/or interpreting a Pearson product-moment correlation include:</p>
<ul>
<li>Cases are randomly sampled from the population, such that the variable scores for one individual are independent of the variable scores of another individual;</li>
<li>The nonoccurrences are included, where nonoccurrences refer to the instances in which an event or category does not occur. For example, when we investigate employee voluntary turnover, we often like to focus on the turnover event occurrences (i.e., quitting), but we also need to include nonoccurrences, which would be examples of the turnover event <em>not</em> occurring (i.e., staying). Failure to do so, could lead to misleading results.</li>
</ul>
</div>
<div id="statisticalsignficance_turnoverchisquare" class="section level4" number="42.1.0.2">
<h4><span class="header-section-number">42.1.0.2</span> Statistical Significance</h4>
<p>Using null hypothesis significance testing (NHST), we interpret a <em>p</em>-value that is less than .05 (or whatever two- or one-tailed alpha level we set) to meet the standard for statistical significance, meaning we reject the null hypothesis that the variables are independent. If the <em>p</em>-value associated with <span class="math inline">\(\chi^2\)</span> value is equal to or greater than .05 (or whatever two- or one-tailed alpha level we set), then we fail to reject the null hypothesis that the categorical variables are independent. Put differently, if the <em>p</em>-value associated with a <span class="math inline">\(\chi^2\)</span> value is equal to or greater than .05, we conclude that there is no association between the predictor variable and the outcome variable in the population.</p>
<p>If we were to calculate the test by hand, then we might compare our calculated <span class="math inline">\(\chi^2\)</span> value to a table of critical values for a <span class="math inline">\(\chi^2\)</span> distribution. If our calculated value were larger than the critical value given the number of degrees of freedom (<em>df</em>) and the desired alpha level (i.e., significance level cutoff for p-value), we would conclude that there is evidence of an association between the categorical variables. <a href="https://davidmlane.com/hyperstat/chi_square_table.html">Here is a website</a> that lists critical values. Alternatively, we can calculate the exact <em>p</em>-value using statistical software if we know the exact <span class="math inline">\(\chi^2\)</span> value and the <em>df</em>, and most software programs compute the exact <em>p</em>-value automatically when estimating the <span class="math inline">\(\chi^2\)</span> test of independence.</p>
</div>
<div id="practicalsignficance_turnoverchisquare" class="section level4" number="42.1.0.3">
<h4><span class="header-section-number">42.1.0.3</span> Practical Significance</h4>
<p>By itself, the <span class="math inline">\(\chi^2\)</span> value is not an effect size; however, in the special case of a 2x2 <span class="math inline">\(\chi^2\)</span> test of independence, we can compute a phi (<span class="math inline">\(\phi\)</span>) coefficient, which can be interpreted as a Pearson product-moment correlation and thus as an effect size or indicator of practical significance. The size of a <span class="math inline">\(\phi\)</span> coefficient can be described using qualitative labels, such as small, medium, and large. The quantitative values tied to such qualitative labels of magnitude should really be treated as context specific; with that said, there are some very general rules we can apply when interpreting the magnitude of correlation coefficients, which are presented in the table below <span class="citation">(<a href="references.html#ref-cohen1992power" role="doc-biblioref">Cohen 1992</a>)</span>. Please note that the <span class="math inline">\(\phi\)</span> values in the table are absolute values, which means, for example, that correlation coefficients of .50 and -.50 would both have the same absolute value and thus would both be considered large.</p>
<table>
<thead>
<tr class="header">
<th><span class="math inline">\(\phi\)</span></th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.10</td>
<td>Small</td>
</tr>
<tr class="even">
<td>.30</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td>.50</td>
<td>Large</td>
</tr>
</tbody>
</table>
<p><em>Note: Typically, we only interpret the practical significance of an effect if the effect was found to be statistically significant. The logic is that if an effect (e.g., association, difference) is not statistically significant, then we should treat it as no different than zero, and thus it wouldn’t make sense to the interpret the size of something that statistically has no effect.</em></p>
</div>
<div id="samplewriteup_turnoverchisquare" class="section level4" number="42.1.0.4">
<h4><span class="header-section-number">42.1.0.4</span> Sample Write-Up</h4>
<p>Our organization created a new onboarding program a year ago. Today (a year later), we wish to investigate whether participating in the new vs. old onboarding program is associated with employees decisions to quit the organization for the subsequent six months. Based on a sample of 100 newcomers (<em>N</em> = 100) – half of whom went through the new onboarding program and half of whom went through the old onboarding program – we estimated a 2x2 chi-square (<span class="math inline">\(\chi^2\)</span>) test of independence. The <span class="math inline">\(\chi^2\)</span> test of independence was statistically significant (<span class="math inline">\(\chi^2\)</span> = 7.84, <em>df</em> = 1, <em>p</em> = .04), such that those who participated in the new onboarding program were less likely to quit in their first year.</p>
<p><em>Note: If the p-value were equal to or greater than our alpha level (e.g., .05, two-tailed), then we would typically state that the association between the two variables is not statistically significant, and we would not proceed forward with interpreting the effect size (i.e., level of practical significance) because the test of statistical significance indicates that it is very unlikely based on our sample that a true association between these two variables exists in the population.</em></p>
</div>
</div>
<div id="tutorial_turnoverchisquare" class="section level2" number="42.2">
<h2><span class="header-section-number">42.2</span> Tutorial</h2>
<p>This chapter’s tutorial demonstrates how a chi-square test of independence can be used to identify whether an association exists between a categorical (nominal, ordinal) variable and dichotomous turnover decisions (i.e., stay vs. quit).</p>
<div id="videotutorial_turnoverchisquare" class="section level3" number="42.2.1">
<h3><span class="header-section-number">42.2.1</span> Video Tutorial</h3>
<p>As usual, you have the choice to follow along with the written tutorial in this chapter or to watch the video tutorial below.</p>
<iframe src="https://youtube.com/embed/l8v3kx6zNuQ?rel=0" width="672" height="400px">
</iframe>
<p>Link to video tutorial: <a href="https://youtu.be/l8v3kx6zNuQ" class="uri">https://youtu.be/l8v3kx6zNuQ</a></p>
</div>
<div id="functions_turnoverchisquare" class="section level3" number="42.2.2">
<h3><span class="header-section-number">42.2.2</span> Functions &amp; Packages Introduced</h3>
<table>
<thead>
<tr class="header">
<th>Function</th>
<th>Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>xtabs</code></td>
<td>base R</td>
</tr>
<tr class="even">
<td><code>print</code></td>
<td>base R</td>
</tr>
<tr class="odd">
<td><code>xtabs</code></td>
<td>base R</td>
</tr>
<tr class="even">
<td><code>chisq.test</code></td>
<td>base R</td>
</tr>
<tr class="odd">
<td><code>prop.table</code></td>
<td>base R</td>
</tr>
<tr class="even">
<td><code>phi</code></td>
<td><code>psych</code></td>
</tr>
</tbody>
</table>
</div>
<div id="initsteps_turnoverchisquare" class="section level3" number="42.2.3">
<h3><span class="header-section-number">42.2.3</span> Initial Steps</h3>
<p>If you haven’t already, save the file called <strong>“ChiSquareTurnover.csv”</strong> into a folder that you will subsequently set as your working directory. Your working directory will likely be different than the one shown below (i.e., <code>"H:/RWorkshop"</code>). As a reminder, you can access all of the data files referenced in this book by downloading them as a compressed (zipped) folder from the my GitHub site: <a href="https://github.com/davidcaughlin/R-Tutorial-Data-Files" class="uri">https://github.com/davidcaughlin/R-Tutorial-Data-Files</a>; once you’ve followed the link to GitHub, just click “Code” (or “Download”) followed by “Download ZIP”, which will download all of the data files referenced in this book. For the sake of parsimony, I recommend downloading all of the data files into the same folder on your computer, which will allow you to set that same folder as your working directory for each of the chapters in this book.</p>
<p>Next, using the <code>setwd</code> function, set your working directory to the folder in which you saved the data file for this chapter. Alternatively, you can manually set your working directory folder in your drop-down menus by going to <em>Session &gt; Set Working Directory &gt; Choose Directory…</em>. Be sure to create a new R script file (.R) or update an existing R script file so that you can save your script and annotations. If you need refreshers on how to set your working directory and how to create and save an R script, please refer to <a href="setwd.html#setwd">Setting a Working Directory</a> and <a href="gettingstarted.html#createRscript">Creating &amp; Saving an R Script</a>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="turnoverchisquare.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your working directory</span></span>
<span id="cb1-2"><a href="turnoverchisquare.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;H:/RWorkshop&quot;</span>)</span></code></pre></div>
<p>Next, read in the .csv data file called <strong>“ChiSquareTurnover.csv”</strong> using your choice of read function. In this example, I use the <code>read_csv</code> function from the <code>readr</code> package <span class="citation">(<a href="references.html#ref-R-readr" role="doc-biblioref">Wickham and Hester 2020</a>)</span>. If you choose to use the <code>read_csv</code> function, be sure that you have installed and accessed the <code>readr</code> package using the <code>install.packages</code> and <code>library</code> functions. <em>Note: You don’t need to install a package every time you wish to access it; in general, I would recommend updating a package installation once ever 1-3 months.</em> For refreshers on installing packages and reading data into R, please refer to <a href="gentleintro.html#packages">Packages</a> and <a href="#read">Reading Data into R</a>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="turnoverchisquare.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install readr package if you haven&#39;t already</span></span>
<span id="cb2-2"><a href="turnoverchisquare.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Note: You don&#39;t need to install a package every </span></span>
<span id="cb2-3"><a href="turnoverchisquare.html#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># time you wish to access it]</span></span>
<span id="cb2-4"><a href="turnoverchisquare.html#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;readr&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="turnoverchisquare.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access readr package</span></span>
<span id="cb3-2"><a href="turnoverchisquare.html#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb3-3"><a href="turnoverchisquare.html#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="turnoverchisquare.html#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data and name data frame (tibble) object</span></span>
<span id="cb3-5"><a href="turnoverchisquare.html#cb3-5" aria-hidden="true" tabindex="-1"></a>cst <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;ChiSquareTurnover.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## -- Column specification ---------------------------------------------------------------------------------------------------
## cols(
##   EmployeeID = col_character(),
##   Onboarding = col_character(),
##   Turnover = col_character()
## )</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="turnoverchisquare.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the names of the variables in the data frame (tibble) object</span></span>
<span id="cb5-2"><a href="turnoverchisquare.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cst)</span></code></pre></div>
<pre><code>## [1] &quot;EmployeeID&quot; &quot;Onboarding&quot; &quot;Turnover&quot;</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="turnoverchisquare.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print number of rows in data frame (tibble) object</span></span>
<span id="cb7-2"><a href="turnoverchisquare.html#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(cst)</span></code></pre></div>
<pre><code>## [1] 75</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="turnoverchisquare.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print structure of data frame (tibble) object</span></span>
<span id="cb9-2"><a href="turnoverchisquare.html#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(cst)</span></code></pre></div>
<pre><code>## spec_tbl_df[,3] [75 x 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ EmployeeID: chr [1:75] &quot;E1&quot; &quot;E2&quot; &quot;E3&quot; &quot;E8&quot; ...
##  $ Onboarding: chr [1:75] &quot;No&quot; &quot;No&quot; &quot;No&quot; &quot;No&quot; ...
##  $ Turnover  : chr [1:75] &quot;Quit&quot; &quot;Quit&quot; &quot;Quit&quot; &quot;Quit&quot; ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   EmployeeID = col_character(),
##   ..   Onboarding = col_character(),
##   ..   Turnover = col_character()
##   .. )</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="turnoverchisquare.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print first 6 rows of data frame (tibble) object</span></span>
<span id="cb11-2"><a href="turnoverchisquare.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cst)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   EmployeeID Onboarding Turnover
##   &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;   
## 1 E1         No         Quit    
## 2 E2         No         Quit    
## 3 E3         No         Quit    
## 4 E8         No         Quit    
## 5 E14        No         Quit    
## 6 E22        No         Quit</code></pre>
<p>There are 3 variables and 75 cases (i.e., employees) in the <code>cst</code> data frame: <code>EmployeeID</code>, <code>Onboarding</code>, and <code>Turnover</code>. Per the output of the <code>str</code> (structure) function above, all of the variables are of type <em>character</em>. <code>EmployeeID</code> is the unique employee identifier variable. <code>Onboarding</code> is a variable that indicates whether new employees participated in the onboarding program, and it has two levels: did not participate (No) and did participate (Yes) <code>Turnover</code> is a variable that indicates whether these individuals left the organization during their first year; it also has two levels: Quit and Stayed.</p>
</div>
<div id="turnoverchisquare_contingencytable" class="section level3" number="42.2.4">
<h3><span class="header-section-number">42.2.4</span> Create a Contingency Table for Observed Data</h3>
<p>Before running the chi-square test, we need to create a contingency (cross-tabulation) table for the <code>Onboarding</code> and <code>Turnover</code> variables. To do so, we will use the <code>xtabs</code> function from base R. In the function parentheses, as the first argument type the <code>~</code> operator followed by the two variables names, separated by the <code>+</code> operator (i.e., <code>~ Onboarding + Turnover</code>). As the second argument, type <code>data=</code> followed by the name of the data frame to which both variables belong (<code>cst</code>). We will use the <code>&lt;-</code> assignment operator to name the table object (<code>tbl</code>). For more information on creating tables, check out the chapter on <a href="crosstabs.html#crosstabs">summarizing two or more categorical variables using cross-tabulations</a>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="turnoverchisquare.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create two-way contingency table</span></span>
<span id="cb13-2"><a href="turnoverchisquare.html#cb13-2" aria-hidden="true" tabindex="-1"></a>tbl <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="sc">~</span> Onboarding <span class="sc">+</span> Turnover, <span class="at">data=</span>cst)</span></code></pre></div>
<p>Let’s print the new <code>tbl</code> object to your Console.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="turnoverchisquare.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print table</span></span>
<span id="cb14-2"><a href="turnoverchisquare.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tbl)</span></code></pre></div>
<pre><code>##           Turnover
## Onboarding Quit Stayed
##        No    16      7
##        Yes    6     46</code></pre>
<p>As you can see, we have created a 2x2 contingency table, as it has two variables (<code>Onboarding</code>, <code>Turnover</code>) with each variable consisting of two levels (i.e., categories). This table includes our <strong>observed data</strong>.</p>
</div>
<div id="turnoverchisquare_chisquare" class="section level3" number="42.2.5">
<h3><span class="header-section-number">42.2.5</span> Estimate Chi-Square (<span class="math inline">\(\chi^2\)</span>) Test of Independence</h3>
<p>Using the contingency table we created called <code>tbl</code>, we will insert it as the sole parenthetical argument in the <code>chisq.test</code> function from base R.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="turnoverchisquare.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate chi-square test of independence</span></span>
<span id="cb16-2"><a href="turnoverchisquare.html#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tbl)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  tbl
## X-squared = 23.179, df = 1, p-value = 0.000001476</code></pre>
<p>In the output, note that the <span class="math inline">\(\chi^2\)</span> value is 23.179 with 1 degree of freedom (<em>df</em>), and the associated <em>p</em>-value is less than .05, leading us to reject the null hypothesis that these two variables are independent of one another (<span class="math inline">\(\chi^2\)</span> = 23.176, <em>df</em> = 1, <em>p</em> &lt; .001). In other words, we have concluded that there is a statistically significant association between onboarding participation and whether someone quits in the first year.</p>
<p>To understand the nature of this association, we need to look back to the contingency table values. In fact, sometimes it is helpful to look at the column (or row) proportions by applying the <code>prop.table</code> function from base R to the <code>tbl</code> object we created. As the second argument, type the numeral 2 to request the column marginal proportions.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="turnoverchisquare.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print column marginal proportions</span></span>
<span id="cb18-2"><a href="turnoverchisquare.html#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(tbl, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##           Turnover
## Onboarding      Quit    Stayed
##        No  0.7272727 0.1320755
##        Yes 0.2727273 0.8679245</code></pre>
<p>As you can see from the contingency table, of those employees who stayed, proportionally more employees had participated in the onboarding program (86.8%). Alternatively, for those who quit, proportionally more employees did <em>not</em> participate in the onboarding program (72.7%). Given our interpretation of the table along with the significant <span class="math inline">\(\chi^2\)</span> test, we can conclude that employees were significantly more likely to stay through the end of their first year if they participated in the onboarding program.</p>
<p>In the special case of a 2x2 contingency table (or a 1x4 vector), we can compute a phi (<span class="math inline">\(\phi\)</span>) coefficient, which can be interpreted like a Pearson product-moment correlation coefficient and thus as an effect size. To calculate the phi coefficient, we will use the <code>phi</code> function from the <code>psych</code> package. If you haven’t already, install and access the <code>psych</code> package.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="turnoverchisquare.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install package</span></span>
<span id="cb20-2"><a href="turnoverchisquare.html#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;psych&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="turnoverchisquare.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access package</span></span>
<span id="cb21-2"><a href="turnoverchisquare.html#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code></pre></div>
<p>Within the <code>phi</code> function parentheses, insert the name of the 2x2 contingency table object (<code>tbl</code>) as the sole argument.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="turnoverchisquare.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate phi coefficient</span></span>
<span id="cb22-2"><a href="turnoverchisquare.html#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">phi</span>(tbl)</span></code></pre></div>
<pre><code>## [1] 0.587685</code></pre>
<p>The <span class="math inline">\(\phi\)</span> coefficient for the association between <code>Onboarding</code> and <code>Turnover</code> is .59, which by conventional correlation standards is a large effect (<span class="math inline">\(\phi\)</span> = .59). Here is a table containing conventional rules of thumb for interpreting a Pearson correlation coefficient (<em>r</em>) or a phi coefficient (<span class="math inline">\(\phi\)</span>) as an effect size:</p>
<table>
<thead>
<tr class="header">
<th><span class="math inline">\(\phi\)</span></th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.10</td>
<td>Small</td>
</tr>
<tr class="even">
<td>.30</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td>.50</td>
<td>Large</td>
</tr>
</tbody>
</table>
<p><strong>Technical Write-Up:</strong> Based on a sample of 75 employees, we investigated whether participating in an onboarding program was associated with new employees’ decisions to quit in the first 12 months. Using a chi-square (<span class="math inline">\(\chi^2\)</span>) test of independence, we found that new employees who participated in the onboarding program were less likely to quit during their first 12 months on the job (<span class="math inline">\(\chi^2\)</span> = 23.176, <em>df</em> = 1, <em>p</em> &lt; .001). Specifically, of those employees who stayed at the organization, proportionally more employees had participated in the onboarding program (86.8%), and of those employees who quit the organization, proportionally more employees did <em>not</em> participate in the onboarding program (72.7%). The magnitude of this effect can be described as large (<span class="math inline">\(\phi\)</span> = .59).</p>
<div id="turnoverchisquare_observedexpected" class="section level4" number="42.2.5.1">
<h4><span class="header-section-number">42.2.5.1</span> Optional: Print Observed and Expected Counts</h4>
<p>In some instances, it might be helpful to view the observed and expected, as these are the basis for estimating the <span class="math inline">\(\chi^2\)</span> test of independence. First, we need to create an object that contains the information from the <code>chisq.test</code> function. Using the <code>&lt;-</code> assignment operator, let’s name this object <code>chisq</code>.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="turnoverchisquare.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create chi-square object</span></span>
<span id="cb24-2"><a href="turnoverchisquare.html#cb24-2" aria-hidden="true" tabindex="-1"></a>chisq <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(tbl)</span></code></pre></div>
<p>We can request the <em>observed</em> counts/frequencies by typing the name of the <code>chisq</code> object, followed by the <code>$</code> operator and <code>observed</code>. These will look familiar because they are the counts from our original contingency table.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="turnoverchisquare.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Request observed counts/frequencies</span></span>
<span id="cb25-2"><a href="turnoverchisquare.html#cb25-2" aria-hidden="true" tabindex="-1"></a>chisq<span class="sc">$</span>observed</span></code></pre></div>
<pre><code>##           Turnover
## Onboarding Quit Stayed
##        No    16      7
##        Yes    6     46</code></pre>
<p>To request the <em>expected</em> counts/frequencies, type the name of the <code>chisq</code> object, followed by the <code>$</code> operator and <code>expected</code>.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="turnoverchisquare.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Request expected counts/frequencies</span></span>
<span id="cb27-2"><a href="turnoverchisquare.html#cb27-2" aria-hidden="true" tabindex="-1"></a>chisq<span class="sc">$</span>expected</span></code></pre></div>
<pre><code>##           Turnover
## Onboarding      Quit   Stayed
##        No   6.746667 16.25333
##        Yes 15.253333 36.74667</code></pre>
<p>We can descriptively see departures from the observed and expected values in a systematic manner.</p>
<p>To understand which cells were most influential in the calculation of the <span class="math inline">\(\chi^2\)</span> value, it is straightforward to request the Pearson residuals. Pearson residuals with larger absolute values have bigger contributions to the <span class="math inline">\(\chi^2\)</span> value.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="turnoverchisquare.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Request Pearson residuals</span></span>
<span id="cb29-2"><a href="turnoverchisquare.html#cb29-2" aria-hidden="true" tabindex="-1"></a>chisq<span class="sc">$</span>residuals</span></code></pre></div>
<pre><code>##           Turnover
## Onboarding      Quit    Stayed
##        No   3.562489 -2.295234
##        Yes -2.369277  1.526473</code></pre>
</div>
</div>
<div id="summary_turnoverchisquare" class="section level3" number="42.2.6">
<h3><span class="header-section-number">42.2.6</span> Summary</h3>
<p>In this chapter, we learned how to estimate a chi-square (<span class="math inline">\(\chi^2\)</span>) test of independence using the <code>chisq.test</code> function from base R.</p>

</div>
</div>
</div>



<div id="identify-a-content-area-or-context-that-excites-you." class="section level4 unnumbered">
<h4>Identify a content area or context that excites you.</h4>
</div>
<div id="identify-an-area-of-data-analytics-that-excites-you." class="section level4 unnumbered">
<h4>Identify an area of data analytics that excites you.</h4>
</div>
<div id="figure-out-what-knowledge-skills-abilities-your-ideal-employer-wants-or-what-it-needs-but-doesnt-yet-realize-it-needs." class="section level4 unnumbered">
<h4>Figure out what knowledge, skills, abilities your ideal employer wants – or what it needs but doesn’t yet realize it needs.</h4>
</div>
<div id="decide-whether-you-want-your-portfolio-to-teach-showcase-or-do-both." class="section level4 unnumbered">
<h4>Decide whether you want your portfolio to teach, showcase, or do both.</h4>
</div>
<div id="find-an-appropriate-dataset." class="section level4 unnumbered">
<h4>Find an appropriate dataset.</h4>
</div>
<div id="create-an-immersive-environment-for-the-intended-audience." class="section level4 unnumbered">
<h4>Create an immersive environment for the intended audience.</h4>
</div>
<div id="articulate-a-clear-problem-question-that-can-be-solved-answered-with-the-available-data." class="section level4 unnumbered">
<h4>Articulate a clear problem (question) that can be solved (answered) with the available data.</h4>
</div>
<div id="write-and-annotate-your-code-with-an-emphasis-on-clarity." class="section level4 unnumbered">
<h4>Write (and annotate) your code with an emphasis on clarity.</h4>
</div>
<div id="if-your-portfolio-project-includes-data-analysis-or-visualization-make-sure-that-youve-chosen-an-appropriate-analysis-or-visualization-given-the-problemquestion-and-available-data." class="section level4 unnumbered">
<h4>If your portfolio project includes data analysis or visualization, make sure that you’ve chosen an appropriate analysis or visualization given the problem/question and available data.</h4>
</div>
<div id="focus-on-good-storytelling." class="section level4 unnumbered">
<h4>Focus on good storytelling.</h4>
</div>
<div id="solicit-friendly-feedback-prior-to-sharing-your-portfolio-with-an-employer." class="section level4 unnumbered">
<h4>Solicit friendly feedback prior to sharing your portfolio with an employer.</h4>
</div>
<div id="select-a-platform-that-will-allow-you-to-share-your-portfolio." class="section level4 unnumbered">
<h4>Select a platform that will allow you to share your portfolio.</h4>
</div>
<div id="update-your-portfolio-regularly." class="section level4 unnumbered">
<h4>Update your portfolio regularly.</h4>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="turnoverrate.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="literature-search-review.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
